### ISSUE TITLE
Latte's new logo

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#1]
a new place to discuss development steps...

**Comment by varlesh** [comment]
I see you mail message, Michail.
 Ok, i'm create some samples icons for Latte-Dock. But maybe latter, because now holidays :)

**Comment by psifidotos** [comment]
@varlesh 

>Ok, i'm create some samples icons for Latte-Dock. But maybe latter, because now holidays :)

Thank u very much!!!!!!!!!!!!!! :) 
And thank u again for your contributions for the community!!!

**Comment by psifidotos** [comment]
merry Christmas to everyone!!!

![image](https://cloud.githubusercontent.com/assets/2216474/21471293/b39e8b28-cab5-11e6-9669-670676d98b25.png)

**Comment by varlesh** [comment]
See this:
[latte-dock.zip](https://github.com/psifidotos/Latte-Dock/files/672209/latte-dock.zip)

**Comment by psifidotos** [comment]
fantastic work!! I fansy I think 1 or 2 (with 2 gaining more points... :) ) ,
1 - for the geometrical structure and
2 - for the simplicity

![spectacle h15540](https://cloud.githubusercontent.com/assets/2216474/21471327/3f5b2b34-cab7-11e6-881a-7a77c28d1f39.png)

**Comment by varlesh** [comment]
i like 2 variant too...
Create PR with all sizes?

**Comment by psifidotos** [comment]
i like 2 variant too...
Create PR with all sizes?


We must wait, I am not the only developer... We must wait for more
feedback...

**Comment by varlesh** [comment]
haha, but i'm already create 16px-128px :) You and others can check this:
[latte-dock-16-128.zip](https://github.com/psifidotos/Latte-Dock/files/672230/latte-dock-16-128.zip)

**Comment by varlesh** [comment]
Little modification:
![image](https://cloud.githubusercontent.com/assets/8083855/21471753/3234d350-cad6-11e6-8675-b97c8407b2c2.png)

**Comment by varlesh** [comment]
[latte-dock-ver4.zip](https://github.com/psifidotos/Latte-Dock/files/672241/latte-dock-ver4.zip)

**Comment by psifidotos** [comment]
Looks interesting! 

Alexey, is it possible to add some how the beautiful geometrical structure from dock1? Are you consider it too much detail? 

I am trying to combine somehow 1-2 ... but without being too much in detail... I dont know... I might be crazy...

BTW: I like a lot the 3 dots under **L** they could be a semantic for the dock(its tasks)... ;)

**Comment by varlesh** [comment]
Yes, if icon will be have more details - it's not good looking for smaller sizes. I think better use minimal symbols for logo.
I create yhis how:
L - latte
dots - it's icons :)

**Comment by psifidotos** [comment]
:+1: nice!

**Comment by audoban** [comment]
Sorry for my absence I was asleep.

Hi @varlesh 
I love the 2 concept with **L** is very interesting.

**Comment by varlesh** [comment]
hi @audoban )
What you think about cup-style?
![image](https://cloud.githubusercontent.com/assets/8083855/21472040/56720fd4-cae1-11e6-85e1-bf469a416d0b.png)
Or maybe create icon on breeze style with long shadow?

**Comment by audoban** [comment]
> Yes, if icon will be have more details - it's not good looking for smaller sizes. I think better use minimal symbols for logo.
I create this how:
L - latte
dots - it's icons :)

Yes, Looks good.

**Comment by audoban** [comment]
hi @audoban )
What you think about cup-style?

I like the first proposal, without the cup.

**Comment by audoban** [comment]
@varlesh 
> Or maybe create icon on breeze style with long shadow?
Could you show me?

**Comment by varlesh** [comment]
for example
![image](https://cloud.githubusercontent.com/assets/8083855/21472099/f08da06e-cae2-11e6-97f5-6e8f93526567.png)

**Comment by audoban** [comment]
@varlesh 
Looks very breeze style, I agree with using this for project.

The coup looks better, now that there are fewer details.
@psifidotos What do you think, about breeze version?

**Comment by varlesh** [comment]
Guys, i have to go now :( 
But, you can choose ;) Available 5 variants (i'm recolored some things... )
![image](https://cloud.githubusercontent.com/assets/8083855/21472138/c6c65a58-cae4-11e6-8c19-7144e1fb2957.png)
[latte-dock-5versions.zip](https://github.com/psifidotos/Latte-Dock/files/672267/latte-dock-5versions.zip)

**Comment by audoban** [comment]
@varlesh  ok, not problem. We will decide on today.

**Comment by psifidotos** [comment]
@audoban 

Hello!!
I think that I fancy more:
![image](https://cloud.githubusercontent.com/assets/2216474/21472247/181625e4-cad8-11e6-8fd3-c23ce72aa527.png)


the dark cup I think it lloks like a magnifier so I prefer it with lighter color.
of (2) by adding also the shadow but with no cup

**Comment by audoban** [comment]
@psifidotos Yes, It might look like a magnifier. Let's use breeze style without the cup.

**Comment by psifidotos** [comment]
> Yes, It might look like a magnifier. Let's use breeze style without the cup.

agreed!! :) let;s leave @varlesh to make its magic.... :)

@varlesh "breeze style without the cup" it is!!!! :)

**Comment by varlesh** [comment]
This?
![image](https://cloud.githubusercontent.com/assets/8083855/21473403/2cc33ad6-cb23-11e6-9efb-cd1d6f9675f4.png)

**Comment by audoban** [comment]
@varlesh  Yes, It looks great.

**Comment by varlesh** [comment]
needed other sizes or only 48px? Because Breeze now have only 48px for apps...

**Comment by varlesh** [comment]
i'm modify some colors, because on breeze not like use white for logo
![image](https://cloud.githubusercontent.com/assets/8083855/21473486/ba5a291a-cb26-11e6-937b-3782ecdb98cb.png)

**Comment by audoban** [comment]
@varlesh it's okay, not problem, thank you very much. :)

**Comment by audoban** [comment]
> needed other sizes or only 48px? Because Breeze now have only 48px for apps...?

48 pixels, and the SVG icon.

**Comment by varlesh** [comment]
[latte-dock48breeze.svg.zip](https://github.com/psifidotos/Latte-Dock/files/672386/latte-dock48breeze.svg.zip)

**Comment by varlesh** [comment]
sorry, i'm forgot clean icon...
Now clean version with SVGO:
[latte-dock48breezeclean.svg.zip](https://github.com/psifidotos/Latte-Dock/files/672388/latte-dock48breezeclean.svg.zip)

**Comment by audoban** [comment]
@varlesh thank's a lot. We are very grateful for your work🥇 :)

**Comment by varlesh** [comment]
PNG's 
48px:
![latte-dock48](https://cloud.githubusercontent.com/assets/8083855/21473586/64559a32-cb2a-11e6-9722-661423f4f470.png)

96px:
![latte-dock96](https://cloud.githubusercontent.com/assets/8083855/21473588/77a78596-cb2a-11e6-8b3b-2fca9c478066.png)

192px:
![latte-dock192](https://cloud.githubusercontent.com/assets/8083855/21473592/8b63d012-cb2a-11e6-9c41-72ed5406b6a1.png)

**Comment by varlesh** [comment]
For **L** use Tangerine font:
https://www.fontsquirrel.com/fonts/tangerine
License: SIL Open Font License v1.10
Author: Toshi Omagari

**Comment by varlesh** [comment]
But i'm  modify **L** for pixelated align

**Comment by audoban** [comment]
> For L use Tangerine font:
https://www.fontsquirrel.com/fonts/tangerine
License: SIL Open Font License v1.10
Author: Toshi Omagari

@varlesh  ok. I will add to comments of project.

**Comment by varlesh** [comment]
@psifidotos @audoban Not scarry - used not original font. L - have only source for latte-dock logo
For compare:
![image](https://cloud.githubusercontent.com/assets/8083855/21473704/8e7edf96-cb2d-11e6-9227-5158ae0a86b3.png)

**Comment by audoban** [comment]
@varlesh  then it is not necessary to comment?

**Comment by varlesh** [comment]
i don't know, because it's not original font, but have source for logo...
 [SIL Open Font License v1.10](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) - it's free and open license, maybe you want use this font for banner or other customization

**Comment by audoban** [comment]
> maybe you want use this font for banner or other customization

For now we do not include it elsewhere.

**Comment by varlesh** [comment]
> For now we do not include it elsewhere.

Ok, i think not needed, because it's not original font

**Comment by audoban** [comment]
@varlesh, You have been added to contributions. Thank you :)
[README](https://github.com/psifidotos/Latte-Dock/blob/master/README.md)

**Comment by varlesh** [comment]
@audoban thx )
Sorry, i'm not use KDE now and not know how worked latte dock. 
Dock worked as widget or how application?
If dock use as widget, on breeze also exist applets (preview):
![image](https://cloud.githubusercontent.com/assets/8083855/21473919/6df1e012-cb31-11e6-9e71-3dfc491255f5.png) for this icons used plugin info name.

**Comment by audoban** [comment]
@psifidotos Latte Dock, is now a executable or application. The widget preview image isn't necessary.

**Comment by varlesh** [comment]
> Latte Dock, is now a executable or application. The widget preview image isn't necessary.

wow, it's very cool. I want try this ))

But if you want add widget support i can add widget preview. For example:
![image](https://cloud.githubusercontent.com/assets/8083855/21474016/faff49bc-cb32-11e6-9552-b23b14fdf126.png)

**Comment by audoban** [comment]
@varlesh 
> But if you want add widget support i can add widget preview. For example:

beautiful. If necessary, we will let you know 👍 .

**Comment by psifidotos** [comment]
@varlesh <https://github.com/varlesh>

Fantastic job! This is definetely the designe I also want!!! I have some
small requests if it is possible...

1. a little more contrast from the L and the dots
2. the L and dots should be slighter bigger
3. a 24px version, because of the light design in small versions I am
afraid that L and dots will not be shown properly without specific care...

I hope we have time for the above...

Thank a lot @varlesh !! You are great!!

**Comment by varlesh** [comment]
1. Ok
2. Not possible, because dots have 4px. If change dots to 5px - dots not possible pixelated align (because i can't align dots by center - need even value). 6px - it's very big dots. Also this worked with "L"
3. You need 24px icon? I can draw 24px if you needed

**Comment by varlesh** [comment]
increase logo contrast (rename zip to svg):
[latte-dock.zip](https://github.com/psifidotos/Latte-Dock/files/672727/latte-dock.zip)

**Comment by psifidotos** [comment]
@varlesh 

varlesh very nice!!!! I like it a lot!!!
If Jojan agrees also, we will use that one and we will need also a 24px version... :)

*Question:* as a designer Alexey do you believe that we will need also a 16px versions which is the lowest Latte Dock supports or visually we are ok with the 24px version and the rest?

**Comment by varlesh** [comment]
16-48px:
[latte-final.zip](https://github.com/psifidotos/Latte-Dock/files/672809/latte-final.zip)

**Comment by psifidotos** [comment]
16-48px:
latte-final.zip
<https://github.com/psifidotos/Latte-Dock/files/672809/latte-final.zip>


Thank u!!!!

Please Johan take a look if we are ok because until next weekend I wont
have a computer

**Comment by audoban** [comment]
@psifidotos @varlesh I agree with the final result.

**Comment by psifidotos** [comment]
Nice!!! Now we must include the icon in the installation process :-)

**Comment by varlesh** [comment]
art:
![art](https://cloud.githubusercontent.com/assets/8083855/21497685/29d89208-cc40-11e6-891f-d13b4cdff9b5.png)

**Comment by psifidotos** [comment]
> wow, it's very cool. I want try this ))
> But if you want add widget support i can add widget preview. For example:
image

@varlesh we need a widget preview as we have our own plasmoid. If you find time for us!!!! Our pleasure!!! ;)

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/21521438/5ece5976-cd16-11e6-8180-3888543849b9.png)
rename zip to svg:
[org.kde.latte.containment.zip](https://github.com/psifidotos/Latte-Dock/files/675518/org.kde.latte.containment.zip)

**Comment by psifidotos** [comment]
Thank u !!!

Dont worry about the naming... We are in the process of renaming it...

![latte-plasmoid](https://cloud.githubusercontent.com/assets/2216474/21521937/ee551858-cd09-11e6-8513-79f068d58b13.png)

**Comment by psifidotos** [comment]
@varlesh in Latte there will be an edit mode visual possibly, I currently use a blueprint pattern in the background to indicate that state, do you have any alternative ideas maybe?


![blueprint](https://cloud.githubusercontent.com/assets/2216474/21577280/0bc0b7a2-cf5e-11e6-9c06-c013a1c8d213.png)

**Comment by psifidotos** [comment]
this is how it looks currently... actually I fancy it...

![editmode](https://cloud.githubusercontent.com/assets/2216474/21578126/df232d04-cf7d-11e6-9199-a623eebbd54c.png)
