### ISSUE TITLE
Latte-Dock don't reflect the changes when is mutable.

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#10]
When I open config ui, and I change the position of dock, just I can seen the changes when is immutable.
I don't like this behavior.

**Comment by psifidotos** [comment]
I suppose you mean the alignment.... bottom, center, top, double...

for "bottom,center,top" I aggree this can be fixed. The "double" layout (top and bottom at the same time) is currently broken but will be updated soon, the "double" layout is considered a centered layout in !immutable state with a special icon in it to separate top plasmoids from bottom ones...
