### ISSUE TITLE
Warning spam prevents startup

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#100]
Just now something happened and dock no longer starts. It freezes on startup. Starting it from console i see endless spam of this warning:

	[debug 21:20:35.295295] - "applications:google-chrome.desktop" linked to activities ()
	[debug 21:20:35.295295] - "applications:snapper-gui.desktop" linked to activities ()
	[debug 21:20:35.295295] - "applications:pkgbrowser.desktop" linked to activities ()
	[warning 21:20:35.361361] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
	[warning 21:20:35.361361] - file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/main.qml:78:27: Unable to assign [undefined] to QStringList
	[warning 21:20:35.361361] - file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/main.qml:37: TypeError: Cannot read property 'DateTime' of undefined
	[warning 21:20:35.425425] - file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/DigitalClock.qml:443:5: QML Text: Cannot anchor to a null item.
	[warning 21:20:35.619619] - file:///usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardRepresentation.qml:277:17: QML Heading: Binding loop detected for property "height"
	[warning 21:20:35.688688] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:43: TypeError: Cannot read property 'length' of undefined
	[warning 21:20:35.689689] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:43: TypeError: Cannot read property 'length' of undefined
	[warning 21:20:35.690690] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:43: TypeError: Cannot read property 'length' of undefined
	[warning 21:20:35.690690] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:45:20: Unable to assign [undefined] to QColor
	[warning 21:20:35.777777] - Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/rk/.local/share", "/home/rk/.local/share/flatpak/exports/share", "/var/lib/flatpak/exports/share", "/usr/local/share", "/usr/share")
	[warning 21:20:35.781781] - Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/rk/.local/share", "/home/rk/.local/share/flatpak/exports/share", "/var/lib/flatpak/exports/share", "/usr/local/share", "/usr/share")

It worked minutes ago. I updated to latest master commit - issue is not gone. I found [this](https://github.com/psifidotos/nowdock-panel/issues/42) issue mentioning similar log. The only major thing i changed just now is enabling video wallpaper, however i can not see how it could interfere. Especially since this happens only on my laptop and my main pc with same change did not affect dock. Dock should really give up on errors like this instead of spamming warning in a right loop.

**Comment by psifidotos** [comment]
I dont think is the warning creating this issue... you could test latest master, any messages should appear only if the user sets **--debug** when executing latte

**Comment by psifidotos** [comment]
I think that this is more related to the video wallpaper, something probably with the graphics driver used...

**Comment by rokups** [comment]
Indeed it does not solve the problem, but hidden log is useful. I no longer see spam in `journalctl -f`. Not sure if i should be seeing it though, since dock is now broken. I ruled out video wallpaper because disabling it does not help. I have few custom servies of type `ServiceTypes=KonqPopupMenu/Plugin`, however they are functioning properly and moving `~/.local/share/kservices5` has no effect for this issue. Not sure what else i could try. I am adding more full fragment of log where problem starts to occur. Maybe it will give you better idea on what could be triggering it.

	[debug 21:20:35.295295] - "applications:google-chrome.desktop" linked to activities ()
	[debug 21:20:35.295295] - "applications:snapper-gui.desktop" linked to activities ()
	[debug 21:20:35.295295] - "applications:pkgbrowser.desktop" linked to activities ()
	[warning 21:20:35.361361] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
	[warning 21:20:35.361361] - file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/main.qml:78:27: Unable to assign [undefined] to QStringList
	[warning 21:20:35.361361] - file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/main.qml:37: TypeError: Cannot read property 'DateTime' of undefined
	[warning 21:20:35.425425] - file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/DigitalClock.qml:443:5: QML Text: Cannot anchor to a null item.
	[warning 21:20:35.619619] - file:///usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/ui/DashboardRepresentation.qml:277:17: QML Heading: Binding loop detected for property "height"
	[warning 21:20:35.688688] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:43: TypeError: Cannot read property 'length' of undefined
	[warning 21:20:35.689689] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:43: TypeError: Cannot read property 'length' of undefined
	[warning 21:20:35.690690] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:43: TypeError: Cannot read property 'length' of undefined
	[warning 21:20:35.690690] - file:///usr/share/plasma/plasmoids/org.kde.plasma.systemloadviewer/contents/ui/CompactBarMonitor.qml:45:20: Unable to assign [undefined] to QColor
	[warning 21:20:35.777777] - Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/rk/.local/share", "/home/rk/.local/share/flatpak/exports/share", "/var/lib/flatpak/exports/share", "/usr/local/share", "/usr/share")
	[warning 21:20:35.781781] - Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/rk/.local/share", "/home/rk/.local/share/flatpak/exports/share", "/var/lib/flatpak/exports/share", "/usr/local/share", "/usr/share")

**Comment by psifidotos** [comment]
What qt, plasma and kf5 versions are you using?You could also try to go backwards to commits to see if this was introduced for you by a specific commit or because something changed in your system...

**Comment by psifidotos** [comment]
Is it possible to test also: https://github.com/psifidotos/Latte-Dock/commit/5eb53a2cbc45cf3823f0d242d599221ad03d13c9     ? In order to see if this was working for you and the next one broke it for you?

**Comment by rokups** [comment]
Plasma 5.8.5 / KF 5.3 / Qt 5.7.1. I am on archlinux so versions are latest and greatest ;)

I tested your suggested commit and it turned out to be broken. I then bisected commits and found first bad one to be 7daf0d9169878eaf09dcb3906107b57ee92b72bf.

And then i figured i should try deleting my old config and i found this: [lattedock-appletsrc.tar.gz](https://github.com/psifidotos/Latte-Dock/files/737377/lattedock-appletsrc.tar.gz)

For some reason config file swell to crazy size (300KB). On this very machine i was having these phantom panels as well. That issue was already reported i think, but i cant find it right now. Those phantom panels are like small strip on top-left corner of the screen. Had to right-click > latte settings and remove them. Maybe this is related somehow.

**Comment by psifidotos** [comment]
> For some reason config file swell to crazy size (300KB). On this very machine i was having these phantom panels as well. That issue was already reported i think, but i cant find it right now. Those phantom panels are like small strip on top-left corner of the screen. Had to right-click > latte settings and remove them. Maybe this is related somehow.

the phantom panels were fixed one commit after: https://github.com/psifidotos/Latte-Dock/commit/5eb53a2cbc45cf3823f0d242d599221ad03d13c9

this is why I wanted you to test this commit to see if it works...

-try to delete all the latte applets rc with latest master and then open latte. latte creates by its own the appletsrc on first run, to see if it works, if it doesnt, upload here the,
lattedock-appletsrc file

**Comment by rokups** [comment]
Err sorry, forgot to mention that after deleting that file everything indeed works.

**Comment by psifidotos** [comment]
ok ... no prob then... ;)
