### ISSUE TITLE
[feature request] vertical padding ?

### ISSUE THREAD

**Issue by jmaris** [psifidotos/Latte-Dock#1000]
Hey ! When using a background with latte dock, i've noticed it is only ever as big as the icons contained in it, i'd like it to be a little padded (so there is more space between the icons and the edge of the background). Would it be possible to implement a feature that allows this ?

**Comment by psifidotos** [comment]
I cant understand, provide screenshots please...

**Comment by jmaris** [comment]
Sorry this was unclear
![screenshot_20180420_145623](https://user-images.githubusercontent.com/342289/39052125-39551a28-44ab-11e8-9fbc-aecb4d5a849c.png)

note how the icons totally fill the dock area : there is very little space between the icons and the edge of the dock, vertical padding would be nice to space things out a bit
 (like this) : 

![spaced](https://user-images.githubusercontent.com/342289/39052268-bca9e7a0-44ab-11e8-9623-8c37f5935386.png)

**Comment by psifidotos** [comment]
Is you background size to 100% ?

Have you enabled Tweaks->Shrink thickness margins to minimum?

**Comment by jmaris** [comment]
Yes!  and disabling the Shrink margins thing does considerably improve it ! sorry I missed that setting ! 

Thanks :)

**Comment by jmaris** [comment]
Going to reopen this issue, because padding on top is still relatively low, and others have expressed interest for this feature.
would there not be a way to increase top padding further?

**Comment by psifidotos** [comment]
The top padding is calculated through plasma theme margins.

1. How a plasma panel looks for the same plasma theme, is there any difference?

2. If you use Breeze plasma theme isnt this fixed?

**Comment by psifidotos** [comment]
3. If you are using latte git version there is a trick you can use... Enable applet shadows, set their size to 100% and their transparency to 0%

**Comment by jmaris** [comment]
The shadows trick did it ! Thanks so much :) !
