### ISSUE TITLE
[feature request] Hide titlebar for maximized windows

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#1001]
Sometimes I switch the Latte layout between the `macOS-style/unity-style` layout and the `Plasma-style` layout.

In the macOS-style, I use the `Active Window Control` and turn on the **"Hide titlebar for maximized windows"** setting.

The problem is, the Plasma-style need titlebar for the maximized windows, but after I switched to it from the macOS-style layout, that ACW setting is still applied.

So, could you implement a new tweak that override that setting depending on the Latte layout ?

![image](https://user-images.githubusercontent.com/11857205/39026862-6ee5fefa-4479-11e8-871d-a345a36c0f2e.png)

**Comment by trmdi** [comment]
Here is how the `ACW` widget does it: https://github.com/kotelnik/plasma-applet-active-window-control/blob/a20410a1f0fb9a6fe56e954b603df33aa2143af4/package/contents/ui/config/ConfigAppearance.qml#L38-L40

**Comment by psifidotos** [comment]
Sorry this is AWC responsibility... it should disable that feature on exit or when it is removed.

**Comment by psifidotos** [comment]
How the user will define for which layouts this option should be applied?

**Comment by trmdi** [comment]
Manually check a checkbox in the Tweak section. The latte configs are different between the layouts, aren't they?

**Comment by psifidotos** [comment]
The per-layout settings arent found in dock settings but in Latte Settings. Based on the current design only way it can be exposed is through by adding a new column in Layouts editor or only by editing manually the layout file

**Comment by trmdi** [comment]
It's your design, I don't know. But I think this feature is very interesting, th multi-layouts users will love it. :)

**Comment by psifidotos** [comment]
Can you describe how you are using multiple layouts? There arent many users using them

**Comment by trmdi** [comment]
Sometimes I just want to switch between the layouts to change the desktop look (macOS style / unity style / Plasma style). That's all.

**Comment by psifidotos** [comment]
I will play with it... But for start I am not going to add it in the gui.... 

in each layout file there is a section called: [LayoutSettings]

a variable in there could do the trick eg.:

`disableBordersForMaximizedWindows=true`

**Comment by trmdi** [comment]
Great, I can't wait to test it. :)

**Comment by psifidotos** [comment]
@trmdi ok you can play with it...

**Comment by trmdi** [comment]
Works nearly perfectly, but why don't you want to add a checkbox to the Layout gui? Everyone can understand and use it easily.

**Comment by psifidotos** [comment]
> , but why don't you want to add a checkbox to the Layout gui? 

it will become overcrowded and I dont want to...

in the future maybe an Options button in Layouts editor could be possible instead of the Locked one in order contain such small features as:

- Lock/Unlock
- Hide window borders for maximized windows
