### ISSUE TITLE
Latte Dock crashes on startup

### ISSUE THREAD

**Issue by Slater91** [psifidotos/Latte-Dock#1002]
I've been experiencing crashes when launching Latte since April 15th's update. The dock crashes on startup without further information; launching it from the terminal returns a message saying "another instance is currently running, use --replace to restart Latte" - but there is in fact no other instance running. Using "--replace" yields no result.
KDE's crash dialog appears, but as the debug symbols package is not available for the latest version, I could not create a dump.
I am currently using KDE neon, with all packages up to date. Latest build I tested is 0.7.79+git20180420.0053-0~ubuntu18.04~ppa1. Versions released before April 15th worked as a charm.

Could anyone please help me in tracing down the issue?

Thank you!

**Comment by psifidotos** [comment]
Have tried to clear cache?

**Comment by psifidotos** [comment]
Try to remove the latte-dock lock file at tmp folder in order to be able to restart Latte

**Comment by psifidotos** [comment]
@Slater91 the above comment is for you

**Comment by Slater91** [comment]
@psifidotos Yes, that solved the problem. In fact the behaviour is now correct and consistent across restarts and system reboots.
Thank you for your help: though trivial, I could not find a solution to the issue!

**Comment by psifidotos** [comment]
>  I could not find a solution to the issue!

so is everything ok now?

**Comment by Slater91** [comment]
Yes, it is. It now works as expected.
