### ISSUE TITLE
Latte Plasmoid and Task manager conflict with Meta+Nr keybindings

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#1003]
```
$ latte-dock --version
lattedock 0.7.79
```
So I have the latest latte-dock because I thought it might help but it doesn't. 

My config:
- a dock on the left with application widgets (dragged and dropped, not pinned) and the latte plasmoid
- another dock (pretty much like the default panel) - it has the task manager

Expected:
- hitting meta+nr will open the numbered widgets on the left dock (I do have my configurations in the settings)

What happens:
- hitting meta+nr (activate entry) actually activates the task manager instead and brings to focus what is on it; activate task manager entry does not have any binding to it (in the settings) but it is a default in plasma 5
- also doing  Show dock, that gives me the number hints does not disappear because the actual command to open an entry does not work

Workaround
```
$ killall latte-dock 
$ latte-dock &
```

**Comment by RaitaroH** [comment]
Oh yeah also I have these `New instance for task manager entry shortcuts` mapped to `Ctrl+Meta+Nr` but they don't do anything. Also for some reason even though I set up my battery shortcut to 'Alt+b` it is never saved next time I login. Maybe related.

**Comment by psifidotos** [comment]
@RaitaroH can you show me a screenshot of all docks ?

**Comment by RaitaroH** [comment]
![screenshot_20180420_191446](https://user-images.githubusercontent.com/19552720/39062107-286a39e0-44cf-11e8-9ef4-d54315077d83.png)

**Comment by psifidotos** [comment]
Why the left dock should be prioritized in your system comparing to the bottom?

**Comment by RaitaroH** [comment]
Because it has the latte plasmoid? I mean it usually is the main but sometimes it does act up and the task manager becomes first. Now you may say why have the task manager... cus I dont like using the big icons on the left.  And I need the latte plasmoid for my meta+nr that you implemented, in essence.

At least if the task manager was always the focus but no. Also a normal plasma panel didn't steal the attention actually. But I moved to latte to use a bit less ram (maybe) but mostly for the time for show/delay.

**Comment by psifidotos** [comment]
Latte treats all taskmanagers the same, independent of which one is which just like plasma implementation is doing.Taskmanagers that get biger priority are those that are present in primary screen. If they are in the same screen then there is no priority. They are treated equal. The first one found is used.

**Comment by RaitaroH** [comment]
Hmm. Ok then.

**Comment by psifidotos** [comment]
I must think it, Latte proritizes in a few places docks by their edge e.g. showing the dock settings with Meta+A. So instead of just leaving it in luck we could use the same.

The internal priority is Bottom, Left, Top, Right. which would solve also you case.

**Comment by RaitaroH** [comment]
I see. But in my case it should be left, bottom. So maybe have an option? Idk.

**Comment by psifidotos** [comment]
Yeah you are rigjt you want left first, so doesnt help... unfortunately I wouldnt want to add such option
