### ISSUE TITLE
Setting a keybinding that already exists should give a warning

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#1004]
So plasma is kind enough to tell you that hey, this shortcut is used by bla bla, somewhere else. Latte basically ignores that and the shortcut is executed instead.

Ex:
1. set up say a shortcut for the sound widget
2. set up the same shortcut for the battery and notice how the sound widget popsup.

**Comment by psifidotos** [comment]
Can you show me how Plasma warns and how Latte doesnt?

**Comment by psifidotos** [comment]
as a comment Latte doesnt alter any shortcuts behavior

**Comment by psifidotos** [comment]
;)
