### ISSUE TITLE
Freezes of the whole system

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#1005]
Latte acts weird since 0.7.78 I think. I get a lot more freezes. Sometimes I can only use the tty to reboot, some other times I can't even do that. I tried rolling back to 0.7.78 from 0.7.79 and the freezes stopped. Now I got back on 0.7.79 just to see if I still have #1003 and I already restarted twice in the last 15 min...

**Comment by psifidotos** [comment]
What is the cpu usage for Latte when it freezes?

**Comment by psifidotos** [comment]
Have you tried to remove Latte cache ?

**Comment by RaitaroH** [comment]
To be fair I did try stuff like trying to restart plasma through shortcuts... it didn't work. I also have a script for it so from a tty I also tried that with no results. I also tried `kwin --replace` but unfortunately from a tty it spits fatal error while trying to find display.

There is also `qdbus org.kde.ksmserver /KSMServer logout 0 0 0` which does nothing from a tty so I am usually forced to restart.

I will come back to you with more info on the CPU usage next time it happens but I think it might be the drivers... Though it happened due to updating latte, or at least it might just be a correlation.

**Comment by RaitaroH** [comment]
Also right now I get this 2-5 sec freezes when latte doesn't show up, krunner doesn't show up, stuff like that. I just have to wait and they show up o.O

Maybe I should reinstall, I just think neon on my machine got a bit unstable due to me playing around with CUDA and some other stuff.

**Comment by RaitaroH** [comment]
@psifidotos It happened again btw. In htop latte was showing 36% CPU. Killing it did nothing besides getting my CPU to normla, restarting plasma did nothing. I had to reboot.

**Comment by psifidotos** [comment]
You restarted plasma and didnt fix what?

**Comment by RaitaroH** [comment]
So I can't do anything. I try to restart using the keyboard shortcut but nothing happens. I go to the tty and trying to restart plasma from there using `killall plasmashell; plasmashell &` but then I go back to a black screen maybe maybe with my cursor showing. I can't do anything. My applications show like they work, my music is playing etc, but black screen and nothing else.

Also latte keeps on disappearing for some reason. It drives me nuts. I have to go back to the .78 version.

**Comment by psifidotos** [comment]
The fact that Latte breaks your system in such degree I find it almost impossible. At least by killing Latte everything should return to normal the fact that it doesnt its totally weird.

1. Have you enabled Dynic Background and Improve visibility from Tweaks page.
2. Does this occur with Default layout without any changes in it?

**Comment by RaitaroH** [comment]
So I activated now everything in dynamic background.

Not sure if it does happen in the normal layout. I may have to come back to you tomorrow for this one.

**Comment by RaitaroH** [comment]
Yeah so I tried to change the layout the plasma. It simply restarted latte then it went back to my layout. After trying again it crashed.

```
Sending SIGCONT to process
KCrash: Attempting to start /usr/bin/latte-dock directly
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = latte-dock path = /usr/bin pid = 22639
KCrash: Arguments: /usr/bin/latte-dock 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi directly
found lsb_release
Using /proc to determine executable path
Executable is: "/usr/bin/latte-dock"
Executable exists: true
Enabling drkonqi crash catching
Sending SIGSTOP to process
KCrash: Attempting to start /usr/bin/latte-dock directly
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = latte-dock path = /usr/bin pid = 24003
KCrash: Arguments: /usr/bin/latte-dock 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi directly
found lsb_release
Using /proc to determine executable path
Executable is: "/usr/bin/latte-dock"
Executable exists: true
Enabling drkonqi crash catching
"An instance is already running!, use --replace to restart Latte"
Sending SIGSTOP to process
Sending SIGSTOP to process
Sending SIGCONT to process
Sending SIGCONT to process
```
I had latte-dock started ina terminal.

**Comment by RaitaroH** [comment]
Oh... you will love this one: https://youtu.be/CkhUUCIT5ak

It happend at startup right now. I restarted I think 4 to 5 times today. Considering that in the last week I didn't not even once, but today the only thing I updated was latte.

**Comment by RaitaroH** [comment]
So yeah I am just thinking [this](https://stackoverflow.com/questions/1616957/how-do-you-roll-back-reset-a-git-repository-to-a-particular-commit#1616959)

**Comment by RaitaroH** [comment]
So I tried to switch to plasma layout. No success. To unity was fine, but I decided to just add a new panel and remove everything else.

```
raitaro@reika ~ $ latte-dock --replace
KCrash: Attempting to start /usr/bin/latte-dock directly
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = latte-dock path = /usr/bin pid = 27696
KCrash: Arguments: /usr/bin/latte-dock --replace 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi directly
found lsb_release
Using /proc to determine executable path
Executable is: "/usr/bin/latte-dock"
Executable exists: true
Enabling drkonqi crash catching
Sending SIGSTOP to process

[1]+  Stopped                 latte-dock --replace
raitaro@reika ~ $ killall latte-dock 
raitaro@reika ~ $ latte-dock &
[2] 30803
raitaro@reika ~ $ KCrash: Attempting to start /usr/bin/latte-dock directly
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = latte-dock path = /usr/bin pid = 30803
KCrash: Arguments: /usr/bin/latte-dock 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi directly
found lsb_release
Using /proc to determine executable path
Executable is: "/usr/bin/latte-dock"
Executable exists: true
Enabling drkonqi crash catching
"An instance is already running!, use --replace to restart Latte"
Sending SIGSTOP to process
^C

[2]+  Stopped                 latte-dock
raitaro@reika ~ $ latte-dock &
[3] 30988
raitaro@reika ~ $ "An instance is already running!, use --replace to restart Latte"
^C
[3]   Done                    latte-dock
raitaro@reika ~ $ killall latte-dock 
raitaro@reika ~ $ latte-dock &
[3] 31199
raitaro@reika ~ $ Sending SIGCONT to process
Sending SIGCONT to process
^C
[1]-  Terminated              latte-dock --replace
[2]+  Terminated              latte-dock
```
Right now latte is working fine. Also ` "An instance is already running!, use --replace to restart Latte"`
![screenshot_20180420_221508](https://user-images.githubusercontent.com/19552720/39069522-b25fd3c6-44e8-11e8-9a16-83993ad81f7d.png)

**Comment by psifidotos** [comment]
1. Improve visibility is used at single colour  panels, having  it enabled at any other case isnt work ok... blame plasma libraries that dont support any better for now

2. Crashes without meaningful backtraces cant be identified and fixed. You can read at: https://github.com/psifidotos/Latte-Dock/wiki/How-to-Report-Crashes

3. A crash under X11 when changing layouts was fixed two days ago I dont know if that has reached you

4. Steaking with 0.7.78 can be a temp solution but next stable release 0.8.0 will be based at 0.7.79

**Comment by RaitaroH** [comment]
So I decided to remove the bottom panel in favor of a new plasma panel. I deleted the cache and install ddd. It hasn't crashed yet but for some reason (I had improve in dynamic back checked) it went from normal to black for some reason:
![screenshot_20180421_091058](https://user-images.githubusercontent.com/19552720/39081107-0ce4cc42-4544-11e8-9f49-0e9ad813e191.png)
Also it went back to normal just after taking the test.

Also here is everything ddd spit out:
```
GNU DDD 3.3.12 (x86_64-pc-linux-gnu), by Dorothea LReading symbols from latte-dock...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe048c700 (LWP 14494)]
[New Thread 0x7fffde286700 (LWP 14503)]
[New Thread 0x7fffd7bbe700 (LWP 14504)]
[New Thread 0x7fffb85fc700 (LWP 14524)]
[Thread 0x7fffb85fc700 (LWP 14524) exited]
[New Thread 0x7fffb85fc700 (LWP 14533)]
[Thread 0x7fffb85fc700 (LWP 14533) exited]
[New Thread 0x7fffb85fc700 (LWP 14534)]
[New Thread 0x7fffb5ad5700 (LWP 14535)]
[New Thread 0x7fffa7b7b700 (LWP 14545)]
[New Thread 0x7fff9bffe700 (LWP 14577)]
[New Thread 0x7fff9b1bd700 (LWP 14578)]
[New Thread 0x7fff9a93c700 (LWP 14587)]
[New Thread 0x7fff996fb700 (LWP 14588)]
[New Thread 0x7fff98cda700 (LWP 14597)]
[New Thread 0x7fff839ff700 (LWP 14664)]
[New Thread 0x7fff815c0700 (LWP 14665)]
[New Thread 0x7fff7bbff700 (LWP 14674)]
[New Thread 0x7fff7af80700 (LWP 14675)]
[Thread 0x7fff839ff700 (LWP 14664) exited]
[Thread 0x7fff7af80700 (LWP 14675) exited]
[Thread 0x7fff815c0700 (LWP 14665) exited]
[Thread 0x7fff7bbff700 (LWP 14674) exited]
[New Thread 0x7fff7bbff700 (LWP 14720)]
[New Thread 0x7fff815c0700 (LWP 14721)]
[New Thread 0x7fff7af80700 (LWP 14722)]
[New Thread 0x7fff839ff700 (LWP 14731)]
[New Thread 0x7fff79852700 (LWP 14732)]
[Thread 0x7fff79852700 (LWP 14732) exited]
[Thread 0x7fff7bbff700 (LWP 14720) exited]
[Thread 0x7fff839ff700 (LWP 14731) exited]
[Thread 0x7fff815c0700 (LWP 14721) exited]
[Thread 0x7fff7af80700 (LWP 14722) exited]
[New Thread 0x7fff7af80700 (LWP 14972)]
[New Thread 0x7fff815c0700 (LWP 19083)]
[Thread 0x7fff815c0700 (LWP 19083) exited]
[New Thread 0x7fff815c0700 (LWP 19087)]
[Thread 0x7fff815c0700 (LWP 19087) exited]
[New Thread 0x7fff815c0700 (LWP 19098)]
[New Thread 0x7fff839ff700 (LWP 19099)]
[New Thread 0x7fff7bbff700 (LWP 27546)]
[New Thread 0x7fff789ce700 (LWP 27552)]
[New Thread 0x7fff671bf700 (LWP 27564)]
[New Thread 0x7fff669be700 (LWP 27565)]
[New Thread 0x7fff65fbd700 (LWP 27566)]
[Thread 0x7fff669be700 (LWP 27565) exited]
[Thread 0x7fff7bbff700 (LWP 27546) exited]
[Thread 0x7fff65fbd700 (LWP 27566) exited]
[Thread 0x7fff789ce700 (LWP 27552) exited]
[Thread 0x7fff671bf700 (LWP 27564) exited]
[New Thread 0x7fff671bf700 (LWP 28042)]
[Thread 0x7fffb5ad5700 (LWP 14535) exited]
[Thread 0x7fff671bf700 (LWP 28042) exited]
[Thread 0x7fff815c0700 (LWP 19098) exited]
[Thread 0x7fff9a93c700 (LWP 14587) exited]
[Thread 0x7fff996fb700 (LWP 14588) exited]
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
Continuing.
^C
Thread 1 "latte-dock" received signal SIGINT, Interrupt.
0x00007ffff18c974d in poll () at ../sysdeps/unix/syscall-template.S:84
frame 3
#3  0x00007ffff271b5af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) cont
Continuing.
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) Continuing.
Continuing.
Continuing.
[New Thread 0x7fff996fb700 (LWP 665)]
[New Thread 0x7fff9a93c700 (LWP 667)]
[New Thread 0x7fff815c0700 (LWP 668)]
[New Thread 0x7fff671bf700 (LWP 677)]
[Thread 0x7fff996fb700 (LWP 665) exited]
[Thread 0x7fff671bf700 (LWP 677) exited]
[Thread 0x7fff9a93c700 (LWP 667) exited]
[Thread 0x7fff815c0700 (LWP 668) exited]
Continuing.
Continuing.

file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) Continuing.
Continuing.
^C
Thread 1 "latte-dock" received signal SIGINT, Interrupt.
0x00007ffff18c974d in poll () at ../sysdeps/unix/syscall-template.S:84
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) 
file: "../sysdeps/unix/syscall-template.S", line number: 1
(gdb) Quit
(gdb) 
```

**Comment by RaitaroH** [comment]
So I had 2 crashes since this morning so pretty much every hour or so.

`env QV4_FORCE_INTERPRETER=1 latte-dock -d > allout.txt 2>&1` So I used this to get some output.
[allout.txt](https://github.com/psifidotos/Latte-Dock/files/1934250/allout.txt)
[top_latte.txt](https://github.com/psifidotos/Latte-Dock/files/1934251/top_latte.txt)
I also put the top info based on the PID of latte there as well. 

Now you may ask for ddd output but I am not sure how can I output to a file. Once the system freezes up I can't really do anything anymore.

I have no disabled latte to even startup and I will come back to you.

**Comment by psifidotos** [comment]
> Now you may ask for ddd output but I am not sure how can I output to a file

_1. you dont have to. If you read at: https://github.com/psifidotos/Latte-Dock/wiki/How-to-Report-Crashes_

> - when it crashes, in ddd click status from the menu -> backtrace
> - This will show you a window with numbered lines, this could be helpful for us


This issue must follow a structure or I am going to close it for losing focus:

2. This issue is about crashes or freezes? They are different.
3. First thing you must try before everything is the first three steps at : https://github.com/psifidotos/Latte-Dock/wiki/How-to-Report-Crashes in order to clear your crash in case this a qt cache issue and totally irrelevant to Latte
4. **DISABLE** the **Improve visibility** at Tweaks page. It is used **ONLY** when your panel/dock contains items that **ALL** have the same color such as the the top panels case.


afterwards please report for each comment by saying for which number you are referring....

**Comment by RaitaroH** [comment]
@psifidotos No news on neon 18.04? Some reddit threads with hopes but thats about it.

**Comment by psifidotos** [comment]
No idea

**Comment by RaitaroH** [comment]
yeah... I will see.

**Comment by defue** [comment]
I've built the latest version from the sources today and also faced with frequent freezes. I managed to get my system back to the working state by switching to the console (CTRL + ALT + F2 on Ubuntu) and then restarting KWIN using the below command
```
DISPLAY=:0 kwin --replace &
```
Fortunately I found a way how to reproduce the freeze on my system:
- make the dock hide under active window
- move mouse down to make the dock appear and show a tooltip of an open application window
- move mouse back to the active window to make the dock and tooltip hide
In 1 of about 10 cases it led to the complete freeze of X11 and the tooltip stayed on my screen in semitransparent state.

Then I tested all the commits starting from the head to find out which commit introduces that bug and finally found it. Here it is:
https://github.com/psifidotos/Latte-Dock/commit/fb8063cdee0f0b7ae58f54d62b8124e5900902cf

Hope it helps to fix the issue.

**Comment by defue** [comment]
I ended up commenting the below lines in app/dock/screenedgeghostwindow.cpp file and recompiling. It fixed the issue for me.
```
connect(this, &QQuickView::xChanged, this, &ScreenEdgeGhostWindow::fixGeometry);
connect(this, &QQuickView::yChanged, this, &ScreenEdgeGhostWindow::fixGeometry);
connect(this, &QQuickView::widthChanged, this, &ScreenEdgeGhostWindow::fixGeometry);
connect(this, &QQuickView::heightChanged, this, &ScreenEdgeGhostWindow::fixGeometry);
```

**Comment by psifidotos** [comment]
Having a way to reproduce in your system we can play with it....are you able to build from a branch in order to check if it is solved?

**Comment by defue** [comment]
That's what I initially did and faced with the freeze problem. Then I patched screenedgeghostwindow.cpp and the problem gone.

**Comment by psifidotos** [comment]
The lines you commented are important, so a solution is needed but I wiil need feedback what breaks in your system and why...


When a dock has activated Tweaks->Enable KWin screen edges (this is default) then KWin Screen Edges are used per dock. Each dock in such case has a hidden window in order to activate/deactivate the kwin screen edge. That window must be placed at specific position but in your system probably never succeeds.... the question is why it never succeeds?

**Comment by psifidotos** [comment]
@defue  can you please test branch **fix1005** ? I added a timer in order to not make so intrusive that code

**Comment by defue** [comment]
Just built and installed the fix1005 branch and it seems working fine. Can't make it to freeze as before. I am going to use it for a while and if I get a freeze again I'll let you know.

**Comment by defue** [comment]
BTW I've just noticed that the dock doesn't appear when firefox location bar is extended (see the screenshot below). Is it related to the 1005 fix or should I open a new issue?
![firefox_location_bar](https://user-images.githubusercontent.com/7314657/40298185-ee812c82-5cea-11e8-8d58-7524e9bf269f.png)

**Comment by psifidotos** [comment]
@defue this isnt a bug, the user still works in firefox window and can always drag something from firefox to the dock

**Comment by psifidotos** [comment]
@defue you can open a different issue if you want to communicate that issue

**Comment by RaitaroH** [comment]
@psifidotos I reinstalled to see what will happen. I am still due for a full system update :sweat_smile:
