### ISSUE TITLE
Background is shown for maximized windows, which are minimized

### ISSUE THREAD

**Issue by Scrumplex** [psifidotos/Latte-Dock#1006]
If I enable "Show background only for maximized windows" in Tweaks, the background stays visible if a window is maximized, but minimized.

Reproduction steps:
1. Enable Show background only for maximized windows for Dock
2. Maximize window
3. Minimize window

-> Dock background stays visible

**Comment by psifidotos** [comment]
You have enabled windows previews for all windows and that breaks the minimized window identification   of X11. This is X11 limitation. You can enable window previews only for shown windows if you want this fixed

**Comment by Scrumplex** [comment]
Okay thanks. It's really sad, that there is no way to detect this with KF5 for something
