### ISSUE TITLE
Dynamic transparency behaviour for maximized but hidden windows

### ISSUE THREAD

**Issue by enryIT** [psifidotos/Latte-Dock#1007]
`➜  ~ latte-dock --version`
`lattedock 0.7.4`

Dynamic transparency effect (show the background only for maximized windows) is showing a wrong behaviour: while the window is maximized it correctly shows the configured dock background, if you minimize the window it then hide the background and make it transparent BUT if you hide (send to background) the window leaving it maximized the dock keeps the background enabled.

I think if a window is maximized but moved to the background Latte should treat it as minimized therefore restore the panel opacity to 0%.

GIF showing the problem:
![issue](https://user-images.githubusercontent.com/590989/39067047-995cc3a4-44d7-11e8-9593-780af1b63067.gif)

Is this a design choice or is it configurable as per user preference?

**Comment by enryIT** [comment]
Yes, and disabling that "resolves" the issue.

This is nasty.

**Comment by psifidotos** [comment]
Unfortunately this X11 to blame, Latte cant do simething....
