### ISSUE TITLE
Add option to open menu on "current" screen

### ISSUE THREAD

**Issue by Scrumplex** [psifidotos/Latte-Dock#1008]
I tried the solution in #102 which opens one of my application menus, but on the wrong monitor. I two kickoff-menus: one on my first screen, one on my second. I use two different docks for that. The DBus action opens the menu on my second screen.

Ther should be an option to open the menu on the current screen (respecting the KWin option "Active screen follows mouse").

**Comment by psifidotos** [comment]
This isnt Latte respondibility but plasma and kwin

**Comment by Scrumplex** [comment]
This is definetely not plasma's responsibility: https://github.com/psifidotos/Latte-Dock/blob/a6a98f3ac7cf6c707f6a32d4c39152f391c09620/app/globalshortcuts.cpp#L268
You are looping through all applets and then triggering the first occurrence of `org.kde.plasma.launchermenu`.

**Comment by psifidotos** [comment]
Oh... this is a feature request... I see...

Latte is just following the plasma implementation...

Of course the fact that you can understand the code, it means that you can also make a pull request... feel free to attach one for review...

**Comment by Scrumplex** [comment]
I am not that skilled with C++, but I could try. I was already researching how to query the "active screen" via KWin.

**Comment by psifidotos** [comment]
You cant query from kwin current screen. Only thing you can do is from Qt to access mouse coordinates. Based on that and the screens geometries you identify in which is inside.
