### ISSUE TITLE
Latte Dock draws shadows on applet menus while shadows are disabled.

### ISSUE THREAD

**Issue by Scrumplex** [psifidotos/Latte-Dock#1009]
I disabled shadows and enabled, that the background is only drawn when something is maximized. If I now open a menu of an applet in the dock the background gets drawn, but shadows, too. Additionally there is a bug with Global Menu, as it wants to draw shadows (and probably draw background), but then decides not to.

It does not draw shadows on maximized windows (which is the expected behaviour).

Demonstration: https://youtu.be/mF535wf8KvY

**Comment by psifidotos** [comment]
Videos for issues in youtube is bad marketing for the product so please remove them. You can use alternative ways such google drive and dropbox.

This issue isnt Latte fault but AWC one, that I have personally fixed in each codepage at the master version at: https://phabricator.kde.org/source/plasma-active-window-control/

just use that AWC version...

**Comment by Scrumplex** [comment]
I don't use AWC. I only show stock plasma applets in the video (Global Menu, Application Launcher). The issue is a Latte issue, as the shadow is drawn, although it is disabled. I can't think of a reason, why an applet could "force" Latte to draw a shadow. 

At https://youtu.be/mF535wf8KvY?t=18s I am opening and closing the application launcher. If you look closely, you can see that a shadow is drawn, although I disabled it.

As the YouTube video is unlisted, it has the same effect as a GDrive video.

**Comment by psifidotos** [comment]
> I don't use AWC. I only show stock plasma applets in the video (Global Menu, Application Launcher). The issue is a Latte issue, as the shadow is drawn, although it is disabled. 

it is drawn because the applets popups contain shadows by default and this can not be changed. So this is a design decision to draw also the shadow in the panel for consistency.

**Comment by Scrumplex** [comment]
If this is inteded, there should be an animation. Without a fade animation it looks odd.

**Comment by psifidotos** [comment]
You cant have animations when the shadows are drawn external of the window from the window manager

**Comment by Scrumplex** [comment]
Then there should be a way to disable the shadows. I would classify the behaviour as a bug, as I disabled shadows in the Latte settings

**Comment by psifidotos** [comment]
Sorry... I dont
