### ISSUE TITLE
Please allow the dashboard/menu to be launched with the meta key

### ISSUE THREAD

**Issue by kudapara** [psifidotos/Latte-Dock#1011]
When using the default plasma panel if the shortcut for the dashboard/menu widget is set to ```meta+F2``` you can open the dashboard/menu by just pressing the ```meta``` key without having to stretch your span to reach to the ```F2``` button.

But with the same shortcuts in latte dock the dashboard/menu does not open unless you actually click ```meta+F2```.

 My sincere request is for that nice convenience to be implemented into latte dock. Thank you.

**Comment by trmdi** [comment]
Read the FAQ, there is a solution for this issue.

**Comment by kudapara** [comment]
Thanks a lot :clap: :clap:
