### ISSUE TITLE
[Help] Panel become completely transparent no matter what theme use.

### ISSUE THREAD

**Issue by kevinsmia1939** [psifidotos/Latte-Dock#1012]
Latte dock 0.7.4-1
Manjaro KDE stable
The top panel become completely transparent for some reason no matter what theme use.
Maybe I will reset latte dock but I am not sure that there could cause by some setting or not.
https://imgur.com/HP8jXNS

**Comment by kevinsmia1939** [comment]
I do a simple work around by deleting the top panel and replace it with the panel that come with normal plasma. So I think its fix then.

**Comment by psifidotos** [comment]
There are settings that provide this.

1. You have diisabled panel background
2. You have set panel transparency to 0%
3. You have enabled Dynamic background from Tweaks
