### ISSUE TITLE
 Unite makes KDE look like Ubuntu Unity Shell.

### ISSUE THREAD

**Issue by candrapersada** [psifidotos/Latte-Dock#1013]
KDE which makes a few layout tweaks to the top panel and removes window decorations to make it look like Ubuntu Unity Shell and macOS.
![image](https://user-images.githubusercontent.com/36833664/39216168-d58107c6-4844-11e8-967d-2559b5e8fd94.png)
- Adds window buttons to the top panel for maximized windows.
- Shows current window title in the app menu for maximized windows.
- Removes titlebars on maximized windows.
- Hides window controls on maximized windows with headerbars.
- Moves the date to the right, fixes icons spacing and removes dropdown arrows.
- Moves legacy tray icons to the top panel.
- Moves notifications to the right.
- Hides activities button.

**Comment by psifidotos** [comment]
looks nice... but what is the issue about?

**Comment by candrapersada** [comment]
buttons top lefi panel
![staticshot_26-04-2018_07-42-13](https://user-images.githubusercontent.com/36833664/39279818-9b9c3f58-4925-11e8-98ce-2465ddbe897a.png)

**Comment by trmdi** [comment]
You can install the Active Windows Control widget then download the Unity layout to get that look.

What else do you want?

**Comment by candrapersada** [comment]
top left panel
![staticshot_26-04-2018_11-30-24](https://user-images.githubusercontent.com/36833664/39285956-690ae736-4945-11e8-8396-fe75cf6a4493.png)
