### ISSUE TITLE
Latte Dock: Integration with Plasma Containments

### ISSUE THREAD

**Issue by star-buck** [psifidotos/Latte-Dock#1014]
Is latte dock integration such that the plasma desktop containments (desktop, folderview) are aware of any docks and should adjust the icon grid accordingly (like when detecting a plasma panel in the same space)?
see this screenshot where the top icons extend into the latte dock at top:
![screenshot_20180430_112606](https://user-images.githubusercontent.com/840070/39421536-cdf6debc-4c69-11e8-8c8a-e1deb953a7a1.png)

**Comment by psifidotos** [comment]
nope... plasma doesnt offer yet any way for external docks/panels to publish their geometries to it...

duplicate from: #737

**Comment by star-buck** [comment]
okay, thanks for the info.
