### ISSUE TITLE
Closing widget shadow

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#1015]
After second click on widget in latte dock to close it there is some weird shadow. Plasma panel have no this shadow.
https://youtu.be/TxRGSsFMABs

**Comment by psifidotos** [comment]
I cant understand what you are referring at... Can you make a screenshot and point to the shadow you are mentioning?

**Comment by divinae** [comment]
![screenshot_20180430_130553](https://user-images.githubusercontent.com/15931906/39424574-9c69727a-4c77-11e8-80ab-9ee59ff12791.png)
![screenshot_20180430_130604](https://user-images.githubusercontent.com/15931906/39424577-9de2d786-4c77-11e8-9f1a-dd7df517db79.png)

**Comment by psifidotos** [comment]
isnt that the panel shadow? In my system a plasma panel just shows that shadow always...

can you replicate the screenshot with a top plasma panel and the same applet to compare?

**Comment by divinae** [comment]
moving panel to the left and then back resolve this o.O
You are need screenshot still ?

**Comment by psifidotos** [comment]
> Are you need screenshot still ?

nope, I just dont know yet the reason for this behavior

**Comment by psifidotos** [comment]
@divinae your top panel is in AlwaysVisible mode, correct ?

**Comment by divinae** [comment]
correct :+1:

**Comment by psifidotos** [comment]
and one more info, this is only X11 issue... in wayland doesnt appear...

**Comment by psifidotos** [comment]
from today all new or unclosed issues should be reported to: https://bugs.kde.org/
