### ISSUE TITLE
Sometime the audio badge is shown on the wrong icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#1016]
Sometime the audio badge is shown on the wrong icon
Do you think it could have anything to do with the issue #984 ?

**Comment by psifidotos** [comment]
Libtaskmanager mess.. no idea for its root...

**Comment by psifidotos** [comment]
nothing new and at the same time:

from today all new issues should be reported to: https://bugs.kde.org/
