### ISSUE TITLE
How to start on login?

### ISSUE THREAD

**Issue by keeganjk** [psifidotos/Latte-Dock#1017]
After shutting down device and rebooting, I have to manually open Latte. How do I get it to open automatically?

**Comment by trmdi** [comment]
Right click on Laate-dock > Layout > Configure > Preferences > ...

**Comment by keeganjk** [comment]
Don't see "Preferences" in Layouts Editor...

**Comment by keeganjk** [comment]
I think I got it to work by enabling my loadout as the default and adding it as a startup app in the KDE settings.
