### ISSUE TITLE
Improving colors of active window markers

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#1018]
Currently there is no way to personalize colors of active window markers. So far I can judge, their color is taken from theme but that produces odd results in certain backgrounds.

Here are examples of opened programs white theme on white background (many sites have it) and black theme also on white background:

![screenshot-2018-05-04-14 10 15](https://user-images.githubusercontent.com/10132958/39627228-6bb116a2-4fa5-11e8-85b4-4f7048b5969f.png)

![screenshot-2018-05-04-14 10 55](https://user-images.githubusercontent.com/10132958/39627230-6e70b0e6-4fa5-11e8-8fbb-0a85b39de538.png)

Actually, only one program from showed above is not opened... can someone guess which one? ;) It can be spotted but it's hardly visible. There are some backgrounds when that color works well:

![screenshot-2018-05-04-14 20 27](https://user-images.githubusercontent.com/10132958/39627523-84b71e20-4fa6-11e8-9ea9-5d7e6cbb4dee.png)

Since dock/panel background can be transparent and heavily customized, static colors don't work well. We don't need dynamic changes this time only simple option with color picker so we can simply choose a color that DISTINCTIVE or OPPOSITE to the panel/dock background. At the moment it's in the same color which is weird.

**Comment by psifidotos** [comment]
Sorry i dont want to add any such option, a way to overcome the above described small issues is to enable applet shadows and set an applet shadow that provides the needed contrast

**Comment by michaldybczak** [comment]
How? Shadows are enabled, I set both sliders to maximum and I got only an ugly shadow around program icons, but not activity markers. Wait a moment. Applet shadow does not help, but there is glow setting and it adds some kind of shadow to activity markers. They seems to be more visible now, although that's not an ideal:

![screenshot-2018-05-04-20 47 46](https://user-images.githubusercontent.com/10132958/39646698-94628c48-4fdc-11e8-81fc-9333bb6baee5.png)

That may be not a crucial function, but I often wonder if the program is opened without seeing any clear, graphical clue.

**Comment by michaldybczak** [comment]
Or maybe from different side.
Maybe there will be option to make markers like on default Plasma panel, meaning, the whole area behind window is marked if it's opened, a line when it's minimized, stronger background is when app is active. There are few variations here but most main default distro themes have that effect on Plasma panel, similarly it can be set on Mate dock, this is how it works on Win10, etc. In fact, you could use Plasma's panels way of interpreting theme colors and effects. This is the least problematic and most visible way to mark state of opened windows. At least that's my opinion. I guess there is a low chance of introducing this kind of markers but I can hope, maybe some day ;). I realize that at some point you have to carefully cherry pic features and not all propositions will have a merit.

Anyway, thanks for latte, it skyrocketed my experience on Plasma (together with AWC widget and kvantum themes we can do wonders now)!
