### ISSUE TITLE
Opacity and Dynamic Transparency Behavior Issues

### ISSUE THREAD

**Issue by daved3464** [psifidotos/Latte-Dock#1019]
First of all, sorry for bad english.

I've been using Latte master and have noticed some issues (?) with the behavior of the panel in these cases:

A) Set as Dock: 
    -Always Visible.
    -Aligned.
    -Background Size 85% (and below, else sets as Panel).
    -Blur Enabled or Disabled.
    -Force Solid Background for maximized windows.
    -Hide shadows for maximized Windows.

On window snap or maximized window, transparency isn't set correctly, becoming just a little bit darker, but not solid.

![peek 07-05-2018 02-59](https://user-images.githubusercontent.com/7122738/39692114-83e9a7f0-51a5-11e8-9965-c9d35614c43c.gif)

B) Set as Panel:
    -Always Visible
    -Aligned
    -Background size 90% to 100%
    -Blur Enabled
    -Force Solid Background for maximized windows.
    -Hide shadows for maximized Windows.
    
The panel becomes almost solid (like a common plasma panel, as if opacity was set to 95% and on window snap, or maximize a little darker). If the blur becomes disabled, then this issue is fixed, at cost of the blur effect. 

![peek 07-05-2018 03-13](https://user-images.githubusercontent.com/7122738/39692138-98ba2704-51a5-11e8-9805-1b5a597e85d0.gif)

(The property exists and can be seen at a moment when opening the settings that it is applied, so the issue may be something about the panel appearance handling I suppose).

Edit: Only becomes solid if visibility set to Always on Top, else, opacity with blur works

**Comment by psifidotos** [comment]
Please open two new issues because otherwise the discussion cant be organized.

**Comment by psifidotos** [comment]
these issues you are describing cant be reproduced in my system:

1. what is your plasma theme?

2. Have you enabled the kwin background contrast effect at plasma systemsettings?

**Comment by daved3464** [comment]
Worked well for some days, hadn't seed the message but then today happened again. Did some test, happened to me when using system base themes (Breeze, Oxygen, etc), (i have Adapta and Materia Too) and yes, could reproduce this way.

1. Apply system theme Eg. Breeze. 
2. Open and close latte preferences
 = Bug happens, background darkens

then fixed this way

1. Chose Materia (did with the Adapta theme too)
2. Open and close latte preferences
= background trasparency fixes

**Comment by psifidotos** [comment]
Latte cant bypass the plasma theme maximum solidness which is set by its developer. Only way is to choose also from Latte,Appearance, Panel Background, Solid

**Comment by daved3464** [comment]
Also I noticed that the "solidness"/trasparency effect works when the blur effect is set off at latte settings.

Naturally as an end  user, I don't understand how this awesome software works, or how plasma themes do, but thanks for your response. 

![screenshot_20180608_001319](https://user-images.githubusercontent.com/7122738/41140033-ec5ff504-6ab0-11e8-83bf-bbd88fb7cb72.png)

![screenshot_20180608_001334](https://user-images.githubusercontent.com/7122738/41140038-eec8e5ee-6ab0-11e8-80bd-c642d24c1597.png)

![screenshot_20180608_001346](https://user-images.githubusercontent.com/7122738/41140043-f1ce9b9e-6ab0-11e8-997f-455b72a7159b.png)
