### ISSUE TITLE
Single super key press support for opening application menu

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#102]
Since recently plasma supports opening application menu or dashboard using single super/meta/windows  key press. This works properly if usual panel is added and menu widget is assigned Alt+F1 shortcut. However if i remove normal panel, start the dock, add application menu widget and assign Alt+F1 shortcut - single super key press does not open the menu. You are probably aware that we had to use [ksuperkey](https://github.com/hanschen/ksuperkey) in the past to achieve this. Maybe it can give ideas on how this could be worked out.

**Comment by psifidotos** [comment]
I dont know how feasible is for Latte to support any new feature from the plasma shell... I am not sure that not all features can be supported except if we are a team of 5-6 active developers :) nonetheless we can priotirize things based on our goals and users needs...

so, we will see...

**Comment by kupiqu** [comment]
I was about to ask about adding this feature too. 

This would be very useful to have indeed if we aim to replace all plasma panels by latte docks as I am trying to...

**Comment by giogziro95** [comment]
The same issue here. I was about to file a bug report. I switched back to Now Dock for this reason... Any plans for supporting it in the near future?

**Comment by psifidotos** [comment]
> The same issue here. I was about to file a bug report. I switched back to Now Dock for this reason..

It's called free of choice...

**Comment by psifidotos** [comment]
> Any plans for supporting it in the near future?

As long as it needs dbus support and kwin developers havent provided me with information how to alter kwin behavior from text files, then dont expect it any time soon...

**Comment by rokups** [comment]
> I switched back to Now Dock for this reason...

No need. While having support for this would be cool and all we did not have this feature in KDE desktops until very recently. As a workaround you can use [ksuperkey](https://github.com/hanschen/ksuperkey). I am using it - works great. Just do not forget to bind `Alt+F1` shortcut to applications widget.

**Comment by psifidotos** [comment]
@rokups @giogziro95 

tired of so many asking for this... so I found out how this is configured in kwin... you could try branch
**#superkey**  and you also must set to your

**.config/winrc** 

```
[ModifierOnlyShortcuts]
Meta=org.kde.lattedock,/Latte,org.kde.LatteDock,activateLauncherMenu
```

**Comment by psifidotos** [comment]
> Just do not forget to bind Alt+F1 shortcut to applications widget.

this is not needed in Latte, i disabled it... the user jhas enough trouble updating kwinrc... doesnt need more steps to activate it... :-)

**Comment by rokups** [comment]
Well yeah.. I meant for use with ksuperkey.

Any idea how to make config mod take effect? I restarted both kwin and plasma, setting is in kwinrc however message is still sent to org.kde.PlasmaShell.

Also is there no way to listen on dbus messages of other objects? Intercepting default one would probably be more user-friendly.

**Comment by psifidotos** [comment]
> Any idea how to make config mod take effect? I restarted both kwin and plasma, setting is in kwinrc however message is still sent to org.kde.PlasmaShe

I read somewhere that you must first close kwin and then edit its kwinrc file
if you run:

` qdbus org.kde.lattedock /Latte`

do you see Latte instance?

> Also is there no way to listen on dbus messages of other objects? Intercepting default one would probably be more user-friendly.

not fancy it... what must be done is kwin to support a gui for this... which is going to be added at some point...

**Comment by psifidotos** [comment]
> Also is there no way to listen on dbus messages of other objects? Intercepting default one would probably be more user-friendly.

I dont think this should be possible... intercepting dbus messages between different apps... security concerns etc....

**Comment by rokups** [comment]
Yeah Latte is in there. I did manual call to that dbus method and surely enough application dashboard does open. So i guess you can declare a victory here ;)

**Comment by kupiqu** [comment]
works like a charm :)

**Comment by giogziro95** [comment]
@psifidotos

> tired of so many asking for this... so I found out how this is configured in kwin... you could try branch
> **#superkey** and you also must add/set to your
> 
> **.config/winrc**
> 
> ```
> [ModifierOnlyShortcuts]
> Meta=org.kde.lattedock,/Latte,org.kde.LatteDock,activateLauncherMenu
> ```

Typo there (also in the original report) — it should be _.config/**k**winrc_. And yes, it works.

Also, here's a simple one-liner for lazy people:

`echo -e "\n[ModifierOnlyShortcuts]\nMeta=org.kde.lattedock,/Latte,org.kde.LatteDock,activateLauncherMenu" >> .config/kwinrc`

After running that, just restart KWin:

`kstart kwin_x11 --replace`

**Note:** The previous command assumes that you use X.Org.

**Comment by psifidotos** [comment]
I will fix it here... the correct place of course is: https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-can-i-use-my-super-key-to-open-the-app-launcher

and i will add also in both your solution as an alternative...

**Comment by psifidotos** [comment]
> Note: The previous command assumes that you use X.Org.

why ? it is a kwin file which is used both on X and wayland...

**Comment by giogziro95** [comment]
Sorry for the confusion, I chose bad wording. I meant the command that restarts the shell.

**Comment by Zren** [comment]
Stumbled upon this while helping on IRC. You can use `kwriteconfig5` to edit an INI like desktop file. You can also reload KWin's configuration rather than restarting it (possibly causing problems).

```
kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.lattedock,/Latte,org.kde.LatteDock,activateLauncherMenu"
qdbus org.kde.KWin /KWin reconfigure
```

**Comment by psifidotos** [comment]
@Zren nice!!! Do you want to update our F.A.Qs, the relevant record?

**Comment by Zren** [comment]
Sure. Done. https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-can-i-use-my-super-key-to-open-the-app-launcher

**Comment by giogziro95** [comment]
Why not make the dock to automatically configure it after the first launch (or, at least, add a setting for it)? Wouldn't it be a more user-friendly approach? Just wondering.

**Comment by psifidotos** [comment]
It is kwin developers wish to not set this automatic for the user from any app outside kwin because it could break other kwin parts... in the future it might be a kwin mechanishm or kcm to configure this...

so i just respect their choice...
