### ISSUE TITLE
Serious AWC issue after latest latte git update

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#1021]
Octopi discovered yesterday an update of latte-dock-git version in AUR and as usual I installed it. Since I wasn't rebooting, everything was ok, but today after reboot I came across strange issue.

AWC wasn't stripping titlebars in maximized windows. So I turned the option on again and then I saw this jumping animation as if AWC was having hard time to strip the title bar and the whole window was jumping like jelly. Next maximizing action went fine. Third - the same jumping issue, fourth - fine, fith - again with the issue.

I had to go to work so I closed the system and booted again in the evening. AWC titlebar stripping was again disabled and after enabling it the issue happens again for all windows and makes the whole desktop hardly usable so I will have to downgrade latte or switch to repo version.

I am writing about AWC but this happened after latte update, I re-checked my pacman history to be sure that there was no AWC update yesterday.

Here is the film how the problem looks like:

https://www.youtube.com/watch?v=s6Zlr0j7Ao8

**Comment by psifidotos** [comment]
1. Disable from your AWC "Hide TitleBar for maximized windows", does this fix the issue?
2. If you remove AWC everything is ok ?

**Comment by psifidotos** [comment]
3. Are you using latest AWC from https://phabricator.kde.org/source/plasma-active-window-control/ ?

**Comment by psifidotos** [comment]
4. Latest Latte master supports "Hide TitleBar for maximized windows" through the layout file. You can disable the AWC choice and enable the Latte through: https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks#q-can-i-have-different-borderlessmaximized-windows-option-between-different-layouts   this has been added in order for users that use Multiple Layouts at the same time to have different such option  for different layouts.

**Comment by michaldybczak** [comment]
Hmm.. It's hard to describe everything, it's a mess.
1. Disabling AWC titlebar stripping didn't help so that's not the root of the issue.
2. Will check that later. AWC is hard to set up and I need to make screens from settings to restore them later.
3. I'm using plasma5-applets-active-window-control-git from AUR.
4. I don't see it, but maybe that's correct since I'm not using latte master but git version?

![screenshot_20180509_202610](https://user-images.githubusercontent.com/10132958/39832353-39832dfc-53c7-11e8-981b-ad8adeb88446.jpg)

Here gets wilder: To test it I was maximizing and un-maximizing windows quickly. At some point latte settings got screwed and reversed. So if I had solid panel on maximized, I got transparent on maximized and solid in un-maximized. Restarting latte restores correct behavior of settings but then settings get screwed again.
I never observed this earlier or during normal usage.
Another things I have to add are:
- I had similar issue before but to a lesser extent and I believe it was related to panel shadow. Once in a while maximized windows has a space between panel and window which disappears in a few seconds. Most of the time shadow gets disabled quickly and all looks ok but sometimes I get that space for a while. Unless that's not from the shadow? Also, sometimes when windows are snapped to the panel (touching it) and sometimes windows do get jelly, but not so much as you saw on the video. And also, sometimes smaller windows snapped (touching the border) of the panel jump but much quicker and about 1 pixel, so it's as windows was electrocuted, but the effect is so small that it doesn't disturb me.

So basically there is a wide range of jelly like behaviour.

When recording screen, I see some colored wide stripe showing sometimes under the panel and sometimes I can see it on a desktop (not on a recording) when I manipulate panel elements (widgets).

Most of those things are just slight annoyances and I was just ignoring them, but they showed a while ago, maybe a month or more? But this strong effect is overkill and disturbing normal usage.

I'm using bumblebee intel-nvidia proprietary drivers, desktop runs all the time on intel, if that matters. Also I have enabled wobbly windows which may add to that jelly like effect?

Anyway, you gave me idea and I will start testing various features. At first I thought this is because AWC, but disabling the AWC feature didn't help. Then I thought, maybe that's because of  "Improve contents..." feature, so I disabled it but I still get the issue. So that's not it. Will be playing around and will tell you what I found but disabling few options in the row increased stability and jelly issue shows up less.

**Comment by michaldybczak** [comment]
Update 1:

This is weird, I disabled several tweak options, my latte behaviour got screwed, restarted latte and had some settings changed. I set them properly again, put those tweak options on and... so far problem disappeared and I can't trigger it again. So AWC is stripping windows, I get solid panel when maximized, transparent when un-maximized, dynamic colors are on and all works well now...

There is some slight difference thou... It's as if panel lost completely its edge, which looks very cool:

![screenshot-2018-05-09-20 44 28](https://user-images.githubusercontent.com/10132958/39833486-7872727c-53ca-11e8-9c51-ccb1dcfb4dde.png)

I guess I have to reboot system and see if the old look and issue will happen again. If it does, I will test some other features and maybe switch themes? Something was triggering it. The consistent point was, issue was happening with interaction with panel's edge so all effects influencing it have chance to trigger it.

**Comment by michaldybczak** [comment]
Update 2:

I rebooted computer and... all seems fine now. And I know how to get that borderless effect. I simply have to disabled full background, so the look is not a coincidence. I love it!

I can't trigger the issue now, even with the same settings so I'm confused. However one bug stayed:
after reboot AWC titlebar stripping option was off again... This is weird.

Will monitor situation and will let you know if I discover more or if the issue reappears.

**Comment by michaldybczak** [comment]
Update 3:

I was in the same session, just resizing windows and suddenly I was thrown again to AWC without striping titlebars, so the option changed spontaneously.... This is disturbing.

**Comment by psifidotos** [comment]
This behavior is very strange... Make sure that you have only one AWC running, disable that option for AWC, it shouldnt be enabled by its own and enable the Latte one! 

If it is still present afterwards then something is broken in your system

**Comment by michaldybczak** [comment]
I'm not sure what do you mean by "only one AWC running". How could there be more then one? Or do you mean as number of AWC widgets on panels? If so, I have only one in upper panel.

I still can't figure out where is this latte option to strip titlebars. The post with screenshot was not helpful because it was in greek? I think and for me this menu looks different and I am not sure which option this might be or if it's really there.

**Comment by michaldybczak** [comment]
OK, I installed latest Manjaro KDE in virtualbox, updated the system, installed trizen and made it as default AUR engine in octopi, searched and installed latte-dock-git, searched and installed plasma5-applets-active-window-control-git with octopi. I set upper latte panel, cleaned it and added AWC to it, configured it to show buttons and menu and also enabled stripping of title bar.

It turned out the problem is reproducible that way so it's not my "broken" system. Latte git and AWC git on Arch (or maybe only on Manjaro) are clashing somehow after latest commit.

In my vbox install, after reboot, AWC's stripping titlebars seem to work, just for a few seconds and then it's as if AWC or something crashed, restarted again (no visible effect) and option of stripping titlebars is disabled. So the same issue and quite easy reproducible and won't go away if we won't debug and fix somehow. Maybe this can or should be fixed on AWC side but first we need to know what is happening.

Just take your time, no pressure. This is what git versions are after all - testing software in live, real systems to discover and fix potential issues before it turns out to be an official version.

I may also try to downgrade latte to ensure that the bug was introduced in latest commit.

**Comment by michaldybczak** [comment]
Yeap, downgrading to latte-dock-git-0.7.1.r626.ga6a98f3a-1-x86_64.pkg.tar.xz  fixed the issue. So the reason for this must be in commits from May 6th, 2018.

Of course it doesn't have to mean that the bug is on your side but somehow all was ok before and something in that latest code is not playing nice with AWC which is a classic addition to latte dock.

Let me know if I could do some more tests. Of course you can play with virtualbox as well to see what is happening.

**Comment by psifidotos** [comment]
The thing is that I cant reproduce in my Neon system

**Comment by psifidotos** [comment]
The only thing I can think of for this is Latte to have an enabler/disabler for that functionality and by default to be disabled... currently this is supported only by adding the option in the layout text file... it should restore the behavior

**Comment by michaldybczak** [comment]
Not sure if I understand. Enabler/disabler for what functionality?

Downloading Manjaro, installing it, installing latte, AWC and setting it properly took me about half an hour (while most of the time you can minimize vbox and do other things). Or setting up Antergos could be nice thing to keep in touch what's happening on arch side.
I keep Neon install in my vbox to see what is happening on Ubuntu side and sometimes to check if some things can be reproducible there.

Neon still uses Ubuntu 16.04 so the issue may show up there too once it upgrades to 18.04 or maybe not ;).

Maybe other users who are more technical then me could provide more valuable output for this issue.

**Comment by psifidotos** [comment]
> Not sure if I understand. Enabler/disabler for what functionality? Do you mean stripping titlebar in latte?

Yes, Latte no longer needs AWC for this

**Comment by michaldybczak** [comment]
But how do I enable it in layout conf?

Should I add some line, if so where (if it matters)?
Or maybe I should change to yes on some line, if so in which one, etc,?

Aside from that, latte's option is a temporal workaround. I guess if the bug starts itching more people, we may get some more info on what is going on.

I have another idea. Maybe AWC developer might know more about what is happening? I'll ask him about that when I find the time.

**Comment by psifidotos** [comment]
I added in the gui this option... the user must enable the functionality first from preferences:

![default](https://user-images.githubusercontent.com/2216474/39886279-af59f72e-5497-11e8-99c2-e181d239162d.png)

and afterwards can set this option per layout...

![default](https://user-images.githubusercontent.com/2216474/39886288-baa496c0-5497-11e8-97b6-209344cc1764.png)

**Comment by michaldybczak** [comment]
Great! Updating latte now. At first I thought that AWC option is better but given various possible layouts, being able to control this option per layout is an awesome idea!

To summarize: jelly effect is not showing at all so I have no idea why it was triggered before. All I did was to disable several options and then restart latte-dock and then re-enable those options. Maybe some config lines for some feature got corrupted. If so, this was just singular, accidental issue that is no more so we can forget about it. Issue with AWC stripping titlebar - we have valid workaround. We'll see if other people will report that issue when some packages will get closer to versions on arch. Or maybe those libraries and dependent packages have bug that influences it and it may be fixed soon and only stable versions come to ubuntu and AWC stripping titlebar bug won't show? Either way, we'll live and see but so far we're good. At least I hope. Will see after reboot.
