### ISSUE TITLE
Pin to Activity Disappeared

### ISSUE THREAD

**Issue by BaronBlake** [psifidotos/Latte-Dock#1024]
![activities](https://user-images.githubusercontent.com/39238015/40029992-cbc353ee-57b5-11e8-88eb-b52b47cfc288.png)
![context menu](https://user-images.githubusercontent.com/39238015/40029997-d3df335e-57b5-11e8-8045-d0fa1d4f3dc9.png)

Not sure what/when this happened, but I can no longer specifiy which activities to Pin the applet to.

In other words, I was previously able to configure the dock to show specific applets on Activity A, and another on Activity B,  (and others on All Activities).

Now I no longer have the Pin feature, even after an uninstall / reinstall.

Any thoughts on this?   Thank you.

**Comment by psifidotos** [comment]
First of all Pin was only for Tasks not for applets...

Only reason that pin isnt shown is probably that you are running only one activity, it needs at least 2 or more running...

**Comment by psifidotos** [comment]
@BaronBlake this isnt a task you right clicked. Open an app and right click that app in the dock and make a screenshot please

**Comment by BaronBlake** [comment]
Can you give me an example of what is a task? All the icons were configurable previously. I would just drag the icon from the application launcher into the dock. If I drag the icon from application launcher, is that a task?

On May 15, 2018 1:50:49 AM EDT, Michail Vourlakos <notifications@github.com> wrote:

@BaronBlake<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBaronBlake&data=02%7C01%7C%7Ce373310480a94e2a3fd508d5ba27d059%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636619602512287181&sdata=GxfeFKAcv3HnzDFcia0YVXleivWgAAWZ1W8sCJCcn38%3D&reserved=0> this isnt a task you right clicked. Open an app and right click that app in the dock and make a screenshot please

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsifidotos%2FLatte-Dock%2Fissues%2F1024%23issuecomment-389050586&data=02%7C01%7C%7Ce373310480a94e2a3fd508d5ba27d059%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636619602512443440&sdata=x6jjO1i%2FfHLGAOf%2FluTumWYneK8bO4KC3xjmdTdqNHM%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAla5f5jCbYK7-K7igjzClvL8VTKHk31Pks5tymy5gaJpZM4T8xmR&data=02%7C01%7C%7Ce373310480a94e2a3fd508d5ba27d059%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636619602512443440&sdata=3JsPeABEHtkQ%2BEDnrsLeGch3aETo6Jk2Qef370XBwDE%3D&reserved=0>.

--
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by psifidotos** [comment]
> If I drag the icon from application launcher, is that a task?

it is called a launcher and when you click it, it opens a task (the application window) . The Note icon is an applet not a task. Make you sure that you have enabled at **Tweaks->Add launchers only in the corresponding area** if you changed it then there is a chance that you added your launchers as applets...

Open any window you want e.g. dolphin and right click it at the dock what does it show?

**Comment by BaronBlake** [comment]
This is great.let me check on these settings this evening and see if I can't reestablish functionality.  Thank you, I will report back.

Sent from my iPhone

On May 15, 2018, at 7:50 AM, Michail Vourlakos <notifications@github.com<mailto:notifications@github.com>> wrote:


If I drag the icon from application launcher, is that a task?

it is called a launcher and when you click it, it opens a task (the application window) . The Note icon is an applet not a task. Make you sure that you have enabled at Tweaks->Add launchers only in the corresponding area if you changed it then there is a chance that you added your launchers as applets...

Open any window you want e.g. dolphin and right click it at the dock what does it show?

**Comment by BaronBlake** [comment]
![settings3](https://user-images.githubusercontent.com/39238015/40092307-a8ffd71c-588a-11e8-93bb-0894680e758e.png)
![settings2](https://user-images.githubusercontent.com/39238015/40092308-a9194b48-588a-11e8-9853-f9ec1a75fda8.png)
![settings1](https://user-images.githubusercontent.com/39238015/40092309-a944b9c2-588a-11e8-83fd-4b04972a1b79.png)

Perhaps it's something with my settings.  When I open up dolphin it doesn't even appear on my dock?!    (I had previously deleted from my dock to see if it appears when i re-open it.)   It's like a static dock and open items don't get added to it)

Any thoughts?   Can i just delete the config file and start over?    I did uninstall and reinstall, but my actual dock came back.  

Any insight is appreciated.

Thanks,
Brandon

**Comment by BaronBlake** [comment]
Must be a setting.  New Dock, appears straight away.  I'm just deleting the dock and re-creating.. Simple fix.   Was it a setting option that is easy to see from the previous screenshots?

![new dock](https://user-images.githubusercontent.com/39238015/40092704-c04d3606-588c-11e8-91ce-e9b153414a9c.png)

**Comment by psifidotos** [comment]
You had removed Latte plasmoid probably by mistake
