### ISSUE TITLE
Icon moves to the end of the dock

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#1026]
Spotify snap moves to the end of the dock(right side) after clicking on it.

Step to reproduce:
- install Spotify snap
- pin to dock
- restart
- open Spotify

It's the 3rd icon on my dock, but when I click it moves to the end of the dock.

Looks like it's the only one doing it, I didn't try other snaps, regular apps work fine.

Version: 0.7.4-0ubuntu2
DE: KDE 5.44.0 / Plasma 5.12.5 but it was happening on the main Kubuntu 18.04 version of KDE too, I guess 5.12.3.

**Comment by psifidotos** [comment]
Yep, this is plasma libtaskmanager responsibility so Latte cant do something
