### ISSUE TITLE
Show dock using a shortcut

### ISSUE THREAD

**Issue by diegogangl** [psifidotos/Latte-Dock#1027]
Hi, thanks for the hard work! I have an idea to improve latte's workflow.
Right now when the dock is hidden or below windows the only way to bring it up is by pushing the cursor to the border where it's at,  it'd be cool to have the option to use a keyboard shortcut instead. At least for me, the screen border solution constantly makes me accidentally click on the dock no matter what side I put it in. Using a key would be more explicit, and if one had multiple docks it could create a really cool effect.

**Comment by psifidotos** [comment]
for master version that is Meta+`   it doesnt cycle through multiple docks, it finds the dock in primary scrern that has a tskmanager and shows it

**Comment by diegogangl** [comment]
Thanks! I'll check master. The most important part for me is that the shorcut can be changed (M+backtick won't work with spanish/latin keyboards) and the edge sensitivity can be disabled.
