### ISSUE TITLE
Application launcher is misplaced when invoked by super key

### ISSUE THREAD

**Issue by defue** [psifidotos/Latte-Dock#1029]
I bound the super key to show the app launcher. When dock is hidden and I press the super key the app launcher is misplaced related to the dock that appears. 
![app_as_is](https://user-images.githubusercontent.com/7314657/40296174-9d36b4d8-5ce4-11e8-84d7-e1797d5beae5.png)

It should be the same as when I click on the app icon directly
![app_to_be](https://user-images.githubusercontent.com/7314657/40296130-7acb9210-5ce4-11e8-9733-5e18bd43bc02.png)

**Comment by defue** [comment]
To be honest the fix made it worse. Now it takes half a second to show the applications launcher that is supposed to be immediately. In my opinion it would be better to keep the old behavior with overlapping app launcher that appears immediately.

**Comment by defue** [comment]
The ideal fix would be to calculate the correct position of the app launcher and show it immediately.

**Comment by psifidotos** [comment]
This is my proposal and this is how it is handled in other places of plasma also. Latte isnt positioning applets windows. So this is it.

**Comment by psifidotos** [comment]
If you believe you can send a patch for better behavior, I will review it.
