### ISSUE TITLE
Background is still transparent even if opacity is set to 100%

### ISSUE THREAD

**Issue by defue** [psifidotos/Latte-Dock#1030]
Even if I set the background opacity to 100%
![latte_dock_background_setting](https://user-images.githubusercontent.com/7314657/40297088-3bae1f64-5ce7-11e8-840f-5baa47465a18.png)

The background is still ~80% transparent
![latte_dock_opaque](https://user-images.githubusercontent.com/7314657/40297147-762c4396-5ce7-11e8-9f30-5e70306e6b2b.png)

Actually I want to make it ~90% transparent

**Comment by psifidotos** [comment]
this is plasma theme related...
Latte cant do much...

except.. you can enable Blur effect for Latte and enable also kwin effects, "Blur" and Background Contrast" or you can enable the Latte Solid option...
