### ISSUE TITLE
VirtualBox icon is pixelated when zoomed

### ISSUE THREAD

**Issue by defue** [psifidotos/Latte-Dock#1032]
All icons on the dock are in excellent quality the VirtualBox one. I noticed that in the latte config file VirtualBox string is different from others:
```
file:///usr/lib/virtualbox/VirtualBox?iconData=iVBORw0KGgoAA...
```
While firefox launcher is
```
file:///usr/share/applications/firefox.desktop
```

If I manually add the VirtualBox launcher from the app menu the icon is OK, but when I run VirtualBox it appears as a separate application under "Oracle VM VirtualBox manager" name.
![virtual_box_latte](https://user-images.githubusercontent.com/7314657/40298591-55242f1a-5cec-11e8-9b7e-43a3b8a299c3.png)

**Comment by psifidotos** [comment]
probably the virtualbox desktop file is missing a StartupWMClass record...
