### ISSUE TITLE
Dock is not shown when location bar is down in Firefox

### ISSUE THREAD

**Issue by defue** [psifidotos/Latte-Dock#1035]
How to reproduce:
- Make the dock dodge all windows
- Open Firefox in maximized window
- Make the location bar open like on screenshot below
![firefox_location_bar](https://user-images.githubusercontent.com/7314657/40418779-eb1eaafe-5e8b-11e8-92d0-32999f918ca5.png)
- Or click on down arrow in firefox toolbar to show downloads
- Move mouse to the dock location and it won't appear

The expected behavior is to show the dock.

Actually the main purpose of the dock is to provide the ability to switch between windows. I should be able to switch to another window in those situations.

**Comment by psifidotos** [comment]
Can you reproduce with any other app!

**Comment by psifidotos** [comment]
any other app?

**Comment by defue** [comment]
Yes, Dolphin for example. Click on the control button to make the drop down menu appear and then try to show the dock.

**Comment by psifidotos** [comment]
ok this is kwin edge default behavior and can be reproduced also with plasma panels... can you report it upstream at bugs.kde.org if you want an answer why this is happening... If you dont care about kwin edges and the benefits that brings you can disable that behavior from:

(disable) Tweaks->Activate KWin edge after hiding

**Comment by defue** [comment]
If I disable the "KWin edges" option the dock appears but is not active, i.e. I need to click on it to make the animation working.

**Comment by psifidotos** [comment]
I suppose that kwin behavior is better... ask kwin developers because there is a chance that kwin edges behavior follows some guidelines
