### ISSUE TITLE
Zoom on Hover (parabolic effect?) slowness

### ISSUE THREAD

**Issue by ayberkozgur** [psifidotos/Latte-Dock#1036]
I have the following problem:
[https://youtu.be/4j_544r_vh0](https://youtu.be/4j_544r_vh0)
Essentially, after being unhidden, the Zoom on Hover effect is very slow and unresponsive while the cursor moves a lot. As soon as the cursor slows down, the effect "catches up" and becomes responsive.

**Comment by psifidotos** [comment]
v0.7 issue, has been fixed in master

**Comment by ayberkozgur** [comment]
Yes I can confirm this problem is gone as of 0.7.79, thanks.
