### ISSUE TITLE
Right click on Latte does not show anything

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#1037]
Latte version: https://github.com/psifidotos/Latte-Dock/commit/8866047099ecb80d5b83f9c32a6f5fe87568d75e
Tried removing the old Latte configs.

**Comment by psifidotos** [comment]
cant reproduce this... are you  sure you have built the package correctly?

**Comment by trmdi** [comment]
Ok, after rebuilding latte with `kf5_version 5.30.0` and update the whole system, it works again. Dunno what caused it ?

**Comment by psifidotos** [comment]
Frameworks running on the system and frameworks to build Lattemust hav
