### ISSUE TITLE
Low quality icon under hover

### ISSUE THREAD

**Issue by ndtoan96** [psifidotos/Latte-Dock#1039]
Some icons such as chromium, inkscape,... break up when I hover the mouse over it. (see picture below)
![untitled](https://user-images.githubusercontent.com/33489972/40536687-2d265b7a-6037-11e8-8a84-3820160d1656.png)

**Comment by psifidotos** [comment]
this is upstream not Latte fault

**Comment by ndtoan96** [comment]
What do you mean exactly? Is it KDE's fault, or the theme I'm using? Is there any way to fix it?

**Comment by psifidotos** [comment]
> Is it KDE's fault, or the theme I'm using? Is there any way to fix it?

it can be plenty things...

1. the desktop file is missing StartupWMClass (you can reproduce this with plasma panels) it is either Chromium fault or Distro fault.
2. the plasma libtaskmanager doent identify correctly the icon (so you can reproduce this with plasma panels) this is plasma fault
3. it can be icon theme fault but if that was case then by changing the plasma theme it should be fixed

all the above arent Latte responsibility
