### ISSUE TITLE
Parabolic animation too slow on start.

### ISSUE THREAD

**Issue by relmay** [psifidotos/Latte-Dock#1040]
When i hover my mouse above icons it's slowly popup, but when i stop my cursor for one sec animation speed back to normal. In debug mode, there are no errors.

Here is a [video](https://youtu.be/tYHflkvmtvc) of this bug.
Here is my [settings](https://imgur.com/ZZ8GYsp).
Here is my [system info](https://gist.github.com/relmay/1926d2c4b69f34bdc579c6d291024293).

**Comment by psifidotos** [comment]
has been fixed in master
