### ISSUE TITLE
Compilation warning for Layout::appliedActivities

### ISSUE THREAD

**Issue by gagbo** [psifidotos/Latte-Dock#1043]
I had a few warnings while compiling from source but one of them got my attention (rough translation from french, sorry) :
```make
[ 47%] Building CXX object app/CMakeFiles/latte-dock.dir/layout.cpp.o
/home/gagbo/soft/Latte-Dock/app/layout.cpp: In member function « const QStringList Latte::Layout::appliedActivities() »:
/home/gagbo/soft/Latte-Dock/app/layout.cpp:732:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
``` 

The function is [here](https://github.com/psifidotos/Latte-Dock/blob/591ce6c4d5af7298365a474e89c10ce3a9050a5e/app/layout.cpp#L717). Maybe it's normal and I'll never get crashes, maybe we just need the same return as when `m_corona == nullptr`, I'm just reporting something that felt weird.

**Comment by psifidotos** [comment]
it is ok because it never reaches to the end... m_corona->layoutManager()->memoryUsage()  can have only two values Single and Multiple...

but no problem to solve this... I dont get such warning though in my system, what compiler are you using?

**Comment by gagbo** [comment]
I'm on Fedora 28, which seems to be quite on the edge with regards to gcc : 
```
gcc (GCC) 8.1.1 20180502 (Red Hat 8.1.1-1)
```
