### ISSUE TITLE
Icons in random position

### ISSUE THREAD

**Issue by kalasni** [psifidotos/Latte-Dock#1044]
Is there any way to keep the icons always in the same position? In each session the icons appear in a random position. 
I'm using Latte on Kubuntu 16.04

**Comment by psifidotos** [comment]
what is your Latte version and your plasma version?

**Comment by kalasni** [comment]
Plasma 5.8.9 and Latte version 0.6.2

**Comment by psifidotos** [comment]
these are two old versions... it must have been fixed upstream to plasma...
