### ISSUE TITLE
Disable bounce animation?

### ISSUE THREAD

**Issue by marvolo3d** [psifidotos/Latte-Dock#1046]
Non-critical:

Any chance we could get the option to disable icon bounce animation? Or have it time out after a set number of bounces? I have a few applications that frequently trigger the bounce animation and it never times out, switching application focus back and forth won't even stop it. 

I see animation can be disabled altogether, but I do like having the hover zoom animation.

**Comment by psifidotos** [comment]
You mean the needsattention bouncing?

**Comment by psifidotos** [comment]
from today all new issues should be reported to: https://bugs.kde.org/
