### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#106]
Hi, I have edited the files
```
/Latte-Dock-master/po/app/it.po
/Latte-Dock-master/po/plasmoid/it.po
```
for the Italian translation... 
well, how can I do to upload the files ?

I can not update the file ```/Latte-Dock-master/po/plasmoid/it.po``` ... I guess you must first uninstall the plasmoid it? ...but I can not :(

**Comment by omni6** [comment]
hey, if you have forked latte-dock and you change files in pisififodotos-repository github should suggest you to create a new branch in your-forked-repo. for this you can create a pull request.

**Comment by JenaPlinsky** [comment]
@omni6 Thanks a lot for the suggestion. I've Just done ;)

**Comment by JenaPlinsky** [comment]
despite compiling with ./install.sh
the translations of 
 ```
/Latte-Dock-master/po/plasmoid/it.po
```
 are not updated
while about
```
/Latte-Dock-master/po/app/it.po
```
everything works fine
