### ISSUE TITLE
small and perhaps unnecessary aesthetic suggestions

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#109]
buttons, with different alignment
![screenshot_20170129_182301](https://cloud.githubusercontent.com/assets/24593950/22406399/ecd4c566-e652-11e6-846c-676d77b1af50.png)

![screenshot_20170129_183107](https://cloud.githubusercontent.com/assets/24593950/22406402/f1886e8c-e652-11e6-97b4-2bb664ad103e.png)

**Comment by audoban** [comment]
1. The buttons for Location are arranged clockwise. But maybe we can rearrange it.
Location
[ left, bottom, top, right ]

I think it's fine, but @psifidotos should agree as well, however I like it more as it currently is.

2. If the strings are very long then the space is not distributed evenly, remember that the contents of the buttons is more important. You can try to play with the strings in Itialian.

3. It is easy to implement, but I do not like.

**Comment by JenaPlinsky** [comment]
it's not important !!! they are foolishness I know;)

**Comment by audoban** [comment]
@JenaPlinsky Do not worry any suggestion is welcome.
