### ISSUE TITLE
indicators

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#110]
I am using Latte with the mode "shows only the tasks of the current activity"

- I have three open instances of Dolphin but the icon show the number 2 and has two lighted indicators

- I have only one instance of systrmmonitor but the icon show the number 2, and has one lighted indicators

is it correct ?

- The "Indicator for active window group" option I did not understand its mean

**Comment by psifidotos** [comment]
this is the default behavior... 2 dots mean a group of windows, not the number of that windows

> The "Indicator for active window group" option I did not understand its mean

When you have 2 dolphin windows and one is active, it shows a line and a dot next to it

**Comment by JenaPlinsky** [comment]
Ok about the indicators, I understood their meaning while the number superimposed,that I do not understand at all "number 2 / and three dolphin instances"

**Comment by psifidotos** [comment]
What number 2? Any screenshot?

**Comment by JenaPlinsky** [comment]
![screenshot_20170129_220702](https://cloud.githubusercontent.com/assets/24593950/22407884/5e1ee4ce-e66f-11e6-9e01-1772038378be.png)

**Comment by audoban** [comment]
> I have three open instances of Dolphin but the icon show the number 2 and has two lighted indicators

The indicator don't tell you how many instances exist, only indicates that there are 2 or more.

> I have only one instance of systrmmonitor but the icon show the number 2, and has one lighted indicators

**Comment by psifidotos** [comment]
This must be a bug... the numbet 2 you see is used to show running tasks and their progress... e.g. copying files, directories... but when the task finishes the number should hide

**Comment by JenaPlinsky** [comment]
It's not a bug !!! ...there were still 2 active processes
![screenshot_20170129_231608](https://cloud.githubusercontent.com/assets/24593950/22408457/7b6dc360-e679-11e6-8660-8394c4551514.png)

**Comment by audoban** [comment]
@psifidotos  But is it normal for the systemmonitor to show 2 progress tasks?...

**Comment by JenaPlinsky** [comment]
mhhhh true!, for that you are right

**Comment by JenaPlinsky** [comment]
@audoban 
Ahahhaha A are beautiful, videos, what are you doing about plasma
Audubon, Ahhhahahahahah I've just saw your amazing videos, that are you doing, about plasma with alergia y energía. Bravo .... !!!! olè

**Comment by audoban** [comment]
@JenaPlinsky What videos do you mean??

**Comment by JenaPlinsky** [comment]
https://www.youtube.com/watch?v=eO7Y8y-FVRI
https://youtu.be/dZ79kwhkjDc
https://youtu.be/Rf5ebP9-CR8

**Comment by JenaPlinsky** [comment]
you tried the project plasmatube semancico of kde.store?
I like it when it's docked in Latte even if full of bugs

**Comment by audoban** [comment]
The first video is of YoyoFernandez and the others are of Elav.

> you tried the project plasmatube semantic of kde.store?
I like it when it's docked in Latte even if full of bugs

:), I'll have to try it.

**Comment by psifidotos** [comment]
> But is it normal for the systemmonitor to show 2 progress tasks?

It hasnt ever happened to me... it could be a lbtaskmanager bug of categorization, systemmonitor might thinks is dolphin...

@JenaPlinsky can you test when number 2 indicator for systemmonitor is happening?

**Comment by JenaPlinsky** [comment]
it just re-occurs, I will let you know

**Comment by audoban** [comment]
@psifidotos this is a bug of libtaskmanger?

**Comment by psifidotos** [comment]
@JenaPlinsky has this reappeared? did you notice your steps to reproduce it?

@audoban I believe yes but we must know how to reproduce it...

**Comment by JenaPlinsky** [comment]
sorry, I can not reproduce it

**Comment by psifidotos** [comment]
@JenaPlinsky ok... we can close it and if it happens again we re-open it...
