### ISSUE TITLE
Improve the Latte experience with "folder view"

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#117]
![screenshot_20170131_080009](https://cloud.githubusercontent.com/assets/24593950/22455392/82c81796-e78c-11e6-9b33-5b2d086ec2d1.png)

/df03dbcc-e78b-11e6-8b39-748f4a29648e.png)
in order to improve the experience with Latte to the new features of the "folder view", introduced in 5.9 
https://www.youtube.com/watch?v=QIRGoOzbp88 ...I ask:
if the user has the need to move files or folders within a docked "folder view", **only in these cases**, 
would be it possible and wise to inhibit (I do not know how, maybe by dragging combined with a pressed key) the ability to insert new objects in Latte ?
doing so would be much more comfortable, move files within the docked "folder view"

**Comment by psifidotos** [comment]
as mentioned in the video this is for Plasma 5.10,
for locked folderviews this should work just fine with current implementation and for animated folderviews it just needs some small minor tweaks

**Comment by psifidotos** [comment]
somethink similar as a technique is already supported for example you can open a file which any launcher you want from the latte dock. You can open a png or jpg file by just dropping them on the gwenview or gimp launchers...

**Comment by psifidotos** [comment]
Can someone test this for plasma 5.10?

**Comment by audoban** [comment]
this applet give much problems, I want to do a fork for Latte, what do you think @psifidotos ?

**Comment by psifidotos** [comment]
I dont object but it is a very big codebase... when I looked at it this is not an applet, it is the entire desktop qml applet that is used...
take a look into it..

**Comment by audoban** [comment]
Maybe a folderview from scratch. I do not like doing forks.

**Comment by psifidotos** [comment]
@audoban if you think you can sustain the effort... no prob... either way is just a plasmoid and can be removed at any point from the user... 

my concerns are only because of the big codebase the folderview has and the many features already supports and will be added in the feature...

if you go on with this, the c++ plugin which will be needed should not be inside the current liblatteplugin, the plasmoid should be installable/uninstallable completely separately from Latte dock...

**Comment by JenaPlinsky** [comment]
moving file on launchers work fine but is not possible move file inside a subfolder in a docked folder-view (appears placeholder add applets)
     the fact is that, the placeholder for the addition of a new applet is correct !!! and I do not know how to suggest a smart way to be able to open and scroll through the folder-view without creating confusion

**Comment by psifidotos** [comment]
Do you work in latest plasma master?

Does this work on the reqular plasma panel?

**Comment by JenaPlinsky** [comment]
I used a script with these commands, this should be fine, right?
git clone https://github.com/psifidotos/Latte-Dock.gi
bash "$target/Latte-Dock/install.sh"

the default plasma panel has the same behavior than Latte
it could be a folder-view plasma regression

**Comment by psifidotos** [comment]
to test master:

-  **git clone https://github.com/psifidotos/Latte-Dock.git**
- **cd Latte-Dock**
- **sh install.sh**

> the default plasma panel has the same behavior than Latte
> it could be a folder-view plasma regression

this feature was introduced in plasma master and will be ready for Plasma 5.10, not 5.9

**Comment by JenaPlinsky** [comment]
Ok then I can confirm that I'm always installing the master branch



`this feature was introduced in plasma master and will be ready for Plasma 5.10, not 5.9`
Shit !!!
In fact ... I did not remember this, you are right !! ..indeed I got to go to Leap aahaha :)

**Comment by JenaPlinsky** [comment]
You can consider this issue fixed, with plasma_5.9.90 everything works fine

**Comment by psifidotos** [comment]
;)
