### ISSUE TITLE
Raise application window when file is draged over it's icon

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#118]
Suppose i want to attach file to email message and email client window is minimized. I drag file from file manager over email client icon in the dock, `+` icon appears for starting new instance. It should raise and bring window to the front if application is already running so file can be dropped on to that window.

Issue #117 is somewhat related.

**Comment by psifidotos** [comment]
this could of course implemented but needs a little design decisions.

I propose the following:
- when a file is dropped on a launcher this file is opened with the launcher's app (current behavior)
- when a file is hovered on a minimized window this window is shown and if the file leaves without dropping it then the window becomes minimized again
- when a file is hovered on a normal shown window nothing happens, if the file is dropped then it is opened with that app. (current behavior)
- if a file is hovered above a group of same windows nothing happens and if it is dropped then it is opened with that app. (current behavior)

**Comment by rokups** [comment]
> when a file is hovered on a minimized window this window is shown and if the file leaves without dropping it then the window becomes minimized again

This may be a convenient behavior but being a non-default one i think it should be configurable. People are used to window staying up and it may even be desired behavior. For example in cases where user changes his mind about dropping file but would like to continue interacting with the window.

> when a file is hovered on a normal shown window nothing happens

That window should be brought to front because other windows may be covering it. That is how normal taskbar works.

> if a file is hovered above a group of same windows nothing happens and if it is dropped then it is opened with that app. (current behavior)

Then we would not have a way to drop file on a window that belongs to a group. Default panel allows this by popping a menu where user can continue dragging file over desired window.

All in all i think best would be emulating default taskbar. Any additional/custom behaviors should be configurable.

**Comment by psifidotos** [comment]
> All in all i think best would be emulating default taskbar. Any additional/custom behaviors should be configurable.

as long as this is feasible with Latte...

**Comment by psifidotos** [comment]
@rokups is it possible to create a numbered list showing what works and what doesnt in Latte from the default taskmanager behavior concerning the dragging a file situation?

**Comment by rokups** [comment]
- [x] Dropping file on the panel always starts a new instance of application passing file as parameter.
- [ ] Drag on to minimized window taskbar item - window is be raised.
- [ ] Drag on to window (which is behind other windows) taskbar item - window is brought to front.
- [ ] Drag on to window group taskbar item - popup list of windows is displayed.
    - [ ] Dragging and hovering file over window list item for about 200ms raises that window.
    - [ ] Minimized windows are grayed out in the list.

**Comment by psifidotos** [comment]
this should be fixed in master except the group case, but it is something I would like it to be solved together with #118

**Comment by psifidotos** [comment]
#138

**Comment by psifidotos** [comment]
ok... this is supported now... and instead of group windows list, we use for dropping files the previews window!!!
