### ISSUE TITLE
latte dock sometimes fails to dynamically increase length according to content (applets size change)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#119]
latte dock panel decreases its size dynamically according to content, but it fails to increase it when required. It successfully does though when mouse hovers the latte panel.

Please see:

![image](https://cloud.githubusercontent.com/assets/3875196/22483174/1783b2e0-e7ca-11e6-95b3-4510c366fb1b.png)

**Comment by kupiqu** [comment]
Please compare with:

![image](https://cloud.githubusercontent.com/assets/3875196/22483281/8476d512-e7ca-11e6-9854-eda9374e2b60.png)

**Comment by kupiqu** [comment]
a more clear example:

![image](https://cloud.githubusercontent.com/assets/3875196/22483468/6328025e-e7cb-11e6-95f1-98ee777abadb.png)

**Comment by kupiqu** [comment]
Alignment is Center and misses a bit of content in either side

**Comment by psifidotos** [comment]
what is the icon size shown in the images?

**Comment by kupiqu** [comment]
> what is the icon size shown in the images? 

28 in the screenshots, I also tried 32

**Comment by psifidotos** [comment]
there is no 28, you mean 24?

Στις 1 Φεβ 2017 13:11, ο χρήστης "kupiqu" <notifications@github.com> έγραψε:

> what is the icon size shown in the images?

28 in the screenshots, I also tried 32




—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/psifidotos/Latte-Dock/issues/119#issuecomment-276631848>,
or mute the thread

**Comment by kupiqu** [comment]
Right, sorry, I meant 32 (and 40)

> there is no 28, you mean 24?

**Comment by psifidotos** [comment]
If you add more windows to increase dock size does the icon size shrinks to 24 and 16?

**Comment by psifidotos** [comment]
@kupiqu one update also, in master I have just added the possibility to add debug flags when executing Latte...

one of them is: **_--with-window_**
so you can execute:

`latte-dock --debug --with-window`

when this problem appears I would like a lot to see all the values mentioned in the previous window...

an example:
![debugwin](https://cloud.githubusercontent.com/assets/2216474/22523025/94b8ff8e-e8c6-11e6-9a3f-7ffba4615b00.png)

**Comment by audoban** [comment]
@psifidotos nice feature

**Comment by kupiqu** [comment]
before hovering:

![image](https://cloud.githubusercontent.com/assets/3875196/22577005/19ea7afe-e98d-11e6-9f47-f3c5242f9b62.png)

after:

![image](https://cloud.githubusercontent.com/assets/3875196/22577015/30145a52-e98d-11e6-9295-bd81d066aba9.png)


(sorry for the latency, I've been busy)

**Comment by psifidotos** [comment]
this a wrong mask calculation issue...

have you noticed when does before state occurs?

**Comment by kupiqu** [comment]
This happens in two different conditions. It happens to me at startup, and also when an applet changes size (extra icon appearing in systray, or modifying short to long date, or moving from icon to  full name in user switch, to tell some examples).

**Comment by psifidotos** [comment]
Ok... to be honest I hadnt thought that!! that applets and not our plasmoid change their length by themselves...

I'll try to think of something...

**Comment by kupiqu** [comment]
:+1:

**Comment by psifidotos** [comment]
@kupiqu is it possible to test branch **fix119** for this ?

**Comment by kupiqu** [comment]
It works!
