### ISSUE TITLE
multi-screen support

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#12]
special care for multi screens must be taken into the app and the configuration window...

**Comment by audoban** [comment]
Yes, I will be very careful.

**Comment by rokups** [comment]
Dock crashes when setting location to the right when second screen is on the right.

**Comment by psifidotos** [comment]
> Dock crashes when setting location to the right when second screen is on the right

you mean that setting dock's location to bottom, left or top does not crash in that case?

**Comment by rokups** [comment]
Hmm i can not trigger that same crash any more. Too bad i did not save log, but i noticed something about "widget" and "screen" in the log.

I did a new test. Saved my working config and did these steps:

My desktop setup is as follows:

    [ main screen ][ secondary screen ]

1. Dock initially is at the bottom of main screen.
2. Set dock to the left. Works.
3. Set dock to the top. Works.
4. Set dock to the right. Works, dock is on the right of main screen as one would expect.
5. Set dock to the bottom. Crash.

After the crash restarting dock fails, it keeps crashing. This is difference between my working config and crashing config:

	# Good

	[Containments][1]
	formfactor=2
	location=4

	[Containments][9]
	formfactor=2
	location=4

	# Bad
	[Containments][1]
	formfactor=3
	location=6

	[Containments][9]
	formfactor=3
	location=6

Restoring good config works. Tried multiple times, setting dock to all edges work, but once dock is set to the right moving it to other edges rarely works but most of the time crashes.

**Comment by psifidotos** [comment]
ok... this is totally something to do with the multi-screen setup which is going to be supported in 0.7 version...

**Comment by psifidotos** [comment]
Just to add in the discussion, supporting multi-screen setups we must provide the following:

- easy screen switching for every dock
- a dock to be able to be on all screens (global dock) if it is possible (this is more more difficult that it sounds)
- no crashes are acceptable when the user alters its screens layouts (de-activate monitors etc.)

**Comment by psifidotos** [comment]
@audoban the next days i will start experimenting with multi screens. How do you imagine to set the dock's screen?

One way is through the configuration window, will we add a screen multiple choice in behavior?

The other way is through the context menu(thus the right click menu)?

**Comment by psifidotos** [comment]
@rokups @Petross404 @JenaPlinsky @kupiqu if you have a multi screen setup and you want to test the new multi-screen behavior, you could try the **multiscreens** branch

**Comment by psifidotos** [comment]
**_so.... this is landed in master!!!_** 

**_With multi-screen support
the user can set for its docks either to be always
on the primary screen or an explicit one... The
docks are loaded and removed automatically on
screen changes_**

**Comment by kupiqu** [comment]
I think this broke snap. I don't get snap anymore unless I git checkout to the commit immediately before this was landed to master.

Could you please check it out?
