### ISSUE TITLE
cannot build project on FreeBSD.

### ISSUE THREAD

**Issue by Norbytus** [psifidotos/Latte-Dock#120]
I changed two string in install.sh for FreeBSD and in compiling time i have error
Text error:
in file included from .../Latte-Dock-0.5.91/app/visibilitymanager.cpp:22:
.../Latte-Dock-0.5.91/app/visibilitymanager_p.h:59:44: error: implicit instantiation of undefined template 'std::__1::array<QMetaObject::Connection, 4>'
    std::array<QMetaObject::Connection, 4> connections;
I fixed this problem did include array in visibilitymanager_p.h but after a have second problem and i don't how fix her 
text error:
.../Latte-Dock-0.5.91/liblattedock/iconitem.cpp:98:29: error: call to 'make_unique' is ambiguous
                m_svgIcon = std::make_unique<Plasma::Svg>(this);

**Comment by audoban** [comment]
Your compiler support C++14?

**Comment by Norbytus** [comment]
Fix this problem, set in env gcc6

**Comment by audoban** [comment]
How do you fixed?

**Comment by Norbytus** [comment]
I set root env
export C=path_to_gcc(Y)
export C=path_to_gcc(Y)
export CXX=path_to_g++(Y)
Where Y it's version gcc

**Comment by Norbytus** [comment]
But after build whatever not work. I see widget in widget's list but in desktop i have error.

**Comment by psifidotos** [comment]
> But after build whatever not work. I see widget in widget's list but in desktop i have error.

what is the error for the plasmoid ?

if you just run **_latte-dock --debug_** what happens?

**Comment by Norbytus** [comment]
`[1]    3477 trace trap (core dumped)  latte-dock --debug`

**Comment by psifidotos** [comment]
can you please follow these instruction?

You could try to debug it if you want...

- Install ddd
- ddd latte-dock
- in ddd window write and execute, run
- when it crashes, click status from the menu, backtrace

This will show you a window with numbered lines, this could be helpful for us...

**Comment by Norbytus** [comment]
![_2017-02-02_13-03-09](https://cloud.githubusercontent.com/assets/13504897/22544979/6509f362-e950-11e6-9f14-9688c36e5263.png)

**Comment by psifidotos** [comment]
this could be something with the c++ version mentioned also earlier but i cant be sure

**Comment by Norbytus** [comment]
Now i have another error
I change LD_LIBRARY_PATH to another gcc version(gcc6 or gcc5)
![_2017-02-02_15-18-35](https://cloud.githubusercontent.com/assets/13504897/22549138/4b3723b6-e963-11e6-8932-da6257d44f85.png)

**Comment by psifidotos** [comment]
is this a crash or just it stops there?

are you using wayland?
what is you plasma, kde frameworks and qt version ?

**Comment by psifidotos** [comment]
and which is your graphic card and driver?

**Comment by Norbytus** [comment]
kde frameworks 5.30.0
qt 5.7.1
GeForce210 Driver 3.3.0.NVIDIA 340.101

**Comment by audoban** [comment]
@Norbytus  Please build Latte with the same version with which KDE Frameworks were compiled.

**Comment by Norbytus** [comment]
I did not compile kde. But i know he compiled with cclang, but latte-dock don't wanted compiled with him

**Comment by audoban** [comment]
which version of cclang?

**Comment by psifidotos** [comment]
as long as there arent any more infos...
