### ISSUE TITLE
Application launcher unremovable from latte

### ISSUE THREAD

**Issue by Magnus2552** [psifidotos/Latte-Dock#121]
When you drag items into the latte app (for example when you search for the app in krunner and then drag and drop it), it creates a launcher that is not removable. Also the analogue clock that is by default in latte, is not removable with GUI. Is it possible to at least manually delete these launchers again? It would also be very convenient do have a GUI right click entry to remove these.
![konsole_unremovable](https://cloud.githubusercontent.com/assets/21310755/22561713/adf3a2d4-e979-11e6-9f24-9a5ea0e85be1.png)

**Comment by psifidotos** [comment]
to remove any applet you want you must be in editing mode...

To do that just open the Latte settings and after that the remove action is appearing in applets context menu

**Comment by Magnus2552** [comment]
Oh wow, sry I didn't see this. This is much better then a right click menu. Sry for bothering you and thanks for this really nice plasmoid, keep up the good work! :)
I will close the issue then...

**Comment by psifidotos** [comment]
no worries!!! ;)

**Comment by psifidotos** [comment]
thank you for the kinds words!!!
