### ISSUE TITLE
Some icons are low res when an instance is started

### ISSUE THREAD

**Issue by magnus-gross** [psifidotos/Latte-Dock#123]
I added konsole to my latte menu. The konsole icon is a svg so it should be crisp. As you can see in the image, the konsole icon on the left is in fact crisp, however, when I start an instance of it, it spawns a new icon in the bar, which is very blurry compared to the one that I started it from (the one on the right side in the image).
![konsole_blurry](https://cloud.githubusercontent.com/assets/21310755/22563070/6d42d13c-e97f-11e6-973c-065042b63877.png)
Any idea how to fix this?

**Comment by psifidotos** [comment]
the console icon on the left is it a launcher or an applet ?

what is the icon size set for Latte?

**Comment by Magnus2552** [comment]
The console icon on the left is a launcher.
I have maximized the icon size to 128 to make it more clear, but the icon is already blurry on lower resolutions.

**Comment by Magnus2552** [comment]
This is btw also true for some applications, that do not have a launcher. For example kwallet should be crisp too, because it has a svg as well (as you can see in the Alt+Tab it is in fact crisp), but in latte-dock it is blurred. ;)
![kwallet](https://cloud.githubusercontent.com/assets/21310755/22565009/f5f68f62-e986-11e6-8ca2-b93ed473f3e4.png)

**Comment by audoban** [comment]
What is your icon theme? I need it to try locally.

**Comment by audoban** [comment]
please try with plasma icontask.

Add icon task to desktop view, and make it big.
Tell me if this happens too.

**Comment by Magnus2552** [comment]
My icon theme is [la-capitaine](https://github.com/keeferrourke/la-capitaine-icon-theme), but slightly patched, meaning I got the konsole icon from [Luv-Dark](https://github.com/NitruxSA/luv-icon-theme/blob/961ba1f3edc2854e31dc345e36a5e34d3c095e21/L%C3%BCv/apps/32/utilities-terminal.svg)
I do not quite understand what you mean with your second comment though. Do you want me to try a native KDE icon task manager and look if the icons get blurry there too?

**Comment by psifidotos** [comment]
@Magnus2552 yes try the native plasma taskmanager, the same problem should also appear there as we use the same infrastucture with them...

Easy way to test this is:
- add the icon only plasma taskmanager in your desktop
- increase its size enough so the icons become bigger than 64px
- you should notice the same problem

we just need a confirmation...

**Comment by Magnus2552** [comment]
Ok, I just tested it and the problem appears in the native plasma taskmanager as well, so I guess it is not a bug of yours.
I also just upgraded to Plasma 5.9 and the problem disappeared for some applications (including konsole) but it still is appearing for other applications (like kwallet or sublime text).

**Comment by psifidotos** [comment]
@Magnus2552 either way thank you for the report!! :)

**Comment by audoban** [comment]
@Magnus2552 Is more complicated than it seems.

KWallet and Sublime text have icons on SVG?

**Comment by Magnus2552** [comment]
Sublime text not entirely sure (the icon theme provides a svg, but sublime switches the icon at runtime to a png)
With kwallet I actually just mean the icon of the KDE Wallet service as seen in the screenshot above (not kwalletmanager) and I am pretty sure that the icon comes from my icon theme, because it wasn't like this without the icon theme, which means it has to be a svg, because every icon in this icon theme is a svg. I don't know the name of the icon though and couldn't find the icon, so I cannot say for sure... I will keep trying to find it...

**Comment by audoban** [comment]
@Magnus2552  thanks a lot. I needed to confirm it.
I'm trying to fix these issues from plasma upstream, I think this week I fix it.

**Comment by Magnus2552** [comment]
Wow, this sounds really cool!
Thanks for your effort, I really appreciate it! :)

**Comment by JenaPlinsky** [comment]
taskmanager - ksysguard
taskmanager - systemmonitor
![screenshot_20170207_021145](https://cloud.githubusercontent.com/assets/24593950/22674258/433b5f5e-ecdf-11e6-9c1e-ffc9cd07e9e7.png)

**Comment by psifidotos** [comment]
@Magnus2552 @JenaPlinsky 

- Can you please confirm that this is still an issue in Plasma 5.9? 
- Have you touched this icons by yourself, have you changed something for them?

**Comment by Magnus2552** [comment]
Yes, it is still an issue in 5.9. No, I have not touched anything except using an alternate icon theme.

**Comment by JenaPlinsky** [comment]
I have not touched too

**Comment by psifidotos** [comment]
@Magnus2552 @JenaPlinsky 

I found this: https://bugs.kde.org/show_bug.cgi?id=375497

can you confirm that you still have this problem with KDE Frameworks: 5.31 ?

**Comment by Magnus2552** [comment]
Yes, I can confirm that the bug is still there:

![temp](https://cloud.githubusercontent.com/assets/21310755/23519422/1fa244f4-ff77-11e6-891e-425261468868.png)

**Comment by psifidotos** [comment]
I want a case to reproduce this in my system... for which latte has that issue and plasma task manager doesnt...
Is it possible?

**Comment by psifidotos** [comment]
@Magnus2552 checked it...
this is upstream...
it should happen also with default plasma taskmanager...

**Comment by psifidotos** [comment]
@JenaPlinsky this should also be the case for your report...
it should also happen with the plasma taskmanager...

@audoban  is right, libtaskmanager returns empty strings for the source string and that means that QIcons are created instead of using the svg files...

**Comment by Magnus2552** [comment]
Yeah, I can confirm that this happens with the default plasma taskmanager as well.

**Comment by JenaPlinsky** [comment]
@psifidotos ...fantastic news
I can confirm, this also happens with default plasma taskmanager

**Comment by psifidotos** [comment]
as long as this isnt Latte fault should be closed...

**Comment by romanlex** [comment]
Hello. I have plasma 5.11.4 and Latte Dock 0.7.2
My phpstorm icon is ugly. 
![image](https://user-images.githubusercontent.com/3369304/33998954-2b2ac1c4-e0fa-11e7-80c9-203f6791f6cf.png)

But when I run app icon has correctly size. Why?
![image](https://user-images.githubusercontent.com/3369304/33998929-190a0cb6-e0fa-11e7-9061-5dab7d697bae.png)

**Comment by psifidotos** [comment]
I suppose something is wrong with your phpstorm desktop file...

**Comment by romanlex** [comment]
@psifidotos 
my desktop file is fine:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=PhpStorm
Icon=/opt/phpstorm/bin/phpstorm.png
Exec="/opt/phpstorm/bin/phpstorm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-phpstorm
```
and another icon on second desktop work properly
![image](https://user-images.githubusercontent.com/3369304/34009788-476be900-e11b-11e7-9975-153b1f548076.png)

**Comment by psifidotos** [comment]
> StartupWMClass=jetbrains-phpstorm

is this correct by double checking the app with xprop?


> Icon=/opt/phpstorm/bin/phpstorm.png

this is a png file (no svg) and not a generic icon found from the icon theme...

**Comment by romanlex** [comment]
> is this correct by double checking the app with xprop?

Yes ```WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "jetbrains-phpstorm"```

> this is a png file (no svg) and not a generic icon found from the icon theme...

In my webstorm desktop file icon is png - all work perfectly
```
[Desktop Entry]
Version=1.0
Type=Application
Name=WebStorm
Icon=/opt/webstorm/bin/webstorm.png
Exec="/opt/webstorm/bin/webstorm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-webstorm
```

**Comment by psifidotos** [comment]
> Yes

doesnt look like correct... based on the xprop info it should be:

`StartupWMClass=jetbrains-phpstorm`

and not 

`StartupWMClass=jetbrains-webstorm`

**Comment by psifidotos** [comment]
1. dont you have that issue with plasma taskmanager?
2. if you change applet sizes what is happening?

**Comment by romanlex** [comment]
> dont you have that issue with plasma taskmanager?
> if you change applet sizes what is happening?

I understand, thx. I'm add widget with taskmanager icon and now I see what icon is wrong(((
https://youtu.be/8vE4HQz_T6s 
When I start app icon replaced on properly size. You known what i'm doing wrong and why my icon is broken?
