### ISSUE TITLE
Latte, don't rise the dock-panel

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#124]
Latte does not want to know to get up and after a bit of trial with Alt + Tab it has crashed!

[File di testo.txt](https://github.com/psifidotos/Latte-Dock/files/750577/File.di.testo.txt)

![screenshot_20170203_142227](https://cloud.githubusercontent.com/assets/24593950/22593361/57fb363a-ea1e-11e6-905e-a495cab93fce.png)

**Comment by psifidotos** [comment]
must be duplicate for #103

**Comment by JenaPlinsky** [comment]
# 103 ... it flickers and then, in some way, it work again
# 124 ... it does not flicker and then the process crashes

**Comment by psifidotos** [comment]
@JenaPlinsky can you please check again with latest master for:

#103 #124 ?

**Comment by JenaPlinsky** [comment]
I've just upgrade from master and I note:
#103 the problem is the same as before (notes #103  for details)
#124 I can not replicate

**Comment by psifidotos** [comment]
should be fixed in master
