### ISSUE TITLE
adding applets in normal Latte state (e.g by dropping) in Justify alignment breaks applets order and splitter positions

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#127]
I realized that if I remove an applet from latte panel (justified alignment), then the organization of the remaining applets gets disrupted. I would expect the order and splitter positions to remain the same.

**Comment by psifidotos** [comment]
The order is  broken on the next latte restart or directly after going to normal state instead of editing mode?

Can you give me screenshot of your editing mode to see what applets and order do you have and which applet you are removing afterwards and breaks the order?

**Comment by kupiqu** [comment]
yes, sorry, at following latte startup.

actually I realized because I'm trying to add this network monitor (https://github.com/kotelnik/plasma-applet-network-monitor), but whenever I try latte crashes (it works in a plasma panel), so I gave a shot to the one from plasma, but looks ugly in a panel and I took it out afterwards.

![image](https://cloud.githubusercontent.com/assets/3875196/22618454/82ad947c-eaaa-11e6-84af-8fbebd832998.png)

and the differences it creates in the config file after removing an applet (in this case the lock_logout applet)

![image](https://cloud.githubusercontent.com/assets/3875196/22618470/ff4a5006-eaaa-11e6-9041-c2f823c5b94b.png)

**Comment by kupiqu** [comment]
Btw, could you please test if network monitor (https://github.com/kotelnik/plasma-applet-network-monitor) crashes latte dock in your system as well? Thanks

**Comment by kupiqu** [comment]
Excellent!

Unfortunately, this doesn't fix the issue on plasma-applet-network-monitor. Could you please test if it crashes latte for you as well?

**Comment by psifidotos** [comment]
@kupiqu open a different ticket!! I can not keep track in my head with the bug reports!! :)

**Comment by kupiqu** [comment]
Sure, sorry

**Comment by psifidotos** [comment]
no no, I dint tell it with roughness... just in order to improve productivity...

this bug report was very important!!!
