### ISSUE TITLE
Occasional broken visual for panel corners

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#128]
![screenshot_20170204_093242](https://cloud.githubusercontent.com/assets/24593950/22617229/ccd30cd4-eabf-11e6-87b7-808648e1fea1.png)
![screenshot_20170204_093459](https://cloud.githubusercontent.com/assets/24593950/22617230/cdeb7c14-eabf-11e6-9123-867014cb5429.png)
![screenshot_20170204_094111](https://cloud.githubusercontent.com/assets/24593950/22617232/d1946e34-eabf-11e6-8d0a-01be8879f85c.png)

**Comment by psifidotos** [comment]
this should be fixed in branch fix103...

for the wrong corner shadows please make a screenshot with the relevant debug window and which plasma theme are you using ?

**Comment by JenaPlinsky** [comment]
I'm using a customized theme based on breeze dark
![screenshot_20170204_103650](https://cloud.githubusercontent.com/assets/24593950/22617465/27c217ba-eac6-11e6-8550-172f6bd1cc97.png)
![screenshot_20170204_103852](https://cloud.githubusercontent.com/assets/24593950/22617466/29a40818-eac6-11e6-9ccf-d37798c988ea.png)

**On the bottom Latte corner are OK**
![screenshot_20170204_103441](https://cloud.githubusercontent.com/assets/24593950/22617469/3bdbea32-eac6-11e6-9003-697225c2c959.png)
![screenshot_20170204_103301](https://cloud.githubusercontent.com/assets/24593950/22617474/4487ad42-eac6-11e6-985a-1ee2e46b18cb.png)

**and now, wrong corner**
![screenshot_20170204_103456](https://cloud.githubusercontent.com/assets/24593950/22617471/3d1e5600-eac6-11e6-937d-39a6fcf4266a.png)
![screenshot_20170204_103400](https://cloud.githubusercontent.com/assets/24593950/22617475/46d9a1c2-eac6-11e6-8ec4-af0a6ffa62ab.png)

**Comment by psifidotos** [comment]
Can you please send the customized theme? it would be good for debugging...

**Comment by psifidotos** [comment]
what is your graphics card and driver ?

**Comment by JenaPlinsky** [comment]
![screenshot_20170204_140028](https://cloud.githubusercontent.com/assets/24593950/22618662/c4865ef0-eae2-11e6-828a-5cdf359df5a7.png)

 **Intel** graphics card
```
UltrabookSamsung:/home/Ivan # glxinfo | grep direct
direct rendering: Yes
    GL_ARB_direct_state_access, GL_ARB_draw_buffers, 
    GL_ARB_draw_indirect, GL_ARB_draw_instanced, 
    GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_multi_draw_indirect, 

```

```
UltrabookSamsung:/home/Ivan # glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```
**OLD renfering method UXA**
Option      "AccelMethod"  "uxa"

**Comment by JenaPlinsky** [comment]
since the last update all seems ok

**Comment by psifidotos** [comment]
please test branch fix128, it contains many panel fixes for drawing...

**Comment by JenaPlinsky** [comment]
mmmm it is no fixed 
now I'm going to test current mentioned branch "fix128"

**Comment by JenaPlinsky** [comment]
since the last update all seems ok
![spectacle ak3415](https://cloud.githubusercontent.com/assets/24593950/22619448/70146318-eaf5-11e6-8d98-048a8ee3d539.png)
