### ISSUE TITLE
Latte don't rise on Drag&Drop image from "Spectacle" to Latte-dock

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#129]
I'd like directly open spectacle preview by dragging its preview on docked kolourpaint task
![screenshot_20170204_093915](https://cloud.githubusercontent.com/assets/24593950/22617247/65c4d7a6-eac0-11e6-8221-f775ee47c242.png)

**Comment by psifidotos** [comment]
duplicate for #118

**Comment by psifidotos** [comment]
this is supported in master, for all features mentioned in #118

**Comment by JenaPlinsky** [comment]
moving spectacle screenshoot to a docked kpaint, Latte don't rise up ...still not fixed !!!

**Comment by psifidotos** [comment]
@audoban can have an eye on this...

**Comment by audoban** [comment]
@psifidotos of course

**Comment by audoban** [comment]
The bug is probably of Spectacle but we are not totally sure

**Comment by psifidotos** [comment]
https://bugs.kde.org/show_bug.cgi?id=377178

**Comment by JenaPlinsky** [comment]
Now all works fine

**Comment by JenaPlinsky** [comment]
Sorry 
This issue, In auto hide mode is still present 
I bag your pardon

**Comment by JenaPlinsky** [comment]
@psifidotos 
The problem seems to be related to latte please watching the video
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1034028/video.zip)

**Comment by psifidotos** [comment]
@JenaPlinsky no it isnt

1. open ksysguard and watch all the time what is happening
2. drag the image as you did at the bottom edge and keep it over there
3. notice in ksysguard that the spectacle app goes cpu crazy
4. after a while the dock will rise and then you will be able to drop it in a task

**Comment by psifidotos** [comment]
https://bugs.kde.org/show_bug.cgi?id=377178

**Comment by JenaPlinsky** [comment]
Ok I saw
However it does work it is enough to stay in that position for a while longer
I thought the dock would not rise up at all
