### ISSUE TITLE
desktop pager and activity pager do not load properly

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#13]
both pagers are initialized in Hidden status and do not update to Ready

**Comment by audoban** [comment]
I can not reproduce it. Please explain.

**Comment by psifidotos** [comment]
I have 2 running activities...

the activity pager in the dock is not shown... I have to enable a third activity in order to be shown...

**Comment by audoban** [comment]
It works for me. I can't reproduce. Maybe is a bug of plasmoid? Remember that we use different versions of plasma.

**Comment by psifidotos** [comment]
> It works for me. I can't reproduce. Maybe is a bug of plasmoid? Remember that we use different versions of plasma.

we will find out...

**Comment by audoban** [comment]
Apparently I was able to reproduce it by accident. But I need found the steps for reproduce again.

**Comment by audoban** [comment]
Confirmed.

**Comment by psifidotos** [comment]
strange thing is that in my system this happens only when Latte is starting first time... By running or closing one activity everything works ok afterwards...

**Comment by psifidotos** [comment]
loadlayout in corona should be loaded after activities...
