### ISSUE TITLE
[Widgets Explorer] - missing the index of added plasmoids

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#130]
![screenshot_20170204_092904](https://cloud.githubusercontent.com/assets/24593950/22617303/9aac9f2a-eac1-11e6-8ab5-633344222677.png)

**Comment by psifidotos** [comment]
I dont think this will ever be fixed because Latte and Plasma are separate processes...

**Comment by JenaPlinsky** [comment]
Well, yes I know, I had imagined ;)

**Comment by audoban** [comment]
Impossible, we can not make communication between latte and plasmashell, because plasmashell does not provide a API for this.
