### ISSUE TITLE
[Crash]-When I click on Applet

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#131]
It happens occasionally and for now I can not give additional details
![screenshot_20170204_101917](https://cloud.githubusercontent.com/assets/24593950/22617386/39489736-eac4-11e6-9aa0-94cffaad707a.png)
![screenshot_20170204_102538](https://cloud.githubusercontent.com/assets/24593950/22617392/4f9f4976-eac4-11e6-9655-d77688d97974.png)

**Comment by psifidotos** [comment]
with left click or right click ?

**Comment by JenaPlinsky** [comment]
Left

**Comment by psifidotos** [comment]
is that the default plasma applet, switch user ?

**Comment by JenaPlinsky** [comment]
This bug does not exist anymore

**Comment by JenaPlinsky** [comment]
Latte crash clicking on "change user" applet (on the current user)
I'm waiting that re-occour to capture its backtrace with ddd

**Comment by JenaPlinsky** [comment]
it just happened, but,once again, I was not ready

**Comment by psifidotos** [comment]
It's good to have the crash to report it upstream...

I am  almost certain that this is an applet problem... just like the network applet in previous issue it looks like a call to draw the session model while a reload for it is executed but I cant reproduce it in my system

**Comment by psifidotos** [comment]
kde bug: https://bugs.kde.org/show_bug.cgi?id=376663

it would be better to attach also the backtrace

**Comment by JenaPlinsky** [comment]
Finally here is the crash backtrace
![spectacle jn1023](https://cloud.githubusercontent.com/assets/24593950/23596384/47a08474-022a-11e7-9e80-17bdb44682b9.png)
![screenshot_20170306_045816](https://cloud.githubusercontent.com/assets/24593950/23596336/c34bdbec-0229-11e7-9059-be28b63d76bb.png)
![screenshot_20170306_045835](https://cloud.githubusercontent.com/assets/24593950/23596337/c5a55d5a-0229-11e7-988e-a67dc195513b.png)

**Comment by psifidotos** [comment]
I have sent the screenshots upstream and by reading the comments that I had uploaded back then for me is a confirmation why this is happening and it is upstream fault...
