### ISSUE TITLE
Latte does not dodge active window when switching desktop

### ISSUE THREAD

**Issue by Magnus2552** [psifidotos/Latte-Dock#133]
Immediately after switching desktop, Latte forgets to dodge the active window, when set to "dodge active window".
Steps to reproduce:

1. Maximize a windows (Latte will hide with the setting "dodge active window")
2. Switch to another desktop and maximize another window (Latte will hide there as well then)
3. Switch back to the first desktop with the maximized window: Latte will not hide automatically now

This problem does btw not occur, when Latte was not hidden on the previous desktop (e.g. the other window was not maximized).
The problem also does not occur, when switching desktops using Latte, but only when the desktop is switched externally, e.g. via a global shortcut

**Comment by audoban** [comment]
it is right, latte don't hidden automatically

**Comment by audoban** [comment]
check the master
