### ISSUE TITLE
Tips & Tricks "History"

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#134]
- Create a folder
- drag it to the latte-dock as folder view
- click with the right mouse button on the new applet
- click on folder view setting
- edit the "specify a folder field" with "recentdocuments: //"

![screenshot_20170204_145841](https://cloud.githubusercontent.com/assets/24593950/22618971/7da5c784-eaea-11e6-937b-6b4a14400a56.png)

**Comment by JenaPlinsky** [comment]
Just reported on Wiki F.A.Q page

**Comment by Petross404** [comment]
Hey nice trick. I did what you wrote and I also edited ` ~/.config/lattedock-appletsrc` in order to append a proper icon to this launcher. 

Everything is ok but the icon doesn't have this "shadow" all the other have. Is it a configuration option that I am missing in  `~/.config/lattedock-appletsrc`?

**Comment by psifidotos** [comment]
Latte Configuration Window -> Appearance -> Shadows -> All

is that checked?

**Comment by JenaPlinsky** [comment]
yes
.... You have noticed something strange?
![spectacle bc6068](https://cloud.githubusercontent.com/assets/24593950/23333038/9507a820-fb84-11e6-9e74-16a3e0c7b40b.png)

**Comment by JenaPlinsky** [comment]
@Petross404 these are dolphin's special link
![screenshot_20170225_181944](https://cloud.githubusercontent.com/assets/24593950/23333227/5695b1be-fb88-11e6-86db-0e440ca07151.png)
![screenshot_20170225_182009](https://cloud.githubusercontent.com/assets/24593950/23333217/1c854b7e-fb88-11e6-9d6d-b515d5068f9f.png)
![screenshot_20170225_182054](https://cloud.githubusercontent.com/assets/24593950/23333218/1e8ac228-fb88-11e6-942c-01f43dfbb19d.png)
![screenshot_20170225_182520](https://cloud.githubusercontent.com/assets/24593950/23333220/22103176-fb88-11e6-9497-f051b0406f7e.png)
![screenshot_20170225_182130](https://cloud.githubusercontent.com/assets/24593950/23333221/259d0364-fb88-11e6-9470-8dd23bf94b29.png)
![screenshot_20170225_182701](https://cloud.githubusercontent.com/assets/24593950/23333223/347181b2-fb88-11e6-9215-ff0a6f58708d.png)

**Comment by Petross404** [comment]
For Christ shake, the configuration window was somewhat shorter and I could see the shadows config. I scroll down and saw it. Thank you both.

But for completeness, I could write shadows=All inside lattedock-appletsrc.

**Comment by JenaPlinsky** [comment]
> Hey nice trick. I did what you wrote and I also edited ~/.config/lattedock-appletsrc in order to append a proper icon to this launcher.

@Petross404  you do not need to edit the configuration file to change an icon...
![screenshot_20170225_212751](https://cloud.githubusercontent.com/assets/24593950/23334552/95063ffe-fba1-11e6-8d7b-ee531f422a2e.png)
![screenshot_20170225_212644](https://cloud.githubusercontent.com/assets/24593950/23334566/cff767e6-fba1-11e6-8e49-641686e6c48a.png)
![screenshot_20170225_212713](https://cloud.githubusercontent.com/assets/24593950/23334570/e1b7ebd6-fba1-11e6-82a6-1d7ee33c9b35.png)

**Comment by Petross404** [comment]
Good to know 👍

**Comment by psifidotos** [comment]
There is also: https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks
