### ISSUE TITLE
[Plasma 5.9] - Small icons in taskmanager

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#135]
this is new.... :)

libtaskmanager returns too small icons...

hehe...

![image](https://cloud.githubusercontent.com/assets/2216474/22620121/0de69072-eb0d-11e6-9c5c-9779f40a5cfc.png)

**Comment by psifidotos** [comment]
not only that... there is also no animation any more from 48px to 64px. on hover... it is just like the 
folderviews behavior mentioned at #83...

good news is that #123 is fixed for the latte icon after 64px...

**Comment by audoban** [comment]
Wow then we can close #123?

**Comment by psifidotos** [comment]
I dont know if this is fixed for all icons, problem is that the latte icon looks ok but it broke the animation

**Comment by audoban** [comment]
The zoom animation does not work fine?

**Comment by psifidotos** [comment]
> The zoom animation does not work fine, for latte icon?

No.. it's behavior is like the plasma default one... The QIcon given to us from libtaskmanager doesnot provide sizes between 48-64 pxs. If we add a 64px icon for Latte we may fix this from our side...

**Comment by psifidotos** [comment]
I tried to install a 64px version, no luck... problem remains...

**Comment by audoban** [comment]
If the libtaskmanager gives us the icon named, this will be fixed automatically.
Because an icon name is used to create a Plasma :: Svg object

**Comment by psifidotos** [comment]
@audoban QIcon provides a name() function 
http://doc.qt.io/qt-5/qicon.html

that can be accessed through our c++ code. The libtaskmanager isnt returning this correctly?

**Comment by psifidotos** [comment]
EDIT2: I just found that it publishes the names correctly, so this is something is our part, isnt it? for example by debugging iconitem.cpp I get:
icon name:  "latte-dock",
inside function, void IconItem::setSource(const QVariant &source), I think that the problem may be that our icon and other default icons are not located in the themes directory path but at:
/usr/share/icons/hicolor

from our installation that is:
-- Up-to-date: /usr/share/icons/hicolor/16x16/apps/latte-dock.svg
-- Up-to-date: /usr/share/icons/hicolor/22x22/apps/latte-dock.svg
-- Up-to-date: /usr/share/icons/hicolor/24x24/apps/latte-dock.svg
-- Up-to-date: /usr/share/icons/hicolor/32x32/apps/latte-dock.svg
-- Up-to-date: /usr/share/icons/hicolor/48x48/apps/latte-dock.svg
-- Up-to-date: /usr/share/icons/hicolor/scalable/apps/latte-dock.svg

so I think an heuristic in our part in iconitem.cpp could be added I think for this and I dont know if there are and other default theme directories, e.g.
/usr/share/icons/HighContrast
/usr/share/icons/locolor

**Comment by psifidotos** [comment]
ok... this was  an icon cache issue for me... during trying to fix #123 I had tried to install a 64px version of latte icon but with wrong metrics in it...

I cleaned up my icon cache and now everything is ok in Plasma 5.9!
