### ISSUE TITLE
is possible to clean the Latte start up ?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#136]
during the start-up phase for a moment appears Latte and then disappear ...

**Comment by psifidotos** [comment]
in what visibility mode?

**Comment by JenaPlinsky** [comment]
I think so, as soon as I launch the app Latte

**Comment by psifidotos** [comment]
What visibility mode is it happening? Auto-hide?

**Comment by JenaPlinsky** [comment]
Yess AutoHide visibility mode ;)

**Comment by audoban** [comment]
Could you describe me better the situation?

**Comment by JenaPlinsky** [comment]
what I expect, it is that when Latte is launched in "visibility mode auto-hide", everything is hidden, right? but it happens that, for a frame appears Latte

**Comment by audoban** [comment]
@psifidotos I'm going to fix this bug.

**Comment by psifidotos** [comment]
:+1:

**Comment by JenaPlinsky** [comment]
in addition to the initial frame, I also observe a flicker on a first un-hide

**Comment by psifidotos** [comment]
all of them i consider them qt issue cleaning the mask buffer properly

**Comment by JenaPlinsky** [comment]
I propose a trick
and if on start-up mode the visibility was "Dodge actyvity windows"
and then become "auto-hide" after an event or elapsed time T? Do you think that would hide the problem ?

**Comment by audoban** [comment]
Now when latte is started, the current state is set to hidden.

**Comment by JenaPlinsky** [comment]
@audoban @psifidotos 

I noticed a regression in visibility mode autohide
on start-up ..
- rising dock
- Seeking for its geometry
- and then hide

before the latest updates seemed to me that it was all clean and that latte-dock, always remained hidden waiting for an user trigger event

**Comment by psifidotos** [comment]
this may need a lot of attention to not break other things...

e.g. loading visibility mode correctly at startup
