### ISSUE TITLE
can not set separate wine launchers

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#137]
- impossible set "show task when not running"
![screenshot_20170204_205809](https://cloud.githubusercontent.com/assets/24593950/22621190/f5f0b0ea-eb1d-11e6-9395-6651a290c193.png)

- is possible separate wine tasks ?
![screenshot_20170204_210254](https://cloud.githubusercontent.com/assets/24593950/22621191/f75c6924-eb1d-11e6-8088-a85c11b6fee1.png)

**Comment by psifidotos** [comment]
Its a known plasma bug, fixed i think in plasma 5.9    what plasma version are u using?

**Comment by JenaPlinsky** [comment]
5.9,90

**Comment by psifidotos** [comment]
Try this with the plasma's taskmanager. If the same problem appears you should report it to them at bugs.kde.org

**Comment by JenaPlinsky** [comment]
Ok thanks

**Comment by JenaPlinsky** [comment]
I can confirm 
also from the taskmanager process are grupped

**Comment by psifidotos** [comment]
if you file the bug at bugs.kde.org please publish here the link...

**Comment by JenaPlinsky** [comment]
of course

**Comment by JenaPlinsky** [comment]
Solved !!! it is not a bug
![screenshot_20170205_103120](https://cloud.githubusercontent.com/assets/24593950/22625191/d4d1a58c-eb8f-11e6-91e5-0194fb1bf1a6.png)
![screenshot_20170205_103751](https://cloud.githubusercontent.com/assets/24593950/22625230/d3c01d4e-eb90-11e6-8335-eb028554534f.png)
![screenshot_20170205_103820](https://cloud.githubusercontent.com/assets/24593950/22625231/d4dc001c-eb90-11e6-86ce-4b05dcc9569f.png)
![screenshot_20170205_104836](https://cloud.githubusercontent.com/assets/24593950/22625232/d61801ba-eb90-11e6-93fb-9402363ac5f6.png)
![screenshot_20170205_104026](https://cloud.githubusercontent.com/assets/24593950/22625233/d7b001a8-eb90-11e6-8079-afaf819b7b75.png)

**Comment by psifidotos** [comment]
@JenaPlinsky can we close this report then?

**Comment by JenaPlinsky** [comment]
Ohhh Yess ;)
