### ISSUE TITLE
Un-hide Latte at desktop and activity changes

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#139]
Would be nice, un-hide Latte on cube-desktop-swithing like as happens for the default panel

**Comment by audoban** [comment]
@psifidotos We can detect when the cube-desktop is active?

**Comment by psifidotos** [comment]
I dont think so... But i think that neither plasma uses it that way, i think it just detects
an active desktop change.

I would like this for active desktop change or activity change. Currently i support for activity change through qml but i would prefer it to go into the visibilitymanager in c++

**Comment by audoban** [comment]
Maybe with a timer, with KWindowSystem i can know when the user switch desktop, but I dont know what is the duration of the animation, or when started and finished the change.

**Comment by audoban** [comment]
I feel that KWindowSystem does not give me enough information to achieve this.

**Comment by psifidotos** [comment]
> Maybe with a timer, with KWindowSystem i can know when the user switch desktop, but I dont know what is the duration of the animation, or when started and finished the change.

it doesnt have to be that accurate.. In every desktop of activity change we could show the dock for just 3secs using a timer

**Comment by audoban** [comment]
But this desktop change notification happens when I finish changing not before. 

https://api.kde.org/frameworks/kwindowsystem/html/classKWindowSystem.html#a5ff0c02733368f3bacb05ea30a26ff87

**Comment by psifidotos** [comment]
The correct order I think is the following:

1. The user changes desktop or activity
2. the relevant signal is catched up from Latte
3. we show the dock for 3 secs and then we restore it to its hiding situation concerning dodge active, auto-hide etc.

**Comment by audoban** [comment]
> we show the dock for 3 secs and then we restore it to its hiding situation concerning dodge active, auto-hide etc.

okay no problem, but maybe 1.5 seconds, 3 is too much.

**Comment by psifidotos** [comment]
we can test drive it and see what works better...

maybe 2 secs? the point in this is that the user can see the minimized windows of the currect desktop or activity

**Comment by psifidotos** [comment]
for the activity change when this implemented I must remove the qml code in order to work correctly...

**Comment by psifidotos** [comment]
:+1:

**Comment by JenaPlinsky** [comment]
Really well done !!! I like it
...however, the dock should hide when the animation of desktop change is finished, or parameterize the delay to hide time (even as it stands is perfect ;) )
