### ISSUE TITLE
Dodge modes are not working correctly for top docks

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#140]
In the visibility mode "always-visible" and only for top alignement
![screenshot_20170205_090042](https://cloud.githubusercontent.com/assets/24593950/22624640/3649435a-eb82-11e6-9eb3-7793cc1a0da3.png)

is not possible place a window behind Latte

**Comment by psifidotos** [comment]
This is the default "Always Visible" behavior even for plasma in contrary with  "Windows Go Below" that Latte is not supporting

**Comment by audoban** [comment]
This also happen with plasmashell. You can report this bug to KWin development team.
This bug is related to X11 struts.

Although I would think it is normal behavior?

**Comment by JenaPlinsky** [comment]
the strange thing is that this does not happen for Latte on the bottom and always in visibility mode always-visible

**Comment by audoban** [comment]
I would also like to put windows behind the panel.

**Comment by JenaPlinsky** [comment]
Well
now I've change setting to "dodge active windows"
top panel and bottom behaviour are different

the top dock  does not hide ..it happens only if the mouse is on hover the screen  edge

**Comment by psifidotos** [comment]
> the top dock does not hide ..it happens only if the mouse is on hover the screen edge

@audoban  this is because for the window geometries used the decoration is not taken into account. I dont know how can this be fixed. Optiman behavior is to use windowgeometry+decorations(that is borders but without the shadows)

**Comment by psifidotos** [comment]
@JenaPlinsky you must decide what this report should be:

- Support "Window Go Below" case 
or
- Dodge modes are not working correctly for top docks

**Comment by audoban** [comment]
Latte does not use the geometry of the decoration, use the geometry of the content window. For this reason does not dodge the title bar.

**Comment by psifidotos** [comment]
@audoban is this easily fixed ?

**Comment by JenaPlinsky** [comment]
@psifidotos  i think this is better "Dodge modes are not working correctly for top docks"

**Comment by audoban** [comment]
In principle I use the content of the window because it always gives me valid rectangles, but if the decoration is not available I get nothing.

**Comment by audoban** [comment]
@psifidotos is easy to fix.

**Comment by audoban** [comment]
@JenaPlinsky fixed 2e3595779f858539e0203ceaa4d61e5e4ab74d7e
