### ISSUE TITLE
Bright Placeholder when mouse approaches the screen edge

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#144]
What do you think about this? perhaps with an option in the configuration form
![screenshot_20170205_151736](https://cloud.githubusercontent.com/assets/24593950/22626823/73f71c20-ebb6-11e6-857b-2c244439a82c.png)

**Comment by psifidotos** [comment]
it can be easily drawn in our qm side...

but this means tracking the mouse all the time and also that our mask in isHidden state to grow from 2pixels to all pixels needed to draw these graphics...

I am 50-50 in this...

**Comment by JenaPlinsky** [comment]
I expect a great version for plasma 5.10
Latte-dock
Activities encrypting
Virtual assistant Mycroft
etc

It Rocks ;)

**Comment by audoban** [comment]
I do not know, it can bring us issues, or it could break the workflow.

whatever, the mask can not have more than 2 px

**Comment by psifidotos** [comment]
This is a feature for kwin, the original plasma panel supports this?

**Comment by psifidotos** [comment]
ok... original plasma supports it in AutoHide mode and the glow is based on the plasma theme used...
I dont know if it is possible to use the same mechanism or this is all inside kwin so we cant do anything..

**Comment by psifidotos** [comment]
as it appears for X, this could be supported with: 

```
#if HAVE_X11
    if (KWindowSystem::isPlatformX11()) {
        xcb_connection_t *c = QX11Info::connection();

        const QByteArray effectName = QByteArrayLiteral("_KDE_NET_WM_SCREEN_EDGE_SHOW");
        xcb_intern_atom_cookie_t atomCookie = xcb_intern_atom_unchecked(c, false, effectName.length(), effectName.constData());

        QScopedPointer<xcb_intern_atom_reply_t, QScopedPointerPodDeleter> atom(xcb_intern_atom_reply(c, atomCookie, NULL));

        if (!atom) {
            return;
        }

        if (!enabled) {
            xcb_delete_property(c, winId(), atom->atom);
            return;
        }
```

but for wayland this is done internal in kwin...

so... I dont know if  this will be feasible...

**Comment by psifidotos** [comment]
my mistake... I tried it but I didnt have any luck... messed up things a lot...

**Comment by audoban** [comment]
Yes, we can't use the extension "_KDE_NET_WM_SCREEN_EDGE_SHOW" because this api hide the window automatically and I cant configure timers for show and hide a panel.

**Comment by audoban** [comment]
Maybe with wayland we can provide this feature.

**Comment by psifidotos** [comment]
@audoban I managed to add the "_KDE_NET_WM_SCREEN_EDGE_SHOW" without any issues for X11. 

I uploaded the work at branch **placeholder** but because I touched visibilitymanager I would like from you to review it first...

**Comment by audoban** [comment]
@psifidotos It works but it does not convince me.

When I have show timer greater than 0, the edge bright disappears instantly, and it does not feel natural for me.

And sometimes the dock appear instantly without slide animation.

**Comment by psifidotos** [comment]
ok... lets drop it then

**Comment by audoban** [comment]
@psifidotos I'm sorry.  The extension  "_KDE_NET_WM_SCREEN_EDGE_SHOW" is very limited for our purpose

**Comment by psifidotos** [comment]
no worries

**Comment by psifidotos** [comment]
unfortunately, no technical solution can be found except integrating  something new in kwin... which I dont see feasible until wayland has been supported properly....
