### ISSUE TITLE
google earth icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#145]
![screenshot_20170205_231942](https://cloud.githubusercontent.com/assets/24593950/22630406/f8f6c7f2-ebf9-11e6-91f4-2900e79d5a47.png)
!

**Comment by psifidotos** [comment]
check please if this happens also with the plasma taskmanager

**Comment by JenaPlinsky** [comment]
Latte and TaskManager have the same behaviour
you can close this issue
![screenshot_20170206_180713](https://cloud.githubusercontent.com/assets/24593950/22658034/f617c0f0-ec98-11e6-88d5-9ea8043bed29.png)
