### ISSUE TITLE
is not possible set google earth launcher

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#146]
![screenshot_20170205_232457](https://cloud.githubusercontent.com/assets/24593950/22630447/848b1b24-ebfa-11e6-80f0-79ed908af1c3.png)

**Comment by psifidotos** [comment]
check if this happens also with the plasma taskmanager

**Comment by JenaPlinsky** [comment]
The TaskManager does not has this menu item

**Comment by psifidotos** [comment]
> The TaskManager does not has this menu item

The new TaskManager has a new sub-menu called Pin,
try  the right click, "Pin->To All Activities"

**Comment by JenaPlinsky** [comment]
Ok 
TaskManager  / Google Earth
... the items of the pin submenu are denied

**Comment by psifidotos** [comment]
so this isnt  in our part...
