### ISSUE TITLE
How To - Crash Reports

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#147]
_First try to clean your qt cache, #788, [kubuntu bug 1736765](https://bugs.launchpad.net/kubuntu-ppa/+bug/1736765):_

1. **Close Latte**
2. **In folder** `~/.cache/lattedock/qmlcache/` **remove everything**
3. **Start Latte again**

_Use the following guidelines:_

- **Install ddd**
- **ddd latte-dock**
- **in ddd window write and execute, run**
- **when it crashes, click status from the menu, backtrace**
- **This will show you a window with numbered lines, this could be helpful for us...**

_If the crash is from QML you should try the following:_

- **run command:** `env QV4_FORCE_INTERPRETER=1 latte-dock -d`
- **if the above doesnt provide enough info again you could try:** `env QV4_FORCE_INTERPRETER=1 ddd --debugger /bin/gdb latte-dock` **that should provide more infos if the debug packages are installed**

_if nothing from the above in order to check if the crash is from a specific plasmoid:_

1. **Use Latte only with default Layout (does it crash?)**
2. **If it doesnt crash start adding one by one your plasmoids to check their behavior if the crash Latte...**
--------

_so if someone knows that in the day latte will crash, can use the above to give us the backtrace... 95% for that backtrace we can know if the crash is in our side..._

**Comment by psifidotos** [comment]
personally i dont know how this is done.... in my system it is very long to even have a crash... what i do is use the following guidelines:

- Install ddd
- ddd latte-dock
- in ddd window write and execute, run
- when it crashes, click status from the menu, backtrace

This will show you a window with numbered lines, this could be helpful for us...

so if someone knows that in the day latte will crash, can use the above to give us the backtrace... 95% for that backtrace we can know if the crash is in our side...

**Comment by JenaPlinsky** [comment]
yes I can confirm very rare crash
Well these are very useful information ... I do not know;)

**Comment by psifidotos** [comment]
Try to run latte with ddd,

when the crash occurs, go to ddd, status from its menu and then click backtrace

take a screenshot of the window with the numbered lines and upload it to us

**Comment by JenaPlinsky** [comment]
now I try ;)

**Comment by JenaPlinsky** [comment]
`ddd` `latte-dock`
and now ?
![spectacle ui1776](https://cloud.githubusercontent.com/assets/24593950/22665237/4e010aea-ecb4-11e6-9dc5-bfccf98d34e5.png)

**Comment by psifidotos** [comment]
click ok to the two dialogs and type in ddd, run, and press enter

**Comment by JenaPlinsky** [comment]
![screenshot_20170206_214344](https://cloud.githubusercontent.com/assets/24593950/22665546/69f52366-ecb5-11e6-98c5-4c6968b1fb45.png)
crash hunter :)

**Comment by psifidotos** [comment]
nice!!!

**Comment by psifidotos** [comment]
one more question, are u working on a single screen or multiple screen system?

**Comment by JenaPlinsky** [comment]
Single screen. 
I'm using a laptop

**Comment by JenaPlinsky** [comment]
Latte is ready for multi screen ?

**Comment by psifidotos** [comment]
not yet... we are trying to support it properly in February

**Comment by JenaPlinsky** [comment]
Hard job

**Comment by JenaPlinsky** [comment]
When a crash happens, have I to send you a screenshot without touching anything? or can I continue to use the laptop ?

**Comment by psifidotos** [comment]
@JenaPlinsky take a screenshot of the window mentioned and after that you must close ddd completely and restart it if you want to use it again

**Comment by JenaPlinsky** [comment]
I was wondering, the feedback must be immediate? if I execute actions of any kind, the feedback is polluted

**Comment by psifidotos** [comment]
after a crash everything is freezed and ddd waits for your action

**Comment by JenaPlinsky** [comment]
;) ok !

**Comment by JenaPlinsky** [comment]
Just reported on Wiki F.A.Q page

**Comment by Aetf** [comment]
Have you considered using KCrash for easier backtrace generation?
https://api.kde.org/frameworks/kcrash/html/index.html

**Comment by brauliobo** [comment]
@JenaPlinsky this should be a wiki page not an issue!

**Comment by psifidotos** [comment]
@brauliobo done... https://github.com/psifidotos/Latte-Dock/wiki/How-to-Report-Crashes
