### ISSUE TITLE
tool-tip and focus

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#148]
When the cursor leaves the running task and passes to a launcher, its too-tip I think should drop,  just as it is now may confuse
![screenshot_20170206_225657](https://cloud.githubusercontent.com/assets/24593950/22668404/eb904620-ecc0-11e6-854d-c1a8a6ae4575.png)

**Comment by JenaPlinsky** [comment]
- Not always the thumbnails (tool-tip) are shown, sometimes, for some tasks, when I hover on, these are skipped, then re-hovering over them again, these reappear

- When setted "show only current activity" the tasks related to the current activities are shown, well !! ...
..with the tooltips, is there is a chance to show the opened tasks on other activities?
I do not know if it's a good idea or break its purpose, but it would give a better view of what is open on other tasks

**Comment by psifidotos** [comment]
> Not always the thumbnails (tool-tip) are shown, sometimes, for some tasks, when I hover on, these are skipped, then re-hovering over them again, these reappea

the new tooltips based on plasma are not robust yet...

> ..with the tooltips, is there is a chance to show the opened tasks on other activities?..

yes, **disable** the setting you mentioned previously "show only current activity". this should show you tasks from all activities. If you dont see the previews for these tasks, you should go to plasma systemsettings -> Screen -> Compositor -> Windows Previews -> **ALWAYS**

**Comment by JenaPlinsky** [comment]
I did not make myself clear;)
what I mean is a hybrid solution
with always setted "show only current activity" and, in addition to the tootips of the current activity, a tootip of the open tasks on other activities 

I hate to click on a task and ritovarmi involuntarily on a different activity from the one in use
and at the same time I would like to avoid having too many open instances of an application


So it would be convenient to have a smart solution to be able to view all instances of an application, but while remaining, always in the activity in use

**Comment by psifidotos** [comment]
sorry... this would need two totally different tasks models, increases complexity a lot... and makes us our qml code too divergent from the official plasma taskmanager...

so I'm sorry but i dont agree

**Comment by JenaPlinsky** [comment]
> the new tooltips based on plasma are not robust yet...

I noticed something and I do not know if it will be useful
trigger after which, the dock is hidden, it is different ...

Dock:
![screenshot_20170218_100748](https://cloud.githubusercontent.com/assets/24593950/23092113/227f6254-f5c4-11e6-97aa-7cd8f89f9d90.png)

Plasmoid: 
notes, the pointer position  it is as if we were in the tool-tip
as mentioned before, sometimes the tool-tip are not shown
![screenshot_20170218_100944](https://cloud.githubusercontent.com/assets/24593950/23092104/09c8a432-f5c4-11e6-9fc7-3a1fdb4e1ba6.png)
![spectacle i11935](https://cloud.githubusercontent.com/assets/24593950/23092128/8518b1a4-f5c4-11e6-9419-033884fa77b1.png)

**Comment by psifidotos** [comment]
concerning the usability change of different tooltips and different tasks shown. Personally i dont want many changes that change the default plasma behavior... only very specific and needed ones... the case of tooltips does not belong in the exceptions from my perspective
