### ISSUE TITLE
Ksysguard and grouping

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#149]
![screenshot_20170206_232205](https://cloud.githubusercontent.com/assets/24593950/22669028/3f36e20a-ecc3-11e6-87eb-6da31264b533.png)
launcher and task are not grouped
![screenshot_20170206_232145](https://cloud.githubusercontent.com/assets/24593950/22669269/20a3f2a0-ecc4-11e6-837b-b3d1cc2f7b91.png)

**Comment by psifidotos** [comment]
isnt that also the plasma's taskmanager behavior?

**Comment by JenaPlinsky** [comment]
no, in the image there is also the taskmanager and it has two similar icons
- grouped ksysguard, and
- grouped systemmonitor

**Comment by JenaPlinsky** [comment]
![screenshot_20170206_234635](https://cloud.githubusercontent.com/assets/24593950/22669810/a2ca0f4c-ecc6-11e6-8593-59971e38218a.png)
![screenshot_20170206_234652](https://cloud.githubusercontent.com/assets/24593950/22669812/a44acdc0-ecc6-11e6-8b86-5847c3318dcd.png)
![screenshot_20170206_234709](https://cloud.githubusercontent.com/assets/24593950/22669813/a576b06a-ecc6-11e6-9891-5bbd4155512a.png)

**Comment by psifidotos** [comment]
not in my system... two ksysguard windows are grouped correctly...

![ksysguard](https://cloud.githubusercontent.com/assets/2216474/22670307/4aab412c-ecd1-11e6-9bf5-6000bb6a5048.png)

**Comment by JenaPlinsky** [comment]
I have a feeling that if I close tasks and re-open them, everything returns to normal

**Comment by JenaPlinsky** [comment]
I have make a bit of hacking on their config.dektop file 
ksysguard and srstemmonitor
the guilt could be mine ?

**Comment by JenaPlinsky** [comment]
![screenshot_20170207_002724](https://cloud.githubusercontent.com/assets/24593950/22671010/4c812cf0-eccc-11e6-8b5d-0a2eeb2d40f8.png)
I redid the launcher and now everything is ok
