### ISSUE TITLE
Test system overload

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#150]
**test system overload 1**
- unresponsive Latte while taskmanager is responsive
- process ... [waiting disk]
- once the system load was liberated Latte work again
![screenshot_20170207_014535](https://cloud.githubusercontent.com/assets/24593950/22673607/854c9984-ecdb-11e6-9a37-ffbf79e3e480.png)

**test system overload 2**
- unresponsive Latte while taskmanager is responsive
- process ... [unknow]
- I have to kill Latte
![screenshot_20170207_020808](https://cloud.githubusercontent.com/assets/24593950/22673610/88f9a694-ecdb-11e6-8370-0a24764d8843.png)
![screenshot_20170207_020710](https://cloud.githubusercontent.com/assets/24593950/22673608/871870a8-ecdb-11e6-9a67-be663241e597.png)

**Comment by psifidotos** [comment]
Can you check if this occurs also if you disable from Latte Config Window: "Show tasks progress" ?

**Comment by JenaPlinsky** [comment]
- the problem that was highlighted in the test 1 has occurred but less frequently, it
 gave me this impression
- the problem that was highlighted in the test 2 has not occurred

Here are some screenshots:
![screenshot_20170207_213017](https://cloud.githubusercontent.com/assets/24593950/22717933/17ef3176-ed9e-11e6-895d-b091eeab6ae2.png)
![screenshot_20170207_213944](https://cloud.githubusercontent.com/assets/24593950/22717711/f1fefd1c-ed9c-11e6-9452-567e30fe954f.png)
![screenshot_20170207_214008](https://cloud.githubusercontent.com/assets/24593950/22717713/f32c028e-ed9c-11e6-82a0-1ef9302c95b5.png)
![screenshot_20170207_214145](https://cloud.githubusercontent.com/assets/24593950/22717714/f451a2c2-ed9c-11e6-8f30-06d70a5bcd71.png)
![screenshot_20170207_214223](https://cloud.githubusercontent.com/assets/24593950/22717715/f57cc4ec-ed9c-11e6-8abd-7511d5d1c2a7.png)
![screenshot_20170207_214301](https://cloud.githubusercontent.com/assets/24593950/22717717/f6fc867c-ed9c-11e6-86e0-ee173c5bb15a.png)
![screenshot_20170207_214329](https://cloud.githubusercontent.com/assets/24593950/22717719/fa24875a-ed9c-11e6-84cc-1d7e6709a996.png)
![screenshot_20170207_214344](https://cloud.githubusercontent.com/assets/24593950/22717720/fb9532e2-ed9c-11e6-808b-7dde59ce8568.png)
![screenshot_20170207_214400](https://cloud.githubusercontent.com/assets/24593950/22717723/fcf74ba2-ed9c-11e6-8fb7-f31d4008ce4f.png)
![screenshot_20170207_214422](https://cloud.githubusercontent.com/assets/24593950/22717726/fec91cd0-ed9c-11e6-81df-6cf50e061877.png)
![screenshot_20170207_214437](https://cloud.githubusercontent.com/assets/24593950/22717728/0047c944-ed9d-11e6-9f2e-2ad665142b52.png)
![screenshot_20170207_214541](https://cloud.githubusercontent.com/assets/24593950/22717735/03c31ed4-ed9d-11e6-8685-87a02708f9bf.png)
![screenshot_20170207_214611](https://cloud.githubusercontent.com/assets/24593950/22717743/088a6c9c-ed9d-11e6-9d2f-101b613f0dc7.png)
![screenshot_20170207_214639](https://cloud.githubusercontent.com/assets/24593950/22717744/0a53a9f8-ed9d-11e6-87dc-75b213a90c27.png)

**Comment by JenaPlinsky** [comment]
in the event of a crash, would it make sense to re-open automatically a new Latte instance ?

**Comment by psifidotos** [comment]
it depends from the crash... there are cases that this could create a continuous unstopped crash after restart, that would make the system totally unresponsive I think...
We can think to support it but after the project has matured enough

**Comment by JenaPlinsky** [comment]
Well now.
In order don't interrupt the workflow in critical condition. you believe that, on loop exception, is possible and convenient look for an alternative default panel ?
I mean, before, I try to re-open a new instance of Latte then if I see that it goes in a loop, I close Latte and I open an alternative panel

**Comment by psifidotos** [comment]
This would need at least different threads for each dock, I dont find it feasible at this moment

**Comment by psifidotos** [comment]
@JenaPlinsky  also we had a memory leak fixed in master... I believe that those huge memory usage from Latte seen in your screenshots should be fixed now...

**Comment by psifidotos** [comment]
I had seen a 2Gbyte usage in one of your screenshots but I cant remember which one...

**Comment by JenaPlinsky** [comment]
Maybe when Latte will be robust and stable, you could think to implement some sort of "emergency mode" mechanism such as occurs, for Kwin and plasma-shell, I think
 - try to re-open a new latte-dock instance
 - if it is still unresponsive than try to restore a saved backup configuration file
 - if the last attempt did not work, then as an alternative, try to open the default Plasma panel

**Comment by psifidotos** [comment]
memory talks at #199
