### ISSUE TITLE
Latte process takes 100% CPU when an applet is spinning due to an internet connection failure

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#151]
I wonder if Latte is bitten by this bug as well

[https://bugs.kde.org/show_bug.cgi?id=356479](https://bugs.kde.org/show_bug.cgi?id=356479)
If so, there is a fix already in plasma, perhaps same thing could apply to Latte...

**Comment by psifidotos** [comment]
you wonder? or you confirm it in your system?

I tried the konversation case mentioned in the bug with KF 5.30 and I dint have any issue...

**Comment by psifidotos** [comment]
following also the comments, the patch mentioned has been added in plasma systray from Plasma 5.8 and on going... Anyone using Plasma 5.8 version updated after the end of the December and Plasma 5.9 shouldnt have that issue...

**Comment by kupiqu** [comment]
I have it in my system for the weather plasmoid when off of internet and the plasmoid tries to update data (spinning animation).

This is the weather plasmoid for the case you want to confirm it in your system:

[https://github.com/kotelnik/plasma-applet-weather-widget](https://github.com/kotelnik/plasma-applet-weather-widget)

**Comment by psifidotos** [comment]
what is your plasma version ?

**Comment by kupiqu** [comment]
Plasma 5.9

I have to say, though, that the weather plasmoid is outside the system tray

**Comment by kupiqu** [comment]
In the latte panel

**Comment by psifidotos** [comment]
in my system I can not make it spin... I close my internet connection and restart Latte... no spin is appearing, just a blank small blank space...

either way the only case that this is in our side would be the shadows... Try to disable all shadows from latte configuration window and see if this still happens... Except that I dont think latte produces this...

Add this applet also in a regulara plasma panel and see if the problem persists...

**Comment by psifidotos** [comment]
in the latte another thing to test is to lock the weather applet in order to not use the zoom effect

**Comment by kupiqu** [comment]
Not sure why if I disconnect the wifi I cannot trigger the animation either (this happened to me before while connected, but apparently the connection failed)

Another way to see the same in a different applet is when trying to connect to a wifi that is not available (if it is not available the spinning lasts longer and makes it easier to check this out). The spinning of the network applet makes latte and xorg raise a lot in cpu demand.

**Comment by psifidotos** [comment]
> Another way to see the same in a different applet is when trying to connect to a wifi that is not available (if it is not available the spinning lasts longer and makes it easier to check this out). The spinning of the network applet makes latte and xorg raise a lot in cpu demand.

isnt this happening also with plasma ?

**Comment by kupiqu** [comment]
Well, not sure what happened before but I cannot get the high CPU usage in latte anymore. 

Now it is comparable to plasma, yes.

If I see this back, I'll try to see under what context...

**Comment by psifidotos** [comment]
ok...

**Comment by psifidotos** [comment]
I tried copying a big file in order to show a spinner in latte dock for the progress...

Latte cpu usage went to 20% in my system and dock became a little unresponsive.. from testing this tranlated at:

5% of latte core (probably from libtaskmanager)
5% of task progress animation (the circle over dolphin showing progress)
10% of animation spin at systray

either way, Latte doesnot handle at all painting for applets, so if the progress animation is costly it couldnt be latte's fault, except in the case of drawing the shadows

**Comment by kupiqu** [comment]
Ok, great, thanks for checking this out!
