### ISSUE TITLE
Support an alternative session

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#152]
I go by train (in a regular basis) and plane (not that frequently but still), and use my computer quite a lot during my journeys.

It just came to mind that it would be great (and as far as I know, novel) to add a toggle setting to enable/disable private mode.

The use for it would be to activate either a latte config. In private mode I would like for instance to avoid some applets or have in them different configuration.

Examples for this may be the user switch (instead of name or username to show only icon), weather plasmoid (I modified it a bit to show the city as well as the temp and weather icon), so in private mode I would like to remove the city name or the applet entirely.

These are a couple of examples that come to mind (name and city make you easy to be tracked), but there may be others...

What do you think?

**Comment by psifidotos** [comment]
the idea is very good! :)

when we were discussing multi-screen support we envisioned a profiles settings. For example the user could be able to set different setups according to the monitors used and based on their order and that would make Latte to provide different docks... For example when a user goes to work and connects his laptop with the works monitor, Latte knows that setup and for that specific profile loads a very specific dock loaded in the work's screen... If we achieve this then it will be easy enough to support also profiles setup by the user e.g. the private mode you are mentioning...

First stop in our journey of course is to support  multi-screen setup correctly without crashes and providing useful features for example:

- a dock to be able to be on all screens (this is more more difficult that it sounds)
- easy screen switching for every dock
- no crashes are acceptable when the user alters its screens layouts (de-activate monitors etc.)

**Comment by psifidotos** [comment]
@kupiqu having in place the multi-screen architecture this feature can be discussed further...

1. I dont like the name... maybe a "Guest Session" ?
2. in that session are you going to need one dock or more?

**Comment by kupiqu** [comment]
The role would not be quite the same, would it? 

Guest session for me would be for guest users, while private mode would be for main users that need some privacy while using a laptop in a public environment.

In my case, I would just have all the same configuration but user-switch applet would show my user icon instead of my full name, and perhaps, my weather applet would omit the city name where I live/work/etc.

I guess I could do it manually back and forth, but it would be good to go to latte settings and have a toggle button or alike to switch to default configuration or to the private one.

Guest session is like

**Comment by psifidotos** [comment]
So you will need more than one docks ... 
I dont like the Private naming because it isnt Private mode, the Latte will remember all the applets and their configurations and their usement...

So for the naming I would like something different. The idea of having two modes to toggle between them sounds ok and it is feasible with the current architecture...

@audoban what do you think about that thread?

**Comment by kupiqu** [comment]
> I dont like the Private naming because it isnt Private mode, the Latte will remember all the applets and their configurations and their usement...

Yes, that's right, let's find a better name

**Comment by kupiqu** [comment]
Perhaps better De-identified or Confidential Mode...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/23812408/0fc521a6-05e3-11e7-8cc4-6a0d223297cc.png)

**Comment by psifidotos** [comment]
> Edit: I think the one I like the most is Restricted Mode, as it can be applied for different use cases... Another one would be Limited Mode, but I think I prefer Restricted better

there arent any limitations for "on the road" session... so the previous names I dont find them that correct... You can set up your "On The Road" session as you please and switch between "Default" and "On The Road" whenever you want...

**Comment by kupiqu** [comment]
Cool!

**Comment by psifidotos** [comment]
> there arent any limitations for "on the road" session... so the previous names I dont find them that correct... You can set up your "On The Road" session as you please and switch between "Default" and "On The Road" whenever you want..

meaning also of course the number of docks you use...

> Cool!

I dont know if this will be merged in master... As we discussed we want to test it also and see if there is a demand for this from our users.... It would be nice if there were more active users wanting this...

**Comment by psifidotos** [comment]
@JenaPlinsky @Saboteur777  @mateushonorato @Petross404 

can you give us please your thoughts around this?

**Comment by kupiqu** [comment]
> I dont know if this will be merged in master... As we discussed we want to test it also and see if there is a demand for this from our users.... It would be nice if there were more active users wanting this...

I understand. If not in master, I can grab it from a branch, I guess. Thanks a lot for implementing it!

**Comment by Saboteur777** [comment]
Thanks for the ping! I like the idea, but I think the main goal here are the profiles. Moreover there are function overlap with profile functionality: you would use both function (this and profiles) for the same, but the profiles are more flexible. An ideal merge of the two functionality would be: profiles + a quick toggle for this ("On the road") one. This way we preserve the main takeaway of this feature (quick switch to Public mode) and mix it with the original idea: profiles.

**Comment by audoban** [comment]
I dont like this feature, i consider that a implemetation based con activities. So the user can configurate latte for each activity.

**Comment by psifidotos** [comment]
> An ideal merge of the two functionality would be: profiles + a quick toggle for this ("On the road") one. This way we preserve the main takeaway of this feature (quick switch to Public mode) and mix it with the original idea: profiles.

I dont know if profiles will be supported... This is why I proposed this...

**Comment by kupiqu** [comment]
If there were the possibility to instantly copy an activity with your
current files, folders, etc, but with anonymous plasmoids I wouldn't ask
for the feature ;-)


--

Enviat des del telèfon

**Comment by kupiqu** [comment]
It's fine if you decide not merge this feature to master. I can easily implement a bash script that loads a different config file for latte when "on the road".

I just thought it could be nice to have for other users :)

**Comment by psifidotos** [comment]
> It's fine if you decide not merge this feature to master. I can easily implement a bash script that loads a different config file for latte when "on the road".
> I just thought it could be nice to have for other users :)

we agreed in renaming it at "Alternative Session"... Latte is not going to support multiple profiles...

**Comment by psifidotos** [comment]
the branch was renamed to **_altsession_**....

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/23817641/6a37b332-05fd-11e7-9dd2-6f82c04a579a.png)

**Comment by kupiqu** [comment]
I guess the question is whether it will be merge to master at some point....

I can use the branch for now, but it won't be very efficient for me when the branch gets outdated, neither for you to keep that branch up-to-date with master in a long term :/

**Comment by psifidotos** [comment]
> I guess the question is whether it will be merged to master at some point....

I think that it will be reviewed and without any big problems arising from it, there wont be any problem merging it in master... Please test it also in case I missed any strange bugs from it... In my system it works beautifully!!!! Even the session changing is beautiful....

**Comment by kupiqu** [comment]
I just tried it, works wonderfully

Just a side note: it's second time it happens to me that just running "install.sh" does not work out of the box, but I need to first delete the build directory first.

Just telling for the case you want to add it to the script, or for other users if they see an expected feature seems not to work.

**Comment by psifidotos** [comment]
> Just a side note: it's second time it happens to me that just running "install.sh" does not work out of the box, but I need to first delete the build directory first.

it may happen from time to time with cmake behavior... it is a known small issue with cmake etc... nothing to do with the feature...

Alternative session colored differently in order for the user to understand easily in which session is in...

![image](https://cloud.githubusercontent.com/assets/2216474/23822623/d0fc4726-0658-11e7-969e-91771e7d42d0.png)

**Comment by kupiqu** [comment]
> it may happen from time to time with cmake behavior... it is a known small issue with cmake etc... nothing to do with the feature...

I know, this place is not the right place to discuss this (I could open a different issue related to install.sh script). Would you consider to workaround the issue in cmake by start compilation from scratch? Compilation time is short anyways, it's not like it takes two days to compile...

**Comment by psifidotos** [comment]
> Compilation time is short anyways, it's not like it takes two hours to compile...

unfortunately in my computer is a lot.. I use a dual core of 1.6Ghz and from the two processors, one has been melt... I build latte around 25 times per day minimum... Why are you so concerned ?

Latte is not meant to be installed from master for most of the users... Its goal is to get into packagers hands and make users life a lot easier by just installing it from the repos... after version 0.6 gets out of the door, this wont be an issue... Also this happens very very rare ... In my system only happened 2-3 times in 6months period... And if  a user reports an issue that doesnt exist, we developers can point him to the right direction...

**Comment by psifidotos** [comment]
merged it...

**Comment by JenaPlinsky** [comment]
@psifidotos @audoban @kupiqu 

Immediately, I was perplexed by this idea.
but right now, trying it, I must admit that I like it

the first thing that comes to mind is ...
it would be handy to have a more immediate access such an item on the Latte's context menu
or use the mouse wheel to switch between different sessions, maybe with a check box on the tweak tab to control its access

what do you think about this ?

**Comment by kupiqu** [comment]
If implemented, a latte's context menu would be my preferred option and, in fact, it would be the best place to for the quit option to be, instead of in settings, so settings would only have add and remove panels.

I know quit and remove buttons are clearly for different things, but I recall myself at the beginning clicking the incorrect button, just because I was too fast and because the two buttons are too close by from each other.

Perhaps other users would appreciate this as well...

**Comment by psifidotos** [comment]
> for the quit option to be, instead of in settings, so settings would only have add and remove panels.

I dont agree... in such case the Quit would be very often and easily accesible... So mistakes would happen more often... I still thank plasma developers for integrating the undo behavior for when we delete something accidentaly...

> it would be handy to have a more immediate access such an item on the Latte's context menu
or use the mouse wheel to switch between different sessions, maybe with a check box on the tweak tab to control its access

yes, I like that also but it should definitely be **only available through user configuration**, the vast majority for users I dont think they will ever use "Alternative Session" :)

**Comment by kupiqu** [comment]
> I dont agree... 

Fair enough :)

> in such case the Quit would be very often and easily accesible... So mistakes would happen more often... 

That may be right. I guess I see quit as sth that can easily be restored by launching latte again, while restoring from remove can be done only temporarily. A bit worried for unexperienced users that may try to fix things by just reboot the computer. It would solve quit issues, but not remove issues. I think that's a minor thing given the point below, though.

> I still thank plasma developers for integrating the undo behavior for when we delete something accidentaly...

Me too! This alleviatted these problem so much!! :)
