### ISSUE TITLE
Notifications don't fit as well in Latte as compared to Plasma

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#155]
In plasma notifications don't overlay a panel, but they do in Latte. Please see:

<img width="404" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3875196/22784917/fa007622-ee9f-11e6-8c9d-7bac4ee324c3.png">

Not sure if this is sth easily fixable, though

**Comment by psifidotos** [comment]
I think we can fix this but only for specific docks, docks that are Always Visible with zoom factor 0℅, and have Justify fill mode.

But i think this is also the case for the screenshot

**Comment by kupiqu** [comment]
Nice! :)

It is the case you mentioned (only that the maximum size is scaled to 90%, at least for now until #126 is resolved)

**Comment by psifidotos** [comment]
sorry, I tried what I had in my mind but this is something else...

**Comment by psifidotos** [comment]
ok... an update ... this needs a small investigation... this is fixed already except in startup...

try to open the Latte configuration window of that dock and then just close it... after that the notifications should be shown correctly... but I dont know yet why this happens after the first show/hide of the configuration window

**Comment by kupiqu** [comment]
Weirdly enough, this only happens when scaling is 100%, is there a way to have it for other scalings (e.g. maximum length to 90%)?

**Comment by psifidotos** [comment]
I have no idea... this needs investigation first to understand why it is behaving this way...

**Comment by psifidotos** [comment]
> Weirdly enough, this only happens when scaling is 100%, is there a way to have it for other scalings (e.g. maximum length to 90%)?

this can work to maxLength 90% but the panel background size must be below the iconSize

**Comment by kupiqu** [comment]
Indeed!

However, my background disappears if I set to a size below the icon size now, I don't recall this before, might it be coming from a recent update? Can you confirm this?

Also snapping is not working as good as if panel size >= icon size

**Comment by psifidotos** [comment]
>However, my background disappears if I set to a size below the icon size now, I don't recall this before, might it be coming from a recent update? Can you confirm this?

yes, this is a bug and must be fixed...

> Also snapping is not working as good as if panel size >= icon size

this is logical because the special behavior for good snapping all the time requires panel size >= icon size

**Comment by psifidotos** [comment]
one temporary fix is also to set the zoom factor to 5% but this will make the dock to lose the good snaping when moving windows around, for the maximized windows it will work ok...

**Comment by kupiqu** [comment]
I see. I guess it means that the snapping feature acts also on the notification and that's why it is moved upwards, is it that what's happening?

**Comment by psifidotos** [comment]
no idea...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/22807290/dc7af796-ef2e-11e6-8a2b-c7b7c1e50f19.png)

**Comment by kupiqu** [comment]
Excellent, as usual!

Many thanks :)

**Comment by psifidotos** [comment]
thanks
