### ISSUE TITLE
multi-docks and tool-tips

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#156]
top bar tool-tips ignores control option "show tool-tips" in Latte settings
![screenshot_20170209_233630](https://cloud.githubusercontent.com/assets/24593950/22806101/c8e0e744-ef20-11e6-9663-498d109717e8.png)
![screenshot_20170209_233608](https://cloud.githubusercontent.com/assets/24593950/22806110/d075c506-ef20-11e6-92c5-7ef4a0c80446.png)

...moreover, it would be nice to have tool-tips separate settings for each dock

**Comment by JenaPlinsky** [comment]
ok ... probably, in the example that I have made, the tool-tips of which I speak are those of the system tray, and are not controlled by Latte
however, is there a way to disable the system tray tool-tips and let those of Latte?

**Comment by psifidotos** [comment]
the setting from latte does not correspond to tooltips in general, the translation is wrong!!! It refers to window previews (enable/disable)... If you want to disable tooltips in general in your plasma you should use the plasma systemsettings-> Workspace Behavior -> on the first tab -> uncheck the option, show tooltips

**Comment by JenaPlinsky** [comment]
ok I will correct the translation
