### ISSUE TITLE
Preview windows shows the same image

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#159]
Preview of windows don't work correct. For all of opened apps show the same image.

**Comment by psifidotos** [comment]
send a screenshot

**Comment by divinae** [comment]
![screenshot_20170210_211130](https://cloud.githubusercontent.com/assets/15931906/22842433/8097c25e-efd5-11e6-9436-eb52e3cd1150.png)

**Comment by divinae** [comment]
after first run of dock(im not sure) there is other bug with preview
![screenshot_20170210_215820](https://cloud.githubusercontent.com/assets/15931906/22846082/188ae48c-efe6-11e6-8328-25f11bf6ab2d.png)

**Comment by psifidotos** [comment]
These bugs dont exist with the regular plasma taskmanager? can you check please ?

**Comment by psifidotos** [comment]
these look more as chromium bugs... can you reproduce them with other apps?

**Comment by divinae** [comment]
second bug really looks like chromium problem, but first not 
![screenshot_20170211_091438](https://cloud.githubusercontent.com/assets/15931906/22852368/0cae7ae8-f03b-11e6-9d3a-ca50455879c6.png)

and there is no preview in plasma taskmanager here :/
![screenshot_20170211_091648](https://cloud.githubusercontent.com/assets/15931906/22852373/37b229c4-f03b-11e6-9923-65d4b1554991.png)

**Comment by psifidotos** [comment]
it is the one called "show tooltips" - this is window previews

**Comment by psifidotos** [comment]
I am trying to reproduce this behavior in my system but it doenst occur even with chromium

**Comment by divinae** [comment]
Previews in taskmanager works normal

**Comment by psifidotos** [comment]
in my system the taskmanager previews do not work at all

**Comment by psifidotos** [comment]
the issue you have appears all the time or after a while it is fixed?

**Comment by divinae** [comment]
Bug with the same images appears all the time.
for taskmanager previews i had to enable some option in workspaces settings

**Comment by psifidotos** [comment]
So you see for all previews the cantata one? When you close cantata what happens?

**Comment by divinae** [comment]
I think it is showing image of last focused app. But for SystemSettings preview work correct. 
It's strange.

**Comment by psifidotos** [comment]
a video to demonstrate all this is it possible?

**Comment by divinae** [comment]
i will try, but not today

**Comment by psifidotos** [comment]
:+1:

**Comment by psifidotos** [comment]
ok... I managed to reproduce it but it needs further investigation...
