### ISSUE TITLE
Always keep Latte at top level

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#161]
I was wondering if it would be possible to ignore the option "above over other," it makes sense?

![spectacle j13442](https://cloud.githubusercontent.com/assets/24593950/22861119/4e0f3da2-f111-11e6-9987-a61bc3742562.png)

![screenshot_20170212_103614](https://cloud.githubusercontent.com/assets/24593950/22861105/f6e75000-f110-11e6-9bc1-07b0ab8d6966.png)

**Comment by psifidotos** [comment]
unfortunately this is the default plasma behavior... This could be changed only in kwin if kwin forced Dock type windows to be above regular windows that have set always on top...

There is a chance that this was fixed in wayland for plasma case but I am not sure...
