### ISSUE TITLE
darken the maximized window

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#162]
I was wondering if it is possible to darken the maximized window  in order to give greater prominence to Latte that to the background of the below window ? I do not know if that makes sense, and this is supposed to be just a thought
![spectacle k13442](https://cloud.githubusercontent.com/assets/24593950/22861236/212b6e16-f114-11e6-845b-2228b914ee33.png)

**Comment by psifidotos** [comment]
this is only kwin responsibility, Latte shouldnt have any involvement in this... You could use the panel background, or a plasma theme which can create a panel background that satisfies these requirements... 

I had tried in the past to add a shadow behind Latte icons but it didnt look nice in the end...

**Comment by psifidotos** [comment]
@JenaPlinsky  concerning this, are you aware of a kwin, Desktop Effect that darkens the inactive windows? and you can choose also how much to darken them...
