### ISSUE TITLE
Dodge Active is broken for windows on all desktops...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#164]
@audoban In my system the latest commits broke Dodge Active. In my system it behaves more as an Auto-Hide

**Comment by psifidotos** [comment]
this probably effects **ALL** Dodge modes...

**Comment by psifidotos** [comment]
I dont know why... something with the windows types? For the plasma's system settings dodge active works ok... but with thunderbird and telegram it keeps hiding even though it shouldnt...

**Comment by audoban** [comment]
On my system DodgeActive works fine.

> I dont know why... something with the windows types?

I don't touch windows types valid

**Comment by audoban** [comment]
Tell me what commit started happening

**Comment by psifidotos** [comment]
the commit introduced it is:

https://github.com/psifidotos/Latte-Dock/commit/3ca6a7d096fe6b99999a9c492890237e174fa37e

I think I found the reason...
your new check for current desktop doesnot take into account windows on all desktops

**Comment by psifidotos** [comment]
and also it doesnt check for the windows to be on the same activity or on all activities
