### ISSUE TITLE
Latte-dock's events notification

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#166]
How about, the events notification?
the problem is that I do not know for which events ;)
![spectacle h18792](https://cloud.githubusercontent.com/assets/24593950/22908968/9a37ceb0-f251-11e6-9595-9956f1f5415d.png)

**Comment by audoban** [comment]
What events do you propose?

**Comment by JenaPlinsky** [comment]
Hi
I do not see a real usefulness, so hard to get ideas about it, but maybe someone can think of something of original

hmmm perhaps ...
- show dock
- hide dock
- add applet or launcher
- remove applet or launcher
- open applet
- close applet
- lock applet
- un-lock applet
- move task

**Comment by psifidotos** [comment]
sorry I dont agree... It is not about supporting technologies, but it is about to add value to the user workflow... Notifications are used by default to confirm from the user the delete of an applet, I found value in that. But I cant think of anything else that could add value...

**Comment by JenaPlinsky** [comment]
I agree with you what you say, what I was wondering, if it could be or not be pleasant to add sound effects combined in certain events

**Comment by audoban** [comment]
I'm sorry I do not agree with adding event sounds.

**Comment by audoban** [comment]
@psifidotos I can not find any use for this other than the decoration. What do you think about this issue?

**Comment by psifidotos** [comment]
we can close...
