### ISSUE TITLE
Dock after suspend bug

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#167]
Something like this happens after suspend on my machine: 
![screenshot_20170215_2215](https://cloud.githubusercontent.com/assets/15931906/22995789/8f3dfcec-f3cc-11e6-9413-9ffe5ec06b71.png)
![screenshot_20170215_215238](https://cloud.githubusercontent.com/assets/15931906/22995788/8f3e5066-f3cc-11e6-81be-e464469f16da.png)

**Comment by psifidotos** [comment]
this is probably your graphic driver issue... #163
