### ISSUE TITLE
Disable dock hiding when a plasmoid is activated

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#170]
Is possible drop the  folder-view's opened window, when the mouse approaches to the launchers
or when the dock is hidden ? ...do you think this would be correct?

**Comment by psifidotos** [comment]
this is.the default behavior of plasma, it must lose focus in order to hide...

when a plasmoid is activated on the other hand the dock shouldnt hide but this needs investigation...

**Comment by JenaPlinsky** [comment]
I mean, drop the folder-view's opened window
![screenshot_20170218_014125](https://cloud.githubusercontent.com/assets/24593950/23088305/955047b0-f57b-11e6-9057-742bab2a75c2.png)

**Comment by psifidotos** [comment]
Yes  i understood... Are you proposing to change the default behavior for folderview and hide when loses focus?

**Comment by psifidotos** [comment]
this is fixed in master... concerning not hiding the dock when a plasmoid is active
