### ISSUE TITLE
Multiple Latte instances 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#171]
I happened to accidentally open multiple instances of Latte, and perhaps it would be good to avoid this by killing all Latte's processes before starting a new one

![spectacle na3692](https://cloud.githubusercontent.com/assets/24593950/23082119/480f91a4-f558-11e6-8390-d569b1c78cce.png)
![screenshot_20170217_212628](https://cloud.githubusercontent.com/assets/24593950/23082128/5554070a-f558-11e6-8f25-459be7f077a0.png)

**Comment by audoban** [comment]
We had once thought to avoid this, but we are not sure.

Maybe we should reconsider. @psifidotos what do you think?

**Comment by psifidotos** [comment]
@audoban, I dont understand, avoid what?

The screenshots above do not show two Latte, one is latte and one is plasmashell

**Comment by psifidotos** [comment]
ok... I managed to run 2-3-4 different Latte instances...

@audoban can you check branch **sinstance**  it's  a minimal code and protects from this... Only one instance can run every time...

**Comment by JenaPlinsky** [comment]
No, if it loses focus **must remain active** but maybe, if mouse hovering a plasmoid, as in the screenshot, in these cases I think so, what do you think about ?

**Comment by psifidotos** [comment]
@JenaPlinsky this message goes in other thread
