### ISSUE TITLE
HiDPI and Scaling stretching

### ISSUE THREAD

**Issue by sebbuku** [psifidotos/Latte-Dock#172]
I just received a new notebook with a 4k display. Everythig is looking crisp and great except latte-dock.
The icons and the text look fuzzy and stretched.

My settings:
xdpyinfo | grep -B 2 resolution                                                                                                                                                                
screen #0:
  dimensions:    3840x2160 pixels (351x191 millimeters)
  resolution:    278x287 dots per inch

Scaling is set at 1.5

Icons in Dolphin:
![image](https://cloud.githubusercontent.com/assets/7261864/23083660/19fbea0e-f55f-11e6-9893-4c062f549eed.png)

Application Launcher on the Desktop:
![image](https://cloud.githubusercontent.com/assets/7261864/23083770/9853228c-f55f-11e6-99e4-13a0a4b7ed10.png)

Latte Dock:
![image](https://cloud.githubusercontent.com/assets/7261864/23083808/c0ea7dbc-f55f-11e6-8280-418c5dc2584a.png)

**Comment by psifidotos** [comment]
1. What icon size are you using for Latte

2. Restoring scale factor to 1.0 and increasing the latte icon size what is happening?

3. Other qt5 apps do they look ok? e.g. dolphin

**Comment by psifidotos** [comment]
4. what plasma version are you using?

**Comment by psifidotos** [comment]
@sebbuku is it possible to check also branch **hidpi** to see if fixes this issue ?

**Comment by sebbuku** [comment]
Confirmed. Great work. Thanks!!!

**Comment by psifidotos** [comment]
nice to hear, it works!!!

**Comment by sebbuku** [comment]
By the way there was another bug that the last commit solved. I had a small line under every window aprox. 10 px high and the dock had a very high delay until it showed. But hey everything is working again after the last commit. I thought you just wanted to know.

**Comment by psifidotos** [comment]
good to know!!!
