### ISSUE TITLE
Default debugging geometry window hides some lines

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#174]
![spectacle p11935](https://cloud.githubusercontent.com/assets/24593950/23091773/011be8f4-f5be-11e6-80c1-90c1ce277c07.png)

**Comment by psifidotos** [comment]
this could be fixed by fixed a scrollbar

**Comment by JenaPlinsky** [comment]
it is possible that the user forgets to make all lines visible, so in case of screenshot you lose information
