### ISSUE TITLE
Tips & Tricks "Debug command" 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#175]
ddd --gdb --debugger latte-dock --debug --with-window --graphics --mask

**Comment by JenaPlinsky** [comment]
Just reported on Wiki F.A.Q page

**Comment by psifidotos** [comment]
Tips And Tricks can also be used : https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks
