### ISSUE TITLE
Tooltips hide themselves even though they shouldnt

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#176]
here is this is the exact point:
![screenshot_20170218_110056](https://cloud.githubusercontent.com/assets/24593950/23092445/5eee037e-f5cb-11e6-84b6-1a6828b5c9ae.png)

and now frame by frame
![screenshot_20170218_110127](https://cloud.githubusercontent.com/assets/24593950/23092450/6f61dad2-f5cb-11e6-8f95-76b7a67e2b5a.png)

and now frame by frame
![screenshot_20170218_110143](https://cloud.githubusercontent.com/assets/24593950/23092451/73ec808e-f5cb-11e6-98dd-640adc2b0dd1.png)

and now frame by frame
![screenshot_20170218_110225](https://cloud.githubusercontent.com/assets/24593950/23092452/780fc84c-f5cb-11e6-81d2-380b05eeaad3.png)

and now frame by frame
![screenshot_20170218_110259](https://cloud.githubusercontent.com/assets/24593950/23092453/7d101266-f5cb-11e6-87e8-12b8a678c4d7.png)

**Comment by JenaPlinsky** [comment]
> I observe a strange flickering to Tooltips hide themselves even though they shouldnt

in addition to this, there is also, in the position indicate in the first screenshot, a strange pumping on the zoomed icon

**Comment by psifidotos** [comment]
> in addition to this, there is also, in the position indicate in the first screenshot, a strange pumping on the zoomed icon

I dont understand what this means... is this relevant to this thread ?

**Comment by JenaPlinsky** [comment]
with the #176 fix
you have fix the issue concerning...
> in addition to this, there is also, in the position indicate in the first screenshot, a strange pumping on the zoomed icon
Well done !!!

**Comment by psifidotos** [comment]
nice !!
