### ISSUE TITLE
Animation on plasmoid first icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#177]
frame1:
![screenshot_20170218_182019](https://cloud.githubusercontent.com/assets/24593950/23095305/e06374fc-f607-11e6-9a2a-d0eeae15fbb1.png)
frame2:
![screenshot_20170218_182113](https://cloud.githubusercontent.com/assets/24593950/23095303/d8daa5de-f607-11e6-9ea0-0f05d718dd32.png)

**Comment by JenaPlinsky** [comment]
You can consider this issue fixed, with plasma_5.9.90 everything works fine

**Comment by JenaPlinsky** [comment]
Sorry @psifidotos this a my paste error !!! :(  this issue is still active

**Comment by psifidotos** [comment]
when does this happen? in my system happens the mouse enters the preview tooltip... does it occur to you in other cases also ?

**Comment by JenaPlinsky** [comment]
No, only in that case ... then I do not know if it is to be considered a defect, but I thought to report it anyway

**Comment by JenaPlinsky** [comment]
You have also fix this issue. Great I can confirm
