### ISSUE TITLE
Weather plasmoid and unrensponsive debug script

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#179]
from autostart, this script runs
```
#!/bin/bash
killall -9 latte-dock 2>/dev/null  # This is no longer necessary
ddd --debugger latte-dock --debug --with-window --graphics --mask
```
after clicking near the applet "Wewther"
I get an unressponsive dock
and clicking on the backtrace command does not get anything, in the sense that ddd is not responding
what I was expecting, however, it was to see the task of konsole opened with the currently executing script
here are the pictures
![screenshot_20170218_210301](https://cloud.githubusercontent.com/assets/24593950/23096602/2f5768d0-f620-11e6-9582-c8494c396a4c.png)
I note missing konsole process
![screenshot_20170218_210701](https://cloud.githubusercontent.com/assets/24593950/23096603/315f9166-f620-11e6-865b-2950b288b1a4.png)
![screenshot_20170218_210719](https://cloud.githubusercontent.com/assets/24593950/23096614/624a695e-f620-11e6-853f-866d440ec7a4.png)

instead, here's the konsole after killing Latte and restarted
![screenshot_20170218_210957](https://cloud.githubusercontent.com/assets/24593950/23096604/341c39ae-f620-11e6-9087-7482a5d6077b.png)

**Comment by psifidotos** [comment]
I dont understand the issue...

- this is not a crash so a backtrace from ddd is not generated.

- the missing konsole if it wasnt executed from you it could be just the one used from ddd in order to print the text output...

**Comment by JenaPlinsky** [comment]
Yes, you're right
however, I confirm that the triggering event is the wether applet, but even here it is hard to replicate

**Comment by psifidotos** [comment]
Weather plasmoid has also a  very rare crash if i remember correctly... i wouldnt be suprised if the crash is related to applets models handling

**Comment by JenaPlinsky** [comment]
yeah, well I thought the same thing
and probably this is true also for applets "user switcher" ... the strange thing is that it's never happened with the default plasma dock

**Comment by psifidotos** [comment]
this doesnt mean that the applet's code is free of crashes in all use cases
