### ISSUE TITLE
The QEvent:Leave at DodgeActive does not hide the dock

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#18]
After the mouse leaves the dock in DodgeActive even though the dock should be hidden when it covers the active window, it does not

**Comment by audoban** [comment]
ok, when, the mouse leave the dock should call also dodgeActive()
I'm fixing this

**Comment by psifidotos** [comment]
this should be use the hideTimer in order to not hide immediately affter the QEvent.Leave event

**Comment by psifidotos** [comment]
fixed in master
