### ISSUE TITLE
Reordering launchers in Plasma 5.9 does not work

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#188]
this has been reported also to upstream from the users... the bug is in the libtaskmanager probably...

**Comment by audoban** [comment]
It's okay.

**Comment by psifidotos** [comment]
@audoban 
- does it store the new order of launchers?
- when you change activities or restore Latte the order is the new one ?

**Comment by psifidotos** [comment]
@audoban  and now the big question.... launchers handling in libtaskmanager was changed...
if I update latte into the new infrastructure it would mean that launchers wouldnt work in plasma 5.8...

any ideas?

**Comment by audoban** [comment]
> if I update latte into the new infrastructure it would mean that launchers wouldnt work in plasma 5.8...

any ideas?

Update to the new infrastructure, and use a conditional build for maintain the backward compatibility.

**Comment by psifidotos** [comment]
this hits also plasma according to the mailing list... scheduled to be fixed for 5.9.3 but this hasnt been confirmed yet...

**Comment by psifidotos** [comment]
I confirmed that this wasnt an upstream bug but because all the launchers architecture changed in 5.9, I prepared a patch that makes our architecture to restore our functionality with the new architecture
