### ISSUE TITLE
latte crash with active window control using app menu (it works in plasma panels)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#189]
This is associated to issue https://github.com/kotelnik/plasma-applet-active-window-control/issues/42

I don't know where the ultimate issue is, whether in the applet or in latte. Could you please take a look?

Many thanks!

**Comment by kupiqu** [comment]
I found that the issue is the size of the panel, it works for >40px, it crashes for 32px.

I'll check, but surely the same happens for plasma, if panel is thin too

**Comment by kupiqu** [comment]
I think I can close this now, as it really seems an issue in the applet

**Comment by kupiqu** [comment]
It's weird, although most likely the issue is in the applet, it doesn't make plasma crash.

@psifidotos, could you please take a look to see if there is an easy workaround for the issue? Thanks in advance!

**Comment by psifidotos** [comment]
> @psifidotos, could you please take a look to see if there is an easy workaround for the issue? Thanks in advance!

This is again something with the model... A deleted item is trying to be painted but I cant find an easy fix

**Comment by kupiqu** [comment]
I see. Thanks for taking a look :)

**Comment by psifidotos** [comment]
@kupiqu is this fixed with Plasma 5.9.3 ? I am trying to reproduce it but I cant... it works ok in my system....

**Comment by kupiqu** [comment]
It is still happening to me. I workaround it by reducing "font size scale" in the active window control applet.

**Comment by kupiqu** [comment]
The way to trigger the issue in my case is to reduce the size of the latte panel enough (in my case 32 px).

**Comment by psifidotos** [comment]
@kupiqu, unfortunately I used 24px and it didnt crash ... neither or loading or updating different values...

**Comment by kupiqu** [comment]
can you go down, e.g. 16 px, to see if it crashes? perhaps you did already

btw, I see now a % of screen height proportion setting which is disabled in my settings, should I try this out. It might be better to compare relative sizes instead of absolute ones...

**Comment by psifidotos** [comment]
> can you go down, e.g. 16 px, to see if it crashes? perhaps you did already

i will test it to confirm...

> btw, I see now a % of screen height proportion setting which is disabled in my settings, should I try this out. It might be better to compare relative sizes instead of absolute ones...

this settings is used more on multi-screen environments, Latte adopts its size according to screen resolution... So the dock when moves from a 4K resolutions to normal ones adapts its applets size accordingly...

**Comment by kupiqu** [comment]
> this settings is used more on multi-screen environments, Latte adopts its size according to screen resolution... So the dock when moves from a 4K resolutions to normal ones adapts its applets size accordingly...

I see. It might also be useful for the case one wants same aspect in two different computers :)

**Comment by kupiqu** [comment]
That setting starts at 3%, that is too wide as starting point IMO, could it start from a lower value?

**Comment by psifidotos** [comment]
>  That setting starts at 3%, that is too wide as starting point IMO, could it start from a lower value?

yes it can...

**Comment by psifidotos** [comment]
but will need adjustments...

it could start from 1.5 %
