### ISSUE TITLE
Dodge Maximized is not functioning properly

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#19]

**Comment by audoban** [comment]
I'm fixing now

**Comment by audoban** [comment]
I think I can fix it. But I have to debug more

**Comment by audoban** [comment]
There are still problems changing desktop. It's almost ready.

**Comment by audoban** [comment]
Can we close this bug?

**Comment by psifidotos** [comment]
have the commits fixing this been commited to master?
