### ISSUE TITLE
Improvements in the management of resources and memory

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#190]
Let's discuss ideas here to improve memory consumption.

My ideas:

Convert the Interface `AbstractWindowInterface` on a shared resource or singleton class.
Join `WindowSystem` with `AbstractWindowInterface`

Find bottlenecks with QML and Callgrind profiling.

**Comment by psifidotos** [comment]
ok... no prob....

> Join WindowSystem with AbstractWindowInterface

these are in different places... WindowSystem is in the plugin because it is used by the latte plasmoid and the AbstractWindowInterface is inside the app... what do you have in mind?

I would like to keep the possibility to be able to add the Latte plasmoid in the desktop without the Latte dock...

**Comment by audoban** [comment]
> these are in different places... WindowSystem is in the plugin because it is used by the latte plasmoid and the AbstractWindowInterface is inside the app... what do you have in mind?

Export AbstractWindowInterface instead of WindowSystem.

**Comment by psifidotos** [comment]
Are we going to move the abstractwindowinterface into the plugin?

**Comment by JenaPlinsky** [comment]
a curiosity
you can make comparisons with other dock, in terms of memory consumption? How's it going Latte?

**Comment by audoban** [comment]
> Are we going to move the abstractwindowinterface into the plugin?

yes.

> you can make comparisons with other dock, in terms of memory consumption? How's it going Latte?

It would be fine, it could be a good way to know where we are in terms of memory consumption.

**Comment by psifidotos** [comment]
>Are we going to move the abstractwindowinterface into the plugin?
> yes

this is a big architectural change... so the work must go in an alternative branch for reviewing etc...
this will need too much attention in order to not brake things and miss features in the process...

the good part is that having multiple docks running they will all use the same instance...

**Comment by audoban** [comment]
> this is a big architectural change... so the work must go in an alternative branch for reviewing etc...
this will need too much attention in order to not brake things and miss features in the process...

> the good part is that having multiple docks running they will all use the same instance...

we need to be careful

**Comment by audoban** [comment]
Leave me join the classes.

**Comment by psifidotos** [comment]
lets keep just #199 for memory issues thread...
