### ISSUE TITLE
Use percent for calculate the size background.

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#191]
It would be more convenient to use percentages to calculate the thickness of the background. because regardless of the size of the icons of the background will be proportional to the icon size.

**Comment by psifidotos** [comment]
It makes sense but there are cases that i want the panel size be set with pixels accuracy especially in the lower values

**Comment by audoban** [comment]
could you use a minimum size on px?

**Comment by psifidotos** [comment]
> could you use a minimum size on px?

it's very different from theme to theme... values 0,2,4,6,8,10,12,14,16 px. these are very important for the user to provide a beautiful experience...

i cant agree with this...

**Comment by audoban** [comment]
But on the current implementation 0px don't correspond to 0px exactly. The background is ever visible even when the user configure 0px.

We can use percent, but with minimum size on px.
