### ISSUE TITLE
Spotify behavior when using Dodge Active

### ISSUE THREAD

**Issue by joseffilzmaier** [psifidotos/Latte-Dock#192]
Hello, and thank you for your work!
This dock is a really promising opportunity for the plasma desktop!

After trying this dock for a few days i noticed a problem in the following scenario:
* I am using Archlinux, Plasma 5.9.2
* With the [Spotify](https://aur.archlinux.org/packages/spotify/) application
* Now Dock version 0.5.91 from [AUR](https://aur.archlinux.org/packages/latte-dock/)
* I use the setting "Dodge Active" without delays
* Location: left, Alignment: center

The problem i have is that if spotify is the active, maximized window the latte dock is *not* hidden.
I know that this bug probably has to do with spotify setting incorrect window properties. I have tried using [spotifywm](https://github.com/dasJ/spotifywm) but it didn't work.

The expected result would be that latte dock hides in this scenario.

Thanks

**Comment by psifidotos** [comment]
this is fixed is master by a workaround ...

infos: #80
