### ISSUE TITLE
Tips & Tricks "How to autostart latte-dock"

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#193]
![screenshot_20170220_192221](https://cloud.githubusercontent.com/assets/24593950/23137504/a97526a6-f7a2-11e6-9f4d-2d22157a33cb.png)
![screenshot_20170220_192307](https://cloud.githubusercontent.com/assets/24593950/23137511/ad2c2db2-f7a2-11e6-8c26-d1039cc724b5.png)

**Comment by JenaPlinsky** [comment]
Just reported on Wiki F.A.Q page

**Comment by psifidotos** [comment]
this is added and more infos the user can get from the WiKi

**Comment by psifidotos** [comment]
you can also user from know on: https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks
