### ISSUE TITLE
Background very translucent

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#194]
Why the background of latte is more translucent that plasmashell?

*latte right and plasmshell  bottom*
![screenshot_20170220_183519](https://cloud.githubusercontent.com/assets/7884292/23145304/5d6aa1fc-f79b-11e6-9985-2808e34149e8.png)

I wish it were opaque.

**Comment by psifidotos** [comment]
because in plasma the blur and background contrast kwin effects are used which we cant use... disable them and you will see same transparency... except of course when we draw the shadows externally in X or wayland, in this case we can support it

**Comment by audoban** [comment]
Maybe we can use a FastBlur from QML for the background

**Comment by psifidotos** [comment]
You can try but it will be costly

also the blur effect blurs the contents behind the window, that is the desktop and the windows below, no the background content

**Comment by audoban** [comment]
I known that blur effect isn't cheap, but a FasBlur is more quickly that a GaussianBlur. But we need see the overload with QML profiler for a background with blur and without blur effect.

**Comment by audoban** [comment]
Maybe we can consider add to configuration a `enable blur effect`.

**Comment by psifidotos** [comment]
I dont object in any of these...
I had tried it in the past it didnt work...feel free to experiment...
as an info, blurring an image that all pixels have the same color it doesnt blut something...

an alternative approach could be to add some effects to reduce transparency by user choosing this from the settings...

BTW, what theme is used in the screenshot? it has too much transparency in it...with breeze, arcdark etc... the annoyance isnt so big...

**Comment by psifidotos** [comment]
Instead we could use : http://doc.qt.io/qt-5/qml-qtgraphicaleffects-leveladjust.html

to disable transparency for the panel background if the user chooses to....

**Comment by psifidotos** [comment]
for example in most cases this could be used in PanelBox.qml:

```
        LevelAdjust {
               anchors.fill: solidBackground
               source: solidBackground
               minimumOutput: "#ff000000"
               maximumOutput: "#ffffffff"
         }
```

but sometimes the round corners do not look ok with the filter...

**Comment by psifidotos** [comment]
and another solution would be instead of use the generic "widgets/panel-background", we could use the specific "widgets/opaque/panel-background" but in such case there will not be any round corners but I am not totally sure....

**Comment by audoban** [comment]
I can upload an branch for testing?

**Comment by psifidotos** [comment]
of course!!! but it has to be by user choice, ok?

**Comment by audoban** [comment]
ok course.

**Comment by psifidotos** [comment]
this work is also inside the **newoverlap** branch.. it looks pretty nice in my system...
