### ISSUE TITLE
Proper way to use Latte Dock: Is there any use for Latte Dock *widget* or should one just launch latte-dock?

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#196]
Hello. Once again I 've come to replace Cairo Dock and I thought Latte Dock (as the great NowDock) could be very usefull. Although I wrote an ebuild for my Gentoo system and installed it the proper Linux way, I am not sure that I use the Dock correct.

I launch it just from menu, without any Latte Dock widget or applet on the desktop. Is there any use for this and I am using the software wrong?

Please forgive my ignorance, it seems to work pretty much ok without it.

**Comment by psifidotos** [comment]
**Latte is used directly as an app... So you just execute it from the menu...**

The Latte widget can be used separately for fast testing purposes :-)

**Comment by Petross404** [comment]
Thank you very much and congratulations for Latte Dock 👍 

Last thing, is there a FAQ, or something like a help page/blog about expert configuration, tweaking or even helping in development? It  whould be super usefull to know some of the ins and outs of the software.

**Comment by psifidotos** [comment]
thank u!!!

> Last thing, is there a FAQ, or something like a help page/blog about expert configuration, tweaking or even helping in development? 

except the README and INSTALLATION files there isnt something relevant yes... but of course we are totally open for contributions in every scale of the project.... A good place for a FAQ could be the Wiki page of the project... feel free to submit content for this... e.g. upload any questions you find them important and we will answer them... Latte is a very big project so it hides many cheerys and cookies for different configurations... :)

>  It whould be super usefull to know some of the ins and outs of the software.

of course... feel free to help with that one in the Wiki - FAQ

**Comment by Petross404** [comment]
Well, clicking on `Wiki` on top of the page doesn't do anything, besides redirecting me to the `Code` tab. Am I missing something?

**Comment by psifidotos** [comment]
I have just added two pages in the wiki... one is f.a.q.  does it give you edit access?

If it doesnt you should clone the wiki, make any changes you want and make pull request afterwards

**Comment by Petross404** [comment]
No, it doesn't. I will make a pull request sometime in the next day. I guess you meant, fork the wiki and make changes. It's my first time trying to make pull request and plain google says cloning doesn't cut it; it needs to be forked first.

Anyway, will take a look at it in the next morning buddy. Thank you for patience.

**Comment by psifidotos** [comment]
I hope you make it!!!

Thank u for your involvement

**Comment by Petross404** [comment]
I am sorry, I just can't get it. There isn't a fork button for wiki and I am all-around utterly confused with pull requests.

Anyway, if there is a way you get this file, or copy it's contents, here it is.
https://github.com/Petross404/wiki/blob/master/F.A.Q..md

Maybe README.md should contain techinal info, which of course will be written by someone more involved with the project.

**Comment by psifidotos** [comment]
@Petross404 sorry for this, it was my mistake, I had restricted edit access to wiki to only registered contributors...
if you access Latte wiki again it should give you editing access directly from the web interface

**Comment by Petross404** [comment]
Take a look at the questions, the overall style and edit the FAQ so that you like it. Thank you very much, appreciated 👍

**Comment by audoban** [comment]
@Petross404 Great contribution

**Comment by Petross404** [comment]
@audoban Thanks :)

**Comment by JenaPlinsky** [comment]
You could add Wiki F.A.Q. page to the Latte's "about dialog"

**Comment by Petross404** [comment]
Maybe start a new issue with the right title and then append this label? I shouldn't hijack the current issue with another question.

**Comment by JenaPlinsky** [comment]
No sorry !! the comment, was a suggestion referred to the developers. They think them,  if they consider the case to assigning the most appropriate labels

**Comment by JenaPlinsky** [comment]
@Petross404 
If the developers agree, it could be also interesting, add pages as "Road Map" and "Feautures"
