### ISSUE TITLE
Make LatteDock override kwin's "Keep Above Other's" for a window

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#198]
A small enhancement could be the ability to remain on top of **all** windows, even if for some the option "Keep Above Other's" is ticked.

Or Latte could indeed be (partially) hidden from such a window, but appear the rest of the dock and override the window temporarily, when the mouse pointer is aprroaching at the bottom of the dock.

This way the window can indeed be above all other's (and above the Dock) like the user want it to be, but he/she can also use the Dock if the window is hiding it and he/she move the pointer to the bottom of the Dock.

**Comment by psifidotos** [comment]
duplicate #161

I have the opinion that changing default behaviors such as this is may not be the proper way to go forward.... This is totally the window manager responsibility e.g. to keep Dock windows always on top even on top of keep above windows... I have read somewhere that wayland will behave like this by default but I am not sure...

Either way, I dont decide alone...

@audoban what is your opinion? personally I think this is an upstream issue

**Comment by Petross404** [comment]
Oh, I see. Good to know though.

Keep up the good work folks :-)

**Comment by audoban** [comment]
@audoban what is your opinion? personally I think this is an upstream issue

There may be limitations for X11, but we will have to ask the KWin team

**Comment by psifidotos** [comment]
the only way I can think of for this to be implemented in our side is that when a window in dock's screen set itself to "above all" then the dock must re-enable its "above all" again by disabling/reenabling it. If I have unnderstood it correctly on top of above all windows is the last one that have set itself above all. 

my opinion is that it depends on the complexity it adds... I think this is upstream but you can give it a shot to see how it's going...

-----

@audoban the above behavior should also happen when the active window changes... The dock must still the focus and become active...

I am starting to believe this is possible only in window manager level

**Comment by Petross404** [comment]
Cairo Dock had this behavior and maybe we can take a look at it's code. Actually Cairo Dock didn't disappear at all, no matter which window approaced the screen's bottom edge. It always was above the windows when the corresponding option was set.

But Cairo Dock is a another software and is written in gtk+ (I think), it doesn't make use of plasma's internals.

**Comment by JenaPlinsky** [comment]
Ciao @Petross404 
Out of topic:
Can you make ua comparison between Cairo-Dock and Latte in terms of memory consumption for their processes ?  (...possibly with a similar configuration intended as pitchers and tasks)
I think that might be useful

**Comment by Petross404** [comment]
Aboslutelly doable. I will do it as soon as I use my desktop today. Although the tasks and launchers are somewhat similar, in Latte I have added some plasma wigdets (system tray).

I hope this isn't a big deal, otherwise I will temporarily remove it.

**Comment by JenaPlinsky** [comment]
if the comparison is made with similar configurations, the test takes on a more significant value
Please, then, could you paste the results on the #199 issue
Thanks a lot

**Comment by JenaPlinsky** [comment]
@audoban @psifidotos 
Can you do a few considerations on this comparison of Latte and the ultra optimized Cairo born many several years ago ?

**Comment by psifidotos** [comment]
> Cairo Dock had this behavior and maybe we can take a look at it's code.

interesting... possibly it was using the flag: X11ByPassWindowManagerHint these windows are always on top, but I dont know what is happening with tooltips and menus...

> Absolutelly doable. I will do it as soon as I use my desktop today. Although the tasks and launchers are somewhat similar, in Latte I have added some plasma wigdets (system tray).
> I hope this isn't a big deal, otherwise I will temporarily remove it.

it is... every widget you add adds more to memory.... the systray adds a lot of memory because because it is a container of many widgets... 
the best case would be to compare only with tasks...

**Comment by Petross404** [comment]
> it is... every widget you add adds more to memory.... the systray adds a lot of memory because because it is a container of many widgets...
the best case would be to compare only with tasks...

Here you are 
![latte3](https://cloud.githubusercontent.com/assets/18561627/23331974/019f5368-fb79-11e6-918e-a0cbc28a0010.png)

**Comment by psifidotos** [comment]
@Petross404 how many icons are shown ? and what icon size?

**Comment by Petross404** [comment]
56 icons and with a size of 20. That is without the system tray of course.

**Comment by psifidotos** [comment]
> 56 icons and with a size of 20. That is without the system tray of course.

oh!!!! and the cairo dock had the same number of icons and icon size ?

**Comment by Petross404** [comment]
Yes it did. Maybe cairo's icons were 22 but certainly not above that.

**Comment by Petross404** [comment]
22 = size not the number of icons!

**Comment by psifidotos** [comment]
@audoban this is done easily by adding into dock window flags, ByPassWindowManagerHint,

do you agree adding it?

I am positive...

**Comment by Petross404** [comment]
If it is going to be added, should it's compilation be conditional with cmake option?

**Comment by psifidotos** [comment]
> If it is going to be added, should it's compilation be conditional with cmake option?

why? it will work directly but for this to be added all the developers must agree

**Comment by Petross404** [comment]
Just for configurability. Nothing more really

**Comment by audoban** [comment]
> @audoban this is done easily by adding into dock window flags, ByPassWindowManagerHint,

What do you want with this flag?

the documentation of Qt tell: 
```Bypass the window manager completely. This results in a borderless window that is not managed at all (i.e., no keyboard input unless you call QWidget::activateWindow() manually).```

**Comment by psifidotos** [comment]
@audoban  this flag **breaks snap and struts** for always visible state...

**Comment by psifidotos** [comment]
I dont know if it is possible to support both cases correctly...

**Comment by audoban** [comment]
> I dont know if it is possible to support both cases correctly...

I'll try it to fix at  tonight

**Comment by JenaPlinsky** [comment]
@Petross404 
regression on "keep over other"
sometimes Latte remains covered
[test](https://youtu.be/L9jwZeGXpx0)

**Comment by psifidotos** [comment]
fixed in master

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/23757418/73c799f8-04ef-11e7-9d4a-3933f3c1f2a1.png)
