### ISSUE TITLE
Test memory consumption

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#199]
From last master branch...
Here is the latte-dock's memory consumption, taken after its start-up
![screenshot_20170224_033238](https://cloud.githubusercontent.com/assets/24593950/23288147/fa970e54-fa41-11e6-87be-f91331ffeaf2.png)

...and here is the latte-dock's memory consumption, taken after a bit of random tweaking between applets, launchers and tasks
![screenshot_20170224_032617](https://cloud.githubusercontent.com/assets/24593950/23287988/151ed80c-fa41-11e6-9b95-90c524f03a3b.png)

Why, after growing by nearly 50%, and after remaining idle for a long time, this does not return the start-up value? (Note, that has not been added or removed anything)

**Comment by psifidotos** [comment]
1. The memory garbage of qt is not so good... something to be improved at qt 5.9

2. Are you using latest master?

3. Qml during the process it says it loads to memory elements based on usage and at some point it finds the needed equilibrium... the memory used at startup is not at the equulibrium yet..

4. based on personal experience, the metrics usually are...

latte is using 40-50mb more comparing with deprecated nowdock when used internally at plasmashell

(1)plasma,nowdock = plasmashell + nowdock
  
(2)latte,plasma = latte+plasmashell

(2) is usually 40,50Mbyte more from (1) case

**Comment by JenaPlinsky** [comment]
Yep, i'm using the last master branch

**Comment by audoban** [comment]
I have made some improvements in resource management

**Comment by audoban** [comment]
But we probably can not do much with garbage collector qml

**Comment by JenaPlinsky** [comment]
Ciao audoban 
Well, certainly the qml garbage collector infrastructure will evolve and improve with future releases.
Is there a chance to force a reset for the garbage collector without compromising Latte, maybe on a change of activity or desktop switch or hidden state?

**Comment by audoban** [comment]
Call directly the garbage collector it is discourage, but I personally think QML is highly optimized.

I think that we should take Into account the recommendations of Qt: [Performance Considerations And Suggestions](http://doc.qt.io/qt-5/qtquick-performance.html), I personally think QML is highly optimized.

But the biggest problem here is undoubtedly the images or icons, we have to look for optimizations for this apart, because this is always the most expensive.

**Comment by Petross404** [comment]
The test procedure was this : I launched CairoDock (without Latte running), I took a snapshot of it's memory use. Then I played a little with it and took another. After `killall -9 cairo-dock` I did the same for Latte.

Cairo Dock, fresh started : 
![cairo1](https://cloud.githubusercontent.com/assets/18561627/23331224/47d88692-fb6a-11e6-82e3-a2c6b18046d9.png)

Cairo Dock, after a few minutes of clicking : 
![cairo2](https://cloud.githubusercontent.com/assets/18561627/23331229/6723b1ac-fb6a-11e6-9065-0981788c4e9b.png)

Latte Dock, fresh started:
![latte1](https://cloud.githubusercontent.com/assets/18561627/23331232/72cdcc04-fb6a-11e6-88df-a3b4c2ffc1fe.png)

Latte Dock after a few minutes of clicking:
![latte2](https://cloud.githubusercontent.com/assets/18561627/23331263/fd5dd3fa-fb6a-11e6-82c2-d9c02b4034d5.png)

Stupid cursor. Always above my user. I forgot to put a little paint with gimp above that.

**Comment by JenaPlinsky** [comment]
@audoban @psifidotos 
Can you do a few considerations on this comparison of Latte and the ultra optimized Cairo born many several years ago ?

**Comment by Petross404** [comment]
@JenaPlinsky I think it's not their fault. After all Cairo Dock is a plain gtk+ application and Latte is based has dependencies on QML and framework.

If QML and Qt don't become optimized themselves, little a developer can do.

**Comment by JenaPlinsky** [comment]
Well yes, of course !!!
It is just to understand the potential of the entire QML,QT,C ++ and Plasma framework infrastructure

**Comment by psifidotos** [comment]
@Petross404 can you try this comparison again but latte should have only one dock and only the tasks plasmoid... **not even the clock**

**Comment by psifidotos** [comment]
@Petross404 _and another interesting case it would be to test with no plasmoid at all... not even the tasks... this would show us the memory usage inherited from qt and plasma-frameworks...._

**Comment by psifidotos** [comment]
also.... 

@Petross404 @JenaPlinsky @kupiqu if you have a multi screen setup and you want to test the new multi-screen behavior, you could try the **multiscreens** branch

**Comment by kupiqu** [comment]
Sorry, I don't have multiscreen setup right now. I could try this on Tuesday...

**Comment by psifidotos** [comment]
@kupiqu  of course... give us your feedback then...

the thread for multi-screen will be: #12

**Comment by kupiqu** [comment]
Sure!

**Comment by psifidotos** [comment]
just to add in the metrics:

1. Latte with not any plasmoid!!!!: 20Mbyte (so this is the heap by loading all the libraries needed and the theme)
2. Latte with only the task plasmoid and three icons in it: 42Mbyte 
3. Latte showing the configuration window: 64Mbyte that are not dropped when the configuration window closes... (we keep the configuration window in memory in order to be smooth when shown the next times, I am definetely possitive to restore the memory release when the configuration window is closed for 2 minutes, this is the plasma default behavior)

**Comment by JenaPlinsky** [comment]
Unfortunately I do not have a chance to test the multiscreens branch :(

**Comment by JenaPlinsky** [comment]
I had the impression that the garbage collector does not release the memory **used by the applet**, but I should investigate better ..maybe when QT5.9 will be available

**Comment by Petross404** [comment]
> ...if you have a multi screen setup and you want to test the new multi-screen behavior, you could try the multiscreens branch

I wish I had a second screen. But I might plug the desktop's screen I am using now to the laptop and test it from there.

**Comment by JenaPlinsky** [comment]
![spectacle kh6068](https://cloud.githubusercontent.com/assets/24593950/23333610/66eb458c-fb8e-11e6-9600-06c4d4b38ec6.png)
Shared mem what does it mean?
In my system is always greater than 2GB ... significantly different than the Petross404's screenshots  
@psifidotos  ...it also happens to you?
The same thing happened to me when I was on Tumblewed
Is it normal ?
...then, it happens to me that when the system is overloaded, Latte process goes,for a while, in "disk wait" and is not responding while the defaut panel responds

**Comment by JenaPlinsky** [comment]
eheheheh I know there are, messed issues

**Comment by JenaPlinsky** [comment]
Also is Latte using GPU hardware acceleration? and if so ...what would change?

**Comment by Petross404** [comment]
> Also is Latte using GPU hardware acceleration? and if so ...what would change?

Correct me if I am wrong, but isn't this determined by kwin and/or qt's graphics system (opengl, raster etc)?

**Comment by JenaPlinsky** [comment]
Sorry I can not answer :-(
I think, however, that a comparison with logical sense, is also very complicated to do
There are so many things I do not know about it
and I wonder, also, whether the type of icon PNG or SVG vector can affect the test?
It must also consider that Latte is independent from the plasma-shell and that it free the latter from workload to manage tasks, applets and launchers

**Comment by psifidotos** [comment]
- latte is using svg's
- latte us using graphics acceleration through QML 2, the type of the acceleration is determined through qt... by default plasma uses raster
- if latte is not responding because of a computer workload, this is either by a specific applet causing it or because of latte's animations... you could try to disable to zoom effect
- in my system virtual memory is also 2Gb and plasma has 3.5 Gb, by googling its nothing important
- by dont using Latte and use Now Dock with plasma the memory metrics are very near

**Comment by JenaPlinsky** [comment]
Fantastic clear and precise as ever ...thanks

**Comment by Petross404** [comment]
> and another interesting case it would be to test with no plasmoid at all... not even the tasks... this would show us the memory usage inherited from qt and plasma-frameworks....

@psifidotos  I am terribly sorry, I haven't seen this comment. I did remove both the clock and the plasmoid applet, but I did the test in my laptop (Arch Linux) where it has smaller RAM and overall different memory-caching results.

![spectacle c22469](https://cloud.githubusercontent.com/assets/18561627/23339479/0d623cb6-fc2c-11e6-9a1f-52648f92bb31.png)

With plasmoid applet (and 4 launchers, size 24) and a clock too.

![latte_widgets](https://cloud.githubusercontent.com/assets/18561627/23339487/37144996-fc2c-11e6-8209-da659c6c73e1.png)


I will later test the same in my desktop, where I have 8Gb RAM and the caching is more agressive. 

Also, can you redirect me to some instrunctions of how to force Latte, show up in 2 screens?
I did clone the repo, changed and checkouted the `multiscreens` branch, but I think I am missing something.

**Comment by psifidotos** [comment]
> Also, can you redirect me to some instrunctions of how to force Latte, show up in 2 screens?

you cant... you can add a second dock if you want and associate it with the second screen... all this from the Latte configuration window

**Comment by psifidotos** [comment]
**_so.... this is landed in master!!!_** 

**_With multi-screen support
the user can set for its docks either to be always
on the primary screen or an explicit one... The
docks are loaded and removed automatically on
screen changes_**

**Comment by JenaPlinsky** [comment]
@audoban @psifidotos 
I updated a while ago and I notice a decrease in memory consumption in about 30% ... possible? Can you confirm

**Comment by psifidotos** [comment]
It can be but i dont know about that much, we are deleting the config window when it is hidden to free its memory...

**Comment by JenaPlinsky** [comment]
But how good you are !!! compliments and professional

**Comment by psifidotos** [comment]
until we have a solid approach and real metrics that express exactly in what areas we can imrove our memory usage I am closing this..
