### ISSUE TITLE
(crazy) feature request: alternative method to icon size scaling + hover zoom effect

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#200]
First some context... Current behavior of latte dock is that icons' size scale down if there isn't available space in the panel. Also, users can use zoom on hovering.

What I am proposing is an alternative method, which I think may increase usability.

1. Instead of scaling icon sizes down, I would like icons to be shear transformed, i.e. icons appearance would be stretched so they'd occupy much less space while still identifiable. The amount of stretch would be proportional to how much extra space is needed (plus the space that would be needed on hovering, see point below).

2. This hover effect should be applied only if icons are stretched (see above), so on hovering I would like to undo the stretching of the hovered icon, as well as to reduce the stretch of icons in its vicinity, similar to what the parabolic zoom effect does on hovering. 

I don't know if this is doable (at all) in qml, or how easy/difficult it would be to implement, but if doable, I think it would be a very useful and cool effect for the latte task bar.

This is a bit difficult to explain and may also be a bit difficult to get what I meant, so if sth is unclear, please let me know...

**Comment by kupiqu** [comment]
This link may help a bit in what I meant by shear transformation or mapping:

[https://en.wikipedia.org/wiki/Shear_mapping](https://en.wikipedia.org/wiki/Shear_mapping)

For instance, if the panel is vertical, the icons would be stretched in the vertical axis, while keeping the horizontal length the same. And the other way around for horizontal panels.

**Comment by kupiqu** [comment]
I think this is actually doable. Please see shear in X and Y direction in the following link:

[http://stackoverflow.com/questions/25919378/qt-transform-matrix#25925466](http://stackoverflow.com/questions/25919378/qt-transform-matrix#25925466)

In this case the matrix would just be 2D, plus scaling (3D; it would need to be scaled down to not exceed the length of the icon in any direction).

**Comment by kupiqu** [comment]
This all can be done simply in a 2D matrix with

Shear in X direction: 1/(1+A)*[1 A; 0 1]
Shear in Y direction: 1/(1+B)*[1 0; B 1]

In 3D, I guess it would be: [1 A 0; 0 1 0; 0 0 1/(1+A)] and [1 0 0; B 1 0; 0 0 1/(1+B)]

**Comment by kupiqu** [comment]
Btw, what I'm proposing should only be applied to icons in the task bar

**Comment by audoban** [comment]
Wow, I do not know what to say. I think it may be more or less difficult, but it is not out of our capabilities.

@psifidotos What do you think of this crazy feature

**Comment by psifidotos** [comment]
> Wow, I do not know what to say. I think it may be more or less difficult, but it is not out of our capabilities.

the only way I can think of for this to be implemented in our side is that when a window in dock's screen set itself to "above all" then the dock must re-enable its "above all" again by disabling/reenabling it. If I have unnderstood it correctly on top of above all windows is the last one that have set itself above all. 

my opinion is that it depends on the complexity it adds... I think this is upstream but you can give it a shot to see how it's going...

**Comment by psifidotos** [comment]
@audoban the above behavior should also happen when the active window changes... The dock must still the focus and become active...

I am starting to believe this is possible only in window manager level

**Comment by psifidotos** [comment]
@audoban not even time to think it... :) it will definitely add complexity... 
I am more keen to support fundamental things the next period...

- no crashes
- robust behavior
- multi screen 
- touching wayland

Currently I find these more important.. I dont say no but personally I wouldnt touch this for this period...

**Comment by kupiqu** [comment]
I agree with last comment very much. I was not really expecting this to be implemented very soon, instead sth to be discussed (i.e. whether to consider it or not) for the development of a future release.

Trying to follow the discussion a bit further (you don't have to reply soon, if busy on other things):

- I didn't get why windows need to be "above all" or steal any focus, do I miss sth here? I just want to transform how icons in the task bar look like so they occupy less space (but only when there are many of them that they don't fit the size of the latte panel). Perhaps it's how the task bar is implemented in latte... (?)

- I could give it a try. In different stages:

1. First just applying the transformation to see how it looks like.
2. If it looks good, then implement when the transformation applies (instead of scaling factor when no room is available for new icons in the task bar)
3. Reverse the transformation on hovering. First just for the icon that is on hoering. Second, partially for the icons on its vicinity.

- Btw, would you consider supporting plugins in latte? Not sure it's easy thing to add, but that would help for:

1. Third people to contribute
2. Keep the core source code clean and well mantained
3. Alike for end users, only users interested in specific plugins would add those
4. If a plugin (once polished) becomes mainstream, I guess, you could add it to the core source code

In terms of cons, you would need to create the infrastructure to make this possible, which may be hard thing to do.

**Comment by psifidotos** [comment]
> I didn't get why windows need to be "above all" or steal any focus, do I miss sth here? I just want to transform how icons in the task bar look like so they occupy less space (but only when there are many of them that they don't fit the size of the latte panel). Perhaps it's how the task bar is implemented in latte... (?)

sorry for this... these were comments for #198 and this is why I deleted them from here...

> Btw, would you consider supporting plugins in latte? Not sure it's easy thing to add, but that would help for:

they are called plasmoids :)... of course we are totally open to developers that want to participate and we can guide them through the code...

**Comment by kupiqu** [comment]
> they are called plasmoids :)...

I actually meant within latte itself, the best examples I can think of are the ones I referred here, alternative effects to scaling or zoom. It might be others...

But it may make no sense, if there are no many things to really tweak

**Comment by psifidotos** [comment]
too old... and no interest...

**Comment by kupiqu** [comment]
+1

Yes. Sorry, I didn't 'find' the time to work on this. I guess also because I never have problems of space in the taskbar, so my task icons (for the size I configured) don't ever get scaled down or get out of place.
