### ISSUE TITLE
Can't compile on Plasma 5.9.2

### ISSUE THREAD

**Issue by ccpak** [psifidotos/Latte-Dock#201]
Dependencies mentioned in INSTALLATION.md have been installed. 
On compilation, the following error is generated.

CMake Warning at /usr/local/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5Wayland"
  (requested version 5.26.0) with any of the following names:

    KF5WaylandConfig.cmake
    kf5wayland-config.cmake

  Add the installation prefix of "KF5Wayland" to CMAKE_PREFIX_PATH or set
  "KF5Wayland_DIR" to a directory containing one of the above files.  If
  "KF5Wayland" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)

-- Could NOT find KF5Wayland: found neither KF5WaylandConfig.cmake nor kf5wayland-config.cmake 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find KF5 (missing: Wayland) (found suitable version "5.31.0",
  minimum required is "5.26.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:20 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/user1/Latte-Dock/build/CMakeFiles/CMakeOutput.log".

**Comment by psifidotos** [comment]
kwayland-devel

is it installed?

**Comment by kupiqu** [comment]
In KDE neon, it would be libkf5wayland-dev
