### ISSUE TITLE
F.A.Q.s appearance...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#202]
I think it would be much better to make the questions in F.A.Q. bold and italic...

anyone interested?

**Comment by psifidotos** [comment]
or better... after testing it... a header 4

`#### _Q: How Latte Dock (auto)starts and why a widget is provided?_`

#### _Q: How Latte Dock (auto)starts and why a widget is provided?_

**Comment by Petross404** [comment]
Is anyone up to it?

**Comment by psifidotos** [comment]
I think the answers are fine.... will you go for it?

**Comment by Petross404** [comment]
Well I did formate the faq. Is there anything else or something to do in another way?

**Comment by JenaPlinsky** [comment]
@Petross404 Well done !!

**Comment by psifidotos** [comment]
@Petross404 thank u!!! I am thinking the next days to add small tasks concerning wiki staff, community organize etc....

**Comment by Petross404** [comment]
I am starting to think if the wiki creates confusion with some (mine) questions. I mean some configs options or requests for higher customisability (eg distance from the edge) should belong to a dedicated page or something that could be way more extensive. This way not only clear answers will be given, but it will motivate to actually make ever more feature-full and customisable. 

Feel free to remove whatever you think not worthing to be asked. After all a user can always open an issue, but I worry this way might be inefficient.

**Comment by psifidotos** [comment]
@JenaPlinsky @Petross404 fantastic work with the F.A.Q. !!!!  Thank u!!!!

 very good questions and answers!!! I will try to answer some missing ones....

**Comment by Petross404** [comment]
@psifidotos What about a final clean up of Wiki? Some questions can't be answered, so...

**Comment by JenaPlinsky** [comment]
Ciao @Petross404 
I tried to respond briefly to these two questions ... I hope to have us taken ... you know, my English is a bit insecure :)

- Q: What happens if I drag files on launchers ? ...and about the folder-view, what happens ?
- Q: Is Latte a semantic dock ? what does it mean ?

**Comment by JenaPlinsky** [comment]
I'd like see the wiki pages's link in the about dialog ... here on GitHub goes unnoticed I believe
