### ISSUE TITLE
Hidding PlasmaTube applet

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#204]
The first click open the applet and with a second click should be hiding, right?
in fact generally it works this way !!! ...except, however, for PlasmaTube applets
I suppose, that this depends from the applet ... Do you suggest to ask directly to the developer?
![spectacle bc9781](https://cloud.githubusercontent.com/assets/24593950/23334326/8d4d6724-fb9c-11e6-9f7e-f658b2206020.png)

**Comment by psifidotos** [comment]
With plasma does it work ok?

**Comment by JenaPlinsky** [comment]
@psifidotos 
with plasma works fine
it happens only on Latte

**Comment by psifidotos** [comment]
where can I see its code?

**Comment by JenaPlinsky** [comment]
https://store.kde.org/p/1151366/

**Comment by psifidotos** [comment]
By just reading the code i cant locate how showing/hiding by click is happening... can you point the developer to this thread in order to discuss it?

**Comment by JenaPlinsky** [comment]
Ok ... I just contacted Zanturik and I invited him to join us to the discussion

**Comment by psifidotos** [comment]
thank you !!! :)

**Comment by psifidotos** [comment]
I dont see any interest from the developer so I am closing this...

**Comment by psifidotos** [comment]
@JenaPlinksy have you tried to lock this applet to not animate? The problem remains in such case?

**Comment by psifidotos** [comment]
this was inside Latte because of inaccurate clicking signaling between Latte and applets...

**Comment by JenaPlinsky** [comment]
wonderful !!!!

**Comment by JenaPlinsky** [comment]
wonderful !!!!

**Comment by JenaPlinsky** [comment]
the developer responded: ...
![spectacle zu9599](https://cloud.githubusercontent.com/assets/24593950/24070504/1603da94-0bbf-11e7-80c2-2ca214ac7bd1.png)

**Comment by psifidotos** [comment]
nice... :)

and he is right... problem has been fixed... ;)

**Comment by JenaPlinsky** [comment]
Yesssss :)
