### ISSUE TITLE
feature backup and restore

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#205]
Is it possible, that in somehow, something goes to corrupt the configuration files ?
Do you believe that is it wise and appropriate to implement a system for making backups and restore of the "rc" files ?

**Comment by Petross404** [comment]
An idea might be that `latte-dock` could take a parameter which then `cp`ied the configuration files under the same name with .BAK in the end. Let's say something like : `latte-dock -b`

I was thinking of how easy it is with a bash script, but if Latte Dock is/or ever wants to be crossplatfrom to accompany Plasma under Windows, stuff like these should be very tricky to overcome.

**Comment by audoban** [comment]
> I was thinking of how easy it is with a bash script, but if Latte Dock is/or ever wants to be crossplatfrom to accompany Plasma under Windows, stuff like these should be very tricky to overcome.

Our main goal now is to support the multiscreen and Wayland. We have never considered Windows.

However I like the idea of exporting and importing the configuration from Latte.

**Comment by psifidotos** [comment]
> However I like the idea of exporting and importing the configuration from Latte.

yes... I agree also...

**Comment by psifidotos** [comment]
@audoban just to mention here, I dont know how you are thinking to approach this, just to know, on the corona destructor I use a clean up function that removes any garbage records from lattedock-appletsrc... Such garbage can occur by crashes or not correct deletions of applets, I dont know all the cases these occur but they do... Closing latte by using that function it cleans up that file

**Comment by audoban** [comment]
**Notice:** this feature is implemented right now, I'm trying to get time this week to finish it.

@psifidotos I'll keep that in mind.

**Comment by psifidotos** [comment]
@audoban I think this is merged... so we can close it...
