### ISSUE TITLE
Graphics effects on battery low level trigger event

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#206]
Do you believe that is it wise and appropriate to implement a features to decrease the waste of resources by disabling graphics effects on battery low level trigger event ?

**Comment by audoban** [comment]
Personally I think it would not make any difference on the battery, but you can disable the effects of KWin.

**Comment by audoban** [comment]
However if you justify that there is difference in the performance of the battery when latte have effects enabled, we can add a option but this feature.

**Comment by audoban** [comment]
You have intel? You can calculate the consume of energy with `powertop`, with graphics enabled and graphics disabled.

And tell me if there is a difference between the two states.

**Comment by JenaPlinsky** [comment]
my context menu not working ( due messed dependences )
how can I disable graphics effects from file:///home/Ivan/.config/lattedock-appletsrc or what you mean is the global 3d acceleration ?
[latte whith graphics](https://youtu.be/qc7W0Pa80pM)

**Comment by audoban** [comment]
You can try three types of tests.
Calculate the duration and the consume on WATS of battery, using powertop:

1. KWin without composition.
 `sudo powertop -t 1200  --html nocomposition.htm`

2. Latte without effects(shadows and zoom effect)
 `sudo powertop -t 1200  --html no_effects.htm`

3. Latte with effects(shadows and zoom effect)
 `sudo powertop -t 1200  --html effects.htm`

### NOTES:
- Please use only the battery for the test. 
- Each test lasts **20 min**.

share the reports to my telegram `https://t.me/audoban`, Because these reports generate a lot of information that could be sensitive.

**Comment by JenaPlinsky** [comment]
I'm sorry but I can't, my laptop has no longer the battery, it is blown and as a precaution I have to eliminated it

**Comment by Petross404** [comment]
Mine doesn't have too. Is there anyone else?

**Comment by audoban** [comment]
> I'm sorry but I can't, my laptop has no longer the battery, it is blown and as a precaution I have to eliminated it
Furthermore, I do not know how to copy all the line from the konsole terminal, do not let me do it, maybe I should use another terminal ....anyone can do this test?

The test generate a report of 20 min of consume of resources.
Anyone can run the test, but we need to test to justify the feature..

**Comment by Petross404** [comment]
So literaly anyone with a laptop and Latte can test can test? 

Will see this issue later this day.

**Comment by JenaPlinsky** [comment]
@audoban  metrics testing what they say about this #223 ?
how can I execute the test?

**Comment by audoban** [comment]
>@audoban metrics testing what they say about this #223 ?
yes.

> So literaly anyone with a laptop and Latte can test can test?
yes anyone can run the test.

> how can I execute the test?

Calculate the duration and the consume on WATS of battery, using powertop:

  1. Disable the composition from KWin and run:
   `sudo powertop -t 1200 --html nocomposition.htm` # generate a file: nocomposition.htm

  2.  Latte without effects, disable the shadows and zoom effect and run:
    `sudo powertop -t 1200 --html no_effects.htm` # generate the file: no_effects.htm

  3. Latte with effects use shadows and zoom effect > 50% and run:
    `sudo powertop -t 1200 --html effects.htm` # generate the file: effects.htm

Run each command one by one during 20 minutes, then it will generate a file HTML with much a lot information, if you consider that the file has sensitive information. Share the reports to my telegram https://t.me/audoban.

Please use only the battery for the test, after you finish a command you can load the battery a bit and continue with the next test.

**Comment by JenaPlinsky** [comment]
unfortunately I can not. I have not the battery
I can only, from the power supply

**Comment by audoban** [comment]
Anyone can run the test

**Comment by psifidotos** [comment]
no solid metrics etc.. I am closing this for now...
