### ISSUE TITLE
[Crash] - Quit button from the configuration when 2 or more docks are running

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#208]
this happens either by using the Quit button from configuration window, either by using
Ctrl+C

**Comment by psifidotos** [comment]
@audoban is this happening also to your system?

**Comment by psifidotos** [comment]
one time that I had only one dock running it didnt happened but now it happens all the time

**Comment by psifidotos** [comment]
```
[debug 11:58:13.785785] - dock view deleting...
[debug 11:58:13.785785] - dock view connections deleted...
[debug 11:58:13.831831] - Latte::QuickWindowSystem destructed
Σφάλμα κατάτμησης (segmentation fault) (core dumped)
```

**Comment by Petross404** [comment]
@psifidotos on Arch Linux, with git master, I can't confirm the problem. Is there a possibility the problem to be, say, configuration specific?

I am running Plasma 5.9.2 with Qt5.8

**Comment by psifidotos** [comment]
@Petross404 try to use two docks and afterwards to hit the Quit button from the configuration window

**Comment by psifidotos** [comment]
found it....

@audoban this code creates a mess in event of dockview, I am disabling it...

```
    if (e->type() == QEvent::Leave) {
        engine()->collectGarbage();
        engine()->clearComponentCache();
        engine()->trimComponentCache();
    }
```

the engine() is shared between dockviews because of plasma frameworks architecture... By hitting Quit Button when two or more docks are running the above code creates a crash...
