### ISSUE TITLE
Dragging a task or launcher from latte plasmod is not blocking hiding

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#21]
When the user drags a launcher or task to change its position the dock loses focus and hides if such a state was needed otherwise...

In NowDock this was working with a blockingMechanism, the Latte plasmoid has already a signal in order to request blocking and unblocking the dock...

@audoban , how would like to handle this?

**Comment by audoban** [comment]
1. I can expose a function forceShow(bool) or property for avoids this.
2. the containment has control isHidden variable. Maybe add a condition for this.

**Comment by psifidotos** [comment]
I propose (1), a property that helps in this.... e.g. blockHiding

**Comment by audoban** [comment]
> I propose (1), a property that helps in this.... e.g. blockHiding

You want VisibilityManager remember the state of isHidden when blockHiding is set again to false?

**Comment by psifidotos** [comment]
You want VisibilityManager remember the state of isHidden when blockHiding
is set again to false?

I dont think  isHidden can be anything else than true when blockHiding is
activated. The visibilitymanager shouldnt send any mustBeHide signal when
blockHiding has been activated... After blockHiding has been released then
the hideTimer should be activated to check in the end if the dock must hide

**Comment by audoban** [comment]
ok if, blockingHiding is set again to false, then timerHiide should start only if necessary.

**Comment by psifidotos** [comment]
> ok if, blockHiding is set again to false, then timerHide should start only if necessary.

> also, anything intent for set isHidden to true, while blockHiding is true, would be ignored.

sounds ok to me...

**Comment by psifidotos** [comment]
> also, anything intent for set isHidden to true, while blockHiding is true, would be ignored.

I think that it would be good if in such a case occurs, a text message is appearing to inform us just like when kwindowinfo informs when a correct flag wasnt set for specific propertied

**Comment by audoban** [comment]
I'll keep it in mind.

**Comment by psifidotos** [comment]
fixed in master

**Comment by audoban** [comment]
Now visibility manager has control about this.
