### ISSUE TITLE
Regression on snap feature

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#210]
The snap feature is not working anymore after commit b66f12d32a143fcc7614e9d2a09123d714a104aa

**Comment by psifidotos** [comment]
this is the same with #209 the ByBassWindowManagerHint flag must not be used with AlwaysVisible state...

**Comment by kupiqu** [comment]
I see, sorry, didn't realized of issue 209

**Comment by psifidotos** [comment]
Dont worry!!! You did something better.... :) you found the reason of this

**Comment by audoban** [comment]
This flag should be disabled on AlwaysVisibible?

**Comment by psifidotos** [comment]
yes
