### ISSUE TITLE
Reconsider shortcuts for New Instance / Close Window

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#213]
Instead of right clicking to find Start New Instance, left click with a keyword button (eg shift) could Start New Instance. 

**Instead** the simple left click when at least 2 instances are already running, should show all the instances so that I can choose which I want to work with.

Eg. If left-click Kate, I could shift left click again the launcher to start a new instance. When I left click now, both instances should be appeared in order to choose which I want kwin to activate.

What do you think? If you find this idea usefull ( I certainly find it ) we could propose ideas of what effects could be used and how the instances should appear (eg they can be shown on a square, or on a dock, or on something that could look like a parabolae etc)

Some ideas: [square](http://4.bp.blogspot.com/-iP-JZ2_i2Zg/T413DdpfniI/AAAAAAAAIhs/2vZa5zv_DV4/s1600/cairo-dock-unity2d.png)

[another idea](https://i.ytimg.com/vi/ZPoytbm1kUA/maxresdefault.jpg)

[third idea](https://i.ytimg.com/vi/5NZpB5kgL98/maxresdefault.jpg)

Now imagine multiple instances of dolphin are started, and left clicking on the launcher pops up something like these to choose the one you want.

**Comment by psifidotos** [comment]
You can use middle click for a new instance....

Personally the other effects i find them too fancy for my style

**Comment by Petross404** [comment]
Middle click, closes the instance, like what is happening with browsers.

I don't like either the last 2 effects. But I find the first simple enough.

**Comment by Petross404** [comment]
Yes, ok with that. Which shortcut and mouse click should close the instances then?

**Comment by psifidotos** [comment]
none yet... only through right click menu

**Comment by Petross404** [comment]
See that is one of my points here. Would you consider usefull such a small facilitation?

Secondly: In my currest desktop setup, I can view my windows with middle clicking on an empty space. 
[here](https://postimg.org/image/oflg69y6f/)

**But** when someone hasn't configured Plasma like this **and** uses a dock, he/she expects the dock to act somewhat like a _task manager_ too. So like plasma's task manager grouped the tasks of the same program and when someone clicked of hovered above could choose a task, I think the same can do Latte Dock.

**Comment by psifidotos** [comment]
I cant understand what is missing from current implementation concerning the task accessibility. 
Latte with single click in a grouped task presents all the windows through the present windows effect,
It also provides window previews on hovering if the user chooses that from the configuration window

**Comment by Petross404** [comment]
I suppose you are right. Didn't enable the preview, because I though that somehow without showing the contents of the window, an icon would appear to click and enable the window.

My bad, I am sorry. After all I found that if I just hover, I can indeen see my instances without any preview. Assumption is the mother of all fuckups, they say...

Thank you very much for your patience.

**Comment by psifidotos** [comment]
no worries....

**Comment by psifidotos** [comment]
Can you please open a new thread concerning the shortcuts? that way the discussion will be more focused
