### ISSUE TITLE
Multi monitor setup - No dock after misconfiguring a single dock to explicit screen

### ISSUE THREAD

**Issue by sebbuku** [psifidotos/Latte-Dock#214]
Hi guys,

after the last installation I noticed the option to choose on which monitor should the dock be. Everything was working great until I disconnected the external monitor and noticed there is no way to bring it back on my notebook's display. 

I tried killing it and relaunching, restart, uninstall and new installation to no avail. It doesn't even show if I connect another external monitor. 

Thanks for the great work nonetheless.

**Comment by Petross404** [comment]
Can you upload to a pastebin `~/.config/lattedock-appletsrc` and give us the link?

**Comment by sebbuku** [comment]
Sure. Here you go:
http://pastebin.com/VsazqpUC

**Comment by psifidotos** [comment]
Easy...

- Close latte
- In the file you sent change last screen to be 10 instead of 11
- Reopen latte

Why dont you just reconnect the specific monitor?

**Comment by psifidotos** [comment]
If you open lattedockrc you will see the ids for your monitors, latte is expecting to see activated the one with id 11

**Comment by psifidotos** [comment]
Also you can you use the setting "on primary" this makes the dock to be always on the primary screen, so disconnecting the monitor properly (not by unplugging the screen but through shotcuts or plasma screen management) automatically maked the dock to return at its first place

**Comment by psifidotos** [comment]
Also instead of changing the last screen id from 11 to 10 you can set in the same file the value, onPrimary=true

**Comment by psifidotos** [comment]
@sebbuku with Latte you can have multiple docks and you can organize them at your monitors... Latte will load/unload them properly based on screens attached/removed...

But i can consider this a bug... Latte shouldnt have left you with only one screen and not dock in it...

I am thinking what Latte should do in such case, i dont believe returning the dock to laptop screen is the best choice, but i think that latte should create a new default dock in such case, what do you think?

I will reopen this because i will need feedback from more people about what Latte should do in such case

**Comment by sebbuku** [comment]
Normally if I have some widgets or windows on another screen and I simply disconnect the external monitors (I don't normally do this because I have my own bash scripts to rearrange my desktop with xrandr depending on the configuration: at home, at work, on the road) it suffices to restart plasmashell with "killall plasmashell; plasmashell & disown" and plasma does a great job at "reconfiguring" itself.

**Comment by sebbuku** [comment]
As long as I didn't have any dock I just added an default kde panel to have some functionality at least, so maybe adding a default dock wouldn't be so bad.

**Comment by psifidotos** [comment]
I could also by pass user setting and if such case occurs to force the dock to become primary, in that way when latte restarts dock will be shown correctly...

My personal experience is that Latte doesnt crash and is very robust on screen changes, in the other hand plasma underneath it shows things I dont understand, black screens etc...

**Comment by sebbuku** [comment]
Oh don't get me started with plasma. I just received a new laptop with a 4k resolution, but I also have two full hd monitors at my workplace. The last day has been a lot of fun with: incompatible kernels, nvidia proprietary drivers, dpi settings, scaling, wrong monitor placement and so on.

I am just used if you disconnect a monitor and restart the plasma shell everything tries to fit on the remaining screen. Latte used to do that as long as it was only a widget but now it is it's own application so it's not affected by plasma restarts. 

The worse in not having my latte dock was not the task manager functionality, because I can still start applications with krunner and switch with alt+tab, I couldn't connect to my wifi because I don't have any panels besides latte and my system tray is in it. My wifi connected only when I added a default panel.

Sure if latte could see that only one screen remains to position itself when it starts on that one would be a solution, but in my experience not very reliable because sometimes the external monitors would still be reported even if disconnected (especially when using the open drivers for amd graphics cards).

I personally like how krunner or the task switcher work: they always start on the screen that currently has the "focus".

**Comment by psifidotos** [comment]
The on primary screen feature does not work for you?

**Comment by psifidotos** [comment]
Latte is aware of screen changes an long as they are made from systemsettings or laptop shortcuts...

**Comment by psifidotos** [comment]
one more thing, unplugging a monitor only by removing its cable it may has a delay before the screen is really removed in order to give the user the time to reconnect in case that was by mistake

**Comment by sebbuku** [comment]
I will extensively test the multi monitor functionality in the following days and provide additional feedback. 
How about opening a dock on the screen you currently have the focus? It's a behavior that you would intuitively expect and that way you can have more docks on the screens you want.

**Comment by psifidotos** [comment]
that way the dock will change position whenever the focus is altered...

How about a new setting to return to primary if the screen you have associated is not active?

**Comment by sebbuku** [comment]
No, the position should not change on a different focus. It should only respect the focus when you launch it the first time.
That setting would be great by the way.

**Comment by sebbuku** [comment]
But I feel that my opinion on this is very subjective. Maybe the other ones would like to chime in?

**Comment by psifidotos** [comment]
I dont like the idea of only in startup... so the on focused desktop I dont think it clarrifies it...

I believe the goal is the following:
"Latte should always provide a dock with tasks in it"
The question is should the user clarify this dock? e.g. Global Dock,
or Latte creates a default one in such cases?

**Comment by psifidotos** [comment]
I have also one more idea... Latte should understand when a dock has tasks applet in it... In such case Latte should always provide a dock that has tasks applet in it (it will prevent deleting automatic the last dock containing tasks in it).

After that Latte will be able to move that dock in specific cases even though the user has set to be only on specific screens... For example Latte will move that dock to primary screen when the screen for which is associated has been closed...

**Comment by psifidotos** [comment]
@sebbuku you could try branch **multi2** it has many fixes concerning this issue... it will never leave you without a dock with tasks in it... the older dock with tasks has also the bigger priority in many circumstances...

**Comment by sebbuku** [comment]
Ok will do and provide feedback

**Comment by psifidotos** [comment]
@sebbuku ok... latest commits in **multi2** improve a lot the situation, I will wait for your feedback...

**Comment by sebbuku** [comment]
So I just tested the multi2 branch.
I tried everything that somebody could do:
- disabling monitors from display widget
- pulling monitor cable
- going to suspend and waking without external monitor
- pulling cable from docking station without disabling external monitors.
I tried this with the dock set on the primary display and a second time with the dock set to a specific external monitor. 
Every time the dock managed to re position itself to an active monitor. I like it very much how it handles itself! As an bonus it looks like the dock is reacting to multi-monitor changes better than the plasma desktop!
Great job guys!

**Comment by psifidotos** [comment]
Nice... ;) I just have to add comments in the code explaining the various parts achieving this... :-)

To add in the feedback, the new code is even able to distinguish a dock set on primary and one set on explicit, so the user can have a second dock for an explicit and other on primary... the code will always try to provide the best experience for the user concerning with docks to activate/deactivate and where to place them...

After commenting the code I will merge this code into master...

**Comment by sebbuku** [comment]
That sounds great. If we still are by the multi-monitor subject I have another idea. 

The applet size is set in absolute values. While a size of 96px looks great on a 4k monitor it's much too big on a full hd monitor. Do you think it would be possible to scale the applets according to the vertical size of the monitor as a second setting. For example 4,5% from vertical size (rounded to the next multiple of 8) looks great on both resolutions. 

Just an idea seeing that the dock is becoming so intelligent. ;)

**Comment by psifidotos** [comment]
we can investigate the case in the future but hidpi resolutions cooperating smoothly with native ones is one of the topics of the current age in which even qt is trying to handle natively...

**Comment by sebbuku** [comment]
![image](https://cloud.githubusercontent.com/assets/7261864/23509851/80158bfe-ff57-11e6-9196-4149a4a34ecb.png)

Something like this, if you push the dock it would calculate the new applet size according to the proportional value, i.e. by 4k it would be 64px.

Just a thought.

**Comment by psifidotos** [comment]
I dont object but we must play with it and test it..
 Open a different ticket specific for this in order to have a more structured conversation... this ticket will be closed after i merge in master

**Comment by sebbuku** [comment]
Ok will do! Thanks.
