### ISSUE TITLE
Mouse shortcuts that should be appended for "New Instance" and "Close".

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#215]
#213 

Here let's consider which mouse clicks should be a shortcut for each of those activities.

**Comment by Petross404** [comment]
My opinion is middle click closes a window, just like a browser does or how a tab in Dolphin is closed.

On the other hand left click with some keyboard key (eg Shift) can open one more instance if one or more are already running.

**Comment by Petross404** [comment]
Also for users with extra buttons or their mice, an option to choose shortcut for one of these buttons from latte's configuration, could be provided in the future.

**Comment by audoban** [comment]
Sounds very good, i like it. @psifidotos do you want implement this feature?

**Comment by psifidotos** [comment]
> Sounds very good, i like it. @psifidotos do you want implement this feature?

@audoban which one?

1. Modifiers and mouse clicks? 
2. clicks from extra buttons?

concerning (2), I think it gets out of Latte focus, so I dont fancy it...
concerning (1), how open to configuration this will be and are we talking for version 0.6 or latter on?

2.1 I dont want a time limit for 0.6 for this... if it gets into ok but 0.6 cant be delayed for this...
2.2 If we want a configuration of a type **(Modifier + Click action = Action)**, so the user can config both modifier, mouse click and the action this will be one action or the user can set multiple actions?
for example, different for **Shift+left mouse click** and different for **Shift+middle mouse click**? 

concerning 2.2,
I dont fancy multiple actions, this would definitely need a fifth tab in configuration window but it would be a lot cleaner of course than adding even just one extra action for setting  **(Modifier + Click action = Action)**

this needs a lot thought and discussion in my opinion how to not add clutter in the configuration window, even now with the tweaks page I am not that happy with the situation in there....

**Comment by psifidotos** [comment]
sorry, I had user wrong numbering previously...

@Petross404 we would appreciate if you can comment around **(1.2)**

**Comment by audoban** [comment]
@psifidotos I dont want more tabs of configuration.
I want to open another instance with eg: shift + leftMouse click, however but close a instance could be more complex if the app is grouped, in this case we need to discuss the behavior.

**Comment by Petross404** [comment]
About 1.2 all I have to say is that the basic actions a user wants is to (re)open and close the apps. Opening happens (apparently) with left click. Closing could happen with middle click (like in the browsers - that is just my opinion). Reopening (aka New Instance) on the other hand could happen again with left click + some other keyboard key. 

Somehow Latte must distinguish if the user wishes to activate the running instance or start another one. That is why I think a modifier is needed. 

Under consideration must be taken the case in which no instance of -eg- dolphin is running but the user is used Modifier+left click

**Comment by Petross404** [comment]
Used* not is used. Typo

**Comment by Petross404** [comment]
@audoban let's not make things complicated.If an app is grouped, one can hover the previews and middle click (or click the close , red button) to close a specific instance. 

What do you think?

**Comment by psifidotos** [comment]
> I dont want more tabs of configuration.

me neither, in that case we are discussing **only** a secondary action based on a modifier key

>if the app is grouped, in this case we need to discuss the behavior.

what do you have in mind? @Petross404 suggesting to show the previews window and the user can choose from there...

> Opening happens (apparently) with left click. Closing could happen with middle click (like in the browsers - that is just my opinion). 

this is of course an opinion and **not** what plasma taskmanager provides as default... in each case for default I fond only:

1. middle click -> New Instance
2. modifier + click -> None Action

of course the user could alter both... In such case that the user base increases much and prefers others defaults I wouldnt object

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/24015781/1e76ac98-0a92-11e7-97d4-a7ec310488fc.png)

**Comment by Petross404** [comment]
Very nice. Clean and tidy menu while giving functionality and customazibility. Well done 👍
