### ISSUE TITLE
Setting "Animations" to None, disables all the effects, but clicking a launcher momentarily disappears the ico

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#216]
In F.A.Q. it is written that setting Animations to None, disables all the effects, but clicking a launcher momentarily disappears the ico. Can I disable this feature somehow?

**Comment by psifidotos** [comment]
default behavior of libtaskmanager... also reported upstream... i have tried to find a workaround but didnt find any...

**Comment by Petross404** [comment]
Good to know :)

**Comment by Petross404** [comment]
> default behavior of libtaskmanager... also reported upstream... i have tried to find a workaround but didnt find any...

Can I write this to the F.A.Q. until a solution is found?

**Comment by psifidotos** [comment]
yes

**Comment by Petross404** [comment]
Done. It is up to you if this issue is considered closed, or we should wait until upstream find a fix. :)

All the best, Petros

**Comment by psifidotos** [comment]
Petro I had an idea and tried it... I think it is fixed... can you check the **mutli2** branch?

**Comment by JenaPlinsky** [comment]
Nothing is impossible !!! Believe it ;)

**Comment by Petross404** [comment]
> can you check the mutli2 branch?

Sure enough.

**Comment by Petross404** [comment]
Uh, it seems I have a certain difficulty with git's operation. Could you help me with changing branch?

So far I have done:
`git pull
git branch multi2
git checkout multi2
git pull`

Is this correct? Of course I was on master branch. Either I am right or not, maybe such a technical aspect should be present in FAQ, so many novice users can test etc.

**Comment by Petross404** [comment]
I see the same behavior. I think I compiled the right branch (hence the correct code). I installed Latte in a safe directory and run _this specific_ executable. 

`git status`
On branch multi2
nothing to commit, working tree clean

Is the problem from my side?

**Comment by Petross404** [comment]
Yes, it is fixed! Congratulations!

**Comment by Petross404** [comment]
For completness shake I will report my mistake. I compiled the correct branch by hand and installed it under a directory of my user, so that it would not install anything in the system without the Package Manager.

So I managed to have installed both Latte under /usr and under ~/LinuxApps. When I executed the executable from the second directory, the dynamic linker chose to pick the libraries under /usr (which is fair enough if you think of it) so it was not the fixed libtaskmanager that was used!

That's why the new (fixed) executable, failed to act the way it should. On loading it linked with the wrong libs. 

Once again, thank you and congratulations. Now are you going to do with upstream? Is this fix ok, or a more stable solution is still needed?

**Comment by psifidotos** [comment]
the fix is inside Latte, i tried to emulate completely the way plasma taskmanager is behaving when Latte animations are set to None...

The fix will be merged in master in few days wheb branch multi2 that contains also many multi screen improvements has been test a bit by users

**Comment by Petross404** [comment]
Still for some reason it didn't work. I should have run `ldd` to be sure.

Anyway, it is fixed now. :)
