### ISSUE TITLE
Feature request: adaptive applet size scaling based on screen height

### ISSUE THREAD

**Issue by sebbuku** [psifidotos/Latte-Dock#217]
Because of sometimes different resolutions of multi-monitor setups a single absolute size for the applets and implicitly the dock doesn't work on multiple displays. 

I propose an additional optional setting that would take in account the vertical size of the display the dock is currently on. 

For example instead of setting a size of 32px you could set the applet size to 3% of the monitor vertical size. 

The calculated applet size would look something like this:
int(verticalSize * setting / 100 / 8) * 8

Python test:
```
>>> verticalSize = 1080
>>> setting = 3
>>> int(verticalSize * setting / 100 / 8) * 8
32
>>> verticalSize = 2160
>>> int(verticalSize * setting / 100 / 8) * 8
64
>>> verticalSize = 1440
>>> int(verticalSize * setting / 100 / 8) * 8
40
>>> verticalSize = 1080
>>> setting = 3.5
>>> int(verticalSize * setting / 100 / 8) * 8
32
>>> setting = 4
>>> int(verticalSize * setting / 100 / 8) * 8
40
```

What do you think?

**Comment by psifidotos** [comment]
I dont know why the above calculation works, we will need also to not go always to lower icon size but a round function somewher...

either way I will try to try something for this during the day even though I dont want to break visually the Appearance page...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/23757120/9b133ab8-04ee-11e7-92b9-e73886bdf3ac.png)

**Comment by sebbuku** [comment]
I love it! 
Thank you, thank you!

**Comment by psifidotos** [comment]
I hope it works ok for you...
