### ISSUE TITLE
Regression on memory consumption

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#218]
Visibility mode **AutoHide** 
until a few days ago, the Latte process memory consumption was about 135MB
....then yesterday was after upgrading it was reduced by approximately 30% and thus **95MB**
but now after a new upgrading from the master branch it came back as two days ago

**Comment by JenaPlinsky** [comment]
![spectacle q10874](https://cloud.githubusercontent.com/assets/24593950/23519932/0eb95e1e-ff79-11e6-97c0-a736c7a153ca.png)

**Comment by psifidotos** [comment]
I have disabled some code concerning cache free up because it was creating crashes when closing Latte. If the crashes dont be fixed this code wont be accepted....

more specific the code that was creating the crashes was: 

```
bool DockView::event(QEvent *e)
{
    emit eventTriggered(e);

    //Important! this code creates a crash when there are two docks
    //running and the user clicks the Quit button, it is also
    //suspicious for some rare cases when removing a dock and the
    //dock is deleted after the 1min time limit of plasma
    /*if (e->type() == QEvent::Leave) {
        engine()->collectGarbage();
        engine()->clearComponentCache();
        engine()->trimComponentCache();
    }*/

    return ContainmentView::event(e);
}
```

**Comment by JenaPlinsky** [comment]
Ahahahah improvement was evident. Now you have one more confirmation. ;)
The code must be be robust before, then everything else

**Comment by psifidotos** [comment]
@JenaPlinsky I managed to restore two of three cleaning functions without crashes... I believe it will improve the memory consumption significantly... The third I dont bellieve it should exist as a memory releaser...

**Comment by JenaPlinsky** [comment]
Unfortunately I dnot see improvements
- without cleaning functions **138MB**
- with two of three cleaning functions:
      -  at beginning it start (**115MB**)
      -  after a while of hovering and without clicking on applets (**149MB**)
      -  after a few minutes of inactivity, and always with the hidden dock (**137MB**)
      -  I also observed a crash but do not know if the cause of these are the introduced cleaning functions...
- with full cleaning functions: (if I remember correctly !!!)
      -  at beginning it start (**95MB**)
      -  after a while of hovering and without clicking on applets (**105MB**)
      -  after a few minutes of inactivity, and always with the hidden dock (**105MB**)

**Comment by JenaPlinsky** [comment]
During the installation I got this warning ... This might cause problems?
```
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found XCB_XCB: /usr/lib64/libxcb.so (found version "1.12") 
-- Found XCB_EVENT: /usr/lib64/libxcb-util.so (found version "0.4.0") 
-- Found XCB_RANDR: /usr/lib64/libxcb-randr.so (found version "1.12") 
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-randr.so (found version "1.12") found components:  XCB RANDR EVENT 
CMake Warning (dev) at /usr/lib64/cmake/Qt5/Qt5ModuleLocation.cmake:4 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '${_qt5_install_prefix}/Qt5@module@/Qt5@module@Config.cmake'

  the old evaluation rules produce:

    '/usr/lib64/cmake/Qt5/Qt5Config.cmake'

  but the new evaluation rules produce:

    '/usr/lib64/cmake/Qt5@module@/Qt5@module@Config.cmake'

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt5/Qt5Config.cmake:25 (include)
  CMakeLists.txt:33 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Disabling debug info
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Shared/Settings/Script/Latte-Dock/build
Scanning dependencies of target translations-plasmoid
[  0%] Built target translations-plasmoid
Scanning dependencies of target translations-containment
[  0%] Built target translations-containment
Scanning dependencies of target translations-app
[  0%] Built target translations-app
Scanning dependencies of target org.kde.latte.containment-plasmoids-metadata-json
[  3%] Generating org.kde.latte.containment-plasmoids-metadata.json
About to parse service type file "plasma-applet.desktop"
Found property definition "X-Plasma-API" with type "QString"
Found property definition "X-Plasma-RootPath" with type "QString"
```

**Comment by psifidotos** [comment]
I dont see anything related... I'll let @audoban review also this concerning memory usage...

I have one more ace in my pocket to try to reintroduce the third cleaning function without crashes but I am not that optimistic...

the third function does not clean garbage, it cleans the real qml component cache so this can have a drawback on smoothness in some cases... hunting memory usage must give better performance, not the opposite...

**Comment by JenaPlinsky** [comment]
@psifidotos @audoban 
Do you think that inhibit the shadows when Latte is hidden, it can help to free up memory?

**Comment by psifidotos** [comment]
I am not that fond on improving any more memory usage without metrics providing that it is latte's fault...

Latte can not improve qt, qml and plasma frameworks in that area...

**Comment by JenaPlinsky** [comment]
I do not know if I explained well or maybe I misunderstood me :), what I meant was referred to the shadows on the Latte's icons

**Comment by psifidotos** [comment]
shadows do not use any buffers, they are painted directly from the graphic card

**Comment by JenaPlinsky** [comment]
Ok thanks for the clarification I do not know how these things work

ehehehehe
everything else works really well .... so, I look at these tiny details

**Comment by psifidotos** [comment]
I suppose you just love the project and want to make it to work as best as possible...
I feel the same...
- It might be that these days the most important thing in my head is that Latte is already too good to hold it back, Latte is doing now things that many users always wanted from their panels for so much long...
- It would be a good thing to increase our community more and get more feedback also from them...
- a stable Latte version 0.6 will also open the doors for distributions to package it more officially...

**Comment by JenaPlinsky** [comment]
Fantastic !!!, Latte has now become of age

**Comment by Petross404** [comment]
> a stable Latte version 0.6 will also open the doors for distributions to package it more officially...
That's for sure. Besides, it's not just the version's number, but Latte is also much more mature and stable now.

You are rigth thinking that now is time to increase Latte's users and this version is capable of doing that. Multiscreen is fixed, crashes are not an issue (at least for me they never were) and a nice interaction with the dock takes place when using it.

Maybe in a future release, more configuration options should be provided, but for now everything is just fine.
