### ISSUE TITLE
QML module org.kde.latte "not installed" (fedora 25)

### ISSUE THREAD

**Issue by asfdms** [psifidotos/Latte-Dock#219]
After building and installing without errors, both the widget and the app show this message:

 Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:34:1: module "org.kde.latte" is not installed

Here is the log of the build; it should provide enough information about versions.

-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found KF5Plasma: /usr/lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.31.0") 
-- Found KF5PlasmaQuick: /usr/lib64/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.31.0") 
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.31.0") 
-- Found KF5Activities: /usr/lib64/cmake/KF5Activities/KF5ActivitiesConfig.cmake (found version "5.31.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Found KF5I18n: /usr/lib64/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.31.0") 
-- Found KF5XmlGui: /usr/lib64/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.31.0") 
-- Found KF5DBusAddons: /usr/lib64/cmake/KF5DBusAddons/KF5DBusAddonsConfig.cmake (found version "5.31.0") 
-- Found KF5IconThemes: /usr/lib64/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.31.0") 
-- Found KF5Wayland: /usr/lib64/cmake/KF5Wayland/KF5WaylandConfig.cmake (found version "5.31.0") 
-- Found KF5: success (found suitable version "5.31.0", minimum required is "5.26.0") found components:  Plasma PlasmaQuick WindowSystem Declarative Activities I18n CoreAddons XmlGui DBusAddons IconThemes Wayland 
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found XCB_XCB: /usr/lib64/libxcb.so (found version "1.12") 
-- Could NOT find XCB_EVENT (missing:  XCB_EVENT_LIBRARY XCB_EVENT_INCLUDE_DIR) 
-- Found XCB_RANDR: /usr/lib64/libxcb-randr.so (found version "1.12") 
-- Found XCB_EVENT: /usr/lib64/libxcb-util.so (found version "0.4.0") 
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-randr.so (found version "1.12") found components:  XCB RANDR EVENT 
-- Disabling debug info
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sergiant/Source/git/Latte-Dock/build
Scanning dependencies of target translations-plasmoid
[  0%] Built target translations-plasmoid
Scanning dependencies of target org.kde.latte.shell-shells-metadata-json
[  3%] Generating org.kde.latte.shell-shells-metadata.json
[  3%] Built target org.kde.latte.shell-shells-metadata-json
Scanning dependencies of target org.kde.latte.containment-plasmoids-metadata-json
[  7%] Generating org.kde.latte.containment-plasmoids-metadata.json
[  7%] Built target org.kde.latte.containment-plasmoids-metadata-json
Scanning dependencies of target translations-app
[  7%] Built target translations-app
Scanning dependencies of target translations-containment
[  7%] Built target translations-containment
Scanning dependencies of target org.kde.latte.plasmoid-plasmoids-metadata-json
[ 11%] Generating org.kde.latte.plasmoid-plasmoids-metadata.json
[ 11%] Built target org.kde.latte.plasmoid-plasmoids-metadata-json
Scanning dependencies of target latte-dock_automoc
[ 15%] Automatic moc for target latte-dock
Generating moc source moc_alternativeshelper.cpp
Generating moc source moc_panelshadows_p.cpp
Generating moc source moc_screenpool.cpp
Generating moc source moc_abstractwindowinterface.cpp
Generating moc source moc_dockconfigview.cpp
Generating moc source moc_dockcorona.cpp
Generating moc source moc_dockview.cpp
Generating moc source moc_dockpackage.cpp
Generating moc source moc_visibilitymanager.cpp
Generating moc source moc_visibilitymanager_p.cpp
Generating moc source moc_xwindowinterface.cpp
Generating moc source moc_dock.cpp
Generating moc compilation latte-dock_automoc.cpp
[ 15%] Built target latte-dock_automoc
Scanning dependencies of target latte-dock
[ 19%] Building CXX object app/CMakeFiles/latte-dock.dir/__/liblattedock/dock.cpp.o
[ 23%] Building CXX object app/CMakeFiles/latte-dock.dir/windowinfowrap.cpp.o
[ 26%] Building CXX object app/CMakeFiles/latte-dock.dir/abstractwindowinterface.cpp.o
[ 30%] Building CXX object app/CMakeFiles/latte-dock.dir/xwindowinterface.cpp.o
[ 34%] Building CXX object app/CMakeFiles/latte-dock.dir/visibilitymanager.cpp.o
[ 38%] Building CXX object app/CMakeFiles/latte-dock.dir/dockcorona.cpp.o
[ 42%] Building CXX object app/CMakeFiles/latte-dock.dir/dockview.cpp.o
[ 46%] Building CXX object app/CMakeFiles/latte-dock.dir/dockconfigview.cpp.o
[ 50%] Building CXX object app/CMakeFiles/latte-dock.dir/packageplugins/shell/dockpackage.cpp.o
[ 53%] Building CXX object app/CMakeFiles/latte-dock.dir/panelshadows.cpp.o
[ 57%] Building CXX object app/CMakeFiles/latte-dock.dir/alternativeshelper.cpp.o
[ 61%] Building CXX object app/CMakeFiles/latte-dock.dir/screenpool.cpp.o
[ 65%] Building CXX object app/CMakeFiles/latte-dock.dir/main.cpp.o
[ 69%] Building CXX object app/CMakeFiles/latte-dock.dir/latte-dock_automoc.cpp.o
[ 73%] Linking CXX executable latte-dock
[ 73%] Built target latte-dock
Scanning dependencies of target lattedockplugin_automoc
[ 76%] Automatic moc for target lattedockplugin
Generating moc source moc_dock.cpp
Generating moc source moc_iconitem.cpp
Generating moc source moc_lattedockplugin.cpp
Generating moc source moc_quickwindowsystem.cpp
Generating moc compilation lattedockplugin_automoc.cpp
[ 76%] Built target lattedockplugin_automoc
Scanning dependencies of target lattedockplugin
[ 80%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/lattedockplugin.cpp.o
[ 84%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/quickwindowsystem.cpp.o
[ 88%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/dock.cpp.o
[ 92%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/iconitem.cpp.o
[ 96%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/lattedockplugin_automoc.cpp.o
[100%] Linking CXX shared library liblattedockplugin.so
[100%] Built target lattedockplugin
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/AppearanceConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/BehaviorConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/Header.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockConfiguration.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteTextField.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TasksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/config.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls/SpinBox.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/SIL Open Font License.txt
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/tangerine.ttf
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/metadata.desktop
-- Installing: /usr/share/metainfo/org.kde.latte.shell.appdata.xml
-- Installing: /usr/share/kservices5/plasma-shell-org.kde.latte.shell.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/LayoutManager.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config/main.xml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/blueprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter2.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images/panel-west.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AddWidgetVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AppletItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/ConfigOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/DebugWindow.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/EditModeVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.desktop
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.containment.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/layout.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/tools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/config.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/main.xml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images/panel-west.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/CircleText.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigAppearance.qml.cmake
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigInteraction.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigPanel.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/GlowPoint.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/MouseHandler.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskActiveItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskGroupItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskProgressOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipDelegate2.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipWindowMouseArea.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/VisualAddItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.desktop
-- Installing: /usr/share/metainfo/org.kde.latte.plasmoid.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.plasmoid.desktop
-- Installing: /usr/bin/latte-dock
-- Installing: /usr/share/applications/latte-dock.desktop
-- Installing: /usr/lib64/qml/org/kde/latte/liblattedockplugin.so
-- Installing: /usr/lib64/qml/org/kde/latte/qmldir
-- Installing: /usr/share/icons/hicolor/16x16/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/22x22/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/24x24/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/32x32/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/48x48/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/scalable/apps/latte-dock.svg
-- Installing: /usr/share/icons/breeze/applets/256/org.kde.latte.plasmoid.svg

**Comment by psifidotos** [comment]
Your distro has a bug and someone communicate it with them...

You can read at: #86
