### ISSUE TITLE
Latte-dock loads many instances of it and block top sceen section

### ISSUE THREAD

**Issue by fapasv** [psifidotos/Latte-Dock#221]
Some times latte-dock loads many instances (2 to 61) 
[image](https://www.dropbox.com/s/vgt7ystq2xj47yw/lattebug.png?dl=0)

----
$ latte-dock
[debug 10:14:40.162162] - package is valid true
[debug 10:14:40.162162] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 10:14:40.202202] - Adding dock for container...
[debug 10:14:40.233233] - dock geometry: "(0, 0) 1360x24"
[debug 10:14:40.265265] - dock geometry: "(0, 0) 1360x24"
[debug 10:14:40.265265] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[debug 10:14:40.265265] - dock geometry: "(0, 744) 1360x24"
[warning 10:14:40.454454] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[debug 10:14:40.711711] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 10:14:40.711711] - 7e7248b9-8ea3-4d6f-a17e-a12b5aa9525c
[debug 10:14:40.711711] - ----------- Latte Plasmoid Signal End ---------
[debug 10:14:40.929929] - dock geometry: "(0, 655) 1360x113"
[debug 10:14:40.929929] - dock geometry: "(0, 655) 1360x113"
[debug 10:14:40.930930] - 1 docks on screen: 0
[debug 10:14:40.945945] - Adding dock for container...
[debug 10:14:40.947947] - dock geometry: "(0, 0) 1360x24"
[debug 10:14:40.948948] - dock geometry: "(0, 0) 1360x24"
[debug 10:14:40.948948] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[warning 10:14:40.948948] - wrong location, couldn't update the panel position 0
[warning 10:14:40.948948] - wrong location, couldn't update the panel position 0
[debug 10:14:40.948948] - dock geometry: "(0, 0) 1360x24"
[warning 10:14:40.964964] - file:///usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml:69: Error: Cannot assign [undefined] to QString
[warning 10:14:40.964964] - wrong location, couldn't update the panel position 0
[debug 10:14:40.964964] - dock geometry: "(0, 0) 1360x24"
[debug 10:14:40.965965] - 2 docks on screen: 0
[debug 10:14:40.966966] - 2 docks on screen: 0
[warning 10:14:41.490490] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml:418: TypeError: Cannot read property 'visibility' of null

**Comment by JenaPlinsky** [comment]
These problems have been fixed ... trying to install from the last master branch
What distribution are you using?
For information read the  [F.A.Q.](https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.)

**Comment by fapasv** [comment]
thanks a lot man!

**Comment by JenaPlinsky** [comment]
if you intend to install from the master branch probably you need some dependencies
Are you using openSUSE ?

**Comment by JenaPlinsky** [comment]
@fapasv 
This script...
- try to install the dependences (...only tested on openSUSE)
- download from git hub 
- and install latte 
```
os(){ os=$(cat /etc/*-release | grep ^DISTRIB_ID= | sed 's/DISTRIB_ID=//')
      echo $os
    }

# here add the dependences
os
echo $os
if [ "${os:1:8}" == "openSUSE" ];then
   sudo zypper --non-interactive --quiet install \
   plasma-framework-devel \
   ki18n-devel \
   kcoreaddons-devel \
   kxmlgui-devel \
   kactivities5-devel \
   kdeclarative-devel \
   kwindowsystem-devel \
   kiconthemes-devel \
   libQt5Core-devel \
   libqt5-qtx11extras-devel
elif [ "${os:1:7}" == "Kubuntu" ];then
   sudo add-apt-repository ppa:kubuntu-ppa/backports
   sudo apt update
   sudo apt dist-upgrade
   sudo apt install cmake \
   extra-cmake-modules \
   qtdeclarative5-dev \
   libqt5x11extras5-dev \
   libkf5iconthemes-dev \
   libkf5plasma-dev \
   libkf5windowsystem-dev \
   libkf5declarative-dev \
   libkf5xmlgui-dev \
   libkf5activities-dev
elif [ "${os:1:4}" == "Arch" ];then
   sudo pacman -Syy
   sudo pacman -S cmake extra-cmake-modules
   sudo pacman -S qt5-base qt5-declarative qt5-x11extras
   sudo pacman -S kiconthemes kdbusaddons kxmlgui kdeclarative plasma-framework plasma-desktop
elif [ "${os:1:6}" == "Fedora" ];then
   echo
   # sudo dnf install -y .....
else
   echo "unknown distribution"
   exit 1
fi

target="$HOME"
cd "$target"
sudo rm -rf "$target/Latte-Dock" 2>/dev/null
killall -9 latte-dock 2>/dev/null
killall -9 ddd 2>/dev/null

# download folders
git clone https://github.com/psifidotos/Latte-Dock.git # git pull -r #When you want to update:


cd "$target/Latte-Dock"
bash "$target/Latte-Dock/install.sh"
latte-dock #&
# ddd --gdb --debugger latte-dock --debug --with-window --graphics --mask #debug mode command

exit
```
