### ISSUE TITLE
Preparing v0.6.0 - Release

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#222]
This is an open dialog between the developers in order to discuss the schedule for the first release of Latte (v0.6.0)

**Comment by psifidotos** [comment]
I have merged all fixes in master and updated the translation strings for all these want to contribute translations...

I believe that we must release v0.6.0 inside March... All needed pieces are present...

- multi screen
- very rare crashes but nothing specific
- configuration window
... and so many more that fix problems with v0.5.91

the only feature that I would like to include in v0.6 is to add widgets in Fill alignment for all three available places when it isnt at editing mode (e.g. left,center,right). Currently the user can add only in the center

**Comment by psifidotos** [comment]
> the only feature that I would like to include in v0.6 is to add widgets in Fill alignment for all three available places when it isnt at editing mode (e.g. left,center,right). Currently the user can add only in the center

#226 merged in master...

**Comment by audoban** [comment]
Ok then I will to begin to add support for wayland and to update the changelog.
