### ISSUE TITLE
Why waste energy needlessly?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#223]
On the **visibility mode autohide** I think that there is the possibility of inhibiting the task bumping animation and eventually other animation, **when the dock is in hidden state** in order to save energies (although the increase of the CPU activity seems to be insignificant)

When I open dolphin for the first time, the CPU activity increases up to **5%**
and the same thing happens if I open a new instance of dolphin, but in this case the increase is **2%**

What do u think about it ?

**Comment by psifidotos** [comment]
@audoban had ordered metrics that provide proof of Latte being energy consumer... if these metrics dont land there isnt a discussion concerning this...

If a user values energy consumation that much, can always disable all animations..

**Comment by JenaPlinsky** [comment]
I do not mean to say that there is an excessive waste of resources, I just wondered if Latte could be even more powerful than it is already
