### ISSUE TITLE
help, I cannot build the project

### ISSUE THREAD

**Issue by fapasv** [psifidotos/Latte-Dock#225]
./install.sh 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.31.0") 
-- Found KF5PlasmaQuick: /usr/lib/x86_64-linux-gnu/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.31.0") 
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.31.0") 
-- Found KF5Declarative: /usr/lib/x86_64-linux-gnu/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.31.0") 
-- Found KF5Activities: /usr/lib/x86_64-linux-gnu/cmake/KF5Activities/KF5ActivitiesConfig.cmake (found version "5.31.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.7") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.31.0") 
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.31.0") 
-- Found KF5XmlGui: /usr/lib/x86_64-linux-gnu/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.31.0") 
-- Found KF5DBusAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5DBusAddons/KF5DBusAddonsConfig.cmake (found version "5.31.0") 
-- Found KF5IconThemes: /usr/lib/x86_64-linux-gnu/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.31.0") 
-- Found KF5Wayland: /usr/lib/x86_64-linux-gnu/cmake/KF5Wayland/KF5WaylandConfig.cmake (found version "5.31.0") 
-- Found KF5: success (found suitable version "5.31.0", minimum required is "5.26.0") found components:  Plasma PlasmaQuick WindowSystem Declarative Activities I18n CoreAddons XmlGui DBusAddons IconThemes Wayland 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.11.1") 
-- Could NOT find XCB_EVENT (missing:  XCB_EVENT_LIBRARY XCB_EVENT_INCLUDE_DIR) 
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so (found version "1.11.1") 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find XCB (missing: EVENT) (found version "1.11.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindXCB.cmake:187 (find_package_handle_standard_args)
  CMakeLists.txt:31 (find_package)

**Comment by psifidotos** [comment]
you are missing xcb development packages...

you can get help for installing at: #203

**Comment by fapasv** [comment]
no, in fact, i have installed xcb dependences... u_u

**Comment by nixway** [comment]
hi, prompt that for a problem?
```
Installing with make install...

========================= Результаты установки ===========================
[  0%] Built target translations-separator
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  0%] Built target translations-containment
[  0%] Built target translations-spacer
[  2%] Automatic MOC for target latte-dock
Generating MOC predefs moc_predefs.h
[  6%] Built target latte-dock_autogen
[ 74%] Built target latte-dock
[ 76%] Built target audoban.applet.separator-plasmoids-metadata-json
[ 78%] Built target org.kde.latte.spacer-plasmoids-metadata-json
[ 80%] Built target org.kde.latte.containment-plasmoids-metadata-json
[ 82%] Automatic MOC for target lattedockplugin
Generating MOC predefs moc_predefs.h
[ 82%] Built target lattedockplugin_autogen
[ 95%] Built target lattedockplugin
[ 97%] Built target org.kde.latte.plasmoid-plasmoids-metadata-json
[100%] Built target org.kde.latte.shell-shells-metadata-json
Install the project...
-- Install configuration: ""
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/pt/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/ru/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/ru/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/pt/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/ru/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.spacer.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.spacer.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.spacer.mo
-- Installing: /usr/bin/latte-dock
-- Installing: /usr/share/applications/org.kde.latte-dock.desktop
-- Installing: /usr/share/metainfo/org.kde.latte-dock.appdata.xml
-- Installing: /usr/share/dbus-1/interfaces/org.kde.LatteDock.xml
-- Installing: /usr/share/knotifications5/lattedock.notifyrc
-- Up-to-date: /usr/share/plasma/plasmoids/audoban.applet.separator
-- Up-to-date: /usr/share/plasma/plasmoids/audoban.applet.separator/contents
-- Up-to-date: /usr/share/plasma/plasmoids/audoban.applet.separator/contents/ui
-- Installing: /usr/share/plasma/plasmoids/audoban.applet.separator/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/audoban.applet.separator/metadata.desktop
-- Installing: /usr/share/plasma/plasmoids/audoban.applet.separator/metadata.json
-- Installing: /usr/share/metainfo/audoban.applet.separator.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-audoban.applet.separator.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.spacer
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents/config/config.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents/config/main.xml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents/ui/ConfigAppearance.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.spacer/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.spacer/metadata.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.spacer/metadata.json
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.spacer.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/AppletIdentifier.js
CMake Error at containment/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/nihi1ist/Разработка/builds/src/plasmoids/plasma-applet-latte-dock/0.7.1/plasma-applet-latte-dock-0.7.1/containment/package/contents/code/HeuristicTools.js".
Call Stack (most recent call first):
  cmake_install.cmake:143 (include)


Makefile:61: ошибка выполнения рецепта для цели «install»
make: *** [install] Ошибка 1

****  Установка неудачна. Отменяется создание пакета.

Очищается...OK

Удачи.
```

**Comment by psifidotos** [comment]
it doesnt find: `/containment/package/contents/code/HeuristicTools.js`

from where did you download the source code?

**Comment by nixway** [comment]
From [here](https://github.com/psifidotos/Latte-Dock/archive/v0.7.1.tar.gz).

**Comment by psifidotos** [comment]
how are you trying to install it? 
have you tried to use our `install.sh` script?

**Comment by nixway** [comment]
> have you tried to use our `install.sh` script?

yes, but i'm change `make install` command to `checkinstall` command.

**Comment by psifidotos** [comment]
Is the build directory at the root of Latte source?

**Comment by nixway** [comment]
no, `latte_source/build` directory.

**Comment by nixway** [comment]
error:
```
CMake Error at containment/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/nihi1ist/Разработка/builds/src/plasmoids/plasma-applet-latte-dock/0.7.1/plasma-applet-latte-dock-0.7.1/containment/package/contents/code/HeuristicTools.js".
Call Stack (most recent call first):
  cmake_install.cmake:143 (include)


Makefile:61: ошибка выполнения рецепта для цели «install»
```
full path:
```
ls -l /home/nihi1ist/Разработка/builds/src/plasmoids/plasma-applet-latte-dock/0.7.1/plasma-applet-latte-dock-0.7.1/containment/package/contents/code/HeuristicTools.js
-rw-r--r-- 1 nihi1ist nihi1ist 8093 авг 31 13:53 /home/nihi1ist/Разработка/builds/src/plasmoids/plasma-applet-latte-dock/0.7.1/plasma-applet-latte-dock-0.7.1/containment/package/contents/code/HeuristicTools.js
```

**Comment by psifidotos** [comment]
Btw what is your distro? Doesnt provide a prebuilt 0.7.1 Latte?

**Comment by nixway** [comment]
Debian testing. A packet from PPA animation doesn't work.
