### ISSUE TITLE
compositing state through liblatteplugin has broke some relevant ui functionality

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#23]

**Comment by audoban** [comment]
Is it because of the latest changes I made in class?

**Comment by psifidotos** [comment]
yes, but dont worry I will update the ui....

**Comment by audoban** [comment]
ok, thanks

**Comment by audoban** [comment]
Have you fixed this?, because I fixed this on my local branch, but if you already fixed I will doesn't a commit about this.

**Comment by psifidotos** [comment]
Please commit it

**Comment by psifidotos** [comment]
fixed in master
