### ISSUE TITLE
Ignored translation

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#230]
```
#: ../../shell/contents/configuration/AppearanceConfig.qml:255
#, fuzzy
msgid "Solid Background"
msgstr "Sfondo solido"
```
![screenshot_20170305_231819](https://cloud.githubusercontent.com/assets/24593950/23591984/3978a97e-01fa-11e7-9c41-8a20e6432886.png)

**Comment by psifidotos** [comment]
You have an old locale file installed at your system...

/usr/share/locale/kf5/<lang>/LC_LOCALES/latte-dock.mo

you must delete it... latte installs its new locales at the above path but without the kf5 in it...

**Comment by JenaPlinsky** [comment]
are you sure ?
There are strings that I translated and are displayed correctly
while, only the one shown in the picture, remains in English

by the way I've removed:
rm /usr/share/locale/kf5//LC_LOCALES/latte-dock.mo    .....not exist
rm /usr/share/locale/kf5/it/LC_LOCALES/latte-dock.mo    .....not exist
rm /usr/share/locale/it/LC_MESSAGES/latte-dock.mo    .....deleted

**Comment by psifidotos** [comment]
From it.po


#: ../../shell/contents/configuration/AppearanceConfig.qml:255
#, fuzzy
msgid "Solid Background"
msgstr "Sfondo solido"

**Comment by psifidotos** [comment]
The tag fuzzy i dont know what is...

**Comment by psifidotos** [comment]
https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html

**Comment by psifidotos** [comment]
The it.po hasnt be authored correctly...
you must confirm all strings

**Comment by psifidotos** [comment]
The none string for shadows has also the same tah

**Comment by psifidotos** [comment]
tag

**Comment by JenaPlinsky** [comment]
> The it.po hasnt be authored correctly...
> you must confirm all strings

how?

**Comment by psifidotos** [comment]
When opening it.po with Likalize are these strings shown differently?

**Comment by psifidotos** [comment]
Lokalize

**Comment by JenaPlinsky** [comment]
shit !! I imagined that I had to use Lokalize ... I edited by hand directly to the file ... can work too?

**Comment by psifidotos** [comment]
it could... even though Lokalize is the suggested way to go... you could try to remove the fuzzy tags
completely... install in your system and check if it worked...

**Comment by JenaPlinsky** [comment]
@audoban 
please check the string `msgstr "Fondo"` and the tag `fuzzy`
your translation is read correctly?
```
#: ../../shell/contents/configuration/AppearanceConfig.qml:255
#, fuzzy
msgid "Solid Background"
msgstr "Fondo"
```
