### ISSUE TITLE
Add autostart selection in configuration window

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#233]
what do you think if there was an option to enable autostart only for the KDE environment ... would facilitate things for beginners

**Comment by audoban** [comment]
It would be good.

**Comment by psifidotos** [comment]
yes... this is interesting... 

@audoban how would you approach this?

1. adding latte dock metadata at autostart folder?
2. this is done automatically or the user selects it from the configuration window?

**Comment by audoban** [comment]
yes I think that is easy

**Comment by psifidotos** [comment]
added this option in the Tweaks page of configuration window

**Comment by JenaPlinsky** [comment]
Should prevent the auto start of Latte, if the user decides to access in Gnome or other environments different than plasma
![screenshot_20170308_210901](https://cloud.githubusercontent.com/assets/24593950/23722498/e8c9eaf8-0445-11e7-9d19-fc61854fc3ed.png)

**Comment by psifidotos** [comment]
@JenaPlinsky unfortunately I found a situation for Plasma 5.8 that plasma wasnt starting because of this... so this remains as it is until we know more about it... the user can always enable this from plasma systemsettings...

**Comment by JenaPlinsky** [comment]
Ohhh yeah ;)
I like a lot, your work
