### ISSUE TITLE
ksysguard regression on Latte's icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#235]
![screenshot_20170306_050736](https://cloud.githubusercontent.com/assets/24593950/23596474/052c129c-022b-11e7-9b03-3d8085426e80.png)

**Comment by Petross404** [comment]
Does the Latte's _menu_ have an icon?

**Comment by psifidotos** [comment]
#42 you should clear your icons cache and use latest master

**Comment by JenaPlinsky** [comment]
@Petross404 

> Does the Latte's menu have an icon?

![screenshot_20170306_183307](https://cloud.githubusercontent.com/assets/24593950/23621575/9b7b5ee0-029b-11e7-8d12-b354ecb04867.png)
![screenshot_20170306_183324](https://cloud.githubusercontent.com/assets/24593950/23621578/9d00845c-029b-11e7-9407-5709ea24628e.png)

> you should clear your icons cache and use latest master

how can I do it ?
I've tryed to change icon set ...here is a [video](https://www.youtube.com/watch?v=zLguQ-jwBjM)

**Comment by psifidotos** [comment]
> how can I do it ?

`kbuildsycoca5 -noincremental`

icons caches are a strange thing in plasma... their history is cleared a little difficult...

**Comment by JenaPlinsky** [comment]
I have executed kbuildsycoca5 -noincremental
but still remain the wrong icon

**Comment by psifidotos** [comment]
no more ideas...

**Comment by audoban** [comment]
On my system works fine.

I don't know what happen

**Comment by Petross404** [comment]
@JenaPlinsky  try to see if the problem exists with any other application. Until Latte is officially packaged for your distro and report a bug to plasma devs, little can be done. Except posting the problem in a kde forum and wait for an answer.

**Comment by psifidotos** [comment]
Of course there is a chance that this was introduced from some new commits of plasma.... we will see..
