### ISSUE TITLE
[UX] Keep Latte hidden when switching virtual desktops

### ISSUE THREAD

**Issue by joseffilzmaier** [psifidotos/Latte-Dock#238]
I love your dock, but there are some minor pain points which i would like to share and hear your opinions. I will do so in separate issues and with videos so you know exactly what i mean.

No. 1:

When i switch between two virtual desktops (might also be the case for activities but i don't use those so i dont care) which both have fullscreen windows open the dock appears for a short amount of time before hiding again. This is quite distracting when switching the virtual desktop a lot, like i do.

Demonstration:
https://youtu.be/UaKXbg0BtEg

In my opinion the dock should stay hidden while the virtual desktop switcher is doing it's thing.

I'm using Arch with Plasma 5.9.3 and the AUR git version of latte dock with dodge active

Thank you for your work!

**Comment by psifidotos** [comment]
this was added by #139... it was a user's suggestion and we thought it as a good behavior...

I dont know if we can make an option for this in the configuration window...

@audoban what do you think?

**Comment by psifidotos** [comment]
I think this was proposed by @JenaPlinsky ...

it would be good to be all the members of this discussion in it... :)

**Comment by joseffilzmaier** [comment]
Wow, fast response time :+1:
Hmm, i understand the idea with the behaviour in #139 when using the cube effect for virtual desktop switching, because this effect is in itself quite distracting.

For me personally the "distraction-freeness" aspect should however be the default behaviour. But being a Plasma user i always like to have more options ;)

**Comment by audoban** [comment]
> @audoban what do you think?

I think it also distracts me, do you want to make it configurable?

**Comment by JenaPlinsky** [comment]
in the default plasma panel behavior, the duration of this effect is much shorter
You might think to parameterize its appearance so if one does not want to show it can set it to none

**Comment by psifidotos** [comment]
fixed in master....

**Comment by psifidotos** [comment]
you can set this behavior from Tweaks page in the configuration window...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/23757295/0a982934-04ef-11e7-89dd-ccd0b44af76e.png)
