### ISSUE TITLE
Starting an application with "Show a launcher when not running"

### ISSUE THREAD

**Issue by joseffilzmaier** [psifidotos/Latte-Dock#239]
Hi again!

Starting an application which is currently not running but has the "Show launcher when not running" option set does have a weird behaviour **visually** when launching it.

In my opinion the icon should not hide itself at all and just bounce shortly to let the user know that it has recognized his/her button click. Also when closing a window with this property it should not hide its icon in the dock shortly.

Demonstration:
https://www.youtube.com/watch?v=iy1q2ScQhcY

Plasma 5.9.3 latte-dock git

Thanks again :)

**Comment by psifidotos** [comment]
Sorry this is upstream, nothing can be done for this except disabling all animations that is already supported...

You can read #72
