### ISSUE TITLE
Configuration Window isnt always shown even though it is triggered...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#24]
I can not find the reason but there are some rare cases that the configuration window isnt shown even though it is triggered to

**Comment by audoban** [comment]
I think I fixed it in Candil

**Comment by psifidotos** [comment]
If you can track it down, my pleasure...

**Comment by psifidotos** [comment]
The error shown in such case: 
 QQmlExpression: Attempted to evaluate an expression in an invalid context
