### ISSUE TITLE
Dota2 Icon not respected

### ISSUE THREAD

**Issue by adrfantini** [psifidotos/Latte-Dock#243]
See this screenshot:
http://i.imgur.com/KLgjqMq.png

On the left, Latte Dock, on the right, the built-in Icon-only task manager.
I already run `kbuildsycoca5 --noincremental` to no avail.

Also, the placeholder icon looks terrible, it must be too small for some reason and is not upscaled well.

**Comment by psifidotos** [comment]
What is Dota2? Wine app?

What placeholder, screenshot?

**Comment by adrfantini** [comment]
Dota2 is a Steam game. As you can see in Icon only tasks manager its icon is all right, while in Latte it is an X placeholder (bwlow the chromium icon in the screenshot linked above)

**Comment by psifidotos** [comment]
All steam games have the same issue?

**Comment by psifidotos** [comment]
the placeholder icon used I dont think it's latte fault... it doesnt have an svg...

**Comment by adrfantini** [comment]
@psifidotos No, the only other game I have (Cities Skyline) works fine and has the right icon.

**Comment by psifidotos** [comment]
@adrfantini  at folder:

~/.local/share/applications/ 

you can find all user definied desktop files... in there you should be able to find both the desktop files for dota2 and cities skyline...

can you upload them here?

**Comment by adrfantini** [comment]
Sure:
https://transfer.sh/JQoQ3/dota-2.desktop
https://transfer.sh/kBmpO/cities-skylines.desktop

Also a screenshot with the C:S icon too:
http://i.imgur.com/RMyOiyt.png

For some reason the icon is the .desktop is only called "steam", whcih makes no sense but... it works

**Comment by psifidotos** [comment]
> For some reason the icon is the .desktop is only called "steam", whcih makes no sense but... it works

can you check if by replacing in dota2.desktop file the "steam_icon_570" to "steam" like in cities-skyline.desktop what happens for the icon then ?

**Comment by adrfantini** [comment]
Yes, it works in this case if I just write "steam" as the icon (it looks a
lot too low-res tho, maybe 32px, just like the X icon previously did).

2017-03-08 13:30 GMT+01:00 Michail Vourlakos <notifications@github.com>:

**Comment by psifidotos** [comment]
> lot too low-res tho, maybe 32px, just like the X icon previously did).

upload a screenshot showing the two icons with the fixed behavior (one from latte and one from plasma taskmanager) without hovering the latte icon

**Comment by psifidotos** [comment]
@adrfantini can you check branch **steam** if it makes Latte behave like plasma taskmanager?

**Comment by adrfantini** [comment]
Errrrr. I swear it was working, I saw it. But now it does not work anymore? Still got the X icon, but now... also in icon-only task manager! (normal version, not steam branch)

Both with "steam" and with "steam_icon_570"... is there some sort of cache?

**Comment by psifidotos** [comment]
`kbuildsycoca5 --noincremental`

**Comment by adrfantini** [comment]
Ok, works. There is no difference in the "Icon-only task manager" icon -
both are correct, but both are definitely too low-res. This may be because
Steam provides an icon which is crap.

2017-03-08 15:15 GMT+01:00 Michail Vourlakos <notifications@github.com>:

**Comment by psifidotos** [comment]
> Ok, works. There is no difference in the "Icon-only task manager" icon -
both are correct, but both are definitely too low-res. This may be because
Steam provides an icon which is crap.

so... what works? the **steam** branch or setting manually steam as icon ?

**Comment by psifidotos** [comment]
> both are correct, but both are definitely too low-res. This may be because Steam provides an icon which is crap.

definitely...

**Comment by adrfantini** [comment]
Setting manually "steam" as icon. I did not try the steam branch and do not
have time to do so right now.

2017-03-08 15:22 GMT+01:00 Michail Vourlakos <notifications@github.com>:
