### ISSUE TITLE
Show Launcher when not Running 'Juggling'

### ISSUE THREAD

**Issue by kusius** [psifidotos/Latte-Dock#244]
When launching an application that I've set to show on the dock when not running , there's a weird sequence that happens, that is:

1. Clicking to launch the application, the launcher gets removed from the dock temporarily until the application runs, then the icon shows again.
2. when closing the application, the inverse happens. That is the running icon disappears and after a while the launcher icon appears again.

I'm wondering if it is possible that those transitions are made more seamlessly,  meaning : avoiding the hide/show ('juggling') of the icon and having the icon stay on the dock and switch from / to the "running" state and the "launcher" state.

Great work on Latte so far , enjoying it !!!
Cheers, GK

**Comment by psifidotos** [comment]
unfortunaly this is plasma's libtaskmanager default behavior... only thing can be done is disabling animations totally...

#72

**Comment by kusius** [comment]
oh ok got it , well it's not a huge deal either way. Thanks for the quick response!
