### ISSUE TITLE
QtCreator's launcher Icon issue

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#245]
QtCreator task:
![screenshot_20170309_190806](https://cloud.githubusercontent.com/assets/24593950/23764014/34f924c8-04fc-11e7-8162-c55e0faebfcb.png)
QtCreator launcher:
![screenshot_20170309_190833](https://cloud.githubusercontent.com/assets/24593950/23764011/328281c6-04fc-11e7-990a-f43d18c95c6b.png)

**Comment by psifidotos** [comment]
confirm this isnt an issue with original plasma taskmanager...

**Comment by JenaPlinsky** [comment]
Eheeeeheheh. I always forget to make the comparison with the default plasma task manager ;(
the problem is not due to Latte
![spectacle s24893](https://cloud.githubusercontent.com/assets/24593950/23767158/d666e056-0507-11e7-8b4f-9f1b1c891ae7.png)

**Comment by psifidotos** [comment]
;)
