### ISSUE TITLE
Incorrect/inconsistent behaviour when switching virtual desktops

### ISSUE THREAD

**Issue by giogziro95** [psifidotos/Latte-Dock#246]
The dock has an incorrect/inconsistent behaviour when you switch between the virtual desktops under the _Dodge Active_ setting activated.

**Version:** 0.5.91.

**Reproducible:** Always.

**Steps to reproduce:**

1. In _Behavior_ tab, Set _Visibility_ to _Dodge Active_.
2. Open a window and maximize it or move it so that it covers the dock, hence the dock disappears.
3. Switch to another virtual desktop, open another window and maximize it / move it the same way as well.
4. Switch to the previous virtual desktop using the Desktop Grid or a keyboard shortcut (set it up first, if you haven't already).

**Actual results:**

- The dock shows up. You can toggle between the virtual desktops and it's still there.
- The dock behaves correctly and disappears when you switch from a desktop with a non-covering window to a desktop with a covering window.

**Expected results:**

- Since the active window covers the dock, it shouldn't be showing up.
- Even if it _should_ be showing up, it doesn't do that when switching from a desktop with a non-covering window to a desktop with a covering window, resulting in an inconsistent behaviour.

**Comment by psifidotos** [comment]
What latte version are you using? 0.5.91 or installed from master?

**Comment by psifidotos** [comment]
> Since the active window covers the dock, it shouldn't be showing up.

no... this is a design decision... the user can choose when changing desktops or activities the dock to be shown temporarily in order to see what tasks exist and what has changed...

you can disable this behavior from tweaks configuration page...

![image](https://cloud.githubusercontent.com/assets/2216474/23822608/37b93146-0658-11e7-9a0d-7585e558ec8f.png)

**Comment by giogziro95** [comment]
Hmm... I don't see the _Tweaks_ tab here, though. I'm using the version from the AUR, so it might be the build issue, perhaps?

I'll try building it from the source.

**Comment by giogziro95** [comment]
Never mind, it's there if you install a version from the _master_ branch.

**Comment by giogziro95** [comment]
I can still replicate the bug. When _Raise docks on desktop or activity change_ is unchecked under _Latte Settings_ → _Tweaks_ → _Behavior_.

When it's checked, it appears and disappears after a second when switching desktop. However, when it's unchecked, it doesn't disappear afterwards. The initial bug report was also about the last behaviour (it didn't dissapear).

**Comment by psifidotos** [comment]
> When it's checked, it appears and disappears after a second when switching desktop. However, when it's unchecked, it doesn't disappear afterwards. The initial bug report was also about the last behaviour (it didn't disappear).

the implementation for this will change the next days.. we can try again with the new implementation and see what happens...

**Comment by JenaPlinsky** [comment]
Ciao @giogziro95 
in the transition from version 0.5.91 to 0.6.0
a lot of issues have been fixed
and implemented additional features
What distro are you using ?

**Comment by Petross404** [comment]
@giorgziro95 You have to install latte-dock-*git* from AUR. Have a nice day.

**Comment by JenaPlinsky** [comment]
@giogziro95 
If you are impatient and if you have the libraries and frameworks as in the screenshot ...

this script should work: ...
- download the latest version from the master branch
- install the missing dependencies (never tried before)
- kills the dock running
- install the last downloaded version
- and run latte-dock

![screenshot_20170312_075226](https://cloud.githubusercontent.com/assets/24593950/23829696/202f8b28-06f9-11e7-9fd7-822f963871ca.png)


```
#!/bin/bash
os(){ os=$(cat /etc/*-release | grep ^DISTRIB_ID= | sed 's/DISTRIB_ID=//')
      echo $os
    }

# here add the dependences
os
echo $os
if [ "${os:1:8}" == "openSUSE" ];then
   sudo zypper --non-interactive --quiet install \
   plasma-framework-devel \
   ki18n-devel \
   kcoreaddons-devel \
   kxmlgui-devel \
   kactivities5-devel \
   kdeclarative-devel \
   kwindowsystem-devel \
   kiconthemes-devel \
   libQt5Core-devel \
   libqt5-qtx11extras-devel
elif [ "${os:1:7}" == "Kubuntu" ];then
   sudo add-apt-repository ppa:kubuntu-ppa/backports
   sudo apt update
   sudo apt dist-upgrade
   sudo apt install cmake \
   extra-cmake-modules \
   qtdeclarative5-dev \
   libqt5x11extras5-dev \
   libkf5iconthemes-dev \
   libkf5plasma-dev \
   libkf5windowsystem-dev \
   libkf5declarative-dev \
   libkf5xmlgui-dev \
   libkf5activities-dev
elif [ "${os:1:4}" == "Arch" ];then
   sudo pacman -Syy
   sudo pacman -S cmake extra-cmake-modules
   sudo pacman -S qt5-base qt5-declarative qt5-x11extras
   sudo pacman -S kiconthemes kdbusaddons kxmlgui kdeclarative plasma-framework plasma-desktop
elif [ "${os:1:6}" == "Fedora" ];then
   echo
   # sudo dnf install -y .....
else
   echo "unknown distribution"
   exit 1
fi

target="$HOME"
cd "$target"
sudo rm -rf "$target/Latte-Dock" 2>/dev/null
killall -9 latte-dock 2>/dev/null
killall -9 ddd 2>/dev/null

# download folders
git clone https://github.com/psifidotos/Latte-Dock.git # git pull -r #When you want to update:

cd "$target/Latte-Dock"
bash "$target/Latte-Dock/install.sh"
latte-dock

exit
```
