### ISSUE TITLE
Feature request: Switching to the application window while dragging

### ISSUE THREAD

**Issue by giogziro95** [psifidotos/Latte-Dock#247]
In many docks and task managers, when you drag a content to an application icon within the dock (task manager), the application window (or list of the windows in the case of multiple windows of the same application open) shows up and activates. A similar functionality would be nice here too.

See also:

- psifidotos/nowdock-panel#70

**Comment by giogziro95** [comment]
See also:

- psifidotos/nowdock-panel#70

**Comment by psifidotos** [comment]
What latte version are you using?

**Comment by psifidotos** [comment]
In master all this is supported..

**Comment by psifidotos** [comment]
this has been implemented.....

**Comment by giogziro95** [comment]
The version number is 0.5.91. I don't know; it doesn't seem to be working here.

**Comment by psifidotos** [comment]
The version from AUR is around one and a half month old... if i remember correctly there is also a build based on master...

**Comment by psifidotos** [comment]
https://aur.archlinux.org/packages/latte-dock-git/

**Comment by giogziro95** [comment]
`./install.sh` worked just well from the _master_ branch. Sorry, you're right, I was using an outdated version. It does work on the newest version indeed. Though, for some reason, it did reset my configuration. From what I can tell, it's because the newer version uses a dedicated folder under _~/.config_ folder rather than writing files directly in there.

**Comment by psifidotos** [comment]
not in my system... in my system files, lattedockrc and lattedock-appletsrc are used under .config

at some point we move from LatteDockrc to lattedockrc, i dont know if thats the case for you...

**Comment by giogziro95** [comment]
I've deleted the folder and the files under _~/.config_ that included _latte_ in their names for the sake of a fresh start and it didn't re-create the folder. I guess it was from a previous installation and I missed it then (I was tinkering around the settings files before).

**Comment by psifidotos** [comment]
@giogziro95 I dont have any ideas...
