### ISSUE TITLE
Minimize thickness spacing for reverse state of tasks

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#248]
![reverse](https://cloud.githubusercontent.com/assets/2216474/23822653/c7219278-0659-11e7-9785-63096a1ca2fe.png)

**Comment by psifidotos** [comment]
mentioned also at: #224

**Comment by psifidotos** [comment]
it is ready but it isnt merged to master yet...

![image](https://cloud.githubusercontent.com/assets/2216474/23825399/d7eb9f76-0691-11e7-8175-ad940fc8a325.png)

**Comment by psifidotos** [comment]
merged it...

**Comment by Petross404** [comment]
Excellent job 👍

**Comment by psifidotos** [comment]
thank u ... :) it works also with regular positioning not only the reverse lines/dots
