### ISSUE TITLE
Resize plasma widget from latte's configuration

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#249]
Good afternoon. I was experimenting with some plasma widgets on my dock and I realized that "Web browser" for example can't be resized if it is docked on latte.

Is there a way to set the size of an applet when it's shown inside the `~/.config/lattedock-appletsrc` ?

`[Containments][1][Applets][36]`
`immutability=1`
`plugin=org.kde.plasma.webbrowser`

`[Containments][1][Applets][36][Configuration][General]`
`url=http://www.google.gr/`

Can't figure out something like : Height, Width etc...

![screenshot_20170311_213240](https://cloud.githubusercontent.com/assets/18561627/23826291/4a8afd28-06a2-11e7-894d-2c90c239dc27.png)

This is way too small to be usefull. When placed on desktop the widget can be resized.

**Comment by Petross404** [comment]
Oh, and thanks for the weather widget :)

**Comment by psifidotos** [comment]
This appletsn responsibility... nothing to do with Latte... same problem would occur with traditional plasma panels also...

**Comment by Petross404** [comment]
I see. Perphaps the widget stores some defaults somewhere...  :)
