### ISSUE TITLE
The lighting effect on the applet, does not disappear when it is closed

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#250]
The lighting effect on the applet, does not disappear when it is closed
![screenshot_20170311_211234](https://cloud.githubusercontent.com/assets/24593950/23826627/6a421054-06a0-11e7-8829-1617e1128062.png)
![screenshot_20170311_211435](https://cloud.githubusercontent.com/assets/24593950/23826626/670629fc-06a0-11e7-9438-0f1c0977b725.png)

**Comment by psifidotos** [comment]
what do you mean?

**Comment by JenaPlinsky** [comment]
when the hover on a icon, this is zoomed and lighted
once lost the focus, its lighted effect should disappear, but it does not happen

**Comment by psifidotos** [comment]
this is a lot hardered that it sounds... I dont believe we will find something for this, but either way...

**Comment by JenaPlinsky** [comment]
I do not know if I explained well ....
I mean that there should be an lighted icon at a time .... but in the first screenshot I have four lighted icons at the same time

**Comment by JenaPlinsky** [comment]
until now I have not noticed anything like this
or I was distracted or working properly :)

**Comment by psifidotos** [comment]
this issue existed for ever... I added a workaround for this... it should work for most of the applets...

**Comment by JenaPlinsky** [comment]
@psifidotos
Well done ...very nice !!!

I noticed a difference in the highlight between applets and launchers/tasks
- launchers/tasks highlight effect is smooth
- applets highlight effect  **is not smooth**

**Comment by psifidotos** [comment]
The tasks higlight effect is from Latte, the applets from plasma... i will try to make applet use the Latte one...

**Comment by JenaPlinsky** [comment]
Ohhhh it is true, you're right !!!! I did not think about it

**Comment by Petross404** [comment]
@JenaPlinsky can you give a link for the wallpaper please?

**Comment by JenaPlinsky** [comment]
@Petross404 
it's the default Plasma 5.10 wallpaper
![3840x2160](https://cloud.githubusercontent.com/assets/24593950/23831386/48d7abec-0720-11e7-8632-3d30ef2ba82a.png)

**Comment by Petross404** [comment]
Thank you :)

**Comment by psifidotos** [comment]
because the improved hovering was conflicting with tooltips I disabled it for those applets that are not animated for Latte... This should also fix the folder applet spring loading when the applet is not animated...

**Comment by JenaPlinsky** [comment]
It works very well and I like it a lot ;)
