### ISSUE TITLE
What happens when the composer openGL is disabled?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#251]
visibility autohide mode does not work
Is there a way to reduce discomfort in these conditions?
is manageable a condition like this?
![screenshot_20170311_210724](https://cloud.githubusercontent.com/assets/24593950/23826662/4f6eca0a-06a1-11e7-8b05-f9d4d6bfe8b4.png)

**Comment by Petross404** [comment]
You where just testing and this is intentional or is it a plasma problem?

**Comment by psifidotos** [comment]
latte has beem designed for enabled composition... it justs provides an always visible disabled composition in order to not lose your tasks...

I would recomend to use traditional plasma panels is such case...

**Comment by JenaPlinsky** [comment]
ciao @Petross404 
It's caused due to a problem with Kwin

**Comment by JenaPlinsky** [comment]
a concept of this type, it might work?

autostart script
```
if copositor is true
   run Latte
else
   add default panel
```

**Comment by psifidotos** [comment]
sorry no...

I cant understand why you need to work with disabled compositor...
in the event that the compositor doesnt work first thing must be done is to restore it...

**Comment by JenaPlinsky** [comment]
nooooo I do not want at all !!!!! the compositor I have not disabled anything

**Comment by psifidotos** [comment]
@JenaPlinsky the disabled compositor case has get a lot of love from latest commits... It is more than workable... modes and theming work correctly... I used it many times...

**Comment by JenaPlinsky** [comment]
@psifidotos  Now, I'm going to see if you did a good working Ahahahahahah ;)

**Comment by psifidotos** [comment]
Be gentle or I will block you from the threads!!! hahahaha ;)

**Comment by JenaPlinsky** [comment]
ahhahahahah O.O

**Comment by JenaPlinsky** [comment]
Well, that is .... you left me speechless !!!
...although very young milk is now a dock to the next level !! it rocks !!! ....and the thing I appreciate most is that it integrates into plasma to perfection ... Guys you are doing a fantastic job !!!!

![1](https://cloud.githubusercontent.com/assets/24593950/23922060/3d4a0422-0901-11e7-937f-23b8cbb707af.jpg)

![brindisi-birra](https://cloud.githubusercontent.com/assets/24593950/23922094/5cefaf3e-0901-11e7-9364-cacdd451c113.jpg)

**Comment by psifidotos** [comment]
Latte has transformed my plasma, beauty and work efficient !!! :-)

**Comment by Petross404** [comment]
You started eating already? Wait for me to fetch gyros and Fix(greek beer) first :p

Anyway, Latte is slow and steadily going next level. Well done to everyone behind it's code. Also developers, forgive us if sometimes we put pressure on you with requests.

**Comment by JenaPlinsky** [comment]
well said @Petross404
