### ISSUE TITLE
Crash when click on weather applet and Latte is fresh started.

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#253]
If I click on "weather Widget" as soos as Latte just showed up I get a crash. For me this is not a problem; I can wait a second or two for Latte to fully load, but anyway for development shake.

[latte-dock-20170312-145841.kcrash.txt](https://github.com/psifidotos/Latte-Dock/files/836518/latte-dock-20170312-145841.kcrash.txt)

![backtrace](https://cloud.githubusercontent.com/assets/18561627/23832067/7cbf8edc-0736-11e7-9bc1-a6f4fed00fb2.png)

![backtrace1](https://cloud.githubusercontent.com/assets/18561627/23832068/82f41304-0736-11e7-8ba9-2664cf6374a0.png)

**Comment by psifidotos** [comment]
this is definetely upstream...  Latte has nothing to do with the models which are described in the crash...

**Comment by psifidotos** [comment]
the plasmoid should protect its model in the case that the model is not fully loaded...

**Comment by Petross404** [comment]
Is there something I have to do?

**Comment by psifidotos** [comment]
if you want... you can report it to its developer and show also the crash report...

**Comment by Petross404** [comment]
On it

**Comment by Petross404** [comment]
[Here](https://github.com/kotelnik/plasma-applet-weather-widget/issues/50) it is. Let's see.
