### ISSUE TITLE
Plasmoids tooltips stopped appearing in latte

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#255]
Perhaps one of the recent commits?

**Comment by psifidotos** [comment]
yes ... the correct hovering effect between tasks and applets... both can not be supported...

you mean the tooltips for information, right?
can you give an example to be sure?

**Comment by kupiqu** [comment]
yes, that's it, e.g. weather plasmoid, active window (long) title, system load monitor, etc.

I am not sure I understand the problem with previous implementation, but would it be possible to somehow distinguish task applets from the rest?

**Comment by psifidotos** [comment]
ok.. I restored for those applets that are not animated... **but** the hover effect used for them plasma ones...

**Comment by kupiqu** [comment]
Great, thank you!
