### ISSUE TITLE
Support user setting distance between applets

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#259]
a way for the user to change the distance between applets

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/23909346/28a1e890-08df-11e7-82c0-adedec6274a5.png)

**Comment by Petross404** [comment]
Awesome :+1:

**Comment by Petross404** [comment]
@psifidotos can you hack this feature, to be able to get icons a liitle closer? Afterall one can set how far apart they must be, but not closer that already and by default they are.

**Comment by psifidotos** [comment]
the current minimum is what Latte considers as good experience... it is around 25% of the current icon size, personally I find it sufficient... enabling lower values, I dont like how the icon margin slider will look for the default option...

**Comment by Petross404** [comment]
The default value will show a distance like this one now. But _if_ the user wishes so, let him have the ability to do whatever he likes (ok almost). Besides I am talking about a little closer and as always one has the freedom to re-adjust the distance.

So, nobody looses. But anyway :)
