### ISSUE TITLE
New config ui

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#26]
The current ui has much options together, and It does not fit on my screen, we need separate this on tabs.

* Behavior
location
alignment
visibility
show and hide timers

* appearance
zoom on hover
icon size
background
shadows

Also I want to change the Double(Left|Right) for Fill because is more simple.

**Comment by psifidotos** [comment]
I agree on the split... 

one more question: do you think a third tab would be good to have for Latte plasmoids settings or is it ok to keep it this way? (settings like preview windows, different color indicators for windows, etc.)

> Also I want to change the Double(Left|Right) for Fill because is more simple.

You mean the name? and keep the behavior?

**Comment by audoban** [comment]
> You mean the name? and keep the behavior?

Yes same behavior, different name.

> one more question: do you think a third tab would be good to have for Latte plasmoids settings or is it ok to keep it this way? (settings like preview windows, different color indicators for windows, etc.)

I'm agree with third tab for Latte plasmoids settings, and drop the current Latte plasmoid settings

**Comment by psifidotos** [comment]
> Yes same behavior, different name.

No problem

> I'm agree with third tab for Latte plasmoids settings, and drop the current Latte plasmoid settings

ok...

**Comment by psifidotos** [comment]
a beauty.... ;)

![config](https://cloud.githubusercontent.com/assets/2216474/21581701/c7a99cd0-d045-11e6-91a2-49ef98c38da5.png)

**Comment by audoban** [comment]
Looks good. But I do not like the version number.

+1 for third tab, also I wanted to call Tasks

**Comment by psifidotos** [comment]
The font choice or the text?

**Comment by audoban** [comment]
I do not like the version to be seen there.

**Comment by audoban** [comment]
That says in the last two buttons? If they are buttons to accept and cancel, we can remove them.

**Comment by psifidotos** [comment]
> I do not like the version to be seen there.

sorry, I dont agree. The version number is very important especially when users report bugs. We can make it not so disturbing if you want

> That says in the last two buttons? If they are buttons to accept and cancel, we can remove them.

add new dock, remove dock until we find the correct place for them...

**Comment by audoban** [comment]
> sorry, I dont agree. The version number is very important especially when users report bugs. We can make it not so disturbing if you want

But it is not good. Anything app of KDE show number of version on the ui config.
We need a about window, that is a correct place for number of version, web page, link for issues, etc.

**Comment by audoban** [comment]
We can use this [KAboutApplicationDialog](https://api.kde.org/frameworks/kxmlgui/html/classKAboutApplicationDialog.html), It is better to use KF5 tools

**Comment by psifidotos** [comment]
> We can use this KAboutApplicationDialog, It is better to use KF5 tools

To access it how ? through Right Click?

**Comment by audoban** [comment]
yes with rightclick

**Comment by psifidotos** [comment]
ok, when the about dialog is implemented and connected with right-click we can remove it

**Comment by psifidotos** [comment]
> Also I want to change the Double(Left|Right) for Fill because is more simple.

Do you prefer Fill or Justify? which is used at text editing?

**Comment by audoban** [comment]
Justify agrees more with the word Alignment

**Comment by psifidotos** [comment]
ok... Justify the...
