### ISSUE TITLE
Very rare previews do not disappear

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#260]
![spectacle w31919](https://cloud.githubusercontent.com/assets/24593950/23925134/211aeb74-090e-11e7-9df7-77eaacd985d2.png)
I do not know how and why it happened
then with a right click and everything is back to normal

**Comment by psifidotos** [comment]
Are you using qt 5.8? #183

**Comment by JenaPlinsky** [comment]
![spectacle ch3883](https://cloud.githubusercontent.com/assets/24593950/23935570/dbf7c5fa-094c-11e7-9797-3f708061c5f4.png)
just remember that in that occasion the dock did not want to hide

**Comment by psifidotos** [comment]
It is a bug from 5.8  but we could add also that when dock becomes hidden tooltips should become hidden also...

**Comment by JenaPlinsky** [comment]
Good idea !!!

**Comment by JenaPlinsky** [comment]
@psifidotos  please, watch [video](https://youtu.be/y3OpGAwMcaM) from minute 1:22 
Here, I'm able to reproduce the bug, which then led to the reporting just mentioned above
- It is replicable by following the mouse path
(For now, I've only tried on the Firefox task)
![spectacle ds9599](https://cloud.githubusercontent.com/assets/24593950/24070392/cc0fb1f8-0bbc-11e7-9f50-ebd7dc774604.png)

**Comment by psifidotos** [comment]
trying to replicate the behavior at 1:22 with the three konsoles in my system and I cant...

**Comment by JenaPlinsky** [comment]
- Does not depend on the task type (eg. Konsole) [video](https://youtu.be/EjgMXqBST9U)

- Initially I believed that this condition was caused by a right click on the icon ... but it is not so
This bug is reproducible, even with the only mouse hovering, between  tasks ....although it is not easy to replicate

**Comment by JenaPlinsky** [comment]
Here, as mentioned before, I was able to reproduce the bug starting from a different task and without any clicks [video](https://youtu.be/kB2qDi40WOw) (...from minute 0:35)

**Comment by JenaPlinsky** [comment]
Here the issue is more clear
[Vudeo](https://youtu.be/0Eqic6Zktcc)

**Comment by psifidotos** [comment]
@JenaPlinsky there are some fixes for previews in master, can you please test that still problem still exists?

**Comment by JenaPlinsky** [comment]
I think to have recorded the mouse pointer's movements  combined with a certain Latte configuration ....
- I've to recreate the Latte's conditions when I recorded the cursor
- then I put the mouse macros in play

**Comment by JenaPlinsky** [comment]
Well, I tested the dock ... more times with even disabling and then re-enabling the latest changes you've implemented on  tweaks tab
here it is the  [Bug tes](https://youtu.be/Z7P2olzTI78)

**Comment by psifidotos** [comment]
Nice!!! ;)
