### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by kmbilly** [psifidotos/Latte-Dock#261]
Got these messages and crash when starting in Fedora KDE plasma spin (Fedora 25, QT5), any advices for me to solve the problems? I really would like to use the dock:

[warning 9:27:42.907907] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 9:27:42.907907] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:46: TypeError: Cannot read property 'DateTime' of undefined
[warning 9:27:42.907907] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:47: TypeError: Cannot read property 'DateTime' of undefined
[warning 9:27:42.933933] - file:///usr/lib64/qt5/qml/QtQuick/Controls/TextArea.qml:941: TypeError: Cannot read property '__cursorHandle' of null
[warning 9:27:42.934934] - file:///usr/lib64/qt5/qml/QtQuick/Controls/TextArea.qml:905: TypeError: Cannot read property '__selectionHandle' of null
[warning 9:27:42.934934] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:350: TypeError: Cannot read property 'padding' of null
[warning 9:27:42.934934] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:351: TypeError: Cannot read property 'padding' of null
[warning 9:27:42.934934] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:352: TypeError: Cannot read property 'padding' of null
[warning 9:27:42.934934] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:353: TypeError: Cannot read property 'padding' of null
[warning 9:27:43.6565] - QObject(0x21740f0) ( QScreen(0x1d7a5a0, name="DP-1-2") ): Attempt to set a screen on a child window.
KCrash: Application 'latte-dock' crashing...
KCrash: Attempting to start /usr/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0

**Comment by psifidotos** [comment]
Use #147 for proper crash reports

1. Are you in multiscreen environment?
2. Are you using master or old 0.5.91 version packaged for distros?
3. Is this your first time using Latte?

**Comment by kmbilly** [comment]
![latte-dock-ddd-backtrace](https://cloud.githubusercontent.com/assets/822521/23937449/98cb298e-0992-11e7-83b1-23f6cdfb4f0d.jpg)

1. Yes, multiscreen
2. using master
3. Yes, first time

Thx a lot!

**Comment by psifidotos** [comment]
If you disable the multi screen environment, in single screen the crash remains?

**Comment by psifidotos** [comment]
I just kooked again...

You said you are using master, how do you use it?

The function adapttoscreen mentioned in your backtrace does not exist anymore in our master codebase

**Comment by kmbilly** [comment]
Sorry my fault, I'm using 0.5.91 before.
I use the master branch and try again, no crashing this time, but got a bottom bar with an error:

![screenshot_20170315_182707](https://cloud.githubusercontent.com/assets/822521/23944235/1148ecce-09ad-11e7-9f48-2ea9b4c82bd9.png)

The error message on the bottom bar is "file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:31:1: module "org.kde.latte" is not installed

Am I missing anything?

**Comment by psifidotos** [comment]
You can use #86

**Comment by kmbilly** [comment]
Thanks! It works, in my case, the files are wrongly installed under /usr/lib64/qml
