### ISSUE TITLE
Holes on tool-tips cross-fade

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#262]
[video](https://youtu.be/3axFUTZQpHE) ...frames sequence:
![vlcsnap-2017-03-15-02h47m00s099](https://cloud.githubusercontent.com/assets/24593950/23930089/6e92e980-092a-11e7-8999-01d1896b3318.png)
![vlcsnap-2017-03-15-02h47m19s537](https://cloud.githubusercontent.com/assets/24593950/23930090/700b21a6-092a-11e7-8ae0-601bf7b8441b.png)
![vlcsnap-2017-03-15-02h47m35s995](https://cloud.githubusercontent.com/assets/24593950/23930093/7400056a-092a-11e7-80fc-5c57293f3699.png)
![vlcsnap-2017-03-15-02h47m49s109](https://cloud.githubusercontent.com/assets/24593950/23930096/77301e28-092a-11e7-98cf-87c62b769a4c.png)
![vlcsnap-2017-03-15-02h47m59s140](https://cloud.githubusercontent.com/assets/24593950/23930100/7c76ddc2-092a-11e7-91ee-b08db03bf83e.png)
![vlcsnap-2017-03-15-02h48m15s446](https://cloud.githubusercontent.com/assets/24593950/23930122/a5e4e32a-092a-11e7-9959-20fcc01452e5.png)

**Comment by psifidotos** [comment]
This is normal ... when changing tasks the only way i found to show them properly is to make the window visible false and then fast to true again... otherwise, different previews are shown to diffferent tasks
