### ISSUE TITLE
Link to Kde store Latte plasma extension

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#263]
![spectacle sj4486](https://cloud.githubusercontent.com/assets/24593950/23936888/ca01e3dc-0954-11e7-9c21-94e8277f2c5f.png)
@psifidotos  with the ship of Latte 0.6 you might think to put a link to Latte on this page and declare Now.dock project as no longer supported

**Comment by psifidotos** [comment]
I know... :-) i am just waiting the official 0.6 release and announcement :-)
