### ISSUE TITLE
Custom dekstop launcher missing icon

### ISSUE THREAD

**Issue by SreckoM** [psifidotos/Latte-Dock#264]
When I 'pin' app that was launched using desktop launcher I made, I lose icon when I quit app. How can I fix that?
http://screencloud.net/v/lqlIF

**Comment by psifidotos** [comment]
this is a bug and havent been solved yet....

**Comment by psifidotos** [comment]
To confirm.... you mean that during removal anination that launcher is not showing correctly is that right?

**Comment by SreckoM** [comment]
So when I click Show Launcher When Not Running, and close that app, I lose icon. It happens for app for which I made desktop launchers.

**Comment by SreckoM** [comment]
When I start app again, app icon comes back.

**Comment by psifidotos** [comment]
@SreckoM  please check last updates in master if this is fixed for you...

**Comment by SreckoM** [comment]
Thanks I was using script I grabbed from omgubuntu, I executed it once more and it cloned and installed dock once more, but it is still same for me. I am on KDE Neon.

**Comment by psifidotos** [comment]
in such case... I am sorry but I can not reproduce... you must write down all the steps to reproduce this in detail... even how to create the launcher with the issue...

**Comment by SreckoM** [comment]
Thanks for your help. Pls check this gif https://drive.google.com/open?id=0Byw1djo6arb3SFNDOEdDX3JrdzQ

**Comment by psifidotos** [comment]
1. upload here this desktop file to give a glance

2. check that this doesnt happen with plasma icon only taskmanager

**Comment by SreckoM** [comment]
1. Attached desktop file
[Blender2.78b.zip](https://github.com/psifidotos/Latte-Dock/files/845843/Blender2.78b.zip)
2. It works with plasma task manager. http://screencloud.net/v/4JiBj Also works as widget icon too.

**Comment by psifidotos** [comment]
and this file please:

/home/srecko/Applications/blender-2.78b-linux-glibc219-x86_64/icons/48x48/apps/blender.png

**Comment by SreckoM** [comment]
![blender](https://cloud.githubusercontent.com/assets/2272022/23968400/db5adca6-09c2-11e7-8906-a07621277647.png)

**Comment by psifidotos** [comment]
you could also replace at your desktop file, the line concerning the icon to ;

Icon=blender

do you want the specific icon ?

**Comment by psifidotos** [comment]
you have the same issue with other launchers also ?

**Comment by psifidotos** [comment]
in my system this is what is happening... libtaskmanager is not grouping together the launcher and the app

![image](https://cloud.githubusercontent.com/assets/2216474/23969959/f3d7c20e-09d0-11e7-9b28-6343e9a87200.png)

**Comment by TheGitJay** [comment]
I can confirm, having the exact same issue on KDE 5.10.2, it only happens with some apps not all. 

for example if I pin Kmail to the dock, when the app is actually open the icon is visible, but once the app is closed all that remains is a blank placeholder icon

its just a blender problem, see attached
![screenshot_20170623_204744](https://user-images.githubusercontent.com/26307740/27498173-be420590-5855-11e7-8842-8282d4893302.png)

**Comment by psifidotos** [comment]
what latte version are you using?

**Comment by Dariasteam** [comment]
Same on antergos lattedock 0.6.2

**Comment by psifidotos** [comment]
has been fixed in master... in master we show exactly the same icons with plasma taskmanagers

**Comment by Dariasteam** [comment]
my fault for not compiling it, sorry
