### ISSUE TITLE
Global shortcuts for mpris triggered twice

### ISSUE THREAD

**Issue by DemaroStanberry** [psifidotos/Latte-Dock#265]
Whenever Latte is active (I've only tested this with a single dock instance) media shortcuts, i.e. play/pause, next.. are triggered twice.

**Comment by psifidotos** [comment]
do you use also plasma panels?

**Comment by DemaroStanberry** [comment]
Yes, empty panel containing system tray > media player activated

**Comment by psifidotos** [comment]
If you remove the plasma panel is this happening also?

From Latte you could add from configuration window "Add" a second dock to replicate exactly the plasma panel if you want...

**Comment by DemaroStanberry** [comment]
1. If the plasma panel is removed then the media player plasmoid isn't around to listen to global events.. the key strokes do nothing.

2. Replacing the plasma panel with a latte dock to host the plasmoid works out just fine. Global shortcuts work as expected.

**Comment by psifidotos** [comment]
> Replacing the plasma panel with a latte dock to host the plasmoid works out just fine. Global shortcuts work as expected.

I suppose then this is ok... right? did you manage to make the second dock to look and behave exactly as the plasma one?

**Comment by DemaroStanberry** [comment]
It works for the time being as a workaround.. The look and feel is 'close' to what I was able to achieve with the plasma panel. There are a couple things amiss such as no longer being able to open the application launcher using the meta key (Alt+F1 was used as the key binding). That being said it's not a deal breaker. 

However, I do think that it's not unreasonable to expect latte users to also employ a plasma panel elsewhere..

**Comment by psifidotos** [comment]
> It works for the time being as a workaround.. The look and feel is 'close' to what I was able to achieve with the plasma panel. There are a couple things amiss such as no longer being able to open the application launcher using the meta key (Alt+F1 was used as the key binding). That being said it's not a deal breaker.

this is supported but it requires from you to adjust the kwinrc file.... #102 and it doesnt require from you to set Alt+F1 for the apps launcher...

> However, I do think that it's not unreasonable to expect latte users to also employ a plasma panel elsewhere..

Latte is just using the default behaviors... Latte can not interfer with how systray is working internally...

**Comment by psifidotos** [comment]
> It works for the time being as a workaround.. The look and feel is 'close' to what I was able to achieve with the plasma panel. 

concerning also this, you could upload here two screenshots, one of latte and one of plasma panel to see what is missing in order to be almost perfect close...
