### ISSUE TITLE
Usability feature request: unlock/lock plasma widgets and add widgets submenu on (right click) latte panel ?

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#267]
That's perhaps a minor usability feature request:

Most of the times I have my desktop full of windows and then at some point I want to install, update, add, test, or try a widget.

I think usability might be improved if a plasma submenu would be added with those two options (unlock/lock plasma desktop and add widgets).

Right now I need to either show desktop (or move to another one, or minimizeAll windows) first, then right click on the desktop to do it. 

With that feature one would be able to do it directly from the latte panel (right click) as one does in plasma panels.

**Comment by psifidotos** [comment]
unfortunately by design plasma does not expose this functionality...

All the patches I have sent for this were rejected....

**Comment by kupiqu** [comment]
That's unfortunate...

**Comment by psifidotos** [comment]
Personally i work only with latte panels and plasma is always at unlocked state... works just fine for me... to add, my screen bottom left corner is showing my desktop
