### ISSUE TITLE
The fork of IconItem is a ready for use.

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#27]
https://github.com/psifidotos/Latte-Dock/blob/master/app/iconitem.h

**Comment by psifidotos** [comment]
unfortunately this is not the place to be...

this must go into the liblattedockplugin because it is going to be used by the Latte plasmoid

after that I will give it a ride!!!!

**Comment by audoban** [comment]
> this must go into the liblattedockplugin because it is going to be used by the Latte plasmoid

OK not problem, we can move this class to liblatteplugin.

**Comment by psifidotos** [comment]
I created branch iconitem. I moved iconitem into the plugin and used it for the plasmoid...

Even though it feels lighter I think, the memory usage looks the same to me

**Comment by audoban** [comment]
> Even though it feels lighter I think, the memory usage looks the same to me

Apparently yes, but I remenber that when I use KIconItem on Candil dock the use of memory It increase to 100 mb. But with the fork increase to 70 mb. I don't know, but at least Icon Item does not create as many Warning in logs.

**Comment by psifidotos** [comment]
we will keep your implementation and wait for user feedback...

Let's be ready for this from users... :)
