### ISSUE TITLE
Adding blur to Latte Dock in all cases for the panel background

### ISSUE THREAD

**Issue by chameleoon** [psifidotos/Latte-Dock#270]
First , just wanna say that you guys done a great job and I'm liking it, thanks for your work!
P.S: english is not my native so expect typo`s or grammatical errors.

Currently I'm trying to copy my XFCE desktop visual modifications over to KDE (which I must say: I love it), everything goes very well since KDE is so good for customizing, just one thing that's bothering me for 2 days is my blurred plank from XFCE using compiz it was a smooth process but with kwin and latte it's a different story, without further ado here's my result so far:

![screenshot_20170316_235936](https://cloud.githubusercontent.com/assets/11075833/24020423/c47a70fe-0aa4-11e7-9286-1225d20d5cb6.png)

I tried editing the source files , I`m a web developer...so no success there (just a little frustration).
So how can I make the dock container the size of the actual background so the blur applies correctly?

**Comment by Petross404** [comment]
From Latte Settings -> Appereance , set `Length` slider to whatever value you need. That is a "static" workaround. Maybe the devs know a way to _dynamically_ change (on the fly), based on the tasks that are shown on the dock.

**Comment by psifidotos** [comment]
Latte applies blur only on the docks that have been set as, "Always Visible, Fill alignment, zoom:1, backround:100℅"

**Comment by chameleoon** [comment]
@Petross404 Thanks, I know about that setting, the problem is that it adds about 5px above the panel of blank space...and the blur goes out of it kind of.

@psifidotos Thank you for the quick reply, I'll try your suggestion and see what I get out of it, but there is no way to remove the extra ~5px around the panel of transparent padding/margin/thickness or whatever that is?

**Comment by psifidotos** [comment]
With the mentioned dock you wont have that issue... and you dont need xprop to enable it ... the thing is that because of your comment i just saw that both blur and background contrast effects from kwin provide a qregion setting...

I might be able to enable it the next days on master for all cases...

**Comment by chameleoon** [comment]
Well the effect is pretty,  the only problem is that it forces me to a always show/full width dock ... which is not my favorite, anyways maybe you'll think of offering an option for those obsessed with consistency and customization like myself.

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/24049098/9b625a44-0b33-11e7-99f2-194ccb0d0cc6.png)

**Comment by psifidotos** [comment]
what you see here....

A Latte top dock always visible with full capabilities for snapping etc... and a Latte left dock, dodge active with zoom capabilities and of course both with full, correct blur ;)

we should all thank Martin from kwin for the eassiness in supporting blur and background contrast effects... The blurred area is computed even at a pixel density meaning even correct rounded corners!!!

Enjoy and have fun!!! ;)

@chameleoon forget xprop etc... this works out of the box in all cases... ;)

![spectacle e16176](https://cloud.githubusercontent.com/assets/2216474/24049432/a2762efe-0b34-11e7-9791-5182baa0da8d.png)

**Comment by psifidotos** [comment]
I forgot to mention of course... that the left dock in auto positioned from Latte!!! :) the user doesnt have to configure anything except to set it as Left Edge, Top Alignment ....

**Comment by chameleoon** [comment]
This is awesome!!!

Buuut I have a problem:
 - when the dock is hidden I get a weird full width panel with transparency but no blur
 - when I get the dock out using my mouse the panel gets blurred
P.S: I've used git pull and ./install.sh to update, should I do a full reinstall?

![screenshot_20170317_222521](https://cloud.githubusercontent.com/assets/11075833/24061610/c20f37ca-0b60-11e7-83ff-9c052e5d426c.png)
![screenshot_20170317_222537](https://cloud.githubusercontent.com/assets/11075833/24061613/c5d77a5c-0b60-11e7-8b3c-7db8ae256c94.png)

**Comment by psifidotos** [comment]
1. Can you please try to delete build directory and run install script again please?

2. Is this also occurs when you have zoom factor above 20%?

3. Can you run latte-dock -d --with-window and take a screenshot of the debug window when this problem occurs?

**Comment by psifidotos** [comment]
Also  i am almost sure that what you see is the background contrast effect kwin, you can disable it from plasma systemsetting to be sure that this is the case...

**Comment by chameleoon** [comment]
Yep, it was the background contrast - silly me, thanks again for your great work! Greatly appreciate it!

**Comment by psifidotos** [comment]
the this thing is that we support background contrast effect... so this shouldnt occur and I cant reproduce...

**Comment by chameleoon** [comment]
1. same
2. yes
3. http://pastebin.com/6gYtKZva
4. I've disabled kwin's background contrast effect and the large whiteish panel disappeared but the blur is still affecting 100% width of the screen

**Comment by chameleoon** [comment]
Also a screenshot:
![screenshot_20170317_233047](https://cloud.githubusercontent.com/assets/11075833/24063787/c89ce00c-0b69-11e7-85ec-f9faa48ef14a.png)

**Comment by psifidotos** [comment]
@chameleoon the debug window looks ok... I added an effectsArea record in the debug window which should be updated correctly when hovering the dock or becoming hidden... Can you make one more screenshot with the new debug window from master?

**Comment by chameleoon** [comment]
Hey, sorry for the delay, here's the ss:
![screenshot_20170318_005507](https://cloud.githubusercontent.com/assets/11075833/24065668/98bf615a-0b75-11e7-901e-e33e7f7f7c17.png)

**Comment by psifidotos** [comment]
so strange... effects area has good numbers... 

can please also try a different plasma theme? e.g Breeze ?

**Comment by chameleoon** [comment]
Ok...just found out the problem, it`s the kwin blur effect, but if I disable it I loose all blur effects on my top panel etc.
I`ll search for a method to exclude latte-dock from kwin's blur effect.

**Comment by psifidotos** [comment]
> I`ll search for a method to exclude latte-dock from kwin's blur effect.

latte is using kwin's blur effect for the blur... disabling it wont make any difference...

**Comment by chameleoon** [comment]
Well then that's just weird, I've also installed a fresh environment in VirtualBox and getting the same results... I'll try with 5.8 too...maybe it's a 5.9 problem?

**Comment by psifidotos** [comment]
I am using 5.9 and I dont have that issue.... did you try a different theme?

**Comment by chameleoon** [comment]
yes, it's the same with all themes

**Comment by psifidotos** [comment]
are you using open source graphic drivers or proprietary?

**Comment by chameleoon** [comment]
proprietary - NVIDIA

**Comment by psifidotos** [comment]
could that be ? I dont know... can you use irc ?

**Comment by chameleoon** [comment]
skype?

**Comment by psifidotos** [comment]
ok... let's text at skype... login: psifidotos

**Comment by yohanespradono** [comment]
any solution for this issue guys? I also don't get that blur on the dock despite the latte setting window is blurred.

**Comment by psifidotos** [comment]
we didnt know we had that issue... what Latte version are you using ?

**Comment by psifidotos** [comment]
send also a screenshot of Latte

**Comment by yohanespradono** [comment]
sorry, i installed the .deb version 0.6.0. i removed it and reinstalled using source from the repo. and the blur is now working after i set the opacity. 
Pls ignore my comments. Thx so much!
