### ISSUE TITLE
Latte blocks PlayPause-Key

### ISSUE THREAD

**Issue by LinusCDE98** [psifidotos/Latte-Dock#271]
When I press this Key (keycode 172, XF86AudioPlay). The dock seems to press it instantly again, to revoke the event.
It occurs only when I have Latte-Dock running.

**Comment by psifidotos** [comment]
are you using a plasma panel also ? this is probably because you are using now running in the systray...

you can always substiture your plasma panel with a latte one...

**Comment by LinusCDE98** [comment]
Thank you. It worked when I remove the 'Now Running'-Systrayicon, 'Media Player Compact' and restartet plasmashell.
I now have no more troubles, but it would be nice to add a Feature to disable the MediaPlayer-Functions of Latte for that case since I used 'Media Player Compact' to view my current song.

**Comment by psifidotos** [comment]
> but it would be nice to add a Feature to disable the MediaPlayer-Functions of Latte 

unfortunately I dont know a way to do that yet...

>  I used 'Media Player Compact' to view my current song.

why dont you add that plasmoid in Latte ?

**Comment by LinusCDE98** [comment]
> unfortunately I dont know a way to do that yet...
Ok, no problem than.
> why dont you add that plasmoid in Latte ?
I've done it now. Thanks for your advice. This Dock is also more suitable as a Panel than the default Plasma-Panel.

**Comment by psifidotos** [comment]
> I've done it now. Thanks for your advice. This Dock is also more suitable as a Panel than the default Plasma-Panel.

thanks!!! :)
