### ISSUE TITLE
Multiscreen support

### ISSUE THREAD

**Issue by quarckster** [psifidotos/Latte-Dock#273]
In version 0.5.91 it's not possible to create a dock in another display.

**Comment by JenaPlinsky** [comment]
I think this is supported for version 0.6 ..that should be already ready (maybe in a few days)
if you want to test the latest version ... 

**Q**: How can I install from the current master branch ?

**A**: You can easily, download and instal from the last master branch by running a script with commands:

- git clone https://github.com/psifidotos/Latte-Dock.git
- cd Latte-Dock
- sh install.sh The last command might ask for your root password, just before installing.

**Comment by psifidotos** [comment]
multi-screen is working very good in master ....

**Comment by JenaPlinsky** [comment]
multi-screen support #12

[Release 0.6](https://github.com/psifidotos/Latte-Dock/milestone/1?closed=1)
I am convinced that any suggestions and bug reports are appreciated by developers
