### ISSUE TITLE
How to reproduce mouse movements and events to test behaviors, difficult to reproduce

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#274]
[xdotool](http://tuxradar.com/content/xdotool-script-your-mouse)
example:
```
Ivan@UltrabookSamsung:~> xdotool mousemove 1000 768 \
> xdotool sleep 1 \
> xdotool mousemove 1001 768 \
> xdotool sleep 1 \
> xdotool mousemove 1002 768 \
> xdotool sleep 1 \
> xdotool mousemove 1003 768
```

@psifidotos It may aid a script like this, to reproduce the bug #260
maybe by using relative coordinates ?

**Comment by psifidotos** [comment]
@JenaPlinsky I dont know

**Comment by JenaPlinsky** [comment]
@psifidotos 
With Xnee automate testing tool, I can now to systematically replicate the same bug
[openSUSE search](https://software.opensuse.org/search) : xnee 

- to rec:
`cnee --record --mouse  -o test.xnee`

- to play:
`cnee -rep -f test.xnee`

**Comment by psifidotos** [comment]
so how we will use it?

**Comment by JenaPlinsky** [comment]
Only to test a possible solutions, as this bug is difficult to replicate (at least for me I mean)

**Comment by JenaPlinsky** [comment]
Are you  able to replicate the bug ? or it only occurs to me

**Comment by psifidotos** [comment]
I havent reproduced this yet...

**Comment by Petross404** [comment]
Why don't you wait until one or two more users configure this?

**Comment by psifidotos** [comment]
@Petross404 what do you mean?

**Comment by Petross404** [comment]
@psifidotos Yes, you are right. I thought you are talking about a specific bug.

**Comment by psifidotos** [comment]
If I remember correctly this was related for a previews issues... and in general this hasnt helped us in reproducing bugs...
