### ISSUE TITLE
minor visual thing: shadow between two latte panels depends on focus

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#275]
what follows is very minor visual thing, but anyways...

please see the screenshots:

focus on vertical panel:
![image](https://cloud.githubusercontent.com/assets/3875196/24071897/36738196-0bb3-11e7-9980-f0534ffd6d68.png)

focus on horizontal panel:
![image](https://cloud.githubusercontent.com/assets/3875196/24071914/4eb1379e-0bb3-11e7-9182-1433608621cd.png)

the shadow that separates the two panels only appears when focus is on the horizontal panel, but not when on the vertical.

not sure which one should be preferred but I'd prefer a consistent view independent of which panel is on focus.

**Comment by psifidotos** [comment]
this is a lot harder than it sounds...

**Comment by kupiqu** [comment]
I thought that could be the case. Then, don't worry, it's not just a minor thing...

**Comment by psifidotos** [comment]
@kupiqu there is way to achieve always the first case...

you can make the left dock to not draw the shadows externally...
this can be done for example by setting its zoom factor to 5% or settings panel background to 95%

**Comment by kupiqu** [comment]
Neither of these options does not seem to work for me... 

If they would work, I would use the second one better, as I prefer no zoom.

**Comment by psifidotos** [comment]
@kupiqu you can try again but both dock must be set at Always Visible, the other settings dont matter... top dock gained above priority in such case...

**Comment by kupiqu** [comment]
Works great, thanks!!

**Comment by psifidotos** [comment]
@kupiqu I added also #277 which gives a way for the user to lower left and right docks for all visibility modes.... ;)

**Comment by kupiqu** [comment]
Cool!
