### ISSUE TITLE
YaST2 and Latte

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#276]
How can I use YaST2 without uninstalling Latte ?
![screenshot_20170318_180103](https://cloud.githubusercontent.com/assets/24593950/24074262/87bcf1d4-0c05-11e7-97d2-219f3dd279de.png)

**Comment by psifidotos** [comment]
These are from an old latte installation, right? 

As long as you install from master you can do the following, uninstall it with yast2, and afterwards install it again with the install script... yast will not show you this error afterwards...

**Comment by JenaPlinsky** [comment]
Thanks @psifidotos I'll do so
