### ISSUE TITLE
[Help] - Video to add/move launchers properly

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#278]
Please I would like someone to create a video for newcomers how to add launchers properly in Latte...

1. the video should show drag n drops of apps inside the taskmanager not outside as applets

2. the video must demonstrate how to move them with drag n' drop

3. after that should drag n drop some widgets from plasma widgets explorer

4. should demonstrate how to move this applets

the video doesnt have to be big....

**Comment by psifidotos** [comment]
Something like: https://www.youtube.com/watch?v=8LE250L12_c

but with better quality... :) unfortunately my computer is old...

**Comment by JenaPlinsky** [comment]
[Video 1](https://youtu.be/z-rTd5KAD7c)

**Comment by psifidotos** [comment]
I used an ffmpeg command but unfortunately my computer is very old to support it properly....

**Comment by BigDaddyonTech** [comment]
@psifidotos I would be happy to make one up. I am heading to work right now. Maybe I can get it done tomorrow.

**Comment by psifidotos** [comment]
@BigDaddyonTech thank you very much!!! This would help many new users!!! :)

**Comment by JenaPlinsky** [comment]
@psifidotos  
[Video Demo](https://youtu.be/VSEA0CppJ5A)

**Comment by psifidotos** [comment]
@JenaPlinsky  nice video!! :)

**Comment by BigDaddyonTech** [comment]
@psifidotos Do you have or use Telegram?

**Comment by BigDaddyonTech** [comment]
Let me know if this is what you were looking for. 
https://www.youtube.com/edit?o=U&video_id=2AzCvs2NhTM
I can also do one for you without me in it or anything to do with my channel and you can upload it somewhere if you like. 
Just let me know

**Comment by psifidotos** [comment]
> @psifidotos Do you have or use Telegram?

yes, username: psifidotos

**Comment by psifidotos** [comment]
> https://www.youtube.com/edit?o=U&video_id=2AzCvs2NhTM

this link doesnt work for me...

**Comment by BigDaddyonTech** [comment]
https://www.youtube.com/watch?v=2AzCvs2NhTM
Sorry my bad
Try this one

**Comment by psifidotos** [comment]
thank you every one!!! :)
