### ISSUE TITLE
Launcher disappears a second then reappears when run.

### ISSUE THREAD

**Issue by sic-f** [psifidotos/Latte-Dock#279]
I think this is similar to this in the FAQ:

> Q: I set Animations to "None", but when clicking on an launcher it's icon is momentarily disappeared.

> A: This bug is already fixed in current master and will be included in the next (0.6.0) release. So all you have to do is git pull the latest changes of master, or wait for the next stable version if you like so.

But is still happening in my distro, KDE Neon 5.8.6.

Setting Animations to "None" fixes it but nobody sets it to none anyway.

**Comment by psifidotos** [comment]
#72, if you are a programmer you can help the plasma devs fix this for libtaskmanager

**Comment by psifidotos** [comment]
found a fix for this, it is in master!!!

**Comment by sic-f** [comment]
cool!
