### ISSUE TITLE
Disappeared kwrite's Icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#282]
I seem to remember that I had opened more than kwrite processes
and then this happened by closing one of them

![screenshot_20170319_152725](https://cloud.githubusercontent.com/assets/24593950/24082778/5096fcd8-0ccb-11e7-91e6-495cd5f5c25b.png)

**Comment by psifidotos** [comment]
so strange...

**Comment by JenaPlinsky** [comment]
few time ago, I could run ddd with a single command...
now it does not work .... you know where I'm wrong?
maybe I can replicate the problem, and I'd like send you both the backtrace that the debug windows
`ddd -gdb --debugger latte-dock --debug --with-window --graphics --mask`
or
`ddd -x -gdb --debugger latte-dock --debug --with-window --graphics --mask`

**Comment by psifidotos** [comment]
- I never succeed in showing debug messages when I run latte with ddd

- the backtrace has meaning only when the application crash

**Comment by JenaPlinsky** [comment]
I also get a crash working on that situation

**Comment by psifidotos** [comment]
send it

**Comment by JenaPlinsky** [comment]
Here it is the [video bug](https://youtu.be/fzCzwSmrE2g )
now I'm going to cath the crash

**Comment by JenaPlinsky** [comment]
it also happened, again in visibility mode = **always visible**
- Top dock works properly, while...
- bottom dock is **hidden** and appears only to during the desktop change

**Comment by psifidotos** [comment]
Please test again for the crash because latest commits may help...

**Comment by JenaPlinsky** [comment]
I'm sorry it reoccurs

**Comment by psifidotos** [comment]
How can i replicate the icon disappear?

**Comment by JenaPlinsky** [comment]
@psifidotos  did you see the video in the previous comment just above the screenshot?

**Comment by audoban** [comment]
So strange, @psifidotos do you think that the bug is related with LatteIconItem or with libtaskmanager?

**Comment by psifidotos** [comment]
This must be our side...

an update for firefox latteiconitem is not trigerred properly, i have touched some things at latteiconitem and qml iconitem.

The reason of the changes were that libtaskmanager touches its model before delayremoval has ended.

This could be a case that the new implementation doesnt take into account a corner case

**Comment by psifidotos** [comment]
I have to replicate it in my sysyem first to see what is happening...

**Comment by audoban** [comment]
@psifidotos I see it, then probably latteIconItem doesn't paint sometimes.

**Comment by JenaPlinsky** [comment]
guys, how good, can you fix everything !!! amazing
