### ISSUE TITLE
**fuzy** string on po files could make discard some translation strings

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#286]
Update de.po #284
Update it.po #240
**fuzy** string on po files could make discard some translation strings

the issue is already known ... this is supposed to be a call for a revision of the translations

**Comment by omni6** [comment]
ok will build and look if everything fits. looking the .po file isn always clear ;) need a few mins

**Comment by omni6** [comment]
ok revised everything. looks fine so far. due the changes by @audobahn, are you able to merge or have i to reset my git and redo my changes?

**Comment by JenaPlinsky** [comment]
sorry I'm not able :(

**Comment by omni6** [comment]
ok try now

**Comment by psifidotos** [comment]
proper way for translations is to use Lokalize... fuzzy strings mean that need authoring from the translators
