### ISSUE TITLE
Wrong animation during the transition between applets and the task manager

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#287]
Wrong animation during the transition between applets and the task manager

**Comment by psifidotos** [comment]
show me

**Comment by JenaPlinsky** [comment]
[video](https://youtu.be/SWfi0vRlm5E)
near the edge between the containers applets and task-manager happen this...
once the cursor goes beyond the central axis of the applet's icon, the first task manager's icon, should start to slowly rise 
...instead, happens that its rise, coincides exactly the white plasmoid separator and having lost time to half of the applet's icon, this last, rise sharply

**Comment by audoban** [comment]
@JenaPlinsky  What is the name of plasmoid and where can I download it?

**Comment by psifidotos** [comment]
Remove the separator or lock it... there is no other way... the width of the separator is very narrow to support smooth animation in that case...

**Comment by JenaPlinsky** [comment]
Shit !!! l ... I can confirm !!! .... The cause, it was the "separator" plasmoid ... I would have never imagined

**Comment by audoban** [comment]
@psifidotos I imagined that was it.

**Comment by JenaPlinsky** [comment]
@audoban is there a way, for future releases, to fix this issue with separator plasmoid ? or "separator"  will be this, definitely considered deprecated" ?

**Comment by psifidotos** [comment]
I dont know any way yet to solve this
