### ISSUE TITLE
Adding applets and launchers differentiate their behavior

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#288]
Currently, it can happen accidentally add launchers in the area reserved for applets, can you avoid this?
...and same thing, as regards the task -manager ...You Should prohibit The Possibility of adding applets there.

It **would** be a big improvement for the user experience I think
and although Latte is in feature freeze, I suppose, it **would** be important to make an exception for the upcoming release 0.6

- Applets container 
    - good       [ applets + folders ]
    - no-good  [ desktop-launchers + files ]  
          ...files and folders should only be passed as a parameter for the folderview, if dragged on 
folderview
![screenshot_20170320_073310](https://cloud.githubusercontent.com/assets/24593950/24090374/dc86486a-0d3f-11e7-91a7-c6ad97bc95ee.png)
![screenshot_20170320_073840](https://cloud.githubusercontent.com/assets/24593950/24090418/48e6110c-0d40-11e7-94a9-fe5ab8342531.png)

- Task-manage rcontainer
    - good       [ desktop-launchers + folder ]
    - no-good   [ applets + files ] 
           ...files should only be passed as a parameter for the launcher
![screenshot_20170320_073126](https://cloud.githubusercontent.com/assets/24593950/24090364/caf86934-0d3f-11e7-9663-dc90588dee95.png)

**Comment by audoban** [comment]
I'm not really aware but there are some limitations and design decisions that have been discussed with us a long time ago.

> You Should prohibit The Possibility of adding applets there.
@psifidotos is possible avoid drag and of plasmoids over the latte-plasmoid? 

> no-good [ desktop-launchers + files ]
I remember that this had been discussed but we had come to the conclusion that both must be supported.

> good [ desktop-launchers + folder ]
Actually the libtaskmanager doesn't support folders, @psifidotos Can you confirm this?

> no-good [ applets + files ]
...files should only be passed as a parameter for the launcher

Why? There may be plasmoids that need it.

**Comment by psifidotos** [comment]
libtaskmanager doesnt support folder or applets... disabling the launchers outside the taskmanager is not the road to go... there maybe users that want them to be placed far from task manager

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/24118791/accdecb8-0db7-11e7-9eb3-a02aa3549a4a.png)

**Comment by JenaPlinsky** [comment]
@psifidotos  @audoban ...moving a launcher, which is already present in the task manager does not make sense ... you might think to intervene even in this circumstance to inhibit the add function
![spectacle j27278](https://cloud.githubusercontent.com/assets/24593950/24121551/f10a3be2-0db8-11e7-8226-a0ea571d5906.png)

**Comment by psifidotos** [comment]
You mean to not show visual when launcher already present ? 

Your screenshot isnt showing a launcher but a folder...

**Comment by JenaPlinsky** [comment]
As observed might be subjective ... what do you think about this ?
- launchers container
         - add a launcher, which is already present in the task manager does not make sense
         - add a folder with the dolphin launcher already present it does not make sense

- Applet container
         - add applets that already exist on the applet container, does not make sense to me at least ....
         - add more than one folder view is useful and wise
         - add 2 or more folder view with the same "path" does not make sense

**Comment by psifidotos** [comment]
> add a launcher, which is already present in the task manager does not make sense

it may does not but on the other hand I prefer it that way because if nothing is shown then the user might believe that it would be better to add it as an applet

> add a folder with the dolphin launcher already present it does not make sense

it does, dolphin opens that folder

> add applets that already exist on the applet container, does not make sense to me at least ...

I use a dock with three different active window controls in order to provide the best experience for me...

> - add 2 or more folder view with the same "path" does not make sense

it may does not but I dont understand why it should prohibited

-----

I think that with the latest commits, this situation has been improved a lot

**Comment by JenaPlinsky** [comment]
Yess I like it !!!! really well done
although, I think, make the dock,even more intelligent at the end  would result very practical ..... Would be, the dock itself, to indicating the right way  to do things .... mine wants to be a personal opinion I know ... .

...add smart option in the tweaks ... Do you ever, took it into account?
"Totally free add behavior" or "smart add"

**Comment by psifidotos** [comment]
That is good idea now that Latte can understands launchers, plasmoids...

I will add a choice "Add launchers in the taskmanager" in Tweaks which will be enabled by default. So all launchers will be added in the taskmanager by default...

@audoban, i think this is the best to do...

**Comment by JenaPlinsky** [comment]
@psifidotos @audoban ...since the question can be confusing, I took the liberty of doing an overview to verify the behavior of the latest implementations

- Applets container 
    - good 
            plasmoids/applets    - ok addable
            folders                      - ok addable
            files as parameter    - ok addable
            folder as parameter - ok addable
    - no-good  
            duplicates               - wrong is addable (except for the folders for which duplicates are allowed)
                                             more folder with the same "path" does not make sense
            desktop launchers  - ok not addable (no message, when hovering folder-view)
            files as applet         - wrong is addable

- Task-manager container
    - good  
            desktop-launchers    - ok addable
            folder as launcher     - wrong is not addable ( for a moment it is addable )
            files as parameter     - ok addable ( for a moment it is addable as launcher )
    - no-good 
            duplicates                 - wrong is addable
            plasmoids/applets     - ok not addable
            folder as parameter  - wrong is addable
            files as launcher       - is not addable ....I don't know if it make sense ( for a moment it is addable )

**Comment by JenaPlinsky** [comment]
Nice !!! ...perfect solution ;)

**Comment by JenaPlinsky** [comment]
@psifidotos 

**Dragging a launcher:**
Does It makes sense to allow the movement of launchers in folderview applet? ... maybe or maybe not
in any case, the suggestion "launchers'area" should be visible even in these cases

![screenshot_20170324_233945](https://cloud.githubusercontent.com/assets/24593950/24316171/41b27d80-10ec-11e7-8b44-6ae00e24e572.png)

**Dragging a link:**
Is feasable get the same result for the launchers link?
I mean, is it possible to interpret if a link refers to a file or to a launcher?
![screenshot_20170324_234122](https://cloud.githubusercontent.com/assets/24593950/24316145/15385a2c-10ec-11e7-98cd-119fcc88b6e2.png)

**Comment by psifidotos** [comment]
> Does It makes sense to allow the movement of launchers in folderview applet? ... maybe or maybe not

upstream behavior, Latte is not responsible

> in any case, the suggestion "launchers'area" should be visible even in these cases

sorry not possible... you will lose the hover effect again and the spring anination of the folderview

> Is feasable get the same result for the launchers link? 

Do you mean for the applets? I will check but i think is not possible with the current implementation

**Comment by psifidotos** [comment]
> > in any case, the suggestion "launchers'area" should be visible even in these cases

> sorry not possible... you will lose the hover effect again and the spring anination of the folderview

I just checked...  a lot messier... the reason that doesnt work is that this applets they have their own DropArea and use for their specific use cases...
