### ISSUE TITLE
"Add Widget" item onto the Latte's context menu

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#289]
It may be convenient, add the entry "add widget" to the Latte's context menu
just as in the default task manager

in this way, it would be possible to add objects simply by double clicking on the plasmoid in the widget explorer

**Comment by audoban** [comment]
The problem with this is that we can not tell plasma that show the widgets browser, we have to do our implementation.

However is easy add the widget explorer.

The only thing that worries me is that this can increase the use of RAM. @psifidotos What do you think about this?

**Comment by psifidotos** [comment]
Only if we test it we will know, it could be also like the settings window that is removed on closing and frees most of its resources... but i dont think this can catch up 0.6 release

**Comment by audoban** [comment]
@psifidotos  yep, another release

**Comment by psifidotos** [comment]
as long as there isnt any big interest in alternative desktop environments, I am closing this...

**Comment by psifidotos** [comment]
by fixing #441, we can now activate the plasma widgets explorer from our app (this was introduced in plasma 5.9, before was not possible)

![image](https://cloud.githubusercontent.com/assets/2216474/25640055/c8ab1ba8-2f96-11e7-9d52-5da94d80a491.png)

**Comment by MarianArlt** [comment]
KDE Plasma 5.9.5 here. KDE Framework 5.34.0. Qt 5.7.1 OS KDE Neon
Adding Widgets won't work at all for me. Actually I'm having issues with adding a self created widget to a system panel. Might be an issue with Plasma?

**Comment by psifidotos** [comment]
> Actually I'm having issues with adding a self created widget to a system panel.

I dont understand the statement.

If you use "Add Widgets" by right clicking on the desktop, does the widgets explorer appearing on the left ?

**Comment by MarianArlt** [comment]
Sorry I'll try to be more specific and not bother you with other issues I have. Yes sir, the widget explorer functions like expected, which really only means it shows up. I can add widgets to the desktop and Plasma panels. I can not add widgets to Latte Dock with this menu entry. I just can double click the widgets all day long, they won't get added to the dock. Reading your comment I suppose you are not experiencing this behaviour? Is there any way I could debug this?

**Comment by psifidotos** [comment]
They are not added through double click, you must drag n' drop them into the Latte Dock...

You should see a rectangle indicator with a  "+" symbol in it when hovering the Latte dock by dragging a widget onto the dock, Just try to move your mouse a little left or right to the dock to appear...

**Comment by MarianArlt** [comment]
Oh. One is very used to the double click Plasma behaviour. Sorry for that. Is that documented? Did I miss this? Sorry for the inconvenience!

**Comment by psifidotos** [comment]
no worries, https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-how-can-i-add-applets
