### ISSUE TITLE
RELEASE AND TRANSLATORS

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#290]
The launch date for latte has been moved for March 24, from the day 22 can update their translations.
We promise not to touch the strings, have three days to update their po files if you wish.

On Friday there will be no changes in the code and we will dedicate to prepare the launch.

**Thank you all for your translations.**

**Comment by psifidotos** [comment]
Ok... the translation strings are updated... 

just to inform: on Friday 24th we will try to make a string freeze, that means that no translatable strings will be changed from our side..

that means of course that we accept translations all the time!!!now... in beta stage... after the release etc...

**Comment by JenaPlinsky** [comment]
@psifidotos  @audoban Guys, I just updated the translations from the master branch downloaded one hour ago 
how can I upload the file to  ?

**Comment by psifidotos** [comment]
You must make a pull request

**Comment by psifidotos** [comment]
Concerning translators, there are new strings also at plasmoid and containment!!

**Comment by JenaPlinsky** [comment]
and then
![spectacle k14544](https://cloud.githubusercontent.com/assets/24593950/24220630/43c5f73e-0f4b-11e7-8726-b000ccb10d08.png)

**Comment by psifidotos** [comment]
you should read how this is done

**Comment by JenaPlinsky** [comment]
@psifidotos  ...sorry but I'm confused, understanding that, should I first read some how-to

until now ... I was going to edit manually **psifidotos/Latte-Dock/po/app/**

Now:
- step1 ...  from **local** I've edit by Lokalize, the file it.po
- Step2 ... I went on **psifidotos/Latte-Dock/po/app/**
- Step3 ...  I clicked the button **file uploads** ...but I get "**Uploads are disabled**"

I'm trying to upload to the correct repository?
I noticed that I created a fork **JenaPlinsky/Latte-Dock/po/app/** although do not know how
so have I to upload the files from here?

**Comment by audoban** [comment]
@JenaPlinsky The language Italian has many duplicate messages and the master doesn't build correctly, I will accept your last [PR](https://github.com/psifidotos/Latte-Dock/pull/313).

Please correct the Italian language and upload again.

**Comment by omni6** [comment]
@JenaPlinsky check your email!

**Comment by JenaPlinsky** [comment]
@omni6  
Tanks !!!!!!

git clone JenaPlinsky@github.com:Latte-Dock.git
You've successfully authenticated, **but GitHub does not
provide shell access.**

and now ?

**Comment by JenaPlinsky** [comment]
@psifidotos  
- psifidotos/Latte-Dock  ...**Uploads are disabled. File uploads require push access to this repository.**
so from firefox I can not UpLoad files ...why ?

- now I'm ready with SSH,  well almost :)  "...You've successfully authenticated, **but GitHub does not
provide shell access**."

- have I to create a fork of Latte from your repository, add my PO files and then a pull request to your repo? or send a file by SSH ?

**Comment by psifidotos** [comment]
> have I to create a fork of Latte from your repository, add my PO files and then a pull request to your repo?

Yes, this is the way... But we decided that from now on we accept only translations that are produced from a dedicated program such as Lokalize, this is the only way to be sure that Latte build is not broken because of incorrect translation files

**Comment by omni6** [comment]
user name is always git, the authentication relies on the ssh key you have added!
`git push git@github.com:JenaPlinsky/Latte-Dock.git` should work
then make pull request

**Comment by omni6** [comment]
> have I to create a fork of Latte from your repository
you have already! here: https://github.com/JenaPlinsky/Latte-Dock

**Comment by omni6** [comment]
clone your repo locally
in your homedir
 
`git clone git@github.com:JenaPlinsky/Latte-Dock.git`
 
copy your it.po out of your local git repo in a backup folder.
 
make reset to upstream (deletes your whole repo and pull newest from pisifidotos!)

in your local clone:
 
```
git remote add upstream https://github.com/psifidotos/Latte-Dock.git
git remote update
git reset --hard upstream/master --
git push origin +master
```
 
look in your browser your repo should be even with pisifidotos master!
 
make your changes locally in your cloned repo if you use lokalize your strings are already in the database! 
then:
 
```
git status  ---> se what changed
git add /changed/e.g.it.po /changed/b   and so on, seperate with space
git commit -am "Update it.po"
git push git@github.com:JenaPlinsky/Latte-Dock.git
```
 
and then make a pull request from your browser

**Comment by JenaPlinsky** [comment]
yes ... that's a fork that I do not know how I created
Anyway, I added in the repo, the file created with Lokalize.
- The fork was made a month ago
- the file that I added in JenaPlinsky / Milk-Dock / bit / apps
It is updated with the latest master branch and edited with Lokalize

I'll explain, I would just upload That file.
I can do it ?

**Comment by JenaPlinsky** [comment]
@omni6  your explanation is perfect !!!! and it could be useful to many

@audoban @psifidotos @omni6 
Tanks Guys

**Comment by JenaPlinsky** [comment]
@omni6  

backup my Latte repo on local ...ok
delete my Latte repo ...ok

then I get 
```
Ivan@UltrabookSamsung:~> git remote add upstream https://github.com/psifidotos/Latte-Dock.git
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by omni6** [comment]
no dont delete any files. 
this commands:
```
git remote add upstream https://github.com/psifidotos/Latte-Dock.git
git remote update
git reset --hard upstream/master --
git push origin +master
```
will overwrite your repo with this one from pisifidotos. to be even with the versions (up to date!)

all git commands exept `git clone` have to be typed IN your local clone!

**Comment by JenaPlinsky** [comment]
:( 
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by omni6** [comment]
```
~/git/omni6/Latte-Dock(master*) » ls                                                                                                                                                                            jan@royal-ts
app/    containment/  liblattedock/  po/     astylerc      clean.sh*       Definitions.cmake  INSTALLATION.md  LICENSE       README.md    uninstall.sh*
build/  icons/        plasmoid/      shell/  CHANGELOG.md  CMakeLists.txt  formatter.sh*      install.sh*      Locale.cmake  TRANSLATORS
------------------------------------------------------------
~/git/omni6/Latte-Dock(master*) » git remote add upstream https://github.com/psifidotos/Latte-Dock.git                                                 
```                         

so it should look, but i see you have deleted your fork on github!? try to make a new fork of latte dock and clone it locally again. 

you have all informations you need. struggle on, you'll get it. if you make a new fork you dont need to reset. 

follow arch wiki or here is another link:              [Git Reference](http://gitref.org/index.html)

**Comment by omni6** [comment]
just for information
i have pushed the up-to-date it.po into my master branch. devs could fetch...
[it.po](https://github.com/omni6/Latte-Dock/commit/66b8d9cfbbb6fb1e04a0f7c4b04e9a3e84826fd8)

**Comment by JenaPlinsky** [comment]
@psifidotos  @omni6  Push request for file edit with **Lokalize**
Permission to psifidotos/Latte-Dock.git denied to JenaPlinsky
```
git push git@github.com:psifidotos/Latte-Dock.git
ERROR: Permission to psifidotos/Latte-Dock.git denied to JenaPlinsky.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by audoban** [comment]
Hello @JenaPlinsky, please follow the tutorial of GitHub.

https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

**Comment by psifidotos** [comment]
@audoban should we close this ?

**Comment by audoban** [comment]
@psifidotos yep
