### ISSUE TITLE
plasmoid draggind on folder view

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#294]
By dragging a plasmoid, on the docked folder-view applet, folder-view content, is shown.
Dragging plasmoids, never should activate, the  folder-view explorer mode
![screenshot_20170321_025250](https://cloud.githubusercontent.com/assets/24593950/24129329/4da15182-0de2-11e7-9807-e5c1de820f06.png)

**Comment by psifidotos** [comment]
This is upstream, confirm that this is happening with plasma panel also

**Comment by JenaPlinsky** [comment]
tes I can confirm same behaviour foe default panel and dock
