### ISSUE TITLE
Strange behavior of top dock

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#299]
The icons size, on the top panel, don't follow their parameter in config dialog
![screenshot_20170321_080221](https://cloud.githubusercontent.com/assets/24593950/24167289/8a16f146-0e76-11e7-9a42-c4b59f47965a.png)

- Here is a [Video](https://youtu.be/8Duw7TYXA3k) ..and also the parabolic effect is strange

![spectacle x11934](https://cloud.githubusercontent.com/assets/24593950/24168748/994b7f42-0e7b-11e7-99df-4319958682ec.png)

**Comment by psifidotos** [comment]
This is automatic icon size... your maximum length is very small so the icons are shrinked to fit... 

You can disable automatic icon decrease from tweaks page

**Comment by psifidotos** [comment]
For the folderview animations i dont comment... the regular incosistencies from plasma implementation...
