### ISSUE TITLE
latte shell does not load its translation...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#3]

**Comment by psifidotos** [comment]
this is ok now, but I think there is an issue with so many no needed translations... Currently there are four:

- plasmoid
- containment
- shell
- corona

I think we must stay only with:
- plasmoid
- corona

**Comment by audoban** [comment]
> I think we must stay only with:
    plasmoid
    corona

And config window.

**Comment by psifidotos** [comment]
> And config window.

this is already in **old** corona, new **app** directory... The configuration window is inside the shell directory but it is loaded as just a simple qml file, so the translations werent working based on the shell loading mechanism... The translation strings include automatically into the app ones the shell ones... 

In config loading I just added the line:

`engine()->rootContext()->setContextObject(new KLocalizedContext(this));`

everything is ok now... I have my greek translation back...
