### ISSUE TITLE
Background panel don't grow consistently with applets at the edge

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#30]
1. set alignment to center and vertically(Left or Right edge).
2. Move the mouse to the first icon and observe with attention the background isn't grow with the icon.
3. Move the mouse to last icon and observe again, the background grow with the icon.

Also happens horizontally

**Comment by psifidotos** [comment]
I am sorry but I cant reproduce this... I tried also with latted plasmoid being the first or any other plasmoid that is animated but this didnt occur...

**Comment by psifidotos** [comment]
what plasma theme are u using?

**Comment by psifidotos** [comment]
a screenshot also would help... you could use also the visual debug mode in order to have more details...

**Comment by audoban** [comment]
I'll make a video.

**Comment by audoban** [comment]
[growing-2017-01-02_15.39.02.zip](https://github.com/psifidotos/Latte-Dock/files/681362/growing-2017-01-02_15.39.02.zip)

Please take attention to dock background.

**Comment by psifidotos** [comment]
ok... so as fas as I understood when there is an applet at the edge instead of a latte task(launcher or task) the dock background doesnot act accordingly... (this is something to do with hidden spacers)

I suppose, we prefer the way Latte plasmoid is doing it, right?

**Comment by audoban** [comment]
> I suppose, we prefer the way Latte plasmoid is doing it, right?

Yes, I prefer that way.
