### ISSUE TITLE
[Crash] - Enable hovering and previews at the same time

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#301]
![screenshot_20170321_215152](https://cloud.githubusercontent.com/assets/24593950/24170364/f6014672-0e80-11e7-8062-beb2da765e56.png)

crash event on
- replicable
- Set the checkbox "stands out active window"
- ...and moving on the task manager

![spectacle l17787](https://cloud.githubusercontent.com/assets/24593950/24170092/040e2fb0-0e80-11e7-9805-594e3412b238.png)
![spectacle g17787](https://cloud.githubusercontent.com/assets/24593950/24170113/1a9e4878-0e80-11e7-98f8-823c019375f9.png)
![spectacle e17787](https://cloud.githubusercontent.com/assets/24593950/24170138/2f14ec9e-0e80-11e7-8a81-3dde57c40297.png)

**Comment by psifidotos** [comment]
the user can choose only one from previews or hovering

![image](https://cloud.githubusercontent.com/assets/2216474/24171998/4f19f4da-0e8f-11e7-9580-432256229d92.png)

**Comment by JenaPlinsky** [comment]
Nice :) it's perfect

**Comment by psifidotos** [comment]
@JenaPlinsky this was a lot more general!!! Hovering effect was creating a lof of crashes even when used without previews!!! Thank you a lot for discovering the root of this!!!

When re-enabled the combination of the two effects in master and not they shouldnt crash... you could check please...
