### ISSUE TITLE
overlapping window without desktop effects look weird

### ISSUE THREAD

**Issue by tofuhead** [psifidotos/Latte-Dock#303]
If I turn off the desktop effects (shift-alt-f12) and have a window overlapping the latte dock I get a bar with a grid on it that overlaps everything. I'm guessing this is the transparency area, but not working not because of the effects shut down. 

usually I don't ofcourse turn off the effects, but to make this particularry annoying is because it happens when you launch a game that goes full screen. the game takes down desktop effects (to get max gpu for the game) and then this bar appear on top of the game.. 

I put a picture up to illustrate the problem:
http://pasteall.org/pic/show.php?id=113792

two shots from the same lower left side of my desktop, with two windows covering latte dock..  second image is ofcourse the one without desktopeffects. 

.b

**Comment by psifidotos** [comment]
KDE Frameworks 5.32 bug, fixed in master... update Latte with latest commits...
