### ISSUE TITLE
inconsistent translation string

### ISSUE THREAD

**Issue by omni6** [psifidotos/Latte-Dock#305]
should 
`Add launchers only in the taskmanager`      not be
`Add launchers only in Latte Plasmoid`
?

for me the term taskmanager in context with latte dock is new...

**Comment by psifidotos** [comment]
it could also changed to:

`Add launchers only in the Launchers Area`

**Comment by omni6** [comment]
yes i think this is the most clear discription. no new pull requests for translations yet? 
you should change it...

**Comment by psifidotos** [comment]
yes, dont send translations yet. ..
we must fix also an issue with our translation strings in order to include some strings that were missed

**Comment by psifidotos** [comment]
when it is ready for translators I will add an announcement at: #290

**Comment by psifidotos** [comment]
we decided to change it at:

`Add launchers only in the corresponding area`
