### ISSUE TITLE
Always visible option does not work for side-set dock on unusual multi screen setup.

### ISSUE THREAD

**Issue by slagiewka** [psifidotos/Latte-Dock#308]
Given the setup:

![screenshot_20170309_214817](https://cloud.githubusercontent.com/assets/11974489/24217702/0a005ea4-0f41-11e7-8ecd-ec10fbb9685f.png)

If I set a dock on the left side of the upper-left or on the right side of the upper-right, the _Always visible_ option - it behaves as expected. The dock pushes (or reserves?) space for itself and windows don't interfere with it. 

A different case is when I try to setup the dock on each side of the laptop screen. Both times dock is properly placed (though sometimes crashes on toggling settings) but the space underneath is not blank - the dock overlays with current window.

We can see that those edges are not actually the left- or right-most in the virtual space of the display server but it's not on a shared edge as well. Well, at least not entirely - maybe it collides with the upper screen edges?

My dock version is 0.5.91, installed from AUR latte-dock-git package.

**Comment by psifidotos** [comment]
For the crash use #147, in order to provide us the backtrace issue...

For the always visible not working correctly, try the same setup with plasma panels and check if it works ok eith them

By your infos, do you mean that for bottom and top docks, things are working ok for the laptop screen?

**Comment by psifidotos** [comment]
For the backtrace to work you must first install the  debug backages for latte-dock-git

**Comment by slagiewka** [comment]
> For the always visible not working correctly, try the same setup with plasma panels and check if it works ok eith them

With a regular plasma panel on both right and left side of the laptop screen, the window does not go underneath. Panel and windows stick together really nicely. Of course I'm taking about maximized windows from the beginning. Not-maximized window can go underneath both panel and dock, which is fine by me. 

> By your infos, do you mean that for bottom and top docks, things are working ok for the laptop screen?

For the bottom (of laptop) it works as expected. Empty space for the dock and maximized windows don't intrude.

For the bottom of top displays and the top of the laptop screen - it get crazy. When on the bottom of top display (1) - the laptop's bottom gets free space reserved. When on the top of the laptop screen (2) - the top screens' tops get free spaces reserved. Pictures related are attached beneath.

1.
![screenshot_20170322_223432](https://cloud.githubusercontent.com/assets/11974489/24221797/0ef3b49c-0f50-11e7-969f-3cbfb40b12aa.png)
2.
![screenshot_20170322_222627](https://cloud.githubusercontent.com/assets/11974489/24221795/0c29c026-0f50-11e7-9a97-b4dee4b057af.png)


A panel on bottom of the laptop screen would definitely work OK. Almost the same goes the panel being placed on top of the laptop screen but this has some more general drawbacks that are not related to Latte (like limited windows moving space on top screens or yakuake not opening on top screens).

**Comment by psifidotos** [comment]
if you run, latte-dock -d with-window ,a debug window appears with infos for the dock screen and the window properties... please provide us with some screenshots of that window when Latte doesnot behave correctly...

**Comment by slagiewka** [comment]
Actually, no window is provided when I start Latte with `latte-dock -d with-window`. Only log text info is available in shell output.

**Comment by psifidotos** [comment]
it is:

`latte-dock -d --with-window`

but dont worry... I found it... it is in our code...

@audoban please take a look into this... Our struts function does not take into account a multi-screen environment for which the virtual screen geometry needs to be used in order to compute correctly the offsets...

**Comment by audoban** [comment]
@slagiewka @psifidotos hello, The space reserved is correct, just that I dont take account the offset, I will to fix it

**Comment by slagiewka** [comment]
I got the new master updates and it works better indeed!

One drawback - Yakuake misbehaves heavily. Other windows don't seem to have this issue.
When dock is on the left and Yakuake is on the upper left screen then Yakuake has limited space. When dock is on the right and so is Yakuake, then Yakuake behaves properly...

![screenshot_20170323_095910](https://cloud.githubusercontent.com/assets/11974489/24260383/ffacd76c-0ff3-11e7-833c-6e10a18a3181.png)
![screenshot_20170323_100007](https://cloud.githubusercontent.com/assets/11974489/24260388/014b49d2-0ff4-11e7-9bdc-fdae659c60b3.png)
![screenshot_20170323_100125](https://cloud.githubusercontent.com/assets/11974489/24260392/02c5bbda-0ff4-11e7-9cb8-0a391823132e.png)

**Comment by psifidotos** [comment]
> One drawback - Yakuake misbehaves heavily. Other windows don't seem to have this issue. When dock is on the left and Yakuake is on the upper left screen then Yakuake has limited space. When dock is on the right and so is Yakuake, then Yakuake behaves properly...

Yakuake is known to have issues.. please confirm that that there isnt that issue with plasma panels...

**Comment by slagiewka** [comment]
I can confirm that having panel set the same as Latte on the first screen causes Yakuake to behave exactly the same.
Thank you! I hope Yakuake gets finally resurrected as Eike promised last October.
