### ISSUE TITLE
Exporting settings - Adding a dot in the filename

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#315]
If the user adds a dot in the filename the exported file does not contain the extension **.latterc**

**Comment by audoban** [comment]
This is normal behavior of QFileDialog, if the user use a custom extension then QFileDialog do prefer to extension selected for the user.

http://doc.qt.io/qt-5/qfiledialog.html#defaultSuffix-prop

**Comment by audoban** [comment]
I would leave it like this, you agree?

**Comment by audoban** [comment]
ignore the last commit

**Comment by psifidotos** [comment]
@audoban the problem is the following, the user adds a dot and the exported file doesnt have .latterc extension. When he will try to import it this file is not shown by default...

Can we consider it an upstream bug as long as QFileDialog doesnt provide a way to alter this?

**Comment by audoban** [comment]
It doesn't bug is a normal behavior, if the user write a .suffix then QFileDialog doesnt return a name with the suffix .latterc.

**Comment by audoban** [comment]
Nop QfileDialog doesnt provide a feature for force the suffix.

**Comment by psifidotos** [comment]
I see...

Can we add in the import dialog an (*) fillter which is **not enabled by default** in order for the user to be able to import such latte files? (meaning files that the user has set an alternative extension)

**Comment by audoban** [comment]
@psifidotos yes is possible.

**Comment by audoban** [comment]
Is unnecessary the filter (*) because the user can delete all filter for show all files.

**Comment by psifidotos** [comment]
ok...

**Comment by audoban** [comment]
![spectacle ve1434](https://cloud.githubusercontent.com/assets/7884292/24311222/43ec33c0-10a1-11e7-85cb-ad93d7e1bb05.png)
