### ISSUE TITLE
[Crash] - Exporting settings and trying to open directory of the file

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#316]
![image](https://cloud.githubusercontent.com/assets/2216474/24246807/b900ce30-0fd1-11e7-9ec8-8159ca6a22f8.png)

**Comment by psifidotos** [comment]
to be more descriptive the crash occurs when trying to open the directory of the exported file from the notification shown

**Comment by audoban** [comment]
The error really occur because QDir cannot parse the filename correctly

**Comment by psifidotos** [comment]
Why does it need the filename? Only the relevant directory dont we need?

**Comment by psifidotos** [comment]
Or send the dolphin command directly?

**Comment by audoban** [comment]
It was not QDir's problem, I was doing it wrong.

**Comment by audoban** [comment]
@psifidotos Latte should not call the browser directly, xdg is the responsible of which browser should be launched.
