### ISSUE TITLE
Error loading main.qml

### ISSUE THREAD

**Issue by Alexander-Wilms** [psifidotos/Latte-Dock#318]
Latte Dock doesn't start properly, there's an error message being displayed at the bottom of the screen stating that there was an error while loading the QML file main.qml.

My system:

Fedora 25 KDE
Plasma Version: 5.8.6
KDE Frameworks Version: 5.32.0
Qt Version: 5.7.1
Kernel Version: 4.8.6-300.fc25.x86_64
OS Type: 64-bit

```
[warning 15:37:45.778778] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 15:37:45.778778] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:46: TypeError: Cannot read property 'DateTime' of undefined
[warning 15:37:45.778778] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:47: TypeError: Cannot read property 'DateTime' of undefined
[warning 15:37:45.853853] - file:///usr/lib64/qt5/qml/QtQuick/Controls/TextArea.qml:941: TypeError: Cannot read property '__cursorHandle' of null
[warning 15:37:45.853853] - file:///usr/lib64/qt5/qml/QtQuick/Controls/TextArea.qml:905: TypeError: Cannot read property '__selectionHandle' of null
[warning 15:37:45.854854] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:350: TypeError: Cannot read property 'padding' of null
[warning 15:37:45.854854] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:351: TypeError: Cannot read property 'padding' of null
[warning 15:37:45.854854] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:352: TypeError: Cannot read property 'padding' of null
[warning 15:37:45.854854] - file:///usr/lib64/qt5/qml/QtQuick/Controls/ScrollView.qml:353: TypeError: Cannot read property 'padding' of null
[warning 15:38:39.914914] - "" doesn't have any WindowType, assuming as NET::Normal
[warning 15:38:40.155155] - "" doesn't have any WindowType, assuming as NET::Normal
[warning 15:38:47.290290] - "" doesn't have any WindowType, assuming as NET::Normal
[warning 15:39:05.513513] - "" doesn't have any WindowType, assuming as NET::Normal
[warning 15:39:08.809809] - "" doesn't have any WindowType, assuming as NET::Normal
[warning 15:39:08.812812] - "" doesn't have any WindowType, assuming as NET::Normal

```

![image](https://cloud.githubusercontent.com/assets/3226457/24280033/e3fe9050-104d-11e7-882d-b8ecdf956a1a.png)

**Comment by audoban** [comment]
@Alexander-Wilms please show me your log of installation.

**Comment by Alexander-Wilms** [comment]
Sure

`
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awilms/Latte-Dock/build
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  0%] Built target translations-containment
[  3%] Automatic moc for target latte-dock
[  3%] Built target latte-dock_automoc
[ 74%] Built target latte-dock
[ 77%] Automatic moc for target lattedockplugin
[ 77%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  0%] Built target translations-containment
[  3%] Automatic moc for target latte-dock
[  3%] Built target latte-dock_automoc
[ 74%] Built target latte-dock
[ 77%] Automatic moc for target lattedockplugin
[ 77%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/metadata.desktop
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/SIL Open Font License.txt
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/tangerine.ttf
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls/SpinBox.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteTextField.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockConfiguration.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/BehaviorConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TweaksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TasksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/Header.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/AppearanceConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/config.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml
-- Installing: /usr/share/metainfo/org.kde.latte.shell.appdata.xml
-- Installing: /usr/share/kservices5/plasma-shell-org.kde.latte.shell.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config/main.xml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/LayoutManager.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/purpleprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/blueprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter2.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/sepiaprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/ConfigOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AddWidgetVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AppletItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/EditModeVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/DebugWindow.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images/panel-west.png
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.containment.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.desktop
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/config.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/main.xml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/tools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/layout.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskProgressOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigInteraction.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskGroupItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipDelegate2.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/GlowPoint.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigAppearance.qml.cmake
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/CircleText.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/VisualAddItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskActiveItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigPanel.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipWindowMouseArea.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/MouseHandler.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images/panel-west.png
-- Installing: /usr/share/metainfo/org.kde.latte.plasmoid.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.plasmoid.desktop
-- Installing: /usr/bin/latte-dock
-- Installing: /usr/share/applications/latte-dock.desktop
-- Installing: /usr/share/dbus-1/interfaces/org.kde.LatteDock.xml
-- Installing: /usr/share/knotifications5/lattedock.notifyrc
-- Installing: /usr/lib64/qml/org/kde/latte/liblattedockplugin.so
-- Installing: /usr/lib64/qml/org/kde/latte/qmldir
-- Installing: /usr/share/icons/hicolor/16x16/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/22x22/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/24x24/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/32x32/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/48x48/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/scalable/apps/latte-dock.svg
-- Installing: /usr/share/icons/breeze/applets/256/org.kde.latte.plasmoid.svg

`

**Comment by audoban** [comment]
Let's do a test.

exec on the terminal:
`sudo mv /usr/lib64/qml/org/kde/latte/liblattedockplugin.so /usr/lib64/qt5/qml/org/kde/latte/liblattedockplugin.so`

`sudo mv /usr/lib64/qml/org/kde/latte/qmldir /usr/lib64/qt5/qml/org/kde/latte/qmldir`

And try again.

**Comment by Alexander-Wilms** [comment]
The second command fails, since /usr/lib64/qml/org/kde/latte/qmldir doesn't exist

**Comment by audoban** [comment]
@Alexander-Wilms try to move `/usr/lib64/qml/org/kde/latte/qmldir` to `/usr/lib64/qt5/qml/org/kde/latte/qmldir` notice that the path qt5 is missing.

this issue had been reported here before https://github.com/psifidotos/Latte-Dock/issues/86
and probably is a bug of your distro.

**Comment by Alexander-Wilms** [comment]
Hm, that doesn't fix it. I reported the issue here: https://bugzilla.redhat.com/show_bug.cgi?id=1435525

**Comment by audoban** [comment]
@Alexander-Wilms try to install latte from this branch https://github.com/psifidotos/Latte-Dock/tree/fedora-install

**Comment by Alexander-Wilms** [comment]
The issue persists, even with that new branch.

**Comment by audoban** [comment]
please show me your log again.

**Comment by Alexander-Wilms** [comment]
Here you go:

```
[awilms@localhost Latte-Dock]$ git checkout fedora-install
Bereits auf 'fedora-install'
Ihr Branch ist auf dem selben Stand wie 'origin/fedora-install'.
[awilms@localhost Latte-Dock]$ sudo ./install.sh
-- Disabling debug info
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awilms/Latte-Dock/build
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  0%] Built target translations-containment
[  3%] Automatic moc for target latte-dock
[  3%] Built target latte-dock_automoc
[ 74%] Built target latte-dock
[ 77%] Automatic moc for target lattedockplugin
[ 77%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  0%] Built target translations-containment
[  3%] Automatic moc for target latte-dock
[  3%] Built target latte-dock_automoc
[ 74%] Built target latte-dock
[ 77%] Automatic moc for target lattedockplugin
[ 77%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.containment.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/latte-dock.mo
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/metadata.desktop
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/SIL Open Font License.txt
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/tangerine.ttf
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls/SpinBox.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteTextField.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockConfiguration.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/BehaviorConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TweaksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TasksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/Header.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/AppearanceConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/config.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/views
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml
-- Installing: /usr/share/metainfo/org.kde.latte.shell.appdata.xml
-- Installing: /usr/share/kservices5/plasma-shell-org.kde.latte.shell.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config/main.xml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/LayoutManager.js
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/purpleprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/blueprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter2.png
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/sepiaprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter.png
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/ConfigOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AddWidgetVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AppletItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/EditModeVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/DebugWindow.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images/panel-west.png
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.containment.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/config.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/main.xml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/tools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/layout.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskProgressOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigInteraction.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskGroupItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipDelegate2.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/GlowPoint.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigAppearance.qml.cmake
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/CircleText.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/VisualAddItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskActiveItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigPanel.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipWindowMouseArea.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/MouseHandler.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images/panel-west.png
-- Installing: /usr/share/metainfo/org.kde.latte.plasmoid.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.plasmoid.desktop
-- Installing: /usr/bin/latte-dock
-- Installing: /usr/share/applications/latte-dock.desktop
-- Installing: /usr/share/dbus-1/interfaces/org.kde.LatteDock.xml
-- Installing: /usr/share/knotifications5/lattedock.notifyrc
-- Installing: /usr/lib64/qt5/qml/org/kde/latte/liblattedockplugin.so
-- Installing: /usr/lib64/qt5/qml/org/kde/latte/qmldir
-- Installing: /usr/share/icons/hicolor/16x16/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/22x22/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/24x24/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/32x32/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/48x48/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/scalable/apps/latte-dock.svg
-- Installing: /usr/share/icons/breeze/applets/256/org.kde.latte.plasmoid.svg
```

**Comment by Alexander-Wilms** [comment]
Now, it works!

**Comment by audoban** [comment]
@Alexander-Wilms the installation is totally correct. This should work.

Show me the output of latte dock from the terminal: `lattedock -d`

**Comment by Alexander-Wilms** [comment]
Since it works, I assume you don't need the output anymore?
