### ISSUE TITLE
Dock shouldnt hide on userConfiguring state

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#32]
I think that this should go into the visibilitymanager but I am not so sure...
I have uploaded a fix from the ui side that can be removed when the visibilitymanager supports it if we decide to do so...

**Comment by audoban** [comment]
we can block the isHidden property, isn't necessary add more complexity

**Comment by psifidotos** [comment]
> we can block the isHidden property

I can not understand how this is sufficient....

**Comment by audoban** [comment]
VisibilityManager already have blockHidden property. Remember that ui has responsibility of update isHidden property, I can not allow Visibility Manager to take over ownership

**Comment by audoban** [comment]
However, visibilitymanager can emit mustBeShown when config ui is open with this property [Plasmoid::userConfiguring](https://api.kde.org/frameworks/plasma-framework/html/classAppletInterface.html#af25873dd077aec61d9a56a7578d1bb54.)

**Comment by psifidotos** [comment]
> VisibilityManager already have blockHidden property. Remember that ui has responsibility of update isHidden property, I can not allow Visibility Manager to take over ownership

ok... I will wait for blockHidden. We will keep this in ui responsibility

**Comment by audoban** [comment]
The property has already added.
https://github.com/psifidotos/Latte-Dock/commit/53cb0f25222521109535109aea55c1abcdb310f2

**Comment by psifidotos** [comment]
perfect! that opens the doors to one two more fixes then... dragging and context menu from latte plasmoid

**Comment by psifidotos** [comment]
fixed in master...

**Comment by audoban** [comment]
Still broken
