### ISSUE TITLE
[Crash] - Windows hovered effect

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#323]
The use of Qt 5.8 and KDE Frameworks 5.32 creates a frequent crash on the start, I dont know which one is responsible...

![image](https://cloud.githubusercontent.com/assets/2216474/24295941/b93c9c06-10a5-11e7-81be-d0967eb6848a.png)

**Comment by psifidotos** [comment]
Just as a notice... Plasma devs are so frustrated of Qt 5.8 that some of them even thought to blacklist its use with plasma, until a better release comes out...

**Comment by psifidotos** [comment]
I added a workaround and reported the bug also:

https://bugs.kde.org/show_bug.cgi?id=378016

**Comment by Findus23** [comment]
Is it possible that b07b689f9b230a42bd2a96bd77bc90be2299b360, creates a new bug?

For me the program-icons are gone now and instead there is a latte icon, which shows the following error, when clicked:
```
Fehler beim Laden der QML-Datei: [error while loading QML-file]
file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:467:9:
Cannot assign to non-existent property "groupDialog"
```
![screenshot_20170324_193854](https://cloud.githubusercontent.com/assets/6266037/24308806/c2151d7a-10c9-11e7-972e-e2db9768b21e.png)

I am using plasmashell 5.8.4 on debian Stretch

**Comment by psifidotos** [comment]
ok... thank u!! fixed both...

**Comment by Findus23** [comment]
Many thanks, it's working now.
