### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#325]
![screenshot_20170324_220751](https://cloud.githubusercontent.com/assets/24593950/24313758/9c2342d0-10de-11e7-8b0e-88d0fb287ea7.png)

**Comment by psifidotos** [comment]
with all this mess the last days your generated it.po file missed a string... I uploaded in master a correct merged italian file, you can translate it and request a pull request afterwards... please use Lokalize for translation...
