### ISSUE TITLE
Increasing amount of the dock instances

### ISSUE THREAD

**Issue by quarckster** [psifidotos/Latte-Dock#329]
If I put Latte Dock in KDE autostart then each login I will get more and more the dock instances in the left upper corner. In the config I can see increasing amount of `[Containments]` section. Version 0.5.91.
[Latte Dock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/869852/Latte.Dock-appletsrc.txt)

**Comment by audoban** [comment]
hello @quarckster 
On the version master, the instances of latte-dock has been limited to 1 for session. We also add a feature to clean unused `containments`. 

You can use the master and tell us your experience again or wait for the next beta.

**Comment by JenaPlinsky** [comment]
Bello funziona ...doveri sistemare un sacco di cose ancora

**Comment by psifidotos** [comment]
fixed in master...
