### ISSUE TITLE
visibilitymanager does not load correctly the timers values on startup

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#33]
closing the dock and restarting it does not load the timers values

**Comment by audoban** [comment]
Apparently the containment is created before that visibility manager, and for this reason dont load the configuration.

**Comment by psifidotos** [comment]
how do you want to handle this ?

**Comment by audoban** [comment]
how do you want to handle this ?

I will load the configuration when containment has been created.

**Comment by psifidotos** [comment]
perfect

**Comment by psifidotos** [comment]
is this fixed in master? in configuration window the timers values are still not shown....

**Comment by audoban** [comment]
> is this fixed in master? in configuration window the timers values are still not shown....

then is a error of Config UI, should read initial values.

**Comment by psifidotos** [comment]
yes you are right... I dont know what changed but after rebasing the master 2-3 times it worked...
