### ISSUE TITLE
visibility mode and options

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#330]
the settings for...
- show dock on desktop change
- show dock on activities change

... are reset when switching from **visibility mode auto hide** to **always visible**, and perhaps this is true, for every change in visibility mode, I have not checked

**Comment by JenaPlinsky** [comment]
Ok fixed !!!
perhaps, for the only **always visible mode**, the right way would be to set those options as unavailable (gray)

**Comment by audoban** [comment]
@JenaPlinsky, I agree, thanks for your suggest
