### ISSUE TITLE
[Feature] Customizable delay before higlighting windows on hovering.

### ISSUE THREAD

**Issue by ToastyYogurtTime** [psifidotos/Latte-Dock#332]
Currently, the "highlight windows on hovering" option highlights windows immediately when they're hovered over. I find this helpful but a bit disorienting with a hidden dock, so I'd like to be able to set a delay in which the item must be hovered over for X ms before the window is highlighted.

**Comment by psifidotos** [comment]
I dont know if we will add this in the future but for sure wont make it at version 0.6

**Comment by ToastyYogurtTime** [comment]
I understand.

**Comment by psifidotos** [comment]
Configurable delay is a bit too much... on the other hand we could easily use the same delay the window previews use....

@audoban do you agree?
