### ISSUE TITLE
 Tasks or launchers dragging, within the task manager

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#334]
- protecting areas other than the task manager [video](https://youtu.be/nBMhCfMJUJU)

![screenshot_20170326_122542](https://cloud.githubusercontent.com/assets/24593950/24330580/64e7b9b0-1221-11e7-9ec1-0caaf4174a70.png)
![screenshot_20170326_122619](https://cloud.githubusercontent.com/assets/24593950/24330582/66a9815c-1221-11e7-977b-d5ff8479989a.png)

**Comment by psifidotos** [comment]
for the folderview, sorry this is not in our side... it is on plasmas....
