### ISSUE TITLE
Folder multi selection dragging

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#335]
- In the case of dragging a multi-selection of  folders, iis it possible to impose, automatically select the "folder-view as" option ?
- while, with regard to drag individual files I have no idea if the user likes to have its choice,
 folder-view or icon
![screenshot_20170326_132656](https://cloud.githubusercontent.com/assets/24593950/24330878/aa22a1a0-1228-11e7-944a-79ebfe04e7c2.png)
![screenshot_20170326_132829](https://cloud.githubusercontent.com/assets/24593950/24330942/103dae02-122a-11e7-8124-34722982a2ed.png)

**Comment by psifidotos** [comment]
> Ιn the case of dragging a multi-selection of folders, iis it possible to impose, automatically select the "folder-view as" option ?

sorry, I would like to keep things simple as much as possible...

> while, with regard to drag individual files I have no idea if the user likes to have its choice,
folder-view or icon

it can have its choice... if the user would like to unblock where the launchers are added, can do so from Tweaks page

**Comment by JenaPlinsky** [comment]
Ok no problem ;)
