### ISSUE TITLE
Launcher's link dragging on task manager

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#337]
Perhaps I had already given an input of this kind, I can not remember but it was something like that, I guess.
Well, personally I'm used to divide the desktop-launchers in folders which represent categories of applications, in reality, I do not make a copy of the launcher in its class, but I'll paste a series of links

I'm wondering, dragging the links, if it was possible to get the same behavior that you get by dragging desktop-launchers

**Desktop-Launcher:**
![screenshot_20170326_190609](https://cloud.githubusercontent.com/assets/24593950/24333433/45b8e4c4-1258-11e7-92fc-ad2f8f4a422e.png)

**Launcher's link:**
![screenshot_20170326_190535](https://cloud.githubusercontent.com/assets/24593950/24333434/478f3488-1258-11e7-9810-4d2f84fdfde8.png)

**Comment by psifidotos** [comment]
a launcher link can not be identified as a launcher from libtaskmanager, it is identified as a file...

I dont really get your workflow...
Dont you add your launchers only once ?

**Comment by JenaPlinsky** [comment]
Yes ...I normally run the application and successively tell to it  "show as a launcher when not running"

few days ago I happened to drag links and these were added as launchers 
... but then, how many times can happen to make things like this? ... well few

The current behavior seems to me the most convenient
It allows you to add only desktop-launcher, while excluding plasmoids, files, and links (which, as you've mentioned, are identified as files)

we can not have both the egg and the chicken :)
