### ISSUE TITLE
[Feature Request] - Support applets scrolling instead of decreasing the applet size

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#338]
what do you think about this mockup ?
rather than climb the icons, when the dock reaches maximum width available.
![1](https://cloud.githubusercontent.com/assets/24593950/24382216/1f802c38-1355-11e7-9aa7-8f8f412bb681.png)
![2](https://cloud.githubusercontent.com/assets/24593950/24382219/1f88a44e-1355-11e7-953a-1a889edf14ec.png)
![3](https://cloud.githubusercontent.com/assets/24593950/24382217/1f8388e2-1355-11e7-9602-1534d5ca8877.png)
![4](https://cloud.githubusercontent.com/assets/24593950/24382218/1f85c058-1355-11e7-89e9-efa8a7aff071.png)
![5](https://cloud.githubusercontent.com/assets/24593950/24382220/1f8b6e54-1355-11e7-8821-62233fd4851f.png)

**Comment by Petross404** [comment]
Can you implement a shaking or rotating effect for the launchers when clicked?

Actually for the widgets too

**Comment by psifidotos** [comment]
For lauchers it can be done... for all applets it cant...

personally i dont find any interest in supporting different effects
