### ISSUE TITLE
[Feature] Disable dock shadow

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#339]
Could you implement option in latte settings to disable dock (_KDE_NET_WM_SHADOW) shadow when Panel background is enabled?
Actually i need to run script:
"#!/bin/bash
for WID in $(xwininfo -root -tree | sed '/" (failure in conversion from UTF8_STRING to ANSI_X3.4-1968)": ("latte-dock" "lattedock")/!d; s/^  *\([^ ]*\) .*/\1/g'); do
   xprop -id $WID -remove _KDE_NET_WM_SHADOW
done"

**Comment by psifidotos** [comment]
This shadow is drawn only on Always Visible mode with Fill alignment and panel background size 100%, in all other cases the shadow is drawn internally in the Latte window... 

The shadow is set by the plasma theme...
If you find a theme that has not shadow at all, or remove from widgets/panel-background.svgz of your theme all the shadow elements then Latte will follow this setting directly...

**Comment by divinae** [comment]
Thanks, changing panel-background work

**Comment by psifidotos** [comment]
;-)
