### ISSUE TITLE
Occasional instant sliding-in on activity change animation

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#342]
For some reason the qml side is responsible for this but I havent found yet why...

**Comment by psifidotos** [comment]
strange enough this occurs only on activity change and not for desktop change...

**Comment by psifidotos** [comment]
more details... this is happening on desktop change also, it occurs when there are additions/removals from the latte tasks plasmoid...

**Comment by Petross404** [comment]
Please move it in the proper thread if I am wrong to post it here, but sometimes when I click on a launcher I observe that the one next to it, swaps positions, like sliding in it's position and the launcher I clicked slides in to the other's.

I can't express myself quite clear in english, so let's give an example:

`...konversation.desktop;akregator.desktop...` but if I click on Akregator it becomes for a brief moment like `...akregator.desktop;konversation.desktop;...` and then back again to normal.

**Comment by psifidotos** [comment]
Not related... open a new issue to discuss this...

**Comment by audoban** [comment]
OK, I think this is more frequent, when you first enter an activity, can be Could it be that there are missing frames in the animation of sliding

**Comment by psifidotos** [comment]
It happens in every activity or desktop change that there are additions or removals in the Latte plasmoid... i researched a lot but didnt find the reason...

**Comment by psifidotos** [comment]
this is totally related to compositor painting...

because of the new greatly improved  animations architecture I was able to add also a delay when adding adding new records (tasks).

to observe someone the faulty X11 and compositor behavior, someone can minimize all windows everywhere and try to make a desktop or activity change... in my computer this always provides a beautiful sliding in/out of the dock. When windows are shown the probably because the painting makes many calculations our sliding-in painting can not catch up...

**Comment by psifidotos** [comment]
@audoban this could be fixed totally I think by delaying a bit to send the signal for the sliding in on activity/desktop change, for example by 500ms. That way all painting of the compositor and the window manager (window changes) will probably have ended and after beautiful sliding in would take place
