### ISSUE TITLE
Drop Latte launchers mechanism and use completely the libtaskmanager...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#343]
The Latte lauchers internal mechanism has its routes at plasma5.8 for which different launchers per activity werent supported. Latte 0.6 by trying to support two different plasma launchers mechanism one for 5.8 and one for 5.9 even though it supports different launchers per activity on the other hand doesnt help libtaskmanager to categorize correctly in some cases windows and launchers... There are cases that plasma launchers in 5.9 work much better than the Latte ones...

For Latte 0.7 for which we can break compatibility with plasma 5.8 i propose the following:
1. drop the entire Latte internal launchers mechanism and use only the one offered from plasma 5.9 and beyond. Plasma developers put a lot of effort into this for 5.9
2. add an import function from the old architecture into the new one. Optimal the user wont notice any diffetence only a better behavior. The worst case scenario would be the user to lose some of its launchers from specific not running activities which can add afterwards of course
3. this way for any issue with launchers we will be able to compare it truly with the default plasma taskmanager
4. sharing more code with libtaskmanager is good because there are plans in the future to become a more concrete public api

**Comment by audoban** [comment]
I don’t have any problem with the propose

**Comment by MichaelTunnell** [comment]
> For Latte 0.7 for which we can break compatibility with plasma 5.8 i propose the following:

Plasma 5.8 is the LTS so I hate the idea of completely breaking compatibility.

**Comment by psifidotos** [comment]
> Plasma 5.8 is the LTS so I hate the idea of completely breaking compatibility.

version 0.6 can keep the compatibility and 0.7 can break it... there are also other things that we need from 5.9 and later... such as tooltips in the configuration window...

**Comment by Petross404** [comment]
> version 0.6 can keep the compatibility and 0.7 can break it 

Or maybe if you have the time, make 0.6.x "LTS" and provide support and bugfixes as long a Plasma 5.8 is around

**Comment by audoban** [comment]
@psifidotos While plasma 5.8 remains LTS we must maintain compatibility

**Comment by psifidotos** [comment]
@audoban sorry i dont agree... plasma 5.8 users know that can not have new features only bug fixes and maintenance...

Latte 0.6 can play that role but
Latte 0.7 can not provide that role otherwise we should stick with only with 0.6 for one more year...

**Comment by MichaelTunnell** [comment]
> sorry i dont agree... plasma 5.8 users know that can not have new features only bug fixes and maintenance...

That's an assumption. There are people who don't even know what LTS means and thinks it means "oh this one will be stable and not crash on me". The fact that Neon has an Plasma LTS release means that many people will be using that version.

> maybe if you have the time, make 0.6.x "LTS" and provide support and bugfixes as long a Plasma 5.8 is around, in parallel with 0.7.x

In my opinion, this would be ideal. 0.6 wouldn't be left in limbo but it wouldn't receive new features. I think that is totally reasonable for everyone. The Latte Dock devs wouldn't have to promise a lot of work on the 0.6 branch but just in case it was needed it would just make users feel comfortable with using it.

Though to be fair, this assume Latte Dock has any intention of making packages. If it will always be a "download source and install via bash script" then people who might be affected by the LTS issue may never even use the dock.

**Comment by psifidotos** [comment]
> In my opinion, this would be ideal. 0.6 wouldn't be left in limbo but it wouldn't receive new features. I think that is totally reasonable for everyone. The Latte Dock devs wouldn't have to promise a lot of work on the 0.6 branch but just in case it was needed it would just make users feel comfortable with using it.

latte developers currently are just two persons...

> If it will always be a "download source and install via bash script" then people who might be affected by the LTS issue may never even use the dock.

Latte 0.6 was published yesterday and today there are pre-built packages for almost all the big distros, not from Latte developers (@audoban provides packages for openSUSE) but from the distro packagers that understand the importance of the project

-----------
sometimes I am concerned that I didnt write correct my thoughts in english.... but then I just read in my initial comment:

> For Latte 0.7 for which we can break compatibility with plasma 5.8 i propose the following:

it is pretty clear what I am describing, please before posting take some time to read the responses...
Latte 0.6 can not break compatibility with plasma 5.8, of course I hope that there will be the manpower to maintain and help for as long as possible... but Latte 0.7 we should move forward and provide the fixes that can be provided to users of plasma 5.9 and beyond...

adding in the above Latte 0.7 is probably going to be the first release that will try to support something in wayland but we cant promise anything around that #73 ....

**Comment by MichaelTunnell** [comment]
> latte developers currently are just two persons...

I'm aware but what I was suggesting was not to continue development of 0.6 or to not make changes or innovation with 0.7 but rather to continue maintenance for 0.6, if it is ever needed.

> Latte 0.6 was published yesterday and today there are pre-built packages for almost all the big distros, not from Latte developers (@audoban provides packages for openSUSE)

Where would I find these packages? I found the openSUSE and AUR links on the README but I can't find anything for any other distro.

> from the distro packagers that understand the importance of the project

One of the best things and worst things about Linux package distributions is this approach because they may understand the importance but they won't be able to do anything for 6 months or even more at times.

> it is pretty clear what I am describing, please before posting take some time to read the responses...

In most software projects old versions are deprecated with new versions being made. Your statement was clear but not thorough to convey what would happen with 0.6.

0.6 will continue to work with Plasma 5.8 but what if something is changed in Plasma 5.8.x point release that breaks 0.6? Would this project provide a fix or no? That's pretty much all I was requesting with future support for 0.6.

**Comment by psifidotos** [comment]
> Where would I find these packages? I found the openSUSE and AUR links on the README but I can't find anything for any other distro.

Ubuntu derivatives:  http://www.ubuntuvibes.com/2017/04/first-stable-build-of-latte-dock.html
Gentoo and RedCore: https://github.com/redcorelinux/redcore-desktop/blob/master/kde-apps/latte-dock/latte-dock-0.6.0.ebuild

> they may understand the importance but they won't be able to do anything for 6 months or even more at times.

having AUR, opensuse Build Service and ppa's the situation is not as tragic nowdays... but of course it depends from packagers effort and commitment...

> 0.6 will continue to work with Plasma 5.8 but what if something is changed in Plasma 5.8.x point release that breaks 0.6? Would this project provide a fix or no? That's pretty much all I was requesting with future support for 0.6.

I believe that we would like to support a maintenance cycle for 0.6 version as long as this possible concerning this is an open source project and we just contribute in our spare time. Breaking something from 5.8.x is very rare because plasma devs are very concrete in not breaking api no matter what... of course if we are not able no provide such a fix in the rare case something breaks, Latte is an open effort... we will always accept pull requests, contributions, etc... Latte being in github someone can always fork it and do his magic with it... :)

**Comment by psifidotos** [comment]
### We have an agreement... Latte master which is going to be the 0.7 version will break compatibility with Plasma 5.8... and branch v0.6 will keep feature freeze and preserve compatibility with Plasma 5.8 which is an LTS release... we will try to maintain of course branch v0.6 as long as possible...

**Comment by psifidotos** [comment]
if someone want to test the new architecture... can try the launchers59 branch

![image](https://cloud.githubusercontent.com/assets/2216474/24839830/4bf0cc36-1d6a-11e7-9f17-1ec1c2c53c2c.png)

**Comment by psifidotos** [comment]
some infos concerning the new implementation!!
with the new architecture we have the following pros! : 

- much improved identification/categorization between launchers and windows... _has fixed in my system the libreoffice case that was broken otherwise_
- much improved animations during activities/desktops changes... only the differences are removed/added... all the rest are staying and updated in their place!
- support an easier and more understanding way to set launchers for different activities through the new Pin option in the context menu
- support mixing placement of global and explicit launchers
- special cases launchers such as wine, webapps etc. which are supported  correctly from official plasma taskmanager, now are also supported in the same way in Latte also
- the launchers are stored in our side... in the applets settings there is a record for **launchers** (that is the old way to store launchers) and **launchers59** the new architecture
- there is a default import between old and new architecture... the algorithm is clever enough in order to check on latte startup, if launchers59 is empty and launchers contain records then by default the importing is taking place


cons:
- it probably breaks compatibility with Plasma 5.8 and this is why I am not merging it in master branch yet and I am leaving it at the **launchers59** branch... I believe that a 2 weeks window is enough for this... so in two weeks the master branch will break compatibility with plasma 5.8 and I will add the fantastic new features #343 and #365 ...
