### ISSUE TITLE
Strange animation while testing wrong-struts  branch 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#345]
#344 Seems fixed but I get this  [Srtange animation](https://youtu.be/2JuaLr-n5ps)
#330 fixed too

**Comment by psifidotos** [comment]
there is no wrong-struts branch everything is included in the 0.6 release..


for animation issues with folderview applets we have discussed it so many times... plasma folderview is not working good with Latte animations...

**Comment by JenaPlinsky** [comment]
I think that this is not the usually defect referred to the folder-view
 if you well observe, the folders do not follow the mouse, they are properly moving along its Y axis while remaining fixed on the x axis

- all this has happened, without touching in any way the display settings
- the current configuration was working properly until yesterday
- by importing a previously saved configuration file       ... the problem persists
- restarting the dock                                                              ....the problem persists
- loading from an old branch                                               ... the problem persists
- by changing visual parameters such as zoom, space ... the problem remains
- deleting  folderview icons                                                  ....the problem remains
- This behavior is very similar to the problem encountered with the applet Spacer #287

![screenshot_20170402_150817](https://cloud.githubusercontent.com/assets/24593950/24587430/955c27ee-17b6-11e7-9dab-2d9a37afeba5.png)

**Comment by psifidotos** [comment]
You are memtioning that loading from an old branch the problem persists ... that means that may something else updated and created this...

i know it is annoying but plasma folderview has so many ways to break Latte experience... personally i use only one to show the activity's linked files and i lock it....

**Comment by JenaPlinsky** [comment]
if the popularity of milk will grow much .... maybe someone within the plasma team will take to heart and inprove its support to the applets and folder.view side 👍

**Comment by psifidotos** [comment]
Or someone will provide an alternative which will also be better from memory perspective... each folderview applet you can consider as a full one plasma desktop from a memory perspective... 10 different folderviews mean 10 plasma desktops
