### ISSUE TITLE
Empty "look and feel" settings tab

### ISSUE THREAD

**Issue by federicoiosue** [psifidotos/Latte-Dock#347]
Using Plasma 5.9.3, by selecting the "latte dock settings" by right clicking on the desktop object I expected to have some sort of panel settings view but what I got is the standard Latte Dock settings window, but with empty "look and feel" page.
![](http://i.imgur.com/HsPR0Rf.png)

**Comment by psifidotos** [comment]
Latte must be run as an executable...

latte-dock

You probably have added only the latte plasmoid in the plasma desktop

**Comment by psifidotos** [comment]
There is already an Arch package of 0.6 Latte that may work with Manjaro,

https://aur.archlinux.org/packages/latte-dock-git/

it is based on master branch, i would propose to use the official 0.6  stable package when it is released...

**Comment by federicoiosue** [comment]
I've actually installed [this](https://aur.archlinux.org/packages/latte-dock/) that is already updated to latest release.

By the way, launching as a binary everything worked fine thank you very much.

**Comment by psifidotos** [comment]
Nice!!! That is the official stable package for 0.6 from AUR!! It is provided very fast... ;-)
