### ISSUE TITLE
file contents missing for build

### ISSUE THREAD

**Issue by gmoutso** [psifidotos/Latte-Dock#348]
With install.sh I get  
`file COPY cannot find "/home/george/temp/Latte-Dock-0.6.0/contents".`

**Comment by psifidotos** [comment]
which distro?

**Comment by gmoutso** [comment]
kubuntu 16.10

**Comment by psifidotos** [comment]
as long as you have followed guidelines from:

https://github.com/psifidotos/Latte-Dock/blob/master/INSTALLATION.md

then the file you downloaded of the extraction wasnt correct...

**Comment by gmoutso** [comment]
Thank you. This time I git cloned instead and it worked. Congratulations on the release!

**Comment by psifidotos** [comment]
nice hearing you got it work out!!!
