### ISSUE TITLE
Delay in application launch

### ISSUE THREAD

**Issue by andrevmatos** [psifidotos/Latte-Dock#349]
I've a very fast SSD, and most applications usually start instantly when launched from a panel, launcher or krunner. But, when launched from Latte Dock, it takes a considerable amount of time to show up in the screen. Looks like the process is only started after the "bounce" animation is finished, taking what seems more than a full second for the application to be started, and making the dock feels "unresponsive". Would be possible to launch it immediatelly/concurrently with the bounce animation? 
Here a small [GFYCAT](https://gfycat.com/GroundedFancyCrocodileskink) showing the issue.

**Comment by psifidotos** [comment]
you can read at #336 the reason for this... with current plasma libtaskmanager implementation this is not possible... the alternative would be to not play the bouncing animation... of course by disabling all animations this issues does not occur

**Comment by andrevmatos** [comment]
Oh, thanks! Did a initial search, but missed the terms it was put on that issue, and couldn't find it. Looking ahead for it to be fixed upstream, the animations are very fancy, would be a shame to have to disable it. Thank you for your great work and time spent on this.

**Comment by psifidotos** [comment]
@audoban @andrevmatos I tried to workaround the libtaskmanager nasty behavior by orchestrating the animations etc... please try branch **fix349** if you use plasma 5.9 and provide me some feedback... in my system it is ok... the application is started directly and the launcher animation is played...

**Comment by andrevmatos** [comment]
I'm getting segfault with fix349, and not in master. I'll setup debug env to get where it is segfaulting.

**Comment by psifidotos** [comment]
@andrevmatos be sure to clean first the build directory in case something isnot updated properly during building...

**Comment by andrevmatos** [comment]
@psifidotos Ok, weirdly, after restarting plasma, everything is working fine. No more segfaults, and your fix worked like a charm. Only minor detail is that, if mouse cursor is in the left half of the icon on click, icon during animation is shifted to the right some 0.3x icon width. If the cursor is in the right half, animation is centered as usual.

**Comment by psifidotos** [comment]
@andrevmatos is it possible to provide me a video because I can not reproduce the issue?

**Comment by andrevmatos** [comment]
Of course, here it is: https://gfycat.com/ContentShimmeringKakapo
Please, note the horizontal alignment of the icon when clicked in the right side and when clicked in the left side. Maybe something related to the model, some dummy/transparent item in the left, not sure, but this "alignment" thing happens every time.

**Comment by psifidotos** [comment]
@andrevmatos can you check please? I protected some when an item is not visible to set width and height to 0...

but I believe that issue is something different... but lets give it a try... with master branch can you make also a video to compare?

**Comment by andrevmatos** [comment]
Issue persists in current head of fix349 branch. Here is a video from master, same actions: https://gfycat.com/FabulousWhiteAustralianshelduck

**Comment by psifidotos** [comment]
does this occur with all launchers or only with that one that opens its window too fast ?

**Comment by andrevmatos** [comment]
Occurs with all launchers, except the left-most/first one (in my case, Dolphin). Happens even with apps that delays a lot more to open than pavucontrol. In all launchers (except the first), clicking in the right half doesn't trigger the issue, but clicking in the left half does, always (in every click, in every launcher except first one). Moving another launcher (e.g. konsole) to the first place makes it to not trigger the issue, and dolphin, now in second, triggers the bug.

**Comment by psifidotos** [comment]
@andrevmatos please give this one more try... trying to debug this I found a nasty situation... ListView anchors its childrens very strange in some siturations... this patch fixes for me 2-3 cases that the animations werent aligned completely correct...

**Comment by psifidotos** [comment]
the commits in fix349 were so important for the animations that should be in master... :) the animations alignment has been improved vastly...

only small issue in my system is that executing a launcher of an app that is heavy to start, the animation is not so smooth... but this could be of my very slow system... if this infects more people I can try to add the execution code into a separate thread...

**Comment by andrevmatos** [comment]
Woow, it's perfect! Tested current master branch here, and it's flawless. Thank you very much for your work on this! Latte Dock is an awesome gift for the whole KDE community! Thank you again.

**Comment by Petross404** [comment]
@psifidotos So let's say a heavy app is Libreoffice and it's animation is jerky? I test this...

**Comment by psifidotos** [comment]
@andrevmatos based on this... the fixes and issues discovered based on Qt are so important that I could create a blog for them... :) (especially ListView faulty behavior :) )

**Comment by psifidotos** [comment]
@Petross404 tell me your results... :)

**Comment by Petross404** [comment]
Yes, there if there is a slight delay\higher load in my system the animation is a little jerky . Noticable but not irritating

**Comment by psifidotos** [comment]
We have some ideas how to deal with it...
