### ISSUE TITLE
Tremor with zoom effect

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#35]
Icons tremble with the zoom effect.

**Comment by psifidotos** [comment]
in all cases **or** with specific behavior?

**Comment by audoban** [comment]
It is very subtle, but it begins to be noticed more when you have many icons.

**Comment by psifidotos** [comment]
latest master you can disable shadows.. Can you check it if this is because of the shadows?

**Comment by audoban** [comment]
It's not the shadows. it's fault of launchers of plasma, not smart launchers.

**Comment by audoban** [comment]
What do you think if we only allow smart launchers?

**Comment by psifidotos** [comment]
> It's not the shadows. it's fault of launchers of plasma, not smart launchers.

ok...

> What do you think if we only allow smart launchers?

I dont know, there could be users and use cases that might need them. Either way is the user that adds them and not our fault about their perfomarnce. I would prefer to let them be but advice our users that have problem to use the smart launchers

**Comment by audoban** [comment]
> I dont know, there could be users and use cases that might need them. Either way is the user that adds them and not our fault about their perfomarnce. I would prefer to let them be but advice our users that have problem to use the smart launchers

I think that is not problem, the smart launcher offers more functionality

**Comment by psifidotos** [comment]
> I think that is not problem, the smart launcher offers more functionality

doesnt that break also the Places shortcuts, when the user wants to add a specific directory shortcut in the dock?

there is also the locked state... 
If the user wants the plasmoid for its own reasons, can keep it in any edge wants and locked it in order to not break the animation experience

**Comment by audoban** [comment]
The menu branch not build for me. 
```
/home/audoban/Documentos/Dev/desktop-projects/Latte-Dock/app/dockview.cpp: En la función miembro ‘bool Latte::DockView::tasksPresent()’:
/home/audoban/Documentos/Dev/desktop-projects/Latte-Dock/app/dockview.cpp:479:40: error: ‘class Plasma::Applet’ no tiene un miembro llamado ‘pluginMetaData’
         KPluginMetaData meta = applet->pluginMetaData();
                                        ^
/home/audoban/Documentos/Dev/desktop-projects/Latte-Dock/app/dockview.cpp: En la función miembro ‘virtual void Latte::DockView::mousePressEvent(QMouseEvent*)’:
/home/audoban/Documentos/Dev/desktop-projects/Latte-Dock/app/dockview.cpp:697:44: error: ‘class Plasma::Applet’ no tiene un miembro llamado ‘pluginMetaData’
             KPluginMetaData meta = applet->pluginMetaData();
                                            ^
/home/audoban/Documentos/Dev/desktop-projects/Latte-Dock/app/dockview.cpp:712:56: error: ‘class Plasma::Applet’ no tiene un miembro llamado ‘pluginMetaData’
                         KPluginMetaData meta = applet->pluginMetaData();
                                                        ^
app/CMakeFiles/latte-dock.dir/build.make:230: recipe for target 'app/CMakeFiles/latte-dock.dir/dockview.cpp.o' failed
make[2]: *** [app/CMakeFiles/latte-dock.dir/dockview.cpp.o] Error 1
CMakeFiles/Makefile2:231: recipe for target 'app/CMakeFiles/latte-dock.dir/all' failed
make[1]: *** [app/CMakeFiles/latte-dock.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by audoban** [comment]
> EDIT: Playing around with the new menu branch, do you mean disabling dragging from the plasmoid to the containment ? I think this can be disabled... I thought you were meaning to disable the launchers/places plasmoid totally...

I like the idea of not allowing drag from the plasmoid to the container.

**Comment by psifidotos** [comment]
> please don't use deprecated functions.

these are not deprecated functions... Are u still using Frameworks 5.26 ??? applet->pluginMetaData() was introduced at 5.27

**Comment by psifidotos** [comment]
> I like the idea of not allowing drag from the plasmoid to the container.

ok, this is feasible I think...

**Comment by audoban** [comment]
> Are u still using Frameworks 5.26

yes I still use, 

> these are not deprecated function
You have reason, I confused with [pluginInfo()](https://api.kde.org/frameworks/plasma-framework/html/classPlasma_1_1Applet.html#a5e0d3b3e734f80aa5a1fdfee3ff24427)

But you can use ```applet->kPackage().metadata() ``` instead ```applet->pluginMetaData()```

**Comment by psifidotos** [comment]
I have just updated menu branch... it should compile fine now with KF 5.26

**Comment by audoban** [comment]
I can't show configuration UI, because I don't have QtQuick 2.7

The maximum version that you can use with KF 5.26 and Qt 5.6, is QtQuick 2.6

**Comment by psifidotos** [comment]
> I can't show configuration UI, because I don't have QtQuick 2.7

I dropped it then and updated both master and menu...

I wanted the choices in the Tasks to be a little more to right... I will find another way to support this visual...

**Comment by audoban** [comment]
you can still use QtQuick 2.6, In order to the end the minimum version that supports Latte is Plasma 5.8 with KF5 2.26

What feature of Qtquick 2.7 you need?

**Comment by psifidotos** [comment]
> What feature of Qtquick 2.7 do you need?

I needed leftPadding from Column, I implemented it with a Row, it works ok now, and I updated menu and master...
