### ISSUE TITLE
Preloaded Layouts for Latte 0.6

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#350]
Some users asked for the different layouts from the video of the release announcement...

I will upload here some from my personal toolbox that use very regular plasmoids:
[MyProfiles.zip](https://github.com/psifidotos/Latte-Dock/files/888568/MyProfiles.zip)

you should extract the zip file, it contains:
- Default
- Unity
- Plasma
- MyFavourite

**Comment by psifidotos** [comment]
_a user asked for a layout with no Latte plasmoid in it..._

_Experimental - Default Latte - NoTasks :_  [Default-NoTasks.zip](https://github.com/psifidotos/Latte-Dock/files/888687/Default-NoTasks.zip)

**Comment by psifidotos** [comment]
this is from now on build in the Appearance page...

**Comment by JenaPlinsky** [comment]
Hi @psifidotos 
You can always leave me amazed. ;)  compliments !!!
just a few questions
Where, the rc files are saved ?
If I export my configuration to that folder, the combo box, can you read it  ( i mean  rc files array) ?
In that case the "import" button could be replaced by the user-selected configuration, right ?

**Comment by JenaPlinsky** [comment]
**Out of topic discussion**
You might even think of adding to the autostart, a cron script to monitor the Latte process, and if it drops the ability to load the last used configuration or the default one


wathcdog process:
```
if [ -z "$(pgrep latte-dock)" ];   then
     echo "Do you want reload Latte with its  default configuration ?" 
     latte-dock 
fi
```

**Comment by JenaPlinsky** [comment]
For each preset configuration is possible import or maintain the previous pinned tasks ?

**Comment by psifidotos** [comment]
@JenaPlinsky thank u! ;) this is of course a combined work of me and @audoban ...

some infos concerning this...

1. Latte provides 4 default layouts(Default, Plasma, Unity, Extended). these are located inside the Latte shell tree and should never be changed in my opinion...
2. the user is able to export its current configuration anytime he wants by using the "Export" button and he can places it wherever he wants (as a backup for example)
3. the user is able to import any configuration he wants (either from its backups or from other users) by using the "Import" button. In such case the new layout is imported and there is always available as a 5th, 6th layout from the Layouts Combobox
4. if the user wants to delete any of its own layouts he can just delete them from the filesystem. In such case these layouts wont be shown again in its Layout combobox.
5. if the user loads one of its old layouts inside the combobox then this layout will go on the top of the user layouts (this is the 5th position in the layuouts combobox)
6. all the paths for the user layouts are stored in a third config file in the .config directory called: lattedockextrc 

I hope these answer most of the questions... if you want more infos please ask.. ;)

> You might even think of adding to the autostart, a cron script to monitor the Latte process, and if it drops the ability to load the last used configuration or the default one. wathcdog process: ( maybe with a parameterized option)

this is @audoban code so I dont have any influence in it.. :) but in general I am not that fond of watchers...

**Comment by JenaPlinsky** [comment]
Your explanations are clear and meet perfectly with what I would expect from Latte !!!
Latte's combo box not only shows embeded layouts but also loads those imported !! ... Well, Ehehheeheh 👍 I was thinking, that milk read all the rc files placed inside its root directory, so I had moved everything inside there    
 .. your solution is smarter and the user can thus, choose to save its rc files everywhere he wants

@psifidotos  @audoban  Guys I like it ...Let's keep it up

**Comment by psifidotos** [comment]
in the future the v0.6 layouts can be found at: https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-are-there-preloaded-layouts-for-latte-v06
