### ISSUE TITLE
Tasks screen filtering doesn't work in plasma 5.8

### ISSUE THREAD

**Issue by quarckster** [psifidotos/Latte-Dock#351]
Version 0.6
I have two docks on each screen and I have checked "Show only tasks from current screen". Nevertheless both docks show all tasks.

**Comment by psifidotos** [comment]
Reproduce same layout with plasma panels does it work ok for you?

**Comment by quarckster** [comment]
Plasma panels work as expected. I have a panel on each screen and each panel shows only tasks from current screen.

**Comment by psifidotos** [comment]
strange we use the same libs... 

Give us some info about your system, plasma versions and your screens layout

**Comment by quarckster** [comment]
openSUSE 42.2
plasma 5.8.6
frameworks 5.26
qt 5.6.1
![screenshot_20170403_123421](https://cloud.githubusercontent.com/assets/1011257/24605662/041fdc4e-186a-11e7-8c4a-d573437d2995.png)

**Comment by psifidotos** [comment]
Ok... i think, this is our fault... plasma 5.8 uses different screen filtering than 5.9... we should support both for Latte 0.6...

If you run, latte-dock -d
debug messages are appearing... one of them should be about screenGeometry that doesnt exist...

Are you capable of testing a branch that i can try to fix this?

**Comment by psifidotos** [comment]
the fix will be included at 0.6.1 and later versions
or
you can just try it now but building and installing the project by yourself...
