### ISSUE TITLE
Pressure based reveal instead of time based

### ISSUE THREAD

**Issue by mooop12** [psifidotos/Latte-Dock#352]
It would be nice to see a pressure based implementation of dock revealing, something like Gnome's Dash-to-Dock has.

**Comment by psifidotos** [comment]
@mooop12 I am sorry but I dont understand... can you describe more the behavior you are proposing?

**Comment by mooop12** [comment]
In dash-to-dock, when you move the cursor to the edge of the screen the dock doesn't appear based on a delay, you have to move the cursor "into" the edge with more force and then it appears.

I found this behavior to be faster, a more decisive move of the mouse towards the edge always showed the dock (without the delay), but when I needed to click something near the edge, a slightly slower mouse move didn't show it (the "pressure" threshold is configurable).

**Comment by audoban** [comment]
@psifidotos @mooop12 I understand the feature, I think I can it, this feature also has it Plank.

@psifidotos This feature should be implement from VisibilityManager.

**Comment by psifidotos** [comment]
@audoban no problem... of course new features only in master and not in branch v0.6

**Comment by audoban** [comment]
@psifidotos @mooop12 Hello again, the feature edge pressure is almost ready, still needs several improvements but is usable. My next step is add multiscreen support, and do the **pressure threshold configurable**

**Comment by psifidotos** [comment]
nice!!

Can you give some infos what do you mean by multiscreen?

**Comment by audoban** [comment]
@psifidotos if a dock change of screen, then the barrier(edge pressure) should follow the dock.

**Comment by psifidotos** [comment]
Oh... ok! interesting!

**Comment by psifidotos** [comment]
Some cases that you can test in order to check the feature's multi screen behavior for consistency and not crashes

- add a dock on explicit screen, restart Latte
- set a dock to primary screen and close that screen from systemsettings, the dock should move on the next primary screen
- try again the above behavior but this time on the next screen should exist an explicit dock that prevents the primary dock to take up that edge

**Comment by audoban** [comment]
I'll take your suggestions into account, and I'll be careful.

**Comment by JenaPlinsky** [comment]
I tried, this your new feautures, and I must say, it works very well ... congratulations !!! maybe one day, you can add to this your new feauture a placeholder with the same mechanism that you've implemented just now

You will leave the user the possibility to choose between timers or pressure?

**Comment by audoban** [comment]
@JenaPlinsky thanks for your feedback.  :)

> You will leave the user the possibility to choose between pure timers or timers and pressure?
Yes, the user can choose between showTimer and edgePressure.

**Comment by psifidotos** [comment]
@audoban is this going to be enabled by default or is it just for tech preview in the pressure branch?

**Comment by audoban** [comment]
Is enabled for default, while I continue with the devel.

**Comment by mooop12** [comment]
Any news on when this will be merged? I've been using the dock-pressure branch since April, it seems to be working fine, it's only missing configuration.

**Comment by JenaPlinsky** [comment]
I like too

**Comment by psifidotos** [comment]
this feature is not going to be at 0.7 and I dont know if there are any plans for 0.8

it depends totally on @audoban , personally I would just drop it....

**Comment by psifidotos** [comment]
as Latte now supports kwin edges then this should be added directly to kwin support
