### ISSUE TITLE
Notify user that compositing is not enabled

### ISSUE THREAD

**Issue by bulldog98** [psifidotos/Latte-Dock#354]
If you start latte-dock and have no compositing enabled, you should be notified that you should enable it. I was not aware that I had turned it off and was wondering why it had such interesting effects. (Panel full size etc.)

**Comment by psifidotos** [comment]
@bulldog98 did you notice in no compositing something very strange that shouldnt happen with Latte ?

**Comment by bulldog98** [comment]
Yes if you have something in fullscreen there will be a small bar where the dock is and if you disable the background you get this wierd texture I've seen in some other closed issue.

**Comment by psifidotos** [comment]
can you make screenshots to understand what you are describing ?

**Comment by psifidotos** [comment]
I dont think we will support it...
