### ISSUE TITLE
Request for new visibility policy: Windows Go Below

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/Latte-Dock#355]
Standard plasma applets have this option, which is like always-show, except that it does not reserve screen space, and instead is painted over any other windows.

**Comment by psifidotos** [comment]
If i remember correctly, we had decided to not support this behavior... @audoban am i right?

**Comment by audoban** [comment]
@psifidotos We never wanted to support this feature seem too intrusive.
@AndydeCleyre Do you want add some behavior special to this mode, to make it less intrusive. Maybe a shortcut for hide or show the Dock, I don’t know, what do you want?

I will to accept this request if do you have any idea to give added value?

**Comment by psifidotos** [comment]
@audoban when we had decided in our conversation through telegram in the early steps of the project which visibility modes to support I had mentioned "Windows Go Below" because Now Dock was supporting it and plasma panels of course... the discussion lead that there is no added value for the user... personally I would never use it as it is very intrusive....

**Comment by psifidotos** [comment]
@audoban i am thinking that it should be pretty easy supporting it as it is just a dock that never hides and it doesnt use struts...

the idea about the always-on-top button either at the window titlebar or from a plasmoid like Active Window is also a good one...

The fact that a sixth visibility mode will make Behavior page look nicer is also a good argument... :)

**Comment by audoban** [comment]
@psifidotos We need an accurate idea to improve the feature and will make it more useful. Because whenever that a user use Always On Top should add Active Window plasmoid?

**Comment by psifidotos** [comment]
@audoban i was imagining it more like the always visible mode, the always on top windows are shown above the dock

**Comment by AndydeCleyre** [comment]
@audoban I wouldn't want to be forced to use the active window plasmoid . . .

**Comment by audoban** [comment]
@psifidotos finally is the same behavior that have plasma panel?

**Comment by psifidotos** [comment]
@audoban sorry i didnt understand, what do u mean?

**Comment by audoban** [comment]
@psifidotos The behavior of WindowsGoBelow will then be the same as the plasma panel

**Comment by psifidotos** [comment]
@audoban yes of course...

**Comment by psifidotos** [comment]
@audoban some code references for help if you try to implement this...

- creator of dockview,  the addDock of corona checks if the containment is alwaysvisible and passes that flag in the creator of dockview
- dockconfigciew, on hiding the dockconfigview checks if the dock must be recreated according to the old and new values of config window, alwaysvisible mode changes and behaveasnormalwindow option
- the behave as a normal dock window option is disabled on alwaysvisible mode and it should be disabled also on windowsgobelow mode

all the above must be updated to take into account not only the alwaysvisible mode but the windowsgobelow also... this is the way that alwaysvisible mode never uses BypassWindowManagerHint flag correctly

**Comment by psifidotos** [comment]
@AndydeCleyre both features you requested "Windows Go Below" and offset have been added in our master branch... you could try them out...  #355 and # 356

**Comment by AndydeCleyre** [comment]
It's working beautifully, thank you!

**Comment by psifidotos** [comment]
@AndydeCleyre  we would love to have some screenshots from your system using windowsgobelow...

**Comment by AndydeCleyre** [comment]
https://streamable.com/5vkbd

**Comment by psifidotos** [comment]
@AndydeCleyre  it looks and behave lovely!!!

**Comment by AndydeCleyre** [comment]
![screenshot_20170410_122605](https://cloud.githubusercontent.com/assets/1787385/24871819/ead05a64-1de8-11e7-8d71-108d5799e2d6.png)
![screenshot_20170410_122555](https://cloud.githubusercontent.com/assets/1787385/24871824/eae27f5a-1de8-11e7-8cb1-3c7587950801.png)
![screenshot_20170410_122447](https://cloud.githubusercontent.com/assets/1787385/24871822/eada4fb0-1de8-11e7-82e0-0b969bada2c7.png)
![screenshot_20170410_122427](https://cloud.githubusercontent.com/assets/1787385/24871823/eadb8c18-1de8-11e7-89c5-af92bfde9eb7.png)
![screenshot_20170410_122409](https://cloud.githubusercontent.com/assets/1787385/24871820/ead75788-1de8-11e7-8315-7f6891b02db5.png)
![screenshot_20170410_122403](https://cloud.githubusercontent.com/assets/1787385/24871821/ead9531c-1de8-11e7-9a84-d2a4347c7d9b.png)
