### ISSUE TITLE
Request: Set anchor point for alignment options: left, center, right, top, bottom

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/Latte-Dock#356]
Sometimes you want a panel or dock, say, right-aligned, but not at the rightmost edge. Instead it should be possible to right-align to a custom anchor point, which serves at the "right edge" for alignment/placement purposes. The standard plasma panels do this.

**Comment by psifidotos** [comment]
Can you make a use case and mock up that you need an offset?

**Comment by psifidotos** [comment]
@audoban am i correct that we preferred auto-positioning instead of offsets?

**Comment by AndydeCleyre** [comment]
My personal use case depends on #355. I was hoping to recreate a plasma panel I have (well, had, as I started replacing it before I realized this and #355) with latte dock.

The idea in my case is to have a short panel at the top of the screen that is always displayed on top, so that it blends in with any maximized window's title bar.

I have the windows' title bars display the titles from the left, so I want this latte instance anchored at the right (so that as much of the window title as possible is shown without interference). But I don't want it *quite* all the way to the right, because I have a few window title bar buttons displayed in that corner.

So I'd like to right-align the dock, but anchor that right-alignment at the left edge of the window buttons.

Here is an example of this setup working with 2 right-aligned panels at the top: http://i.imgur.com/rkNmAGx.png (2 are used there as a hacky way of forcing the color picker applet to use the smaller icon).

**Comment by psifidotos** [comment]
This can be supported but with an alternative way...
I use the Active Window Applet from:  https://store.kde.org/p/998910/
Active(1) = active window icon and title + double click maximizes the active window
Active(2) = not showing anything + double click maximizes the active window
Active(3) = provides the buttons of the active window (I have enabled them to show only on hovering)

also I have set from Active Window applet the mazimized windows to not show their titlebar...

the top dock is set to Always Visible, Fill mode, 100% background, zoom: 0%,  applet size: 24px, and from tweaks i disabled "decrease applets size when it is needed"

the right dock is self explanatory...


![image](https://cloud.githubusercontent.com/assets/2216474/24632106/9750c5ee-18cb-11e7-9611-b56c28fb9938.png)

**Comment by AndydeCleyre** [comment]
I wouldn't want a top panel always showing the active window's details or controls.

![screenshot_20170403_220555](https://cloud.githubusercontent.com/assets/1787385/24638856/dda5fddc-18b9-11e7-9e62-0bb5375cfa7d.png)
![screenshot_20170403_220533](https://cloud.githubusercontent.com/assets/1787385/24638858/dda682c0-18b9-11e7-8c5d-6eff4f24a6f9.png)
![screenshot_20170403_220419](https://cloud.githubusercontent.com/assets/1787385/24638857/dda60dc2-18b9-11e7-8e9d-994e7e1ca3ee.png)
![image](https://cloud.githubusercontent.com/assets/1787385/24638950/674fdb52-18ba-11e7-9194-30a234f7e0a0.png)

**Comment by audoban** [comment]
@psifidotos the offsets can be supported for Latte, it was done in CandilDock and I think that's is easy.
We can use the offset slider based on percent for avoid the problem of the resolutions, and convert the percent to px for configure the position of dock. 
The only problem I saw with offsets was the complexity of the shrink calculation, I do not know.

**Comment by psifidotos** [comment]
@audoban   the difficult part for the offset would be to update all the calculations for automatic positioning etc... the shrinking mechanism in kust a function in Latte and can be updated easily to take into account the offset...

**Comment by psifidotos** [comment]
my main issue with offset is that in most cases is just to add functionality with no valid use cases

**Comment by AndydeCleyre** [comment]
Let me know if I can convince you that my use case is valid, as it seems more functional and space-saving to me than any suggested alternatives.

**Comment by audoban** [comment]
@psifidotos do you want to decline the feature?

**Comment by psifidotos** [comment]
@audoban I propose to leave it open and see... I sounds logical to support it but it is more difficult to support it correctly .... :) so many cases that the offset must get in the calculations... :) e.g. when we are drawing shadows externally in the dock window... the availableScreenRegion calculations... etc... :) we 'll see...

**Comment by psifidotos** [comment]
#audoban I need your thought a bit in this... 

I believe I can understand offset at Left,Right alignments... for example...
10% offset means that the dock will have that offset and the  100% maximumLength in reality will become in the calculations 90% (is that correct?). I propose the value of offset in such case to be from 0% to 50% (bigger values doesnot make any sense I think as that offset is after the center)

For Center, Justify alignments... 10% offset means that the dock should be moved 10% to the right and the 100% maximumLength will become in the calculations = (50% - 10%) * 2 = 80% (do you agree?). I propose the value of the offset in such case to be from -25% (left) to 25%(right)

**Comment by psifidotos** [comment]
as mentioned in the patch... this a work in progress so the following missing:

> -this patch provides the offset variable for our qml side...
> 
> the offset feature is not complete, the following are missing:
> -expose offset at the dockview
> -use offset in !compositing state
> -update borders by taking into account the offset also
> -update the automatic-positioning to take into account  the offset also

but we will get there...

![image](https://cloud.githubusercontent.com/assets/2216474/24831279/b1d7d6b4-1c9f-11e7-873b-f291fb625500.png)

**Comment by psifidotos** [comment]
only thing remains is correct positioning when we draw shadows externally and in !compositing mode

**Comment by psifidotos** [comment]
ok fixed for both in master...

**Comment by psifidotos** [comment]
everything I checked with latest commits... offset works just fine...

!compositing, draw shadows external, auto-positioning etc... 
the c++ part was much cleaner than what I was guessing in the beginning...
