### ISSUE TITLE
[Crash] - recreating dock for AlwaysVisible mode

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#358]
![image](https://cloud.githubusercontent.com/assets/2216474/24631698/f1062806-18c9-11e7-80c9-ba7e66335388.png)

**Comment by psifidotos** [comment]
@audoban this was introduced with commit 569ad5ab409a4976ace547c5e22e9eb76742f9eb

and specific from line 526-527:

```
    // Make sure the rest of events are handled
    // return QObject::event(ev);
```

by disabling it doesnt crash any more... please take a look... and this must be fixed both for master and v0.6 branches

**Comment by audoban** [comment]
A function without return has a behavior undefined, also the policies of build in openSUSE does not allow create packages without the patch.

**Comment by audoban** [comment]
The documentation of Qt tell us: http://doc.qt.io/qt-5/qobject.html#event

`Make sure you call the parent event class implementation for all the events you did not handle.`

**Comment by psifidotos** [comment]
Of course... but a crash is a crash... you must find a way to not crash and follow the documentation also...

**Comment by psifidotos** [comment]
Steps to reproduce, set a dock to dodge active and close the config window, afterwards set that dock to always visible and close the config window....

Be chance to crash also when removing docks...

**Comment by psifidotos** [comment]
@audoban... meaning also that openSuse package is a crashy one in contrast to the rest that do not use this patch

**Comment by audoban** [comment]
@psifidotos If fix works, I will go patch the package now, please confirm the fix.

**Comment by psifidotos** [comment]
i will be able to test at around 6 hours from now...

**Comment by audoban** [comment]
@psifidotos I keep an eye on your answer, my system no longer crashes

**Comment by psifidotos** [comment]
@audoban It is ok... you can merge...
