### ISSUE TITLE
Request: Add option to use Latte Dock as application launcher only

### ISSUE THREAD

**Issue by AdmcWolfy** [psifidotos/Latte-Dock#359]
Yeah, you read it right. I preffer classic KDE style task manager and want to use Latte Dock only as pretty application launcher :)

**Comment by psifidotos** [comment]
you mean with no windows?

can you provide a screenshot to understand what you are describing? (show in it the plasma taskmanager and the latte one what would you like to  be different)

**Comment by AdmcWolfy** [comment]
I mean I want Latte just to act like "quick launch" widget. No task managing at all, just application launcher.
![obraz](https://cloud.githubusercontent.com/assets/2904627/24664469/0931983e-195b-11e7-98a7-befa7aab9f77.png)

**Comment by AdmcWolfy** [comment]
I mean I want Latte just to act like "quick launch" widget. No task managing at all, just application launcher.
![obraz](https://cloud.githubusercontent.com/assets/2904627/24664469/0931983e-195b-11e7-98a7-befa7aab9f77.png)
It's a pity that latte uses this low-res icon instead of existing hi-res icon, but I can live with that. It's better than showing generic icon :)
![obraz](https://cloud.githubusercontent.com/assets/2904627/24664909/1d65c978-195c-11e7-8982-7e0be3eb78da.png)

**Comment by psifidotos** [comment]
It can be done... import from #330 the Default-NoTasks layout and afterwards drag  n' drop your launchers, they should be added as plasma applets

**Comment by psifidotos** [comment]
If the hovering animation is not smooth you should set the applets size >=64px.

**Comment by AdmcWolfy** [comment]
I'm sorry, I can't find proper .latterc config file to import in #330. Can you provide me direct link to this file?

**Comment by psifidotos** [comment]
Sorry, my mistake, #350 you must unzip it first

**Comment by AdmcWolfy** [comment]
Thank you very much, works like a charm :)
I think those configs should be bundled in next release or option to disable Latte plasmoid should be available.

**Comment by psifidotos** [comment]
@AdmcWolfy please open two different feature requests to discuss it please

**Comment by AdmcWolfy** [comment]
> If the hovering animation is not smooth you should set the applets size >=64px.
Yes, it isn't smooth. I hope it will be fixed in next release :)

**Comment by psifidotos** [comment]
> Yes, it isn't smooth. I hope it will be fixed in next release :)

It is an upstream plasma issue related to the same reasons of #83

Only thing possible is someone to create an alternative launcher plasmoid that uses our Latte.IconItem instead of PlasmaCore.IconItem
