### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#36]
Any language you want to add.

**Comment by audoban** [comment]
I add Spanish support

**Comment by psifidotos** [comment]
nice, greek is already there, but the translataion strings will need an update... The importat translation files are the plasmoid's, and the app's

**Comment by psifidotos** [comment]
updated translation strings in master

**Comment by audoban** [comment]
nice

**Comment by audoban** [comment]
Added spanish translation

**Comment by psifidotos** [comment]
@audoban I think we better accept only Pull Requests for translations produced through Lokalize...

translators need some expertise in order not to break Latte build...

**Comment by JenaPlinsky** [comment]
@psifidotos  I am now following your suggestions ... I'm getting good :)
