### ISSUE TITLE
Bug: Virtualbox icon doesn't display correctly

### ISSUE THREAD

**Issue by AdmcWolfy** [psifidotos/Latte-Dock#361]
I have problem with Virtualbox icon. Latte dock only display generic application icon and unnecessary groups Virtualbox manager and Virtual machine window in one icon.
![obraz](https://cloud.githubusercontent.com/assets/2904627/24660858/0101cea4-1951-11e7-90cb-3954951ebc79.png)

I think that every virtual machine should have another icon like in classic task manager.
![obraz](https://cloud.githubusercontent.com/assets/2904627/24660880/1105b202-1951-11e7-9870-4416ab01a154.png)

**Comment by psifidotos** [comment]
this is relevant to #343, #353 
we hope that at some point for plasma 5.9 we will move entirely at plasma libtaskmanager support for launchers so that plasma taskmanager behavior and ours will be indentical....

**Comment by AdmcWolfy** [comment]
Issue with icons  was temporary bug, after reboot now latte shows correct icon. I also manually disabled window grouping (this is pretty neat workaround).
![obraz](https://cloud.githubusercontent.com/assets/2904627/24664805/de69c2f6-195b-11e7-9af5-18576402a5df.png)
It's a pity that latte uses this low-res icon instead of existing hi-res icon, but I can live with that. It's better than showing generic icon :)
![obraz](https://cloud.githubusercontent.com/assets/2904627/24664909/1d65c978-195c-11e7-8982-7e0be3eb78da.png)

**Comment by psifidotos** [comment]
The icons used are those provided by plasma libtaskmanager... you shouldnt see any difference from icons-only plasma taskmanager

> Maybe you should consider implementing some scaling algorithm like SAI or hqnx for small icons?
https://en.wikipedia.org/wiki/Pixel_art_scaling_algorithms

Feel free to provide patches for liblatteplugin/iconitem.cpp

**Comment by AdmcWolfy** [comment]
Thank you, feel free to close this issue :)
