### ISSUE TITLE
Request: Add backups manager with predefinied configs included

### ISSUE THREAD

**Issue by AdmcWolfy** [psifidotos/Latte-Dock#363]
There should be backups manager (you can choose another name if you want) that allows multiple latte configs management. I made this mockup to better illustrate what I mean:
![obraz](https://cloud.githubusercontent.com/assets/2904627/24667743/bfbdfca6-1964-11e7-9579-ea2439ebd48d.png)

**Comment by psifidotos** [comment]
this must be considered together with: #364

between #363 and #364 I would prefer more #364

**Comment by audoban** [comment]
@psifidotos  I'm also prefer #364, but where do you want to put these options, tweaks?

**Comment by psifidotos** [comment]
Ok... lets close this then... and move to #364
