### ISSUE TITLE
[Request] Add presets layouts styles to Latte : Unity, Plasma, etc.

### ISSUE THREAD

**Issue by 1Claude** [psifidotos/Latte-Dock#364]
I think you should add some presets layouts, like the ones showed at the end of the video : [https://youtu.be/Q-Oof_CRNG4?t=12m16s](url)

Plasma style, Unity style, Simple dock style, etc. 

Something like in MATE Tweak (Ubuntu MATE), for different panel/dock layouts. So that a user can get started right away and tweak later, if they want.

**Comment by psifidotos** [comment]
this must be considered together with: #363 

between #363 and #364 I would prefer more #364

**Comment by audoban** [comment]
@psifidotos I worry that latte will fill options and options.

**Comment by psifidotos** [comment]
@audoban me too... we should be very careful what we add.... concerning #363, #364 they only thing that make sense to me in by adding some how at Import/Export Configuration a third choice for predefined Presets by us (possibly with a drop-down)... this would help users a lot especially with the top dock configuration with which many simple users cant find all the settings to work correctly...

**Comment by 1Claude** [comment]
There are many simple users out there.  😀

**Comment by psifidotos** [comment]
@audoban a very convenient way to add this feature is at the Import Configuration if it was offering a drop-down choice for our predefined presets (I mean only 3-4 choices that we have created e.g. Plasma, Unity etc...) . I am not fond of downloading presets from the internet...

**Comment by psifidotos** [comment]
mockup for Appearance page by adding also the Layouts (presets) in the upcoming basic/advance settings

@audoban what do you think? should this be in basic or advanced mode?

![image](https://cloud.githubusercontent.com/assets/2216474/25307956/436954ae-27b3-11e7-9dee-8c343c790119.png)

**Comment by psifidotos** [comment]
@audoban I can finish the rest of this during the day with one single commit in order to make adjustments if you want... after the vacations :) I  found time to clean and implement things up ... :)

**Comment by psifidotos** [comment]
merged in master... works beautifully... :)
