### ISSUE TITLE
Add option to import/export settings

### ISSUE THREAD

**Issue by Gibbz** [psifidotos/Latte-Dock#367]
It would be great to have an option to import and export settings on the dock. Especially also via command line args.
Either xml or json as a single file or command line. That way a user could roll out a script for a quick install and preconfigured setup for use in an office environment.

**Comment by audoban** [comment]
You can import the configuration from the command line with `latte-dock --import myconfig.latterc`

and also you can import or export the config from the settings: 
![spectacle pe2764](https://cloud.githubusercontent.com/assets/7884292/24780889/cc7a0cf8-1b00-11e7-91c2-c4c6cb80b1ef.png)
