### ISSUE TITLE
allow windows to go behind dock without autohide

### ISSUE THREAD

**Issue by Gibbz** [psifidotos/Latte-Dock#368]
need an option to allow windows to go behind the dock without it auto-hiding like the dodge feature does...

**Comment by audoban** [comment]
You're talking about https://github.com/psifidotos/Latte-Dock/issues/355?

**Comment by cm-s** [comment]
@Gibbz I can move windows behind the dock without it hiding. Latte Dock version 0.5.98 under Behavior > Visibility > Always Visible. I have that setting active.

**Comment by psifidotos** [comment]
I suppose you added latte in the desktop... Latte needs to be run with just the command:

`latte-dock`

if this doesnt work for you then you must find a way to install it properly in your system... easiest way is to find an prebuilt package for your disto...
