### ISSUE TITLE
Adding a plasmoid is not possible in any isHidden State (AutoHide most importantly)

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#37]
If the dock is hidden and the user tries to add a plasmoid by dragging into the edge the dock is, _the dock is not appearing_ , in order for the user be able to complete the procedure...

**Comment by audoban** [comment]
This has to do with drag events. Now visibility manager handles this, and you do not need any kind of logic in plasmoid or containment.
