### ISSUE TITLE
Latte-Dock exited normally... 

### ISSUE THREAD

**Issue by cirelli94** [psifidotos/Latte-Dock#370]
When I open the settings, default option is that settings pane is pinned.
I don't noticed that so I press `exit` every time to close it and I could not understand why latte-dock was crashing!
Hell, I opened ddd and I understand that that exit was a close all latte-docks! Not a bug!
So I thought, why do not change everything to be more similar to other panels in KDE?
This, can be a little confusing!
Don't know, just wondering.
Thanks.
A mate who spend a little bit of his time understanding who was wrong.

**Comment by psifidotos** [comment]
> When I open the settings, default option is that settings pane is pinned.

1. the pin option for configuration window is not default... are you sure you havent clicked it by yourself when trying Latte? for example hit the Add button to add a new dock and go to its configuration window, for the new dock the configuration window shouldnt be pinned

2. if you hit the Quit button and latte is closing(closing all docks) that is the default behavior and normal... but if it crashes then this is a bug and we must fix it!!!

**Comment by cirelli94** [comment]
@psifidotos 
1. Don't know, really! I hope that is not default! If I open a new one, it isn't pinned by default!
2. Nice, I just don't understood the default behavior, since is different from normal kde!

HOWEVER THANKS FOR THE WONDERFUL WORK!
