### ISSUE TITLE
support Layout.fillWidth and Layout.fillHeight for applets

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#371]
until now we are supporting Layout.minimum/preferred/maximum widths and heights for the applets in the dock... Their values are used in order to provide the best way to present and interact correct with a plasmoid. Based on their values for example an applet can be categorized as not able to be hovered because its appearance would break...

for the next round of development I am confident that I have found a way to support correctly the fillWidth (for horizontal docks) and fillHeight (for vertical docks)...

this would be a very big step forwards because if the effort succeeds the Latte will be on par with plasma panels on presenting its applets.. .

**Comment by psifidotos** [comment]
three active window applets all with fillwidth enabled... ;) some of them to the left layout and some to the right... :) a very sophisticated code supporting this... but it worths the effort... I havent added yet how things are calculated when the are applets in the center but one step at a time...

![image](https://cloud.githubusercontent.com/assets/2216474/24817798/8bafcef6-1be6-11e7-9bca-1c86d05db38e.png)

**Comment by psifidotos** [comment]
ok... done... ;)  a fantastic Justify mode... ;) centered date and fillWidths work correctly for ActiveWindow... do you know any other plasmoids that use fillWidth in order to test???

![image](https://cloud.githubusercontent.com/assets/2216474/24823929/99b8b316-1c0c-11e7-9338-c498289a4ba0.png)

**Comment by audoban** [comment]
@psifidotos fantastic job 👍
