### ISSUE TITLE
Minor Errors when running applications from modified .desktop files

### ISSUE THREAD

**Issue by cm-s** [psifidotos/Latte-Dock#374]
I have modified the kdesystemsettings.desktop and systemsettings.desktop file's Exec properties to include a modified LANG environment variable. I prepended `nohup` to the beginning and `&` to the end of the command to prevent the dock from hanging. Still I get "KDEInit: Cannot start "/bin/sh" just after the application starts.

**Comment by psifidotos** [comment]
what plasma version?
does the plasma taskmanager work ok with them?

**Comment by cm-s** [comment]
Plasma 5.9. Latte Dock version 0.5.98. I just modified it (org.kde.ksysguard.desktop), and the same error occurred just before the application opened.

**Comment by cm-s** [comment]
I downloaded the stable devedition. `neon-devedition-gitstable-20170321-1047-amd64.iso` to be exact.

**Comment by psifidotos** [comment]
@cm-s  add a regular icons-only plasma taskmanager in your desktop and afterwards try your launchers... is everything working ok ?

**Comment by psifidotos** [comment]
@cm-s  you could try also the branch **launchers59** to provide us feedback based on the new launchers implementation... as long as plasma taskmanager works ok with you then Latte will also...

**Comment by cm-s** [comment]
@psifidotos launching the same app from the native application menu works smoothly. I tried deleting my current Latte Dock configuration and opening the app from a fresh one to find the same error occurs.

**Comment by psifidotos** [comment]
@cm-s you can try the **launchers59*" branch which is going to be merged in a week, it should fix your issue

**Comment by cm-s** [comment]
I just installed the launchers59 version over top of the one I cloned from master to begin with. Once again the same error occurred. I launched the dock from Konsole, so I could include my complete output below, should it be helpful. 
```
computer:[root]@Latte-Dock (pts/1)# latte-dock --replace
Config timer connecting...
Setting the name of  0x1277c10  to  "org.kde.ActivityManager.ActivityTemplates"
Setting the name of  0x12833b0  to  "org.kde.ActivityManager.Resources.Scoring"
Creating directory:  "/root/.local/share/kactivitymanagerd/resources/"
KActivities: Database connection:  "kactivities_db_resources_140389460089024_readwrite" 
    query_only:          QVariant(qlonglong, 0) 
    journal_mode:        QVariant(QString, "wal") 
    wal_autocheckpoint:  QVariant(qlonglong, 100) 
    synchronous:         QVariant(qlonglong, 1)
Setting the name of  0x128eff0  to  "org.kde.ActivityManager.RunApplication"
Service started, version: 7.0.0
Cleaning up...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 5514, result = 0
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
kdeinit5: opened connection to :0
kdeinit5: Got EXT_EXEC '/bin/sh' from launcher.
kdeinit5: preparing to launch '/bin/sh'
kdeinit5: PID 5518 terminated.
The desktop entry file "/usr/share/applications/display-im6.desktop" has Type= "Application" but no Exec line
kf5.kservice.sycoca: Invalid Service :  "/usr/share/applications/display-im6.desktop"
The desktop entry file "/usr/share/applications/display-im6.q16.desktop" has Type= "Application" but no Exec line
kf5.kservice.sycoca: Invalid Service :  "/usr/share/applications/display-im6.q16.desktop"
```
On another note, I found a few things odd; The version in the settings GUI was 0.6.0 as opposed to 7.0.0 in the output, the app icon was also invisible, and the styling of the app after it opened differed from my system's theme as well.

**Comment by psifidotos** [comment]
make a fresh config to test with the **launchers59** branch... as long as the problem remains then you should have the same problem with the icon-only plasma taskmanager and you should report upstream, not the app menu launcher they are different...

**Comment by cm-s** [comment]
Sorry, I don't have enough experience with git or KDE. So your telling me to start a new issue, where exactly?

**Comment by psifidotos** [comment]
If you add in your desktop the icon-only taskmanager of plasma which is inside the plasma widgets explorer do you have the same issue?

**Comment by cm-s** [comment]
With one of the desktop widgets, the same error happens.

**Comment by psifidotos** [comment]
So this is a plasma taskmanager issue that you can report at bugs.kde.org
