### ISSUE TITLE
Hiding Latte when a scroll bar is activated

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#375]
When Visibility mode is set as "Always visible" ...
I think it would be right and wise to hide the dock when the user tries to scroll up and down a browser's page or any other app

You might think so too, to not dodge, the dock when windows are maximized
![screenshot_20170408_032617](https://cloud.githubusercontent.com/assets/24593950/24824446/8dc92532-1c0b-11e7-8aca-8a030fea248f.png)
![screenshot_20170408_031740](https://cloud.githubusercontent.com/assets/24593950/24824447/8f5d1d36-1c0b-11e7-8d55-d433346a186f.png)

**Comment by audoban** [comment]
@JenaPlinsky Impossible I can not receive events from other windows for latte, I can not know if the user scrolls with the mouse

**Comment by JenaPlinsky** [comment]
is it  possible, receive an event from the mouse wheel ?

**Comment by audoban** [comment]
@JenaPlinsky a mouse event just is send to active window, with the exception of some like enter or leave. And wheel event is no exception, a wheel event is send to window under mouse. Each type of mouse event can have a different behavior, but they are not totally global.

**Comment by audoban** [comment]
Maybe it's possible with some kind of hack with XCB, but it is probably impossible to do with wayland because its have a high emphasis on security.

**Comment by psifidotos** [comment]
@JenaPlinsky @audoban 

I dont understand... if the user chooses "Dodge Active" mode then when he tries to scroll a page the dock should become hidden because that window becomes the active...

Did I miss something?

**Comment by audoban** [comment]
@psifidotos What he wants is that when Visibility is set as Always Visible, @JenaPlinsky wants that latte dock hide automatically if the user is doing scrolling, but is impossible know if the user is doing scroll why the event just is sent to active window.

**Comment by JenaPlinsky** [comment]
This type of behavior is used on Android .... when a notification covering the browser .... moving up and down the page, the notification disappears temporarily improving the readability of the page

**Comment by psifidotos** [comment]
@audoban I see... I think we can just close this... in my opinion this is why dodge modes exist, for users that do not want the dock to intrude... :) alternatively in AlwaysVisible mode the user can just set its window to ShowOnTop and that window will cover the dock...

my case is that I have set for my kwin titlebars the scrolling mechanism... the i scroll up into the window titlebar the window becomes "always on top" and when I scroll down into the window titlebar the window removes the flag for "always on top"
