### ISSUE TITLE
Plasmoid to sub-group launchers / applets

### ISSUE THREAD

**Issue by s8321414** [psifidotos/Latte-Dock#377]
As title says, cairo-dock also has this feature, if Latte-Dock has, that will be awesome! 😃

**Comment by psifidotos** [comment]
What is a sub dock?

**Comment by s8321414** [comment]
@psifidotos https://farm6.static.flickr.com/5228/5572455209_6afd01ea1e_b.jpg
http://download.tuxfamily.org/glxdock/communication/images/3.1/png/1.png
https://creeperslayersite.files.wordpress.com/2012/10/neon_cairo_dock_by_bit72.png
http://download.tuxfamily.org/glxdock/mediacolor/album3/1295660551_edbecb8257_big.jpg
Like these

**Comment by psifidotos** [comment]
is it only for launchers ?

**Comment by s8321414** [comment]
on cairo-dock, it is also for applet

**Comment by psifidotos** [comment]
hard staff... i wish someone will implement such plasmoid then....

**Comment by audoban** [comment]
@psifidotos It sounds really hard.

**Comment by audoban** [comment]
@psifidotos maybe a plasmoid can solve it.

**Comment by psifidotos** [comment]
yep... a plasmoid like the systray... pretty hard staff... maybe for Latte 0.11 in my regard... 😃

**Comment by audoban** [comment]
@psifidotos It is a very large feature.

**Comment by shvchk** [comment]
Maybe a Folder view widget could be used as a not so fancy, but functional alternative?

**Comment by psifidotos** [comment]
Of course it can... @JenaPlinksy already uses it that way...

**Comment by tofuhead** [comment]
@shvck: I'm actually using just regular folderview for this kind of feature. I have a folder with just some .desktop entries in there.. works fine.. only wish would be that Latte could open that plasmoid automaticly on hover, now I have to click it ... but.. you know.. it's just one click :) 
[http://pasteall.org/pic/show.php?id=114829](http://pasteall.org/pic/show.php?id=114829)

.b

**Comment by audoban** [comment]
I think that the folder view supply perfectly this need.

@psifidotos Do you want to close this issue?

**Comment by psifidotos** [comment]
yeah no prob...
