### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by thecountoftuscany** [psifidotos/Latte-Dock#379]
I am running KDE Neon 5.9.4 and I installed all the dependencies as mentioned in INSTALLATION.md. But the installation fails with:
`Linking CXX executable latte-dock
/usr/lib/x86_64-linux-gnu/libKF5PlasmaQuick.so.5.32.0: undefined reference to 'qt_version_tag@Qt_5.7'
/usr/lib/x86_64-linux-gnu/libKF5XmlGui.so.5.32.0: undefined reference to 'QIODevice::isTransactionStarted() const@Qt_5'
//usr/lib/x86_64-linux-gnu/libphonon4qt5.so.4: undefined reference to 'QJsonObject::value(QLatin1String) const@Qt_5'
/usr/lib/x86_64-linux-gnu/libKF5Notifications.so.5.32.0: undefined reference to 'QGuiApplication::desktopFileName()@Qt_5'
/usr/lib/x86_64-linux-gnu/libKF5PlasmaQuick.so.5.32.0: undefined reference to 'QIcon::fromTheme(QString const&)@Qt_5'
/usr/lib/x86_64-linux-gnu/libKF5Package.so.5.32.0: undefined reference to 'qt_QMetaEnum_flagDebugOperator(QDebug&, unsigned long, int)@Qt_5'
/usr/lib/x86_64-linux-gnu/libKF5Plasma.so.5.32.0: undefined reference to 'QJsonValue::toString() const@Qt_5'
/usr/lib/x86_64-linux-gnu/libKF5XmlGui.so.5.32.0: undefined reference to 'QListWidget::setSelectionModel(QItemSelectionModel*)@Qt_5'
/usr/lib/x86_64-linux-gnu/libKF5XmlGui.so.5.32.0: undefined reference to 'QString::resize(int, QChar)@Qt_5'
collect2: error: ld returned 1 exit status
app/CMakeFiles/latte-dock.dir/build.make:501: recipe for target 'app/latte-dock' failed
make[2]: *** [app/latte-dock] Error 1
CMakeFiles/Makefile2:341: recipe for target 'app/CMakeFiles/latte-dock.dir/all' failed
make[1]: *** [app/CMakeFiles/latte-dock.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2`
at the end of the output. Also, it shows `./install.sh: 10: [: -a: unexpected operator` at the beginning.

**Comment by audoban** [comment]
You probably have a problem with your Environment variables, please read this thread https://github.com/psifidotos/Latte-Dock/issues/203.

All dependencies are satisfied in your system, but you have a erroneous configuration.
`undefined reference to 'qt_version_tag@Qt_5.7'`

**Comment by thecountoftuscany** [comment]
From that thread, I only understood that @lkwq007 faced the same problem as I but did not get how it was solved. He seems to be running ArchLinux and there was some problem with an AUR package I am not running Arch. Sorry if it was obvious or trivial, I am new to linux.

**Comment by psifidotos** [comment]
@thecountoftuscany  what distro are you using ?

**Comment by thecountoftuscany** [comment]
I am running KDE Neon 5.9.4

**Comment by psifidotos** [comment]
You can try a prebuilt package: http://www.ubuntuvibes.com/2017/04/first-stable-build-of-latte-dock.html

**Comment by thecountoftuscany** [comment]
@psifidotos That worked. Thanks.

**Comment by lkwq007** [comment]
> From that thread, I only understood that @lkwq007 faced the same problem as I but did not get how it was solved. He seems to be running ArchLinux and there was some problem with an AUR package I am not running Arch. Sorry if it was obvious or trivial, I am new to linux.

@thecountoftuscany 

`undefined reference to 'qt_version_tag@Qt_5.7'`
Hi. This problem is not system-related. I think that you should check which version of qt is used by qmake. In your case, you need at least qt 5.7 used by qmake. 

( English is not my mother tongue, sorry for my poor English.
