### ISSUE TITLE
Latte plasmoid settings appearance section is blank

### ISSUE THREAD

**Issue by Darksurf** [psifidotos/Latte-Dock#380]
appearance section is blank,  Panel, Interaction, and Keyboard Shortcuts works as intended. Clicking the appearance section after viewing another section only results in showing the last section viewed..
I looked in .config but no config file is being generated? Issue is with version 6.0 and 9999 ebuild.
![latte1](https://cloud.githubusercontent.com/assets/13701401/24843431/7410dab4-1d68-11e7-8fce-fa64d7262d50.png)
![latte2](https://cloud.githubusercontent.com/assets/13701401/24843432/74120358-1d68-11e7-8b00-b077cb0f5ba5.png)
![latte3](https://cloud.githubusercontent.com/assets/13701401/24843433/74125d76-1d68-11e7-8249-1446427c6812.png)

**Comment by psifidotos** [comment]
How did you install Latte?

If you run the command latte-dock what happens?

**Comment by Darksurf** [comment]
I've installed both using .6 code with installer script, then uninstalled
and reinstalled using the ebuild. Both have the same issue. There were
reboots between installs/uninstalls.

Running the command launches another dock, except this one is far better
and settings appear to look different yet work.
[image: latte4.png]


On Mon, Apr 10, 2017, 1:17 AM Michail Vourlakos <notifications@github.com>
wrote:

How did you install Latte?

If you run the command latte-dock what happens?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/psifidotos/Latte-Dock/issues/380#issuecomment-292859024>,
or mute the thread

**Comment by Darksurf** [comment]
I actually added the old dock like a plasma widget. I didn't realize it was
a whole separate program.

**Comment by psifidotos** [comment]
Latte is an application so it must be run with the command 'latte-dock' or through your app launcher... the Latte plasmoid is just for reference reasons and it is the one used also for the Latte app (dock)

I cant see the image...
