### ISSUE TITLE
Indicator for unread e-mail messages for e-mail managers

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#381]
I wish I knew how this is achieved from the e-mail manager point of view... :) how an e-mail manager such as thunderbird or kmail publish their unread mails number...

We have a very beauiful indicator concerning tasks progress... Such as when copying files or downloading a torrent... This indicator could be adjusted very beautiful for unread messages...

**Comment by psifidotos** [comment]
ok found it... there are two approaches..

1. the docky way: https://github.com/lpiepiora/docky-thunderbird
a python plugin for thunderbird that connects to docky dbus interface to achieve this

2. the unity way... there was in the past a thunderbird unity plugin... funny thing is that we already support unity tasks through the libtaskmanager implementation so there is a big chance that we already support it but the unity plugin is not working for new versions of thunderbird...

I think the best way is through (1) ... good point for someone to enter the Latte community if he knows python... and we will of course provide the dbus calls to inform us about new e-mails... ;)

we already expose a dbus interface for the Super key feature... ;)

**Comment by audoban** [comment]
Because thunderbird, I think to be consistent we should first support KMail.

**Comment by psifidotos** [comment]
no prob... in our side the code is the same... the thing is who is going to implement the plugins for the mail managers

**Comment by audoban** [comment]
The problem is not who, we should do something that can be extensible and be able to support more email-clients in the future.

**Comment by psifidotos** [comment]
From our side things are clear... just a dbus exposer for the email clients to send their name and the number of unread e-mails... it is also what unity interface is doing and docky also... but all of them need a plugin in the email client... we need a developer to create such plugin for an e-mail client to test out architecture...

**Comment by psifidotos** [comment]
hehe... I managed to import the outdated docky plugin of thunderbird into Latte... ;)

I need to update texts, graphics etc for the plugin but here it is... :) a thunderbird showing its unread e-mails... I will discuss merging the functionality after launchers59 branch has been merged...

![image](https://cloud.githubusercontent.com/assets/2216474/24921644/2f3c5ef8-1ef4-11e7-91e9-83d1c2fc5ac0.png)

**Comment by psifidotos** [comment]
@audoban  concering this i have added a dbus function with which an app can update its badge, the function is,

updateBadgeForItem, string identifier, string value

thunderbird for example sends "thunderbird, 3" //which means three unread mails... do you propose something else?

**Comment by psifidotos** [comment]
include the Latte part... next weeks when I will find time I will publich the thunderbird extension

**Comment by jamtur01** [comment]
Did the extension ever get published? I can't find it anywhere. Thanks!

**Comment by psifidotos** [comment]
@jamtur01 dont hesitate to publish a 0.0.3 version in order to help other users also...

**Comment by jamtur01** [comment]
If you put the source on GitHub (or I can) I'd be happy to PR that.

**Comment by psifidotos** [comment]
@jamtur01 feel free to upload it ... no prob...

**Comment by jamtur01** [comment]
Done:

https://github.com/jamtur01/lattedock-thunderbird

Added a README and some versioning to the build.
