### ISSUE TITLE
Support Places and Jump Lists for Tasks in Plasma 5.10

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#382]
from plasma 5.10 and above the taskmanager supports to show the Places and the JumpLists for Launchers when a window in not shown... there is a chance that this could be added for plasma 5.9 also...

For example right clicking the dolphin launcher should show the Places of the dolphin when right clicking..

**Comment by psifidotos** [comment]
just checked... this is supported by the TaskManagerBackend from plasma 5.10 and above... contacting the plasma devs they proposed be that this is considered a private qml api so it is better to fork it in our code... that of course means that if we fork that class then these features can be supported also in plasma 5.9..

sooner or later the TaskManagerBackend should be changed into LatteTaskBackend

**Comment by audoban** [comment]
And why not wait until the plasma version 5.10 comes out?, We could avoid a fork and also avoid problems that may arise with the library TaskManagerBackend.

**Comment by psifidotos** [comment]
no prob... lets not fork yet the taskmanagerbackend ... i could add the functionality to be activated in the qml side only when it runs above plasma 5.10

**Comment by audoban** [comment]
I agree so we avoided maintain another library.

**Comment by psifidotos** [comment]
ok... this is included for plasma 5.10...

![spectacle t18961](https://cloud.githubusercontent.com/assets/2216474/26143774/0a28714e-3aef-11e7-945e-6e4521b7c014.png)
