### ISSUE TITLE
[Crash] - When quit from latte widget tweaking menu

### ISSUE THREAD

**Issue by maxnick** [psifidotos/Latte-Dock#385]
Crash every time when push "quit" button in latte widget tweaking menu.

GDB OUT:
Thread 1 "latte-dock" received signal SIGSEV, Segmentation fault.
0x00007ffff40ca1da in QFontPrivate::~QFontPrivate() from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5

My system:
linux Mint 18 KDE
Plasma Version: 5.8.5
Qt Version: 5.6.1
Kernel Version: 4.4.52-040452-generic
x86_64
![ddd_backtrace](https://cloud.githubusercontent.com/assets/26419192/24880864/a7822808-1e44-11e7-8649-3a6819c7960a.png)

**Comment by psifidotos** [comment]
Can you install branch v0.6 and try again and see what the backtrace shows? The current backtrace doesnt show infos inside latte code

**Comment by psifidotos** [comment]
@maxnick we uploaded a fix for this in v0.6 branch that was suspicious causing this... we would love to have your feedback...

**Comment by maxnick** [comment]
I had install latte-dock from v0.6 branch and error still persist. DDD backtrace completely similar as attached above.

**Comment by psifidotos** [comment]
You tried latest commit from branch v0.6 and problem persists?

**Comment by maxnick** [comment]
Yes, exactly.

**Comment by psifidotos** [comment]
unfortunately the crash doesnt show any latte code that it is its fault... all the messages are from libplasma and qt... so it is very strange...

**Comment by maxnick** [comment]
M.b. it is bag in Qt libs... Unfortunately i have not experience with Qt.

**Comment by psifidotos** [comment]
@maxnick this is happening also with the default options right? without changing anything in the config window...

we will leave this open and wait for more users to provide feedback and cases...

**Comment by maxnick** [comment]
Yes, it doesn't matter were changes in configuration or not.

**Comment by psifidotos** [comment]
@maxnick what is your kde frameworks version?

**Comment by psifidotos** [comment]
install also your plasma frameworks debug package... your backtrace should be more descriptive afterwards...

**Comment by psifidotos** [comment]
And some feedback in these cases:

1. Add a second dock and remove it from its configuration window, does it crash?
2. When you just hide the configuration window of the dock, does it crash?
3. Go to Alternative Session from the Tweaks page, does it crash?

**Comment by maxnick** [comment]
I left for several days. I'll give you feedback on the next week.

**Comment by maxnick** [comment]
I have KDE frameworks version 5.28.0. It is strange, but in Ubuntu xenial repo  there is a plasma-framework version 5.18.0. dbg package also for 5.18.0 framework version, i can't install it for my version through broken dependency. looks like linux mint developers include another plasma framework version, unlike kubutu xenial, in mint 18 with kde.

**Comment by psifidotos** [comment]
How about the mentioned cases?

**Comment by maxnick** [comment]
In all three test cases crash does not occurred.

**Comment by psifidotos** [comment]
Interesting!!

Can you try the following?

1. use the v0.6 branch
2. In file, app/dockview.cpp replace line 1069 with:

m_dockView->hide();

3. reinstall

does it make any difference?

**Comment by psifidotos** [comment]
Sorry wrong syntax...

**Comment by psifidotos** [comment]
replace with:

m_configView->hide();

**Comment by maxnick** [comment]
I done it. Crash still persist. M. b. i can build latte-dock with dbg symbols and try debug this. But i don't know where set breakpoints

**Comment by psifidotos** [comment]
me neither... it is a plasma frameworks bug propably trigerred by qml, either by our confg window or an applet... but i am just trying to workaround it... the best is to install debug symbols for plasma framework package in order to find the exact function crashing in libplasma... the crash is not from latte c++ code otherwise in the backtrace it would appear the exact point that triggered it...

**Comment by maxnick** [comment]
I see. Unfortunately i can't install plasma-framework-dbg package through version conflict. I'll write to linux mint support team and ask they how to install dbg symbols form plasma framework on mint 18 kde distro.

**Comment by psifidotos** [comment]
@maxnick, i dont know also how acceptable is to use kde frameworks 5.28 with plasma 5.8, there is a chance that 5.26 is the maximum version number proposed for plasma 5.8

**Comment by psifidotos** [comment]
I checked... 5.28 is fine for plasma 5.8

**Comment by rikmills** [comment]
Edit the sources to add debug packages for FW and plasma versions for Mint:  sudo nano /etc/apt/sources.list.d/ubuntu-defaults.list
Add the line 'deb http://ppa.launchpad.net/kubuntu-ppa/backports/ubuntu xenial main/debug' and do apt-get update.

The newer format dbgsym (.ddeb) files should then be available.

**Comment by maxnick** [comment]
@rikmills , thank you for your help!!! I install debug packages for several plasma and Qt libs. DDD backtrace in attachment :

![gdb_trace](https://cloud.githubusercontent.com/assets/26419192/25097871/f56a6e80-23ae-11e7-80a8-f785acb071e8.png)
![ddd_backtrace_2](https://cloud.githubusercontent.com/assets/26419192/25097870/f56a3096-23ae-11e7-838f-8a9faacc09c1.png)

**Comment by psifidotos** [comment]
It is almost entitely in qt...

found also this: http://www.hexblog.com/?p=991

1. Can you make a screenshot of gitk to show which is the last commit you are using from branch v0.6?

**Comment by psifidotos** [comment]
2. Please try also the following, in file shell/contents/configuration/LatteDockConfiguration.qml

remove lines 49-53 which are refering to FontLoader and reinstall

**Comment by maxnick** [comment]
commit dcb07886edbf9cbc90b4b6148db28f72ebd5bcff
Author: Michail Vourlakos <mvourlakos@gmail.com>
Date:   Tue Apr 11 10:07:14 2017 +0300

    remove clearing cache
    
    --this code was suspicious for crashes

**Comment by psifidotos** [comment]
How about the fix to remove lines 49 to 53?

**Comment by maxnick** [comment]
I remove lines 49-53. Now crash doesn't occurred. When i push quit button in tweak menu, latte-dock process  successfully exit.

**Comment by maxnick** [comment]
I thought quit button meant exit from tweak menu only.

**Comment by psifidotos** [comment]
Quit button... Quits Latte... :-)

so now we know which of our code triggers it...

@audoban can you please read this thread for opinion? FontLoader in qml crashes on exit Latte in some rare cases, do you think it is better to load  the tangerine font from our c++ side?

**Comment by audoban** [comment]
@psifidotos We can use Loader for load or unload the font.

**Comment by audoban** [comment]
@maxnick hello maxnick, I was submit an possible fix on the branch https://github.com/psifidotos/Latte-Dock/tree/fix-fontloader please try again.

**Comment by maxnick** [comment]
I had pulled fix-fontloader branch. Unfortunately crash still occurs.

![gdb_trace_3](https://cloud.githubusercontent.com/assets/26419192/25144158/8de60928-2475-11e7-8442-32eb4fb555b4.png)
![ddd_backtrace_4](https://cloud.githubusercontent.com/assets/26419192/25144159/8de83a40-2475-11e7-9484-c7db6ded7b03.png)

**Comment by audoban** [comment]
@psifidotos then we must to use the 2 aproach, load the font from C++.

**Comment by psifidotos** [comment]
no prob!

**Comment by psifidotos** [comment]
@maxnick please test the fix inside the v0.6 branch

**Comment by maxnick** [comment]
Crash is not occurred anymore!!! All works fine.

**Comment by psifidotos** [comment]
@maxnick nice!!!
