### ISSUE TITLE
Latte blocks screen edge actions when maximum length = 100% and offset = 0%

### ISSUE THREAD

**Issue by RomuloPBenedetti** [psifidotos/Latte-Dock#388]
My latte version is 0.6.0
plasma 5.9.4
qt version 5.8.0
kde framework 5.32.0

**Comment by audoban** [comment]
go to Latte Settings >Tweaks and check **_Behave as normal Dock window_**

**Comment by RomuloPBenedetti** [comment]
Thanks, this worked!
