### ISSUE TITLE
Move add/remove dock to contextMenu

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#39]
It should be better if add /remove dock where moved from configuration window into the Latte ContextMenu...

I propose the following actions for the Latte Containment Actions...

**Normal State**

----separator--------  _(if menu is appearing in an applets menu)_
Latte Settings

**Editing State**

Add New Dock
Remove Dock _(**only if** there are two docks running, so this removes only one of them)_
Latte Settings
----separator--------
Close Latte

**Comment by audoban** [comment]
I'm agree, no problem.

**Comment by psifidotos** [comment]
too much of a trouble with no reason...
