### ISSUE TITLE
[Feature] - panel transparency and disable its shadows

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#392]
The more I read around the kde forums, the more I fall into these features... There is a big amount of users requesting for these two features for very long time and persistenlty...

- Remove panel shadows
- set the panel transparency

I played with our codebase to inverstigate what requires from us... The thing is that because much of our code is in qml these two features are very simple... Because now Latte also supports by default  the blur and background contrast kwin effects both features create very beautiful and interesting results...

I would like a lot to add them for upcoming 0.7 release, both features are only qml code in our containment.

I propose "remove panel shadows" to be a checkbox in Appearance -> Shadows only shown in advanced mode
and "panel transparency" to be a slider in Appearance -> Background only shown in advanced mode. (transparency could be 0% - 100% with 100% to be the maximum transparency provided by the plasma theme)

P.S. there are users that are requesting the wood theme of mac or other known themes from other docks but I dont think they fit in a plasma experience...

**Arc Dark theme with 55% transparency**
![image](https://cloud.githubusercontent.com/assets/2216474/24968871/6604ed1a-1fb7-11e7-865e-762e94a31c85.png)

**Comment by psifidotos** [comment]
@audoban do you agree with this?

**Comment by audoban** [comment]
It's ok, I'm agree.

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/24980214/fc1d3d48-1fdf-11e7-9238-aca29a2089ba.png)
