### ISSUE TITLE
[Feature] - Improve Configuration Window layout...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#395]
the configuration window will provide two different layouts.... Basic / Advanced

- Basic layout, will be clean and provide the most common features
- Advanced layout,  will unveil and provide all the features

**Comment by psifidotos** [comment]
@audoban please use branch **advanced** and tell me your thoughts... I made all the changes we mentioned... I changed in appearance page some settings layouts (applet shadows, panel choices) in order to use the same design decisions in all the configuration window... I think it looks and behave a lot better now...

**Comment by psifidotos** [comment]
@audoban merged in master to not lose all the work for many different branches... we can work directly to master...

**Comment by JenaPlinsky** [comment]
I like it Great ;)

**Comment by psifidotos** [comment]
done...
