### ISSUE TITLE
Reduce side panel margins in fill mode

### ISSUE THREAD

**Issue by kuriot** [psifidotos/Latte-Dock#398]
I think for usability purposes there should be done something with widgets margins.

For example, if there is a button in the top/bottom left corner it should be pushable without aiming. Just move mouse to that corner and click.

Here's an example and comparison with default Plasma panel:

![Latte Dock - Workspaces Pager](http://i.imgur.com/4Cluafl.png)
![Plasma panel - Workspaces Pager](http://i.imgur.com/nmnc6dj.png)

As you can see with Plasma panel you can just move mouse without looking and aiming to the bottom right corner and switch workspaces with mouse scroll.

Or here's another widget "Win7 Show Desktop":

![Latte Dock - Win7 Show Desktop](http://i.imgur.com/E7uCYVq.png)
![Plasma panel - Win7 Show Desktop](http://i.imgur.com/VYR2oyT.png)

Again it can be configured to do different things with mouse scroll but you have to aim on Latte Dock to do things.

**Comment by psifidotos** [comment]
I dont understand the proposal... what aiming? The applets margins in appearance page in settings isnt what you are describing?

**Comment by kuriot** [comment]
I made "Applets Distance" 100% just for screenshots but even if it's 0% you can't just move your mouse to the corner and push/scroll over the widget. You have to slightly move mouse back or aim to widget to operate with it.

Like for example there is a Menu button in bottom left corner but I can't move mouse to that corner and press the button. Instead I have to aim to that button because I'll miss it if just move pointer to the corner without looking at where it is.

**Comment by psifidotos** [comment]
What menu button? From what applet?

**Comment by kuriot** [comment]
It doesn't matter. What I'm trying to say is that applets/buttons/widgets which are in the corner of screen (when Latte Dock is in stretched panel mode) should be activated by mouse when mouse goes all the way to the corner (where that applet/button/widget is). Now when a apple/button/widget is in the most left or right side of Latte Dock stretched to 100% of screen it isn't activated by mouse when you just move it all the way to that corner. Now this applet/button/widget has some margin (you can see it on screenshots I've posted earlier) and you have to point your mouse right above widget.

**Comment by psifidotos** [comment]
You mean to eliminate totally the side margins of the dock in Fill mode because that empty space in the end creates usabilities issues?

**Comment by psifidotos** [comment]
In your screenshots the Latte background is  not calculated correctly, there is a gap between the panel background and the shadow...

Cam you make a screenshot for your Bahavior, Appearance tabs and what theme are you using?

**Comment by kuriot** [comment]
> You mean to eliminate totally the side margins of the dock in Fill mode because that empty space in the end creates usabilities issues?

Yes.

Here are screenshots of settings:

![](http://i.imgur.com/44JlHNy.png)
![](http://i.imgur.com/3mo523w.png)
![](http://i.imgur.com/o7ZJm8Q.png)

**Comment by psifidotos** [comment]
the theme is Breeze dark?

**Comment by kuriot** [comment]
Yes, it's Breeze Dark.

**Comment by shvchk** [comment]
> You mean to eliminate totally the side margins of the dock in Fill mode because that empty space in the end creates usabilities issues?

Yeah an option to have no margins on the edges (left and right when dock is horizontal, top and bottom when dock is vertical) would be nice to have.

In general (and maybe it should be a separate issue), I think panel itself shouldn't force any specific margins, as it does now (e.g. having one edge with bigger margin for Latte Plasmoid's blue applications dots — in this case this margin should probably be added by Latte Plasmoid itself, and not forced by panel to every other widget). Maybe even make every edge margin configurable with some sane defaults, i.e. there could be 4 inputs in settings for left, right, top and bottom edge margin, where user could enter any number he wants, starting from 0.

**Comment by psifidotos** [comment]
Such big configuration complexity doesnot follow what I believe appropriate for Latte...

Currently Latte functions as following:

1. When the Latte plasmoid is present a thickness margin is applied to all applets except systray. This was the only way the applets seemed vertical aligned... on the contrary the visuals werent satisfactory based on my criteria
2. When the latte plasmoid is not present or when the latte plasmoid uses reverse lines and dots the previous thickness margin is not applied
3. Latte currently supports a choice from Tweaks page to shrink thickness margin to minimum possible

The side margins can be improved i think by default, i will play with it
For the thickness margin the only thing I can accept is a user choice to eliminate it for all applets except the latte plasmoid and not per applet

**Comment by shvchk** [comment]
> Such big configuration complexity doesnot follow what I believe appropriate for Latte...
But that would probably simplify both code and configuration: instead of checking if Latte plasmoid is present, instead of hardcoded exceptions like systray, it would just get margin values from these 4 inputs (with current values as default, and hey, these inputs could even be on the Advanced layout, not Basic one :) #395 ). When dots position is reversed, it would change values in those inputs just swapping top and bottom or left and right margins (depending on whether panel is horizontal or vertical). The rest is up to user.

> The side margins can be improved i think by default, i will play with it
Cool, thanks!

**Comment by psifidotos** [comment]
> But that would probably simplify both code and configuration: instead of checking if Latte plasmoid is present, instead of hardcoded exceptions like systray, it would just get margin values from these 4 inputs (with current values as default, and hey, these inputs could even be on the Advanced layout, not Basic one :) #395 ). When dots position is reversed, it would change values in those inputs just swapping top and bottom or left and right margins (depending on whether panel is horizontal or vertical). The rest is up to user.

feel free to provide any pull request for review that simplifies the current behavior and doesnt break the beautiful design of the config window

**Comment by shvchk** [comment]
I don't know C++ yet, so won't be able to make a pull request in near future, but here's a mockup of how this setting could look (with current configuration layout, as I don't know how future Basic / Advanced UI will look like):

![latte-settings-mockup](https://cloud.githubusercontent.com/assets/872945/25058953/0334c2f0-2188-11e7-868c-0bf26032a223.png)

**Comment by psifidotos** [comment]
nice mockup, but either way no personal interest implementing

**Comment by psifidotos** [comment]
btw, the applets distance already sets your left,right margins in a uniform way

**Comment by psifidotos** [comment]
@kuriot except this issue, the issue of the transparent line between the panel shadow and the panel background should have been fixed in master
