### ISSUE TITLE
Add Widgets action is not working...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#4]
I have found a plugin from plasma called: 
org.kde.plasma.private.shell
that contains the WidgetExplorer

I dont know, we might be able to use it....

**Comment by audoban** [comment]
I will investigate, I think it's possible. But, why not function by default?

**Comment by psifidotos** [comment]
I think that I have read somewhere that each shell can have its own implementation for this... But I think there should be a way to call the plasmashell one as this is a qml plugin

**Comment by psifidotos** [comment]
I found the way plasmashell is doing it... the code is in qml at: plasma-desktop,
desktoppackage/contents/explorer

and it is called from:
desktoppackage/contents/view/Desktop.qml 

the call is accesing this by using metaobject etc that can be found at desktopview.cpp at plasma-workspace

**Comment by psifidotos** [comment]
I think the only way is too copy the behavior and qml parts from plasma...

**Comment by psifidotos** [comment]
@audoban cab we close this?
personally I am very happy with the current behavior of normal state and editing state and using plasma's add widgets...

**Comment by audoban** [comment]
Yes, I'm feel that current behavior is sufficient.

**Comment by audoban** [comment]
Great job. :)

**Comment by psifidotos** [comment]
:+1:
