### ISSUE TITLE
Support MaximumLength through configuration

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#40]
the ui already supports a maximumLength which can be used in order automatic to shrink the icon size when this limit is reached.... Throught configuration window this could be set as a percentage... 75%, 85%... etc..

**Comment by audoban** [comment]
I don't agree.

Why not use the maximum width or height of the screen as maximum length?
I do not think this is necessary.

**Comment by psifidotos** [comment]
> Why not use the maximum width or height of the screen as maximum length?
> I do not think this is necessary.

This is the current default behavior... In Now Dock there were many users that wanted this... If you want we can leave it open and when the first release is out, we will see if there is demand for this...

**Comment by audoban** [comment]
> This is the current default behavior... In Now Dock there were many users that wanted this... If you want we can leave it open and when the first release is out, we will see if there is demand for this...

I would wait at least until someone asks for it.
