### ISSUE TITLE
Fn multimedia keys, not working with Spotify/Clementine.

### ISSUE THREAD

**Issue by madrzazg** [psifidotos/Latte-Dock#402]
I have Spotify app running and playing music. When I press Fn+F11 to pause music that doesn't happen. It seems that key press signal is sent twice, because if I press Fn+F10 or Fn+F12 to play previous/next song the second next/previous song is played instead.
If you need any additional info, please let me know. Thanks.

**Comment by psifidotos** [comment]
Disable the Now Playing applet from your systray

**Comment by madrzazg** [comment]
Is this necessary? I would like to have Now Playing in my systray. Do you know why this happens?

**Comment by psifidotos** [comment]
No I dont know the route of this.... The alternative would be to replace your plasma panel with one latte dock that behaves like your plasma panel

**Comment by tenten8401** [comment]
I'm experiencing this issue as well. Removing the media player from the system tray keeps it from working at all while keeping it there results in it working for half a second and stopping again.

**Comment by DemaroStanberry** [comment]
I had a similar experience and filed it in #265.
 I could see that an mpris event would get triggered twice (once by Latte and the other by KDE) using dbus introspection. The quick fix as already mentioned is to use Latte to host the system tray applet

**Comment by audoban** [comment]
The reason most probably of this issue, is that well the dataengine Mpris2 was instanced twice times, for lattedock and plasmashell, then when the user press a multimedia key, the action is triggered for both instances and then is send twice to mediaplayer, doesnt exist a easy solution for this behavior because the dataengine Mpris2 was not designed for this situation, and I doubt that the plasma team considers it as a bug. 

On my plasmoid PlayBar2 however I want to avoid this problem so atay tuned.

**Comment by psifidotos** [comment]
there is a chance that with  https://phabricator.kde.org/D6095 there is an approach to solve this... if the plasma devs disable this shortcuts for all other except plasmashell then we can expose them only from Latte and the user can enable them / disable them whenever wants...

**Comment by psifidotos** [comment]
@audoban we can include the media player shortcuts in our globalshortcuts class. Based on your experience is it easy from implementation side to have a play/pause completely inside Latte code without using the mpris dataengine?

**Comment by audoban** [comment]
Do you refer just to Play/Pause, or all the media keys? I suppose that with call to mpris2 interface from DBus finally the dataengine is abstraction of this interface in dbus

**Comment by audoban** [comment]
However we can still use Mpris2 dataengine and create our shorcuts into of group LatteDock global shortcuts.

**Comment by psifidotos** [comment]
> Do you refer just to Play/Pause, or all the media keys? I suppose that with call to mpris2 interface from DBus finally the dataengine is abstraction of this interface in dbus

whatever is needed in order for the user to be able to combine plasma panels and latte docks and all its media keys to work correctly. I can see four exposed media actions from mpris dataengine,

![image](https://cloud.githubusercontent.com/assets/2216474/26774826/d05117aa-49da-11e7-964f-4916004492d7.png)


> However we can still use Mpris2 dataengine and create our shorcuts into of group LatteDock global shortcuts.

nice... that sounds ok...

**Comment by psifidotos** [comment]
the user should be able either to disable the mpris dataengine shortcuts or disable the Latte ones in order for this issue to be fixed...

**Comment by audoban** [comment]
For eg. in PlayBar I provide the global shortcuts into own group. We can provide these actions in the same way

![spectacle m20860](https://cloud.githubusercontent.com/assets/7884292/26775042/c986c4b6-4998-11e7-9e1d-5cbb0572da1d.png)

**Comment by psifidotos** [comment]
nice... so the user disables the mpris dataengine shortcuts and can use these... nice...

**Comment by audoban** [comment]
Then I think I can do it, finally I was do it with playbar

**Comment by psifidotos** [comment]
ok.. no prob...

**Comment by psifidotos** [comment]
I think that this is might fixed in plasma 5.10.1 by landed commit
https://phabricator.kde.org/D6100

Στις 5 Ιουν 2017 11:09, ο χρήστης "Smith AR" <notifications@github.com>
έγραψε:

**Comment by audoban** [comment]
no prob

**Comment by psifidotos** [comment]
let's close it... I am confident enough that 5.10.1 will fix this... if it doesnt we open it again...
