### ISSUE TITLE
Duplicate settings between two docks?

### ISSUE THREAD

**Issue by odensc** [psifidotos/Latte-Dock#403]
Hello. I'm using Latte Dock and I have two docks, one on each of my monitors.

I'd like them to both have the same launchers as each other, is there a way to make it automatically copy the settings to every dock?

**Comment by psifidotos** [comment]
unfortunately it isnt possible

**Comment by audoban** [comment]
Hello @psifidotos , for achieve this we need to sync the property *launchers* of the configuration, its true? How do you plan to implement this?

**Comment by psifidotos** [comment]
I am not planning anything in that regard... I was thinking about supporting multiple instances of the same dock by creating clones of containments and syncing their configuration somehow but this isnt easy and I dont know if it is even possible

> for achieve this we need to sync the property launchers of the configuration, its true?

yes, the property launchers59 must be updated. From the user point view I cant imagine that feature how it should look and work...

**Comment by audoban** [comment]
neither, You still want to keep the possibility of implementing. I honestly do not see much need. Unless that more people want it

**Comment by psifidotos** [comment]
the need exists, especially from users in multi-screen environments. The main need is for a global dock which is going to be same on all screens. We had investigated this in the past and the only way is by having for each dock different configurations that are synced. This is very advanced. I just keep this open in case in the future new ideas arise or we find a way to overcome the obstacles

**Comment by audoban** [comment]
I think at least provide an option in the context menu to pin a launcher in all docks, something as __"pin > All docks"__

**Comment by psifidotos** [comment]
This can be only an action not a state indicator. By pressing it that launcher is sent to all other docks... or we can sync the launchers to all other docks when pressing, this might be easier...

**Comment by audoban** [comment]
I think that synchronizing the whole configuration is very difficult. 

But at least anchor a launcher or all the launchers should be a feature sufficient and can be a propose most realistic or even better.

**Comment by psifidotos** [comment]
it might be good also to have a Copy function which will be intelligent enough... The copy function for a dock creates a new dock which has the same configuration and also it is positioned first on the first available alternative screen that has the same edge free

**Comment by audoban** [comment]
right, I see it, this feature sounds good.

**Comment by psifidotos** [comment]
> But at least anchor a launcher or all the launchers should be a feature sufficient and can be a propose most realistic or even better. 

it is very important to describe the behavior. 

1. The one launcher case. Launchers are set even on different activities what is updated then? When this launcher  is removed what is happening? It isnt also straightforward to remember which launchers are anchored

2. The all launchers case, in each launchers change the whole launcherlist is sent to other docks, this is a bit cleaner but it will need an intelligent function in the plasmoid to update only the changes between the launcherlist received and the launcherlist that is present.

**Comment by psifidotos** [comment]
@audoban I have uploaded a proposal for all this behavior at:

#521 #522 

after these two have been implemented this issue can close and we can add more improvements afterwards based on user and experience feedback

**Comment by psifidotos** [comment]
the requested features have been added...
