### ISSUE TITLE
Icon disappears for split second when launching a new instance

### ISSUE THREAD

**Issue by thesbros** [psifidotos/Latte-Dock#404]
When launching a new instance of an application that doesn't have one yet, the icon "disappears" quickly. As seen here:

![GIF](https://cloud.githubusercontent.com/assets/1520776/25067758/3ec60e94-2202-11e7-85e5-b04b4f871e54.gif)

Is this supposed to happen (and is there a way to disable) or is it a bug?

**Comment by psifidotos** [comment]
Are you using plasma 5.8?

**Comment by thesbros** [comment]
Yes.

**Comment by psifidotos** [comment]
It is a known upstream issue... we have managed to workaround it for plasma 5.9

**Comment by thesbros** [comment]
Sorry I was wrong. I am using plasma 5.9!

**Comment by psifidotos** [comment]
in that case you can try our branch called **launchers59** , it should fix it this for you... this branch is going to be merged in master in a week

**Comment by thesbros** [comment]
Okay thanks, I will wait for the next version.
