### ISSUE TITLE
chrome apps group issue

### ISSUE THREAD

**Issue by killown** [psifidotos/Latte-Dock#405]
when opening chrome apps in standalone mode it will group all windows in chromium icon, the issue happens with Version 60.0.3073.0 (Developer Build) (64-bit), but lattedock works fine with chromium 57

**Comment by psifidotos** [comment]
does icon only plasma taskmanager behaves the same?

What plasma version are you using?

**Comment by killown** [comment]
plasma-desktop 5.9.4-1, works fine with the plank dock but not with icon only or latte dock

**Comment by psifidotos** [comment]
If it doesnt work for icon only you must report it upstream at bugs.kde.org... we use the plasma libtaskmanager, if plasma fixes it then latte will behave correctly

**Comment by killown** [comment]
ok, icon issues is from libtaskmanager, thank you, I will report there

**Comment by pecigonzalo** [comment]
I just wanted to share that i found a fix for the issue mentioned here:
https://www.reddit.com/r/kde/comments/6ftc6r/kde_510_issue_chrome_apps_combining_under_google/
and here:
https://www.reddit.com/r/kde/comments/7dwpgd/how_to_detach_the_application_icon_from_the_main/
after reading carefully the KDE code, change this
```
# /etc/xdg/taskmanagerrulesrc
[Mapping]
Gimp-2.8=GIMP
Systemsettings=System Settings
oracle-ide-boot-Launcher=Oracle SQL Developer
Dragon=dragonplayer

[Settings]
ManualOnly=Wine,Google-chrome
MatchCommandLineFirst=perl
TryIgnoreRuntimes=perl
```
basically, remove the Google-chrome parts and add it to Google-chrome (could be the process is named differently.)

If this is the case do:

`xprop | grep WM_CASS`

and click on your "Chrome App", notice the second part after the comma and that is the "name" to put under "ManualOnly".

**Comment by psifidotos** [comment]
@pecigonzalo very nice! that would be useful also for plasma taskmanagers users!

**Comment by pecigonzalo** [comment]
I put a PR on their phabricator to review
