### ISSUE TITLE
icon theme issue

### ISSUE THREAD

**Issue by killown** [psifidotos/Latte-Dock#406]
latte dock doesn't match the icon theme for popcorntime, tried a few themes and the icon is the same, this only works with plank dock 
plank dock in the left side, shows the right icon and latte dock in the bottom the default icon
![screenshot_20170416_051053](https://cloud.githubusercontent.com/assets/24453/25069825/21a55cfa-2263-11e7-88a4-efd526847ab0.png)

**Comment by psifidotos** [comment]
try the icon only plasma taskmanager, if it behaves wrongly you should report it upstream at bugs.kde.org and attach here the link of the bug report
