### ISSUE TITLE
Disable dock auto-appearance in fullscreen/OpenGL windows

### ISSUE THREAD

**Issue by mradermaxlol** [psifidotos/Latte-Dock#407]
Example: you have Latte running in auto-hide mode, so that it appears if you apply some pressure to the desired screen edge (you get the idea) and you are playing some game running in fullscreen mode. If you "use the mouse too hard" in that particular game, you will see the dock appearing and actually grabbing the mouse's focus → leaving the game with the last known mouse state. That's not good, isn't it? Is it possible to prevent Latte from appearing if the active window is fullscreen/borderless/whatever?

**Comment by psifidotos** [comment]
Enable in your Tweaks page, "Behave as a normal dock window" does this still happen?

**Comment by mradermaxlol** [comment]
@psifidotos no, it does not... Alright, looks like I was dumb enough not to find out what that feature was supposed to do. Thanks!
