### ISSUE TITLE
update requirements

### ISSUE THREAD

**Issue by mmiat** [psifidotos/Latte-Dock#408]
I've Mint 18.1, Plasma 5.8.5 and libqt5 5.6.1 but latte-dock doesn't start: "latte-dock: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by latte-dock)"

**Comment by psifidotos** [comment]
Did you build it youself or installed a prebuilt package?

**Comment by mmiat** [comment]
Installed Deb package


Il 16 aprile 2017 20:50:04 CEST, Michail Vourlakos <notifications@github.com> ha scritto:
>Did you build it youself or installed a prebuilt package?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/psifidotos/Latte-Dock/issues/408#issuecomment-294367635

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by psifidotos** [comment]
The deb package probably requires qt 5.7... you can contact the packager to create one for qt 5.6...

Latte requires qt>=5.6

**Comment by mmiat** [comment]
I've installed source, and I've tried to compile, I've this error:

> Could NOT find KF5 (missing: Notifications Archive) (found suitable version
  "5.28.0", minimum required is "5.26.0")
