### ISSUE TITLE
Dock don't rise after reboot [dock-pressure branch]

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#409]
Hi guys 
@psifidotos  @audoban 
branch = dock-pressure
visibility mode = auto hide

When I reboot plasma, the dock does not respond and remains hidden,
only appears during the desktop change

I noticed that telegram is in the state "need attention" and I feel that this  could keep blocked the dock

In fact, just telegram appears on the desktop, and thus their status need attention drop
everything returns to normal

but I have to better investigate

**Comment by psifidotos** [comment]
isnt this happening on the master branch?

**Comment by JenaPlinsky** [comment]
it has never happened before, I think.
... as soon as I 'll do a test from the master

**Comment by JenaPlinsky** [comment]
bugs present and confirmed with the only branch doch-pressure
...also confirm how previously mentioned "telegram in need attention state" seems to block the dock rise

**Comment by audoban** [comment]
@thanks for tour report, the branch dock pressure still needs more development.

**Comment by psifidotos** [comment]
I dont know if this will be merged in the future...
