### ISSUE TITLE
Crash: Adding / Removing docks from menu branch

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#41]
I get this, when adding and removing docks in menu branch:

0x0000000000418c35 in QtPrivate::QFunctorSlotObject<Latte::XWindowInterface::XWindowInterface(QQuickWindow*, QObject*)::{lambda(unsigned long long)#2}, 1, QtPrivate::List<unsigned long long>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()

any ideas?

**Comment by audoban** [comment]
I don't have idea, but I'm going to debug.

**Comment by psifidotos** [comment]
A small hint: in menu branch it was introduced proper dockview removal when the relevant containment is destroyed. This fixed also the quit app action because until then it was crashing

If i make a quess, something under visibilitymanager umbrella is not deleted correctly when the dockview is removed but the app is still running. Then with the first next window signal the app crashes... but this is just a guess....
