### ISSUE TITLE
[Qt 5.8] - Escape key and task dragging

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#410]
Can happen while you are moving  a task, that its icon, stay glued to the mouse pointer even when the left mouse button is released

well, I was wondering if in these conditions, you could enable the escape key to cancel the drag
it is a matter manageable by the Latte side ?
![screenshot_20170417_115024](https://cloud.githubusercontent.com/assets/24593950/25086038/95f9f342-2365-11e7-8629-babbc94a27dc.png)

**Comment by psifidotos** [comment]
There is a big chance that this is Qt 5.8 specific issue

**Comment by psifidotos** [comment]
@JenaPlinsky checked the code... this is 99% qt 5.8 problem... you should be able to reproduce it also with the icon-only plasma taskmanager
