### ISSUE TITLE
 task,'s miniature hide the dock but leave open the folder-view windovs

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#411]
when a folder-view is opened, it rightly,  maintains the dock high
if you step over a task,'s miniature  this state is broken, and even this I think is correct
instead the thing that does not happen, is that it only hides the dock, while the folder-view remains open
if the dock is hidden, even the folder-view should follow, I think

if dochk also hides the folder-view should follow, I think
![screenshot_20170417_121009](https://cloud.githubusercontent.com/assets/24593950/25086360/72fc8984-2367-11e7-848a-341cb534a042.png)
![screenshot_20170417_121300](https://cloud.githubusercontent.com/assets/24593950/25086362/741b69d4-2367-11e7-92f3-33e2a1fea1c7.png)
![screenshot_20170417_121220](https://cloud.githubusercontent.com/assets/24593950/25086364/75abc8d4-2367-11e7-835a-25aa449abf48.png)

**Comment by psifidotos** [comment]
@JenaPlinsky this only happens when window previews are enabled... :) if window previews are disabled then the dock doesnot hide when the folderview window is shown...

but yes this is a faulty behavior and should be fixed...

**Comment by JenaPlinsky** [comment]
> his only happens when window previews are enabled... :) if window previews are disabled then the dock doesnot hide when the folderview window is shown...

it is right ;)
