### ISSUE TITLE
Visible line from dock in fullscreen mpv window

### ISSUE THREAD

**Issue by Svadkos** [psifidotos/Latte-Dock#414]
I think, line appears only when compositor is turn off. 
Also, tried to screenshot it, but on screenshot it isn't seen.

**Comment by psifidotos** [comment]
Yes, it is known... you may try to enable by Tweaks "Behave as a normal dock window", does it fix it?

**Comment by Svadkos** [comment]
> does it fix it?

Yes, thanks.
