### ISSUE TITLE
[Multi-screen] Second screen dock showing tasks from first screen

### ISSUE THREAD

**Issue by cathodoluminescence** [psifidotos/Latte-Dock#416]
Hello,

I have the strange behavior that when putting a second dock in the second screen I either can have tasks from all screen showing or (when selecting "Show only tasks from current screen") the tasks from the first screen are shown.
Does this have anything to do with the way I created the second dock? (First screen, add dock, moved dock to second screen).

Pastebin: https://pastebin.com/kZbeQyRa

Thanks!
  CL #

**Comment by psifidotos** [comment]
If you have enabled from Tasks page the filter based on screen and this still happen it means that you are using the released v0.6 version. We have fixed this bug in v0.6 branch so you can either use this branch or wait for the upcoming v0.6.1 that will contain the fix

**Comment by cathodoluminescence** [comment]
Ah ok. Yes, you are right. I'm on the v0.6 release. I'll just wait for the v0.6.1 and will just use show all screen's tasks until then. Thanks for the quick reply!
