### ISSUE TITLE
need new translation string

### ISSUE THREAD

**Issue by omni6** [psifidotos/Latte-Dock#418]
for ver 0.6.87 is no translation string for "Windows go below" available.

**Comment by psifidotos** [comment]
and for many more... :) we will change first the configuration window layout to provide basic/advanced layouts, we will enable the tooltips in the config window I believe afterwards we will be ready to update the translation strings in order for translators to begin translating correctly the upcoming 0.7 version... of course this will not be a translation freeze as we have much road to do to 0.7 version... I believe mid of summer will be ok...

There are plans that we might be able to support wayland for plasma in 0.7 release... so this is a very big step forward ... :)

**Comment by omni6** [comment]
sounds good :)
