### ISSUE TITLE
ksysguard is not showing latte-dock icon

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#42]
any ideas?

**Comment by audoban** [comment]
ok, fixed.

**Comment by psifidotos** [comment]
this is not working in my system... I ksysguard latte is still not appearing its icon...

Does this work for you?

**Comment by audoban** [comment]
Yes this work fine, for me.

**Comment by audoban** [comment]
See it.

![screenshot_20170109_144800](https://cloud.githubusercontent.com/assets/7884292/21780715/a67b6620-d67a-11e6-9285-d91a95d9a394.png)

**Comment by audoban** [comment]
do you still have problems with this?

**Comment by psifidotos** [comment]
unfortunately yes

I think that something in my system probably

**Comment by audoban** [comment]
do you use breeze icon theme?

**Comment by psifidotos** [comment]
yes

**Comment by audoban** [comment]
I tried this even with Adwaita and it works. xD

**Comment by psifidotos** [comment]
it may be a cache issue

**Comment by psifidotos** [comment]
ok... confirmed... this was a simple cache issue... 
after changing the icon theme and restoring it again, it was fixed

**Comment by psifidotos** [comment]
no, my mistake... :( still is not appearing correctly...

**Comment by audoban** [comment]
actually still works on my computer. plasmashell is shown icon?

**Comment by psifidotos** [comment]
yes for plasmashell it is shown correctly... 
and interesting thing is that for the latte debug windows the icon is shown correctly.

![noicon](https://cloud.githubusercontent.com/assets/2216474/22599151/7e245b6e-ea3e-11e6-87be-8588d3f227cb.png)

**Comment by psifidotos** [comment]
add also in this conversation...

1. when latte is in regular state the icon appearing is the one show above
2. when latte is showing its config window or an applet's configuration window then this icon changes into a settings icon
3. when latte is showing a popup e.g. previews window or pop up from an applet the icon changes to plasmashell one
4. when latte is showing its debug windows the latte icon is shown correctly!!!

**Comment by psifidotos** [comment]
Ok, I think I found what is happening...

when latte is starting before the dock window are created then the latte icon is shown correctly. Afterwards these docks windows do not have an icon been set and I think this creates this issue... By using
QWindow::setIcon for both dockview and our settings window I think this will be fixed...
