### ISSUE TITLE
Occasionally window previews ovelap the tasks context menu

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#423]
![screenshot_20170423_045137](https://cloud.githubusercontent.com/assets/24593950/25310475/75902a66-27e5-11e7-8f22-fc9cdffe6b96.png)

**Comment by JenaPlinsky** [comment]
Sorry ...Is still present ...even in the absence of applets
![screenshot_20170423_183550](https://cloud.githubusercontent.com/assets/24593950/25315384/71016dec-2854-11e7-8336-ca38de0710a7.png)
![screenshot_20170423_183729](https://cloud.githubusercontent.com/assets/24593950/25315385/736a09fe-2854-11e7-84bf-176bf3f8abc3.png)
![screenshot_20170423_183804](https://cloud.githubusercontent.com/assets/24593950/25315386/75997a3e-2854-11e7-9e7d-a6cc7e36919a.png)

**Comment by psifidotos** [comment]
fixed in master...
