### ISSUE TITLE
[Crash] - when I try to close the "konsoles" multiple instances 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#425]
Latte [Crash] when I try to close the "konsoles" multiple instances 
... unfortunately I can not get the back-trace the debugger crashes too

**Comment by psifidotos** [comment]
1. how do you reproduce this?
2. was this introduced by latest commits or you have just noticed it in your system?

**Comment by JenaPlinsky** [comment]
> how do you reproduce this?

![screenshot_20170423_101942](https://cloud.githubusercontent.com/assets/24593950/25312102/bd0de6a0-2810-11e7-8db2-f646f93ce5ad.png)


> was this introduced by latest commits or you have just noticed it in your system?

Maybe it's old issue
but I'm not sure, I can not tell you if the problem was present in the past days 
....  now I can not reproduce it
