### ISSUE TITLE
Drag'n'drop support for internal apps files e.g. ark

### ISSUE THREAD

**Issue by devillemereuil** [psifidotos/Latte-Dock#426]
Drag'n'drop doesn't behave in Latte Dock as it does in other task manager.

Say you open an archive with Ark and want to extract a file into an open folder in Dolphin. Using a classical task manager (including the icon-only one), you can drag the file from Ark, hover onto the Dolphin icon in the task manager, wait there a bit, which would change the focus to Dolphin and drop the icon in the folder. Very handy.

Sadly, this doesn't work with the Latte task manager. Hovering onto Dolphin doesn't trigger anything.

As a test, I added the icon-only task manager into the Latte Dock panel and it's behaving as expected (drag-hovering onto Dolphin switch the focus to the Dolphin window), so the culprit is definitely the plasmoid, not the panel.

EDIT: Tested with openSUSE Leap (Plasma 5.8) and Tumbleweed (Plasma 5.9).

**Comment by psifidotos** [comment]
It was working... it may be broken in master from latest launchers fixes... Have you tried also with a reqular file?

Drag an image from dolphin and try to open it with minimized firefox for example

**Comment by devillemereuil** [comment]
Yes, it seems to work when the file is coming from Dolphin.

**Comment by psifidotos** [comment]
I dont think we will have any problem supporting the case

**Comment by psifidotos** [comment]
supported in master...

**Comment by devillemereuil** [comment]
Well done, you guys are awesome! Can't wait to test it in a new release! ;)

**Comment by psifidotos** [comment]
0.7 version is scheduled for July...

**Comment by devillemereuil** [comment]
Oh, no problem! Unless you'd like me to compile from source to test it right now before the release? I can have a go using OBS and your spec files there.

**Comment by psifidotos** [comment]
anything you want it... i tested it in Tumbleweed with plasma 5.9 with ark and thunderbird attachments... it works ok...

**Comment by devillemereuil** [comment]
I'll have a go on Leap and let you know how it went. I think cloning your package in OBS and changing the source from master ought to be simple enough.

**Comment by psifidotos** [comment]
only thing is that Leap is using plasma 5.8 and our master branch is plasma 5.9 and above... in case you are using the kde frameworks repo of opensuse which provides.plasma 5.9 then you wont have any issues

**Comment by devillemereuil** [comment]
Oh... Don't mind me then, not worth testing again in Tumbleweed and I don't have the KDE update repos set up in Leap.
