### ISSUE TITLE
Kmail icon launcher is wrong when Kmail is minimized in systray.

### ISSUE THREAD

**Issue by Tromzy** [psifidotos/Latte-Dock#427]
My Kmail is configured to hide in systray when I click the "Close" icon. I set Kmail as a launcher in Latte Dock. When the Kmail  window is open, Latte displays the correct Kmail icon. But when Kmail is minimized in systray, its launchier icon changes to an icon with two interrogation marks. It should display the correct Kmail icon.

**Comment by Tromzy** [comment]
Strangely, the Akregator icon behaves correctly : when Akregator is hidden in systray (not closed), Latte shows the correct icon.

**Comment by psifidotos** [comment]
1. Is this happening in master branch or in v0.6?
2. When using the plasma icon only taskmanager it behaves correctly with
that problem?

Στις 25 Απρ 2017 10:52, ο χρήστης "Tromzy" <notifications@github.com>
έγραψε:

**Comment by Tromzy** [comment]
It is happening in v0.6 (Arch Linux package). With Icon Only Task Manager, the icon behaves like it should.

**Comment by psifidotos** [comment]
There is a big chance that this is fixed in our master branch for the
upcoming v0.7 version which is going to be compatible with plasma >= 5.9

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-04-25 12:03 GMT+03:00 Tromzy <notifications@github.com>:

**Comment by Tromzy** [comment]
OK ; i'll test with v0.7 when it's available and I'll report to you if it's fixed or not. Thanks !

**Comment by psifidotos** [comment]
It must be also a good idea to make a screenshot to show us the faulty icon

2017-04-25 12:07 GMT+03:00 Michail Vourlakos <mvourlakos@gmail.com>:

**Comment by Tromzy** [comment]
![kmail_icon_bug](https://cloud.githubusercontent.com/assets/1344491/25378032/70b3cd16-29a9-11e7-8be7-b89bd635b39f.png)

**Comment by Tromzy** [comment]
I put a red square around the Kmail icon.

**Comment by artemanufrij** [comment]
this is my Kmail icon when it's closed:
![screenshot_20170507_223043](https://cloud.githubusercontent.com/assets/16517095/25784873/d4f46ca2-3374-11e7-92b8-32563747dfd9.png)

**Comment by DemaroStanberry** [comment]
KMail is a little funky in comparison to other applications, if you take a peek in your latte config file (after you've closed KMail) it probably has a reference to /usr/bin/kmail.. or something like that. I don't use KMail anymore so I don't remember what the path is. You can replace that with the .desktop file path, usually located in /usr/share/applications

**Comment by artemanufrij** [comment]
@DemaroStanberry It works but I have two icons after starting kmail
![screenshot_20170508_185529](https://cloud.githubusercontent.com/assets/16517095/25815108/1344d752-3420-11e7-857f-063e22c48c0d.png)

**Comment by psifidotos** [comment]
This is because libtaskmanager can not categorize the launcher with the window... this is one of the issues that in master branch we switched totally to use libtaskmanager mechanism for launchers and not the hybrid solution latte v0.6 is using... dont expect anything better for v0.6 ... in master branch and the upcoming v0.7 this is fixed along with many launchers issues

**Comment by artemanufrij** [comment]
@psifidotos thank you!

**Comment by artemanufrij** [comment]
Same issue with visual-studio-code

**Comment by psifidotos** [comment]
Can you please confirm that this issue doesnt exist with the official icon-only task manager?

**Comment by psifidotos** [comment]
this should  be fixed in master...

**Comment by artemanufrij** [comment]
@psifidotos I can't confirm.
I have tested current master:
![screenshot_20170511_202350](https://cloud.githubusercontent.com/assets/16517095/25965342/fa7fd202-3687-11e7-932e-682dd62d4335.png)

**Comment by psifidotos** [comment]
@artemanufrij show me how plasma icon-only task manager behave...

**Comment by artemanufrij** [comment]
@psifidotos how do you mean? Should I make a screencast?

**Comment by psifidotos** [comment]
no need to... just a screenshot...

add in your desktop the official plasma icon-only taskmanager...
how does it behave with kmail?
does it have the same issue?

**Comment by artemanufrij** [comment]
No it works as expected on my desktop. Kmail and VSC works in Plank (https://launchpad.net/plank) as expected, too.

I have this issue so far only with Kmail and Visual-Studio-Code

**Comment by psifidotos** [comment]
forget Plank, it is a different codepage... show me please the plasma icon-only taskmanager with kmail

**Comment by artemanufrij** [comment]
@psifidotos sorry I don't understand what you mean "plasma icon-only taskmanager". do you speak russian or german?

**Comment by psifidotos** [comment]
> sorry I don't understand what you mean "plasma icon-only taskmanager". do you speak russian or german?

sorry I dont. What I mean is that there is a plasma widget (taskmanager) that plasma provides. Open the plasma widgets explorer and you can find in there a  "Icon Only Taskmanager". This is provided by plasma and shows only the icons for the windows just like Latte but without the animation. Try to use kmail with that "Icon Only Taskmanager" from plasma and see what happens...

**Comment by psifidotos** [comment]
@artemanufrij as long as you use master now, try also to remove the kmail launcher and readd it in Latte without touching anything in the latte config file

**Comment by artemanufrij** [comment]
ok... kmail works after reorder icons as expected. visual studio code looks a little bit ~ 

--> look my screencast:

[latte-2017-05-11_20.59.01.zip](https://github.com/psifidotos/Latte-Dock/files/994127/latte-2017-05-11_20.59.01.zip)

**Comment by psifidotos** [comment]
@artemanufrij, kmail is ok?

for visual studio code you mean that on launching appears the unknown icon right? did you try to remove this launcher also and readded?

**Comment by artemanufrij** [comment]
@psifidotos yes. kmail is ok!

I have tryed all possibilities (incl. reboot) :).

**Comment by psifidotos** [comment]
please try to use the plasma "Icon Only Taskmanager" to compare if it is working ok...

this is the icon only task manager:
https://www.kde.org/announcements/plasma-5.1/icons_task_manager.jpg

it is provided by default in plasma...

**Comment by artemanufrij** [comment]
@psifidotos ok... I will try it

**Comment by artemanufrij** [comment]
same behavior with "Icon Only Taskmanager"

**Comment by psifidotos** [comment]
In such case is not Latte fault, is either an issue with the desktop file or with plasma libtaskmanager... you can report it at bugs.kde.org with a video, would be helpful for them

**Comment by artemanufrij** [comment]
you are right! I will do it... thank you for your support!
