### ISSUE TITLE
Broken bounce animation for some launchers

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#428]
The new improved triggering of the app launch through our launchers (that is executing the app launch in the start of the bounce animation) showed an issue concerning KRun from kf5 frameworks. That is, there are launchers that do not play their bounce animation smoothly / or even they freeze the ui during the app launch. Such case are (kwrite and kate launchers in Tumbleweed).

The issue was reported upstream at:
https://bugs.kde.org/show_bug.cgi?id=379192

**Comment by audoban** [comment]
It was a big headache

**Comment by psifidotos** [comment]
?

**Comment by gmoutso** [comment]
Hi! By "new improved..." does that mean in latte, and version 0.6.0 does not have this bug? Thank you

**Comment by psifidotos** [comment]
The new lauchers mechanism that solves many issues concerning launchers is included in master branch and will be the 0.7 version compatible with plasma >= 5.9

**Comment by audoban** [comment]
@psifidotos This bug still present on the plasma 5.9?

**Comment by psifidotos** [comment]
yep... no action from plasma side

**Comment by audoban** [comment]
We can only wait

**Comment by psifidotos** [comment]
yep... or try to find in the krun class where it stacks for these launchers

**Comment by audoban** [comment]
I may be able to fix this with our hands

**Comment by psifidotos** [comment]
... just for the story... I had tried in our side to make the code execute in a different thread but that didnt help... KRun is already in different thread...

**Comment by audoban** [comment]
It is assumed that all tasks begin asynchronously, I totally do not know what happens

**Comment by psifidotos** [comment]
just for the record... now that my system is newer and faster, this is not noticed in it...
