### ISSUE TITLE
Latte Dock officially as a gentoo package.

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#429]
Latte is officially in the [portage tree !](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c983b87c3cb0e24dddba1f35a2b23a6c3f73e70d)

As soon as the gentoo users sync their tree, they will have the new package. `emerge -av latte-dock` as usual.

@psifidotos There are some references here and there about a gentoo package for latte. What can be done to update those informations?

**Comment by psifidotos** [comment]
Nice!! :-) !!! Just make a PR and we will accept it

**Comment by Petross404** [comment]
Hmm, I am not sure why. I mean, I can more than happilly make a PR for the ebuild, but our fellow gentoo users _have already_ the ebuild in their portage tree (if they synced it of course).

If you know better and you have your reasons, please let me know so that I make the PR. 👍

**Comment by psifidotos** [comment]
nothing special... I just want the users and packagers be involved in the project.. :) this is why for example why the INSTALLATION.md is fully community responsibility...

no prob if you want from us to update the links for you... :)

**Comment by Petross404** [comment]
I have seen some links to overlays and stuff and I also gave a link for an ebuild in the F.A.Q.

Is it ok if I update the FAQ and you handle the other link for the ebuild? Unless you point to me where it is, so that I don't look around... :)

**Comment by psifidotos** [comment]
no prob...

@audoban do we update the link for Gentoo?

**Comment by Petross404** [comment]
I updated the FAQ. audoban could just inform that a package already exists :)

No need to further delete, or rewrite.
