### ISSUE TITLE
Bug when launching an app

### ISSUE THREAD

**Issue by GrayJack** [psifidotos/Latte-Dock#430]
When launching an app/program, the icon jumps, disappear till the app/program fully opens (that's the issue), and reappears in the same place.

My system is Manjaro, using the latest version of latte (0.6).

**Comment by psifidotos** [comment]
solved in master, plasma 5.9 compatible...

**Comment by GrayJack** [comment]
Oh thanks, tested right now, it's really working now.

Thanks for the awesome dock
