### ISSUE TITLE
Separator inside the Tasks plasmoid

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#431]
I think we can have an approach for this even though I dont know how important this is...

We must trick the libtaskmanager...

so we can create ghost launchers that do not open any app... in case that these launchers are identified from our qml code then we dont paint their icon but the audoban separator design... every functionality for them will be blocked except dragging them and deleting....

**Comment by psifidotos** [comment]
very useful is distinguish launchers and windows!!! ;)

![int1](https://cloud.githubusercontent.com/assets/2216474/25497911/be4a08e2-2b8e-11e7-8ff9-05b2ea416b5d.png)
![int2](https://cloud.githubusercontent.com/assets/2216474/25497914/bea827ba-2b8e-11e7-81d0-e94c1bb51e9e.png)

**Comment by audoban** [comment]
I see you liked me that simple plasmoid xD

**Comment by psifidotos** [comment]
I love it... ;-) i consider it the standard for plasma panel separators...

**Comment by psifidotos** [comment]
internal Tasks separator works beautifully... even when being at the Tasks edges doesnot break the zoom animation with the neighbour applets.... ;)

**Comment by psifidotos** [comment]
unfortunately I disabled this... I created a new architecture signaling for the parabolic effect which creates a very solid parabolic effect even when moving from tasks to applets... the dock remains in its place and is feeling more robust...

unfortunately the internal spacer breaks this experience a bit so I disabled it...

if in the future I think of something we can restore this...

**Comment by psifidotos** [comment]
ok ... I managed to support it with as mush smoothness as is possible based on the architecture-signaling for parabolic effect...
