### ISSUE TITLE
Confusing QT requirement in README

### ISSUE THREAD

**Issue by AnwarShah** [psifidotos/Latte-Dock#433]
First thanks for this dock for the KDE. 

I installed the debs provided for Ubuntu in 16.04, which have only qt 5.6. So, latte-dock was refusing to run without qt 5.7. Afer spending 2+ hours for building qt 5.7, I came to know that it can be run with QT 5.6 just fine from this forum post.

Following the instruction, I easily built the dock using QT 5.6. 

I think you should clarify the issue in README, otherwise many people will be missed from testing this and spending fruitless hours.

**Comment by psifidotos** [comment]
> I came to know that it can be run with QT 5.6 just fine from this forum post.

master branch requires qt5.7 because it is compatible with plasma >= 5.9 which also requires qt 5.7
if you are using plasma 5.8 and qt 5.6 you should use the v0.6 branch which keeps that compatibility

**Comment by AnwarShah** [comment]
Yes, I used 0.6.0 from the release page. Maybe you can update the readme. I'm going to close the issue then
