### ISSUE TITLE
extra badge on libre office launcher

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#434]
I have just one media streaming running but an extra badge, appears on "libre office" launcher
![screenshot_20170501_102330](https://cloud.githubusercontent.com/assets/24593950/25575573/f4f91c9e-2e58-11e7-8218-601a0542eb12.png)

**Comment by psifidotos** [comment]
1. is this always reproducable?
2. by refreshing the webpage stream any difference?
3. does the plasma taskmanager (not the icon one, the one with with the window titles) behave differently?

I tried in my system and I couldnt reproduce...

**Comment by JenaPlinsky** [comment]
> is this always reproducable?

yes
> iby refreshing the webpage stream any difference?

 Appears simultaneously and always with any streaming media on facebook
dis appears when in pause and booth reappears when I restart it
 
>    does the plasma taskmanager (not the icon one, the one with with the window titles) behave differently?

![screenshot_20170501_110340](https://cloud.githubusercontent.com/assets/24593950/25576330/4cc43fa8-2e5e-11e7-8f13-54c74b577022.png)

I tried in my system and I couldnt reproduce...

**Comment by JenaPlinsky** [comment]
New information:
If you launch "libre office"                              - badges on ... LO [no], firefox [yes]
Close "libre office"                                         - badges on ... LO [no], firefox [yes]
Now I stop streaming and then I get it back  - badges on ... LO [no], firefox [yes]
quit latte and restart                                      - badges on ... LO [no], firefox [yes] 

I just do not understand ... now it works as we expect

**Comment by JenaPlinsky** [comment]
![screenshot_20170501_114617](https://cloud.githubusercontent.com/assets/24593950/25577447/4ad1fb06-2e66-11e7-9ae4-517be8b76269.png)
![screenshot_20170501_114642](https://cloud.githubusercontent.com/assets/24593950/25577453/65609cc0-2e66-11e7-81ab-fd99c8a339b7.png)
![screenshot_20170501_114727](https://cloud.githubusercontent.com/assets/24593950/25577459/78d63922-2e66-11e7-9e44-1c533da5e6c5.png)
![screenshot_20170501_114757](https://cloud.githubusercontent.com/assets/24593950/25577467/8d74f206-2e66-11e7-80f8-d6a138544b20.png)
![screenshot_20170501_114821](https://cloud.githubusercontent.com/assets/24593950/25577480/a038474e-2e66-11e7-96f8-6954895ae83d.png)
![screenshot_20170501_115547](https://cloud.githubusercontent.com/assets/24593950/25577486/a761cc8e-2e66-11e7-863b-914054684467.png)
![screenshot_20170501_115603](https://cloud.githubusercontent.com/assets/24593950/25577487/a91926a8-2e66-11e7-9fa0-9cf0a22d832b.png)
always reproducible

**Comment by psifidotos** [comment]
do you know which commit introduced this?

**Comment by JenaPlinsky** [comment]
I was trying to make a screenshot that included both the dock and the media player

... this happens when I'm moving from visibility mode autohide to always visible

**Comment by psifidotos** [comment]
I suppose this could be a different untracked issue then

**Comment by psifidotos** [comment]
It would be helpful if you could find the commit introduced it

**Comment by JenaPlinsky** [comment]
for commit u mean the event, right ?
if so that is the click on always visible button

**Comment by psifidotos** [comment]
> this happens when I'm moving from visibility mode autohide to always visible

unfortunately, not in system.... you should find a series of events or options that trigger this

> ..did you notice the second badge? now is on kcalc

I see it but I cant reproduce this yet neither...

> for commit do u mean the event, right ?

no I dont... by commit I mean commit: https://github.com/psifidotos/Latte-Dock/commits/master

you can try for example: 
1.  `git checkout 089e7175a25ef2efd768297c73a505ec39252309 `
2.  `sh install.sh`

in order to go back to development history at the exact history step (commit) that starts with _089e7175..._
so you can try each commit and see which one introduced this in your system.
As long as you didnt have this problem in the past it probably means that one of the latest commits introduced this and there should be one commit that doesnt have this problem and the next one which is going to have it (this is the commit that introduced the problem in your system)

**Comment by psifidotos** [comment]
@JenaPlinsky concerning the badges, I made a guess and uploaded in master, I dont know if we have caught it

**Comment by JenaPlinsky** [comment]
@psifidotos ...everything seems work fine now even with 2 media streaming running
Just one thing ... right or not, I would not know ... when I launched latte i found kcalc with a badge "1" then i closed kcalc and everything went well

![screenshot_20170501_192032](https://cloud.githubusercontent.com/assets/24593950/25587237/6d1337f6-2ea3-11e7-89db-c3e184693a98.png)

**Comment by psifidotos** [comment]
me neither... the badge indicator e.g. "1" is used when a task for that app is running e.g. when copying files or as an indicator for unread e-mails (e.g for thunderbird)... if it happens again and you ve got more infos open an issue!
