### ISSUE TITLE
Enhance audio streams indicator

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#438]
I believe it is possible to add the following for the audio indicators:

- use scroll up/down to increase/decrease the Volume for the stream of the app
- update volume icon based on the Volume stream value
- improved visuals for the mute state (add some transparency for the textColor circle)

**Comment by RaitaroH** [comment]
Issues:
1. scrolling up behaves as scrolling down, that is, it decreases the volume.
2. audio indicator always shows up even if the normal plasma taskbar removes the icon when the audio stream has ended. Example pausing a music player or the browser.

**Comment by RaitaroH** [comment]
@psifidotos Forgot to add a @ the first time.

**Comment by psifidotos** [comment]
> EDIT it seems to be the case only with the touchpad, but not the mouse. It happens with the scrolling on the dedicated area (right side) and also with 2 finger scroll.

I suppose it is too sensitive

> audio indicator always shows up even if the normal plasma taskbar removes the icon when the audio stream has ended. Example pausing a music player or the browser.

very unlikely... show me two screenshots showing both Latte and plasma taskmanager how there are when audio is playing and when stops... The issue if with Firefox, it doesnt free the pulseaudio resource when the player stops... you can check this from the Audio applet (Applications tab) -> even though the player stopped, Firefox shows : "Firefox: Audiostream"


![default](https://user-images.githubusercontent.com/2216474/36805471-36e61ed4-1cc6-11e8-9256-a52a9d34ea23.png)

**Comment by RaitaroH** [comment]
Ah well, I always had issues with my touchpad.

Welp, here are audacious and waterfox:

Playing:
![screenshot_20180301_061612](https://user-images.githubusercontent.com/19552720/36826726-2a44d9c0-1d18-11e8-9a0f-2fc608f44c67.png)
Stopped
![screenshot_20180301_061616](https://user-images.githubusercontent.com/19552720/36826727-2a72225e-1d18-11e8-8a21-a9b392c0bcdd.png)

Playing:
![screenshot_20180301_061634](https://user-images.githubusercontent.com/19552720/36826728-2a956b4c-1d18-11e8-8c84-1a4bc1d8292e.png)
Stopped:
![screenshot_20180301_061636](https://user-images.githubusercontent.com/19552720/36826729-2ada3c7c-1d18-11e8-8a10-7ce2cb2298c7.png)

**Comment by psifidotos** [comment]
I cant confirm this... 

1. with audacious I dont have such issue in my system...

2. Firefox is upstream bug and should be reported. It doesn free the pulseaudio stream when no audio is playing

3. For waterfox when you go to pulseaudio streams the stream isnt present?

**Comment by psifidotos** [comment]
this discussion has moved to #890
