### ISSUE TITLE
Add margin to panels for folderview icons to respect

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#439]
Folderview is going to be the default in Plasma 5.10. Its behavior with Latte Dock is however not optimal at this point. Please see screenshot:

<img width="290" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3875196/25621205/a9deda52-2f1e-11e7-9a6a-d887def5c1c8.png">

Please note about the icon at top, which partically overlaps with the top panel (see in particular the icon selection square, which appears in red and it is mostly hidden below the panel). Also, if the width of the panel would be higher, the effect would be worse and would start masking the icon itself.

Obviously this doesn't happen when using a plasma panel, as all icons are shifted down to avoid these types of overlap.

It might well be that things need to be changed at Plasma side for this to happen though, not sure...

**Comment by psifidotos** [comment]
sorry .... not possible... the plasmashell configures the desktop available free space by using its internal  panels... there is no way for external apps to alter this

**Comment by kupiqu** [comment]
I see...

But it would be possible (at least in principle) for plasmashell to import non-available space from existing external dock panels, right? I guess some sort of communication would need to be created between the two parts, ideally a stable API from Plasma... ?

Do you think it would be worth if I open a bug at kde for this (with a link to this discussion) to see how Plasma developers feel about such a possibility?

**Comment by psifidotos** [comment]
I dont think the will accept something like this...

the plasma devs dropped a patch a had sent in the past in order to be able for external docks to know if the desktop is locked/unlocked

**Comment by kupiqu** [comment]
Yeah, I'm not naive in the sense that I don't expect Plasma devs tol be super happy about this (immediately) and decide to implement such a thing right away.

Also I know that I don't need to convince you, but just discussing a bit further below because I think this needs to be (respectfully) said (and hopefully to a place that reach Plasma devs):

- The same way Plasma supports external applets (plasma devs would not be able, and would not like either, to implement by themselves all cool existing applets, but an engaged community really can, so both sides as well as final users benefit from this API). 

- Similarly, plasma devs could consider that supporting external panels/docks could be such a great thing. For instance, plasma devs won't be able and won't like to support all great features docks such as Latte dock offers. Once again, both sides as well as final users would have a better usability if things like available space, plasmashell status, etc., would be shared in a proper and secure way.

- I may be wrong, but I think I recall the Latte dock appearing in a recent Plasma release announcement. It's cool that they advertise as well as take some credit (both sides are happy with it, I would say) showing that plasma is awesome. But IMO Plasma devs should also try to treat this kind of projects as first citizen, if possible.

Of course, all my comments are a user point of view. I'm sure there will be complicated technicalities to resolve in all this...

**Comment by psifidotos** [comment]
feel free to communicate with plasma devs what you consider as possible... but... this should be a user point of view and not the Latte devs... technically all these are possible but what plasma devs consider best for plasma is pretty respectful from Latte devs..

plasma had advertised Now Dock (which was an internal extension of plasma) not Latte which is an external app using their libraries

**Comment by kupiqu** [comment]
Well, I don't have much power, so I would basically open a feature request at kde bug and a thread at reddit, respectfully exposing the points and the couple of examples in this discussion. I hope you are ok if I add a link to this issue...

> plasma had advertised Now Dock (which was an internal extension of plasma) not Latte which is an external app using their libraries

Thanks, I was not aware that this wasn't for Latte but for Now dock...

**Comment by psifidotos** [comment]
no prob
