### ISSUE TITLE
Moving icon with badge contaminates other icons

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#440]
Moving icon with badge contaminates other icons
![screenshot_20170502_204143](https://cloud.githubusercontent.com/assets/24593950/25633822/b246e568-2f78-11e7-8d43-8bf9d836b0ab.png)

**Comment by psifidotos** [comment]
can you reproduce with media players? vlc, bomi etc? 

in my system it isnt possible to reproduce yet

**Comment by JenaPlinsky** [comment]
Now I can not replicate it

First it happened 2 times starting from a phantom stream (no running stream but badge marked up) in firefox ... but even in this case replicating it is quite difficult

**Comment by psifidotos** [comment]
I added some more checks in case this helps... generally browsers are not the best users of pulseaudio

**Comment by JenaPlinsky** [comment]
You could kill all the badges while dragging, then let it listen for new streaming, when dragging done

**Comment by psifidotos** [comment]
tell me if you can reproduce first

**Comment by JenaPlinsky** [comment]
in which branch ? master

**Comment by JenaPlinsky** [comment]
I'm trying just now

**Comment by JenaPlinsky** [comment]
👍 all seems work fine even from browser media stream
PS wheel on badge in very nice !!

**Comment by psifidotos** [comment]
@JenaPlinsky i updated the commit to use your approach because it reduces cpu cycles a lot... it should work properly... it this happens again we can try the old approach...

I added also a small animation to show/hide badges

> PS wheel on badge in very nice !!

I know... very useful !! ;)
