### ISSUE TITLE
Litle defect on parabolic effect

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#442]
Ciao super @psifidotos ...I noticed a litle defect on parabolic effect
![screenshot_20170503_195316](https://cloud.githubusercontent.com/assets/24593950/25674434/147f3380-303b-11e7-841a-32e351fd4b41.png)

**Comment by psifidotos** [comment]
@JenaPlinsky  please check again with latest master if this is valid...

**Comment by JenaPlinsky** [comment]
I'm sorry, it is not been fixed

**Comment by psifidotos** [comment]
how do you reproduce this? where is the mouse ?

**Comment by JenaPlinsky** [comment]
This is easily reproducible with rapid movements from the launcher area to the applets area

**Comment by psifidotos** [comment]
which of the two gets stuck? the applet or the launcher?

**Comment by JenaPlinsky** [comment]
When the mouse pointer leaves the launcher zone, the first one remains stucked, while the parabolic effect works regularly on the applets area
