### ISSUE TITLE
Progress and quicklist form libunity

### ISSUE THREAD

**Issue by kanocz** [psifidotos/Latte-Dock#443]
It can be very good to have application progress indicator and quick commands list from apps that has unity launcher integration (more info https://wiki.ubuntu.com/Unity/LauncherAPI). Looks like all events are sent via DBus, so it may be easy to handle.

**Comment by psifidotos** [comment]
> It can be very good to have application progress indicator

it is already provided through libtaskmanager, copy a big file from dolphin to watch it....

> quick commands list from apps 

this is scheduled for plasma 5.10, #382

**Comment by kanocz** [comment]
yes, for KDE applicaions like dolphin it's ok, but other applications (like Telegram or ScudCloud) displays unread messages counters in Unity but not in Latte or any other KDE launchers :-(
is this hard to implement? as I understand it's just a dbus communication...

**Comment by psifidotos** [comment]
@kanocz https://github.com/KDE/plasma-desktop/blob/master/applets/taskmanager/plugin/smartlaunchers/smartlauncherbackend.cpp

if you notice the taskmanager says setupUnity() etc. should it exposes the interface to be used, it may be incomplete, I dont know... Either way this should be implemented first for plasma taskmanager, afterwards Latte would support it directly

**Comment by kanocz** [comment]
but this refers to taskmanager applet from plasma-desktop package, not libtaskmanager which is in plasma-workspace package, so only that applet can use that code
I think just copy-paste of small portion will be a good solution :D

**Comment by psifidotos** [comment]
No, this is a private qml backend but we use it also, exactly as plasma taskmanager does....

The functionality you are searching is it supported by plasma taskmanager?

**Comment by kanocz** [comment]
yes, when I'm using plasma (5.10) icon-only taskmanager it displays unread count number, in Latte it doesn't

**Comment by psifidotos** [comment]
Show me some screenshots please in order to be able to reproduce in my system

**Comment by kanocz** [comment]
So, installed Telegram (from telegram.org), done `export XDG_CURRENT_DESKTOP=unity` before it start to force using Unity counters (in other case no counters will be used), added `@AlertBot` to send messages to myself, send `/alert 2m test message`, in 2 minutes new message received:

![screenshot_20170531_082303](https://cloud.githubusercontent.com/assets/4784978/26618508/e4ac2e78-45da-11e7-88b9-2274a6d51f39.png)
![screenshot_20170531_082323](https://cloud.githubusercontent.com/assets/4784978/26618507/e4a87e36-45da-11e7-812a-e935c94b9171.png)

both screenshots has message count in tryicon, but only original "icon-only tastmanager" has also a badge on telegram application icon

**Comment by psifidotos** [comment]
I am trying with plasma 5.9 and the plasma taskmanager doesnt show the message counter. Did you install Telegram on your local user or globally?

**Comment by psifidotos** [comment]
Telegram in my system on startup shows:

```
(Telegram:5570): libappindicator-CRITICAL **: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.

(Telegram:5570): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
```

**Comment by psifidotos** [comment]
@kanocz there is a chance that in my system libappindicator doesnt work correctly... please test again master to check if the last commit fixes this

**Comment by kanocz** [comment]
no, it doesn't fix it :-( counter doesn't appear 
have you libunity9 installed? and setted `export XDG_CURRENT_DESKTOP=unity`?
P.S.: I have Telegram installed for local user and started from terminal due to environment variable

**Comment by psifidotos** [comment]
> no, it doesn't fix it :-( counter doesn't appear

actually just worked, only one taskmanager can expose the unity dbus service, make sure that only Latte is running and no other taskmananager from plasma... remove all plasma taskmanagers, close Latte and restart it


![image](https://cloud.githubusercontent.com/assets/2216474/26641289/c3e25462-4632-11e7-9310-38738521f506.png)

**Comment by psifidotos** [comment]
last commit fixes also the coloring for the counter to make better contrast

**Comment by kanocz** [comment]
Super! Thank you! you're right, it works! just re-login needed because plasma continue 'listen' as dbus service even after panel remove...

**Comment by jasmines** [comment]
When I installed Latte, I was seeing the counters... Now (don't know why and can't say exactly what changed in my system) I can only see the volume indicator on the task...

When you say "only one taskmanager can expose the unity dbus service, make sure that only Latte is running and no other taskmananager from plasma... remove all plasma taskmanagers, close Latte and restart it"

can you tell me how can I search for other active taskmanagers and how to remove them?

Thanks...

**Comment by psifidotos** [comment]
@jasmines which counters are you refering, to which apps?

**Comment by jasmines** [comment]
Thunderbird.

**Comment by psifidotos** [comment]
Are you using the thunderbird Latte addon?

**Comment by psifidotos** [comment]
the plugin can be found here: https://sourceforge.net/projects/bluestarlinux/files/extra/lattedock-thunderbird-0.0.2.tar.gz/download

**Comment by jasmines** [comment]
I saw the counter without the plugin...

**Comment by psifidotos** [comment]
Test with the addon... i cant know what changed in your system... in my system the important package was libunity9

**Comment by jasmines** [comment]
libunity9 has never been uninistalled...
is there anything else you can suggest before the addon?

**Comment by jasmines** [comment]
I removed another panel I used only for global menus.
Firefox is still missing counters. Chromium works.

**Comment by psifidotos** [comment]
> Firefox is still missing counters. 

I dont think Firefox supports libunity at all...

**Comment by psifidotos** [comment]
> I removed another panel I used only for global menus.

Latte panel or Plasma panel?

**Comment by jasmines** [comment]
plasma panel

**Comment by psifidotos** [comment]
did you have a plasma taskmanager in it?

**Comment by jasmines** [comment]
nope

**Comment by psifidotos** [comment]
no idea why it activated libunity interface then... feel free to report it to plasma devs at bugs.kde.org...
