### ISSUE TITLE
Version 0.6.1 segfaults

### ISSUE THREAD

**Issue by capnsmc** [psifidotos/Latte-Dock#446]
I run an up-to-date _Debian Testing._ Version 0.6.0 worked fine, and does so still, if compiled again. With 0.6.1 all I get is ‘segmentation fault’. When started in _gdb_ I get this (doesn't matter if compiled with debugging enabled or not, output is the same):

$ gdb /usr/bin/latte-dock
[…]
(gdb) run
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe3319700 (LWP 3358)]
[New Thread 0x7fffe1805700 (LWP 3359)]
[New Thread 0x7fffdbdc8700 (LWP 3360)]
[New Thread 0x7fffda32f700 (LWP 3361)]

Thread 1 "latte-dock" received signal SIGSEGV, Segmentation fault.
0x00007ffff546b915 in QV4::QObjectWrapper::wrap(QV4::ExecutionEngine*, QObject*) () from /lib/x86_64-linux-gnu/libQt5Qml.so.5`

A short ‘git bisect’ yields this:

e36033bde7d82206c627fb9710c288f88bc01e8c is the first bad commit
commit e36033bde7d82206c627fb9710c288f88bc01e8c
Author: Michail Vourlakos <mvourlakos@gmail.com>
Date:   Fri Apr 21 16:45:59 2017 +0300

    fix #412,fix for groupDialog in plasma 5.8

:040000 040000 1bfeefc8b29f67b4df09be07397ff3a336671e41 2aa5eae57a6fff0788be8fe343cc62548a0fdddf M      plasmoid

Any further info I can provide?

**Comment by psifidotos** [comment]
What plasma version are you using?

**Comment by psifidotos** [comment]
please try branch `fix446`

**Comment by capnsmc** [comment]
WRT which Plasma version: Some packages show 5.8.5, some show 5.8.6.
WRT branch _fix446:_ It works :)

**Comment by psifidotos** [comment]
Nice... i will merge in v0.6 and in a few days i will publish a 0.6.2 version

**Comment by psifidotos** [comment]
fixed with v0.6.2 that was just released....
