### ISSUE TITLE
Launcher icon disappears while clicking.

### ISSUE THREAD

**Issue by CamelCase11** [psifidotos/Latte-Dock#448]
When i click on any launcher pinned on a dock, it disappears from a dock for a while but when window opens it appears again.

**Comment by psifidotos** [comment]
has been fixed in master (plasma 5.9 compatible), cant be fixed for v0.6(plasma 5.8 compatible)

**Comment by CamelCase11** [comment]
i am using plasma 5.9 on arch. issue is still there.

**Comment by psifidotos** [comment]
have you installed the master branch ?

**Comment by CamelCase11** [comment]
i have installed it from official arch repo.

**Comment by psifidotos** [comment]
you use version 0.6 then... you can observe the Latte version from the configuration window it should say...

v0.6.0 or v0.6.1

**Comment by CamelCase11** [comment]
it is showing 0.6.1. that means bug is still present.

**Comment by psifidotos** [comment]
of course it is... our master branch uses version 0.6.87

**Comment by CamelCase11** [comment]
Ok then. i will install latest version from master. thank you so much.

**Comment by psifidotos** [comment]
no worries!
