### ISSUE TITLE
Cycle through open windows in task group instead of preview

### ISSUE THREAD

**Issue by xternaal** [psifidotos/Latte-Dock#449]
Would it be possible to add an option in the settings to cycle through open windows in a task group instead of opening the window switcher?

This mimics Windows style. When you click the icon it opens the last used instance in the group, then cycles through other windows as you continue to click the icon. Often when you want to just quickly return to the last used instance of the app and you have lots open it can be quite frustrating going back and forth all the time, having to find it in the visual window switcher. Its an additional mouse movement and click just to return to the last used window.

Great app many thanks!

**Comment by psifidotos** [comment]
Supporting it as an alternative left click behavior I am not that fond of...

> This mimics Windows style

which version? by default? I have a win8 and this is not default behavior...

what currently exists in master branch if you want to test is cycling tasks in a group of windows through Super key + task number

what I can consider possible is to improve the above behavior in order for a group to remember its last active window and to expose this behavior further through:
1. Middle click actions (already exists the gui at Tasks config page)
2. Key+Click actions e.g Ctrl+Left Click (already exists the gui at Tasks config page)
3. Mouse wheel, for example the user could cycle the groups window by using the mouse wheel and by remembering which was the last active...

**Comment by notexe** [comment]
What about clicking on a task group and a box comes up allowing us to select the window we wan't to open. Kinda like how Mac OS does it.

**Comment by psifidotos** [comment]
@notexe have you tried windows previews?

**Comment by notexe** [comment]
@psifidotos Yes I have, windows previews are good but I do not like the delay it takes for it to appear. Clicking to make it appear instantly would be a nice feature.

**Comment by psifidotos** [comment]
@notexe open a different issue because your request is different than the initial... afterwards the community should discuss if we will enable left-click customization and then the developers what they think about it...

personally I havent concluded if this is necessary because it is more a visual improvement in the current workflow and on the other hand adds complexity to our configuration window and code... @xternaal proposition on the other hand talks about usability etc. etc..

we 'll see...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/25857221/14d7a286-34e1-11e7-8200-fcc48ae3d009.png)

**Comment by psifidotos** [comment]
by default I added this for the mouse wheel... the behavior is the following

Scrolling Mouse Wheel
- launcher, activates launcher
- single task, activates it / minimizes it
- grouped tasks, cycles through tasks upwards/downwards by remembering also the last active window in that group... ;)

**Comment by www2287** [comment]
@psifidotos could you add support to do this whitout modificator key or mouse wheel?
e.g. some property in settings to override left-click functions. it will be more os x like. full screen previews of window group is a bit laggy, when i want to do fast switch to other window in a group.

Thanks!

**Comment by psifidotos** [comment]
Sorry I wouldnt like to override left click functions
