### ISSUE TITLE
Wheel on launchers executes a new instance

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#451]
Wheel on launchers executes a new instance

**Comment by psifidotos** [comment]
It is done by purpose... it shouldnt ?

**Comment by JenaPlinsky** [comment]
Honestly it does not convince me so much,
If I try to scroll through the grouped tasks, and I have a launcher next to it, it takes very little to have a mouse wheel action on the launcher a new and unwanted instance is annoying

**Comment by JenaPlinsky** [comment]
While, about cycle through grouped tasks and its active task indicator on preview I find it really convenient 👍

**Comment by psifidotos** [comment]
I dont agree... on the other hand someone that will get used in using the mouse wheel in order to activate the last active window in a group will expect the same action to trigger a launcher...

**Comment by JenaPlinsky** [comment]
in reality, now , no new instance is created but simply run the launcher then if the launcher is already open and move the mouse pad on the launcher well, that right !! Minimizes or shows the application

**Comment by JenaPlinsky** [comment]
However there is something that does not work as it should in my dock or now i can not cycle more through the grouped tasks
Or there is something I did not understand well

**Comment by psifidotos** [comment]
What doesnt work?

**Comment by JenaPlinsky** [comment]
So summarizing, if I understand, to launch an application ....Can I use the classic left click and i also use the mouse wheel ? Right?

**Comment by JenaPlinsky** [comment]
cycle through grouped task nor not cycle 
Now I try to close milk and restart it

**Comment by psifidotos** [comment]
yes you can use both...
