### ISSUE TITLE
Cycle through grouped task don't always work

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#452]
Don't cycle:
![screenshot_20170509_213651](https://cloud.githubusercontent.com/assets/24593950/25869224/e0ca1900-34ff-11e7-9984-ede5cf98c3a2.png)

Work fine:
![screenshot_20170509_213724](https://cloud.githubusercontent.com/assets/24593950/25869227/e2b21862-34ff-11e7-8207-ce591e1886e3.png)

**Comment by psifidotos** [comment]
isnt kwrite working for you? I cant reproduce yet...

**Comment by JenaPlinsky** [comment]
Now I closed and reopened Latte leaving everything as it was before and now kwrite can be cycled throigh

**Comment by JenaPlinsky** [comment]
I noticed that with the mouse wheel some times the icon position is altered

**Comment by psifidotos** [comment]
what you mean?

**Comment by JenaPlinsky** [comment]
Wheel on dolphin has shift k writer position:
![screenshot_20170509_225537](https://cloud.githubusercontent.com/assets/24593950/25872587/a5ec31ea-350b-11e7-826f-06633f6b4ac1.png)

After wheel action:
![screenshot_20170509_225644](https://cloud.githubusercontent.com/assets/24593950/25872614/ba39e034-350b-11e7-8d84-2d671879fa0a.png)

**Comment by psifidotos** [comment]
Isnt kwrite your first launcher ?

**Comment by psifidotos** [comment]
After startup plasma libtaskmanager sometimes doesnt position the launchers in correct order... they start going to their correct place when they first activated... this is nothing related to wheel behavior...
