### ISSUE TITLE
Icons "dive" upon launch

### ISSUE THREAD

**Issue by MPE2016** [psifidotos/Latte-Dock#454]
Hi there,

I have no other way of describing what i think is happening, so I included a small video that is pretty self-explanatory. I am using Manjjaro Linux (plasma 5.9.4) and Latte Dock 6.87.

Otherwise, I think you guys have made an amazing dock!

If you have any questions, feel free to ask!

[record.zip](https://github.com/psifidotos/Latte-Dock/files/989471/record.zip)

**Comment by psifidotos** [comment]
@MPE2016 I cant reproduce with our master branch version...

what version are you using?

**Comment by psifidotos** [comment]
fixed in master...
