### ISSUE TITLE
Panel always on top

### ISSUE THREAD

**Issue by mgian** [psifidotos/Latte-Dock#455]
It would be nice if latte-dock had a "always visible" option like the usual plasma panel

**Comment by psifidotos** [comment]
it doesnt???

in master branch we have both: "Always Visible" and "Windows Go Below"

**Comment by mgian** [comment]
It looks no.

![screenshot_20170510_161726](https://cloud.githubusercontent.com/assets/516337/25903317/5ea2d0b4-359c-11e7-8aa4-d5258684d457.png)

Compiled a couple of hours ago fresh from master

**Comment by psifidotos** [comment]
what is that showing?

**Comment by psifidotos** [comment]
Have you checked "Always Visible" ? if yes, then you must move your plasma panel in a different edge or set it in a different visibility mode e.g. "Window Go Below" ....

what is probably happening is that Latte dock "Always Visible" and the plasma panel one are messing each other...

**Comment by psifidotos** [comment]
so, it looks yes... :)

![image](https://cloud.githubusercontent.com/assets/2216474/25904067/c6e0429c-35a6-11e7-93cd-ea516035b436.png)

**Comment by mgian** [comment]
I think I finded the "problem".

If I add latte-dock from the "Add Widget" menu' it is not always visible and a completely different GUI
If I run latte-dock from a terminal or directly it is always visible.

Thanks anyway

**Comment by psifidotos** [comment]
Latte plasmoid exists for demonstration and when you delete it by accident in you dock in order to be able to add it back again... Latte is a standalone app so running:

`latte-dock`

is the way to go...
