### ISSUE TITLE
Every time I copy in config the seperator to a second place, I loose my launchers

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#458]
As the title indicates, when I copy inside the config the seperator and restart Latte, I don't have anymore my launchers. This happened twice, I don't have the courage to try for a third time. :)

So how can I get the seperator in 2 places?

**Comment by psifidotos** [comment]
> So how can I get the seperator in 2 places?

you mean to have two different internal separators in your Tasks ?

**Comment by psifidotos** [comment]
You cant have two separators in the latte plasmoid... if the second separator you want is on the edges of the Tasks plasmoid you can always add the audoban's separator widget

**Comment by Petross404** [comment]
> add the audoban's separator widget

Nice :) Will try later...
