### ISSUE TITLE
System tray's icons, aren't the same size as all the others on the Dock

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#459]
While every task, plasmoid etc use a certain, user-defined size, system tray doesn't follow this and unless a small icon size is used, there is a not-so-good inconsistency.

http://pasteboard.co/5RnIFtJZD.png

**Comment by psifidotos** [comment]
sorry... nothing related to Latte... this is plasma issue and by searching the internet you will find many users concering the systray icons size...

**Comment by Petross404** [comment]
I see. Where should I report this and how?

**Comment by psifidotos** [comment]
bugs.kde.org     for all bugs and feature requests concerning plasma
