### ISSUE TITLE
Removing a dock or applet is not robust...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#46]
When removing a dock or applet a pop up is appearing to confirm from the user that this was the right decision to do... If the user clicks the close button at the pop up then the removal is done correctly and if clicks the Undo button then the removal is undone...

The above functionality works ok with Latte excepts that if the user **doesnt click anything** in the popup then the removal of the dock or applet is not finalised which is the default plasma behavior. So even though the user doesnt see the dock or the plasmoid after the pop up is hidden the dock or the applet havent been removed.

On next Latte restart will appear again...

**Comment by psifidotos** [comment]
actually based on plasma-frameworks code the timer needs 1minute (60 * 1000) in order to really delete the applet or the dock... Some how the plasma-workspace overcomes this behavior...

**Comment by psifidotos** [comment]
no this is ok... my mistake... the notification is added in the notification list... the user has one minute to undo this action... If it doesnt the real removal takes place....

**Comment by audoban** [comment]
nice
