### ISSUE TITLE
Duplicate Icons on Dock and some icons Disappear/change

### ISSUE THREAD

**Issue by xxLOJxx** [psifidotos/Latte-Dock#462]
as the title states there are duplicate icons appearing on the dock when i run some of my pinned apps and the icons for some of my pinned apps disappear after closing those apps.

check video to see what im talking:
https://www.youtube.com/watch?v=XPPcYKc9nQA

any help on fixing these problems are welcomed or any info regarding if im doing something wrong or if the problem can be fixed.

**Comment by psifidotos** [comment]
this is fixed in our master branch but you need plasma 5.9 and above
