### ISSUE TITLE
The applet next to the task manager area remains high

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#464]
On rapid movement 
...the applet next to the task manager area remains high
[rapid_movement.zip](https://github.com/psifidotos/Latte-Dock/files/1005670/rapid_movement.zip)

**Comment by JenaPlinsky** [comment]
The situation has improved but not completely resolved :)
![screenshot_20170520_222951](https://cloud.githubusercontent.com/assets/24593950/26279144/f37546ba-3dab-11e7-8099-a31170df0ed1.png)

**Comment by psifidotos** [comment]
I suppose as good as it can be for now...
If someone pops in with a better solution, no prob from me...

**Comment by JenaPlinsky** [comment]
It is not easy to create the condition as in the screenshot ... you did a good job

**Comment by psifidotos** [comment]
I just uploaded one more commit, I forced the criteria to the limits for this I dont think after the last commit anything better can be done...
