### ISSUE TITLE
Blured background with Qt 5.9 and context menu

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#465]
Blured background
[blured_background.zip](https://github.com/psifidotos/Latte-Dock/files/1005678/blured_background.zip)

**Comment by psifidotos** [comment]
I cant reproduce this

**Comment by JenaPlinsky** [comment]
To replicate it you have to open the context menu with the right-click on an **applet** (with launchers and task does not work)

**Comment by psifidotos** [comment]
qt version?

**Comment by psifidotos** [comment]
are you still using latest plasma?

**Comment by JenaPlinsky** [comment]
![spectacle n19837](https://cloud.githubusercontent.com/assets/24593950/26140498/77c3af10-3ad7-11e7-8eee-baf6732cf2b4.png)

**Comment by psifidotos** [comment]
this is probably a duplicate concerning #183 

please try branch fix183 and tell me how it goes...

**Comment by psifidotos** [comment]
forget branch fix183... I included the fix in master so please check again for this...

**Comment by JenaPlinsky** [comment]
@psifidotos  fix183 is missing

**Comment by psifidotos** [comment]
use master branch

**Comment by JenaPlinsky** [comment]
sorry @psifidotos  is still present

**Comment by psifidotos** [comment]
I will probably be able to fix this... only when Qt 5.9 is land in my system...

**Comment by psifidotos** [comment]
probably duplicatet to #183

**Comment by psifidotos** [comment]
@JenaPlinsky just to confirm because in the video is not shown. After you show the context menu for an applet you click somewhere with your mouse to deactivate the config window.

1. Are you clicking on the desktop?
2. I believe the issue isnt only the blur that remains but also that the config window doesnot become hidden. Am I right?

**Comment by JenaPlinsky** [comment]
Now I'm not able to test latte as soon as possible I'll give you more details
But I think I clicked on the form of milk

**Comment by JenaPlinsky** [comment]
Ok I just checked out.


>  Are you clicking on the desktop?

Clicking on the background or on the latte configuration form produce the same result


>     I believe the issue isnt only the blur that remains but also that the config window doesnot become hidden. Am I right?

yes it is true

**Comment by JenaPlinsky** [comment]
@psifidotos  ....I just updated from master and the background is no longer blured, did you work on it?

**Comment by psifidotos** [comment]
no, I dont think I added anything concerning this but I cant be sure...

is it also fixing the proper configuration window deactivation? the config window closes properly?

**Comment by JenaPlinsky** [comment]
Maybe it might be due to a plasma update
![spectacle ds6230](https://cloud.githubusercontent.com/assets/24593950/26259552/ce73a0ba-3cc9-11e7-9bcf-a7cc5c804a0e.png)
Here is a video
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1015050/video.zip)

**Comment by psifidotos** [comment]
maybe...

ok... let's open a new one for this then...
