### ISSUE TITLE
Parabolic animation and applets

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#466]
First of all I want to congratulate to you for solving the number one defect ;) at least for my personal opinion  Great !!!

[parabolic_defect_.zip](https://github.com/psifidotos/Latte-Dock/files/1005691/parabolic_defect_.zip)
I noticed a small defect on the start up of milk,
For a moment the parabolic animation appears not smooth then after a while everything goes to perfection

The user switch applet icon on the other hand always works no-smooth

**Comment by psifidotos** [comment]
The startup issue must be fixed from last commit...

The user switch applet is a very strange case because it is applet that can show also text next to the icon... so i dont know how easy it is to identify the case...

**Comment by JenaPlinsky** [comment]
Also other icons applet icons has no smooth animation

[video.zip](https://github.com/psifidotos/Latte-Dock/files/1016379/video.zip)

**Comment by psifidotos** [comment]
feeling confident enough now to enable the optimised behavior for all applets that are discovered are such... you can test master branch ...

we should be careful though in case there are applets that we break some of their functionality, in such case we can black-list those...

**Comment by JenaPlinsky** [comment]
still behaves as before

**Comment by psifidotos** [comment]
if you mean the user switch applet, sorry this doesnt fall into this category... the app launcher works fine for me...

**Comment by JenaPlinsky** [comment]
no kde menu icon

**Comment by psifidotos** [comment]
I have four types of app launchers and they all work ok in plasma 5.9 (I used the Alternatives option...) can you check yours and see how many of them are broken in plasma 5.10 ?

**Comment by JenaPlinsky** [comment]
of course !!!  ...What kind of launchers do you refer to?

**Comment by JenaPlinsky** [comment]
have I to use your layout

**Comment by psifidotos** [comment]
I mean the kde menu that you report as broken... if you right click it you can choose "Alternatives" in order to change to another menu (application chooser).

how many of them are broken?

**Comment by JenaPlinsky** [comment]
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1016517/video.zip)
[video2.zip](https://github.com/psifidotos/Latte-Dock/files/1016529/video2.zip)

**Comment by psifidotos** [comment]
ok... so it's only the first one....

**Comment by JenaPlinsky** [comment]
Yes 
...by the way it is the same regardless of its position

**Comment by psifidotos** [comment]
nothing to do... our heuristic algorithm that goes into the qml tree to identify these applets is not yet ready for that specific case...

**Comment by JenaPlinsky** [comment]
ok !!! ;)

**Comment by JenaPlinsky** [comment]
Great u have fixed this issue too even if i change its icon  👍

**Comment by psifidotos** [comment]
@JenaPlinsky I added also a heuristic case for userswitcher applet... should work just fine your icon now... ;)
