### ISSUE TITLE
separator and dock geometry

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#467]
I noticed (not today), with the passing of the mouse between area applets and task manager, a docking geometry adjustment, which does not happen if I remove the separator

I suppose this is very difficult to bypass you agree with me?

**Comment by psifidotos** [comment]
The separator is a widget or the internal in the Tasks plasmoid?

**Comment by JenaPlinsky** [comment]
The internal

**Comment by psifidotos** [comment]
can you show me a video ?

**Comment by JenaPlinsky** [comment]
[withoutseparator.zip](https://github.com/psifidotos/Latte-Dock/files/1005865/withoutseparator.zip)
[withseparator.zip](https://github.com/psifidotos/Latte-Dock/files/1005866/withseparator.zip)

**Comment by psifidotos** [comment]
As good as it can get for now.... the separators are a nasty thing for the parabolic effect..

**Comment by JenaPlinsky** [comment]
Ohh yes I supposed it
