### ISSUE TITLE
Show Background only when there is maximized window

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#469]
I fall onto a very beautiful design case...

A user proposed to have a transparent panel when there is no maximized window and a solid one when there is... I combined it with Active Window Control... 

these are the screenshots from the test.... ;)

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/26173416/6bceba42-3b54-11e7-8059-b978f45bf2d6.png)

![image](https://cloud.githubusercontent.com/assets/2216474/26173471/a0526e26-3b54-11e7-80d4-c04aa4c86f3e.png)

![image](https://cloud.githubusercontent.com/assets/2216474/26173492/b4d9e50e-3b54-11e7-95e6-e22f4c08d8c6.png)

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/26174269/707515fc-3b57-11e7-9f7a-c7bfcc8c2b38.png)

**Comment by JenaPlinsky** [comment]
What do you think of a dose of this kind? The concept is the same but reversed

![screenshot_20170518_231307](https://cloud.githubusercontent.com/assets/24593950/26223811/08d348be-3c20-11e7-9aab-418fc53b6ceb.png)

![screenshot_20170518_231433](https://cloud.githubusercontent.com/assets/24593950/26223814/0a4a60f6-3c20-11e7-95ba-6822d9fbf93b.png)

**Comment by psifidotos** [comment]
not fond of...
