### ISSUE TITLE
Task bar right click menu and application preview stopped working in master

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#471]
I don't have much time right now to identify the exact commit that introduced the issue, so I checked last commit of every recent day and going back 2 days from last commit (to May 16) solved the issue (commit 73ff03f4ec4f70a8192ef9bea11134cfdc76f3ec).

**Comment by psifidotos** [comment]
I cant reproduce in my system...

the last days I reorganized a lot of qml code to improve the readability and the logic separation...

you can try to remove totally folders:

/usr/share/plasma/plasmoids/org.kde.latte.plasmoid
/usr/share/plasma/plasmoids/org.kde.latte.containment

and re-install Latte from master...

- what plasma and qt version are you using?

**Comment by kupiqu** [comment]
I did what you said but not working properly yet.

However I realized that previews work until I try to open right click menu. The menu fails to open and must break sth as then previews stop working too.

Plasma 5.9.5, frameworks 5.34.0 and Qt 5.7.1 (KDE neon User Edition)

**Comment by kupiqu** [comment]
As you cannot reproduce it, I'll try to investigate the particular commit that raises the issue to see if you can do sth about it...

**Comment by kupiqu** [comment]
Ok, I found the causing commit. It is the fix #382,support jumplists and places, contextmenu (commit 86eb2bfa4da9d24b78969acac64555637b194229)

May it be that it works fine for incoming Plasma 5.10 but that it fails in Plasma < 5.10 ?

**Comment by psifidotos** [comment]
ok... you can check master branch again...

**Comment by kupiqu** [comment]
Mmm, while it now works, it is not quite optimal as it loses some nice existing features of Plasma 5.9: 
- different modes in which apps can be open (e.g. open a new Konsole tab/window; private Chromium window instead of standard one)
- direct access to recent files associated with apps like: text editors, browsers, media players, kontact (email attachments and calendar events)...

**Comment by psifidotos** [comment]
> different modes in which apps can be open (e.g. open a new Konsole tab/window; private Chromium window instead of standard one)

these are jump lists, and they are plasma 5.10

> direct access to recent files associated with apps like: text editors, browsers, media players, kontact (email attachments and calendar events)...

it works for me

**Comment by kupiqu** [comment]
> these are jump lists, and they are plasma 5.10

It might be that there were some jump lists in plasma 5.9, as I don't have Plasma 5.10 and this worked in Latte before the commit I mentioned above (86eb2bfa4da9d24b78969acac64555637b194229) that introduced jump list and places support

> it works for me

I'll confirm in a minute (I came back to the commit prev to 86eb2bfa4da9d24b78969acac64555637b194229), but I think recent files were not appearing

**Comment by kupiqu** [comment]
> it works for me

Correct, recent files are appearing just fine, as you said, my fault here.

Then the only remaining issue is in Plasma 5.9 associated jump lists.

**Comment by kupiqu** [comment]
This is the only thing I could find about jump lists in plasma 5.9:

https://www.kde.org/announcements/plasma-5.8.5-5.9.0-changelog.php:

> Plasma Addons: Quicklaunch: Add support for jumplist actions. Commit https://cgit.kde.org/kdeplasma-addons.git/commit/?id=5e175a976967f53fe683ce12e76b1144d98d24d4

**Comment by psifidotos** [comment]
restored...

**Comment by psifidotos** [comment]
strange thing is that taskmanager supported jump lists from plasma 5.9 but it is demonstrated as plasma 5.10 feature...

**Comment by kupiqu** [comment]
Awesome! As always...

Many thanks!
