### ISSUE TITLE
Latte dock overlays steam games. 

### ISSUE THREAD

**Issue by pawelma** [psifidotos/Latte-Dock#473]
Latte dock overlays steam games and sometimes get's stuck and doesn't hide.

![screenshot_20170520_103353](https://cloud.githubusercontent.com/assets/1849200/26274329/d8ced4a2-3d47-11e7-8054-882f50b688a2.png)

**Comment by psifidotos** [comment]
Steam is doing its thing and doesnt respect any linux window types etc.

Choose from Latte Tweaks page,
Behave as a normal dock window...

Should be fixed afterwards
