### ISSUE TITLE
Latte and CPU usage

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#474]
Sometimes it happens that Latte does not want to know, to release the CPU
![screenshot_20170520_191940](https://cloud.githubusercontent.com/assets/24593950/26277967/ba35e50e-3d91-11e7-885c-316406c82453.png)

**Comment by JenaPlinsky** [comment]
after killing firefox's process nothin us changed
and here is ...after restart latte
![screenshot_20170520_193203](https://cloud.githubusercontent.com/assets/24593950/26278067/96dc803e-3d93-11e7-8b56-73846cbc9005.png)

**Comment by psifidotos** [comment]
unfortunately... you have no infos...

**Comment by psifidotos** [comment]
the only such case I have found until now, was the spinning animation in the systray and that is plasma fault...

you should play with it in your system... delete some applets or windows etc... until you find what behavior is causing it for you...

**Comment by JenaPlinsky** [comment]
When the dock is inactive there are any animations running anyway?
Can animation loops occur? if so do u believe that is possible to prevent them with a timeout ?

**Comment by psifidotos** [comment]
There arent anymore animations that cycle endless, maximum duration is 8 secs for needs attention animation... you could try to invesigate by switching to another visibility mode

**Comment by JenaPlinsky** [comment]
If it happens again I'll do, more attention

**Comment by JenaPlinsky** [comment]
This is an interesting video, I hope,  where I tried to circumscribe the issue, and I think I approached a bit
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1034020/video.zip)

**Comment by JenaPlinsky** [comment]
If it occues again. I'll try, as you suggest, changing the visibility mode

**Comment by psifidotos** [comment]
From the video it is almost certain a top dock issue, propably one of the systray widgets...

Next time that happens, start disabling one by one the systray widgets in order to find which one...

Big possibility the notifications one, the fact that libfile is also appearing is suspicious, maybe there was a file copy and didnt ended properly... next time you can also try to kill the libfile if is appearing for latte and there is a stack cpu

**Comment by psifidotos** [comment]
@JenaPlinsky I think I know which one is it...
I think it is the konversation one in the systray...
I just remembered that in the past I had this issue whenever I had messages in the konversation app, it was the reason I never I enabled it in the systray and I dont remember if it occurs again... meaning that Konversation was sending something all the time and didnt end

**Comment by psifidotos** [comment]
the issue was appearing also to plasma panel

**Comment by JenaPlinsky** [comment]
Then I immediately disable the konversation's notification  in the systray... and I will see what happens ;)

**Comment by JenaPlinsky** [comment]
I have never considered this option ... for a milk process, do you think it's wise to customize its priority?
![spectacle sm3432](https://cloud.githubusercontent.com/assets/24593950/26528164/e408c5ea-43a4-11e7-98f9-3ba0d6a03dac.png)

**Comment by psifidotos** [comment]
Only if you get delays with Latte, e.g. with parabolic effect or to show up when hidden

**Comment by JenaPlinsky** [comment]
Then I do not need of that. Latte is always reactive ... I think it might be helpful in those cases of CPU overload (due to various processes) when latte is put in hold on state.

**Comment by psifidotos** [comment]
In such cases it could help

**Comment by JenaPlinsky** [comment]
Probably by its nature a task manager must have a higher priority than the other processes ... maybe it is also for the default task manager

**Comment by JenaPlinsky** [comment]
I did some tests and these commands seem to give you more smoothness (even if I'm not 100% sure) at the dock in cases of CPU overload or disk access stoppage
The problem is that to set a higher priority **administrator privileges are required** 
Is there a way to run these two commands as root in the ~/.config/autostart/latte-dock.desktop or through a bash script ?

```
# The priority value of any given process can vary from -20 (highest priority) to 19 (lowest priority). The default priority is 0.
sudo renice -n -20 $apppid; ps -lfC $apppid

# Scheduling classes:
#     c0 for none        
#     c1 for realtime    ...also, -n level option is applicable, with 0(highest priority)-7(lowest priority) as valid data (priority levels).
#     c2 for best-effort ...also, -n level option is applicable, with 0(highest priority)-7(lowest priority) as valid data (priority levels).
#     c3 for idle
sudo ionice -c1 -n 0 -p $apppid; ionice -p $apppid
```

**Comment by JenaPlinsky** [comment]
..just as information, I happened to have a fixed CPU usage of 30%, and about this, that unlike from the case mentioned days ago in this case it did not depend from the top dock and those from the systray
...then unfortunately I accidentally killed milk .. and I could not better investigate ... 
next time I will be more careful ;)

**Comment by psifidotos** [comment]
@JenaPlinsky one applet causing 10%CPU usage in my system without any visual reason is ktorrent when it is shown in the systray

**Comment by afflerbach** [comment]
Reason here was the blinking notification below the mail client's icon that there are new unread messages…

**Comment by psifidotos** [comment]
In master branch this animation lasts only 7secs, are you using 0.6 version?

**Comment by afflerbach** [comment]
Indeed, I'm currently using 0.6.2.
