### ISSUE TITLE
Audio badge on wrong icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#475]
Firefox stream badge on wrong icon
![spectacle bh5010](https://cloud.githubusercontent.com/assets/24593950/26279428/df4af7ae-3db3-11e7-9acd-8822a4d247a7.png)

**Comment by psifidotos** [comment]
could this be because of wrong positioning of launchers on startup, which is plasma isssue?

**Comment by JenaPlinsky** [comment]
maybe

**Comment by JenaPlinsky** [comment]
f I close and re-start latte ... same result
If I use the alternative session ... same result
I noticed that using the mouse wheel the position of the launchers could be altered
And I fear this is the cause of what I said

**Comment by psifidotos** [comment]
the position of the launchers is not changed by the mouse wheel... the series of events is the following:

1. plasma libtaskmanager sometimes misplaces the launchers on startup
2. by using the mouse wheel that window is activated
3. because the window is activated the libtaskmanager now understands that its position is wrong according the launchers real position
4. the libtaskmanager corrects the position of the launcher

**Comment by JenaPlinsky** [comment]
Surely it is as you say !!! ... but I am pretty certain that I have seen the positions change
In any case I can not replicate this behavior

Now, I'm have this problem.
All firefox streams have its  badge on  dolphin icon and even re-installing latte i get the same
How can I return to normal state ?

**Comment by psifidotos** [comment]
learn your launchers order and you make sure that they are in the corect order by just clicking them on startup, play an audio stream afterwards, does it still happen for you?

**Comment by JenaPlinsky** [comment]
Yes
I forgot to try to see what was happening by closing and restarting the dolphin
anyway...
only after the plasma logout the situation has normalized

**Comment by psifidotos** [comment]
ok... in my system I cant replicate... the first thing after I start Latte is to touch a bit the launchers in order to go automatically to their positions...

![image](https://cloud.githubusercontent.com/assets/2216474/26281626/d88ff7dc-3e05-11e7-8b03-1f873e979c98.png)

**Comment by JenaPlinsky** [comment]
The problem described here was when latte was already open for a while
but I'm not sure ... I'll give you more accurate information
