### ISSUE TITLE
Custom icon for "Show launcher when not running" is not correct when application is closed

### ISSUE THREAD

**Issue by hlavki** [psifidotos/Latte-Dock#476]
Using latest version 0.6.2 and I created some custom application items like Netbeans or Visual Studio Code. When I run this application, check "Show launcher when not running" and finally close it, icon changes to some generic one (Icon in red rectangle)
![screenshot_20170520_235846](https://cloud.githubusercontent.com/assets/5858133/26279627/0d0d10e6-3db9-11e7-8dee-34b18b5f16dd.png)

**Comment by psifidotos** [comment]
most of these issues have been fixed in master branch but unfortunately it is compatible only with plasma >= 5.9

**Comment by hlavki** [comment]
thanks for information

**Comment by hlavki** [comment]
I've installed latte from latest sources and I realy don't like solution. Why latte dock does not take icon from .desktop file? Icon is stored in latte configuration as text encoded binary data. When I add my custom .desktop file to latte configuration manually, it does not work! And also it is not possible to drag desktop file to latte dock.

**Comment by psifidotos** [comment]
latte in master in using completely the plasma libtaskmanager...

1. add in your desktop an official icon-only task manager
2. try to do whatever you want with your launcher and compare with Latte

if the behavior is both the same in Latte and plasma icon-only taskmanager then you should report that at bugs.kde.org

**Comment by psifidotos** [comment]
in step 1 previously, add in your desktop an official plasma icon-only taskmanager

**Comment by hlavki** [comment]
I'm taking it back, you are right. Same behaiour as official task manager. Also drag'n'drop desktop file to latte works.

**Comment by psifidotos** [comment]
no worries...

**Comment by hlavki** [comment]
Have to say, it's really nice piece of work. thanks
