### ISSUE TITLE
Support Alternatives from the Context Menu

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#48]
Currently Alternatives are supported from drag n' drop, e.g. dragging n' dropping a folder in Latte a menu is appearing asking the user what preffer icon or folderview... 

By right-clicking an applet the Alternatives menu entry is appearing for example in case of Clock applet. 

We could support the Alternatives dialog window based on the plasma-workspace implementation but I dont know if there is user interest for this... If there is no interest we could remove the Alternatives menu entry from the context menu...

**Comment by audoban** [comment]
I think we should support it, it is not difficult and since we do not have widgets explorer this is the minimum that we should offer the user.

**Comment by psifidotos** [comment]
I dont quit fancy it implementing it, would you like to take it? if you dont, no worries, I will...

**Comment by audoban** [comment]
> I dont quite fancy it implementing it

I can implement this. But if you want we can disable this action.

**Comment by psifidotos** [comment]
> I can implement this

of course

> But if you want we can disable this action.

no it's ok, even though I believe it is used very rare. I just dont have the mood to implement it personally

**Comment by audoban** [comment]
Then I'll implement it

**Comment by psifidotos** [comment]
:+1:
