### ISSUE TITLE
widget on launcher area

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#482]
When I drag an applet or widget on the launcher area, its gray protection box is no longer visible

**Comment by psifidotos** [comment]
Why it should? A widget can not be added in the Launchers area

**Comment by JenaPlinsky** [comment]
The gray box "launchers area" does not appear anymore
![](https://cloud.githubusercontent.com/assets/2216474/24118791/accdecb8-0db7-11e7-9eb3-a02aa3549a4a.png)

**Comment by psifidotos** [comment]
if it a launcher the one I want to add, it is appearing in my system as long as I have checked in Tweaks page the "Add Launchers in the specified area"

isnt this the behavior in your system?

**Comment by JenaPlinsky** [comment]
Sorry so much, I'm confusing, checked and all function as planned
