### ISSUE TITLE
latte instances

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#483]
It seemed to me that If I open a new plasma session I find two latte instances
You might think of killing all latte instances with "the new session event"

![screenshot_20170522_222508](https://cloud.githubusercontent.com/assets/24593950/26326982/dc434738-3f3d-11e7-944b-9d5c4a4eaa82.png)

**Comment by psifidotos** [comment]
you mean a second session for the same user ?

**Comment by psifidotos** [comment]
where do you see the two instances ?

**Comment by JenaPlinsky** [comment]
Yes I mean that
I realize that having two sessions from the same user makes no sense,
but. it happened by accident and I noticed this thing...
![spectacle h18422](https://cloud.githubusercontent.com/assets/24593950/26329978/0cafa02c-3f4a-11e7-8979-e35bcab2c22e.png)

**Comment by psifidotos** [comment]
No, this is correct behavior... you have two different sessions for the same user, each user must have its own Latte
