### ISSUE TITLE
drkonqi5 is valid for crash report ?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#484]
Here is back-trace referred to a crash on click event on user-switcher applet
![screenshot_20170523_002308](https://cloud.githubusercontent.com/assets/24593950/26331238/2e877b10-3f50-11e7-8e38-6050703e4048.png)
![screenshot_20170523_002532](https://cloud.githubusercontent.com/assets/24593950/26331239/2f942ba2-3f50-11e7-8c28-4342c8546231.png)
![screenshot_20170523_002640](https://cloud.githubusercontent.com/assets/24593950/26331241/31181844-3f50-11e7-8516-fd909cdde4a8.png)
![screenshot_20170523_002741](https://cloud.githubusercontent.com/assets/24593950/26331244/326ea08c-3f50-11e7-9d91-6f01c9003935.png)
![screenshot_20170523_002815](https://cloud.githubusercontent.com/assets/24593950/26331245/33b68a04-3f50-11e7-9dc6-e996325e23bb.png)

**Comment by psifidotos** [comment]
You had reported this again in the past and it is an upstream bug, i have sent a bug report to plasma but no movement there...

**Comment by JenaPlinsky** [comment]
I'm interested in knowing if I can use drkonqi5 instead of ddd
drkonqi5 is always available and offers the ability to restart the dock after a crash

**Comment by psifidotos** [comment]
Yeah no prob, as long as we can see all the backtrace because there are too many messages in it and not all of them are useful
