### ISSUE TITLE
Unable to build from source on ubuntu

### ISSUE THREAD

**Issue by gameslayer** [psifidotos/Latte-Dock#485]
CMake Error at CMakeLists.txt:17 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 1.8.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

**Comment by rikmills** [comment]
sudo apt-get install extra-cmake-modules

**Comment by gameslayer** [comment]
Still got the same error when building

**Comment by gameslayer** [comment]
I see you just edited your post so I will try again.

**Comment by gameslayer** [comment]
E: Unable to locate package libkf5plasma-dev
E: Unable to locate package libkf5wayland-dev

**Comment by rikmills** [comment]
What ubuntu version are you using?

Do you have the Kubuntu backports ppa enabled as the INSTALLATION.md instructs?

**Comment by gameslayer** [comment]
Ah so I do need to add the kubuntu ppa, might want to make the instructions more clearer as it just says Kubuntu only which I am not using also I am using Xubuntu 16.04 LTS

**Comment by rikmills** [comment]
Well, the master branch - which presumably you are trying to build - of latte-dock requires Qt 5.7.0 as a minimum, and the kubuntu-backports PPA only has Qt 5.6.1, so you are still likely to get blocked in cmake on that requirement.

The 0.6.2 release tars in downloads are ok to build on Xenial LTS with the backports ppa.

**Comment by gameslayer** [comment]
yeah I got this error...

Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.7.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.6.1



-- Configuring incomplete, errors occurred!
See also "/home/corey/Latte-Dock/build/CMakeFiles/CMakeOutput.log".

I see now it requires 5.7.0 like you said

**Comment by psifidotos** [comment]
@rikmills thanks a lot for participating in Latte community and for maintaining packages for ubuntu based derivatives !!! 

feel free to provide feedback concerning Latte
