### ISSUE TITLE
firefox launcher behaviour

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#488]
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1029940/video.zip)
Ciao
This video does not want to highlight any defect all works very fine and the animation are smooth and precise!!!! I just thought that this might be useful for checking the proper functioning of the dock geometry .... I noticed a firefox icon movement when I launch firefox

**Comment by psifidotos** [comment]
I dont understand what you mean... what do you show with this video and what you mean about firefox?

the video you have sent I think is from another issue

**Comment by JenaPlinsky** [comment]
I thought that a video with the disabled composer could be interesting to check the dynamics
that's all

It seems to me that with the composer enabled everything is absolutely perfect.
Otherwise, with the composer disabled, I watch tiny launcher shifts when activated
These should not be considered a problem I believe
But maybe they could highlight at least for you things I certainly do not see

**Comment by psifidotos** [comment]
> I thought that a video with the disabled composer could be interesting to check the dynamics
that's all

what composer?

>It seems to me that with the composer enabled everything is absolutely perfect. Otherwise, with the composer disabled, I watch tiny launcher shifts when activated

the video you have sent doesnt show any firefox launcher behavior

**Comment by JenaPlinsky** [comment]
Shit !!!! you're right
Aahahah ugly figure I did !!!! I sent you a video that has nothing to do with it

I lost the video I wanted to show you

I bag your pardon !!!!!!

**Comment by psifidotos** [comment]
@JenaPlinsky dont worry... if you find it again let me know...
