### ISSUE TITLE
[REQUEST] Option to Disable Scroll Wheel Actions

### ISSUE THREAD

**Issue by ToastyYogurtTime** [psifidotos/Latte-Dock#489]
I don't use them and I constantly trigger them by accident, so I would like to disable them.

**Comment by psifidotos** [comment]
makes sense...

is this on laptop?

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/26504354/f3463fbe-424c-11e7-9d54-b56a181357c4.png)

**Comment by JenaPlinsky** [comment]
Activate tasks with mouse wheel is a very good thing
I think that @ToastyYogurtTime  consider how annoying, it is just the possibility of accidentally launching applications
@ToastyYogurtTime  can you confirm this ?
Is possible separate the two things? What do you think about it and the other users?

**Comment by ToastyYogurtTime** [comment]
Yeah, it's on a laptop with a multitouch trackpad, I've often accidentally launched, minimized, and unminimized apps when trying to right click on an app or when I mean to scroll on the left side of the screen where the dock is hiding and accidentally activated it.

Thanks for adding this feature!

**Comment by psifidotos** [comment]
> Thanks for adding this feature!

no prob
