### ISSUE TITLE
The icon of the menu launcher doesn't change...

### ISSUE THREAD

**Issue by jlda** [psifidotos/Latte-Dock#490]
![peek 26-05-2017 01-36](https://cloud.githubusercontent.com/assets/11981120/26482204/1e6ea120-41b4-11e7-83b0-8f20896316b0.gif)
The icon that I put is shown for some second and then it is modified by another, I think the pattern of the theme. And this happens only by using the Latte Dock, not using the standard Plasma panel.

**Comment by psifidotos** [comment]
I included kickoff and two more  app launchers in Latte heuristics... 

Latte in order to provide proper parabolic effect and active indication needs to identify first the applets that break these behaviors...

It should work ok now... let me know...

**Comment by jlda** [comment]
It's working now. Thanks.

**Comment by jlda** [comment]
Hey, I said it was working, but it's not working, I do not know why ...
![main](https://cloud.githubusercontent.com/assets/11981120/26508729/de4925fa-4223-11e7-92d3-48061e711e37.gif)

**Comment by psifidotos** [comment]
which app menu are you using?

**Comment by jlda** [comment]
the alternative applications menu...

![main2](https://cloud.githubusercontent.com/assets/11981120/26509800/65216570-4228-11e7-8d7a-56bbd16eb85e.gif)

**Comment by psifidotos** [comment]
did you update to plasma 5.10 after first worked for you  ?

**Comment by jlda** [comment]
No.

**Comment by psifidotos** [comment]
it works for me in plasma 5.9, even with closing/starting Latte

1. try removing the build directory
2. make sure you are using the latest commits from master branch in case you tested in a different branch
3. try again

**Comment by jlda** [comment]
I have removed everything related to the application, but its not worked...
![spectacle lh5581](https://cloud.githubusercontent.com/assets/11981120/26510705/94ab1602-422c-11e7-9c32-5bc136042b90.png)

**Comment by jlda** [comment]
The icon i'm talking about is the default in the theme's 'icons' folder. If i select the same icon in the menu preferences, the icon changes but, it is strangely small.

**Comment by psifidotos** [comment]
> The icon i'm talking about is the default in the theme's 'icons' folder.

Dont you set an image through browsing?

> If i select the same icon in the menu preferences, the icon changes but, it is strangely small.

this mean that the applet hasnt identified correctly, so the plasma iconutem is used instead, which plasma version are you using?

Can you export you cinfiguration to take a look?

**Comment by jlda** [comment]
Plasma 5.9.5
[config.zip](https://github.com/psifidotos/Latte-Dock/files/1032951/config.zip)

**Comment by psifidotos** [comment]
I use also plasma 5.9.5
the config file doesnt look clean...

1. please restart Latte (in order to clean its configuration a bit)
2. add a second kicker (app menu lanucher) and test again if it has also the behavior with the first one

**Comment by psifidotos** [comment]
@jlda I think i found it... I improved the implementation a lot, please check again and dont try previious suggestions before you try the latest commits

**Comment by jlda** [comment]
Not changed but thanks. Maybe is only here this it's happening.

**Comment by psifidotos** [comment]
hm, we just have to find why this is happening in your system.

Can you make a video showing:
1. Add a new app launcher next to the previous
2. Change its icon to what you want
3. Toggle between your icon and the stack one

I want to investigate these steps, afterwards i will add a fix branch to use in your system in order to return to me rhe debug messagea

**Comment by jlda** [comment]
Here's the video...
[screen.zip](https://github.com/psifidotos/Latte-Dock/files/1033733/screen.zip)

**Comment by psifidotos** [comment]
@jlda I was fixing a different issue... :) I thought the issue for you was that you couldnt set an image with absolute path :)... we need to support usesPlasmaTheme in our IconItem... no prob...

**Comment by psifidotos** [comment]
@jlda please test again... I dont have a theme to confirm it...

**Comment by jlda** [comment]
Thank you so much...

**Comment by psifidotos** [comment]
it works?

**Comment by jlda** [comment]
works totally without problems
