### ISSUE TITLE
feature requests: do not group

### ISSUE THREAD

**Issue by PoiScript** [psifidotos/Latte-Dock#492]
When I open two same application, the dock will group them:

![screenshot_20170527_110759](https://cloud.githubusercontent.com/assets/17513314/26517522/c15549f2-42cc-11e7-97ad-182b0b310379.png)

So I have to click it and then select the right one I need. Could you please add a feature that would allow the dock to show all instance instead of group them? Just like the `Task Manager` Widgets in KDE:

![screenshot_20170527_111526](https://cloud.githubusercontent.com/assets/17513314/26517570/cc11e57a-42cd-11e7-8510-f90cd9755ace.png)

Thanks!

**Comment by psifidotos** [comment]
How would you use such a feature? You would see 2-3 identical icons, how would you distinguish which window is which?

**Comment by PoiScript** [comment]
Well, I also enable "Highlight windows on hovering", so I can just put my
mouse on the icon to check if it's the right one.

**Comment by psifidotos** [comment]
Unfortunately the ungrouping is out of the design goals of latte.

 sorry but i dont think we can add it

**Comment by PoiScript** [comment]
OK, thank you for your awesome work.
