### ISSUE TITLE
Unexpected ordering, of tasks and launchers

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#493]
Test with Composer Disabled
Only after a latte start-up, I get, on a task activation,  an unexpected ordering, of tasks and launchers
[video_one.zip](https://github.com/psifidotos/Latte-Dock/files/1033517/video_one.zip)
[video_two.zip](https://github.com/psifidotos/Latte-Dock/files/1033518/video_two.zip)

I suspect it has to do with # 475

**Comment by psifidotos** [comment]
yes, this is #479
