### ISSUE TITLE
I cannot cycle through dolphin tsaks with the mouse wheel

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#494]
I cannot cycle through dolphin tsaks with the mouse wheel
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1033535/video.zip)

**Comment by psifidotos** [comment]
If you enable the compositor is it fixed?

**Comment by JenaPlinsky** [comment]
Unfortunately for now i did not find a solution for kwin with the compiler ... i am waiting for an update ... otherwise i will be forced to take some step back for something more stable

**Comment by psifidotos** [comment]
> Unfortunately for now i did not find a solution for kwin with the compiler ... i am waiting for an update ... otherwise i will be forced to take some step back for something more stable

oh... compositor is not working for you? I see... in my system the mentioned issue doesnt occur either with compositor or not

**Comment by psifidotos** [comment]
is this still valid? I cant reproduce
