### ISSUE TITLE
[Request] Disable panel shadow only when there is a maximized window

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#495]
Please give latte-dock an option to have panel shadow activated if there is no maximized window and vice-versa if there is a maximized let the shadow disappear.

**Comment by psifidotos** [comment]
this can be added but the implementation will be based on the "Show background only for maximized window" if this crashes for you we must find what is the reason

**Comment by marhkb** [comment]
Ok. How can I debug this and send you useful information?

**Comment by marhkb** [comment]
no. 5.9

**Comment by psifidotos** [comment]
so strange... me too and I have no crashes concerning this feature...

let's move the discussion for this at: #497 
the steps for a backtrace are found at: #147

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/26523288/0a4efd2e-431d-11e7-96d7-70af071517e0.png)
