### ISSUE TITLE
[Feature Request] Extend widgets' limits to dock limits

### ISSUE THREAD

**Issue by PedroArvela** [psifidotos/Latte-Dock#498]
The clickable area of widgets added to the dock, such as kicker or the paginator, does not extend to the limits of the dock.

This would be practical for when the dock is taking the full width, as it allows pressing or using the widgets by placing the mouse on the edge of the screen, which requires very little aiming and can be done quickly.

It'd also fulfil [Fitt's Law](https://en.wikipedia.org/wiki/Fitts%27s_law), as a screen edge is effectively of infinite width (as much as you move in that direction, you will always hit your target).

The Latte taskbar already does this correctly, but it'd be great if external widgets added to the dock would also extend to the limits as the icons in the Latte taskbar already do.

**Comment by psifidotos** [comment]
I cant understand the issue, can you make screenshot describing what doesnt happen ecen though it should?

**Comment by PedroArvela** [comment]
In the next screenshots I have the paginator widget placed against the corner. First image in latte, second image in a generic plasma panel.

![latte](https://cloud.githubusercontent.com/assets/744561/26529196/82d2fa0c-43b3-11e7-9df4-2e5e6ed934ec.png)

![plasma](https://cloud.githubusercontent.com/assets/744561/26529197/82d9191e-43b3-11e7-8151-d7b74bd54f25.png)

In latte, the paginator has a margin between it and the border of the latte panel, placing it away from the edge of the screen, meaning that if I try to move the mouse there to change desktops, I need to carefully aim to the widget.

In plasma, the paginator has no margin placing it away from the edge of the screen, meaning that if I try to move the mouse there to change desktops, I can simply move to the edge of the screen without worrying if I moved too far or not.

I used the paginator here cause it has a very distinct edge, but this problem is more bothersome, for example, with the application menu widget. If I have a menu on a corner in latte, I can't just move the mouse to the corner and expect to click the menu button successfully, I need to aim. In the plasma panel I can just move the mouse to the corner of the screen, as the edges of the widget extend to that corner.

**Comment by psifidotos** [comment]
What I can do is the following... When the Justify mode is used, the first applet and the last can disable their margins relevant to the dock's edge... I dont want to do this for the internal applets because that would open many issues...

What do you think?

**Comment by psifidotos** [comment]
One more thing...
Why dont you minimize the applet's distance to minimum from the Apperance page, isnt that working ok for you ?

**Comment by PedroArvela** [comment]
The applet distance is set to 0%, and even when checking minimal margins on tweaks there is always a margin.

I think the option of having justified applets have their margins disabled could work. Seems like a reasonable compromise.

**Comment by psifidotos** [comment]
> The applet distance is set to 0%, and even when checking minimal margins on tweaks there is always a margin. 

this is because I have coded to always exist a minimum margin, I can update this so that 0% means 0px margins

**Comment by PedroArvela** [comment]
Imho, that would be ideal.

**Comment by psifidotos** [comment]
@PedroArvela fixed... for Justify mode , maximum length at:100% and margins: 0%
the applets touch the edge

**Comment by PedroArvela** [comment]
Thank you :)
