### ISSUE TITLE
[High Memory Usage - Memory Leak] in Latte because of libtaskmanager for the plasmoid

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#499]
this occurs when hovering the taskmanager with an image from spectacle... the plasma memory increases memory endlessly

**Comment by psifidotos** [comment]
https://bugs.kde.org/show_bug.cgi?id=380270

**Comment by psifidotos** [comment]
@JenaPlinsky this should be fixed in kde frameworks 5.35

**Comment by JenaPlinsky** [comment]
fantastic team !!!!

**Comment by psifidotos** [comment]
it is very good that the Latte community reports back to plasma and fixes many bugs!! That one was a memory leak from kde frameworks into Latte and Plasma also!!! Very important that we contribute back to Plasma!!!

**Comment by JenaPlinsky** [comment]
In my little one, I will try to follow your example and report all the possible issues to the plasma team
..and I consider your work a fundamental part of plasma philosophy
I take the opportunity to announce that I have just passed to opensuse 42.3
![spectacle jd4533](https://user-images.githubusercontent.com/24593950/27004982-a29333fa-4e14-11e7-8859-895e8bbcf972.png)
Everything flows smoothly and without bugs !!!!
The only pity is that I have not yet available a session to test Wayland

**Comment by JenaPlinsky** [comment]
> @JenaPlinsky this should be fixed in kde frameworks 5.35

Confirm  ...memory management works now properly !!! .
