### ISSUE TITLE
applet contextual menu accidentally open

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#500]
When I move a task and accidentally step over a folder-view it opens its contextual menu
Well, once finished the task moving you might close the contextual menu accidentally open  and no longer needed
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1034124/video.zip)

**Comment by psifidotos** [comment]
This is plasma folderview issue... 

1. Add a plasma panel
2. Make sure you add in it the icon-only plasma taskmanager
3. Add a forderview widget in that panel (this should happen from plasma 5.10 and above)
4. Drag a launcher from the icon-only taskmanager over the folderview

does that occur ?

**Comment by JenaPlinsky** [comment]
Yes it behaves the same way

**Comment by psifidotos** [comment]
you could report it upstream then...
