### ISSUE TITLE
[Feature Request] Unity launcher like functionality to show more applications than total space shows.

### ISSUE THREAD

**Issue by branfford** [psifidotos/Latte-Dock#501]
I think this is a good option to have. 
If i point the mouse to the bottom corner of the dock, slide all the applications i have. Instead of decreasing the size of the dock.
Like in this [video]( https://youtu.be/YcLTHQepd3Y)

**Comment by psifidotos** [comment]
the video is not working...

**Comment by branfford** [comment]
The first seconds of the [video](https://www.youtube.com/watch?v=xERZI1bcPAA&t=194s).
The carousel-ed list of the apps if i point the mouse in the bottom of the dock placed in the left side of the screen.

**Comment by psifidotos** [comment]
sorry, no interest supporting the case
