### ISSUE TITLE
Strange animation

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#502]
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1034366/video.zip)

**Comment by psifidotos** [comment]
Looks like a semi double click... i can disable the click animation if the click is already running

**Comment by JenaPlinsky** [comment]
I do not know :) -P

**Comment by JenaPlinsky** [comment]
Sometimes with the composer disabled I saw a very slight lateral shift of the task's icon

**Comment by psifidotos** [comment]
the animation should be fixed

**Comment by JenaPlinsky** [comment]
I do not see any differences ... I now try a new download

**Comment by psifidotos** [comment]
it is as good as it can be
