### ISSUE TITLE
Kicker applet crashed Latte

### ISSUE THREAD

**Issue by ahepas** [psifidotos/Latte-Dock#504]
Application: latte-dock (0.6.2)

Qt Version: 5.8.0
Frameworks Version: 5.34.0
Operating System: Linux 4.11.3-1-MANJARO x86_64
Distribution: "Manjaro Linux"

-- Information about the crash:
<In detail, tell us what you were doing  when the application crashed.>

-- Backtrace:
Application: Latte Dock (latte-dock), signal: Aborted
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6be088b7c0 (LWP 1140))]

Thread 4 (Thread 0x7f6bc35ef700 (LWP 1356)):
#0  0x00007f6bdac4567d in poll () at /usr/lib/libc.so.6
#1  0x00007f6bd47249b6 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f6bd4724acc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f6bdb78ef2b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f6bdb7363aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f6bdb54e44a in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f6bde2cf085 in  () at /usr/lib/libQt5Qml.so.5
#7  0x00007f6bdb552e9c in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f6bd688a2e7 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f6bdac4f54f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f6bc9088700 (LWP 1162)):
#0  0x00007f6bd476a1c9 in g_mutex_lock () at /usr/lib/libglib-2.0.so.0
#1  0x00007f6bd4723e99 in g_main_context_prepare () at /usr/lib/libglib-2.0.so.0
#2  0x00007f6bd47248db in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007f6bd4724acc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#4  0x00007f6bdb78ef2b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f6bdb7363aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007f6bdb54e44a in QThread::exec() () at /usr/lib/libQt5Core.so.5
#7  0x00007f6bdc304c45 in  () at /usr/lib/libQt5DBus.so.5
#8  0x00007f6bdb552e9c in  () at /usr/lib/libQt5Core.so.5
#9  0x00007f6bd688a2e7 in start_thread () at /usr/lib/libpthread.so.0
#10 0x00007f6bdac4f54f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f6bcb3f4700 (LWP 1161)):
#0  0x00007f6bdac4567d in poll () at /usr/lib/libc.so.6
#1  0x00007f6bdf8b18e0 in  () at /usr/lib/libxcb.so.1
#2  0x00007f6bdf8b3679 in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007f6bcd9661d9 in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007f6bdb552e9c in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f6bd688a2e7 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f6bdac4f54f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f6be088b7c0 (LWP 1140)):
[KCrash Handler]
#6  0x00007f6bdab96a10 in raise () at /usr/lib/libc.so.6
#7  0x00007f6bdab9813a in abort () at /usr/lib/libc.so.6
#8  0x00007f6bdabd52b0 in __libc_message () at /usr/lib/libc.so.6
#9  0x00007f6bdabdb90e in malloc_printerr () at /usr/lib/libc.so.6
#10 0x00007f6bdabdc11e in _int_free () at /usr/lib/libc.so.6
#11 0x00007f6bde7392a9 in QSGGeometry::~QSGGeometry() () at /usr/lib/libQt5Quick.so.5
#12 0x00007f6bde769b80 in QSGBasicGlyphNode::~QSGBasicGlyphNode() () at /usr/lib/libQt5Quick.so.5
#13 0x00007f6bde76c4e3 in  () at /usr/lib/libQt5Quick.so.5
#14 0x00007f6bde81032e in QQuickTextNode::deleteContent() () at /usr/lib/libQt5Quick.so.5
#15 0x00007f6bde80f97b in QQuickText::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*) () at /usr/lib/libQt5Quick.so.5
#16 0x00007f6bde7cd868 in QQuickWindowPrivate::updateDirtyNode(QQuickItem*) () at /usr/lib/libQt5Quick.so.5
#17 0x00007f6bde7ce06b in QQuickWindowPrivate::updateDirtyNodes() () at /usr/lib/libQt5Quick.so.5
#18 0x00007f6bde7cf062 in QQuickWindowPrivate::syncSceneGraph() () at /usr/lib/libQt5Quick.so.5
#19 0x00007f6bde76ab7f in  () at /usr/lib/libQt5Quick.so.5
#20 0x00007f6bde7d8616 in QQuickWindow::event(QEvent*) () at /usr/lib/libQt5Quick.so.5
#21 0x00007f6badfb52fe in  () at /usr/lib/qt/qml/org/kde/plasma/private/kicker/libkickerplugin.so
#22 0x00007f6bdc6cdd7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007f6bdc6d5494 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#24 0x00007f6bdb737d38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#25 0x00007f6bdbc97b91 in QWindowPrivate::deliverUpdateRequest() () at /usr/lib/libQt5Gui.so.5
#26 0x00007f6bdbc980c9 in QWindow::event(QEvent*) () at /usr/lib/libQt5Gui.so.5
#27 0x00007f6bde7d85b5 in QQuickWindow::event(QEvent*) () at /usr/lib/libQt5Quick.so.5
#28 0x00007f6badfb52fe in  () at /usr/lib/qt/qml/org/kde/plasma/private/kicker/libkickerplugin.so
#29 0x00007f6bdc6cdd7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#30 0x00007f6bdc6d5494 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#31 0x00007f6bdb737d38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#32 0x00007f6bdb78dc3e in QTimerInfoList::activateTimers() () at /usr/lib/libQt5Core.so.5
#33 0x00007f6bdb78e3e1 in  () at /usr/lib/libQt5Core.so.5
#34 0x00007f6bd47247b7 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#35 0x00007f6bd4724a20 in  () at /usr/lib/libglib-2.0.so.0
#36 0x00007f6bd4724acc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#37 0x00007f6bdb78ef0f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#38 0x00007f6bdb7363aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#39 0x00007f6bdb73e744 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#40 0x00000000004202b4 in main ()

Report to https://github.com/psifidotos/Latte-Dock/issues

**Comment by psifidotos** [comment]
This crash is from kicker applet and not related to Latte

**Comment by psifidotos** [comment]
does this happen regularly?

**Comment by ahepas** [comment]
No only once I believe...

Στις 29 Μαΐ 2017 22:31, ο χρήστης "Michail Vourlakos" <
notifications@github.com> έγραψε:

does this happen regularly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/psifidotos/Latte-Dock/issues/504#issuecomment-304719623>,
or mute the thread

**Comment by psifidotos** [comment]
kicker is part of plasma-desktop, only way to fix this is by fixing kicker in plasma.... 

to debug you could install all packages:
plasma-workspace-*debug*
plasma-desktop-*debug*

and afterwards you could follow #147 in order to have a more useful backtrace that contain source lines
