### ISSUE TITLE
Gap when using solid background

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#505]
Hi @psifidotos 

I realized that there is a gap between panel and applications when the solid background is enabled.

This is in the configuration: Justify, Always Active, 100% Length and 100% Background, and the gap does not appear if solid background is disabled.

Could you please try to reproduce? Thank you!

**Comment by psifidotos** [comment]
I suppose you dont mean a visual gap but a gap concerning the good snapping when other windows approach.

Unfortunately this is a known limitation. Currently the solid background is provided by the plasma theme,  so it is a thing that doesnt have its own shadows because it is used only in !compositing mode. The shadows drawn are from the normal panel background, this means that for solid background we canthave external shadows drawn and this is the gap you feel

**Comment by kupiqu** [comment]
I see, thanks for letting me know :)

**Comment by hughwilliams94** [comment]
Sorry to reopen this issue, but I have been trying to get rid of the translucent panel in kde for absolutely ages and Latte is so close to my solution. I have used the [breeze-AlphaBlack](https://github.com/Zren/breeze-alphablack) theme previously buts its changes are a bit too broad. All I want is a solid panel that merges into windows when maximized. Can you point me in the direction of some work I could do to help bring this Latte?

**Comment by psifidotos** [comment]
> All I want is a solid panel that merges into windows when maximized.

I dont understand, do you have a screenshot or something to understand what you want?

**Comment by hughwilliams94** [comment]
Sorry that wasn't very well explained, I have a couple of pictures which might be easier to understand:

LXQT with `lxqt-panel` note that there is no change between the panel and firefox's tab bar:

![screenshot_20171002_222211](https://user-images.githubusercontent.com/15379654/31100231-8ea40f62-a7c0-11e7-8e6a-b16268aa5a81.png)

Here is the same screen area with Latte dock, note that there is a narrow break between panel and firefox:

![screenshot_20171002_222307](https://user-images.githubusercontent.com/15379654/31100429-488294e4-a7c1-11e7-8bd3-f40ac74e8f7c.png)

**Comment by hughwilliams94** [comment]
Hey,
I am really sorry to be stupid about this but something seems to have changed in my setup and the translucency has disappeared already, not sure if there has been an upstream change or whether my tinkering has done something!
Sorry to be a pain

**Comment by psifidotos** [comment]
So this is fixed for you? On your screenshot of latte you have enabled solid panel background, you can disable it for that line to disappear that comes from the plasma theme

**Comment by hughwilliams94** [comment]
Yes this is all fixed for me, wasn't really an issue with Latte I don't think.
