### ISSUE TITLE
[Crash] - Active Window Control crashes Latte in plasma 5.10

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#507]
don't know what is the underlying cause

![image](https://cloud.githubusercontent.com/assets/3875196/26588720/1c719760-4524-11e7-80ad-69912d03cf03.png)

the backtrace does not seem very informative but for the case...

**Comment by psifidotos** [comment]
have you enabled "Show background only on maximized windows" ?

**Comment by kupiqu** [comment]
yes, is that making it crash? I'll check it out...

**Comment by kupiqu** [comment]
mmm, I changed the setting from true to false, but latte is still crashing

**Comment by psifidotos** [comment]
take your configuration a backup and start clean

**Comment by kupiqu** [comment]
If I do that latte starts fine, but it's that the only way to fix the issue? I mean, I have two panels and many widgets configured the way I like...

**Comment by psifidotos** [comment]
I dont have plasma 5.10 to test... something is crashing Latte so they only way to find what is by testing

**Comment by kupiqu** [comment]
ok, I'm testing. I'll let you know once I find the specific thing that makes it crash...

**Comment by psifidotos** [comment]
maybe test if it is the Active Window Control applet... if it isnt Latte it could be AWC

**Comment by kupiqu** [comment]
the first thing I tried after seeing that the vertical panel worked fine. but it isn't, the horizontal panel without AWC crashed too

**Comment by kupiqu** [comment]
hehe, actually it is AWC, forgot that I had two :/

**Comment by psifidotos** [comment]
;)

**Comment by kupiqu** [comment]
I'm going to test if AWC crashes also in a plasma panel and then will report the issue...

**Comment by kupiqu** [comment]
It seems to be the same in a plasma panel
