### ISSUE TITLE
Is it a feature or bug of latte-dock that the icon disappears and reappears when launching an application?

### ISSUE THREAD

**Issue by Paradzayi** [psifidotos/Latte-Dock#508]
Whenever I launch an application using latte-dock the icon disappears for a few seconds then appears.

**My questions are:**
 * is anyone else experiencing the same issue
 * it is a feature of latte-dock or it is somewhat a bug that could be fixed. 
 * is there a way to prevent that from happening.

I experienced this when i was using ```latte-dock v0.6.0``` and now when I am using ```latte-dock v0.6.2```

**Comment by psifidotos** [comment]
it is a big discussion why this was happening in 0.6 branch and plasma 5.8 era...
to answer the basic question, this is fixed in master branch which is plasma 5.9 compatible
