### ISSUE TITLE
Global Shortcut to Reveal Dock

### ISSUE THREAD

**Issue by cswartzvi** [psifidotos/Latte-Dock#510]
Any chance that a new global keyboard shortcut can be added to _reveal the dock_? I'm a huge fan of the `Meta+Num` shortcut for activating tasks but I tend to, embarrassingly, forget the order of the applications when the dock is hidden :unamused:.

I have a sneaking suspicion that this may already be possible but I can't find the option.

By the way, I **absolutely** love this project. Keep up the great work!

**Comment by psifidotos** [comment]
this isnt possible yet

**Comment by psifidotos** [comment]
@cswartzvi to add this is not an issue if this is done with a timer and not with behavior. What I mean is the following. The best shortcut for this is (Meta+`) which is next to number 1. So somenone could see the dock by pressing and then subsequently start pressing 1..9 to activate the task needed. 

The optimal behavior would be for the user to press (Meta+`) and the dock would be hidden until the user release the Meta key. But this is something very difficult to achieve or even impossible for a wayland environment.
The easiest to implement would be to show the dock for a specific time e.g. 5secs after which the dock hides itself, if during that time the user presses again the Meta+` then timer would start again and the hiding would be delayed...

what is your opinion?

**Comment by cswartzvi** [comment]
I honestly like both ideas. The optimal behavior (``Meta + ` `` followed by an application `Num`) is very intriguing. I can definitely see myself enjoying such a feature. On the other hand the easier to implement solution (``Meta + ` `` for a timed reveal of the dock) provides essentially the same visual information to the user and  potentially reduces the number of headaches encountered when moving to Wayland. With that in mind I have to vote for the easier to implement behavior.  

If you decide to proceed in this manner I have a couple more questions:
1) Perhaps the reveal time could be configurable?
2) How difficult would it be to implement number overlays to the individual applications (like in Unity's dock or Gnome's [dash-to-dock](https://micheleg.github.io/dash-to-dock/release/2017/03/26/new-release-v57-Gnome-3.24-support.html) extension), where the display time is tied to the dock's reveal time?

**Comment by psifidotos** [comment]
I dont know what solution will be chosen... First a refactoring for Global Shortcuts must take place and after that the choices will be based on code complexity and maintenance criteria

**Comment by psifidotos** [comment]
@cswartzvi the shortcut has been added and I have set a timer for 3secs, but I will play a bit more with this feature...

**Comment by psifidotos** [comment]
@cswartzvi 
ok... added optimal behavior for global shortcuts in X11, the dock is hidden when the user releases the modifier key and  added also the unity style to show the tasks number...

![image](https://cloud.githubusercontent.com/assets/2216474/26760047/b05d5e90-4917-11e7-9e8d-5a7b7d0afc59.png)

**Comment by cswartzvi** [comment]
Wow, what a quick turnaround! I've played around with this new feature for the last hour and I love it. I only have one question: was it your intention to have the dock appear _every_ time the user presses `Meta+num` (even if the ``Meta+` `` wasn't pressed)? I personally like this feature but could see other disagreeing.

Regardless, fantastic work. Thanks!

**Comment by psifidotos** [comment]
thanks...

Yes, it was intentional
