### ISSUE TITLE
icon of application moving in the dock

### ISSUE THREAD

**Issue by gruel** [psifidotos/Latte-Dock#511]
I am using the dock on different activities and when I am going to another activities the icons are moving around. They are not at a fixed position. This is annoying because sometimes I am trying to click on one of the icon but it moved so I am starting another one.

Thank you very much for latte. It replace KDE panels with a lot of advantage.

**Comment by psifidotos** [comment]
If you are using master branch you are probably describing bug #479 so this is a duplicate... If it is the same issue then the wrong positioning occurs only on startup and after a while of activating tasks and windows they are positioned correctly according to how you have set your launchers
