### ISSUE TITLE
Touch screen swipe gestures activated makes very hard to show the dock for the respective screen edge on 5.10.

### ISSUE THREAD

**Issue by libookami** [psifidotos/Latte-Dock#512]
Hi. The problem started when i upgraded to 5.10. I have the dock on the left in a similar way to Unity with auto-hide activated. Suddenly it became almost impossible to make the dock to appear again touching the left border but interestingly it worked fine on any other border.

After researching a bit i noticed a KCM i honestly don't remember if it was available before or if it may be new. This KCM is called "Touch screen" under the "Desktop behavior" category and noticed it comes with a gesture activated by default for the left border. I disabled the setting and while it don't worked immediately after closing and reopening the session the problem was fixed.

I can reproduce this every time:
1: Activate swipe gesture for an specific border.
2: Put Latte-Dock on the border where you activated the swipe gesture if it was not there already.
3: Activate an option to auto-hide or dodge windows for that dock.
4: Close and open your session again.
5: Now It's very hard or practically impossible to make the dock show itself when you put the mouse on that border.

It's important to mention that i don't have a touch screen so i don't know if the behavior may actually be different on a touch screen. Thanks and i hope you can reproduce the problem the same way as me.

![screenshot_20170601_151446](https://cloud.githubusercontent.com/assets/29102827/26699083/0df41be8-46de-11e7-9ba4-b7c4ab4ec3ea.png)

**Comment by psifidotos** [comment]
this gesture functionality was added in Plasma 5.10... with your problem you also describe the solution... I dont think Latte can do anything more in its side...

The user must set its swipe gestures in a way to not break the Latte functionality

**Comment by libookami** [comment]
Thanks for checking the issue. Yes, i guessed that there's no much it can be done on the side of the dock but still i wanted to report it in case something can be done or as a reference for other people in case they wonder why Latte stopped working properly. I think it would better for plasma to only activate that setting in case a touch screen is detected. Thanks a lot for the great dock!

**Comment by psifidotos** [comment]
> but still i wanted to report it in case something can be done or as a reference for other people in case they wonder why Latte stopped working properly.

the best place for this is in the https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q. feel free to add it in

> I think it would better for plasma to only activate that setting in case a touch screen is detected. 

the best place for this is at bugs.kde.org , in case you report it please add the link here as a reference

**Comment by psifidotos** [comment]
thanks a lot for you contribution

**Comment by libookami** [comment]
Thanks. The link is for creating a new page, should i edit the already existing one (https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q./_edit)?. If i report the problem to kde i'll link it here.

**Comment by psifidotos** [comment]
Yes, edit the current F.A.Qs

**Comment by libookami** [comment]
Understood!

**Comment by libookami** [comment]
Edited.

**Comment by libookami** [comment]
Sorry about taking that much time to fill the bug:
https://bugs.kde.org/show_bug.cgi?id=382219

**Comment by psifidotos** [comment]
I  think that if the user disables the plasma touch gestures for that edge Latte should work ok now... There was also a bug in plasma preventing this but there was a commit fixing it...

For Latte to use the plasma auto hiding functionality this is not possible because plasma animates the window but Latte animates the contents of the window
