### ISSUE TITLE
Plasma widgets are small and do not resize

### ISSUE THREAD

**Issue by heartb1t** [psifidotos/Latte-Dock#513]
After a reboot my Plasma widgets added to the Dock shrunk in size and do not resize with the Applets Size configuration in Latte Settings. Here's a screenshot:

![screenshot_20170603_104731](https://cloud.githubusercontent.com/assets/23617959/26754083/1416d20a-484a-11e7-8f15-ae0a19470ab6.png)

All of the other applications are in the Latte Plasmoid, except for the Application Dashboard and Minimize All Windows.

KDE Plasma 5.10.0
Latte Dock 0.6.2-1
And I'm using Arch Linux

**Comment by psifidotos** [comment]
plasma version? 
Latte version?

**Comment by heartb1t** [comment]
Updated it with the versions

**Comment by psifidotos** [comment]
Go to plasma systemsettings, icons, advanced and set the panel icon to 256px

**Comment by heartb1t** [comment]
Much thanks!
