### ISSUE TITLE
Improve Touch Screen support

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#514]
Is possible do something to better support the touch screen?
[touchscreen.zip](https://github.com/psifidotos/Latte-Dock/files/1049824/touchscreen.zip)

**Comment by psifidotos** [comment]
How do you move the mouse?

**Comment by JenaPlinsky** [comment]
In the video I'm using my finger

**Comment by psifidotos** [comment]
I just checked... parabolic effect is not possible to be supported, there is no tracking of mouse movement... for dragging i dont know

**Comment by JenaPlinsky** [comment]
Both on the applet area and on the task manager, it behaves exactly as if I moved the mouse with the pressed key sx

**Comment by psifidotos** [comment]
what is pressed key sx?

**Comment by JenaPlinsky** [comment]
sorry ;) I mean the muose left button

**Comment by psifidotos** [comment]
this is how it should behave... the best experience would be to set zoom to 0%, touching opens an app and dragging should partially work...

to appear the dock that is hidden I think it should be difficult

**Comment by psifidotos** [comment]
with just a finget to understand when the mouse is in Latte area....

**Comment by JenaPlinsky** [comment]
Can you understand the owner of the mouse movement event ?
Maybe, in case it is possible ... you might think to use as a click event, the mouse movement exit front, and eventually exclude the possibility of dragging the tasks

**Comment by psifidotos** [comment]
feel free to contribute...

**Comment by michaldybczak** [comment]
> to appear the dock that is hidden I think it should be difficult

Maybe it would be possible to integrate it with Plasma's touch screen settings, so swiping from the chosen edge would make the dock appear.

It's just a wild idea for the future.
