### ISSUE TITLE
Unresponsive task with mouse wheel

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#515]
Unresponsive task with mouse wheel
[eagle.zip](https://github.com/psifidotos/Latte-Dock/files/1049827/eagle.zip)

**Comment by psifidotos** [comment]
How can this be reproduced?

**Comment by JenaPlinsky** [comment]
I closed and reopened EagleCad and now the mouse wheel function well

**Comment by psifidotos** [comment]
we need a way to reproduce in order to understand what breaks

**Comment by psifidotos** [comment]
ping

do we find a way to reproduce this ?
