### ISSUE TITLE
Pixelized wine icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#516]
Pixelized wine icon
This does not depend on latte, right?
![screenshot_20170603_195007](https://cloud.githubusercontent.com/assets/24593950/26756174/ff457cf2-489c-11e7-9ddf-9827a4904129.png)

**Comment by psifidotos** [comment]
Yes, it isnt Latte fault

**Comment by ralgozino** [comment]
Is there any workaround for this issue? Having the same problem here.

![screenshot_20170925_113604](https://user-images.githubusercontent.com/6362698/30814136-c25d81c0-a1e5-11e7-9f57-094a64da577d.png)

See the winbox.exe icon, I'm using this hi res .png as icon:
![winbox_icon](https://user-images.githubusercontent.com/6362698/30814229-f32c0966-a1e5-11e7-8795-955121bf9379.png)

**Comment by psifidotos** [comment]
no idea... this is plasma taskmanager responsibility
