### ISSUE TITLE
[Qt 5.9] - sometimes the configuration form doesnt close on focus lost

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#517]
Sometimes the configuration form does not want to know how to close
The only way to do this is re-selecting "Latte stetings" item in the context menu

Unfortunately I did not understand how to reproduce it

**Comment by psifidotos** [comment]
unfortunately without reproducing not a lot can be done... it can be qt 5.9 that you are using but I dont use it in my environment yet

**Comment by audoban** [comment]
steps to reproduce:
1. open configuration
2. Click on the pin icon
3. Click out for lost the focus
4. Unpin the window

The event focusOut Event does not triggered again, then the window can't call hide().
