### ISSUE TITLE
[feature request] separate session with Latte-Dock for sddm.

### ISSUE THREAD

**Issue by frostheart** [psifidotos/Latte-Dock#518]
It would be great if sddm have a separate session to log-in  with Latte-Dock and without my default Plasma panels, 'cause I don't want to remove them instead of using Latte-Dock panels.
Alternative session is good, but it doesn't affect my panels.

**Comment by psifidotos** [comment]
@frostheart I dont think this is possible, except if you use a different user to log in... but I am curious, if you dont want to remove your plasma panels why do you need Latte then?

**Comment by frostheart** [comment]
@psifidotos I just want as an alternative.
I already configured my default plasma panels, and don't want to recreate it in latte.
And for testing of course.
Some plasmoids crash on plasma panels and don't on latte.

**Comment by psifidotos** [comment]
> Some plasmoids crash on plasma panels and don't on latte.

that is new... :) nice...

> I already configured my default plasma panels, and don't want to recreate it in latte. And for testing of course.

unfortunately, there is no way for Latte to touch plasma panels, e.g. to make them hide etc... so the only way you could play with Latte safely without losing you plasma panels configuration is to use a different user

**Comment by frostheart** [comment]
Thank you. So I just removed my plasma panels and use latte instead. This is the simplest way to do it.
