### ISSUE TITLE
Changing activities the dock hides

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#52]
probably in latest master something broke and the dock is not on all Activities...

**Comment by psifidotos** [comment]
thanks!

**Comment by audoban** [comment]
This is a bug on XVisibilityManager

**Comment by psifidotos** [comment]
ok!

**Comment by psifidotos** [comment]
sounds strange because before my latest commits this wasnt happening...

**Comment by psifidotos** [comment]
and I havent touched xvisibilitymanager for a lot commits

**Comment by audoban** [comment]
It was fixed on my branch, I will upload the commit at night

**Comment by audoban** [comment]
However, I will investigate, because this is broken. It's very rare.

**Comment by psifidotos** [comment]
:+1:

**Comment by psifidotos** [comment]
it must be related to my fix for #25  :(

**Comment by psifidotos** [comment]
I think this broke from this: https://github.com/psifidotos/Latte-Dock/commit/a46e0a19c597f887c33e8f51f364738855eb2b29

**Comment by audoban** [comment]
but I don't see nothing strange, on your commit.

**Comment by psifidotos** [comment]
me neither...  but before this, no problem appeared...

I havent debug yet what is happening... dock window is not on all
activities or becomes no visible... the mask i checked it is ok...

Στις 12 Ιαν 2017 22:37, ο χρήστης "Smith AR" <notifications@github.com>
έγραψε:

**Comment by psifidotos** [comment]
by uncommenting in pavelview.cpp lines 162,163 :+1: 

in adaptToScreen function:
    KWindowSystem::setOnAllDesktops(winId(), true);
    KWindowSystem::setType(winId(), NET::Dock);

this is fixed so is definitely something to do with initialization phase and setting the window to dock type. Unfortunately this introduces KWindowSystem in DockView and I dont think we want this....

**Comment by audoban** [comment]
> this can be fixed so is definitely something to do with initialization phase and setting the window to dock type. Unfortunately this introduces KWindowSystem in DockView and I dont think we want this....

Exactly, we can not use KWindowSystem in this place.

**Comment by psifidotos** [comment]
> Exactly, we can not use KWindowSystem in this place.

I totally agree! I just wanted to found it the root of the problem is case I had done something wrong from my commits.

I will leave this totally up to you, I have some commits waiting in order to make config window positioning more robust in order to take into account also the shadow used from the dock in editing mode. But I will wait first for this fix because I touch the dock view in order to support it
