### ISSUE TITLE
Latte-dock without indicator of running apps?

### ISSUE THREAD

**Issue by kinoegit** [psifidotos/Latte-Dock#520]
how to delete the 'latte-plasmoid' which indicates running apps from a single latte-dock?
my goal is to have 2 docks,
-one latte dock exactly like plasma panel (only if 'windows list applet' will be convinced to behave like his sibling in the plasma panel*) and
-an additional latte dock without 'latte plasmoid' that is without an indicator of running apps

For testing purposes i added one more latte-plasmoid to the dock. This seems identical to the first: indicating running apps and impossible to delete via GUI. Now i have two of those i wished to wipe from the dock ;-)
Maybe the right way to delete it is via ~/.config/lattedock-appletsrc? But how?

*I'd love to get plasmas 'windows list applet' in full size but in latte-dock it displays only (minimized) windows in a shortened way and without text.

**Comment by psifidotos** [comment]
@kinoegit both are possible... if you want the 'windows list applet' in Latte you should use the master branch in which we support applets with fillWidths and Heights... in master branch we support also to remove the latte plasmoid if you want from our tweaks page...

if you are using Latte v0.6 you can use at https://github.com/psifidotos/Latte-Dock/issues/350 the layout that offers a single dock that doesnt contain the latte plasmoid

BTW, from our master branch, both top and bottom are latte docks:

![image](https://cloud.githubusercontent.com/assets/2216474/26789437/fb83bf16-4a18-11e7-96ad-e805fce36935.png)
