### ISSUE TITLE
Sync launchers between different docks

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#521]
- The user should be provided a **"Sync launchers for all docks"** option in the Tweaks page.
- The launchers will be stored as a globalsettings value and is going to be used from Latte plasmoids instead of their own launchers
- The two sessions (Main/Alternative) should have distinguished options. The Alternative session docks shouldnt update their launchers behavior if the users doesnt want to
- The first time the **"Sync launchers"** is activated the launchers from that dock are used for all other docks

this request is the first half of syncing configurations between different docks. The other half is to provide a **Copy** function for docks

**Comment by psifidotos** [comment]
ok ... the **syncLaunchers** branch contains all the needed functionality... @audoban can you please check that everything is ok? The user shouldnt lose launchers at any case even when enabling/disabling the syncing or even changing between sessions...

@JenaPlinsky you can also check too..

![image](https://cloud.githubusercontent.com/assets/2216474/26799705/530532f8-4a3f-11e7-8909-191a354e88c4.png)

**Comment by audoban** [comment]
> The two sessions (Main/Alternative) should have distinguished options. The Alternative session docks shouldnt update their launchers behavior if the users doesnt want to

With respect to alternative session, definitely should not sync between the sessions, you should not even give the option.

> The first time the "Sync launchers" is activated the launchers from that dock are used for all other docks

Currently does not occur. If is activated the global configuration for launchers should be overwrites and take the conf the current dock.

**Comment by psifidotos** [comment]
> Currently does not occur. If is activated the global configuration for launchers should be overwrites and take the conf the current dock.

The code has been implemented, but currently it checks if no launchers have been specified and then it uses of the current dock, it copies them as globallaunchers...

Are you proposing to always copy the current dock launchers when it is activated?

**Comment by audoban** [comment]
> Are you proposing to always copy the current dock launchers when it is activated?

Exactly.

**Comment by psifidotos** [comment]
> Exactly.

ok, updated...
