### ISSUE TITLE
Copy dock based on its configuration

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#522]
We should add a function to copy docks. The user should be able to press **Copy** and that specific dock in copied.

- the new configuration is exactly the same with the original dock
- the new dock is placed first based on screens, it is placed on the first alternative screen that has the same edge free, the normal behavior otherwise
- the **Copy** button should be shown from a dropdown button as an alternative option to Add (dock) in the configuration window. (@audoban do you know if a drop-down button exists in qml?)

this is the second half of syncing configurations between different docks, the other half is #521

**Comment by audoban** [comment]
> the Copy button should be shown from a dropdown button as an alternative option to Add (dock) in the configuration window. (@audoban do you know if a drop-down button exists in qml?)

Doesn't exist such button, we need to create from scratch the button.

**Comment by psifidotos** [comment]
> Doesn't exist such button, we need to create from scratch the button.

Can you think an elegant alternative?

**Comment by audoban** [comment]
Let me to do a mockup.

**Comment by audoban** [comment]
It is the same button with a another button align to right of parent

![spectacle k31897](https://cloud.githubusercontent.com/assets/7884292/26807139/41b32a52-4a1a-11e7-9b6a-e002239d3b39.png)

**Comment by audoban** [comment]
I will try to put the context menu

**Comment by audoban** [comment]
The dropdown button with contextual menu has available in the branch **copy-launchers.**

**Comment by psifidotos** [comment]
merged the whole stack in master...

![image](https://user-images.githubusercontent.com/2216474/26839588-2e2250a8-4aec-11e7-9362-65087ab5db72.png)

**Comment by psifidotos** [comment]
changed the ComboBoxButton visuals in config window... I put a ComboBox below the Add button...

![image](https://user-images.githubusercontent.com/2216474/26841481-49a96590-4af2-11e7-9b50-500bd2543ac4.png)

**Comment by psifidotos** [comment]
If anyone does have a multi screen setup, can please test how this feature behave?

**Comment by JenaPlinsky** [comment]
Very comfortable feature and it works very great
