### ISSUE TITLE
Some unproportionally small icons of widgets after plasma 5.10 upgrade

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#523]
You can see three widgets on my dock: start menu (looks normal, but I am using custom icon - rocket launcher, so maybe that's why), minimize all and trash bin. The two last became smaller and look weird.

The screenshot says it all. This is how it looks now:

https://puu.sh/wdNnl/de45924f91.png

This is how it looked before and how it should look:

http://imgur.com/JUS37hE

**Comment by audoban** [comment]
@psifidotos the issue is from our side?

**Comment by psifidotos** [comment]
plasma systemsettings,icons,advanced,panel icons set the size to 256px.

**Comment by michaldybczak** [comment]
Thanks but those options are grayed out for me. Do I miss some package?

https://puu.sh/welM6/ca27117af7.png

**Comment by psifidotos** [comment]
If you try another icon theme such as Breeze, are they still greyed out?

**Comment by michaldybczak** [comment]
Yes, with breeze icons I also have options grayed out. As far I remeber they were always grayed out on various installations on different computers. Manjaro may be missing some package. It would be not the first time. I found few of such gaps, reported them and they are now shipped out of the box. Maybe this time it's similar?

**Comment by psifidotos** [comment]
If you have the same issue with Breeze icons then something is wrong in your system or your distro... Just for the record, this should influence also your plasma panels in plasma 5.10

**Comment by michaldybczak** [comment]
OK, will work on that. Never had a need to change that till now.

Any reason why should I set panel icons specifically to 256px? In Latte settings size of an applet is set 56px for me. I have no idea how that icon sizes option works out. I need only change icons for latte dock, not for plasma panel - those icons are fine.

**Comment by psifidotos** [comment]
since plasma 5.10, the plasma developers decided that this option will restrict the size of the applets in the panel... so this is a **maximum size** (concerning thickness) for applets in the panel... the 256px option for Latte translates that the applets can grow as much as they please...

>  I need only change icons for latte dock, not for plasma panel - those icons are fine. 

strange... increase your plasma panel thickness, do the icons continue to fill all its height?

**Comment by psifidotos** [comment]
plasma 5.10 issues:

https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-some-applets-in-my-dock-are-shown-too-small-from-plasma-510-and-beyond-can-i-fix-this

https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-behaves-strangely-from-plasma-510-and-beyond-can-i-fix-this

**Comment by psifidotos** [comment]
> As you can see, size can easily go beyond that what I see on latte dock for widgets, so it's maybe the maximum size is not the issue.

I dont see in your screenshot from the plasma panel the applets that have the issue in  Latte...

**Comment by psifidotos** [comment]
to compare from my system (plasma 5.10 in Tumbleweed) last two applets after clock is a minimize all and the trash... zoomed with the parabolic effect even above 128px....

![image](https://user-images.githubusercontent.com/2216474/26934249-8a1e7d88-4c71-11e7-8e89-a301cbb17b4f.png)

**Comment by michaldybczak** [comment]
I checked those widgets on upper panel and you're right. All of them resize except minimize all and trash bin... Any thoughts?

**Comment by psifidotos** [comment]
those two behave properly concerning the new plasma architecture... :-)

What needs to happen to work everything ok..
1. You must find why the pane icon size is greyed out
2. set it to 256px

**Comment by michaldybczak** [comment]
OK, problem solved.

I tried Breeze icons again and to my surprise, this time options weren't grayed out. I changed to 256px on panel icons, applied and then changed to La Capitaine icons. Guess what? Settings on Breeze carried over to other icons, so now those widgets have right size again.

Thanks for support :)

**Comment by psifidotos** [comment]
no worries
