### ISSUE TITLE
Disable window grouping

### ISSUE THREAD

**Issue by Gibbz** [psifidotos/Latte-Dock#526]
Would love to see an option to disable window groupings on the dock. Each instance of firefox for example, would have its own icon...

**Comment by psifidotos** [comment]
Unfortunately this is out of Latte design decisions...

**Comment by psifidotos** [comment]
an update on this... looking the libtaskmanager and plasma taskmanager that was pretty simple and straight forward... so I added it...

of course:
1. dont expect Latte to remember the ungroup choices
2. dont expect this to be made for all tasks, is going to be a user action per task to toggle group/ungroup

![image](https://user-images.githubusercontent.com/2216474/27003169-5ba6fa90-4dfa-11e7-972c-bf418bde4d40.png)
