### ISSUE TITLE
Dock dodges maximized window on different screen.

### ISSUE THREAD

**Issue by valeth** [psifidotos/Latte-Dock#527]
When I set visibility to `Dodge Maximized` I would expect it to dodge maximized windows on the screen where the dock is placed.

Instead it disappears even if a window is maximized on an entirely different screen.

**Comment by psifidotos** [comment]
@valeth nice catch!

@audoban any ideas ?

**Comment by psifidotos** [comment]
I suppose we need a geometry check that the maximized window overlaps the dock geometry

**Comment by audoban** [comment]
I will check what happens.

**Comment by audoban** [comment]
@valeth Tell me the steps to reproduce the bug. I can not find it.

**Comment by psifidotos** [comment]
@audoban do you have a multi screen environment, and this works ok?

**Comment by psifidotos** [comment]
@audoban the dodgeMaximized function in visibilitymanager checks the width and height of the window for the docks screen but it doesnt check if they are both in the same screen, if they intersect each other... also, is there a specific reason that you didnt use the isMaximized flag of the window?

**Comment by audoban** [comment]
@psifidotos I want to give a bit more of tolerance dodgeMaximized, because sometimes a window is not maximized but your geometry is almost equal to screen geometry. I have another screen then i will check what happens on a environment multiscreen.

**Comment by psifidotos** [comment]
makes sense...

please if you try in a multiscreen environment, can you please check also the Copy function if it places correctly the new instance in an explicit alternative screen?

**Comment by audoban** [comment]
Doesn't work correctly.

Current situation.
1. If I copy a dock, the dock will be instanced in the alternative screen.
2. When I want copy again with first dock, the copy function doesnt works anymore.
3. In the alternative screen I have the second dock, if I copy the dock, the new dock appears on top screen.
4. If I try copy the dock, the new dock appears again on top screen, then I have 2 docks on the same edge.

_left screen alternative, right primary screen_
![spectacle x12343](https://user-images.githubusercontent.com/7884292/27014032-a2fe99d2-4eb5-11e7-8b8a-3d8a1b88c21f.png)

**Comment by audoban** [comment]
Hello @valeth, the bug has been fixed in master

**Comment by psifidotos** [comment]
unfortunately i dont a multi-screen environment to see what is happening...

> If I copy a dock, the dock will be instanced in the alternative screen.

this is correct

> When I want copy again with first dock, the copy function doesnt works anymore.

this is not correct and I dont know why

> In the alternative screen I have the second dock, if I copy the dock, the new dock appears on top screen.

this is partially correct, you have also one top dock at your primary screen... This dock should be added in the alternative screen but at the left edge

> If I try copy the dock, the new dock appears again on top screen, then I have 2 docks on the same edge.

this is strange... should only happen at the bottom edge....

something is happening and the code doesnt use at all the left and right edges of the screens

**Comment by psifidotos** [comment]
@audoban I created #537 in order to track a bit this down... I uploaded also one new commit in case it improves a bit the situation...
