### ISSUE TITLE
Text in dropdown menus hardly readable when using dark colorscheme

### ISSUE THREAD

**Issue by valeth** [psifidotos/Latte-Dock#529]
Nothing major, just some little annoyances.

Light plasma theme and colorscheme
![screenshot_20170610_154337](https://user-images.githubusercontent.com/3198362/27003292-2422710e-4df4-11e7-9255-64d6dd24f5ce.png)

Light plasma theme and dark colorscheme
![screenshot_20170610_154428](https://user-images.githubusercontent.com/3198362/27003295-32198fae-4df4-11e7-8daa-6f47a0b9c3bb.png)

Dark plasma theme and dark colorscheme
![screenshot_20170610_154525](https://user-images.githubusercontent.com/3198362/27003300-3c902542-4df4-11e7-941d-94afd7650f42.png)

**Comment by psifidotos** [comment]
we are using the **PlasmaComponents.ComboBox**  which is provided by plasma... so this is a plasma issue and it would be good to discuss it at **bugs.kde.org** !! it effects all plasmoids using the same component....

**Comment by psifidotos** [comment]
in case you report this, please add here the link as a reference...

**Comment by valeth** [comment]
Looks like there are already some potentially related issues open about this.

https://bugs.kde.org/show_bug.cgi?id=366543
https://bugs.kde.org/show_bug.cgi?id=279446

**Comment by psifidotos** [comment]
@valeth they look a bit outdated... I think it is better to add a new bug for  **plasma-framework** from which **PlasmaComponents.ComboBox** is provided and I would attach also the screenshots in order to help the developers understand what is happening...

**Comment by valeth** [comment]
@psifidotos Alright, opened a new issue.

https://bugs.kde.org/show_bug.cgi?id=381065

**Comment by psifidotos** [comment]
nice !
