### ISSUE TITLE
Dock will not raise if my cursor Enter, Leave and Enter dock area quickly.

### ISSUE THREAD

**Issue by 0140454** [psifidotos/Latte-Dock#53]
First, appreciate your excellent work.
Latte-Dock provides me some features not included in other software, so i love it much.

But, during this period of time, i face a problem:
No matter how long show/hide timer interval is, dock will not raise if move cursor into/outside it quickly.

I recorded a video and uploaded to Youtube, please take a look, thank you.
https://youtu.be/6FYO4Hbm_PI

**Comment by psifidotos** [comment]
please check again with latest master

**Comment by 0140454** [comment]
Sorry for late reply, this problem is gone.
Thank for your work.
