### ISSUE TITLE
Cannot remove additional dock plasmoids from panel

### ISSUE THREAD

**Issue by valeth** [psifidotos/Latte-Dock#532]
If I add additional dock plasmoid widgets via the add widget menu of Plasma, I can't remove them, at least not in any obvious manner.

Hope this video demonstrates the issue a bit.
https://youtu.be/T-dc3Tg7oZs

I can remove it by editing the config file, but I don't think a regular user would like to do this.

I tested this with both v0.6 and git master.

**Comment by psifidotos** [comment]
add a second dock and afterwards you will be able to delete them

**Comment by valeth** [comment]
@psifidotos ok, this seems to work.

This probably was made this way to prevent removal of the last dock plasmoid in the panel right?
If so, couldn't you simply check if there are more than one dock widgets in the dock and allow removal until just one remains?

It just seem a bit unintuitive having to create a new dock, just to remove something in the current one.

**Comment by psifidotos** [comment]
> This probably was made this way to prevent removal of the last dock plasmoid in the panel, right?

yes

> It just seem a bit unintuitive having to create a new dock, just to remove something in the current one.

from your video you are using v0.6, in master branch you can remove all Latte plasmoids if you want even the last one through the Tweaks page. The last commit also prevents the user from adding a second Latte plasmoid in the same dock... Latte Dock wasnt designed to hold more than one Latte plasmoid in it...

**Comment by valeth** [comment]
Alright, if you can't add them anymore this is no longer a problem.

It was still possible with the AUR git package I built yesterday, but it looks like there were quite a few changes since then.
