### ISSUE TITLE
Show the panel background only for maximized window

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#535]
Why not...
"show the panel background only for maximized **and active** window" ?

**Comment by psifidotos** [comment]
why yes?

**Comment by JenaPlinsky** [comment]
![spectacle g15400](https://user-images.githubusercontent.com/24593950/27012783-b1294486-4ed7-11e7-8059-e4d64c45bc13.png)
![screenshot_20170611_185511](https://user-images.githubusercontent.com/24593950/27012784-bfceb19c-4ed7-11e7-902f-830caa0abf1b.png)

To avoid cases like this ... who uses this option does it exclusively to make the maximized and active window more readable
![screenshot_20170611_185439](https://user-images.githubusercontent.com/24593950/27012786-c3f551e0-4ed7-11e7-9723-0c5f9632e6a6.png)

**Comment by psifidotos** [comment]
I use it much different than what you demonstrate.. it is a different use case... i use it at the top bar in combination with the active window control....

Nonetheless, how did you produce the third screenshot? Is the maximized window minimized and the background is still shown?

**Comment by JenaPlinsky** [comment]
> I use it much different than what you demonstrate.. it is a different use case... i use it at the top bar in combination with the active window control....

Ah ok I now understand 

> Nonetheless, how did you produce the third screenshot? Is the maximized window minimized and the background is still shown?

yes it is a maximized window and minimized

**Comment by psifidotos** [comment]
> yes it is a maximized window and minimized

this sounds like a bug... but I cant reproduce in my system....

**Comment by psifidotos** [comment]
> yes it is a maximized window and minimized

ok... no I remembered... You are using window previews for all windows right... So the minimized state is not working properly for you....
