### ISSUE TITLE
Inconsistent multi-screen behavior for Copy method

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#537]

**Comment by psifidotos** [comment]
1. If I copy a dock, the dock will be instanced in the alternative screen.
2. When I want copy again with first dock, the copy function doesnt works anymore.
3. In the alternative screen I have the second dock, if I copy the dock, the new dock appears on top screen.
4. If I try copy the dock, the new dock appears again on top screen, then I have 2 docks on the same edge.

**Comment by psifidotos** [comment]
@audoban I have created fix537 branch, can you test it please ? there is a chance the containmeni->screen() can not be trusted in some cases... the new code follows a new approach...

**Comment by psifidotos** [comment]
I found more code that wasnt working always correct because of wrong usage in functions of **containment->screen()** this returnes too often -1 and breaks some functionality... I updated in places I discovered...

**Comment by psifidotos** [comment]
merged the code in master... was containing some very important fixes...

**Comment by audoban** [comment]
It's too unpredictable, I dont know what happend. Sometimes works, sometimes the function create 2 copies, sometimes the button of remove dock doesn't work.

**Comment by audoban** [comment]
@psifidotos I honestly do not know where to start. XD

**Comment by audoban** [comment]
@psifidotos In short, it is the same or worse than before.

**Comment by audoban** [comment]
1. The dock is creating two copies
2. when I remove a copy, the second copy is impossible remove from the ui

**Comment by psifidotos** [comment]
1. The add dock works ok?
2. In single screen environment how Copy behave?

**Comment by audoban** [comment]
In single screen, doesnt works

**Comment by psifidotos** [comment]
> sometimes the function create 2 copies

Dont press a second copy before the first copy dock has appeared...

**Comment by audoban** [comment]
@psifidotos with a click the dock create 2 copies on the alternative screen

**Comment by psifidotos** [comment]
> In single screen, doesnt works

in my system works always... in single screen no issues are appearing in my system... something doesnt like... the function is called copyDock in corona, i dont know what parts of it fail in your system

**Comment by psifidotos** [comment]
> @psifidotos with a click the dock makes 2 copies on the alternative screen

The adddock function or the copy?

**Comment by audoban** [comment]
The function copy

**Comment by Jazqa** [comment]
1. If I copy the bar in multiscreen environment it knows the edge is available but places the dock on top of the older one in the main screen.

2. If I move the bar to the other screen the next copy works like it should (copying the dock to the first available edge on the screen it was copied from, works for both displays)

3. If I try to copy the correctly copied bar from step 2. step 1. repeats itself.

**Comment by psifidotos** [comment]
I think I found it...
if it isnt much of a trouble can you recheck (1) and (3) if they now behave correctly with latest master?

**Comment by Jazqa** [comment]
I pulled it a minute ago and rebuilt it. It's still the same as above. 

As a side note. Latte doesn't like the overlapping docks and seems to shut itself down easily without any messages.

**Comment by psifidotos** [comment]
I see... I wish I had a multi-screen environment to track this down...

for crashes you can follow #147

**Comment by Jazqa** [comment]
I tend to use only one screen. Two is just distracting. Mostly use the second display port for TV and Netflix. Anyways, I need to bounce now. I'll delve deeper into the crash tomorrow (if nobody else has). Great job with the 1px bug and awesome job on the dock overall. I just switched to KDE yesterday and I have to admit, this is the best dock available for Linux.

**Comment by psifidotos** [comment]
Ok... I found a way to use my multi-screen environment which is unfortunately plasma 5.8 to behave gently with our master branch... this lead in the previous commit which should solve this...

@audoban @Jazqa if you can check it out my pleasure in case we can do any better...

> I just switched to KDE yesterday and I have to admit, this is the best dock available for Linux.

@Jazqa happy having you in the plasma wagon... :)

**Comment by audoban** [comment]
When I click on copy nothing happens, both in multiscreen and in single screen.

**Comment by psifidotos** [comment]
the docks were created correctly but disabling the show() for dockview's  they didnt show in that case, closing Latte, starting it they copied docks were appearing... restored the show() and double checked with wayland that it isnt crashing... in the process founded and fixed also a case that copy didnt work properyly in wayland...

multi-screen in wayland is totally new chapter and I dont know how things will go in the future... more stability from upstream is needed for this...
