### ISSUE TITLE
AutoStart not saving preference.

### ISSUE THREAD

**Issue by drops77** [psifidotos/Latte-Dock#539]
Straight forward, i click auto start on startup, and the preference does not 'stick'.

**Comment by psifidotos** [comment]
confirmed... if you are using master branch, I renamed a few weeks ago our desktop file and I dint update the autostart feature... I will fix it during the day

**Comment by psifidotos** [comment]
@drops77 ok... you can check master branch again...

**Comment by drops77** [comment]
works perfectly now,thank you
