### ISSUE TITLE
applets in need attention state must make the dock appear if it is hidden

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#54]
the dock can appear itself for as long an applet needs attention

**Comment by audoban** [comment]
well, we can lock hidding property, when a plasmoid needs attention and use a timer for auto unlock the property of visibilitymanager.

**Comment by psifidotos** [comment]
> well, we can lock hidding property, when a plasmoid needs attention and use a timer for auto unlock the property of visibilitymanager.

or we can just wait for the applet to stop the attention needed by it

**Comment by audoban** [comment]
> or we can just wait for the applet to stop the attention needed by it
yes, is better.

**Comment by psifidotos** [comment]
> yes, is better.

one question, by settings blockHiding to true for visibilitymanager when the dock isHidden, does the visibilitymanager takes care of showing the dock?

**Comment by audoban** [comment]
Visibility manager set isHidden to false and call mustBeShown.
