### ISSUE TITLE
Feature/Bug: Vertical dual monitors unable to move windows across bar

### ISSUE THREAD

**Issue by pecigonzalo** [psifidotos/Latte-Dock#541]
As explained in the title, If i have a dock that sits on the `top` of `screen 1` and my `screen 2` is set vertically on top of `screen 1` I can't move the windows as they try to "stick" to the bar. I can move them if I hold `alt` and drag.

**Comment by psifidotos** [comment]
This is a known X11 and kwin limitation... Nothing to do with Latte
