### ISSUE TITLE
[Qt 5.9] - Activating a window preview from a group stucks the parabolic effect

### ISSUE THREAD

**Issue by valeth** [psifidotos/Latte-Dock#544]
The grow animation when hovering over icons sometimes gets stuck, and the last item you hovered over stays. It seems to fix itself when opening and closing the settings menu.

Not sure if this is related to #428 or not.

Using git ref 81b8e94

**Comment by psifidotos** [comment]
Qt version? plasma version? Can you make a video?

**Comment by valeth** [comment]
Qt version: 5.9.0
Plasma version: 5.10.2
Frameworks version: 5.35.0

I can make a video if it happens again, I'm not sure what triggers it yet.

**Comment by psifidotos** [comment]
ok... at least it isnt happening always...
try to check if this is triggered by right-click... 

1. right click in a icon
2. close the context menu by clicking on the desktop

**Comment by valeth** [comment]
@psifidotos I managed to reproduce it
https://youtu.be/29jY7VpeOVg

**Comment by valeth** [comment]
I tested this with an AMD RX480. I would have Intel and Nvidia hardware on which I could test, in case it's a video driver bug.

**Comment by psifidotos** [comment]
no this isnt a driver issue... it is an issue of not reaching a leave event in the dock or an unblocking one from internal from our dock...

I would like some answers with the following:

Steps to reproduce:

1. Show two window previews of Oracle VirtualBox
( Q1: does it occur also for one preview? Q2: does it occur also from other programs previews?)
2. The previews window that is appearing must be exactly above the virtualbox window
3. Activate the VirtualBox preview
the parabolic effect stucks...

you can also try:
`latte-dock -d --with-window`

it appears a debug window and it will show us which variable stuck...

**Comment by valeth** [comment]
Only one preview seems to be fine.
I could reproduce it with Konsole windows as well.
The previews window does not need to be over the window that is activated, tested it with a window on a different screen as well.

Debug window with Konsole stuck
![screenshot_20170615_165500](https://user-images.githubusercontent.com/3198362/27187434-81babe5c-51eb-11e7-9e65-0827e749f4e2.png)
![screenshot_20170615_165519](https://user-images.githubusercontent.com/3198362/27187462-9221b5ac-51eb-11e7-840a-7677d5c33142.png)

**Comment by psifidotos** [comment]
@valeth , please can you test branch `fix544` to see if it helps?

**Comment by valeth** [comment]
@psifidotos still happening with this build

**Comment by psifidotos** [comment]
> still happening with this build

unfortunately I cant reproduce in my system in any way... so, no more ideas for now...

**Comment by psifidotos** [comment]
@valeth if you use branch fix544 then if that happens then the minimum that should provide is the following....

When the issue occurs if you move the mouse inside the dock and outside afterwards then the parabolic effect should work ok afterwards... is that the case?

**Comment by psifidotos** [comment]
@JenaPlinsky can you confirm this behavior ?

**Comment by valeth** [comment]
@psifidotos I need to correct myself.
It looks like something in my config file was interfering.

I completely wiped my Latte configuration and tried again with master which still had the bug.
Then wiped the config again and reinstalled from the fix544 git branch.

The patch seems to fix the problem, so you can close this issue if you merge it.

**Comment by psifidotos** [comment]
@valeth no prob... nice!
