### ISSUE TITLE
[Bug] System Tray and program activator

### ISSUE THREAD

**Issue by VandaLHJ** [psifidotos/Latte-Dock#545]
When i have icon overload (they don't fit into tray, all icons start to shrink down in space. After i make enough space to get applications and panel back to old size, the system tray and program activator (or whatever it's in english) stay small size (and don't get grouped two in one row in case of systemtray plasmoid).

Also, it looks that dividers/spacers are both taking one space on tray, it's possible to have just one spacer or perhaps make both count as one space if they are touching each other on panel?
![screenshot_20170616_033126](https://user-images.githubusercontent.com/28790923/27208235-d5bfb936-5244-11e7-8a15-c35bb4e4b068.png)

**Comment by psifidotos** [comment]
1. If you want to disable the automatic shrinking mechanish you can from the tweaks page

2. All the systray behavior is plasma code and nothing to do with Latte. If you can replicate the same problem with a plasma panel you can report the issue at bugs.kde.org . My guess for the systray not growing afterwards is that it needs more space, your dock icon size hasnt restored completely yet, try to disable 1 and see what happens

3. The dividers dont take any space in normal mode (that is when the configuration winfow isnt shown). What you observe is that automatic shrinking starts earlier than it should. The automatic shrinking algorithm is highly sophisticated so in v0.6 to not fall in other problems we have set its triggering points earlier. In mastet branch we have fixed this
