### ISSUE TITLE
untranslated strings

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#549]
![screenshot_20170617_105456](https://user-images.githubusercontent.com/24593950/27252445-ec3a788e-535e-11e7-8cf7-f624616ecd38.png)
![screenshot_20170617_105456](https://user-images.githubusercontent.com/24593950/27252454-475aae6e-535f-11e7-8e83-e640f481e102.png)

**Comment by psifidotos** [comment]
except "Zoom On Hover" everything else has been included in the June translation strings, they appear just fine in greek in my system...

All the rest will be merged for translation on first days of July

**Comment by JenaPlinsky** [comment]
#547 updates some missing translations
