### ISSUE TITLE
when the icon is invalid, latte show a blank icon.

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#55]
if the icon is invalid latte would set a default icon.

**Comment by audoban** [comment]
![screenshot_20170113_145406](https://cloud.githubusercontent.com/assets/7884292/21943965/a0ee47b6-d9a1-11e6-99ef-8de0a5e22c49.png)

**Comment by psifidotos** [comment]
is it breeze?

which icon is missing?

**Comment by audoban** [comment]
is gitkraken.

**Comment by psifidotos** [comment]
:+1:

**Comment by audoban** [comment]
I'm going to upload this to the master, you agree?

**Comment by psifidotos** [comment]
of course
