### ISSUE TITLE
Officialy on Fedora repositories

### ISSUE THREAD

**Issue by marcdeop** [psifidotos/Latte-Dock#554]
There is no need to enable an external repository for Fedora any more. The package is on the repositories: https://admin.fedoraproject.org/pkgdb/package/rpms/latte-dock/

A simple `dnf install latte-dock` will do the trick :-)

**Comment by psifidotos** [comment]
perfecto!!! :-)

thanks everyone contributed in this!!!

**Comment by psifidotos** [comment]
I have updated  the links for Fedora in the README file...
