### ISSUE TITLE
Windows overlap with Latte Dock

### ISSUE THREAD

**Issue by Jazqa** [psifidotos/Latte-Dock#555]
Trying to set-up an Unity-like desktop, I couldn't help but notice that all windows (including Application Menu) overlap a pixel with Latte Dock and panels made with Latte Dock (which is why it's annoying with the Unity preset as it uses Latte Dock as its top panel).

How to replicate: 
- Create a new latte dock
- Adjust background size to 100%
- Set to "always visible"
- Place a menu on dock or make a window full-screen

Picture of a menu overlapping with dock:
![image](http://i.imgur.com/2NcZeFq.png)

**Comment by psifidotos** [comment]
ok ... some insights for this one... 

1. Background 100%, zoom 0%, Justify alignment and Always Visible falls back to plasma panel behavior, so you should get the same result with plasma...

how does this behave in your system?

2. Concerning all other cases... it is a different behavior for app menus and a different for fullscreen windows... The first case uses the kde frameworks and the popups and windows are placed based on their parent applet item, the second case uses the struts...

I would try first (1)  and compare it with a panel... what results do you get?

**Comment by Jazqa** [comment]
Everything is one pixel too far on Latte.

Plasma:
![](http://i.imgur.com/g0dWjLH.png)

Latte:
![](http://i.imgur.com/YbEcr0p.png)

The issue is most visible in this picture:
![](http://i.imgur.com/lXsm0KK.png)

**Comment by psifidotos** [comment]
what theme are you using ?

**Comment by Jazqa** [comment]
The default one, never changed the theme

**Comment by Jazqa** [comment]
If you have blur on (desktop effects) the issue is not very visible but it's still there.
![](http://i.imgur.com/ilfdDkb.png)

I've tried with different size options under "window decorations" but the size doesn't seem to matter.

**Comment by psifidotos** [comment]
@Jazqa I think I found it... nice catch...

Please, if you have a multi-screen environment can you check the right edge behavior for AlwaysVisible? If you dont, no matter...

**Comment by Jazqa** [comment]
Quickly tried it and it should be working fine.

**Comment by psifidotos** [comment]
@Jazqa what you cant remove ?

**Comment by Jazqa** [comment]
Edited the comment above. Couldn't remove the dock without moving it back to main display. Nothing happened when I clicked the remove button.

**Comment by Jazqa** [comment]
It seems like the docks can't be removed on a secondary display, no matter the alignment.

**Comment by psifidotos** [comment]
you have a remove button but you cant remove it? Did you create with New or Copy?

**Comment by Jazqa** [comment]
I tried both. The remove button does absolutely nothing on my secondary display. As soon as I move it back to main display I can remove it. Weird.

**Comment by psifidotos** [comment]
thank u!!! :) found it... #556 , should be ok now...  is there a chance that you have time to help debug also #537 ? do you have telegram?

**Comment by Jazqa** [comment]
Nope, don't have telegram. Removing the dock works now. I'll check the rest soon.

**Comment by psifidotos** [comment]
ok... thank u... 

the mentioned #537 should behave like this...

when copying a dock in single screen environment the new dock should be positioned in the first available edge in that single screen...

in multi screen environment, the copy method should create the same dock in the next screen that has the same edge available...

both of them have been reported that dont work in some environments and I am still researching what is going on...

**Comment by Jazqa** [comment]
1. If I copy the bar in multiscreen environment it knows the edge is available but places the dock on top of the older one in the main screen.

2. If I move the bar to the other screen the next copy works like it should (copying the dock to the first available edge on the screen it was copied from, works for both displays)

3. If I try to copy the correctly copied bar from step 2. step 1. repeats itself.
