### ISSUE TITLE
Email counts show up on other icons

### ISSUE THREAD

**Issue by poetimp** [psifidotos/Latte-Dock#557]
Thunderbird email counts show up on other icons and stay there even when Thunderbird is restarted. 

![lattedocicons](https://user-images.githubusercontent.com/3538244/27349518-60b71402-55ac-11e7-9855-290fc692a7a8.png)

**Comment by psifidotos** [comment]
how do you see the thunderbird e-mails? what plugin are you using?

**Comment by poetimp** [comment]
I am not running any plugin. I simply run Thunderbird. It must have some means of communicating the number of emails that are unread to KDE. I do not know what that mechanism is. There is no special plugin installed anywhere to facilitate this behavior. 

I see the issue often but I am not able to reproduce it at will. It does not happen all of the time. Just occasionally. When it does, restarting LatteDock will clear the counters off of the other icons.

**Comment by psifidotos** [comment]
strange... it uses libunity to achieve this...

please close latte and add a plasma panel with an icon-only taskmanager in it ... does the same problem occurs again?

it is the only way to see if this is latte fault or not

**Comment by psifidotos** [comment]
Please check also in thunderbird addons for unity or docky something..

**Comment by poetimp** [comment]
Will do, It may take a while for it to occur again. I will let you know.

**Comment by poetimp** [comment]
Turns out it happens in icon-only as well. So, apparently,  not your problem :)

**Comment by psifidotos** [comment]
;) thanks for the commitment...
