### ISSUE TITLE
Dodge all windows and activities 

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#558]
I have checked dodge all windows option. My dock shows only windows from one activity, but dodge windows from all activities.
1. I'm on activity 1 with open window(latte dock dodge that window)
2. Switch to second clear activity - latte dock still hiding

**Comment by psifidotos** [comment]
I suppose you mean that on Activity change the dock is not restored even though it should...

@audoban can you please check this?

**Comment by audoban** [comment]
ok

**Comment by audoban** [comment]
@divinae You can try now

**Comment by divinae** [comment]
works now :)
