### ISSUE TITLE
Add libSM to Kubuntu/KDE Neon installation guide

### ISSUE THREAD

**Issue by Jazqa** [psifidotos/Latte-Dock#560]
The correct package is libsm-dev on Ubuntu repositories. If the package is not installed running `sh install.sh` gives the following error.

![screenshot_20170621_211414](https://user-images.githubusercontent.com/18004783/27399902-03972f48-56c7-11e7-99bb-b28429c0f8e8.png)

**Comment by psifidotos** [comment]
in README it was updated...

for INSTALLATION.md file can you make a pull request please? this file in maintained totally from community members

**Comment by psifidotos** [comment]
merged...
