### ISSUE TITLE
[Feature Request] - Option to manipulate icon shadows

### ISSUE THREAD

**Issue by MarianArlt** [psifidotos/Latte-Dock#566]
Latte is increasingly beautiful, thanks for your awesome work.
There are a lot of options already and I'd like to see even more:
Let me manipulate at least the opacity of the icon shadows or even the size.
Also would it be possible to add extra opacity to the dock background?
The opacity option on icon shadows would be really nice since the shadows are really hard by default but on the other hand without them some icon themes are hard to read/perceive (legibility!)

**Comment by psifidotos** [comment]
> Latte is increasingly beautiful, thanks for your awesome work.
 
thanks

> There are a lot of options already and I'd like to see even more

the thing is that we dont want to make the configuration window overcrowded

> Let me manipulate at least the opacity of the icon shadows or even the size.

I am positive to replace the current applet shadows activation which is (None,Locked,Everywhere) with a layout like the panel background one:

Applet Shadow
[X] Show  | Opacity: 0-100% (Slider)   [this row will be shown in basic mode]
[Color Btn] | Size: 0-50% (slider)   [this row will be shown only in advanced mode]

@audoban what do you think for this? I would like to test how it would go.... the fact is that we dont offer alternative themes so providing maximum customizability for the plasma theme used I think is good to provide...

> Also would it be possible to add extra opacity to the dock background?

isnt that already implemented ?

**Comment by audoban** [comment]
> [X] Show | Opacity: 0-100% (Slider) [this row will be shown in basic mode]
[Color Btn] | Size: 0-50% (slider) [this row will be shown only in advanced mode]

I'm agree with the customization of the opacity and the size.

**Comment by audoban** [comment]
> @audoban what do you think for this? I would like to test how it would go.... the fact is that we dont offer alternative themes so providing maximum customizability for the plasma theme used I think is good to provide...

Yes we can to test

**Comment by MarianArlt** [comment]
>> Also would it be possible to add extra opacity to the dock background?

> isn't that already implemented ?

The background options in 0.6.2 from pacman repo are:
**[ _ ]** Show panel background **[ _ ]** Solid background
**---------------------------------[ _ ]---------------** Slider with percentage determining the background **_height_**
Don't know if this has been expanded in Git version already.

**Comment by audoban** [comment]
On the master version you can change the transparency of background

**Comment by psifidotos** [comment]
![image](https://user-images.githubusercontent.com/2216474/27518504-33c67a72-59ea-11e7-8de6-72a13a1babe0.png)
