### ISSUE TITLE
Show Title Tooltips for Tasks

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#567]
there are plenty users asking for this, based on the fact that they were using it a lot in other docks...

**Comment by psifidotos** [comment]
I have tried once to implement it properly but the visual result wasnt sufficient

**Comment by audoban** [comment]
I think that would be fine. Why does not it convince you?

**Comment by psifidotos** [comment]
The toolips were out of place and they werent positioned predictable. I am thinking about one single tooltip in the center for all tasks. These tooltips also should disable  the window previews feature we cant have both at the same time

**Comment by psifidotos** [comment]
ok... I found a way for these tooltips to positioned properly at least on the thickness side...

![image](https://user-images.githubusercontent.com/2216474/28631508-2349a41c-7236-11e7-8891-061a3f181956.png)
