### ISSUE TITLE
[wayland] - support AlwaysVisible visibility mode

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#569]
more specific the struts mechanism..

**Comment by audoban** [comment]
I am working about this.

**Comment by psifidotos** [comment]
perfect

**Comment by psifidotos** [comment]
@audoban, I think we can close this right? the commit didnt have the **fix #** in order to close it automatic

**Comment by audoban** [comment]
I did not put it fix, because maybe I would have a bug. However works perfectly

**Comment by psifidotos** [comment]
I just checked it in wayland!! works just fine!
