### ISSUE TITLE
mouse wheel

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#57]
suppose you have a folderview containing different apps
it would be interesting if the icon corresponding to folderview instead represent the category of the apps contained in it, would represent an element in it and then have the ability to cycle through the items with the mouse wheel.

I've seen this feature in an old dock and was very comfortable .... in doing so, you avoid the mouse clicks on folderview and you have direct access to content

**Comment by audoban** [comment]
I like your idea. This same behavior has the plasma icon launcher.

**Comment by psifidotos** [comment]
> suppose you have a folderview containing different apps
> it would be interesting if the icon corresponding to folderview instead represent the category of the apps contained in it, would represent an element in it and then have the ability to cycle through the items with the mouse wheel.

> I've seen this feature in an old dock and was very comfortable .... in doing so, you avoid the mouse clicks on folderview and you have direct access to content

unfortunately this isnt dock's responsibility... this must be implemented is the folderview plasmoid, thus this is a plasma concern... As  long as the folderview provides this functionality the dock will also just provide it automatically

**Comment by audoban** [comment]
@psifidotos Can I add this functionality then?

**Comment by psifidotos** [comment]
@audoban where? are you going to fork folderview?

**Comment by audoban** [comment]
When you have several instances of the same application and these are grouped, it should be possible to change the application with the mouse wheel.

**Comment by psifidotos** [comment]
> When you have several instances of the same application and these are grouped, it should be possible to change the application with the mouse wheel.

this is not what the user is asking. The user wants from the folderview applet to cycle through its contents by using the mouse wheel and updating its icon on the dock accordingly. 

@JenaPlinsky did I understand correctly?
