### ISSUE TITLE
[feature-request] - Set width of Panel Spacer

### ISSUE THREAD

**Issue by sh4nks** [psifidotos/Latte-Dock#572]
Hey,

Is it possible to somehow set a specified width (i.e. 1px, 2px, ...) in the Panel Spacer?

btw, great job at Latte Dock! I am looking forward to the 0.7 release.. even though I am living on the edge using the git version ;)

**Comment by psifidotos** [comment]
We have enforce the spacer to the applet size... but it could be a good feature request

**Comment by psifidotos** [comment]
I think that we are going to implement a Latte spacer... it is going to accept a percentage of latte icon size and not only size in pixels

**Comment by sh4nks** [comment]
Cool awesome! So it will accept both pixels and percentage?

**Comment by psifidotos** [comment]
Yes, when used in Latte by default will accept percentage, but you can change it. When uaed in plasma panel will accept only pixels..  you will be able to increas/decrease easily these values with scroll wheel in config mode, when the latte config window is shown... we are in a bit hurry for this as the new version might be released mid of August

**Comment by psifidotos** [comment]
Ok... merged... Latte provides its own unique spacer, you can add it through Tweaks page... by default to percentage and you can choose pixels if you want... It provides a configuration window to apply changes and you can dicrease/increase its length when Latte is in Edit mode by using the mouse scroll wheel...

also extra translation files were added for spacer and separator applets

![image](https://user-images.githubusercontent.com/2216474/28705875-6c00d992-737a-11e7-8e68-4acc0a529d96.png)

![image](https://user-images.githubusercontent.com/2216474/28705893-80b0828e-737a-11e7-9f9c-2f4f4e762fff.png)

**Comment by sh4nks** [comment]
Works flawlessly :)
Thanks again!
