### ISSUE TITLE
latte dock does not show after login. Requires killing the dock and relaunch.

### ISSUE THREAD

**Issue by rahulprabhakar** [psifidotos/Latte-Dock#573]
For last 2 weeks in Manjaro KDE with **latte-dock-git** package installed from Arch User repository, latte dock does not show after login. Requires killing the dock and relaunch.

[Update]: Last Rebuild with latest git code as on 30th June 2017. Issue still persists.

**Observed Behaviour**
Every time i login on first attempt latte-dock will show as a running process in system monitor but dock is not visible. I have to manually kill the process and then run it again from krunner. On second attempt it would show up on the bottom edge as configured.

Error message in Journald log after killing latte-dock process.
**ksmserver: autostart service ("/usr/bin/latte-dock") finished with exit code  15**

For last two weeks i have rebuilt latte-dock from source multiple times. During this duration of 2 weeks
 
Plasma Desktop upgraded from **5.10.0** -> **5.10.1** -> **5.10.2** -> **5.10.3**
KDE Framework upgraded from **5.34.0** -> **5.35.0**
KDE Applications upgraded from **17.04.1** -> **17.04.2**
Qt upgraded from **5.8** -> **5.9**

**Current setup**
KDE Plasma version : **5.10.3**
KDE Frameworks version : **5.35.0**
KDE Application version : **17.04.2**
Qt version : **5.9**

**Comment by rahulprabhakar** [comment]
There is no log entry for latte dock in journald and no errors.

**Comment by rahulprabhakar** [comment]
I removed git version and installed latte dock version 0.6.2 from repository. Now this issue is not reproducible anymore. Pls check code changes since 0.6.2 to identify the root cause for this problem.

**Comment by psifidotos** [comment]
the diffetence is around 600 commits... :-)

**Comment by psifidotos** [comment]
are you working in a multi screen environment?

**Comment by rahulprabhakar** [comment]
yes i have multi screen setup, but laptop display is not used as primary or default. Upon login laptop display is turned off by kscreen becos in system settings i have external monitor enabled and set as primary. I don't use laptop as my primary display.

Did u happen to introduce code changes wrt to multiscreen setup in June 2017 becos this problem started appeared about 2 weeks ago so just have a look to code commits from last week of May2017 till 3rd week of June 2017. I hope code commit wud be less. 

I wud suggest to make stable releases more often. Try not to have 500+ commits between releases else it wud be difficult to debug and fix issues. :-)

**Comment by psifidotos** [comment]
Latte is in a rapid develpoment pace...

What are your settings for your docks? Which screens? Visibility mode, primary? Does anyone of them has latte tasks in it?

**Comment by psifidotos** [comment]
I think that the issue is:

**_when activating an external screen as primary and at the same time disabling the original screen e.g. the laptop one, latte wasnt showing docks at all._** 

I reproduced something similar in my system without needing to relogin. I fixed this and updated also some corner cases that might didnt work corretly... I think this should be ok now... 

can you check please?

**Comment by rahulprabhakar** [comment]
Rebuilt latte dock from git and issue is not reproducible with following code commit.

https://github.com/psifidotos/Latte-Dock/commit/7de8a7430fa5bfb7931c714f55d5e7fff046f009

Arch Linux is still referring to 0.6.2 in official repository. As you commented previously there are around 600 code commits since 0.6.2, request you to push an intermediate release 0.6.3 so that latte dock in official distribution repository could be updated. As of today July 1, 2017 there are only 6 issues in Needsinfo and a bug. Rest all appear to be enhancements.

Waiting to release 0.7.0 would prevent users from experiencing bug fixes, new enhancements and features since 0.6.2.

**Comment by psifidotos** [comment]
Nice solving this... 

unfortunately a 0.6.3 from the master branch is not possible because in our master branch we have break compatibility with qt 5.6 and plasma 5.8 

The v0.6 branch is maintained mainly only for crashes in case these crashes occur in our side. The thing is than none Latte developer is using still qt 5.6 and plasma 5.8


I am sorry but the v0.7 will stay on track until early days of September. It is an open source project so we are doing the best we can in the free time we can provide.... Help is always welcome

**Comment by rahulprabhakar** [comment]
I understand AUR git package is in sync with master branch hence i shud receive updates and bug fixes as we get close to 0.7 release. Since master / 0.7 development depends on plasma 5.9 or higher I can report issues if any observed with AUR git package and test bug fix for the same.

**Comment by psifidotos** [comment]
of course... thank you very much...

> I understand AUR git package is in sync with master branch

I dont know for sure one package I had looked in the past the last time it had been updated was 2-3 June, it wasnt in sync with the master

**Comment by rahulprabhakar** [comment]
latte-dock version in official repos is 0.6.2 since they track official releases only.

I relooked at the PKGBUILD file for "**latte-dock-git**" in aur (Arch User repository). 
Every time a user wud install this package git repo is cloned onto user system and then compiled from source. Since i use this package,  did git pull and then built the package again with latest code change to test ur fix. 

Arch users as well as users of Arch based distro like Antergos and Manjaro supporting AUR wud know how to build package from source using this git package.

**Comment by psifidotos** [comment]
fantastic...
