### ISSUE TITLE
Trying to drop a file on tasks there are rare cases that is not triggered correctly

### ISSUE THREAD

**Issue by introlinux** [psifidotos/Latte-Dock#574]
Hi, when I try drag a file, for example from Dolphin to Inkscape or from Dolphin to Firefox (to loading an image in google images, for example), the target application doesn't raise up automatically when I drag with the mouse to the dock and therefore I can't complete the drop. This is the normal behavior in all panels I know (lxpanel, xfcepanel, mate-panel, even kde panel) but not in Latte Dock.

It would be great if you could incorporate this feature.

Thanks in advance.

**Comment by psifidotos** [comment]
What Latte version are you using? Latte should also behave like this...

**Comment by introlinux** [comment]
Ok, I updated to 0.6.87 and now I only have this issue with Firefox. 
Chrome, Gimp, Inkscape, etc... work as expected.

**Comment by psifidotos** [comment]
@introlinux I cant reproduce this... firefox is shown correctly when I am dragging a file from dolphin on it...

what is you normal procedure to reproduce?

**Comment by introlinux** [comment]
<a href="http://www.youtube.com/watch?feature=player_embedded&v=i2bTqEKpzhg
" target="_blank"><img src="http://img.youtube.com/vi/i2bTqEKpzhg/0.jpg" 
alt="Firefox issue" width="240" height="180" border="10" /></a>

**Comment by introlinux** [comment]
Another thing I don't know if it is normal, go to 1:05 and look at where the video thumbnail has been created: behind the panel. I can place windows behind the panel too. Have I something wrong in the configuration?

**Comment by psifidotos** [comment]
> Have I something wrong in the configuration?

concerning what? the problem with dropping files or that you can place windows behind the panel?

**Comment by psifidotos** [comment]
I managed to replicate this for other tasks also but it isnt that often... Someone can replicate more often when there are only 1-2 tasks shown in the Task manager... 
the issue is that the task is not identified correctly (I dont know why yet) and thus the code path is not ending...

**Comment by psifidotos** [comment]
Concerning 1:05 i dont see any issue

**Comment by introlinux** [comment]
I open a new issue for that topic #578

**Comment by psifidotos** [comment]
@introlinux I think this is fixed now, please check it... Thanks a lot for this one, based on your report I discovered more cases that we could cause inexpected behavior e.g. when dragging tasks around... this now should fix both
