### ISSUE TITLE
[feature-request] - latte shouldnt show shadows when "show background only for maximized windows" is activated

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#575]
As the title says, when this option is set and shadows are set to be disabled, shadows are shown regardless when there is no maximized window.

**Comment by psifidotos** [comment]
This is not an Latte issue... you probably have enabled window previews for all windows even those that are minimized... in x11 this blocks the minimize flag of the windows, in wayland has  been fixed...

**Comment by marhkb** [comment]
I do not understand how this is related to show preview for windows. Maybe the description was not precise. I have preview disabled for minimized windows and also turned it completely off for testing. 

I am talking about the drop shadows of the icons.
The issue occurs when I explicitly set  "applets shadows" to disabled in "appearance" tab.
The applet shadows disappear correctly when I deactivate the option "show background only for maximized windows". But when this option is active, they only disappear when I have an maximized window in the foreground. when there is no maximized window, the applet shadows come back.

**Comment by psifidotos** [comment]
Yes of course, this is default behavior... these shadows are created because there are cases that the contents do not create enough contrast with the underlying background...
