### ISSUE TITLE
[feature-request] on a dock with disabled shadow show shadow when applet is activated 

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#576]
When one has a panel with disabled shadow and one clicks on an applet, then the applet panel has a shadow. This doesn't look very appealing. It would be cool to give the panel a shado as long as the applet panel is open

this
![no-shadow](https://user-images.githubusercontent.com/3630213/27749972-29579f0e-5dd6-11e7-9a15-90ef030842bb.png)

should look like this
![with-shadow](https://user-images.githubusercontent.com/3630213/27749985-3596d33e-5dd6-11e7-9a03-e84350e71402.png)

**Comment by psifidotos** [comment]
Have tryed from tweaks the "show shadow only for macimized windows" ?

Btw there is no should in this, this is a matter of taste. I believe it looks nice but i cant enforce thus for all cases

**Comment by marhkb** [comment]
I seem to not have this option. I have only "no shadow for maximized window".
Because this a matter of taste, an option like "show panel shadow when applet panel is open" would be very useful. I maybe wrong, but if I remember correctly MacOX does this in the same way. 
In my workflow I have panel shadow activated when there is no maximized window. When there is a maximized window, panel shadow disappears - that's fine. But now when I click on the clock applet to show the calendar, I would expect the panel to have the shadow again - as long as the calendar is shown. This shows the user that the focus is on one of the panel's applets.

**Comment by psifidotos** [comment]
@marhkb try the following:
1. Appearance page activate the shadows for the background
2. Tweaks page, enable "show background only for maximized windows"
3. Tweaks page, disable "no shadow for maximized windows"

this should get you the desired effect for applets... but also for maximized windows will also draw shadow

**Comment by psifidotos** [comment]
@marhkb this is merged... In order to work the user must have set a dock to have zoom factor:0% and panel background size:100% . After that when the user expands an applets independent of what the user has chosen for the panel shadows (show or hide) the panel shadow will be shown until the applet is not expanded any more
