### ISSUE TITLE
Latte Redesign and supporting docks per activitiies and layouts on the fly

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#577]
After implementing the dynamic layouts feature that loads the layouts on the fly, we opened the door in a new world... The technical draft around what this is all about and what it will provide when we implement it can be read at: https://docs.google.com/document/d/1ba_cLp0-AFGmUE_z009o0HrsRoOzii33GVCtVUs8H18/edit

Some of the most important features:
- layouts on the fly
- automatic storing for the layouts of the system (current layout will be deprecated)
- cleaner implementation
- activities will be able to gain their own specific layout (different docks per activities)
- crash free changing between different layouts

**Comment by audoban** [comment]
Do you think we can achieve all this before the release?

**Comment by psifidotos** [comment]
We will see... I believe that in the mid of August we will be able to
support everything from the current branch into the new architecture...

Afterwards we will see if layouts per activities are possible...

2017-07-01 21:45 GMT+03:00 Smith AR <notifications@github.com>:

**Comment by psifidotos** [comment]
hehe.... this is already implemented in branch **_newLayouts_**....

**Comment by psifidotos** [comment]
merged the newLayouts in master branch ...
