### ISSUE TITLE
New hiding behavior

### ISSUE THREAD

**Issue by VandaLHJ** [psifidotos/Latte-Dock#579]
Hi, i suggest new hiding behavior, especially useful for something like clock that you don't want to click on. Suggested name is dodge mouseover. It behaves similar to dodge active, but with twist: it is visible nearly always (without hiding when window is maximized or active), but when you put your mouse around it, it hide (you can made it visible by touching the edge of screen, for example to change the setting).

![screen1](https://user-images.githubusercontent.com/28790923/27762104-fe43192a-5e6a-11e7-926f-bd4e33ffd99b.png)

**Comment by psifidotos** [comment]
This reminds me the old BeClock from kwindoweffects...

I think that i am not that fond of the idea...
@audoban  any interest?

**Comment by VandaLHJ** [comment]
Yep, similar to beclock, and the usecase isn't very broad. To be fair, it's nearly only good on laptops with limited space like mine.

**Comment by audoban** [comment]
@VandaLHJ  The feature is a bit similar to autohide and is easy to do, however I have a big question. How will the user to access the settings or calendar of the clock without passing the mouse? ...

**Comment by psifidotos** [comment]
I think we can close this...
