### ISSUE TITLE
Application launcher icons do not scale in "Default-No-Tasks" layout

### ISSUE THREAD

**Issue by raaj-winfred** [psifidotos/Latte-Dock#581]
Hi, I have Latte-Dock v0.6.2 installed in KDE Plasma 5.10.3 (KDE Frameworks 5.35, Qt 5.9.1). I am using "Default-No-Tasks" layout and I am unable to scale the application launcher icons, a screenshot is shown in the link (http://imgur.com/a/IoeU0). The applets size setting shown in the screenshot is 128 px. Even if I scale the applets down to 64 px I am still getting the same icon size. Could you help me in resolving this issue ? Thanks.

**Comment by psifidotos** [comment]
Go to plasma systemsettings, icons, advanced and set the panel icon size to 256px.

Did it work?

**Comment by raaj-winfred** [comment]
> Go to plasma systemsettings, icons, advanced and set the panel icon size to 256px.

Did it work?

It worked ! Thank you very much !

**Comment by raaj-winfred** [comment]
> Go to plasma systemsettings, icons, advanced and set the panel icon size to 256px.

Did it work?

It worked ! Thank you very much !
