### ISSUE TITLE
[feature-request] Separators and pin order inside latte plasmoid

### ISSUE THREAD

**Issue by Barbosabyte** [psifidotos/Latte-Dock#582]
Hi!
It would be great to be possible to add multiple separators wherever we want between pinned apps and an easy way of changing the order of pinned apps inisde latte plasmoid.
Thanks.

**Comment by psifidotos** [comment]
>  great to be possible to add multiple separators wherever we want between pinned apps

From master branch you can add an internal separator between tasks through edit mode, right click on tasks. Dont expect to add more internal separators it is already too complex. Between applets you can add as many as you want through  the widgets explorer, drag the applet separator onto the latte dock

> an easy way of changing the order of pinned apps inisde latte plasmoid

just drag them

**Comment by Barbosabyte** [comment]
Thank you. I did try to drag them before, but I know what I did wrong, and I did it now.
