### ISSUE TITLE
Add GitHub issue templates

### ISSUE THREAD

**Issue by valeth** [psifidotos/Latte-Dock#583]
GitHub offers templates for pull requests and issues.
It might be a good idea to add one that covers important questions like software versions etc in a checklist or something similar.
I would PR it but I think it's better if this is put together by the project owners.

Here's the info page:
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by audoban** [comment]
If we will soon move platform is worth the effort?

**Comment by psifidotos** [comment]
correct... there is a chance to move under kde infrastrucure, so this is irrelevant afterwards
