### ISSUE TITLE
Frame when watching a video

### ISSUE THREAD

**Issue by interact82** [psifidotos/Latte-Dock#584]
Debian 9, KDE-5.8
When watching the video (mpv) in place of Latte-Dock glows the screen in the screenshot indicated by an arrow. How to remove?
PS: English I do not know I write with Google translation
![screenshot_20170705_180737](https://user-images.githubusercontent.com/17098432/27871617-d8690376-61ae-11e7-858d-456a941e1902.png)

**Comment by psifidotos** [comment]
Latte configuration window, Tweaks, Behave as a normal dock window
