### ISSUE TITLE
Latte-dock behavior when start programm

### ISSUE THREAD

**Issue by romanlex** [psifidotos/Latte-Dock#585]
Hello. It's best docker for linux! Thank you very match for this work.
I think it's necessary to add a new function to the docker regarding the behavior. Capture the class of the active window and, for example, hide the docker. 

Example: dock is always visible.
When I use browser: I see latte-dock
When I start IDEA: dock is disappear

**Comment by psifidotos** [comment]
Sorry but i cant understand, can you explain further please?

**Comment by romanlex** [comment]
I'll try to explain again.
I would like a dynamic visibility mode, when at certain maximized windows the docker was hiding or visible.
Suppose I assign a list of programs. When I start program from this list and open in maximized window mode latte-dock change behaivor of visibility

**Comment by psifidotos** [comment]
Sorry but personally  I dont find any interest supporting the case, @audoban what is your opinion?

**Comment by audoban** [comment]
I think it's too much functionality, maybe it can be solved with KWIN rule.
