### ISSUE TITLE
Distorted launcher icons upon waking from sleep.

### ISSUE THREAD

**Issue by soundprizm** [psifidotos/Latte-Dock#586]
I'm not sure if this is a known issue or not, but I couldn't find any information after a search. Whenever I wake up from a sleep state, the launcher icons are distorted/pixelated. Everything returns to normal after a restart. I'm running Plasma 5.10.3 with Latte-dock 0.6.2.

**Comment by psifidotos** [comment]
this is a known nvidia proprietary drivers issue with plasma

**Comment by RaitaroH** [comment]
Yeah is this bug: https://bugs.kde.org/show_bug.cgi?id=364766

Looks like this:
![bug](https://user-images.githubusercontent.com/19552720/36932204-9f351350-1ece-11e8-9536-516d613b1627.png)

**Comment by psifidotos** [comment]
definitely... I switched to nouveau and no issues any more...

**Comment by RaitaroH** [comment]
@psifidotos Not sure I will try. I also have cuda installed for waifu2x and it might fuck it up if I switch the nvidia drivers out. Not sure it will but I really don't want to bother just for a really small bug that can be fixed with just moving the files around or in latte's case just hover.

**Comment by psifidotos** [comment]
@RaitaroH I just mentioned nouveau as proof that this is nvidia proprietary issue...

**Comment by RaitaroH** [comment]
@psifidotos I know, thank you.
