### ISSUE TITLE
Widget placeholder

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#588]
Currently, in edit mode, when I browse widgets, each widget selected has its gray placeholder
Well, when, however, I try to enter on its tool tip, the gray placeholder disappears confusing a bit the 
things
I wonder if it is possible to keep the gray placeholder active when I leave the widget for its tool tip?
![screenshot_20170708_182036](https://user-images.githubusercontent.com/24593950/27987210-36895eda-640a-11e7-8e42-55f0f7424e85.png)
![screenshot_20170708_182005](https://user-images.githubusercontent.com/24593950/27987208-31da205e-640a-11e7-88b9-0f8b3a21f213.png)

**Comment by psifidotos** [comment]
I think it can be done... We are in fantastic break throughs concerning implementation (dynamic layouts, improve code quality etc..)

We I return in development in a few days I will test it
