### ISSUE TITLE
SegFault when starting Virtual-Box (KDE-Starter-Bug)

### ISSUE THREAD

**Issue by LinusCDE** [psifidotos/Latte-Dock#589]
Hi,
some time ago I found a weired bug: When I start Virtual-Box, Latte-Dock crashes.

And yes, I read the "How to Guide" on crashes, but this crash only occurs when I start Latte-Dock via KDE (Startmenu, ALT+F2 or Autostart). When I ran Latte-Dock trough `ddd`, `gdb` or simply the command (zsh), I ran fine and never crashed.

Also when freshly started, the chance of VirtualBox (via Cli or KDE) crashing Latte-Dock is around 30%.

---

Further information:

| Name | Information |
| ---------- | ---------- |
| Distro | Manjaro (KDE) |
| Kernel-Version | 4.8.17-1-MANJARO |
| Plasma-Version | 5.10.3 |
| VirtualBox-Version | 5.1.22-1 |
| Command in .desktop-File | `latte-dock %u` |
| Latte-Dock-Versions tested |  0.6.0.r420.g065837f-1 and 0.6.2-1 |
| Crash information provided by kcrash | [latte-dock-20170708-225447.kcrash.txt](https://github.com/psifidotos/Latte-Dock/files/1133323/latte-dock-20170708-225447.kcrash.txt) |

---

So I guess, its is due to something how KDE intercepts the processes to catch crashes that actually causes them. I personally could not find anything suspicous in the backtrace but I'm also did not much with Qt5 more than simple GUIs in C++ and Python.

**Comment by psifidotos** [comment]
The crash points to libtaskmanager which is a plasma library. Can you please also install the debug package for plasma workspace in case we can find which code inside the libtaskmanager is crashing?

**Comment by LinusCDE** [comment]
I rebuilt the plasma-workspace package with the `-DCMAKE_BUILD_TYPE`-flag set to `Debug` in the [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/plasma-workspace "Arch Package - Pkgbuild"). But it seems I guess there are further options needed for more precise information.

[latte-dock-20170709-022614.kcrash.txt](https://github.com/psifidotos/Latte-Dock/files/1133465/latte-dock-20170709-022614.kcrash.txt)

So if you could tell me the needed cmake flags/options would really help me and you. ;)

**Comment by psifidotos** [comment]
Isnt manjaro providing debug packages somehow for example from a special repo?

Personally i dont know how this is done otherwise

**Comment by LinusCDE** [comment]
I tried to increase the verbosity using additional compiler options.
Although the package-size increased by ~3MB I didn't got any new line-numbers.
So I guess that I can't trace the bug any further that in the first report.

**Comment by nemonein** [comment]
I'm using Kubuntu 17.04(plasmashell 5.10.3), latte dock(the latest one from the PPA) and I have the same issue.

I would like to help you, and I hope you give me an advice what to do.
Then I'll report back to you. (I'm not a programmer, so I don't have little knowledge about debugging, etc.)

**Comment by psifidotos** [comment]
The crash occurs when starting virtualbox from its launcher in Latte or when you run a specific machine image?

**Comment by nemonein** [comment]
The crash occurs when I start Virtual-Box(launcher/Manager) from latte-dock(it's pinned).
I've got "Segmentation fault (core dumped)".

**Comment by psifidotos** [comment]
I am using KDE Neon but I cant reproduce this yet...

**Comment by nemonein** [comment]
Hm..
The Virtualbox I use is 5.1.24. I downloaded it from the Official VB Web site.(https://www.virtualbox.org/wiki/Linux_Downloads)

**Comment by LinusCDE** [comment]
Yan you try launching VirtualBox trough the Terminal?
I made the experiene that the crash only occurs when started trough a KDE-Laucher.

**Comment by psifidotos** [comment]
I am using **5.0.40_Ubuntu r115130** downloaded from the Neon repos...
it runs always without crashes

I suppose the crash doesnt occur with the plasma taskmanager, is that right?

**Comment by nemonein** [comment]
Run VirtualBox from..
```
Terminal ➙ Not crashes
Krunner(Alt-F2) ➙ Crashes
Latte Dock ➙ Crashes
```
I ran it in terminal by 'virtualbox', on 'VirtualBox'.

However, if run VBox in terminal, sometimes Latte Dock looks crashed.
I mean, after I run VBox, Latte Dock disappears, VBox appears, and Latte Dock appears finally.

But when I run VBox in Krunner or Latte Dock, Latte Dock used to disappears(crashes) as soon as VBox appears.

**Comment by psifidotos** [comment]
I suppose the crash doesnt occur with the plasma taskmanager, is that right? have you tried this with the official plasma panel and taskmanager?

**Comment by nemonein** [comment]
Well, I don't use default plasma launcher.. (taskmanager, if you say so.)
I'll try it later.

**Comment by psifidotos** [comment]
the app launching in Latte>=0.6.87 is done through plasma libtaskmanager library... If it also crashes then this is a plasma upstream bug

**Comment by psifidotos** [comment]
I have opened also a bug report at kde: https://bugs.kde.org/show_bug.cgi?id=382525

**Comment by nemonein** [comment]
I tried, and Latte Dock crashes using Plasma's launcher._

**Comment by psifidotos** [comment]
Ok... Plasma devs have confirmed that this is an upstream bug from plasma litaskmanager... All these crashes occur also for plasma... you can read at:

https://bugs.kde.org/show_bug.cgi?id=381317
https://bugs.kde.org/show_bug.cgi?id=381006
