### ISSUE TITLE
mouse wheel

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#59]
Suppose you add a folderview in late dock containing a group of applications eg. "Office" with elements such as: [Excel, LibreOffice, kcalc, Spread, ..., ...., ...] ... well, it would be interesting to have the opportunity instead to display the identification symbol of the category "Office", display the icon relative to an element of the category" Office" by simply using the mouse wheel dellla

It would avoid, in so doing, the use of a mouse click, by accessing in this way, directly to the "Office content"

**Comment by psifidotos** [comment]
duplicate for #57 please report this as a feature request for folder view at:

bugs.kde.org
