### ISSUE TITLE
[Feature-request] Provide an option to avoid other panels when filling the length.

### ISSUE THREAD

**Issue by libookami** [psifidotos/Latte-Dock#590]
Hi again. I have an Unity-like setup and while Latte has an option to change the length of the dock if i set the maximum length to 100% it overlaps with my top panel. The alignment of the panel is justified so it centers itself, but if i choose the max length to be 96% then i get an offset on the bottom too.

The feature i'm requesting is the option to fill the length to 100% but to detect if there's another panel and avoid to overlap that panel in a similar way the dock from the old unity7 does. This is a feature not even the default plasma panels have. If you put two default plasma panels in a similar way to unity does and a program changes the resolution to something smaller (imagine for a moment an old wine game that changes the resolution to 800x600), the plasma applet will be resized automatically to the new smaller resolution, but when you close the game the panel will not enlarge itself again and will remain tiny.

If would be terrific if latte dock could always enlarge itself to the 100% of the resolution but at the same time detect the other panels and avoid Latte to overlap with them. I don't know how hard it would be in theory but if it can be done i'd be very happy. 

In the following image: 
-The left one is how the dock behaves right now if you set the maximum length to 100%, it overlaps with the other panel.
-The middle one is what i do right now by setting the maximum length to 96% and how it looks.
-The right one is a manipulated image that shows what i want. In this example the alignment is justified and the max length is 100% but the dock avoids to overlap itself with other docks.

![example](https://user-images.githubusercontent.com/29102827/28042019-2ae2daba-6591-11e7-9bf6-5168b62b4fd6.png)

What do you think about the idea?

**Comment by psifidotos** [comment]
This is already supported but you need both the left and the top panels to be Latte docks, it cant be done in a mixed envirinment.

Are your left and top panels both Latte docks?

**Comment by psifidotos** [comment]
I forgot to mention that this is provided from Latte automatically, you dont have to enable it somehow

**Comment by libookami** [comment]
Thanks a lot i didn't knew this was possible with a second Latte panel, it works perfectly. The only detail now is that the folder view doesn't seem to recognize the offset so the panel is over the icons but otherwise it's exactly what i wanted, maybe i can add an offset by modifying the qml file of the folder view. 

![spectacle lh5377](https://user-images.githubusercontent.com/29102827/28088994-1ce6e246-664d-11e7-8708-9d3bcb87a022.png)

I noticed that Latte gives the option to only show background for maximized windows and to hide shadows for maximized windows. It would be possible to add the option to make the panel completely opaque for maximized windows? I use a theme that doesn't have shadows for panels and that gives opaque backgrounds for panels, with this option a person can just use the default breeze theme if they want to blend the titlebar and the top panel like with unity.

Honestly Latte has tons of options i think the default plasma panels should ship by default. Thanks to you, plasma is a lot more attractive desktop now than what it used to be before Latte. Thanks for everything.

**Comment by psifidotos** [comment]
> The only detail now is that the folder view doesn't seem to recognize the offset so the panel is over the icons but otherwise it's exactly what i wanted, maybe i can add an offset by modifying the qml file of the folder view.

Unfortunately it isnt possible to set the plasma desktop geometry from external programs, such as Latte. What you can do is to unlock your plasma desktop and drag any items you want fron the desktop to a better place

> . It would be possible to add the option to make the panel completely opaque for maximized windows? I use a theme that doesn't have shadows for panels and that gives opaque backgrounds for panels, with this option a person can just use the default breeze theme if they want to blend the titlebar and the top panel like with unity

sorry i didnt understand.. Latte provides many options for the panel background in Appearance page, Advanced mode. Such as disable it completely, change its transparency etc...

> Honestly Latte has tons of options i think the default plasma panels should ship by default. Thanks to you, plasma is a lot more attractive desktop now than what it used to be before Latte. Thanks for everything.

Thank you very much...

**Comment by libookami** [comment]
> Unfortunately it isnt possible to set the plasma desktop geometry from external programs, such as Latte. What you can do is to unlock your plasma desktop and drag any items you want fron the desktop to a better place
I set a panel behind latte dock as a workaround, that sets the offset nicely, i hope to not get any problem with that approach, otherwise maybe i'll change the folder view to a desktop view.

>sorry i didnt understand.. Latte provides many options for the panel background in Appearance page, Advanced mode. Such as disable it completely, change its transparency etc...
It's just i changed to the normal breeze theme and when you maximize a windows the background is still transparent. I just had the idea of having a normal semi transparent panel with shadow when there's no maximized window and because there's an option to hide the shadow for maximized windows i was thinking would be sweet for the panel to become opaque when there's a maximized window the same way the shadow hides only when there's a maximized window. But don't mind me it was just an idea so i was asking out of curiosity.

Unless you want to give Latte the ability to detect and avoid normal plasma panels i think the bug can be closed. Thanks a lot for your help.

**Comment by libookami** [comment]
Hi, i'm not completely sure if you receive a notification for this message because the issue is closed but i didn't want to create a new bug just for this question,. The question is: does latte implements any kind of mechanism to recover in case of crashing? if the answer is no then, it would be a fair feature to request and to open a bug for?

Allow me to explain: Now that i use Latte and my only kind of panel (except for the small one for the workaround for the folder view), sometimes a plasmoid can crash and take down the whole panel with it. This used to happen sometimes with the regular plasma's panels but in case of crashing they was able to restart themselves. With Latte a few times has happened the same but it doesn't recovers itself. Fortunately is easy to open krunner and launch Latte again.

I searched a bit on google and found this:
https://stackoverflow.com/questions/696839/how-do-i-write-a-bash-script-to-restart-a-process-if-it-dies/697064#697064

So i created this small script and indeed, Latte restarts itself unless Latte ends gracefully: 
`#!/bin/bash

until latte-dock; do
    echo "'latte-dock' crashed with exit code $?.  Respawning.." >&2
    sleep 1
done
`
I tested this sending the signal SIGSEGV to latte.

What do you think? it would be a good idea to open a bug to request giving Latte the ability to try to restart itself in case of crashing?

**Comment by psifidotos** [comment]
Latte doesnt provide such mechanism yet. Please open a new issue to keep track of the conversation. The last time someone requested this feature we refused because we wanted the users to report the crashes in order to make Latte more mature. The thing is of course that almost all of the crashes arent Latte fault.  I think a discussion about how this could be implemented properly and the user should be able to enable/disable it... e.g. we could have a development mode that we would disable it...

**Comment by libookami** [comment]
Thanks a lot, i'm happy to hear you want to eventually implement this. As you say, indeed, most crashes are not Latte's fault, this also happens with the panels from plasmashell, if a plasmoid crashes it takes down the whole shell. I'm gonna open the bug to keep the record on what can be done when this kind of thing happens.
