### ISSUE TITLE
[Latte 0.6]-duplicate task? triplicate....

### ISSUE THREAD

**Issue by PRafael** [psifidotos/Latte-Dock#593]
As you can see on the attached image there are 3 icons for the actual open program.
I don't know if this happened after an upgrade or if it is something wrong with my configuration.
Can you please advise...

Linux Mint 18.1; KDE Plasma 5.8.7; KDE Frameworks 5.36.0; Qt 5.6.1; kernel 4.4.0-83 generic 64 bits

Regards
Paulo
![screenshot_20170716_134233](https://user-images.githubusercontent.com/3193517/28249480-0279b3aa-6a2d-11e7-93cd-4302f3687519.png)

**Comment by psifidotos** [comment]
do you have open only one firefox an spectacle?
what latte version are you using?
can this be reproduced with the icon-only taskmanager?
if you close Latte and start it again you have the same issue?

**Comment by PRafael** [comment]
Sorry for the late reply
1. yes, one one aplication open
2. 0.6.2
3. attached you will see a picture of the task bar...and it's normal
4. same issue 
![task bar - normal](https://user-images.githubusercontent.com/3193517/28739761-2da800ee-73d4-11e7-929c-08908fefa4eb.png)
![screenshot_20170728_204745](https://user-images.githubusercontent.com/3193517/28739990-356f204e-73d6-11e7-858a-3dc29860c170.png)

**Comment by psifidotos** [comment]
The version of 5.36 frameworks with plasma 5.8 is it correct? I think this isnt allowed, is that the official mint kde proposal?

or,

plasma 5.8.7 introduced something new, had you used Latte with prior versions such as 5.8.5, 5.8.6?

**Comment by rikmills** [comment]
Not able to replicate here on Mint 18.2 at the moment.

![8bd742b4d3](https://user-images.githubusercontent.com/25360459/28747003-3f4a5338-748d-11e7-9c00-55782d3c4b3d.png)

**Comment by psifidotos** [comment]
@rikmills are you using plasma 5.8.7 ?

**Comment by rikmills** [comment]
@psifidotos Yes, as that is the current version in all Mint 18.x KDE.

**Comment by psifidotos** [comment]
I havent seen such behavior never in my system... either way 0.6 has some inconsistencies with plasma libtaskmanager. 0.7 fixes all these as is totally based on plasma libtaskmanager and provides same experience with plasma taskmanagers...

**Comment by psifidotos** [comment]
I think we can close this for upcoming 0.7 version...
