### ISSUE TITLE
Odd behavior vivaldi icon

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#594]
Odd behavior vivaldi icon:
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1151262/video.zip)

**Comment by psifidotos** [comment]
@audoban do you have any ideas for this?

**Comment by JenaPlinsky** [comment]
@psifidotos 
After restarting kde everything returns to work as expected
sorry
...
the problem was occurred after a "zypper up"
probably there was an update of the breeze theme or vivaldi

**Comment by psifidotos** [comment]
dont worry... you can close this issue then...

2017-07-17 20:13 GMT+03:00 Ivan Bordoni <notifications@github.com>:
