### ISSUE TITLE
A manual?

### ISSUE THREAD

**Issue by kirbyfan64** [psifidotos/Latte-Dock#598]
It'd be nice if there were an actual manual for Latte dock, containing stuff like:

- The basics of using Latte.
- How to enter editing mode (I've been trying to figure this out for like an hour).
- Troubleshooting (some FAQ entries could probably be moved here).
- etc.

**Comment by psifidotos** [comment]
we have this: https://github.com/psifidotos/Latte-Dock/wiki which is updated completely by the community

isnt doing the job?
