### ISSUE TITLE
Latte can't tell the difference between Android Studio Stable & Canary

### ISSUE THREAD

**Issue by aidengindin** [psifidotos/Latte-Dock#599]
I have both the stable & canary versions of Android Studio installed on my computer, with two different .desktop files. However when both are open Latte thinks they're two windows of the same application, and when I pin either version to the dock it always opens the canary version.

**Comment by psifidotos** [comment]
Latte version?

**Comment by psifidotos** [comment]
I suppose you have the same problem with plasma taskmanager. We use the same library. File a bug at bugs.kde.org if that is the case

**Comment by aidengindin** [comment]
No, the Plasma task manager can tell the two versions apart just fine. I only have this issue with Latte.

**Comment by psifidotos** [comment]
> No, the Plasma task manager can tell the two versions apart just fine. I only have this issue with Latte.

1. did you try the grouping functionality of the plasma icon-only taskmanager? the normal plasma taskmanager doesnt group apps

2. a temporary solution would be: go to Latte settings->Tasks->assign the action "Toggle Task Grouping" and afterwards when these two are grouped together use it to ungroup them
