### ISSUE TITLE
Context menus from plasmoids make the dock to hide...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#6]

**Comment by audoban** [comment]
It does not happen to me.

**Comment by psifidotos** [comment]
steps to reproduce:

1. add in the dock a clock plasmoid
2. set your dock to "Auto Hide"
3. lock your widgets in the dock
4. right click the clock plasmoid to see its settings...

I believe that the panel should not be hidden until the menu was disappearing...

**Comment by audoban** [comment]
Confirmed. Maybe I can avoid this behavior on the visibilitymanager.  But it is not so serious, however it breaks the consistency.

**Comment by psifidotos** [comment]
There is a branch called **menu** that overrided the default ContainmentInterface behavior for right click event... It works, and blocks also the hiding... 

in menu branch I have removed both the "Add Widgets" and "Lock/Unlock widgets" actions, just for testing it...

systray is working ok...

issues:
1. plasmoids that use their own contextmenu instead of plasmoid.actions("...") may not be able to show their menu (I dont know any except our own and the tasks actually)
2. menus from systray do not block the dock's hiding, but this is also problem with the current implementation

personally if no other better way from visibilitymanager exists concerning also the wayland case, we should use our own implementation...


I would like your feedback for this please....
