### ISSUE TITLE
zoom animation

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#60]
I noticed that, with Applets size set to 48 px
and zoom on hover at 50%
the animation is not smooth (only for folderview icons !! ....task icon animation work properly)

while everything runs smoothly if Applets size set to 64 px

**Comment by psifidotos** [comment]
@audoban  take a look in this... I dont think is something we can do, right?

**Comment by audoban** [comment]
It looks like the icon is not completely centered.

**Comment by psifidotos** [comment]
> It looks like the icon is not completely centered.

can we have a screenshot?

**Comment by JenaPlinsky** [comment]
and about the folderview icons, because the problem is only here? the smooth animation scale down to a certain point and then stops and shows the icon to its smallest size

**Comment by psifidotos** [comment]
> and about the folderview icons, because the problem is only here? the smooth animation scale down to a certain point and then stops and shows the icon to its smallest size

this is #58 and it is an upstream plasma issue it is not related to Latte
