### ISSUE TITLE
Memory leak with "Weather widget"

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#600]
![spectacle e20948](https://user-images.githubusercontent.com/24593950/28382694-591f0eb4-6cbf-11e7-95e9-7046abc19e08.png)

![spectacle w20948](https://user-images.githubusercontent.com/24593950/28381991-e23554cc-6cbc-11e7-8602-3c4fd0201e2e.png)

With a configuration with dual monitors I happened a couple of times, to have an high CPU usage load 
- ...I started to deleting a widget at time, starting from the primary monitor 
  ...from here, eliminating the "Weather widget" nothing has changed :) 
- then later followed the same procedure but now on the secondary monitor and finally once the "Weather widget" has been deleted the CPU load has normalized

**Comment by psifidotos** [comment]
I suppose this is a Weather widget issue... no ?

**Comment by JenaPlinsky** [comment]
Yes ... Now, the mentioned condition has just been repeated and I can confirm that the problem is related to the "Weather plasmoid" widget

**Comment by JenaPlinsky** [comment]
But do you think that you have to deal with the dual monitor configuration?
The widget in question has never given any problems with the single monitor

**Comment by psifidotos** [comment]
> But do you think that this could have to deal with the dual monitor configuration?
> The widget in question has never given any problems with the single monitor

If you can replicate this with the plasma panel then this is totally an upstream bug of the widget

**Comment by JenaPlinsky** [comment]
Ok, as soon as it happens, I will investage, thank you very much
