### ISSUE TITLE
Doesn't work with tiling wm

### ISSUE THREAD

**Issue by gspe** [psifidotos/Latte-Dock#601]
Since I get an ultra wide screen (LG 38'') make lot of sense to use tiling windows manager. (Lg has a proprietary app that mimic tailing wm).
I've tried to use Xmonad with Plasma 5 and it works quite well, the one thing that doesn't work is Latte Dock.
When I start Latte it use almost 60% of the cpu all the time, with top I can see the Latte and Xorg are using almost all the cpu together.
Since Latte Dock is my favourite dock it's really a pity that it doesn't work with tiling wm.
I've tried Plank and it work. I've tried i3-wm and also Plank works and Latte doesn't.
So I think that the problem is with Latte not with the tiling wm.
Is there any way I can help top solve this problem? I'm attaching a quick screen shot of Plank and Latte Dock with Xmonad.
I really like Latte Dock and I really would like to use it with tiling wm.

![screenshot_20170719_231442](https://user-images.githubusercontent.com/883731/28389965-7f8e1a0e-6cd8-11e7-8f4a-89624b177e18.png)
![screenshot_20170719_231635](https://user-images.githubusercontent.com/883731/28389966-7f922298-6cd8-11e7-8a6c-458aa623bc48.png)

**Comment by psifidotos** [comment]
can you explain please what doesnt work ?

**Comment by gspe** [comment]
It use 90% CPU all the time
so the system is unusable.

**Comment by psifidotos** [comment]
what happens probably is that the tiling manager is trying to reposition Latte, but Latte has a strict code for its positioning is order to be always at the right place. That could create a continuous loop for repositioning the latte panels...

first thing you should try is to force all latte panels and windows as float windows...

I found this: https://wiki.haskell.org/Xmonad/Using_xmonad_in_KDE

**Comment by psifidotos** [comment]
from xprop I get this in the window class for latte:

WM_CLASS(STRING) = "latte-dock", "lattedock"

**Comment by gspe** [comment]
I've tried and the  result is the same, 100% CPU usage.
Xmonad has this module [XMonad.Hooks.ManageDocks](https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Hooks-ManageDocks.html) that provides tools to automatically manage dock type programs, such as gnome-panel, kicker, dzen, and xmobar.
This module works with Plasma panel and plank but not Latte, I haven't tried other docks yet.

**Comment by psifidotos** [comment]
no more ideas then... for i3 we had fixed an issue in the past with the user, nothing relevant to high cpu usage... and ther

**Comment by psifidotos** [comment]
@audoban did i miss something?

**Comment by snippins** [comment]
I use i3-gaps and have no problem with latte. But certain settings (left or right panel + behave as dock) can break i3. This is i3 limitation. I do have a "hacky" patch for i3 to use latte as a vertical dock though. 

@psifidotos Would I able to use Latte with i3 in the future? I does not have any plan on switching to Wayland for at least 5 more years... I am fully aware that using another WM some settings/features will just can not work, but as long as you keep the "not behave as dock/override redirect" feature available for X, there are multiple workarounds that users of other WMs can make themselves to be able to work with latte.

**Comment by psifidotos** [comment]
@snippins I am using an NVidia laptop which is my main computer for the next 4-5 years so wayland isnt an option for me either... I developed the Latte wayland code in my old computer... I dont believe something radical will change in Latte concerning the X implementation. I dont know of course for kwin and plasma regard.. I dont know if you want to add in our wiki the steps you took in order to make Latte fully workable with i3-gaps... If this is a lot of text I can open a new page in our Wiki called  Tiling WMs
with a sub category for i3-gaps

**Comment by snippins** [comment]
@psifidotos Sure, I love this project and will contribute. However though it is indeed a lot of steps and I am currently super busy, so I will not be able to do anything until 28th next month. But I promise I will go back and write a guide. Thank for your hard work. :)

**Comment by psifidotos** [comment]
no worries... ;) let me know when you want to contribute it...

**Comment by snippins** [comment]
@psifidotos Delaying the date to write the TUT for i3 after 18th Sep since more work came up. :((
