### ISSUE TITLE
Badge on Blender icon is it right ?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#603]
Badge on Blender icon is it right ?

![spectacle n18340](https://user-images.githubusercontent.com/24593950/28488864-6ebb6dde-6eb4-11e7-80b4-10b545555d1c.png)

**Comment by psifidotos** [comment]
go to you volume control icon -> applications

and see if blender is appearing in there when there is this badge

2017-07-22 9:06 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
![spectacle x18766](https://user-images.githubusercontent.com/24593950/28489081-d7dfdb06-6eb9-11e7-984d-49f12c8932e3.png)

Hence, It is a Blender issue I suppose
