### ISSUE TITLE
Unexpected latte closure

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#604]
By adding the default plasma panel, I get an unexpected Latte closure, but it seems, without crash

**Comment by psifidotos** [comment]
I reproduced only in the following situation when Latte has a systray and plasma panel also... Dont ask me why this happens... no idea...

**Comment by psifidotos** [comment]
I reported it at: https://bugs.kde.org/show_bug.cgi?id=382579

I dont know if plasma devs care about it...

**Comment by JenaPlinsky** [comment]
This is going to be a big change
Great ;)
