### ISSUE TITLE
I happen to involuntarily run applications with the mouse wheel

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#605]
Quite often, I happen to involuntarily run applications with the mouse wheel

Is it technically possible to handle, mouse wheel event trigger and make it less sensitive?

Or add a dedicated check box like:
- Activates tasks using the mouse wheel
- Activates launchers using the mouse wheel

**Comment by psifidotos** [comment]
You can deactivate the mouse wheel behavior if you want from the Tasks
page... to make it less sensitive is a bit difficult

2017-07-22 10:28 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
OK thank you very much
