### ISSUE TITLE
Doesn't work Appearance tab.

### ISSUE THREAD

**Issue by nixway** [psifidotos/Latte-Dock#607]
Doesn't work Appearance tab.

[Video](https://youtu.be/5yQsC8ap4Zs)

**OS:** Debian 9, **DE:** KDE 5.8, **Latte Dock** v 0.6.2

**Comment by psifidotos** [comment]
run latte through command: latte-dock or through your app launcher...

2017-07-22 18:35 GMT+03:00 nihi1ist <notifications@github.com>:

**Comment by nixway** [comment]
Thanks, it's works!
