### ISSUE TITLE
How to update to last "master" branch

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#61]
How to update to last "master" branch

**Comment by psifidotos** [comment]
meaning?

**Comment by JenaPlinsky** [comment]
if I want to upgrade to the development version, I have to uninstall and then reinstall or there is an update command that preserves the latte dock's settings

**Comment by psifidotos** [comment]
just run install.sh, the latte dock settings are not lost

**Comment by JenaPlinsky** [comment]
Ah ok. Great ;) !!!
