### ISSUE TITLE
Hint to replicate the configuration of the primary monitor

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#610]
![spectacle yv7246](https://user-images.githubusercontent.com/24593950/28498559-77e39778-6fa0-11e7-9c15-8b781da4e9e1.png)

Is it possible and wise to extend the dock copy feature by adding a "duplicate primary monitor" item or something else? For those who have more docks for activities and a variety of activities, it becomes a rather awkward task

**Comment by psifidotos** [comment]
You mean to copy all docks from primary monitor?

Isnt that just 2-3clicks less from the current behavior?

**Comment by JenaPlinsky** [comment]
Yes, in fact, I did not put so much to adapt the secondary monitor
