### ISSUE TITLE
Grouping layouts on contexctual menu

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#611]
![menu](https://user-images.githubusercontent.com/24593950/28498718-552faef2-6fa4-11e7-9524-c6bbc04a8c47.png)
Once the code for aumatic change based on activity has been implemented, one might think of grouping all these layouts into a single entry and loading the correct layout by associating it with the chosen activity

**Comment by psifidotos** [comment]
You mean to group the layouts that are assigned at an activity?

When the automatic changing is landed then the user can hide these layouts totally from the menu. Latte will take care changing into that layout and Latte will always show you the current layout in your menus even though you might havent enabled it to be shown

**Comment by JenaPlinsky** [comment]
Very nice
