### ISSUE TITLE
Check box not preserved

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#613]
![screenshot](https://user-images.githubusercontent.com/24593950/28499447-92c2ef24-6fb6-11e7-9ea7-8a853ff914a3.png)

Currently, I've disabled this flag "Active the tasks with the mouse wheel" 
but every time I load a new layout, it is reactivated

**Comment by psifidotos** [comment]
This option is under Tasks tab, it is an option per Latte plasmoid and independent from each other
