### ISSUE TITLE
Task indicator

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#614]
I did not understand why but sometimes I find all the applets with its  active indicator
![spectacle r16563](https://user-images.githubusercontent.com/24593950/28501669-ec52f9e2-6fe0-11e7-94b0-248fc2de9eb9.png)

**Comment by psifidotos** [comment]
I dont see it the screenshot... which applets ?

**Comment by JenaPlinsky** [comment]
- I've duplicated a folderview activity
- I've set its background to 100%
- I've set its zoom to zero
- I've scaled the icons to 24-pixel 
- I'm went into a different layout and then came back into this

Following these steps, I get an indicator under each applet
![screenshot](https://user-images.githubusercontent.com/24593950/28502714-b3d9d79e-6ff8-11e7-8f9a-ef6689a314ea.png)

The one green circled has no indicator because I have activated its menu and it is gone away

- then scaling the icons from 24 to 48 everything goes back normal

It would appear that the problem is due to a **rendering failure**
they look like indicators but they are not

**Comment by psifidotos** [comment]
I cant find a way to replicate this...

**Comment by psifidotos** [comment]
does this occur always in your system ?

**Comment by JenaPlinsky** [comment]
Yes ...but only with my old corrupted layouts...
[my_old_config.zip](https://github.com/psifidotos/Latte-Dock/files/1184998/my_old_config.zip)
[My2.0.latterc.txt](https://github.com/psifidotos/Latte-Dock/files/1185007/My2.0.latterc.txt)

...here I tried to replicate it after deleting my old layouts...
[default_config.zip](https://github.com/psifidotos/Latte-Dock/files/1184999/default_config.zip)

**Comment by psifidotos** [comment]
ok... so this was produced only when the layouts were broken from the old copy method?

**Comment by JenaPlinsky** [comment]
I'm almost sure I tried it several times but my hand on fire did not put ahaha;)

**Comment by psifidotos** [comment]
ok... :) the copy method now works beautifully... I checked almost all its parts piece by piece... Coping a dock having a systray in it, doesnt create any problems any problem... that was creating some crashes in the past... and some copied docks in multi screen environments also when we were recreating...

I dont have any such crashes any more... there is also a check when opening the layout manager window informing the user if there are layouts that create such instabilities...

**Comment by JenaPlinsky** [comment]
Very well done !!!!!! ... thanks to this I decided to rebuild my configuration from zero ... and tonight or tomorrow I will pass the missing translations
Thanks for the patience you have @psifidotos

**Comment by psifidotos** [comment]
no worries... :) I am very excited with 0.7 release... :) my plasma system looks so fresh and innovative now... :) my new laptop changes layouts very fast also and it is a reward giving for all this effort to change underlying architecture... :) and I dont get crashes also... :) hehe

**Comment by JenaPlinsky** [comment]
I'm writing a script to retrieve the background of the current plasma activity, and set it as the only background starting from grub, from plymouth, sddm, and splash splash to plasma

This combined with latte creates a much more pleasant environment

**Comment by psifidotos** [comment]
sounds very interesting! let me know how it goes...


2017-07-29 18:28 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
I will share it on github ... for the little I can do, it is complete at 70%

**Comment by JenaPlinsky** [comment]
And here it is with the **brand new** plasma layout 
![dot](https://user-images.githubusercontent.com/24593950/28752434-7eed599e-751f-11e7-9c1d-7d34c27c11d0.png)
