### ISSUE TITLE
Latte dock width

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#62]
![screenshot_20170114_092619](https://cloud.githubusercontent.com/assets/24593950/21953617/925e46f6-da3c-11e6-99c6-d00cb07a012c.png)

 Latte dock wide is not configured, the icons come out, from the screen

**Comment by psifidotos** [comment]
this is not happening in my system....

**Comment by JenaPlinsky** [comment]
it seemed 
I don't know why, but after a latte crash ..I have to re-started latte, and now the icons are shrinked properly
if it re-occurs, I'll give u more details

**Comment by psifidotos** [comment]
ok... :+1: 

if you find what actions created the crash it would be helpful also....

**Comment by JenaPlinsky** [comment]
Siiiii you're right but I missed. Next time I'll be more careful !!!

Guys the configuration form is amazing !!!

**Comment by psifidotos** [comment]
> Guys the configuration form is amazing !!!

thank u....

**Comment by psifidotos** [comment]
duplicate for #66
