### ISSUE TITLE
[upcoming plasma 5.11] - Tooltips name is not visible

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#621]
![spectacle xv2284](https://user-images.githubusercontent.com/24593950/28684219-e4148324-7303-11e7-8958-3c25b2c667e1.png)

**Comment by psifidotos** [comment]
how ?

**Comment by JenaPlinsky** [comment]
I do not know ... I can only see a line

**Comment by psifidotos** [comment]
only with telegram?

2017-07-27 20:50 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
no for all launchers and tasks

**Comment by psifidotos** [comment]
what are your versions ? qt, plasma, frameworks ?

**Comment by JenaPlinsky** [comment]
![spectacle zm3324](https://user-images.githubusercontent.com/24593950/28686982-59c14806-730d-11e7-94f5-683e7243e8af.png)

**Comment by psifidotos** [comment]
I cant know why the libtaskmanager cant return the app name... it will have to wait until i update in my system to 5.11 after September

**Comment by JenaPlinsky** [comment]
no prob ;)

**Comment by psifidotos** [comment]
@JenaPlinsky at window previews can you see correctly the app name ?

**Comment by JenaPlinsky** [comment]
![spectacle ed3324](https://user-images.githubusercontent.com/24593950/28693959-8a4fda2c-7327-11e7-9e11-1be543a7081c.png)

**Comment by psifidotos** [comment]
1. Try the last master branch and confirm problem remains

2. At file containment/contents/ui/main.qml and line 1171 there is line,

height: titleLbl.height

replace with:
height: 20

what happens?

**Comment by psifidotos** [comment]
@JenaPlinsky I may have fixed this... please check again latest master
