### ISSUE TITLE
tooltips name and folderview

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#622]
Is it possible to extend the name tooltips also for the folder-view widgets?

**Comment by psifidotos** [comment]
showing what ?

2017-07-27 20:49 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
![screenshot_20170727_200456](https://user-images.githubusercontent.com/24593950/28685089-03456cb0-7307-11e7-9e6b-0755419d89dc.png)

**Comment by psifidotos** [comment]
difficult...

**Comment by psifidotos** [comment]
ok... I found a way... the option is moved now to Tweaks page as it support applets too...

![image](https://user-images.githubusercontent.com/2216474/28690658-a4d5237a-7322-11e7-85e5-2bf6d5639c08.png)

![image](https://user-images.githubusercontent.com/2216474/28690721-e5ffe100-7322-11e7-9f0d-4159d20c86bc.png)

**Comment by JenaPlinsky** [comment]
Ohhh Yes fixed and very nice !!!
