### ISSUE TITLE
Latte and "run command" 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#627]
Launching Latte by "run command" doesn't get anything
...while from Konsole, everything goes OK

**Comment by psifidotos** [comment]
what is  "run command"

2017-07-29 10:20 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
![spectacle j32697](https://user-images.githubusercontent.com/24593950/28743102-d1acb262-7441-11e7-8efd-f570b46b3fdd.png)
![spectacle x32697](https://user-images.githubusercontent.com/24593950/28743110-021285ee-7442-11e7-879f-5a248e4a06a1.png)

**Comment by psifidotos** [comment]
fixed, it was a broken desktop file
