### ISSUE TITLE
accidental dropped folderviews on the launcher area bring a segmentation fault

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#628]
After resetting Latte to start from zero,
I opened latte with its default layout and in trying to drag my folders categories into a single selection ( grouped folders ), Latte proposes to me as a DropArea, the large launcher area, so without thinking about it, I released it on that area and got a segmentation fault

Now I tried again but did not proposes me (**rightly**) the same drop area 

> --------------------------------------------------------------------------------------------------------------------

I do not remember right now, but the release of the dragged launcher was blocked outside its dedicated area, right?
Has something changed deliberately or has some control mechanism broken?

**Comment by psifidotos** [comment]
folders shouldnt be accepted as launchers in Tasks plasmoid. They should be blocked. Big chance same crash occurs  with plasma taskmanagers. 

Did i understand correctly?

> I do not remember right now, but the release of the dragged launcher was blocked outside its dedicated area, right?

by default yes, you can change this at Tweaks page. But folders shouldnt be considered launchers

**Comment by psifidotos** [comment]
One more thing, what do you mean by grouped folders? You tried to drag folders inside a folderview, correct?

**Comment by JenaPlinsky** [comment]
I mean this
![spectacle id1822](https://user-images.githubusercontent.com/24593950/28743885-5167d5c8-7455-11e7-9b5a-a3143284b6ea.png)


Here is what was happened  !
...the only difference that in this screenshoot I've dragged only one folder 
... but as you can see the launchers area is proposed to me...
![onefolder](https://user-images.githubusercontent.com/24593950/28743897-99c2f3b6-7455-11e7-8439-bd3b4e1f0dd3.png)

**Comment by psifidotos** [comment]
are these simple folders?

**Comment by JenaPlinsky** [comment]
yes

**Comment by JenaPlinsky** [comment]
With regard to this last image the launcher area is only offered once and if I leave and return from the dock area it is no longer proposed but I have to re-verify

**Comment by JenaPlinsky** [comment]
> folders shouldnt be accepted as launchers in Tasks plasmoid. They should be blocked. Big chance same crash occurs with plasma taskmanagers.
> Did i understand correctly?
> 

Yes In fact !! Aware of the fact that the **launcher area had been protected** without thinking twice as soon as I saw the drop zone I released the mouse sx key with the resulting segment fault

**Comment by psifidotos** [comment]
In my system I can not make folders be recognized as launchers, they can be dropped properly over tasks just like regular files...

**Comment by JenaPlinsky** [comment]
I also struggle to reproduce it

**Comment by psifidotos** [comment]
dont bother... either way is very rare someone to try to add a bounch of folders or widgets in the dock...
