### ISSUE TITLE
Corrupted configuration file?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#629]
After several drag-and-drop selection tests with multiple folders, I close and open the latte and I get this strange thing considering that after each test i deleted the added foldeview to return to the starting condition and then repeat the test
![spectacle mn1822](https://user-images.githubusercontent.com/24593950/28743654-64c514a6-744f-11e7-9308-82ae0efe58ef.png)

At each test I did, I dragged all 12 folders
...and I had to give 7 confirmations for the foreground dialog

![spectacle dk1822](https://user-images.githubusercontent.com/24593950/28743857-c6df9efe-7454-11e7-8b67-bbc10f11f7ac.png)

...and then 12 confirmations for the background dialog
![folderview-dialog](https://user-images.githubusercontent.com/24593950/28743939-9c5207ce-7456-11e7-86e3-68038cbda0dd.png)

From what I suppose
I think the changes made to the dock in use are recorded in the My Layout.atte file, right?
...but I noticed that the **default.latte file is altered** and so to restore everything properly I have to
- Switch on a different layout than milk
- remove milk
- apply
- default button
- apply
- switch to milk

[My Layout.layout.latte.txt](https://github.com/psifidotos/Latte-Dock/files/1184862/My.Layout.layout.latte.txt)
[lattedockrc-.txt](https://github.com/psifidotos/Latte-Dock/files/1184868/lattedockrc-.txt)

Sometimes things like this are happening
After restoring the default.latte to the first dragging of 12 folders i get some dupplicate folderview

![spectacle od1822](https://user-images.githubusercontent.com/24593950/28744035-d3810d56-7458-11e7-8ec0-4eb1e1ef87ba.png)

**Comment by psifidotos** [comment]
I dont think we support dropping multiple widgets at the same time... i will check, but the fact that a confirmation pop up is appearing that it isnt in our regard, it is already suspicious

Have you tried with plasma panel to multiple add folders and it worked ok?

**Comment by JenaPlinsky** [comment]
As you can see it is not a latte issue
...it seems the that pop-up confermation accepts more than one click when the system becomes less reactive

**Comment by JenaPlinsky** [comment]
![spectacle hz6201](https://user-images.githubusercontent.com/24593950/28744684-7a8e660e-7466-11e7-95bd-318db06efdf8.png)
