### ISSUE TITLE
freezed screen

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#63]
In my opensuse of tumbleweed, it happens very often that the screen is not rendered ... I do not know if the problem is X11 or some of the plasma configuration file or latte dock    ....to restore the (freezed) parabolic zoom effect I have to disable and then re-enable the check button of the compositor (enables the effects at startup)

I think that this does not happen on Wayland ....but for now, I can not test it since the last update is unstable and it gets me out

**Comment by psifidotos** [comment]
this is totally plasma, report it please to:
bugs.kde.org

probably something with your graphic drivers

**Comment by JenaPlinsky** [comment]
OK thank you very much

**Comment by audoban** [comment]
do you have intel graphics? If you have intel, you can try changing the rendering method, from *SNA* to *UXA*

https://wiki.archlinux.org/index.php/Intel_graphics#Troubleshooting
