### ISSUE TITLE
Overlapped docks

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#635]
Setting up a multimonitor configuration may have two perfectly overlapping docks
Well, I wondered if it was possible to have a check to warn if two docks are the same and superimposed .... i have noticed my overlapping docks by chance

**Comment by psifidotos** [comment]
how did you manage  to make two docks to overlap?

**Comment by JenaPlinsky** [comment]
good question !!!
- I connected the second monitor then I copied the primary dock (set as "on primary" ) on the secondary monitor ( set as "hdmi1" )
I immediately saw a dock for each monitor ...then I do not know how
I found one dock and I assumed they were overlapping

**Comment by JenaPlinsky** [comment]
![spectacle r14027](https://user-images.githubusercontent.com/24593950/28749278-35e4e8c8-74c2-11e7-8da4-23fc53e09f33.png)

**Comment by psifidotos** [comment]
Had you created the second dock by yourself and it was moved by Latte ?

**Comment by JenaPlinsky** [comment]
by "copy the dock"
I've used the same methods either top and bottom docks
The bottom docks were positioned correctly on respective monitors, while the top docks in first instance seem right placed, but after something (i do not remember what) I found the top docks superimposed while the bottom was OK

**Comment by psifidotos** [comment]
try to reproduce it please...

**Comment by JenaPlinsky** [comment]
Once I have carefully configured my main layout, I have copied it and associated it with other activities but I now have overlapped bottom docks (both set as on Primary) ... in the activity change the secondary monitor parameter, It is not preserved

**Comment by psifidotos** [comment]
show me screenshots of your maon layout and the broken behavior

**Comment by JenaPlinsky** [comment]
![dev_layout](https://user-images.githubusercontent.com/24593950/28751131-ebc19212-74ff-11e7-9685-5dbaf3dde8e6.png)
![dev_layout_overlapped](https://user-images.githubusercontent.com/24593950/28751132-f2602188-74ff-11e7-8813-9eb4329a3232.png)

**Comment by psifidotos** [comment]
I tried in my system, still no luck... 

what do we see in the first part and what in the second ?

If for the second part you move one of the bottom docks to the left explicit screen, isnt that change preserved?

**Comment by psifidotos** [comment]
there is a chance that this arent overlapped docks of the same layout but Latte for some reason wasnt able to remove a dock for old layout when switching to new layout.... that could create a crash.... but what is the reason for this...

For the overlapping docks, the second overlapped dock at the bottom wasnt created by you in that layout ? it belongs to the previous layout ?

**Comment by JenaPlinsky** [comment]
Then I checked out some things
Eheeheh here is easy to get lost on the road
- Layout copy works fine
- the copy of the dock on the secondary monitor also works fine

Then what are we talking about? :)

I do not know how I ever found myself with both top and bottom docks superimposed
the fact is that, for the top I had noticed almost immediately, while for the bottom I took a long time

- First thing I have to understand is what I did to get all the docks on the primary output
- Second in the meantime it would be useful a worning otherwise the user does not realize anything

**Comment by psifidotos** [comment]
> First thing I have to understand is what I did to get all the docks on the primary output

play with trying to change primary screen and at the same time disabling one of the two screens

> Second in the meantime it would be useful a worning otherwise the user does not realize anything

This isnt straightforward... there are periods that docks can overlap during screen changes and we cant know when is the final stage after these changes to make the check. This could easily end up in showing very often a warning message that isnt valid

**Comment by psifidotos** [comment]
nasty bug... :( 

I can reproduce it:

1. in multi-screen environment add two bottom docks each one at the bottom edge of separate screens
2. the first dock set it as primary, the second dock set it at explicit at that dock
3. change to a different layout
4. set as primary screen from plasma system settings the screen of the explicit dock
5. change back to the first layout
6. the two bottom docks overlap on the primary screen that when we started it wasnt the primary one

**Comment by JenaPlinsky** [comment]
Woow Great @psifidotos  !!!!!!!!
