### ISSUE TITLE
How to keep, the launcher area, in order

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#637]
I still have no clear task and launcher sorting method or behavior

- My habit is to keep the pinned launchers close to the other, immediately next and close to the separator between many folderviews and launchers area
So, in this way everything seems more orderly

- Now as it is not possible to keep the pinned launchers nearby and I do not know if it can be done in the future

- I also noticed that when the bouncer launcher can swap position with the one close to him

- I have the feeling that the separator positioning, as you use the dock, can be altered ... but I have to investigate better

**Comment by psifidotos** [comment]
> Now as it is not possible to keep the pinned launchers nearby and I do not know if it can be done in the future

The best sorting and one tha plasma could follow possibly is, all activities launchers, explicit activities launchers, tasks

what is happening in your system?

**Comment by psifidotos** [comment]
for the separator you could try instead of using the plasmoid internal one to add the applet separator which can never changer its position. Parabolic effect works just fine

**Comment by psifidotos** [comment]
For the bouncing if you click two nearby launchers too fast, the second moves to the left this is Latte limitation

If it is a single launcher changing position with its neightbour blame the plasma taskmanager

**Comment by psifidotos** [comment]
one more thing... it would be best to set the taskmanagers to filter by screen also in a multiscreen environment... If you dont I also get in my system swaps between neighbour tasks, especially between launcher and launcher with opened window in a different screen

**Comment by JenaPlinsky** [comment]
> what is happening in your system?

I use to keep the launchers alongside
![spectacle mr4125](https://user-images.githubusercontent.com/24593950/28752481-ffe35ec6-7520-11e7-91a4-d1333b5155f1.png)

...but after a while they slit tasks and my order is lost ... but in any case it's just a personal obsession ahahahah i realize
![spectacle if4125](https://user-images.githubusercontent.com/24593950/28752476-e71249e8-7520-11e7-9270-846d8c565af1.png)

**Comment by JenaPlinsky** [comment]
> one more thing... it would be best to set the taskmanagers to filter by screen also in a multiscreen environment... If you dont I also get in my system swaps between neighbour tasks, especially between launcher and launcher with opened window in a different screen

good to know thanks
