### ISSUE TITLE
Kcalc pin setting are not stored on layout files

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#638]
Kcalc pin setting are not stored on layout files

PS. Launcehs group are set as "Layout"

**Comment by psifidotos** [comment]
works perfectly in my system

**Comment by JenaPlinsky** [comment]
each time that I load kcalc pin check box are all empty

**Comment by psifidotos** [comment]
show me

2017-07-30 15:25 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by psifidotos** [comment]
> each time that I load a new layout kcalc pin check box are all empty

of course it is... why do you think it should be otherwise? you said that the launchers goup is Layout, not Global

**Comment by JenaPlinsky** [comment]
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1185687/video.zip)

very strange !!!
To make this clip, I had to disable the secondary monitor...
and I **switched activities a dozen times** without any crashes
Will it be a randomness?

**Comment by JenaPlinsky** [comment]
> of course it is... why do you think it should be otherwise? you said that the launchers goup is Layout, not Global

Sorry I missed the comment

With layout from what I understand 
I synchronize dock launchers within the same layout es. between primary and secondary monitor

But pinned launchers should not be shown in the dedicated acticities ?

**Comment by psifidotos** [comment]
> With layout from what I understand I synchronize dock launchers within the same layout es. between primary and secondary monitor

exactly...

> But pinned launchers should not be shown in the dedicated acticities ?

they will if you assign the same layout to these activities. Otherwise such extent of synchronization is not possible (we can not combine launchers that are global with launchers that are layout specific). What you want can be probably done if you use the Global Launchers Group, I think it would work bettter for you...

**Comment by JenaPlinsky** [comment]
Latte's ways of are really infinite  ..ahahahah

**Comment by psifidotos** [comment]
@JenaPlinsky  :) this is why we provide the basic settings :) the advanced and the new innovative ones need some accustomence and the time will unveil what the users can do with them and if they can create interesting workflows... :) for Group Launchers I think the mid-user could stick with **Unique** and **Global**

**Comment by psifidotos** [comment]
@JenaPlinsky I have just uploaded an improvement for this... In Basic mode the Launchers groups shown is just Unique/Global (which are very explanatory), The Layout option is appearing only in advanced or in Basic also if for some reason the user has enabled it...

**Comment by JenaPlinsky** [comment]
Great
Now i'm using global option and i find it comfortable
