### ISSUE TITLE
I can't add libreoffice-draw.deskot to launchers

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#641]
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1185813/video.zip)

**Comment by psifidotos** [comment]
these are links to desktop files, I dont think this isnt supported also by plasma taskmanager...

**Comment by psifidotos** [comment]
oh... it does... in Latte I can add links of desktop files... Have you tried to add that launcher in a plasma taskmanager? probably something is wrong with that desktop file

**Comment by JenaPlinsky** [comment]
booth plasma taskmanager an latte taskmanager can't accept **dragged** launchers 
...but the latte shown a drop area to accept them "+"

**Comment by JenaPlinsky** [comment]
@psifidotos launcher icons where are placed    
I'd like to change an ugly icon
![spectacle w13451](https://user-images.githubusercontent.com/24593950/28755469-1f5e994c-755c-11e7-9369-84f0e732128f.png)

**Comment by psifidotos** [comment]
Latte accepts dragged launchers even symlinks at my system...

Something in your system is the problem...

Edit desktop files through a plasma menu app launcher
