### ISSUE TITLE
[feature request] - make "Close" item in task context menu to be at the bottom

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#644]
At the moment Latte adds three new items into the context menu of a task, and they are at very bottom. Bottom of the menu is closest to the mouse position therefore items at the bottom are most easy to access and only most important things should go there. Thing is adjusting Latte settings is not something performed often while closing windows is. My muscle memory serves me Latte settings window every time i try to close a task now. Could we please have `Close` menu item at very bottom? It would improve usability a lot.

**Comment by psifidotos** [comment]
I dont know... The design decision was to have the Latte choices at the bottom for consistency... From the three Latte options the **Layouts** can be hidden if from the Layout Manager you disable the Layouts to be shown in the context menu.

I could discuss to move only the close at the bottom of the menu and nothing else... but It would break consistency... @audoban what is your opinion?

**Comment by rokups** [comment]
Consistency with what though? I see inconsistency with just about every other desktop environment including proprietary ones - they all have `Close` menu item at very bottom in the most accessible place. Latte settings there just get in the way.

I think moving just `Close` is perfectly fine. Not sure about others, but i personally rarely use any other options, and when i do it still requires more careful thought and inspection so Latte settings arent a distraction in that case.

**Comment by psifidotos** [comment]
consistency: all the window options to be at the same place

> they all have Close menu item at very bottom in the most accessible place. Latte settings there just get in the way.

so how about the rest of the window options? do we all put them at the bottom? do we split them? The Latte settings, what about them? 

it may be better to propose a full order for the menu items in there... Just proposing moving one without taking into account the rest is not the way...

**Comment by rokups** [comment]
Hmm i noticed that right-clicking empty space gives me menu only with Latte settings. Maybe this could be a potential solution? Not adding Latte menu items to task menus at all and showing them them when right-clicked on empty space or widgets? Latte settings would certainly not interfere if shown in widget context menus and having them here is kind of necessary because hitting empty space is hard if panel is not in justified layout.

**Comment by psifidotos** [comment]
I dont know, for the user would be difficult to understand why in some right clicks the Latte settings appearing and for some they dont, and to remember in the future how to achieve showing them...

Having a shortcut  also is not workable, e.g Meta+RighClick , something like Plank is doing..
So the thing is that these options should appear in the tasks context menu...

Having the Latte options at the top is a bit awkward I think, but I could discuss it...

so the thing is how many users really want that change... If there was a big user base that wants the close button at the very bottom without the rest window actions...

So the thing is, you said that you are not using the Latte options very often in contrast with the Close button... but there are users out there that happens exactly the opposite, like me.... I prefer closing my windows through their titlebar, I dont use that often the Close Window button in contrast with the Latte options that is use them daily...

**Comment by psifidotos** [comment]
@rokups do you have consider to assign a shortcut from the Tasks options to close the window ?

e.g. Ctrl+RightClick ?

**Comment by rokups** [comment]
I do not really believe having settings absent from task context menus would be confusing. All it takes to figure it out is to fiddle with any of the widgets.

Putting Latte settings at the top would interfere with custom items provided by applications like firefox or spotify.

> @rokups do you have consider to assign a shortcut from the Tasks options to close the window ?

I am using plasma specifically because it does not dictate what my workflow should be. Latte getting in the way of usual workflow and forcing things on to users is not a good thing..

**Comment by psifidotos** [comment]
> I do not really believe having settings absent from task context menus would be confusing. All it takes to figure it out is to fiddle with any of the widgets.

so if the user doesnt have any widgets at all and uses only the Latte plasmoid, he wont be able to access Latte settings at all...

> I am using plasma specifically because it does not dictate what my workflow should be. Latte getting in the way of usual workflow and forcing things on to users is not a good thing..

feel free to continue using whatever suits you better... In life you give something and you get something... It is always a question what suits you better in giving and getting...

**Comment by rokups** [comment]
> so if the user doesnt have any widgets at all and uses only the Latte plasmoid, he wont be able to access Latte settings at all...

Right-clicking empty space already gives these settings. Even in highly unlikely scenario of dock being completely empty:

![empty](https://user-images.githubusercontent.com/19151258/28816844-ccf7e6f0-7695-11e7-9556-e54887c0c009.png)

> feel free to continue using whatever suits you better... In life you give something and you get something... It is always a question what suits you better in giving and getting...

I am trying to discuss a usability problem with you. This is met with unexplainable resistance that is not based on any solid arguments. On top of that this last comment is very unprofessional. If you are not interested in solving these problems and improving Latte i would appreciate if you let me know so i can stop trying to present convincing arguments why requested change is a good idea and save time for us both.

**Comment by psifidotos** [comment]
ok, lets save time then
