### ISSUE TITLE
Background size control does nothing

### ISSUE THREAD

**Issue by Adaenn** [psifidotos/Latte-Dock#645]
I'm having issues with my kubuntu 17.04 and latte-dock, mainly that the background size control does absolutely nothing, it is always 100% and the debug info shows nothing, probably is a missing dependency

**Comment by psifidotos** [comment]
screenshot,
is your desktop effects enabled?

**Comment by Adaenn** [comment]
I haven't mess with the default setting of the desktop effects, i try to set it to default anyway just in case

![screenshot_20170801_135908](https://user-images.githubusercontent.com/30626255/28842124-1185335a-76c2-11e7-867e-919a4a71f1ed.png)

**Comment by psifidotos** [comment]
ok I confirm that your desktop effect (compisiting or 2D effects are disabled in kwin). You can check this out at:

plasma systemsettings -> Screen -> Render

the effects for transparency, window shadows shouldnt be shown in your system... You have to reenable it from the below window...

![image](https://user-images.githubusercontent.com/2216474/28842338-ef2d91c8-7705-11e7-9263-b08f5afea638.png)
