### ISSUE TITLE
Launch latte dock before other autostart applications in a plasma session (if possible)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#646]
Is it possible to launch latte dock before other autostart applications in a plasma session?

I guess it's not possible to define an order, is it? It would be visually nice to have plasma, latte-dock and then the rest of applications launched in this order...

Also asking because I'm currently using kwin-quarter-tiling (https://github.com/Jazqa/kwin-quarter-tiling) and kontact launches before latte dock in my system, so its position is not set correctly. I need to manually reorganize the windows with a keyboard shortcut. Not a big deal, but still...

**Comment by psifidotos** [comment]
no idea...

**Comment by psifidotos** [comment]
I suppose you can delay the autostart of other apps like someone did for Latte : http://www.mulley.co.uk/2017/05/delay-startup-of-latte-dock-in-kde.html

**Comment by kupiqu** [comment]
Yes, that hack works, thank you!
