### ISSUE TITLE
Tooltip description with example

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#649]
I personally find the description of some tooltips a bit poor or unclear
Can you help me to improve it with an example?

Unique
- Use a unique set of launchers for this dock
<i> Eg: Uses a configuration like this if you want to keep the launchers, between primary and secondary monitors, un-synchronized</i>     ...**Is this right?**

Layout
- Use the current layout set of launchers for this dock
<i> Eg: Uses a configuration like this if you want to synchronize dock launchers, between primary and secondary monitors, within the same layout</i>     ...**Is this right?**

Global
- Use the global set of launchers for this dock
<i> Eg: In a configuration with different dock layouts coupled with dedicated activities, it allows to keep synchronized launchers, between primary and secondary monitors and keeping, at the same time, separate launchers for activities</i>     ...**Is this right?**

**Comment by JenaPlinsky** [comment]
Do you have any suggestions or changes to offer me?

**Comment by psifidotos** [comment]
> Can you help me to improve it with an example?

What do you mean? Translations shouldnt  be that far from original text... Changing the original text while we are in beta is not allowed....

**Comment by JenaPlinsky** [comment]
ok no problem
