### ISSUE TITLE
Adding an unwanted dock while copying

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#650]
After copying the primary monitor dock to the secondary
I found a third unwanted dock on the left side of the primary monitor

I'm pretty sure of what I've seen even though I still have some suspect:
- I would not have clicked on something I do not remember
- I do not want that the dock in question to be there before

Can a third dock be added?

**Comment by psifidotos** [comment]
> Can a third dock be added?

No idea... you need a way to reproduce this...

**Comment by JenaPlinsky** [comment]
Unfortunately, I can not

**Comment by psifidotos** [comment]
> Can a third dock be added?

as long as the user clicks Copy after the first copy, then the third and fourth copied docks will be added in the primary screen as long that edge is occupied in all screens

**Comment by JenaPlinsky** [comment]
This will certainly be the case
I probably missed a click without knowing it
