### ISSUE TITLE
tooltips and html tags

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#651]
But in tooltip html tags are allowed, right?
am I doing something wrong ?
![screenshot](https://user-images.githubusercontent.com/24593950/28997227-b8ed4f4c-7a0f-11e7-894a-7cf24e88a422.png)

**Comment by psifidotos** [comment]
I dont think they are allowed, to change line we use the character, \n

**Comment by JenaPlinsky** [comment]
I used those tags because they are in the reference label
Do you visualize it correctly?

**Comment by psifidotos** [comment]
no they dont... this needs fixing...

**Comment by psifidotos** [comment]
ok... fixed in master...
