### ISSUE TITLE
move applications to the primary monitor

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#656]
Is there a way to move open applications from the secondary monitor to the primary one by working on the primary monitor dock?

**Comment by psifidotos** [comment]
if you mean to be able to change the screen they are attached no it isnt possible and plasma libtaskmanager doesnt support it yet

**Comment by omni6** [comment]
if i get you right, you have two possibilities:

![unbenannt](https://user-images.githubusercontent.com/24492439/34006514-edaa394c-e0fe-11e7-9dba-71cf631d0f1d.png)
If you click on _move_ the mouse will jump to the titlebar of the chosen application. just click and pull to current monitor.

![unbenannt1](https://user-images.githubusercontent.com/24492439/34006515-ef9b5d9e-e0fe-11e7-8437-1a210acfbd99.png)
Just drag & drop to the screen you want to have it.

**Comment by JenaPlinsky** [comment]
Hi @omni6 

![screenshot_20171215_183711](https://user-images.githubusercontent.com/24593950/34062728-73e00600-e1ee-11e7-8106-761651d18e9d.png)
![screenshot_20171215_051721](https://user-images.githubusercontent.com/24593950/34062723-71dd4926-e1ee-11e7-9c36-33817eefebb9.png)
- I would like to find a convenient solution to bring back to the display of my laptop (primary output), an application placed on my 55-inch TV
I often turn off the TV and can no longer access that application

   > If you click on move the mouse will jump to the title bar of the chosen application. just click and pull to current monitor.

   but this is the same thing as dragging a window with the mouse, right?
the problem is that I can not see the application window
maybe, did you mean this?
  ... unfortunately, this is not right for me since I do not have access to that window
![screenshot_20171215_051515](https://user-images.githubusercontent.com/24593950/34062720-6e780d98-e1ee-11e7-82e9-82794b53be87.png)

> Just drag & drop to the screen you want to have it.

Well, honestly, I had not thought about it before, but this Plasmoid works very well, maybe even docked in a panel
I do not know if technically it is possible to do it, but it would be very convenient to call that application by simply clicking on its thumbnail
  ...if the application was minimized with a click it would be restored and with a second click it would then be moved to the active display
while if the application or window is already active a click would be enough to retrieve it
![screenshot_20171215_051635](https://user-images.githubusercontent.com/24593950/34064070-a6d035a0-e1f6-11e7-9121-ea94596211b6.png)

**Comment by omni6** [comment]
```
but this is the same thing as dragging a window with the mouse, right?
the problem is that I can not see the application window
maybe, did you mean this?
```

right click on desired latte dock's app` More actions --> Move`
**you have not to see anything**, the mouse cursor will jump to the right position, the only thing you have to do is hold left mouse and pull to your laptop's monitor.

**Comment by JenaPlinsky** [comment]
@omni6 
> right click on desired latte dock's appMore actions --> Move
> you have not to see anything, the mouse cursor will jump to the right position, the only thing you have to do is hold left mouse and pull to your laptop's monitor.

ok, it works great !!!! I did not expect this
However, I think that it would seem more intuitive if it were possible to act directly on the miniature
