### ISSUE TITLE
huge CPU load when I copy a 50MB file to googledrive and with contagious badges

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#658]
I observe an huge CPU load when I copy a 50MB file to googledrive
..then playing with task abd tweaks options I get also a crash (without the ability to retrieve its backtrace)
...then, on the next reopening of the dock, the badges become contagious
![screenshot_20170806_234756](https://user-images.githubusercontent.com/24593950/29007500-c5b1037c-7b04-11e7-99e6-98893b5e93e5.png)

**Comment by psifidotos** [comment]
Try to repeat exactly the same thing with icon only plasma taskmanager on your desktop, and compare with plasmashell... probably an upstream bug

**Comment by psifidotos** [comment]
Btw 28% is not a huge cpu load

**Comment by psifidotos** [comment]
@JenaPlinsky one more thing, how do you try to copy the file?
with dolphin? do you have a google drive mounted and you copy it through dolphin?

I tried to copy a file to google drive with chrome and I didnt have any issues...

**Comment by JenaPlinsky** [comment]
> @JenaPlinsky one more thing, how do you try to copy the file?
> with dolphin? do you have a google drive mounted and you copy it through dolphin?

Yes

**Comment by JenaPlinsky** [comment]
Have you seen the badges too?

**Comment by JenaPlinsky** [comment]
> Btw 28% is not a huge cpu load
Playing with the options
I also had 50% higher peaks, resulting in crashes

**Comment by psifidotos** [comment]
I had no prob... did you try with plasma and see what happens?  It sounds more as an upstream bug from google drive plugin

**Comment by JenaPlinsky** [comment]
`Try to repeat exactly the same thing with icon only  plasma taskmanager on your desktop, and compare with plasmashell...  probably an upstream bug`

Plasmashell CPU load, stays fixed at 1%

**Comment by psifidotos** [comment]
Does it show a progress badge in plasma? Had you close Latte when you tried?

**Comment by JenaPlinsky** [comment]
> Does it show a progress badge in plasma? 

Yes, it does shown 

> Had you close Latte when you tried?

yes

**Comment by psifidotos** [comment]
the progress in the systray it goes like crazy... so the issue is between gdrive plugin and the systray progress animation...

![image](https://user-images.githubusercontent.com/2216474/29023933-781316d6-7b78-11e7-8e55-cee61d84e269.png)

**Comment by psifidotos** [comment]
rechecked... the same animation craziness is happening when copying a big file in Dolphin in all cases... so this isnt related to gdrive... systray and the progress animation in there...

**Comment by psifidotos** [comment]
reported : https://bugs.kde.org/show_bug.cgi?id=383227

**Comment by JenaPlinsky** [comment]
Amazing diagnosing !!!!
Great !!!!
