### ISSUE TITLE
Icons not shrinks

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#66]
1- I confirm that if I add folderviews, latte-dock, the icons are not shrinked but the panel expands in its width, and the icons come out from the screen

2- Now dock is no running, but I continue to have a latte-dock, on the bottom and another area at the top that if I click on it with the right button it shows ... "latte setting"

3-incredible but I can not uninstall Now-dock panel and plasmoids, from open suse
![screenshot_20170114_133657](https://cloud.githubusercontent.com/assets/24593950/21954982/59fddc8e-da61-11e6-9cdf-edba4927c68b.png)

**Comment by psifidotos** [comment]
> 3-incredible but I can not uninstall Now-dock panel and plasmoids, from open suse

if you installed Now Dock by sh install.sh then you can go to the folder from which you installed them and run:
sh uninstall.sh

to remove the Now Dock Panel, one way to do it is excactly as you would remove a plasma panel. You can follow the exact same steps...

> Now dock is no running, but I continue to have a latte-dock, on the bottom and another area at the top that if I click on it with the right button it shows ... "latte setting"

and if you click latte settings what does it show? If it shows the Latte configuration window you can click the remove button in the latte settings

> 1- I confirm that if I add folderviews, latte-dock, the icons are not shrinked but the panel expands in its width, and the icons come out from the screen

I will try to find out what is going on for this....

**Comment by JenaPlinsky** [comment]
I get the same fantastic setup form, just like on bottom latte
![screenshot_20170114_133657](https://cloud.githubusercontent.com/assets/24593950/21955142/23b4701c-da65-11e6-9cbd-952bd85200d6.png)
-dock

**Comment by JenaPlinsky** [comment]
I get the same fantastic setup form, just like on bottom latte-dock

![screenshot_20170114_142310](https://cloud.githubusercontent.com/assets/24593950/21955149/5f1e8fca-da65-11e6-9281-285e78cc6224.png)

**Comment by psifidotos** [comment]
> I get the same fantastic setup form, just like on bottom latte-dock

as you can see in your screenshot, there is an add and remove button, you can remove this dock instance by clicking remove. Latte Dock supports multiple instances of docks, the user can have various docks around, in your system there two, one on top and one on bottom, remove the one from top...

**Comment by JenaPlinsky** [comment]
the fact is that I had already tried to will remove
.... He tells me that is removed
but in reality Unfortunately it is always in its place

**Comment by psifidotos** [comment]
> .... He tells me that is removed
> but in reality Unfortunately it is always in its place

the plasma codepage needs one minute in order to remove it... If you want to remove it directly when the message appears if you want to undo your removal then just click the close button in this message

**Comment by JenaPlinsky** [comment]
the fact is that I had already tried to will remove
.... He tells me that is removed
but in reality Unfortunately it is always in its place

**Comment by JenaPlinsky** [comment]
no way, second instance latte-dock always remains on the top

**Comment by psifidotos** [comment]
I dont know what is going on on your system, 

you can try to remove at /home/<youruser>/.config

files Latte Dock-appletsrc, LatteDockrc

in order to start from scratch...

if you can reproduce what is going on let us know...

**Comment by JenaPlinsky** [comment]
Hi I deleted these files many times

kactivitymanagerd-pluginsrc
kactivitymanagerdrc
plasma-org.kde.plasma.desktop-appletsrc
Latte Dock-appletsrc
LatteDockrc (Now. I do not see it)

..... and I get:

![screenshot_20170114_211136](https://cloud.githubusercontent.com/assets/24593950/21958019/2fc22086-daa4-11e6-9c79-c1a469895c2b.png)

**Comment by psifidotos** [comment]
- did you remove the above when latte was closed ?
- what plasma version and frameworks are u using?
- for a confirmation, in the above screenshot we see a regular plasma panel at the bottom and a latte on on top of it, in the top of the screenshot we see a very strange line that you are saying it is second empty Latte dock, right?
- did you remove the applets from the second Latte dock?

**Comment by psifidotos** [comment]
I created #latte channel in irc.freenode.net for those that want a faster response of issues and debugging, I 'll try to be there some hours of the day...

**Comment by JenaPlinsky** [comment]
`
for a confirmation, in the above screenshot we see a regular plasma panel at the bottom and a latte on on top of it, in the top of the screenshot we see a very strange line that you are saying it is second empty Latte dock, right?
`

yes it is right and it is a different instance of latte ...if I change its setting, these have no effect on the main latte

` 
what plasma version and frameworks are u using?
`

Plasma 5.8.90
KDE Frameworks 5.30.0
Qt 5.7.1
kernel 4.9.0-1-vanilla
os 64 bit

`
did you remove the applets from the second Latte dock?`
`
Yes i have removed it

`did you remove the above when latte was closed ?`
Bingo !!!
Great you've solved the problem!. Deleting the rc files, after closing Milk, everything works out fine
how exhausting ! ;) 

`I created #latte channel in irc.freenode.net for those that want a faster response of issues and debugging, I 'll try to be there some hours of the day...`
Well done. Just add it

**Comment by psifidotos** [comment]
nice.... :+1:

**Comment by psifidotos** [comment]
@JenaPlinsky I would like a favor!!!

by clicking applets in Latte their pop ups appearing, e.g. the clock applet... These pop ups are they appearing far from the dock ????

**Comment by JenaPlinsky** [comment]
![screenshot_20170114_224832](https://cloud.githubusercontent.com/assets/24593950/21958311/d15d8abe-daab-11e6-8b20-28863c18496d.png)

**Comment by psifidotos** [comment]
@JenaPlinsky and if you lock the clock (in edit mode when you see the configuration window) then its popup how is it shown?

**Comment by JenaPlinsky** [comment]
I do not know if I understand correctly...


widgets unlocked...
![screenshot_20170114_225736](https://cloud.githubusercontent.com/assets/24593950/21958369/331a9200-daad-11e6-8298-2f0289f36872.png)
then ...re-lock widgets
and I get the parabolic effect is freezed
but it could be a problem of my intel driver
![screenshot_20170114_230410](https://cloud.githubusercontent.com/assets/24593950/21958411/d27f6122-daad-11e6-879d-e45d1b9ff689.png)

then I do enable and I disable compositor and everything returns to work properly

**Comment by psifidotos** [comment]
> then ...re-lock widgets
> and I get the parabolic effect is freezed
> but it could be a problem of my intel driver

no it isnt, when an applet is locked then the parabolic effect is not used, I use it for applets that do not work correct with the parabolic effect...  I wanted to see the pop up from a locked clock where is it placed, is placed far from the clock or near to it

**Comment by JenaPlinsky** [comment]
in order to avoid the problem I had ... with the installation script you might think to close the Latte process and then restart it ... it makes sense?

**Comment by psifidotos** [comment]
> in order to avoid the problem I had ... with the installation script you might think to close the Latte process and then restart it ... it makes sense?

the installation script can not update runtime the latte running... After the installation script the Latte must be closed and re opened, this is the default behavior for all programs...

**Comment by JenaPlinsky** [comment]
Then, the popup is always close and accurately over to watch, whether it is positioned on the right side of milk on the left side, I get the same behavior regardless of whether the widgets are locked or not

instead. the location of the form of the watch is the one stored in the last opening form

**Comment by psifidotos** [comment]
@JenaPlinsky can you please make a screenshot for a locked clock and its popup ?
this is related to #7 and I want to see if Frameworks 5.30 fixed it....

**Comment by JenaPlinsky** [comment]
Ummm, the fact is that I can not understand what the locked clock. Could you tell me the steps to get there? I'm so sorry but ...

**Comment by psifidotos** [comment]
1. right click on the dock, latte settings. The blue board is appearing and
the latte settings
2. Go to the clock and you will notice a locker at its top left corner
3. Click that lock in order to lock
4. Click outside the dock to hide settings and blueboard
5. The clock now can not animate but anything else can
6. Click the clock to appear its popup
7. Is this popup near the clock? screenshot for (7)

**Comment by JenaPlinsky** [comment]
Update to framework 5.31.0
...fantastic feature on the lock icon, I would have never arrived ahahahaahahah ... I must say it works very well and the popup is just above the icon, just as well as it should be

**Comment by JenaPlinsky** [comment]
![screenshot_20170115_142212](https://cloud.githubusercontent.com/assets/24593950/21962782/672c0598-db2e-11e6-9241-703dd7ed5165.png)
![screenshot_20170115_142316](https://cloud.githubusercontent.com/assets/24593950/21962783/692b0d30-db2e-11e6-81a6-a9dd00b9fb84.png)
![screenshot_20170115_142353](https://cloud.githubusercontent.com/assets/24593950/21962785/6aa50e54-db2e-11e6-97cf-f94902dd5925.png)

**Comment by psifidotos** [comment]
> ...fantastic feature on the lock icon, I would have never arrived ahahahaahahah ... I must say it works very well and the popup is just above the icon, just as well as it should be

Fantastic news!!!!!

**Comment by psifidotos** [comment]
thank you very much !!!

**Comment by JenaPlinsky** [comment]
I'm sorry to give you this news but the problem still exists !!!!!!

1-I closed latte-dock
2-I launched ./instal.sh to update from last master brunch
and here again the second lattedock on the top of the screen :(

I did a test:
1 - if I click on remove from the top dock setting form
....nothing happens ...that is:
there remains the top dock
and there remains an open bottom dock too
in this case I remain with 2 active dock

2 - if I click on remove from the bottom dock setting form (main)
there remains the top dock
while the bottom dock closes
in this case I remain with only 1 active dock

**Comment by psifidotos** [comment]
let's move this at: https://github.com/psifidotos/Latte-Dock/issues/75
