### ISSUE TITLE
Can't Delete latte plasmoid.

### ISSUE THREAD

**Issue by nemonein** [psifidotos/Latte-Dock#660]
I'm using Kubuntu 17.04, and Latte Dock from the PPA.(the latest one)

I happened to add latte plasmoid on the Latte Dock.
It means there are two latte plasmoid on it.

I want to delete one of them, but there is no close button, which any other normal widgets has.
Is it impossible?

**Comment by psifidotos** [comment]
1. add a second Latte dock
2. remove the second Latte plasmoid for the first dock
3. remove the second Latte dock that you added in step (1)

if that doesnt work you can try to go at the Tweaks page in advance mode, there is a remove Tasks plasmoid option in there

**Comment by nemonein** [comment]
Thanks @psifidotos 

I could delete it at the Tweaks page you mentioned. I've found a menu labeled 'Remove Task', but should it be named as 'Remove Latte plasmoid'?

Anyway, thank you for your great effort.

**Comment by psifidotos** [comment]
makes sense... unfortunately we are in beta so we cant update translation strings now
