### ISSUE TITLE
Deceive the behavior of autohide mode

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#661]
Currently in autohide mode, when the activity changes, the dock disappears and reappears to disappear again

I know already that they are critical mechanisms to handle

I was wondering, is it possible, at this stage, to deceive its behavior in autohide mode?
What I mean is to tell it to behave as **always visible** until the new layout is fully ready and from that point resume its natural autohide behavior

**Comment by psifidotos** [comment]
sorry, not possible
