### ISSUE TITLE
Altered autohide behaviour

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#662]
(perhaps) The last commits would seem to have altered the normal behavior of autohide mode, at least, as far as the bottom dock

**Comment by JenaPlinsky** [comment]
the dock is no longer hiding

**Comment by psifidotos** [comment]
never? when does it occur? do you have a video?

2017-08-09 12:31 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by psifidotos** [comment]
please confirm that this occurs for you when at the Latte settings window you have the sticker enabled in order to not hide when lose focus

**Comment by JenaPlinsky** [comment]
I think it is related to the tasks miniature
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1211307/video.zip)

**Comment by psifidotos** [comment]
I think is fixed now, please check...

**Comment by JenaPlinsky** [comment]
Great fixed !!!
