### ISSUE TITLE
Some pinned launchers are duplicated

### ISSUE THREAD

**Issue by devillemereuil** [psifidotos/Latte-Dock#663]
Some pinned launchers are duplicated at the bottom/right of the task manager when started. This is happening for Chromium, Kmail and Kile. Tested on Tumbleweed with Latte-Dock 0.6.98, though the behaviour is quite ancient (wanted to test a new version before reporting, but this is the case at least since 0.6.1).

I think this bug is coming from libtaskmanager, so, not much to do on the Latte-Dock side. BUT, how Plasma task manager is behaving is that the pinned launchers is temporarily removed while the new launcher appears at the bottom. 

This, at least, allows to overcome the "duplicate" part of the bug, so I thought it might be worthwhile to raise this difference in behaviour to your attention ! ;)

**Comment by psifidotos** [comment]
1. can you show some screenshots to understand?
2. after the initialization part is everything shown correctly?

**Comment by devillemereuil** [comment]
OK, this is super weird. I created a new activity to make a screenshot and when I pinned new elements, it didn't trigger the bug. I went back to my orignal activity, unpinned/pinned all elements. This is not happening anymore... Could it be some legacy bug solved with a new pinning mechanism?

Anyway, this seems to be effectively solved in this version, provided pinning wasn't already done.

This revealed a new bug though: when Kmail is pinned but not activated, the icon is the white blank paper icon. When it's activated (e.g. some window exists), the icon is normal.

**Comment by psifidotos** [comment]
> Could it be some legacy bug solved with a new pinning mechanism?

what happened probably was that the pinned launchers were from 0.6 version,
by using the new version, Latte automatically imported them into the new architecture and the problem remained. By removing them and adding them again they used the new architecture

> This revealed a new bug though: when Kmail is pinned but not activated, the icon is the white blank paper icon. When it's activated (e.g. some window exists), the icon is normal

1. try to remove the kmail launcher and readd it
2. compare with the plasma icon-only taskmanager if it has the same behavior

**Comment by devillemereuil** [comment]
> try to remove the kmail launcher and readd it

Same thing.

> compare with the plasma icon-only taskmanager if it has the same behavior

Yup, same behaviour with the task manager (icon-only or not). Definitely an upstream bug then. I'll report to Plasma.

Cheers!

**Comment by devillemereuil** [comment]
For information, here's the upstream bug:
https://bugs.kde.org/show_bug.cgi?id=383312

**Comment by psifidotos** [comment]
nice...
