### ISSUE TITLE
Scroll wheel behavior

### ISSUE THREAD

**Issue by eversins** [psifidotos/Latte-Dock#666]
Hello, great work with the update!

I have two suggestions.
1. Don't open applications if you hover over a Icon and use the scroll wheel, we can already press left or middle mouse button to open. Like this it will cause more headaches because of accidentally opening application.

2. Don't minimize a window if only one instance is open and you use scroll wheel while hovering. The scroll wheel is just too sensitive for this action, you windows will just mini/max a few times per second.
In my opinion it would be better if scroll wheel always meant scroll through instances or show me the open one.

**Comment by psifidotos** [comment]
personally I am not quite fond of these proposals. The desing decision is that Latte should act predictable:

1. The user uses the mouse wheel on a launcher and nothing happens, why? the predictable way is to just launch the app
2. A heavy user of mouse wheel I believe would expect such behavior but I may be wrong...

I will expect to see what other scroll wheel users think... 

hint: the scroll wheel behavior can be blocked totally through Tasks settings

**Comment by eversins** [comment]
I am a heavy scroll wheel user, the update is the reason I switched from a different dock. For me the expected behavior is like I described, it is also like this on different docks.

Maybe make it an option in the config file?

1. Is already a problem since most people use the dock as auto hide, when you wan't to scroll on a website but accidentally move the mouse pointer a bit to low, the dock will show and you will accidentally open apps. Or another example would be if you scroll through active windows but move you pointer a little to the side.
Imho accidental program opening should be avoided with the default settings.

2. I can only say that it is the way I described on other docks, it just looks weird and takes a bit longer to get the window to show if you scroll one time to much. But that is noch such a big problem.

**Comment by psifidotos** [comment]
> Is already a problem since most people use the dock as auto hide, when you wan't to scroll on a website but accidentally move the mouse pointer a bit to low, the dock will show and you will accidentally open apps. 

this can be improved... blocking mouse wheel when the dock is hidden

> Or another example would be if you scroll through active windows but move you pointer a little to the side.

can you provide a video to understand? are you refering to touchpad behavior ?

for (2). Blocking the mouse wheel action for minimize and launching a launcher when the scroll wheel is to the bottom direction might be a good idea...

**Comment by psifidotos** [comment]
this is the new behavior that you can test and actually it makes more sense now that the previous implementation:

--when the dock is hidden or in animation no mouse
    wheel actions are accepted
--laucher: only the up action is accepted in order to
    activate that launcher
--window: up action shows the window, if it is shown
    nothing happens,
    down actions, minimizes the window, it is is already
    minimized nothing happens
--group: up/down to cycle through the windows

**Comment by JenaPlinsky** [comment]
No loop cyclic hide show is allowed
[wheel up.zip](https://github.com/psifidotos/Latte-Dock/files/1219977/wheel.up.zip)


Loop cyclic hide show
[wheel down.zip](https://github.com/psifidotos/Latte-Dock/files/1219976/wheel.down.zip)

**Comment by psifidotos** [comment]
I didnt understand... wheel down minimizes a single window, wheel up shows an unminimized window, this is the new behavior

**Comment by JenaPlinsky** [comment]
There are circumstances where when I wheel up the application gets maximized and the bouncing animation is repeated several times

PS. There are mous es. Like mine, where the mouse wheel rotates almost "infinitely", while other mouse where the wheel rotates and when it releases the finger stops
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219995/video.zip)

**Comment by psifidotos** [comment]
> There are circumstances where when I wheel up the application gets maximized and the bouncing animation is repeated several times

In the video what time do we observe  that?


> PS. There are mous es. Like mine, where the mouse wheel rotates almost "infinitely", while other mouse where the wheel rotates and when it releases the finger stops

So what should happen for these mouses?

**Comment by JenaPlinsky** [comment]
> I didnt understand... wheel down minimizes a single window, wheel up shows an unminimized window, this is the new behavior

If the task is only one
On the wheel down the application should be minimized
But if the wheel continues to turn, now as it is, cyclically returns to show and hide the app until the wheel stops

Can be comfortable on goruped tasks but on single task it is annoying "personal opinion"

**Comment by psifidotos** [comment]
> But if the wheel continues to turn, now as it is, cyclically returns to show and hide the app until the wheel stops

Are you using latest master because the new way should allow that... in my hardware scrolling down only minimizes never shows in single windows

**Comment by JenaPlinsky** [comment]
> In the video what time do we observe that?

The frame rate of the video does not look good
But the bouncing animation appears completely altered as if it was interrupted and repeated several times. Occurs every time I launch an app with the mouse wheel, let it run freely

**Comment by JenaPlinsky** [comment]
> Are you using latest master because the new way shouldnt allow that... in my hardware scrolling down only minimizes never shows in single windows

Yes commit 1371

**Comment by psifidotos** [comment]
@JenaPlinsky please check branch **fix666** , i tried to protect these events in order to not double triggered etc...

**Comment by JenaPlinsky** [comment]
> So what should happen for these mouses?

My mouse has a selector that changes the wheel's behavior
- continuous (when I release my finger, it turns free for 10 seconds ahahaah would be effective to produce energy as eolic-shovel)

In this case **it is all more sensitive**
And if there are some horizontal shifts due to launch bouncing it could accidentally take action on wrong launchers, at least this often happened weeks ago, then as you suggested, I disabled this option, and now I'm testing the new behavior

- step (just a few steps and when I release my finger it stops)

**Comment by psifidotos** [comment]
what mouse is this? :) do you have a link for the product? just from curiosity...

**Comment by JenaPlinsky** [comment]
It costs one eye of the head but so I use just one mouse for both my new android tv and my laptop
radio + multi bluetooth selector to couple wiith three different devices
http://www.logitech.com/en-us/product/m720-triathlon

**Comment by JenaPlinsky** [comment]
> @JenaPlinsky please check branch fix666 , i tried to protect these events in order to not double triggered etc...

- Bouncing animation seems now ok

- Wheel up can launch the application but if minimized it does not maximize it

- Wheel down dont work

- Cycling through grouped tasks with the wheel is not admitted

**Comment by JenaPlinsky** [comment]
Just now in these tests, wheeling on the calculator launcher, has accidentally opened me telegram due to an horizontal icon shift

**Comment by psifidotos** [comment]
> Just now in these tests, wheeling on the calculator launcher, has accidentally opened me telegram due to an horizontal icon shift

You can blame libtaskmanager for icon swifts

**Comment by JenaPlinsky** [comment]
The blame is not on the latte side, I know

**Comment by psifidotos** [comment]
> Cycling through grouped tasks with the wheel is not admitted

what do you mean ?

**Comment by JenaPlinsky** [comment]
I can not use, the mouse wheel to move between the tasks of the same group

**Comment by psifidotos** [comment]
@JenaPlinsky ok I updated the fixes... tell me problems that remain in your system

**Comment by JenaPlinsky** [comment]
I do not understand anything more :(
Grouped tasks
- firefox tasks works fine
- dolphin tasks dont cycle at all

**Comment by psifidotos** [comment]
only the grouped tasks now have problem?

I uploaded more fixes in case it catches the group tasks issues in your system

**Comment by JenaPlinsky** [comment]
I'm just compiling

**Comment by JenaPlinsky** [comment]
Now
- cycling through groups works well
- wheel up can open the application but can not maximize the minimized application
- while down can only minimize it for the first time

**Comment by psifidotos** [comment]
Is this when your mouse works in a normal state?

**Comment by psifidotos** [comment]
@JenaPlinsky so what is the difference with the current behavior? 
this changed for single tasks for reasons described earlier...
I agree and it makes sense, for single tasks to track the direction of wheel movement, down to minimize, up to show

> wheel up can open the application but can not maximize the minimized application, while down can only minimize it for the first time

I dont get this in my system

**Comment by psifidotos** [comment]
Of course it doesnt work in your system ... :)
- because the isMinimized state doesnt work in your system (you have enabled window previews for all windows, how many timer we have to fall into this... :) )
- the only way for the wheel actions to not double trigerred etc. is for Latte to identify when that action ended, and the actions ends when the isMinimized becomes true, something that cant happen in your system...

**Comment by psifidotos** [comment]
@JenaPlinsky ok, check again please.. 

@eversins what is your thought for single windows? Is it better to be the wheel action to be a toggler for minimized/unminimized independent of the direction of the wheel
**or** wheel up shows the window, wheel down minimizes the window?

**Comment by JenaPlinsky** [comment]
> because the isMinimized state doesnt work in your system (you have enabled window previews for all windows, how many timer we have to fall into this... :) )

Sorry but where I can find that option in kde ?

**Comment by JenaPlinsky** [comment]
@psifidotos I think it's perfect now !!! Great

**Comment by psifidotos** [comment]
> Sorry but where I can find that option in kde ?

no worries, I uploaded an approach that uses a timer to handle the case so now it should work ok even at your system.
this option is found at: plasma system settings -> Monitors -> Compositor -> Preview Windows (you can chosen for all windows - this breaks the isMinimized state under X11)

**Comment by JenaPlinsky** [comment]
Ok thanks

do you like the new approach ?

**Comment by psifidotos** [comment]
> do you like the new approach ?

small burden, this timer executes only when the wheel is used for single windows so I think it is ok...

**Comment by eversins** [comment]
@psifidotos sorry for not answering the last questions, I was occupied and will go over them in a bit.

To you last question, to be honest I am not a fan of both. So I can't really choose.
We already have the option to just left click to minimize. Imho scroll wheel should always show the applications. In my current work flow I put my mouse cursor over an application and scroll down, this is normally 2-3 scroll/distances, remember the scroll wheel accuracy for each mouse is different! Now I have to be really careful to only scroll once.

Just like with scroll wheel to open applications (instead of just left-click), the question is do we really need 3 ways to do the same thing? If you ask me this just creates confusion and unexpected behavior for casual users. For heavy users it might hinder workflow.

No matter what approach is taken, I would love the option to change the behavior, even if it means editing an exported configuration.

**Comment by JenaPlinsky** [comment]
I'll give you an info
With the free wheel mode on my mouse ....

Sometimes while the wheel rotates in the same direction I get a minimized / maximized toggle .... but we should not let ourselves be deceived by this thing
I think it's a logitech mouse issue
I say this because I observe scroll reversals even when I browse a web page ... and I had the same problem always with a logitech mouse that I used time ago
and I observe the same behaviour on my Android TV

**Comment by eversins** [comment]
I have a Steelseries, a normal small scroll is just 2-3 clicks for me.

**Comment by psifidotos** [comment]
> In my current work flow I put my mouse cursor over an application and scroll down, this is normally 2-3 scroll/distances, remember the scroll wheel accuracy for each mouse is different! Now I have to be really careful to only scroll once.

I really dont understand what you are descibing, please test the new behavior from master if you can build Latte. I suppose you are proposing to not minimize a window ever through scroll wheel but I havent understand yet how that behavior breaks your workflow (a real example would help). What I can understand is the following: 
1. you have your browser maximized and the dock is hidden
2. you scroll at a webpage and at some point accidentaly you touch the screen edge with your mouse
3. because you were scrolling down that means that if there was a window there in the it would be minimized (did I understand correctly?)

> I have a Steelseries, a normal small scroll is just 2-3 clicks for me.

in the new behavior the mouse wheel doesnt act as a toggler in order for you to need to remember how much scroll is needed to see a window without minimizing. In the the behavior moving up only shows and moving down only hides (that is for single windows). For groupped windows is the normal one, cycling through them. The launcher can only activate a task with wheel up, down isnt doing anything...

**Comment by eversins** [comment]
@psifidotos 
"this is the new behavior"

I think that definitely looks better and more predictable than before!

Not a fan of the minimize though (as I said, unnecessary imho), since scrolling down on multiple windows will "show" me the applications and that is what I will always expect. I think I could get used to it but I could see confusion for casual users.

**Comment by psifidotos** [comment]
If you are using the git version of aur, https://aur.archlinux.org/packages/latte-dock-git/ i suppose in a day it will be ready...

**Comment by eversins** [comment]
I have no clue how to reply properly, there are also no post numbers..
@psifidotos 
For me workflow is as follows:

I have many chrome instances open, I wan't to look through them and use scroll down. **
Now I wan't to scroll through my File Managers but nothing shows up. Only later do I notice that only one instance was open. Making the behavior unexpected in the situation.

** Down because that is the natural way one would scroll through windows, If you tell someone to just scroll almost noone will scroll up, it feels unnatural in comparison.

As I already said, with the new  behavior I might get used to always use scroll up, but if you have to get used to something, it often isn't the best way.

Looking forward to the AUR update.

**Comment by psifidotos** [comment]
> Now I wan't to scroll through my File Managers but nothing shows up. Only later do I notice that only one instance was open. Making the behavior unexpected and inconsistent in this situation.

That's a good point... @JenaPlinsky Do you agree removing minimize from scroll wheel and only show?

**Comment by JenaPlinsky** [comment]
In truth I did not well understand how is the issue
...therefore, I entrust myself to your vision of things :)

In any case, by default, I do not use this option because of the fact that I accidentally launch unwanted apps

**Comment by psifidotos** [comment]
@eversins ok... sroll wheel down on single window shows the window if minimized

**Comment by eversins** [comment]
@psifidotos Did no expect this, thank you so much! Sorry for my confusing way of writing. Really looking forward to the update.

**Comment by psifidotos** [comment]
no idea how AUR works... the next days there will be a bug fix release 0.7.1... I suppose in that case the packages will be updated

**Comment by eversins** [comment]
Then it definitely will be, thank you very much. I'll donate to this great project.

**Comment by eversins** [comment]
I think I have received the newest version (r20).

In my opinion the the scroll down should always show the window, no matter if minimized or stacked behind other windows. For a fact nobody will know if a Windows is minimized or stacked behind other windows, thous adding unexpected behavior.

Otherwise great work, feels a lot better.

**Comment by psifidotos** [comment]
> In my opinion the the scroll down should always show the window, no matter if minimized or stacked behind other windows. 

Isnt doing this in your system? What is happening for minimized or stacked windows?

**Comment by eversins** [comment]
I am on 0.7.0.r20.gd6c40b0-1

Scroll down on minimized single window -> shows window.
Scroll down on maximized but hidden (behind other applications/windows) single window -> nothing happens, window is not shown.

**Comment by psifidotos** [comment]
@eversins ok fixed in master...
