### ISSUE TITLE
Magic lamp animation is broken under certain circumstances

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#669]
The bug only seems to occur when dock has auto hide option set to true. My dock is a bottom dock and 
hides for the active windows. It does not matter whether animations are turned off or on. I also have no scaling activated when hovering launchers.

Steps to reproduce:
1. Open the first window (be sure the dock does not hide while the window is opening!) (does not matter if the application has a launcher) 
2. Maximize the first window
3. Open a second window that has **no launcher** (be sure the dock does not hide while the window is opening!)
4. maximize the second window
5. Now you have the second window maximized directly over the first window that is also maximized
6. **EDIT: wait until panel hides and** close the second window.
7. now the first window has the broken animation when you minimize it

This only happens with magic lamp animation. The normal minimize animation is absolutely fine.

EDIT:
The animation also can break sometimes, when one is opening a window and in the meantime, before the window is displayed, the dock hides

**Comment by psifidotos** [comment]
ok... I think I found it... the commit tries to provide only geometries that work ok with the magic lamp, coordinates always inside the screen borders and widths and height that are never zero...

please try master if you can to tell if it is fixed...

**Comment by marhkb** [comment]
Ok, the bug with the two windows is solved. Thanks. But there is still an issue where animation breaks.

Example how to reproduce:
1. Initially the desktop is shown, with no open windows
2. Now press shortcut for opening krunner
3. Position the mouse cursor somewhere where it won't prevent the dock from autohide
4. In krunner open an application that has no launcher (the application must start maximized)
5. When you minimize the application you can see that the animation is broken

It won't break the animation if you would position the cursor at bottom in order to force the dock to stay visible.
This video shows the issue
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219862/video.zip)

**Comment by psifidotos** [comment]
nice catch...

you can try again

**Comment by marhkb** [comment]
Thanks again. Seems to work now. I let you know if I find a broken magic lamp animation again. :-)
