### ISSUE TITLE
prevent events undesiderate

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#67]
With auto-hide mode to prevent accidental activation of the panel, would make sense, un-hide latte-dock only if the mouse pointer is stationary on the edge of mosue, for n time ?   ... that is what I mean is filter events when the mouse is moving

it woud be only an idea i do not know if it makes sense

**Comment by psifidotos** [comment]
unfortunately, this is why the Show timer exists... increase its value if you want more delay to activate dock's showing

**Comment by psifidotos** [comment]
@audoban  can you confirm that we can close this?

**Comment by JenaPlinsky** [comment]
Ohhhh Yesss ;)
