### ISSUE TITLE
Is not possible to change positions to certain tasks

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#670]
Is not possible to change positions to certain tasks
[tasks.zip](https://github.com/psifidotos/Latte-Dock/files/1219765/tasks.zip)

**Comment by psifidotos** [comment]
yes, this is normal... in order to improve the placement of launchers and tasks Latte now follows the plasma icon-only taskmanager approach, launchers first and window after... windows can not be between launchers...

**Comment by JenaPlinsky** [comment]
I meant delphin and systemsetting. Are you referring to the right ones?

**Comment by psifidotos** [comment]
yes

**Comment by psifidotos** [comment]
dolphin and systemsetting are simple windows they arent launchers

**Comment by psifidotos** [comment]
ah... now I understood... the plasmoid can be dragged all along...
