### ISSUE TITLE
Global Menu

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#673]
If a user wants a layout with a global menu like in an IOS style, is possible enable / disable the specific option in KDE depending on whether the "global menu" plasmoid is present in the latte layout?

[video.zip](https://github.com/psifidotos/Latte-Dock/files/1220950/video.zip)

**Comment by psifidotos** [comment]
No this isnt possible I think... this option is set only through plasma systemsettings
