### ISSUE TITLE
Configuration file corrupted 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#675]
![spectacle j29355](https://user-images.githubusercontent.com/24593950/29354399-bc9b9a34-826d-11e7-9ec6-0a2bdc71f296.png)

Differences between the last saved config file and the current corrupted file [lattedockrc.txt](https://github.com/psifidotos/Latte-Dock/files/1227541/lattedockrc.txt) :
- there was a crash while trying to add the default plasma panel
- I've disabled the top-dock's option "behave as normal dock windows"
- I've disabled the bottom-dock's option "behave as normal dock windows"

Saved one day before: [MyDock (1).latterc.txt](https://github.com/psifidotos/Latte-Dock/files/1227546/MyDock.1.latterc.txt) 

Saved one hour before: [MyDock.latterc.txt](https://github.com/psifidotos/Latte-Dock/files/1227535/MyDock.latterc.txt)

I did, so I tried to import the config file saved one hour before but I always get the usual alert
while importing the file from the previous day all goes back normal

**Comment by psifidotos** [comment]
yeap... the second file is a mess... crashes can do such thing... nice you had backup...

**Comment by JenaPlinsky** [comment]
lattedockrc OK ...because of the crash, it can be corrupted
but for the file exported just one hour before, in theory that, had to be intact ...right ?

**Comment by JenaPlinsky** [comment]
What I mean is that it should not be possible to export a corrupt file

**Comment by JenaPlinsky** [comment]
Now I am with MyDock (1).latterc.txt (the one saved the **previous day**) and it is working perfectly
- then I tried to import the file **saved one hour before** MyDock.latterc.txt and I do not get any kind of warning even if it was a corrupt back-up
- but then exiting and re-entering in the configuration form 
...here is again the warning about the corrupted "Main" layout

**Comment by JenaPlinsky** [comment]
With the automatic restart, what does parameters read ? 
the those taken from a back-up or those in the its rc file under ~/.config folder?

**Comment by psifidotos** [comment]
> the those taken from a back-up or those in the its rc file under ~/.config folder?

in the .config directory... The Main layout is broken... in that file there are two applets with same id, that is 
303... an separator applet and a media controller inside a systray... And yes this adds instability... changing from that Main layout it could create crashes in your system... I cant know how this occured for that layout...

**Comment by JenaPlinsky** [comment]
Just yesterday I added the separator in the top-dock 
... indeed i had added by mistake two of that and then i have eliminated one of that

**Comment by psifidotos** [comment]
when you removed the second separator did you press the X button form the
notification?

2017-08-16 13:36 GMT+03:00 Ivan Bordoni <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
the x from its tool-tip

**Comment by JenaPlinsky** [comment]
Always yesterday I did another thing on the system-tray
...I have hidden two entries ...then I noticed an abnormal behavior while trying to apply such changes:
- with "OK" I got a crash
- while with Apply and then OK the changes have become effective

**Comment by psifidotos** [comment]
a crash without a backtrace or reproduce steps cant point somewhere

**Comment by JenaPlinsky** [comment]
Unfortunately either when I add a plasma panel or when I confirm with "Ok", changes to the system-tray ....kcrash is not opened, so i can not get the backtrace

**Comment by psifidotos** [comment]
in master you can find some new debug messages for this... your Main layouts shows the following:

```
[debug 17:33:03.678678] -    ----   ERROR: BROKEN LAYOUT ----
[debug 17:33:03.678678] - Error: Applets with same id :::  "303"
```

I suppose you dont touch the systray, so the question is why the plasma libraries when you add the separator they use an id that is already present...

**Comment by JenaPlinsky** [comment]
> why it should be otherwise? Latte cant fix a broken layout file...

No
- I imported a configuration file with no defects
- I went out and came back into the configuration form,to see if there were any layout-related warnings
- I then exported the current configuration to two files:
lattedockrc
lattedockrc (backup)

After a few days I got corrupted lattedockrc
At that point I try to import from lattedockrc (backup) (verified as working)
But the warning above mentioned  also appears

**Comment by JenaPlinsky** [comment]
> I suppose you dont touch the systray, so the question is why the plasma libraries when you add the separator they use an id that is already present...

Yep

**Comment by JenaPlinsky** [comment]
For Now, I guess it may not know the latte applet IDs because they are part of different configuration files

**Comment by psifidotos** [comment]
reported it here: https://bugs.kde.org/show_bug.cgi?id=383793

**Comment by psifidotos** [comment]
@JenaPlinsky ok...
I played a bit with your configuration, you can fix your layout easily:

1. you have two screens, the issue is with top dock that has been set always on primary
2. remove the separator from that dock (be sure that this is the one and not the one that has been set on top edge of your secondary screen)
3. confirm the separator removal from the pop up that is shown when you remove it (press the X button of the configuration)
4. re-add the separator the same place that you previously removed it

in my system this fixes your layout...

**Comment by JenaPlinsky** [comment]
@psifidotos 
Ok I followed your suggestions and now, there are no duplicate IDs

**Comment by JenaPlinsky** [comment]
The thing I dont understand is how did even contaminate the backup 
 .... could have been created id dupplicaries after its importing ?

**Comment by psifidotos** [comment]
latte is touching ids only when the copy method is used... in no other case...

if you find a way to reproduce this would be helpful!!!!
