### ISSUE TITLE
"Dodge Active" dock when on the left does not extend when behind full screen app 

### ISSUE THREAD

**Issue by poetimp** [psifidotos/Latte-Dock#676]
I have two docks. One at the bottom and one on the left. When set to "Dodge Active" the one on the bottom works as expected. I mouse down and bump the bottom edge of the screen and it pops up. The same is not true when I hit the left edge of the screen. It stays hidden. 

This is new behavior and I have been seeing it for a few days. I just rebuilt with the latest updates and tested and the problem is still there.

git commit 4c06e5000b733f6da33ee285e9961b49f57fca69

**Comment by psifidotos** [comment]
Disable any touch gestures for the left screen edge

**Comment by poetimp** [comment]
I removed the "Touch" gesture and that did nothing. I turned off the top left corner in the screen edge settings and that caused it to work again. I then turned it back on and it continued to work. This did not use to be an issue.

**Comment by psifidotos** [comment]
a way to reproduce please... not just Latte but plasma is also evolving... things can conflict

**Comment by varlesh** [comment]
I confirm this, on left dock not showing. On right all fine... it's strange. Hot left-up angle disabled

**Comment by poetimp** [comment]
I found when I disabled left edge touch (I don't have a touch screen) and upper left corner mouse that the problem went away. I re-enabled the upper left corner mouse and the problem did not return.

**Comment by varlesh** [comment]
video preview bug:
https://youtu.be/EUckyAxhdoI

**Comment by poetimp** [comment]
As I don't have a touch screen I had never looked here before...

![image](https://user-images.githubusercontent.com/3538244/29743692-b27303cc-8a4b-11e7-87b3-c7aa92badaf4.png)

**Comment by varlesh** [comment]
> I found when I disabled left edge touch (I don't have a touch screen) and upper left corner mouse that the problem went away. I re-enabled the upper left corner mouse and the problem did not return.

Oh , thx need disable Touch Screen and Left Edge. Now all fine :)
