### ISSUE TITLE
Unable to pin Firefox

### ISSUE THREAD

**Issue by mustaqimmalim** [psifidotos/Latte-Dock#677]
For some reason, I am unable to pin Firefox to the dock(no matter the location), and if the Firefox desktop file doesn't have `StartupWMClass=firefox`, then the launched icon will be of a lower quality. This seems related to #341

**Comment by psifidotos** [comment]
What Latte version?

The plasma taskmanager acts differently?

**Comment by mustaqimmalim** [comment]
@psifidotos The version is `0.7.0`, the plasma widget behaves the same.

**Comment by psifidotos** [comment]
>  the taskmanager behaves the same

It is an upstream bug then from plasma libtaskmanager... you can report it at bugs.kde.org
