### ISSUE TITLE
adding a second systray in Latte crashes the dock when there are some specific 3rd apps in it

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#68]
this had been fixed, I dont know which commit reintroduced it....

**Comment by psifidotos** [comment]
by restarting  Latte both systrays are shown correctly... this could be a plasma issue...

**Comment by audoban** [comment]
I can not reproduce the bug.

**Comment by psifidotos** [comment]
The following occurs for me when there are in the systray:

**_cryptHider_** or **_yarock_** launchers

**Comment by audoban** [comment]
I tried with Yarock, but latte didn't crashing. I'll try again with cryptHider
