### ISSUE TITLE
[PyCharm] - different application icon used for launcher and window states

### ISSUE THREAD

**Issue by IevgenSobko** [psifidotos/Latte-Dock#680]
Noticed today strange behavior with PyCharm application launcher in Latte.
When it is not started application icon is somehow distorted and doesn't look like other.
![selection_001](https://user-images.githubusercontent.com/14232100/29498882-5accb128-860d-11e7-97c6-e042a3f49372.png)
But after I start PyCharm application icon changes to beautiful and sharp as expected
![selection_002](https://user-images.githubusercontent.com/14232100/29498883-5acd3e36-860d-11e7-833d-cf7ad6bb0438.png)

**Comment by psifidotos** [comment]
compare the behavior with plasma taskmanager, does the same happen?

**Comment by IevgenSobko** [comment]
seems no
see screenshot below
it is icon only task manager
![desktop 1_003](https://user-images.githubusercontent.com/14232100/29499548-897271fc-861c-11e7-9a78-d6bf5196c6c3.png)

**Comment by psifidotos** [comment]
What icon size does Latte use?

Do you know what icon size the plasma taskmanager use in the above screenshot?

**Comment by psifidotos** [comment]
@levgenSobko ok some info for this to check more...

this is at 82px. in my Neon system the PyCharm community edition

![image](https://user-images.githubusercontent.com/2216474/29516509-42bdb7e6-8679-11e7-9127-4a018a0f0128.png)

icons are provided for Latte through the plasma libtaskmanager. The plasma libtaskmanager uses some heuristics in order to find the correct icon, pixel size and image type... From my experience in order for libtaskmanager to use the svg version always the desktop file for the application must contain the
StartupWMClass record. In my system the relevant desktop file looks like this:

[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community Edition
Icon=/usr/lib/pycharm-community/bin/pycharm.png
Exec="/usr/lib/pycharm-community/bin/pycharm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm-ce

If this is missing the plasma libtaskmanager probably uses the icon provided from X11 which is of low resolution and png or jpg type I cant be sure...

**Comment by psifidotos** [comment]
oh... and one more thing... the pyCharm **doesnt provide an svg file**, it provides a png one of size 128x128px... meaning of course that changing sizes cannot be always accurate and if you go to icon size greater than 128px. then in this case you will have pixelated icons...

**Comment by IevgenSobko** [comment]
But my panel is 64px in size.
Also StartupWMClass=jetbrains-pycharm record  present in desktop file.
It is reproducible on 2 my machines with 0.7.0 version.
I've tried to revert to 0.6.2 or something from AUR and on an older version, all works as expected.
What else should I try to resolve this?

**Comment by psifidotos** [comment]
> What else should I try to resolve this?

try to make the plasma panel greater than 64px. e.g. 80px. and see if it reoccurs

**Comment by psifidotos** [comment]
2. you can also try to pin PyCharm after you open its window. That means remove its launcher, open PyCharm and then add its launcher by the contextmenu through Pin option

**Comment by psifidotos** [comment]
3. where is the PyCharm desktop file and what are its contents?
4. what plasma version are you using? what is your distro?
5. are you using PyCharm community edition or regular?

**Comment by IevgenSobko** [comment]
@psifidotos, already tried all your suggestions.

Below some system info
++++++++++++++++++++++++++++++++++
System:    
Kernel: 4.9.44-1-lts x86_64 (64 bit)
Desktop: KDE Plasma 5.10.4 
Distro: Antergos Linux
++++++++++++++++++++++++++++++++++
Regular PyCharm
++++++++++++++++++++++++++++++++++
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm
Icon=/home/dzirt/IDE/PyCharm-2017.2/bin/pycharm.png
Exec="/home/dzirt/IDE/PyCharm-2017.2/bin/pycharm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm
++++++++++++++++++++++++++++++++++

**Comment by psifidotos** [comment]
- this is a standalone user install where does the desktop file is located?
- isnt Antergos providing a package install ?

**Comment by IevgenSobko** [comment]
- it is system-wide installation /usr/share/applications manually downloaded from jetbrains site
- don't know, just see some antergos/jetbrains-toolbox 2:1.4.2492-1 (development IDE editor jetbrains) in official channels

**Comment by IevgenSobko** [comment]
@psifidotos 
I tried to install from AUR and looks like this fixed problem
![selection_001](https://user-images.githubusercontent.com/14232100/29541528-366039ba-86dd-11e7-9747-d3e2fd7e1e53.png)

**Comment by psifidotos** [comment]
ok ... ;) probably some icons were installed properly in the correct paths...

**Comment by IevgenSobko** [comment]
yeah, I think so
thx for ur patience and thanx for this awesome dock

**Comment by biqqles** [comment]
I had this issue with PyCharm Professional after installing the snap. I didn't fancy the idea of reinstalling from a different source, so looked for a simpler workaround. I discovered that creating a Quicklaunch widget on the desktop or in the dock, adding PyCharm, and then dragging that icon out of the widget and into the dock created a launcher with the proper icon. 

This looks to be something to do with different ways of launching the application - the normal method of adding PyCharm to the dock by pinning an instance that results in a pixelated icon also means that further instances do not have a "Pin" option in their context menus, suggesting Latte or some other component isn't linking them to the launcher correctly. This workaround also solves this problem. 

Hopefully this is helpful for anyone coming across this quirk in the future.

**Comment by NicholasDumpling** [comment]
well, I may figured it out.
as the following pic,
![image](https://user-images.githubusercontent.com/9497630/40078096-3adbd23c-58b6-11e8-801a-cd943ef7c97b.png)

the shortcut in Latte is different from the one on the Desktop,
so if we pull a panel widget into the dock, change the icon from panel, the problem will be resolved.

![image](https://user-images.githubusercontent.com/9497630/40078177-78e6094e-58b6-11e8-82cc-042e1b68291e.png)

**Comment by psifidotos** [comment]
plasma libtaskmanager responsibility so this is upstream
