### ISSUE TITLE
latte-dock v0.7，how can I enable the tooltips?

### ISSUE THREAD

**Issue by Schr0dingerCat** [psifidotos/Latte-Dock#681]
latte-dock v0.7，鼠标指针放到图标上，并没有显示该应用名称

**Comment by psifidotos** [comment]
english please

**Comment by Schr0dingerCat** [comment]
@psifidotos oh, sorry, i am chinese, my english is so bad. 
i use opensuse Tumbleweed(language is Chinese) on my computer.
i install latte-dock v0.7 from opensuse repositories in the README.md.
The mouse pointer is placed on the icon but does not display the name of the application

**Comment by psifidotos** [comment]
You must enable them from Latte Settings (advanced mode) -> Tweaks -> Show Title Tooltips

**Comment by Schr0dingerCat** [comment]
@psifidotos thanks a lot
