### ISSUE TITLE
Default Window Postion?

### ISSUE THREAD

**Issue by nemonein** [psifidotos/Latte-Dock#682]
Hi.
I'm using the latest one from the PPA on Ubuntu 17.04.
I have 3 monitors connected, and I've found something interesting.

If I click anywhere(I mean anywhere. It could be the desktop background or any other opened application's window) on the 1st(or 2nd/3rd) monitor and launch a program at the Latte Dock, the program is opened from the same monitor that I last clicked.

However, if I launch from Krunner(of course I follow the above rule), it seems different. If I click an actual window, a program opens from the monitor I clicked. However, if I click the Background(not actual program window, but the desktop background), a program opens from the former position(not the monitor I clicked but the other monitor).

This behavior is for KDE and GTK3 applications only. Qt and GTK2 applications seem to remember their last position.

```KDE System Settings - Window Management - Window Actions and Behavior - Placement ➙ Smart is set.```

I'm afraid you understand what I meant.

Is it intended feature for Latte Dock?
Or am I misunderstanding something?

One last question. Is it impossible to remember the last position for KDE and GTK3 applications?
I've found out that it's been a long and annoying matter for [KDE(KWin)](https://bugs.kde.org/show_bug.cgi?id=15329), but I want to know that that'll be a solution or workarounds.

Thank you for reading!

**Comment by psifidotos** [comment]
this is not related to Latte but rather kwin and plasma libtaskmanager... Latte should provide you with the same behavior as a plasma taskmanager inside a plasma panel

> Is it intended feature for Latte Dock?

Latte doesnt set the screen the a window will open, this is kwin resposibility

> I've found out that it's been a long and annoying matter for KDE(KWin), but I want to know that that'll be a solution or workarounds.

you should try to communicate this with plasma and kwin devs at bugs.kde.org

> Thank you for reading!

no worries
