### ISSUE TITLE
Event Calendar Widget crashes latte dock

### ISSUE THREAD

**Issue by eversins** [psifidotos/Latte-Dock#683]
I use the mouse wheel on event calandar widget.

`23/08/2017 15:19	systemd-coredump	Process 1317 (latte-dock) of user 1000 dumped core.

Stack trace of thread 1317:
#0  0x00007f25ca55e8c0 raise (libc.so.6)
#1  0x00007f25d03a3227 _ZN6KCrash19defaultCrashHandlerEi (libKF5Crash.so.5)
#2  0x00007f25ca55e940 __restore_rt (libc.so.6)
#3  0x00007f25cdca6a01 _ZNK11QQmlBinding15getPropertyDataEPP16QQmlPropertyDataS1_ (libQt5Qml.so.5)
#4  0x00007f25cdca9cfc n/a (libQt5Qml.so.5)
#5  0x00007f25cdcaa7de n/a (libQt5Qml.so.5)
#6  0x00007f25cdca75a3 _ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE (libQt5Qml.so.5)
#7  0x00007f25cdc7e293 _ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv (libQt5Qml.so.5)
#8  0x00007f25cdc1ccd9 _ZN8QQmlData13signalEmittedEP24QAbstractDeclarativeDataP7QObjectiPPv (libQt5Qml.so.5)
#9  0x00007f25cb12ef9f _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
#10 0x00007f259b2f1d84 n/a (libplasma-volume-declarative.so)
#11 0x00007f259b2e6d11 n/a (libplasma-volume-declarative.so)
#12 0x00007f25c1e42d8c n/a (libpulse.so.0)
#13 0x00007f25beb42ba1 n/a (libpulsecommon-10.0.so)
#14 0x00007f25beb42f2b pa_pdispatch_run (libpulsecommon-10.0.so)
#15 0x00007f25c1e37a6e n/a (libpulse.so.0)
#16 0x00007f25beb45997 n/a (libpulsecommon-10.0.so)
#17 0x00007f25beb485eb n/a (libpulsecommon-10.0.so)
#18 0x00007f25beb48989 n/a (libpulsecommon-10.0.so)
#19 0x00007f25beb4920a n/a (libpulsecommon-10.0.so)
#20 0x00007f25c1c23f36 n/a (libpulse-mainloop-glib.so.0)
#21 0x00007f25c4062a57 g_main_context_dispatch (libglib-2.0.so.0)
#22 0x00007f25c4062c88 n/a (libglib-2.0.so.0)
#23 0x00007f25c4062d1c g_main_context_iteration (libglib-2.0.so.0)
#24 0x00007f25cb15a061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#25 0x00007f25cb0fdffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#26 0x00007f25cb107048 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#27 0x0000006d9a13a2ce main (latte-dock)
#28 0x00007f25ca54b4ca __libc_start_main (libc.so.6)
#29 0x0000006d9a13a82a _start (latte-dock)

Stack trace of thread 1338:
#0  0x00007f25ca60ee9d poll (libc.so.6)
#1  0x00007f25cf4d98e0 n/a (libxcb.so.1)
#2  0x00007f25cf4db679 xcb_wait_for_event (libxcb.so.1)
#3  0x00007f25bd29272a n/a (libQt5XcbQpa.so.5)
#4  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#5  0x00007f25c645f049 start_thread (libpthread.so.0)
#6  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 1556:
#0  0x00007f25c64651ad pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f25caf1d5ec _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#2  0x00007f25ce184ae8 n/a (libQt5Quick.so.5)
#3  0x00007f25ce184f4a n/a (libQt5Quick.so.5)
#4  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#5  0x00007f25c645f049 start_thread (libpthread.so.0)
#6  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 17208:
#0  0x00007f25c64651ad pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f25caf1d5ec _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#2  0x00007f25ce184ae8 n/a (libQt5Quick.so.5)
#3  0x00007f25ce184f4a n/a (libQt5Quick.so.5)
#4  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#5  0x00007f25c645f049 start_thread (libpthread.so.0)
#6  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 1439:
#0  0x00007f25ca60ee9d poll (libc.so.6)
#1  0x00007f25c4062c09 n/a (libglib-2.0.so.0)
#2  0x00007f25c4062d1c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f25cb15a061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f25cb0fdffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f25caf1740e _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f25cdcc01d5 n/a (libQt5Qml.so.5)
#7  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#8  0x00007f25c645f049 start_thread (libpthread.so.0)
#9  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 1759:
#0  0x00007f25c64651ad pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f25caf1d5ec _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#2  0x00007f25ce184ae8 n/a (libQt5Quick.so.5)
#3  0x00007f25ce184f4a n/a (libQt5Quick.so.5)
#4  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#5  0x00007f25c645f049 start_thread (libpthread.so.0)
#6  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 1543:
#0  0x00007f25c64651ad pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f25caf1d5ec _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#2  0x00007f25ce184ae8 n/a (libQt5Quick.so.5)
#3  0x00007f25ce184f4a n/a (libQt5Quick.so.5)
#4  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#5  0x00007f25c645f049 start_thread (libpthread.so.0)
#6  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 1355:
#0  0x00007f25ca60ee9d poll (libc.so.6)
#1  0x00007f25c4062c09 n/a (libglib-2.0.so.0)
#2  0x00007f25c4062d1c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f25cb15a061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f25cb0fdffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f25caf1740e _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f25cb579396 n/a (libQt5DBus.so.5)
#7  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#8  0x00007f25c645f049 start_thread (libpthread.so.0)
#9  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 18232:
#0  0x00007f25ca60ee9d poll (libc.so.6)
#1  0x00007f25c4062c09 n/a (libglib-2.0.so.0)
#2  0x00007f25c4062d1c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f25cb15a061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f25cb0fdffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f25caf1740e _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f25cdcc01d5 n/a (libQt5Qml.so.5)
#7  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#8  0x00007f25c645f049 start_thread (libpthread.so.0)
#9  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 1679:
#0  0x00007f25ca60ee9d poll (libc.so.6)
#1  0x00007f25c4062c09 n/a (libglib-2.0.so.0)
#2  0x00007f25c4062d1c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f25cb15a061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f25cb0fdffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f25caf1740e _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f258eafb18a _ZN15KCupsConnection3runEv (libkcupslib.so)
#7  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#8  0x00007f25c645f049 start_thread (libpthread.so.0)
#9  0x00007f25ca618f0f __clone (libc.so.6)

Stack trace of thread 28851:
#0  0x00007f25c64651ad pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f25caf1d5ec _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#2  0x00007f25ce184ae8 n/a (libQt5Quick.so.5)
#3  0x00007f25ce184f4a n/a (libQt5Quick.so.5)
#4  0x00007f25caf1c15b n/a (libQt5Core.so.5)
#5  0x00007f25c645f049 start_thread (libpthread.so.0)
#6  0x00007f25ca618f0f __clone (libc.so.6)

`

**Comment by psifidotos** [comment]
from the description I dont understand, do you have a screenshot? what do you mean by mouse wheel on event calandar widget? what do you mean by trying to change the volume at the event calendar widget?

**Comment by eversins** [comment]
Hello, sorry it was confusing. I have tested a bit and made a new clean install. I have found an easier to understand way to reproduce the error.

Install [Event Calendar](https://store.kde.org/p/998901/) -> add the widget to the dock -> open "Event Calendar Settings" -> Close the settings.

This makes latte-dock crash.

**Comment by psifidotos** [comment]
If you try this with a plasma panel isnt plasmashell crashing?

**Comment by eversins** [comment]
No crash if do the same thing on a plasma panel.

**Comment by eversins** [comment]
No idea what is going on, I can't reproduce the error that was consistent before.. I have seen this behavior before though, looks like its not consistent.

Is there anything I should do the next time it happens? like post a specific log or something?

**Comment by psifidotos** [comment]
> Is there anything I should do the next time it happens? like post a specific log or something?

For crashes we need the debug symbols installed at least from the following packages,

latte-dock,
plasma-workspace,
plasma-framework

it is the only way the crash reports to point ys somewhere
