### ISSUE TITLE
Non-conflicting panels

### ISSUE THREAD

**Issue by MggMuggins** [psifidotos/Latte-Dock#684]
Alright, so I like latte a lot. The one problem I have is my top panel conflicting with the full-height dock on the left side. I found someone who had configured things so that the dock would not conflict, the way I want it to:
![non-conflicting panels](https://user-images.githubusercontent.com/16041213/29640526-e9f197f6-8824-11e7-912f-ceef93f7d530.png)
That's the layout I'd like to have, where the dock is always below the top panel, not just when you select the panel rather than the dock. It also looks better when that happens.
The guy who posted that image said that 0.7 allowed him to do that, but I can't find the configuration option for the life of me. A little help would be great. Thanks!

**Comment by psifidotos** [comment]
This is automatically set as long as the top panel is also a Latte dock instance... use the Unity layout as a base....

**Comment by MggMuggins** [comment]
Is there any way to apply some of the settings from the Unity Layout to my current one or do I have to just switch and reconfigure?

**Comment by psifidotos** [comment]
Yes you can,

Just add a new top latte dock, Always visible, Justify alignment with background size 100%

**Comment by MggMuggins** [comment]
Thanks. I'm looking forward to what you guys come up with in future! I would recommend releasing more often, it helps keep people interested, and gives those who don't want to use AUR builds or the like the newest features and polish. Thanks!
