### ISSUE TITLE
Increase dock/applet size without changing icon size?

### ISSUE THREAD

**Issue by eversins** [psifidotos/Latte-Dock#685]
Hello, I hope I am not getting to annoying.

I was wondering if it is possible to increase the dock/applet size without increasing the Icons size?

I like having small icons with 48px, the problem is that the system tray will only make two rows if you set icon size to 56px, the clock is also too small for my taste.

Until now I have always just had two separate docks, one for applications, the other for Clock + systray. Just wondering if the same would be possible with one dock.

Thank you.

**Comment by psifidotos** [comment]
Unfortunately this is not possible...

**Comment by eversins** [comment]
I think that would be a great feature, would make it more dynamic, I guess most people wouldn't use this though so I fully understand.

A followup question, it is also impossible to have two panels on one side of the screen, is that correct?

**Comment by psifidotos** [comment]
No, it isnt possible to have two panels in the same edge except if one is Latte and the other is plasma panel
