### ISSUE TITLE
[v0.7] - Dock is flickering in tile managers

### ISSUE THREAD

**Issue by magnus-gross** [psifidotos/Latte-Dock#686]
Attached is a screen capture of the problem. The dock is flickering, even if there is no window near. It should be steady instead.

[out.zip](https://github.com/psifidotos/Latte-Dock/files/1249535/out.zip)

I am using a very strange combo: KDE + the tiling window manager bspwm, instead of the default KDE window manager.
However, I know that the problem does not exist with `latte-dock-0.6.2-1`. Downgrading to that version fixes the problem.
The version of the problematic dock is `0.7.0-1`.
I am using Arch Linux, and I can give you any kind of additional information if you need it. :)

**Comment by magnus-gross** [comment]
Btw, forgot to mention that of course I configured bspwm to not manage latte dock windows, meaning I added the lines:
```bspc rule -a plasmashell state=floating
bspc rule -a lattedock state=floating```

**Comment by psifidotos** [comment]
it is pretty obvious from the video that the tile manager is trying to change the dock position and of course the dock refuses it... :)

I dont know why the window manager is still enforcing this even though you have added an exception... try the following:

1. bspc rule -a latte-dock state=floating

2. try from Latte Advanced(Settings) -> Tweaks -> (Disable) Behave as a normal dock window

**Comment by magnus-gross** [comment]
This did not fix it for me.
The window manager cannot be the sole problem, there must have been a change from 0.6 to 0.7 that caused this.

**Comment by psifidotos** [comment]
no idea.... there are around 600 commits between 0.6 and 0.7

**Comment by psifidotos** [comment]
also there are users that report that i3-gaps is working ok

**Comment by magnus-gross** [comment]
I will look, if I find any suspicious looking commit...

**Comment by magnus-gross** [comment]
Somehow it is fixed now, I don't know how, I didn't change anything, maybe it was the reboot.
Btw I learned that the `bspc rule` is not even needed to unmanage latte dock itself, it's only needed to unmanage the windows that latte spawns, such as a Wifi menu. Bspwm automatically does not manage docks, as I learned here: https://github.com/baskerville/bspwm/issues/644

Anyways, I think this can be closed now :)
