### ISSUE TITLE
[solved][0.7] - Dock visibility doesn't trigger for dock on the left side

### ISSUE THREAD

**Issue by tobsz** [psifidotos/Latte-Dock#687]
I'm using Arch with KDE and have my Latte Dock on the left side. Since a while I have the problem, that it's not triggered when the cursor hits the left edge, but only when the cursor halts at 1 pixel before the edge. I tried all other edges and there it works as expected.

**Comment by psifidotos** [comment]
try to disable all the touch gestures from plasma systemsettings

**Comment by tobsz** [comment]
That worked! Thanks!

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-is-not-appearing-what-is-the-problem-
