### ISSUE TITLE
Latte icon needs bigger resolution

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#689]
On the dock, when we open Layout Confiscator window, it shows Latte icon on the dock with visible pixels, even more on hover close up, see screen:

http://imgur.com/a/lnBEE

**Comment by psifidotos** [comment]
has been fixed in master branch it will land in 0.7.1 the user will have to disable/re-enable the Latte autostart from Tweaks page...

![image](https://user-images.githubusercontent.com/2216474/29750270-391049ae-8b45-11e7-9510-e16efc3f2a2b.png)
