### ISSUE TITLE
Append the dependencies in alphabetical order

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#691]
Inside the CmakeLists.txt there are the dependencies that are required for building and running latte. They could be in alpabetical order for a faster look up or helping various packagers.

**Comment by Petross404** [comment]
* Quick Qml DBus Gui

* I18n CoreAddons GlobalAccel Archive XmlGui DBusAddons IconThemes Wayland Crash
Plasma PlasmaQuick WindowSystem Declarative Activities Notifications

*add_subdirectory(app)
add_subdirectory(applets)
add_subdirectory(containment)
add_subdirectory(icons)
add_subdirectory(liblattedock)
add_subdirectory(plasmoid)
add_subdirectory(shell)

**Comment by psifidotos** [comment]
please make a PR .... I will accept it ...

**Comment by Petross404** [comment]
Ok

https://github.com/psifidotos/Latte-Dock/pull/692/files
