### ISSUE TITLE
Ctrl+LeftClick=New Instance

### ISSUE THREAD

**Issue by Kaygusuz91** [psifidotos/Latte-Dock#693]
When Ctrl+LeftClick=New Instance option enabled dock causes to frame drops severely, from 60 fps to 40's.

Edit: Enabling Show applets/task title tooltips on hovering option causes as well.

**Comment by psifidotos** [comment]
no idea... I am not an expert around fps drops... I would compare first with plasma panels...

1. for Ctrl+leftClick, try to open the same task with a plasma taskmanager
2. for title tooltips, compare with hovering over a plasma panel and show the applets tooltips

**Comment by psifidotos** [comment]
more likely... 

https://bugs.kde.org/show_bug.cgi?id=379192

but it hasnt been tracked down... it happens also when launching from any plasma taskmanagers... In Latte is very obvious when clicking such a launcher... in my old system that isnt such powerful opening kate breaks the bouncing animation... Unfortunately this isnt Latte fault but plasma libraries fault...
