### ISSUE TITLE
Gentoo QA Notice: This package installs one or more .desktop files that do not pass validation

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#695]
You might want to read this : https://github.com/gentoo/gentoo/pull/5547

> Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.1. Note that the version field is not required to be present.
> https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

Can you do something for this?

**Comment by psifidotos** [comment]
yes, i will use the plasma desktop files as templates
