### ISSUE TITLE
QuickLaunch in Latte Dock has small icon

### ISSUE THREAD

**Issue by Void97** [psifidotos/Latte-Dock#696]
Hi,
I noticed that, if I add the QuickLaunch plasmoid to Latte Dock, add an application to it and then enable the Popup in QuickLaunch settings, the application icon is very small compared to a QuickLaunch applet in a classic Plasma Panel.

For a better comparison, here's the screenshot of Latte Dock:
![quicklaunchlattedock](https://user-images.githubusercontent.com/15859553/29817458-5cf50c1e-8cb8-11e7-9bd3-28b95bae3a0c.png)
while here's the classic Plasma Panel:
![quicklaunchplasmapanel](https://user-images.githubusercontent.com/15859553/29817491-7a1b981c-8cb8-11e7-8a61-7bb8f8c0e5c3.png)

**Comment by psifidotos** [comment]
1. if you increase the applets size from Latte does it change its size?

2. probably the quicklaunch plasmoid wants more thickness in order to show properly(probably for applets size >=64 it would show better)... This is a known plasma design limitation for which Latte cant do much...

**Comment by Void97** [comment]
Increasing the icon size to 48px in Latte settings works, but now the other applet icons are huge, so I guess I'll stay at 40px size, even if the quicklaunch icon's small. Probably this can be solved only from plasma-side. Thanks for your explanation.

**Comment by Petross404** [comment]
Please report the bug upstream so it can be fixed :)

**Comment by psifidotos** [comment]
Unfortunately it is a dead end... plasma devs should use the Latte IconItem instead of plasma iconitem and not gonna happen... the way is to he forked and make it work correctly with Latte
