### ISSUE TITLE
Pop ups from locked plasmoids are misplaced far from dock...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#7]
This is frameworks bug: https://bugs.kde.org/show_bug.cgi?id=374127

I 've sent a patch: https://git.reviewboard.kde.org/r/129696/

I hope it is accepted...

**Comment by audoban** [comment]
Nice.

**Comment by psifidotos** [comment]
**_FIXED with KDE Frameworks 5.30_**
