### ISSUE TITLE
Issues with latte-dock

### ISSUE THREAD

**Issue by enolp** [psifidotos/Latte-Dock#700]
Right now I'm replacing my Plasma stock docks with Latte, but I think I found bugs related to the aspect of the widgets/applets and the Latte dock itself, let me show you an image:

![screenshot_20170902_110513](https://user-images.githubusercontent.com/16736782/29994382-a84a9288-8fce-11e7-9026-4915f08845ef.png)

As you can see, there are a bunch of icons. From the system load view icon to the printer icon, there are some icons which are larger than the others (Bluetooth, Device automounter, volume applet), these don't respect the applet size that I set in Latte preferences, and also behaves as a normal application having that blue line at the bottom of each of them.

Also if you look closely, there is an white line which covers all the botton part and I don't know if it is bug or is intended, but al would like to replace it with a shadow like Plasma stock docks do.

I hope you can help me. Thanks for the support.

P.D: The letter, Octopi and Manjaro settings manager are icons of the System tray widget.

**Comment by psifidotos** [comment]
> From the system load view icon to the printer icon, there are some icons which are larger than the others (Bluetooth, Device automounter, volume applet), these don't respect the applet size that I set in Latte preferences, and also behaves as a normal application having that blue line at the bottom of each of them.


these are systray icons and Latte cant do anything about that...

> Also if you look closely, there is an white line which covers all the botton part and I don't know if it is bug or is intended, but al would like to replace it with a shadow like Plasma stock docks do.

1. either you have enabled solid panel background from Latte Appearance page
2. or your kwin compositing is disabled

what is the case?
