### ISSUE TITLE
[feature request] Font/icons color based on wallpaper

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#702]
Not sure how possible that is now but this feature works perfectly in Android and is good (required) practice if panel intends to stay transparent.

At the moment, if we want to have full consistency (panel in maximized mode matching colors of windows) then we have two main choices: light and dark UI. Since I use breeze colors, then I have to use breeze colored panel so the result is nicely consistent and homogeneous:

https://imgur.com/oEcgN4V

With those high standards, I just couldn't have dark panel with light window colors so dark panel must come with dark windows for consistency sake. That limits me to two choices light and dark (prefer light so there is no choice for me really) but there can be different sets of colors (other than breeze colored light and dark themes) so it's not that bad.

The problem appears on transparent panel. Light panel uses black fonts and icons (ideally, most light themes - there are little of them - screwed that having both white and black icons, which makes them unusable). This forces wallpaper to be extremely light in panel area. Even sky is too dark so in most cases only white fonts/icons and thus black panel (and dark windows).  This limits strongly choice of wallpaper.
This is an example where sky is already too dark so I experimentally changed to dark panel with white icons:

https://imgur.com/hC1E0xx

However, I insist on homogeneous UI and I don't like dark themes so I must switched it to light theme again.

In order to have transparent panel and independently dark and light panel themes, **we would need panel font/icons be automatically reverted to a color matching dominating brightness of a wallpaper in panel area**. Like I said, Android mastered it perfectly so transparent panel always looks good no matter what wallpaper.

I'm not sure if that''s possible for latte to override theme's panel font/icon colors but it would be nice to consider implementation of that feature. Maybe there is some additional development on Plasma side to be done. Hopefully **WHEN** you join officially KDE team, you could push that so it could be implemented (even better integration of latte with plasma).

Again, Android is the shining example of how nicely it can work. Transparent panel is awesome solution that makes desktop look modern, light, uncluttered, minimalistic but it can work well only under very specific and strict rules. **If wallpaper is changeable, then transparent panel must have dynamically changeable color of fonts/icons (theme override).**

It's just good design, period.

Thanks for hearing me out and I hope you consider this idea if not now, then in the feature.

P.S. Thanks for last update. Now light panel doesn't produce white shadows over dark fonts/icons and panel size can be changed fluently :D. Awesome!

**Comment by psifidotos** [comment]
unfortunately this needs upstream changes to upstream first... and also someone that can handle this expertise... Personally I dont have any knowledge how to achieve this...

**Comment by michaldybczak** [comment]
So just as I expected. I just hope you will remember about it if there will be some opportunity to make such upstream changes (by the discussion with persons who can implement it). That's all. Thanks :)

**Comment by psifidotos** [comment]
I think I can find a way for this... I  dont know how good results it would produce but we could test it and see...

the pipeline is the following. Latte has a choice in order to track wallpaper changes... in such event:
1. it calls wal (just create the pallete and not changing the colors in apps and terminals)
2. it calls Breeze Alpha Black in order to set the background color and text color for the panels/docks

**Comment by michaldybczak** [comment]
Change of font colors must be somehow tied with panel color, otherwise, if I choose breeze lite - a light panel, darker wallpaper, it will change font to white, then I maximize and will see nothing? Or will it switch to default on maximize? Hmmm... ;P

Every small option produces so many effects like domino.

**Comment by psifidotos** [comment]
I am playing with this and it works in most cases but for full panel transparent case when the wallpaper is too bright, the text is not providing enough contrast.. I suppose that we need the panel background to be a bit visible and not completely transparent

**Comment by psifidotos** [comment]
these are some examples... I dont know if it worth the trouble...

![image](https://user-images.githubusercontent.com/2216474/30522328-fe6b0850-9bd6-11e7-921d-bb8c1b2c0cc8.png)

![image](https://user-images.githubusercontent.com/2216474/30522333-214fda58-9bd7-11e7-80a3-fa4a33400993.png)

![image](https://user-images.githubusercontent.com/2216474/30522339-3f3fca0a-9bd7-11e7-8305-6d778ba7d53e.png)

![image](https://user-images.githubusercontent.com/2216474/30522369-8c24a016-9bd7-11e7-894b-93e829a904e1.png)

**Comment by michaldybczak** [comment]
In maximized state, only solid background is most reasonable option. Some may want to flirt with other settings, but I used system with fully transparent panel and semi-transparent for a while and although I love transparency, in maximized mode solid is most functional. In other cases I saw other title bars behind with their descriptions and it looked bad and illegible.

I looked at your screens and wow! It looks very nice! Amazing how font turn into violet in one of the examples. This is very interesting result and it's not that bad. Look how my current wallpaper looks with static black color:
![screenshot_20170917_174253](https://user-images.githubusercontent.com/10132958/30522408-a5c78c16-9bcf-11e7-87d2-b88aa9bd42ff.png)

Despite wallpaper being quite bright, fonts and icons are barely visible. I get that for 99% of wallpapers. It's very, very hard to find a one that is bright enough to look good.

**Comment by michaldybczak** [comment]
But wait. Now when I looked closer, the effect is not what I meant.

I talked about fonts switching colors to the opposite one (black/white) based on the wallpaper overall brightness/color/tone.

If I am right, in your examples, you made fonts semi-transparent so they are colored by the background?

**Comment by psifidotos** [comment]
by enabling blur the situation is improved a little more...

![image](https://user-images.githubusercontent.com/2216474/30522439-9758fc42-9bd8-11e7-9b80-8ce0801643a8.png)

![image](https://user-images.githubusercontent.com/2216474/30522491-671d3a6a-9bd9-11e7-8e33-2b5e9b0f7b36.png)

**Comment by psifidotos** [comment]
> I talked about fonts switching colors to the opposite one (black/white) based on the wallpaper overall brightness/color/tone.
> If I am right, in your examples, you made fonts semi-transparent so they are colored by the background?

I dont touch anything... I just set a background and foreground color for the theme... the colors chosen are wal script resposibility...
https://github.com/dylanaraps/wal

**Comment by michaldybczak** [comment]
Yes, although I personally would like to have fully transparent panel without blur. You always test with dark panel. Majority of themes have dark panels, but I personally found that light panel works out better with overall light window theme.

**Comment by psifidotos** [comment]
> Yes, although I personally would like to have fully transparent panel without blur. You always test with dark panel. Majority of themes have dark panels, but I personally found that light panel works out better with overall light window theme.

unfortunately this cant be possible in many cases, e.g. the background in very light and has many details in it... without blur whatever font color you use the readability wont be acceptable.. I dont know under what criteria wal chooses the background and the font color

**Comment by michaldybczak** [comment]
I have no idea how to use this wal or pywal. I can install it but how to make it work with latte?
Anyway, then in such case we're back to the closest solution: making panel solid on maximizing:

https://github.com/psifidotos/Latte-Dock/issues/713

**Comment by psifidotos** [comment]
> I have no idea how to use this wal or pywal. I can install it but how to make it work with latte?

you cant yet... what I see is that these scripts wal etc... require  a background in order to create the correct contrast, this is what polybar is doing e.g.  without blur...

![image](https://user-images.githubusercontent.com/2216474/30522753-1c1f9cba-9bde-11e7-8181-4908675cfda0.png)

![image](https://user-images.githubusercontent.com/2216474/30522762-362cb6a6-9bde-11e7-9b68-0678a8bb5019.png)

![image](https://user-images.githubusercontent.com/2216474/30522772-615d551a-9bde-11e7-9c05-24441864322f.png)

**Comment by michaldybczak** [comment]
I like the effect but I'm not sure if it's worth to complicate things that much. If it would switch to light, solid panel on maximize... ;P it would be perfect then.

**Comment by aislanmaia** [comment]
Hey @michaldybczak whats your icon pack? Very nice!

**Comment by michaldybczak** [comment]
@aislanmaia the icon pack on my screen is la capitaine, a very nice and complete icon pack.

**Comment by psifidotos** [comment]
@michaldybczak if you are still interested in this, there is a new feature: #905  ;)
