### ISSUE TITLE
Show panel background and shadows when Krunner is opened

### ISSUE THREAD

**Issue by alxlg** [psifidotos/Latte-Dock#703]
When a dock/panel is set to hide its background+shadow when there aren't maximized windows, it intelligently show again background+shadow when you open a drawer-plasmoid like the systray. It doesn't happen when running Krunner (alt+space) though. It would have a better look if the background+shadow are shown when Krunner is opened.

-----

* **Actual look:**

![spectacle dj2337](https://user-images.githubusercontent.com/26327475/30026403-0a14ffe4-917d-11e7-99ee-eaf954b2b505.png)

![spectacle wx2337](https://user-images.githubusercontent.com/26327475/30026377-e7bd99ba-917c-11e7-8122-637847279f1e.png)

-----

* **Expected look (like systray):**
![spectacle jx2337](https://user-images.githubusercontent.com/26327475/30026427-2d97a50c-917d-11e7-9a32-4dd3fd320be6.png)

**Comment by psifidotos** [comment]
that would be nice but it isnt possible

**Comment by alxlg** [comment]
Maybe we could ask to Kwin or KDE developers in general for an API to detect Krunner?

**Comment by psifidotos** [comment]
feature requests can be forwarded to them at bugs.kde.org

**Comment by psifidotos** [comment]
@alxlg I thought a different way to achieve that result...

1. add at your top dock a Search plasmoid
2. assign to that plasmoid a shortcut e.g. Super+Space

and that works...
![image](https://user-images.githubusercontent.com/2216474/32078632-49c0665e-bab0-11e7-9de1-147923a3de39.png)

**Comment by alxlg** [comment]
Great idea, thanks @psifidotos !

**Comment by psifidotos** [comment]
will be fixed with #810 :)...

**Comment by alxlg** [comment]
I saw it, thanks!
