### ISSUE TITLE
[improvement] Better detection on side panel when Dodge Active or Auto Hide

### ISSUE THREAD

**Issue by GortiZ6** [psifidotos/Latte-Dock#704]
I've installed Latte-Dock on a clean KDE Neon Developer under VM. 
I've set Latte-Dock as a left panel, set the Show delay on "Dodge Active" or "Auto Hide" to 0 (I've tried both modes) and Hide to 300ms.
The panel doesn't immediately show up when the cursor hit the left of the screen, instead it seems that the cursor detection is done on the "second pixel" I mean that if I slightly move the cursor away from the screen limit the dock show up.

To reproduce simply create a clean installation of KDE Neon Developer, download Latte-Dock 0.7.1 from Git, follows the INSTALL.md instructions, configure Latte-Dock as previously stated.

**Comment by psifidotos** [comment]
follow instructions: https://github.com/psifidotos/Latte-Dock/issues/676

**Comment by GortiZ6** [comment]
Thanks, sorry for the duplicate. I didn't found the issue.
Anyway since this "left action" is the default on Neon, while you're working on detecting this case, maybe it would be worth to add to the INSTALL.md or README.md or somewhere else that to make it work properly the side where the panel is located should be free by those actions.

**Comment by psifidotos** [comment]
I think this could go to wiki -> F.A.Q.s , https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q. feel free to add an entry there...

**Comment by GortiZ6** [comment]
My bad.. it was already present. I've just added the bug reference so that the textual explanation is now correlated by the pictures in the bug.
