### ISSUE TITLE
Same icon java applications

### ISSUE THREAD

**Issue by brossaip** [psifidotos/Latte-Dock#705]
Hi.
Thanks for the dock, I love it. Most of all its flexibility to have different docks in different screens.
But I have found the problem that when I run netbeans and dbeaver, they are group together and have the same icon in the dock. If I run first netbeans then dbeaver appears as a second dot in netbeans icon and the other way around, if I start dbeaver and later netbeans, then netbeans appears in dbeaver icon.

Thanks a lot!

**Comment by psifidotos** [comment]
compare with plasma taskmanagers... it must be an upstream issue

**Comment by brossaip** [comment]
Yes.
You are totally right. It happens the same with plasma taskmanager.
Thanks a lot.

**Comment by psifidotos** [comment]
then please report it upstream to bugs.kde.org
