### ISSUE TITLE
Prevent from sleep does not work

### ISSUE THREAD

**Issue by tstdin** [psifidotos/Latte-Dock#706]
When playing video in VLC, it prevents screen from sleep in Plasma. But with Latte screen darkens.

I'm using version latte-dock-0.7.0-1 on Fedora 26 KDE.

**Comment by psifidotos** [comment]
I dont understand... what is the difference in rhe experience  between plasma panel and latte dock?

**Comment by tstdin** [comment]
In plasma while playing video the screen stays turned on. In Latte with same conditions not.

**Comment by psifidotos** [comment]
What is your setup? Only Latte docks or combination with plasma ones? 

The power management is activated through a systray... Do you have a systray with activated power management in a latte dock?

**Comment by tstdin** [comment]
I have only one latte dock, systray is present on it.

**Comment by psifidotos** [comment]
power management is enabled in that systray?

**Comment by tstdin** [comment]
Yes,
(sorry for other language)
![systray](https://user-images.githubusercontent.com/25065143/30109034-19e1565a-9305-11e7-9c8e-489984f2cd36.png)

**Comment by psifidotos** [comment]
in my system.. vlc informs the power management to be suspended....

![image](https://user-images.githubusercontent.com/2216474/30109831-764ced68-9310-11e7-9c9f-da792ef57545.png)

**Comment by psifidotos** [comment]
have you tried other media players? none of them shows the above message in power management in the systray?

**Comment by tstdin** [comment]
Ok, probably something wrong with my setup.
With latte dock, the message doesn't appear with any media player I tried. With plasma it does.

**Comment by tstdin** [comment]
You can close this issue. With more testing sometimes it works, sometimes not. But probably it has nothing to do with Latte. Thanks for your time.

**Comment by psifidotos** [comment]
no prob!
