### ISSUE TITLE
Activate panel background when opening krunner

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#707]
When panel background is set to be only shown on maximized windows, it would be more visual appealing
when panel background is also activated on opening krunner.

EDIT:
At least for top panels

EDIT2:
Sry, just saw the closed issue. This can be closed, too.

**Comment by psifidotos** [comment]
not possible

**Comment by psifidotos** [comment]
@marhkb  I thought a different way to achieve that result...

1. add at your top dock a Search plasmoid
2. assign to that plasmoid a shortcut e.g. Super+Space

and that works...
![image](https://user-images.githubusercontent.com/2216474/32078632-49c0665e-bab0-11e7-9de1-147923a3de39.png)

**Comment by psifidotos** [comment]
will be fixed with: #810 :)
