### ISSUE TITLE
Dock won't appear if there is a link at the edge of screen

### ISSUE THREAD

**Issue by shad90** [psifidotos/Latte-Dock#708]
Hi.
First of all, this is a great tool and Thanks to the team. I love latte dock. I am using kubuntu with plasma 5.8.7 and running latte dock v 0.6.2. Every thing is working fine for me. EXCEPT one thing.
 
Dock is configured to dodge active windows and is placed at the bottom. when i am browsing internet and there is a link at the bottom edge of screen latte-dock won't appear by moving the pointer. My pointer transforms into a hand symbol when hovering over a link. I have experimented and came with the result that whenever there is a link at the bottom edge of screen that will change pointer into hand symbol when hovered over it  and every attempt in trying to make dock appear fails.

**Comment by psifidotos** [comment]
Are you using Firefox 55 ?

**Comment by shad90** [comment]
Yes, 55.0.2

**Comment by psifidotos** [comment]
this is a bug of firefox 55 that we have workround it for Latte 0.7 version and i dont think we can add it in the 0.6 version

**Comment by psifidotos** [comment]
you can read at #665
