### ISSUE TITLE
Strange bug with Gimp 2.9.7

### ISSUE THREAD

**Issue by varlesh** [psifidotos/Latte-Dock#709]
Gimp change icon on open app. It's icon taken from gimp icon theme + draw document preview. WTF? :)
![image](https://user-images.githubusercontent.com/8083855/30248506-db7ffef6-9639-11e7-8c9b-269d5a9510c6.png)

Step for reproduce:
- Run gimp 2.9.7
- Open any image on gimp
- Icon will be changed

I think it's hapenned because new gimp version use SVG icons with desktop-file for GUI. This theme contained `gimp-wilber.svg` icon and changed on Latte Dock:
![image](https://user-images.githubusercontent.com/8083855/30248524-5167ac40-963a-11e7-8748-f4ee4bd45568.png)

**Comment by psifidotos** [comment]
does the same thing is happening with plasma taskmanagers?

**Comment by varlesh** [comment]
> does the same thing is happening with plasma taskmanagers?

Yes, but it's not always happened with Open Image, need Create new document and draw anything:

![image](https://user-images.githubusercontent.com/8083855/30248634-781704ec-963c-11e7-9a16-55c64a805c80.png)

**Comment by psifidotos** [comment]
if you are using Latte 0.7 then icons are not changed by Latte... so you can consider this an upstream plasma issue.. to reproduce the same issue with plasma you can increase the size of the panel in order for the icons to become larger...

**Comment by varlesh** [comment]
Increase, not nothing (on left tasks cons only, on down latte):
![image](https://user-images.githubusercontent.com/8083855/30248703-fc186a96-963d-11e7-8f19-70e4c4665552.png)

Yes, i'm use lattedock 0.7.0.

**Comment by psifidotos** [comment]
to increase the icon size for plasma you must go to plasma systemsettings->icons->advanced->Panel Icon size, set it at 256px.

**Comment by varlesh** [comment]
Anyway changed.
![image](https://user-images.githubusercontent.com/8083855/30248741-f0a3d8b6-963e-11e7-89b4-fe8732301560.png)

**Comment by psifidotos** [comment]
If you put it horizontal, isnt increasing?

**Comment by varlesh** [comment]
Why this needed? Used icon(s) from gimp icon themes:
/usr/share/gimp/2.0/icons/Color/ICON-THEME/apps/gimp-wilber.svg
/usr/share/gimp/2.0/icons/ICON-THEME/scalable/apps/gimp-wilber-eek.svg
![image](https://user-images.githubusercontent.com/8083855/30248782-ab4252a6-963f-11e7-8b36-1f6da2dca031.png)

**Comment by varlesh** [comment]
reproduce always:
- open gimp 2.9.7
- create new document
-  fill layer documment any color
- icon changed

**Comment by varlesh** [comment]
If application closed, all fine:
![image](https://user-images.githubusercontent.com/8083855/30248836-5fac4652-9640-11e7-8938-ace4db24f8b1.png)

**Comment by varlesh** [comment]
desktop-file gimp 2.9.7:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=GNU Image Manipulation Program
GenericName=Image Editor
Comment=Create images and edit photographs
# Translators: Search terms to find this application. Do NOT translate or localize the semicolons! The list MUST also end with a semicolon!
Keywords=GIMP;graphic;design;illustration;painting;
Keywords[ar]=GIMP;graphic;design;illustration;painting;
Keywords[ca]=GIMP;gràfics;disseny;il·lustració;dibuix;
Keywords[de]=GIMP;Grafik;Design;Illustration;Malen;
Keywords[el]=GIMP;γραφικό;σχεδίαση;επεξήγηση;βαφή;
Keywords[es]=GIMP;gráfico;diseño;ilustración;dibujo;
Keywords[fr]=GIMP;graphisme;conception;design;illustration;image;peinture;
Keywords[hr]=GIMP;grafika;dizajn;ilustrcija;slikanje;
Keywords[hu]=GIMP;grafika;dizájn;tervezés;illusztráció;festés;
Keywords[is]=GIMP;mynd;hönnun;myndskreyting;málun;myndvinnsla;
Keywords[it]=GIMP;grafica;design;illustrazioni;disegno;fotoritocco;
Keywords[pl]=GIMP;grafika;graficzny;design;dizajn;projektowanie;wzornictwo;ilustracja;ilustrowanie;rysunek;rysowanie;rysownictwo;malowanie;malarstwo;obrazy;obrazki;fotografia;zdjęcia;retuszowanie;renderowanie;wtyczki;
Keywords[pt]=GIMP;gráficos;design;desenho;ilustração;pintura;
Keywords[sk]=GIMP;grafika;grafický;návrh;dizajn;ilustrácia;kresba;maľovanie;maľba;
Keywords[sl]=GIMP;grafika;oblikovanje;ilustracija;slikanje;
Exec=gimp-2.9 %U
TryExec=gimp-2.9
Icon=gimp
Terminal=false
Categories=Graphics;2DGraphics;RasterGraphics;GTK;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=GIMP
X-GNOME-Bugzilla-Component=General
X-GNOME-Bugzilla-Version=2.9.7
X-GNOME-Bugzilla-OtherBinaries=gimp-2.9
StartupNotify=true
MimeType=image/bmp;image/g3fax;image/gif;image/x-fits;image/x-pcx;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-psd;image/x-sgi;image/x-tga;image/x-xbitmap;image/x-xwindowdump;image/x-xcf;image/x-compressed-xcf;image/x-gimp-gbr;image/x-gimp-pat;image/x-gimp-gih;image/tiff;image/jpeg;image/x-psp;application/postscript;image/png;image/x-icon;image/x-xpixmap;image/x-exr;image/x-webp;image/svg+xml;image/x-wmf;image/jp2;image/jpeg2000;image/jpx;image/x-xcursor;
X-Ubuntu-Gettext-Domain=gimp20
```

**Comment by psifidotos** [comment]
I think it is  obvious gimp added a feature in order to update its icon based on the image that us open.... This is desired behavior of gimp and taskmanagers correctly support it...

If you dont like it then look into gimp settings a way to disable this preview or ask at gimp forums if there is any other way to disable it

**Comment by varlesh** [comment]
I'm not found this option... It's very ugly looking :(
I try delete all gimp-wilber icons, delete plasma & icon cache but not nothing... anyway use this ugly icon+preview:
```
sudo rm -r /usr/share/gimp/2.0/icons/*/*/*/gimp-wilber*
rm -rf ~/.cache/ico* ~/.cache/plasm*; killall plasmashell latte-dock
```

**Comment by varlesh** [comment]
@psifidotos maybe possible add support ignore this on latte? It's really ugly

**Comment by varlesh** [comment]
@SmartFinn It's happened on Unity or Gnome?
PPA: `ppa:otto-kesselgulasch/gimp-edge`

**Comment by psifidotos** [comment]
Gimp is updating its icon dynamically... i dont know how you can disable this...

The best way to solve this is with gimp community... maybe add an option in gimp setings

**Comment by varlesh** [comment]
Yes,LOG:
```
[/build/gimp-91bLHR/gimp-2.9.7~3/plug-ins/file-raw/file-darktable.c] have_darktable: 0
gimp_widget_load_icon(): icon theme has no icon 'gimp-wilber-outline'.
gimp_pickable_contiguous_region_by_seed: foo took 0,0038 seconds
gimp_widget_load_icon(): icon theme has no icon 'gimp-wilber-outline'.
```

**Comment by SmartFinn** [comment]
@varlesh no, Unity launcher doesn't have this issue. And log not contains those lines:

```
[/build/gimp-91bLHR/gimp-2.9.7~3/plug-ins/file-raw/file-darktable.c] trying to call 'darktable'
[/build/gimp-91bLHR/gimp-2.9.7~3/plug-ins/file-raw/file-darktable.c] g_spawn_sync failed
[/build/gimp-91bLHR/gimp-2.9.7~3/plug-ins/file-raw/file-darktable.c] error: Failed to execute child process "darktable" (No such file or directory)
[/build/gimp-91bLHR/gimp-2.9.7~3/plug-ins/file-raw/file-darktable.c] have_darktable: 0
 mapped '<Toolbox>/Xtns/Misc' to '<Image>/File/Create/Misc'
 mapped '<Toolbox>/Xtns/Photo' to '<Image>/Filters/Extensions/Photo'
```

**Comment by varlesh** [comment]
@SmartFinn Thx

Bug reported: https://bugzilla.gnome.org/show_bug.cgi?id=787502
