### ISSUE TITLE
Widget tooltip in edit mode is too high

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#71]
I hope i got wording right. Picture will explain it all:

![dock](https://cloud.githubusercontent.com/assets/19151258/21962803/586442da-db26-11e6-94ef-297da2af69e4.png)

Main problem with this is that attempt to click any of controls on that tooltip will fail because cursor leaves widget and tooltip gets hidden.

P.S. Amazing work you guys do here, keep it up! I already removed old dock and using this as a daily driver. New dock is simply perfect.

**Comment by psifidotos** [comment]
_this is #7, plasma bug and it is fixed with KDE Frameworks 5.30_

**Comment by psifidotos** [comment]
I will leave this open for some days, just in case that other users might want to report it also...

**Comment by psifidotos** [comment]
> P.S. Amazing work you guys do here, keep it up! I already removed old dock and using this as a daily driver. New dock is simply perfect.

thank you very much !!!

**Comment by psifidotos** [comment]
> Main problem with this is that attempt to click any of controls on that tooltip will fail because cursor leaves widget and tooltip gets hidden.

until an update to Frameworks 5.30 is possible if someone wants to remove a specific applet,  he can use the right click over the applet, it provides a remove applet choice
