### ISSUE TITLE
icons doesnt zoom on hover ...

### ISSUE THREAD

**Issue by lulu1315** [psifidotos/Latte-Dock#710]
.... which is very frustrating of course :) ...
install from https://github.com/ubuntuvibes/Debs.git : latte-dock_0.6.0-1_all.deb
the zoom on hover is set at 100%
this is kde neon user edition.everything pretty standart
except maybe double screen (one HDMI the other DVI)
screen is on primary.
tried to change a little bit of everything but ... no zoom

**Comment by psifidotos** [comment]
do you have a video or screenshot to understand which icons dont hover? are your desktop effects enabled and compositing is running ok in your system? is your dock transparent? Btw latte has a 0.6.2 version available for its 0.6 branch
