### ISSUE TITLE
Icons become invisible

### ISSUE THREAD

**Issue by GortiZ6** [psifidotos/Latte-Dock#712]
Hi I've searched on the closed issues, but I couldn't find any matching so I opened this new one.
As you can see on the attached picture the icons on my panel are invisible, they are not always "all" invisible, sometimes some of them stay visible, and all of the appear again when hovering with the mouse, but after the parabolic animation finish they randomly disappear.

![screenshot_20170915_124730](https://user-images.githubusercontent.com/3738577/30480665-3df80b16-9a1b-11e7-92a0-9d13e89b2633.png)

I'm running Latte-Dock 0.7.1 on KDE Neon Development. The Latte-Dock is positioned on the left side of the screen and is in auto-hide. Let me know if you need more details on my settings.

**Comment by psifidotos** [comment]
are these icons applets or tasks( windows ) ?

**Comment by GortiZ6** [comment]
Mixed, in the top corner there's the Application Launcher, then the visible one is a Folder View, after it I've several icons some of them are open software (konsole, kdiff3, ...) and some are pinned software (Firefox, Dolphin, ...)

**Comment by psifidotos** [comment]
I cant make any guess... noone has repored such issue before...

if you change icon theme the problem persists?

**Comment by GortiZ6** [comment]
What I forgot to say is that I'm using VMWare VM on Windows, could it be related to the graphic driver?

**Comment by GortiZ6** [comment]
I've just tried to change the icon theme and panel icon size (64 and 256) and what I see is that the first time I recall the panel it's showing all the icons, but they start to disappear when i hover it with the mouse.

**Comment by psifidotos** [comment]
> What I forgot to say is that I'm using VMWare VM on Windows, could it be related to the graphic driver?

it could be but I cant be sure

**Comment by GortiZ6** [comment]
Is there anything I can do to help you test? I'm a developer in Qt, even if I've never used the KDE framework. I usually develop using the QtCreator as well... so it might be not that easy for me to do debug using ddd

**Comment by psifidotos** [comment]
unfortunately if this is a graphics driver issue in virtual environment I dont know how we could track this down and also if this is the case then this is upstream but I dont know where to locate it... 

If you use different virtual environment or at a different computer same problem occurs?

**Comment by psifidotos** [comment]
also kde neon devs that used a virtual machine to test Latte in order to migrate it at Neon Dev Edition didnt report such issue

**Comment by GortiZ6** [comment]
I mounted the same virtual disk on Virtualbox and the issue is not present, so I can probably confirm that it's linked to the video drivers or the interaction with VmWare :(

**Comment by GortiZ6** [comment]
I can also confirm that disabling video acceleration on VMWare (it switch to use llvmpipe) the issue is not present.

**Comment by psifidotos** [comment]
ok...

**Comment by GortiZ6** [comment]
Just for note: further investigation shows that downgrading the VM to hardware 11 (which disables the OpenGL 3.3 and instead allows OpenGL 2.1 only) seems to fix the issue as well.
