### ISSUE TITLE
Regression with future kwin/plasma

### ISSUE THREAD

**Issue by gruel** [psifidotos/Latte-Dock#714]
I tried the version 5.10.95 (the beta version) available on kde-unstable on archlinux and latte does have numerous regressions:

- The pin/unpin is mess up and icon does not remember their position.
- moving icon in the dock crash latte.

Nothing major but I prefer to raise the issue before the final.

**Comment by psifidotos** [comment]
unfortunately I dont have an environment to test things yet... these issues  dont occur with plasma panels/taskmanagers?

**Comment by gruel** [comment]
I am using the dock so I cannot see how it will happen with the panel/taskmanager. I don't see how to achieve the same result with taskmanager.

**Comment by psifidotos** [comment]
1. add a plasma panel that contains a plasma taskmanager
2. try to pin an app or move an icon (does it crash)

Latte is using the plasma libraries to achieve these goals

2017-09-19 16:37 GMT+03:00 Nicolas Gruel <notifications@github.com>:

**Comment by JenaPlinsky** [comment]
Ciao @psifidotos @gruel 

![spectacle n13767](https://user-images.githubusercontent.com/24593950/30607016-fc5d0894-9d73-11e7-92ac-8ceb716bd36b.png)

layouts show the pinned apps correctly but in its conestual menu all check boxes are not set
here, firefox should have been pinned on all the activities but its fag result un marked
![immagine1](https://user-images.githubusercontent.com/24593950/30607229-922cc026-9d74-11e7-89f3-b08af08ec3de.png)

here, code should have been pinned on the "cinema" activities but its fag result un marked
![immagine2](https://user-images.githubusercontent.com/24593950/30607868-d405bcf8-9d76-11e7-9425-41c6c477a290.png)

Plasma panel with the only icons plasmoid does not show the pinned launchers
![screenshot_20170919_201034](https://user-images.githubusercontent.com/24593950/30607877-dae449a4-9d76-11e7-9a0d-4c54eb6d0b1e.png)



> moving icon in the dock crash latte.

on my system....
     moving a folder as folderview - does not crash latte
     moving a folde as icon - does not crash latte
     moving a  .desktop files on area launchers - does not crash latte

**Comment by psifidotos** [comment]
> Plasma panel with the only icons plasmoid does not show the pinned launchers

what do you mean? it doesnt pin launchers at all?

**Comment by psifidotos** [comment]
> moving icon in the dock crash latte.

if you have a crash you must use the following steps to produce a backtrace:
https://github.com/psifidotos/Latte-Dock/issues/147

**Comment by JenaPlinsky** [comment]
since I've been using latte for a long time ... now I can not well remember
Does the "only icon" plasmoid have to show the only tasks or even launchers?

If it is correct to have the launchers in the plasma panel, then,as shown in the last image latte's Layout Cinema has several pinned launchers while the default plasma panel shows no one of them

**Comment by gruel** [comment]
Obviously now that I said that it crashed I cannot reproduce it... If I manage to redo it I will open a new issues and give the ddd results (sorry about that). 

But here some screenshot showing some problem on the pinning of firefox (as example)

Firefox icon exist as pinned:

![latte-dock1](https://user-images.githubusercontent.com/69498/30612103-625042b8-9d7b-11e7-8197-dcaa54a862cb.png)

Firefox pinned icon disappear and a new one is there 

![latte-dock2](https://user-images.githubusercontent.com/69498/30612115-688a5754-9d7b-11e7-9c55-5aa64186f69c.png)

The new one can be pinned 

![latte-dock3](https://user-images.githubusercontent.com/69498/30612120-6b9c208a-9d7b-11e7-863a-88eafab0581c.png)

When I am closing firefox I got two pinned one's

![latte-dock4](https://user-images.githubusercontent.com/69498/30612218-c03d6860-9d7b-11e7-8c94-746e2d7ee69d.png)

**Comment by psifidotos** [comment]
something tells me that can reproduce exactly the same faulty behavior with plasma taskmanagers also...

and yes the plasma icon-only taskmanager support pinning of apps

**Comment by JenaPlinsky** [comment]
> yes the plasma icon-only taskmanager support pinning of apps

If I pin an app with the icon-only taskmanager, then do I find the lanucher of that app on Latte dock too ? Is it correct ?
currently with plasma 5.10.95, this is not the case

**Comment by psifidotos** [comment]
If you pin an icon in the icon-only taskmanager you find it in the icon-only taskmamaget not in Latte
