### ISSUE TITLE
Disabling compositing breaks dock

### ISSUE THREAD

**Issue by eversins** [psifidotos/Latte-Dock#715]
Hello,

When I disable compositing with alt+shift+F12 all that is shown is a black bar, everything is still clickable if you know where to press.

When starting a game like CS:GO compositing gets disabled as well, although everything is still shown but not updated/refreshed, so icons could be at a different location that where they are shown.

**Comment by psifidotos** [comment]
screenshot

**Comment by psifidotos** [comment]
Latte version? Plasma version? A plasma panel with plasma taskmanager does it behave correctly in such case in your system? Screenshot?
