### ISSUE TITLE
Latte get extremely lagy when using the 1.21.0-beta0 x64 version of Atom text editor

### ISSUE THREAD

**Issue by RomuloPBenedetti** [psifidotos/Latte-Dock#717]
It get back to normal when Atom is closed.

**Comment by psifidotos** [comment]
Use ksysguard, does any app have high cpu usage in such case?

**Comment by RomuloPBenedetti** [comment]
Latte itself dominate one of my core constantly (~12%) while Atom is focused, maybe atom beta is spamming something?

**Comment by psifidotos** [comment]
Same issue there was also with firefox 55, it probably triggers a windowchanged event from kwin with no reason...

**Comment by satishux** [comment]
Do you have global menu widget enabled?, on electron apps global menu causes high CPU usage.

**Comment by RomuloPBenedetti** [comment]
Yes but Atom is instructed to not export menu through an environment variable, this is not the case.

**Comment by psifidotos** [comment]
This is totally a menu issue... I can reproduce it in Latte only when Active Window Control is present and shows app menu... If I choose a layout that doesnt have a menu applet in it the this doesnt occur... 

> Atom is instructed to not export menu through an environment variable

it probably doesnt take effect... isnt that a plasma 5.11 feature?

**Comment by RomuloPBenedetti** [comment]
I would like to add that this bug still is in effect, Tried it removing global menus (I don't use AWC, it simply don't work here), deactivated it on KDE settings too (had set it to show menus on applications), always affect Latte when Atom is focused, currently using latest Latte (0.7.75) and latest Atom Beta (1.23), KDE 5.10.5 and QT 5.9.2 on fedora 27.

**Comment by psifidotos** [comment]
no it isnt...
I cant reproduce this at all and its global menu in a Latte panel now works just fine.

I use:
- atom-beta 1.23.0-beta1 
- plasma 5.11.3
- kde frameworks 5.40.0
- qt 5.9.2
- KDE Neon distro

references can be found at:
https://github.com/electron/electron/issues/8455
https://github.com/atom/atom/issues/10573
