### ISSUE TITLE
Wrong border detection on right side panel, on one of my monitors

### ISSUE THREAD

**Issue by RomuloPBenedetti** [psifidotos/Latte-Dock#718]
On my right monitor, I have a latte dock on the right side, especially at this condition it detects the border, not at screen border.
![bordererror](https://user-images.githubusercontent.com/12467382/30786928-8dfceba0-a154-11e7-9c14-e55d9b915439.gif)
It may not be noticeable but It detects somewhat 1 or 2 pixels before the screen border.

**Comment by psifidotos** [comment]
run, latte-dock -d --with-window

tske a screenshot of that window when the dock is hidden to check the geometry and the mask

**Comment by psifidotos** [comment]
I suppose it it can also be relevant with mouse sensetivity settings at plasma systemsettings

**Comment by RomuloPBenedetti** [comment]
The problem is at the HDMI2 left edge one.
![spectacle m16349](https://user-images.githubusercontent.com/12467382/30787133-9e131312-a158-11e7-8fe9-0ecc38c8f174.png)

I never changed mouse setting, faced this problem now at 0.7.0+.

acceleration is 20x
pointer limit 0px
initial drag time 100ms
initial drag distance 3 points

**Comment by psifidotos** [comment]
It is just a x,y value...

Are your docks hidden in these settings? IsHidden is set to no

**Comment by RomuloPBenedetti** [comment]
no, here it is again with the dock hidden:
![spectacle i13550](https://user-images.githubusercontent.com/12467382/30787504-7ee07860-a160-11e7-8b1f-000867e46632.png)

**Comment by psifidotos** [comment]
Is that dock on a shared edge?

The mask is set at 2px width, so it is 1px more than the screen edge, is that what you are refering?

**Comment by RomuloPBenedetti** [comment]
No, all my docks are on the outer borders of my setup. Maybe, I really don't know the internals of latte, the problem is as it is on the gif, the real border where mouse stop did not trigger the dock, I need to put the mouse very near to the screen border, but not exactly on the border (the mouse limit).

**Comment by psifidotos** [comment]
The values you see are, (x,y widthxheight)
The values both for window and mask geometry look ok... Have you disabled all touch gestures from plasma systemsettings?

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-is-not-appearing-what-is-the-problem-

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-behaves-strangely-from-plasma-510-and-beyond-can-i-fix-this

**Comment by RomuloPBenedetti** [comment]
Thanks, it worked and now I know there is a FAQ, haha.
