### ISSUE TITLE
Minimize maximized windows sustain active "show background only for maximized windows" trigger

### ISSUE THREAD

**Issue by RomuloPBenedetti** [psifidotos/Latte-Dock#719]
Maximizing a window and after that, minimizing it, sustain active the "background only for maximized windows".

**Comment by psifidotos** [comment]
X11 limitation, you have enabled window previews for all windows and not just for the shown ones from plasma systemsettings

**Comment by RomuloPBenedetti** [comment]
Sad, but thanks for the appointment :)
