### ISSUE TITLE
Extra panels on autohide do not respend to mouse proximity.

### ISSUE THREAD

**Issue by llomellamomario** [psifidotos/Latte-Dock#721]
I do use 2 monitors, and the panels are mirrored, so I don't have to worry on which monitor I do have the mouse, only about moving to the "nearest edge of the screen" (either left or right) Recently I switched to auto hiding the panel. The first panel auto hide works as advertised, but the extra panels set up to autohide do not appear consistently when I move the mouse over.

In fact making the extra panels appear rarely works as in I can count those times with the fingers of my hands. It seems to respect the panel creation order, as in the first created panel always works with auto hide and subsequent ones are the ones that fail. Restarting latte dock makes them appear, at least temporarily until they auto hide, which gives enough time to change the visibility option. Dodge options do seem to show the same behavior. The video shows the gist of the bug in one screen, the first panel created is on the right.
[2017-09-25 15-26-44.zip](https://github.com/psifidotos/Latte-Dock/files/1329626/2017-09-25.15-26-44.zip)

**Comment by psifidotos** [comment]
try to disable all touch gestures from plasma systemsettings

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-is-not-appearing-what-is-the-problem-

**Comment by llomellamomario** [comment]
It was that. You may want to add that a reboot is needed to stop acting weird. Thanks!

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-behaves-strangely-from-plasma-510-and-beyond-can-i-fix-this
