### ISSUE TITLE
Assign a shortcut key to alter the visibility of the dock - Suggestion/idea

### ISSUE THREAD

**Issue by LedBass** [psifidotos/Latte-Dock#723]
I had an idea and don't know if it's plausible or possible, but it's here anyway

What about to add a functionality that changes the visibility of the dock (auto-hide, dodge windows etc...) to a shortcut key? it would cycle over all the options or only to those that user has predefined using checkboxes on the desired visibility options

Just to exemplify, if the user have configured the cycle to use _"always visible"_ and _"dodge maximized"_ and configured a shortcut combo key, let's say **alt+F11**, then the dock would change it's visibility from _"always visible"_ to _"dodge maximized"_ and the dock would hide if there's a maximized window on the current desktop, and if the user hit **alt+F11** again, it would came back to _"always-visible"_ again

What do you guys think? 

I'll upload a mock window pic of the Latte-Dock config with this idea as soon as I can

**Comment by psifidotos** [comment]
Personally i dont think i like it but i will wait for the mockups to conclude
