### ISSUE TITLE
In plasma 5.11 beta, ordering of launchers gets pretty messed up

### ISSUE THREAD

**Issue by andrevmatos** [psifidotos/Latte-Dock#724]
When an application is launched, it's icons goes to the end of the launchers list. Trying to move it sometimes grabs another icon (instead of the one clicked), and releasing it sometimes messes ordering of other icons besides the intended or the grabbed one.

**Comment by psifidotos** [comment]
Compare with a plasma taskmanager, does this occur also in such case?

**Comment by andrevmatos** [comment]
Couldn't test properly with default task manager, because the icons are too wide, but on Icons Only task manager plasmoid on an empty panel, the issue didn't happen. I'm on current master head. Going to clean Latte config and test again.

**Comment by andrevmatos** [comment]
Couldn't reproduce the first part (dragging wrong icon), but ordering thing is evident here:
https://gfycat.com/gifs/detail/FortunateExhaustedAfricanparadiseflycatcher

**Comment by psifidotos** [comment]
This looks totally upstream... Does it happen only with vlc?

**Comment by psifidotos** [comment]
Try to remove the vlc launcher and readd it... what vlc version are you using?

**Comment by andrevmatos** [comment]
It's not specific to VLC.. looks like now there's some kind of "natural" order of the icons, and it messes with what I see and what I "drag"... The thing about the launcher going to the end (the area of unpinned app icons) happens aways:
https://gfycat.com/gifs/detail/WeirdBountifulArachnid

**Comment by psifidotos** [comment]
no idea... when Neon updates to 5.11 i will test and see if this us ours or upstream issue...

**Comment by kupiqu** [comment]
I just upgraded my system to Plasma 5.11 in KDE neon User Edition and can confirm this behavior

**Comment by Scrumplex** [comment]
Can confirm, too! Happens since I updated my neon to 5.11 (using non LTS edition)

**Comment by psifidotos** [comment]
And all of you can you confirm that doesnt happen  with icon-only plasma taskmanager?

**Comment by DonHugo69** [comment]
I will just join in and confirm the same behaviour. No issues with taskmanager.

**Comment by Zonnev** [comment]
Icon-only taskmanager plasmoid has the same issue of moving icons to the right of the dock as Latte Dock on Plasma 5.11

**Comment by psifidotos** [comment]
If the same thing happens with icon-only plasma taskmanager then this is upstream and you should report it at bugs.kde.org

**Comment by gruel** [comment]
I mention that bug before:

https://github.com/psifidotos/Latte-Dock/issues/714#issuecomment-330494534

And I tried the icon-only-task-manager and it does not have this behavior (not moving of the pinning laucher and no duplicate)

**Comment by psifidotos** [comment]
> And I tried the icon-only-task-manager on plasma 5.11 and it does not have this behavior (not moving of the pinning laucher and no duplicate)

not in my system... in Plasma 5.11 in my system  all the launchers show their windows in the end... bad thing is that if this is the plasma desired behavior Latte cant do anything about it...

**Comment by psifidotos** [comment]
reported at: https://bugs.kde.org/show_bug.cgi?id=385594

**Comment by kupiqu** [comment]
Thanks

**Comment by Zonnev** [comment]
I think its a bug because you can not move around an icon anymore to order them, without messing up the place of other icons (in both latte dock and icon only taskmanager). This would be very strange if it really is plasma's desired behaviour.

**Comment by psifidotos** [comment]
the issues are separate, one thing is the task launching and where the window is placed and the second is the dragging. The first is upstream plasma bug, the second I cant know if they dont fix the first...

**Comment by psifidotos** [comment]
ok... small update by changing in main.qml file in the Latte plasmoid line, line +499 from:

`separateLaunchers: true`

to

`separateLaunchers: false`

the situation is improved but all our animations are broken in order to go from launcher->(to) window... so plasma libtaskmanager devs have updated and our animation chain there is broken... I hope it can be fixed from 5.11 and this is not certain if issue _1_ is not fixed first...

**Comment by psifidotos** [comment]
Full upstream issues from libtaskmanager you can read at:

https://bugs.kde.org/show_bug.cgi?id=385594
https://bugs.kde.org/show_bug.cgi?id=385616

**Comment by Zonnev** [comment]
> ok... small update by changing in main.qml file in the Latte plasmoid line, line +499 from: ...

Thank you for the improvement, Latte Dock is a little bit useable again.

**Comment by psifidotos** [comment]
> Thank you for the improvement, Latte Dock is a little bit useable again.

one more thing that helps is to remove all your launchers and readd them... Launchers in plasma 5.11 use a different format now. At least in my system most of the launching animations work correctly afterwards. Dragging is still an issue...

**Comment by kupiqu** [comment]
This worked for me!

Thanks

**Comment by psifidotos** [comment]
and one small detail, pin through the context menu (right click) on an app window...
pinning through drag n' drop a launcher from an app menu is not working correctly because it uses the old launchers style.

I believe that all these will be fixed in 5.10.1

**Comment by trmdi** [comment]
Congratulation. This bug has been fixed in 5.11.1: https://www.kde.org/announcements/plasma-5.11.1.php

**Comment by psifidotos** [comment]
Fixed in plasma 5.11.1
