### ISSUE TITLE
Task manager widget causes the dock height to shrink

### ISSUE THREAD

**Issue by danielee0707** [psifidotos/Latte-Dock#725]
If I add task manager widget to the dock, and then open several applications or open task manager setting, the height of the widget would shrink and the icons would become very small. Deleting task manager restores the height. It seems the taskmanager cannot be used together with other widgets.
These are without and with task manager.
![screenshot_20170930_222050](https://user-images.githubusercontent.com/25728357/31052054-71a3abcc-a62e-11e7-90d2-ec16851d4b95.png)
![screenshot_20170930_222344](https://user-images.githubusercontent.com/25728357/31052047-22e0d9c4-a62e-11e7-8886-c7392945bf6b.png)

**Comment by psifidotos** [comment]
I think that in 0.7.1 this is automatic set, go to Tweaks and disable automatic applet size shrinking

**Comment by danielee0707** [comment]
Disable automatic applet size shrinking didn't do anything, that's why I am asking. Opening task manager setting still shrinks applet size.

**Comment by psifidotos** [comment]
What Latte version are you using?

**Comment by danielee0707** [comment]
Never mind, logout and login resolved my problem :)
