### ISSUE TITLE
Application launcher in Latte does not open from hotcorner set in System Settings, nor pressing the Meta(Windows) key

### ISSUE THREAD

**Issue by koma111** [psifidotos/Latte-Dock#726]
On Manjaro 17.01- Plasma 5.10- Latte 0.7.1, I have set a hotcorner for Application Launcher plasmoid in System Settings. I started using Latte. I deleted the original Plasma panels. I have an Application launcher plasmoid (no matter which I use) on a Latte dock. The set hotcorner does not work. Pressing the Meta/Super/Windows/Logo key also does not show the Application launcher, as it did with Plasma panels. If I add a Default Plasma panel, the hot corner and the Super key work, but show the Plasma panel instance of the Application launcher.

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-can-i-use-my-super-key-to-open-the-app-launcher
