### ISSUE TITLE
[feature request] firefox right click shortcuts

### ISSUE THREAD

**Issue by segdan** [psifidotos/Latte-Dock#727]
Hello,
I'm a Firefox user, and I think that the ability to launch, for example, an anonymous instance of Firefox by right clicking on the icon would be great. What do you think..?

**Comment by psifidotos** [comment]
This totally firefox responsibility to update its desktop file in order to provide such action like other apps are doing....

**Comment by segdan** [comment]
oh ok, I was thinking that, since this functionality is present in kde panels, it was a latte dock missing feature. Thank you

**Comment by psifidotos** [comment]
If plasma taskmanager offers that then Latte should offer it already... do you have a screenshot showing plasma offering that and Latte not?

What Latte version are you using?

**Comment by segdan** [comment]
Here you are. It's in italian, but where it says "nuova finestra anonima" it means new anonymous window.

I'm on latte dock 0.7.1

![screenshot_20171003_133351](https://user-images.githubusercontent.com/16048154/31123375-f6297850-a83f-11e7-817d-74b55e9d7756.png)
![screenshot_20171003_133621](https://user-images.githubusercontent.com/16048154/31123393-005c9942-a840-11e7-8f97-fae9fc2e833e.png)

**Comment by psifidotos** [comment]
and what plasma version are you using?

**Comment by psifidotos** [comment]
ok... the plasma screenshot is not from plasma taskmanager but an icon-only plasmoid that acts as a launcher for firefox... if you want to add such a plasmoid in latte you can do so by going to:

1. Tweaks->uncheck, launchers only on the specified area
2. Drag firefox onto the Latte dock but on the edges and not over the Latte taskmanager

**Comment by psifidotos** [comment]
this is an upstream request for plasma taskmanagers in order to support it also through the plasma libtaskmanager... afterwards Latte will support it directly...

**Comment by psifidotos** [comment]
and found a solution for this... ;) it is an upstream firefox desktop file bug... :)

edit file, /usr/share/applications/firefox.desktop
go down to the actions sections and you will see that is says there:

OnlyShowIn=Unity;

remove these lines and afterwards the wanted actions will work correctly in all taskmanagers including Latte

**Comment by segdan** [comment]
Great. Thanks mate!
