### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by GregoryIstratov** [psifidotos/Latte-Dock#729]
May be I'm not right, but I think almost 300 Mb resident memory is slightly high for a widget.

Latte 0.7.1 from Arch Linux repository.
Plasma 5.10.5

![screenshot_20171011_105202](https://user-images.githubusercontent.com/11486152/31428347-233e48dc-ae73-11e7-8c40-fd5aa0a174cb.png)

**Comment by psifidotos** [comment]
Latte Dock is an app not a widget...

- what plasmoids are you using?
- show us a screenshot for your docks please

**Comment by GregoryIstratov** [comment]
Nothing special. Here's my desktop.

![screenshot_20171012_001943](https://user-images.githubusercontent.com/11486152/31467714-982b8e6e-aee3-11e7-8454-e7fe8ff139e5.jpeg)

**Comment by psifidotos** [comment]
- The top bar is Latte or plasma panel?
- at the top bar are you using, active window control or an spp menu plasmoid?

**Comment by GregoryIstratov** [comment]
Top bar is plasma panel. I use only built-in plasma features, except Latte.
At the top bar I'm using app menu plasmoid.

**Comment by psifidotos** [comment]
in that case 300Mbyte sounds a lot but unfortunately I dont know how to help....

any improvements in this would be appreciated...

**Comment by GregoryIstratov** [comment]
Sorry. After Plasma 5.11 update, I decided to switch to Gnome desktop  ( which also received a new update up to 3.26 ), because the new plasma was really buggy and everything was twisted and a half of the features just didn't work. 
Also, Latte worked strange as well, icons was moving right and left on the new plasma.

**Comment by psifidotos** [comment]
no prob
