### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#73]
I've just open, a wayland session and does not run the latte-dock process or it crash immediately

**Comment by psifidotos** [comment]
this is scheduled for 0.8 version and we will probably need help...

**Comment by JenaPlinsky** [comment]
Ok 👍

**Comment by audoban** [comment]
It is not yet possible to implement.

**Comment by psifidotos** [comment]
> It is not yet possible to implement.

why ?

**Comment by audoban** [comment]
We should expect to have access to the PlasmaWindowManagement

**Comment by psifidotos** [comment]
> We should expect to have access to the PlasmaWindowManagement API, we can not promise anything

According to Martin, Plasma 5.8 has fully open acces to API
5.9, will totally block any access
5.10-5.11, there will be a way some how to access the API

so 5.8 could be a development environment until 5.10-5.11 a way is found...

**Comment by audoban** [comment]
Well then I will add support from now, for VisibilityManager and DockConfigView.

**Comment by psifidotos** [comment]
+1 +1 +1

that would be magic if it happens....

**Comment by psifidotos** [comment]
@audoban I dont think this should hold back the v0.6.0 release... Latte is very stable already we should give it to the users and get feedback...

**Comment by audoban** [comment]
The release 0.6.0 it will be as we agreed.

**Comment by psifidotos** [comment]
Trying to inform around the wayland case for docks I created this: https://www.reddit.com/r/kde/comments/668yul/common_developer_forum_for_docks_wayland_case/

Good news by reading the comments are that kde devs responded that we can use the same interface plasmashell uses and of course that also means that they accept the use case!!! :-)

Next weeks I will give this a go... ;-)

**Comment by psifidotos** [comment]
**_The motion unfortunately is that wayland case is dead...._**

Kwin developers which have the most merits in the case just responded that the use case is not valid... So my beautiful users...

**_We Can All Forget Latte in Wayland...._**

p.s. disappointment here but at least the things are clear now...

**Comment by psifidotos** [comment]
After some minor debates the discussion that takes place for Latte in wayland with plasma devs...

https://www.mail-archive.com/plasma-devel@kde.org/msg68675.html

The small conclusion is the following... Latte can use the same plasma interface for plasma 5.9, 5.10 and might in the more future also... plasma devs havent concluded around this yet but I am optimistic.

I think that this a good time for us in Latte 0.7 to provide wayland support and in that way prove ourselves a bit.. both from maintaining point of view and as commitment...

@audoban  you might want to read the previous discussion

**Comment by psifidotos** [comment]
If you are following this thread... then you would already know that this was coming!!! :)

wayland painting and positiong for our dock... :) it is inside the **wayland2** branch...

![wayland-positioning2](https://cloud.githubusercontent.com/assets/2216474/25399234/6bb29754-29f7-11e7-9d8d-4c64c11b2885.png)


Known Issues:
- if you add a second dock then the config windows behave very strange afterwards... probaly they are considere xcb instead of wayland... If you use only one dock, e.g. (Default Layout) then you have no prob.
- with plasma 5.9 the experience is a little buggy but the same happens for plasmashell also
- it crashes on clossing the app

except the above it works just fine... :)

**Comment by psifidotos** [comment]
**_Latte Dock in wayland with top and botton docks... ;)_** 

![wayland3](https://cloud.githubusercontent.com/assets/2216474/25442242/32704e30-2aad-11e7-8524-0843af13128a.png)

**Comment by psifidotos** [comment]
@audoban I think that we can finally close this, right??? :) we have a very beautiful Tech Preview for wayland now... :) 

this is our older issue - feature request... :)
