### ISSUE TITLE
google-earth-pro icon does not appears in the dock

### ISSUE THREAD

**Issue by sardus-X** [psifidotos/Latte-Dock#732]
Hi All,
after installing google-earth-pro 7.3 starting the app an "X" icon appears in the dock to the side of google earth icon (Latte dock 0.71). How to fix it?
Thanks in advance for Your help.
p.s. sorry, how to change icon position in the dock?
![google-earth-pro_002](https://user-images.githubusercontent.com/29210004/31574294-be5ea2c0-b0cc-11e7-9ef0-9e9ec889df1f.png)

**Comment by psifidotos** [comment]
Isnt the last icon found in the dock?

**Comment by sardus-X** [comment]
sorry,
dragging the icon from the application menu at the end I was able to make the icon appear (and I had changed the issue title but the title remained the same). However, along with the google earth pro icon when the application starts, another "X" icon (the fourth from the right) is added. it's normal?

**Comment by psifidotos** [comment]
Are you using plasma 5.11 ?

**Comment by sardus-X** [comment]
Yes, on KDE Neon.

**Comment by psifidotos** [comment]
You must wait for 5.11.1 to be released and check if this is valid. Plasma 5.11.0 introduced many issues for launchers on all taskmanagers.

**Comment by psifidotos** [comment]
@sardus-X any update on this ?
