### ISSUE TITLE
Keyboard combo to pop Latte Settings is already taken in KDE+Plasma.

### ISSUE THREAD

**Issue by BobbyBabes** [psifidotos/Latte-Dock#735]
Popping Latte Settings with `Alt+D,Alt+S` doesn't work in KDE+Plasma.
Hitting `Alt+D,Alt+S` pops Plasma's Folder View Settings at Wallpaper.
A key combo that I use often and would be hard to unlearn (when I change it).

**Comment by psifidotos** [comment]
I think that this isnt working even for plasma panels... I need to research it and see if this is possible...

**Comment by BobbyBabes** [comment]
> I think that this isnt working even for plasma panels...
I’m not surprised. Because the `Alt+D,Alt+S` key combo has nothing to do with Plasma panels.

**Comment by psifidotos** [comment]
> I’m not surprised. Because the Alt+D,Alt+S key combo has nothing to do with Plasma panels.

of course it does. Right click on a plasma panel and see the shortcut for its settings

**Comment by BobbyBabes** [comment]
> of course it does. Right click on a plasma panel and see the shortcut for its settings

No it's not.
Check for yourself in KDE's keyboard docs. Just search the page for `Alt+D,Alt+S` (no spaces) here : [https://docs.kde.org/stable5/en/applications/fundamentals/kbd.html](https://docs.kde.org/stable5/en/applications/fundamentals/kbd.html)
You will find `Alt+D,Alt+S | Desktop Settings`.
When I hit `Alt+D,Alt+S` I'm shown the following window (like I said before : `Plasma's Folder View Settings at Wallpaper`) :
![alt d alt s-kde-desktop-settings_20171015_141606](https://user-images.githubusercontent.com/22870070/31584719-a7194600-b1b3-11e7-9167-1da3848beebd.png)

**Comment by psifidotos** [comment]
what is that then by right clicking a plasma panel and going to plasma settings?

![image](https://user-images.githubusercontent.com/2216474/31584755-e1d3de32-b1bc-11e7-9bde-e05173615471.png)

**Comment by BobbyBabes** [comment]
So you're saying that you can't re-associate another keyboard combo with QAction|KAction to replace the hardcoded `Alt+D,Alt+S` (Latte Settings) ?
Similar to this : [https://techbase.kde.org/Development/Tutorials/Using_Actions#Keyboard_Shortcut](https://techbase.kde.org/Development/Tutorials/Using_Actions#Keyboard_Shortcut)
> Keyboard Shortcut
> 
> Setting a keyboard shortcut to perform our action is equally simple:
> 
> actionCollection()->setDefaultShortcut(clearAction, Qt::CTRL + Qt::Key_W);
> This associates Ctrl+W with the QAction.

That's pretty f...ed up.

**Comment by psifidotos** [comment]
we can associate a `Super+S `but not `Super+S+D ` two characters that is... you can check it Global Shortcuts associations at plasma settings... 

So we can find a shortcut but we must also make an assumption, this shortcut what will trigger in the case Latte contains more than 1 docks? The most logical from implementation sided etc... is the first dock containing a taskmanager starting from the primary screen.

**Comment by BobbyBabes** [comment]
You got me there. I forgot about that more than 1 dock is a possibility.
But wouldn't that pose the same limitation for `Alt+D,Alt+S` ?

**Comment by psifidotos** [comment]
I dont know how plasma chooses to show Desktop Settings when it's a multiple-screen environment

**Comment by BobbyBabes** [comment]
Neither do I, I'm afraid.
At the moment I can't think of any program in a similar scenario either. To look at its handling.

**Comment by psifidotos** [comment]
@BobbyBabes  at first I am going to disable that shortcut in order to now confuse the user, and I think I can add a way to be set and triggered through plasma systemsettings like the other latte shortcuts...

one question I have is if this will lead to support key-navigation in Latte settings but I think this isnt possible because it is a window that doesnt accept focus

**Comment by BobbyBabes** [comment]
@psifidotos That is probably for the better. If Plasma doesn’t allow the link to do anything, it shouldn’t have added it in the first place.

If the window doesn’t allow focus, then you have your hands tied.
The fact that I get the Wallpaper settings (with Alt+D,Alt+S) confirms what you’re saying about focus. Because that means that the desktop still has focus. Also when I right-click Latte Dock to get the pop up menu, and then hit Alt+D,Alt+S, nothing happens. Plasma seems broken with this feature.

**Comment by psifidotos** [comment]
--the default shortcut is Meta+A but the user can
change it to whatever wants to from plasma systemsettings.
--the settings windows are shown based on priority.
Primary screen docks have higher priority and for the
edges the priority is: Bottom,Left,Top,Right

**Comment by psifidotos** [comment]
@BobbyBabes ok ... I managed to support key focus in settings window... as a start the user can use Esc to close it and arrows to navigate between settings tabs

**Comment by psifidotos** [comment]
ok fixed also the navigation in settings window...

```
Meta+A : open config window
Esc: closes the config window
Left, Right: navigate to config window tabs
Tab: select option forward in a tab
Shift+Tab: select option backward in a tab
```

**Comment by BobbyBabes** [comment]
@psifidotos I’ll check it out when I install Latte Dock again in the future.
