### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#74]
is necessary a secon setting form for latte-plasmoid it seems very similar

**Comment by psifidotos** [comment]
meaning ?

**Comment by JenaPlinsky** [comment]
I thought, that latte-dock and latte-plasmoid were setting the unified forms, I suppose that they serve for different purposes

**Comment by psifidotos** [comment]
this is already taken care....  a unified settings window exist when a latte plasmoid is inside the dock and when the latte plasmoid in not inside the dock e.g. desktop it has its own configuration window...

**Comment by JenaPlinsky** [comment]
![screenshot_20170122_223749](https://cloud.githubusercontent.com/assets/24593950/22186292/b5f39c8e-e0f3-11e6-932f-cb4f5a5eae5d.png)
![screenshot_20170122_223837](https://cloud.githubusercontent.com/assets/24593950/22186293/b81c1b1c-e0f3-11e6-8d57-bc4e0cdfa90d.png)

**Comment by psifidotos** [comment]
Oh you are right!!! I had fotgot that button!!! That button should also show the dock's configuration window and not the plasmoid one...
