### ISSUE TITLE
Widgets seem strange on Latte panel after KDE suspension and KWin crash

### ISSUE THREAD

**Issue by omtcyfz** [psifidotos/Latte-Dock#741]
I reported a [bug](https://bugs.kde.org/show_bug.cgi?id=386033) about KWin graphics reset after resuming from suspension and this is how Latte Looks like after the graphics reset:

![bug report latte](https://user-images.githubusercontent.com/3352968/31853988-e2a4d608-b69a-11e7-83ca-8e63e237c191.png)

I have to hover over the applications icons to make them look normal again and I have to press the widgets' icons (e.g. Application Launcher/Clock/Tray) to make everything look normal again.

Would be nice to have panel reload normally after the graphics reset, not entirely sure whether it is within the scope of the Latte project or a Plasma bug too, though.

**Comment by psifidotos** [comment]
this is a graphics driver issue nothing related to Latte...

are you using proprietary NVidia ?

**Comment by omtcyfz** [comment]
@psifidotos Yes, I am. Sorry, forgot to mention the specs -_- It's Arch Linux, Plasma 5.11.1, Nvidia proprietary drivers.

Do you know whether progress on this issue is tracked anywhere?

**Comment by psifidotos** [comment]
no idea, if you search about "linux nvidia artifacts after suspend" you will find many threads mentioning the issue
