### ISSUE TITLE
Background is shown when it shouldn't under 'show background only for maximized windows'

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#742]
I have the option `show background only for maximized windows` enabled but still background is shown, without any maximized window, when focus is on an applet inside latte-dock (using version 0.7.1 in KDE neon User Edition)

**Comment by psifidotos** [comment]
@kupiqu this is an X11 limitation you have enabled previews for all windows even those minimized. Only way for this to work is from plasma systemsettings to enable previews only for shown windows

**Comment by kupiqu** [comment]
Could you please remind me where the setting in systemsettings is (if you recall)? I remember seeing it but getting crazy now trying to find it :/

**Comment by psifidotos** [comment]
at Monitor -> Compositor

**Comment by kupiqu** [comment]
Yes, there it is, thank you!

However, my current setting there is "previews only for shown windows" :/

**Comment by psifidotos** [comment]
> when focus is on an applet inside latte-dock

can you make a screenshot? There is a chance this is the default behavior in order to show correctly the popups

**Comment by kupiqu** [comment]
Yes, it must be that. 

Compare:

![image](https://user-images.githubusercontent.com/3875196/31861355-b7e643c0-b6f9-11e7-9b8a-539c179f3d75.png)

with:

![image](https://user-images.githubusercontent.com/3875196/31861682-7c25669e-b6ff-11e7-8fb2-e14d9b1d7e5b.png)

Unfortunately this side of the wallpaper is also dark. I can change it to make this more salient if you want...

**Comment by psifidotos** [comment]
dont have to... this is Latte behavior, when an applet shows its popup for consistency with the plasma theme Latte is showing its background...

e.g.
![image](https://user-images.githubusercontent.com/2216474/31863452-6147d29c-b756-11e7-933f-24abcd3107a3.png)

**Comment by kupiqu** [comment]
I guess it's not possible to have a(n arguably) consistent behavior making transparent popups when background in latte-dock is not shown, right?

**Comment by psifidotos** [comment]
> I guess it's not possible to have a(n arguably) consistent behavior making transparent popups when background in latte-dock is not shown, right?

unfortunately not... this is handled from plasma theme and kwin entirely....

**Comment by kupiqu** [comment]
Ok, thank you :)
