### ISSUE TITLE
Applets, but not tasks, show two lines instead of one

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#743]
Please see screenshots (with the two opposite sides for lines and dots):

![image](https://user-images.githubusercontent.com/3875196/31861355-b7e643c0-b6f9-11e7-9b8a-539c179f3d75.png)

![image](https://user-images.githubusercontent.com/3875196/31861356-d12db5de-b6f9-11e7-927f-64c47899c3f0.png)

Edit: Using latte-dock 0.7.1 in KDE neon User Edition

**Comment by psifidotos** [comment]
one line is from the theme so you have the following solutions:

1. edit your theme in order to not show that line
**or**
2. Enable from Tweaks -> Active Applet Indicator -> Internal
this wont show you two lines but there is a chance that they are different from your theme

**Comment by kupiqu** [comment]
Awesome! I didn't know this setting was about this...

Thank you!

**Comment by psifidotos** [comment]
@kupiqu yeah, you are the first noticing it... ;)

this is setting is for the following:
**None:** Latte doesnt draw any line for the active applet
**Internal:** Latte is drawing a line for the active applet in case the applet is drawn from Latte so the theme line is not appearing
**Everywhere:** Latte is drawing a line for the active applet at all cases, this provides uniformity everywhere but the theme must disable its drawing. (if i remember correctly this was found at theme file. `widgets/tasks.svg` ). You can test it how it would look by trying the BreezeDark theme that doesnt draw a line on its own.

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks#q-how-to-provide-uniformity-for-active-applets-same-active-line-across-all-my-docks-with-latte-07

**Comment by psifidotos** [comment]
![](https://thumbs.gfycat.com/BlindDirtyLeafcutterant-size_restricted.gif)
![](https://thumbs.gfycat.com/LeftGiganticDaddylonglegs-size_restricted.gif)

**Comment by kupiqu** [comment]
Using it! 

Thanks :)
