### ISSUE TITLE
Change 'Always hide' and 'Auto hide' mode names.

### ISSUE THREAD

**Issue by migs911** [psifidotos/Latte-Dock#744]
'Always hide' - in this mode dock is visible when there is no windows overlapping th dock. It should be called ' Auto hide' or 'Smart hide'
'Auto hide' - in this mode dock is always hide except the moment when mouse near it. So it should be called 'Always hide'.
It will be better to change naming of this modes. 
Always hide <==> Auto hide

**Comment by psifidotos** [comment]
There is no such mode... What language are you using? probably a faulse translation
