### ISSUE TITLE
version 0.6.2/latest version (downloaded via git then compiled): Enabling autostart option doesn't get saved

### ISSUE THREAD

**Issue by mrjayviper** [psifidotos/Latte-Dock#745]
using Latte Dock and KDE Neon (using current stable KDE 5.11.x with Ubuntu 16.04 as base)

1st test: so I enabled autostart. I quit latte dock and open it again and when I checked on the settings, it's again disabled.

2nd test: I enabled autostart and then restart my laptop. Latte dock didn't start and when I check on the settings, autostart is disabled again.

3rd test: I opened settings. Enabled autostart. Close settings and when I opened settings again, it's disabled again.

4th test: I downloaded the latest version via git and then compiled it. I then repeated tests 1 to 3 and I get the same issue.

**Comment by trmdi** [comment]
Why don't you use the latest version 0.7.1 ?

**Comment by mrjayviper** [comment]
where can I find a package for xenial for 0.7.x? :)

All I've seen (rikmills) are 0.6.2 for xenial.

**Comment by psifidotos** [comment]
I dont know if we can manage a 0.6.3 version in order to fix this. 

If you want to do it manually you can do the following:

- copy file` /usr/share/applications/latte-dock.desktop` to folder `~/.config/autostart/`
