### ISSUE TITLE
Manjaro update with Plasma 5.11.2-1 killed latte :(

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#747]
Basically, latte loads with some lag and then crashes, reloads automatically for few seconds and it crashes again, sometimes holds up for 10-15s but then crashes again and so on, without end. Clicking on any launch icon crashes it immediately, but I can still open latte options and system tray options with right-click.

Error log shows of course "segmentation fault" that says little.

Will be experimenting with configs.

**Comment by psifidotos** [comment]
it has been fixed through #730 .. the fix will arrive through 0.7.2 version or by usring AUR Latte git version...

**Comment by michaldybczak** [comment]
Ah, thanks. Installing it then :). That was incredibly quick response :).
