### ISSUE TITLE
desktop icon position issue with lattle dock:

### ISSUE THREAD

**Issue by laltroweb** [psifidotos/Latte-Dock#748]
all work as expected in my debian testing with kde, but when i make a new icon in desktop, i see this issue with position (installed from latest ubuntu deb).

![screenshot_20171028_194512](https://user-images.githubusercontent.com/16841896/32137050-1857a09a-bc19-11e7-8384-c6b0808d2404.png)

regards,
S.N.

**Comment by psifidotos** [comment]
unfortunately Latte can not configure the available size of the desktop. That is a plasma request-feature which is not available right now...
