### ISSUE TITLE
Widget crashes desktop

### ISSUE THREAD

**Issue by alpvonkri** [psifidotos/Latte-Dock#749]
The plasma widget crashes the plasma desktop whenever the mouse cursor pass over it.
How to disable/remove (without uninstalling) it?
Note: Using openSUSE repository version. Only widget, app works fine.

**Comment by trmdi** [comment]
Use the latest version on OBS: https://build.opensuse.org/package/show/home%3Atrmdi/latte-dock

**Comment by alpvonkri** [comment]
That one is only for Tumbleweed, I'm using Leap, so Plasma and QT versions differ.

**Comment by alpvonkri** [comment]
Ok, the "Force Widget Removal Without Uninstalling" part was solved editing: `~/.config/plasma-org.kde.plasma.desktop-appletsrc`
But I'm still unable to use the Widget, the app kind of work better for me, but still I see it as some kind of issue.

**Comment by psifidotos** [comment]
What plasma and Latte versiin?

**Comment by trmdi** [comment]
@psifidotos 
openSUSE Leap 42 has Plasma 5.8.x and Qt 5.6.x
I don't know if Latte 0.7.1 could run with those.

**Comment by psifidotos** [comment]
Please give me more info and screenshots to understand what is happening...

This was happening from start or after an update at Leap?

**Comment by alpvonkri** [comment]
System: ![image](https://user-images.githubusercontent.com/104341/32146778-7bc6c82a-bca2-11e7-99a0-feca0908cdd3.png)
Latte-Dock Source: ![image](https://user-images.githubusercontent.com/104341/32146786-95754558-bca2-11e7-9cbe-f0d575170249.png)
Latte-Dock Version: 
![image](https://user-images.githubusercontent.com/104341/32146814-f233f564-bca2-11e7-9069-85f470dda2ad.png)

Was working fine, but after a KDE update it started to crash the plasma desktop.
The widget works and show information, but when the mouse cursor passes over it, it restarts Plasmashell.

Working widget: 
![image](https://user-images.githubusercontent.com/104341/32146910-f995b53a-bca3-11e7-9d8e-98116ad2c8d3.png)

After the cursor pass over the widget, plasmashell is restarted: 
![image](https://user-images.githubusercontent.com/104341/32146945-6774b268-bca4-11e7-80a2-2c90b1e1bd0e.png)
![image](https://user-images.githubusercontent.com/104341/32146953-808b692c-bca4-11e7-80b6-8d174a8e49da.png)

**Comment by psifidotos** [comment]
You are using plasma 5.11 so you need Latte 0.7.1 with the patch  that fixes this...

Latte 0.6 is proposed only for plasma=5.8 version

The crash occurs from qt 5.9.2

**Comment by psifidotos** [comment]
@trmdi I suppose the user is using Leap but has installed plasma 5.11 from KDE:/Frameworks repo, right?

**Comment by alpvonkri** [comment]
I suppose you may be right, but the audoban repository for KDE Frameworks5 has 0.6.2 version, so if it was fixed, maybe just updating your KDE Frameworks5 repository to versión 0.7.1 will do the magic. 👍

**Comment by psifidotos** [comment]
@audoban can you update this?

**Comment by trmdi** [comment]
I think you can install the rpm from my repo posted above.

**Comment by psifidotos** [comment]
I have created also packages for Leap  **in case you are using the KDE:/Frameworks5 repo** that include the needed patch.

[openSUSE Leap 42.2](https://download.opensuse.org/repositories/home:/psifidotos/KDE_Frameworks5_openSUSE_42.2/x86_64/latte-dock-0.7.1-3.1.x86_64.rpm)
[openSUSE Leap 42.3](https://download.opensuse.org/repositories/home:/psifidotos/KDE_Frameworks5_openSUSE_Leap_42.3/x86_64/latte-dock-0.7.1-3.1.x86_64.rpm)

or you can add my repo:
- [home:/psifidotos for openSUSE 42.2](http://download.opensuse.org/repositories/home:/psifidotos/KDE_Frameworks5_openSUSE_42.2/)
-  [home:/psifidotos for openSUSE 42.3](http://download.opensuse.org/repositories/home:/psifidotos/KDE_Frameworks5_openSUSE_Leap_42.3/)

in Yast to install it from your package manager and have updates also is the future...

**Comment by trmdi** [comment]
@psifidotos Thank you for the OBS repo. Please add it to README.md

**Comment by alpvonkri** [comment]
@psifidotos Thanks, I will. 👍
