### ISSUE TITLE
Question(s) -- Not Issue(s) 

### ISSUE THREAD

**Issue by KClickster** [psifidotos/Latte-Dock#750]
First off, I want to say this is a great dock and thank you for your work. Donation is coming.

I am currently using the dock on Arch Linux with KDE Plasma 5.11.2

Question 1: Is there a way to change the color of the glowing bar that is to the left of the active app? It is Orange by default. I couldn't find how to change that color - am I missing it somewhere in settings?

Question 2: Is there a way to make it so that if a program is launched by any other method that is NOT from the Latte Dock that the task DOESN'T appear in the Latte Dock? For example: I open Terminal using my KDE Application Launcher and then 'Favorites.' Can the Terminal task itself NOT show up in my Latte Dock? I'd rather no tasks show there and just keep it as an Application Launcher. Please let me know if there is a way I can set that up.

Thanks for your time and help.
Clickster

**Comment by psifidotos** [comment]
thank you

Question1: please show me a screenshot to understand which color that is

Question 2: if you dont mind losing the bouncing animation and activating the open windows  through Latte you can do the following. Remove the Latte plasmoid totally from the dock and afterwards add your app launchers through drag n drop. They will be added as applets.

**Comment by KClickster** [comment]
Question 1:
https://i.imgur.com/5OhGBSv.png
The Orange next to the Firefox logo.

Question 2:
I'm unsure completely what you mean - how would I go about doing that?

Thanks.

**Comment by psifidotos** [comment]
Q1: this is set through your plasma theme I dont know if this can be changed through plasma colors I will look into it. The color palette from the theme is called Complementary

Q2: 
1. Readd the clock in the dock from plasma widgets explorer
2. Afterwards go to advanced options Tweaks-> Remove Tasks plasmoid
3. Drag n drop any app you want on the dock
4. Remove the clock now if you want

**Comment by psifidotos** [comment]
Q1: I checked it, this cant be altered through plasma systemsettings. Only way is through accessing file `colors` of your plasma theme and changing that option e.g. : 

```
[Colors:Complementary]
...
DecorationFocus=30,146,255
...
```

**Comment by KClickster** [comment]
Thanks!
