### ISSUE TITLE
Latte uses low-res icons, looks very ugly

### ISSUE THREAD

**Issue by UralZima** [psifidotos/Latte-Dock#751]
Hi. I am moving from Icon-Only task manager. I use latest version 0.7.1.
Most icons appear very ugly. If I pin some icons, they looks much better, it seems use another icons from .desktop file. If app is not pinned and latte is loaded having open windows, icons are very ugly.

Icon-Only task manager didn't had this issue

**Comment by psifidotos** [comment]
> Icon-Only task manager didn't had this issue

Latte is using the same plasma libtaskmanager and doesnt change the icons provided by it... so this isnt the case...

icon size that you are using? a screenshot to compare with icon-only taskmanager?
