### ISSUE TITLE
How to install libqt5-qtx11extras-devel ?

### ISSUE THREAD

**Issue by subhanjan21** [psifidotos/Latte-Dock#755]

**Comment by psifidotos** [comment]
what do you mean? in what distro?

**Comment by subhanjan21** [comment]
In ubuntu 16.04
I have a problem while installing paraview due to this. It says I do not have these packages.

**Comment by psifidotos** [comment]
in ubuntu it is called `libqt5x11extras5-dev`

maybe you should try to install the Kubuntu, Neon dependencies as referenced at file:
https://github.com/psifidotos/Latte-Dock/blob/master/INSTALLATION.md

**Comment by subhanjan21** [comment]
Add the installation prefix of "Qt5Help" to CMAKE_PREFIX_PATH or set
   "Qt5Help_DIR" to a directory containing one of the above files.  If
   "Qt5Help" provides a separate development package or SDK, be sure it has
   been installed.

How do I do this ?
