### ISSUE TITLE
Background does not disappear when I minimize a maximized window

### ISSUE THREAD

**Issue by ZeppLu** [psifidotos/Latte-Dock#756]
Sorry my English is poor, the title may be quite difficult to understand. Here is how to reproduce the bug:

1. Create a dock, and place it at the top.
3. Enable `Show background only for maximized windows` in tweaks section.
4. Maximize a window, now dock's background appear.
5. Minimize the window, but dock's background remains there.

**Comment by psifidotos** [comment]
X11 limitation, you have enabled previews for all windows! You must change it to previews for only shown windows

**Comment by ZeppLu** [comment]
Works like a charm! Thanks.
