### ISSUE TITLE
SDL Visual Issues

### ISSUE THREAD

**Issue by MggMuggins** [psifidotos/Latte-Dock#757]
I don't know if this is a problem with KDE itself or Just Latte (I am lead to believe that it's Latte, since a search for visual issues with KDE and SDL didn't turn up much), but when running an SDL app, it breaks the appearance of the panels (specifically the borders and transparency). Here's a shot of my setup without  an SDL app running:
![cleandesktop](https://user-images.githubusercontent.com/16041213/32625539-11980ec4-c552-11e7-89f6-2f1b2168cf17.png)
And here with an SDL app:
![sdlapp](https://user-images.githubusercontent.com/16041213/32625804-e1ffe76c-c552-11e7-8bc0-4f62891b1121.png)
This happens all the while the app is running. KDE Animations like the "genie" effect don't work while the app is running, on any window. It almost appears as though it breaks Kwin compositing, since (even though the pictures don't show it), the titlebars shown while SDL is running don't have rounded corners like they usually do.

It's possible that it's an implementation issue with the library I'm using based on SDL, however, I don't think so, because based on the limited views of my desktop when 0AD is running, it does the same thing. If you need more info or testing, don't hesitate to ask, I'm happy to help debug this issue.

**Comment by psifidotos** [comment]
This is nothing related to Latte and it isnt an issue also... SDL and some games e.g. Steam games disable kwin-x11 compositing when running in order to improve performance.

If you dont want that you can go to plasma systemsettings, monitor, composer

and disable the option to allow apps disabling compositing
