### ISSUE TITLE
Change Applets To Any Size

### ISSUE THREAD

**Issue by nheolinkin** [psifidotos/Latte-Dock#758]
As I see in the 0.7.2 version of Latte Dock, the size of applets is able to be changed only between 16, 24, 32... (+8).
Is there anyway that I can change applets to any size I want? A way that I've not known yet?

It  would be great if "Applets Size" feature can be modify to any size like "16, 17, 18 .....". So it could fit the way everyone wants.

**Comment by trmdi** [comment]
Latte setting > Tweak > Behavior > Uncheck `Disable applets size when it is needed` then resize again.

**Comment by psifidotos** [comment]
@nheolinkin just dont complain about blur in icons in such sizes... nothing can be done about it...
