### ISSUE TITLE
How do I do this ?

### ISSUE THREAD

**Issue by subhanjan21** [psifidotos/Latte-Dock#759]
Could not find a package configuration file provided by "Qt5Help" with any
of the following names:
Qt5HelpConfig.cmake
qt5help-config.cmake

Add the installation prefix of "Qt5Help" to CMAKE_PREFIX_PATH or set
"Qt5Help_DIR" to a directory containing one of the above files. If
"Qt5Help" provides a separate development package or SDK, be sure it has
been installed.

How do I do this ?

**Comment by psifidotos** [comment]
No idea...

 I think it is better to ask at your distro help channels... forums, irc etc...
