### ISSUE TITLE
Latte should not allow removing all dock.

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#76]
1. open the config ui and add a dock.
2. remove the current dock.
3. Opens the configuration window of the second dock, and you will see that the remove button is enabled.
4. Remove the dock.

**Comment by psifidotos** [comment]
This is relevant to how time frameworks need in order to delete a containment or a plasmoid. I suppose this is the reason in plasma workspace codepage exist a list of waiting panels

**Comment by psifidotos** [comment]
the remove dock action could move the panel from dockViews to waitingDockViews and really delete it when the containment is deleted. This would solve the issue directly because the configuration window already counts the docks that are running

**Comment by psifidotos** [comment]
let me take up this

**Comment by psifidotos** [comment]
I tested this a lot and it's clean with no crashes. Adding removing docks, undoing their removal and everything is in sync... 

Should I merge?

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/commit/1518c6899780c3ad53f16b9c5e934aedd1008590

**Comment by audoban** [comment]
But I was fixing it on my local branch.

Well, your commit also fixed the issue, but there is something that worries me, the method docksCount give the total of docks of all screens, this means that I can not add more than 4 docks. However I doubt very much that someone wants to use more than 4 docks.

**Comment by audoban** [comment]
> Should I merge? 

👍

**Comment by psifidotos** [comment]
> But I was fixing it on my local branch.

sorry... wrong communication from my side... were you implementing it differently? would you like to change it?

> the method docksCount give the total of docks of all screens, this means that I can not add more than 4 docks. However I doubt very much that someone wants to use more than 4 docks.

I will add a tag for this and for freeEdges also in order to update them when the infrastructure for multi-screens is in place

**Comment by audoban** [comment]
Our implementations are very similar. but I change the signature of docksCount

```
int DockCorona::docksCount(int screen) const 
{ 
    return m_dockViews.size(); 
    if (screen == -1) 
        return 0; 
     
    int docks{0}; 
     
    for(const auto &view : m_dockViews) { 
        if (view && view->containment()  
                && view->containment()->screen() == screen  
                && !view->containment()->destroyed()) 
        { 
            ++docks; 
        } 
    } 
     
    qDebug() << docks << "docks on screen:" << screen; 
     
    return docks; 
} 
```

on DockView
```
int DockView::docksCount() const
{
    auto dockCorona = qobject_cast<DockCorona *>(corona());
    
    if (!dockCorona || !containment())
        return 0;
    
    return dockCorona->docksCount(containment()->screen());
}
```

**Comment by audoban** [comment]
> sorry... wrong communication from my side... were you implementing it differently? would you like to change it?

Don't worry.

**Comment by psifidotos** [comment]
I replaced also with your implementation...

**Comment by audoban** [comment]
ok
