### ISSUE TITLE
[master] - "Force solid background for maximized windows" doesn't work

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#760]
I suspect that option was to satisfy my need of having a semi-transparent panel but solid in window maximized state. So far, this option does nothing. I have installed AUR git version and updated it yesterday. played around, all works well, aside that one tweak.

Isn't it working just for me or is this option meant for future version and thus not effective yet?

If needed, I may record a vid how it works or rather doesn't work for me.

**Comment by psifidotos** [comment]
give me a screenshot of your top dock that you want that behavior.
The feature is implemented and works fine at my computer but there is a chance that you need adjust a bit the kwin effects settings...

**Comment by psifidotos** [comment]
yeah... you are right, I hadnt enabled the kwin effects to provide the best contrast...

**Comment by michaldybczak** [comment]
Here is the video how it looks for me right now. Screenshots wouldn't be too informative.

https://youtu.be/N6-jVUwDjvM

I will delete this video after some time.

**Comment by psifidotos** [comment]
is fixed, I suppose that some days are needed for the AUR git version to update...
as long as you have enabled the blur and background contrast kwin effects in plasma system settings then Latte will apply them automatically when there is a maximized window...

the see what the result would be, it will be equivalent with 100% opacity and blur enabled from Tweaks page.

**Comment by psifidotos** [comment]
ok... and one more patch for this... you can have the solid background when using the "Fprce solid panel for maximized" and enable its transparency also for when there isnt a maximized window... so the level of customazibility now is enormous for that option...

**Comment by michaldybczak** [comment]
As far I understand AUR git versions, as soon as you made any changes (commits), we can update it to the newest version, although AUR shows old version (which must be changed manually and it's done once in a while, but not so often as commits).

Anyway, I updated package and see no difference so far. Maybe I understand it wrong? Will check in a week if something has changed.

**Comment by psifidotos** [comment]
dont know how long it takes to AUR-git version to update its package... I suppose when you see at your software manager an update for latte-dock-git

**Comment by michaldybczak** [comment]
From what I understood, AUR git version simply downloads current github version and installs it, so it should be right away. I may be wrong thou.

**Comment by psifidotos** [comment]
it might be a matter of hours, you could ask at Arch forums

**Comment by michaldybczak** [comment]
I checked PKGBUILD and as source is:
https://cgit.kde.org/latte-dock.git/
And the latest change there is 3 hours ago with commit:
https://cgit.kde.org/latte-dock.git/commit/?id=e7352e1c9d909facae739d373a56cc18cf8e223d

It's up to you to recognize is that the most recent or older version than the one from github.

**Comment by psifidotos** [comment]
at link : https://cgit.kde.org/latte-dock.git/
choose master branch, not v0.7, if you were using v0.7 branch then you wouldnt have that option...

**Comment by michaldybczak** [comment]
OK, I see a recent change now:
https://cgit.kde.org/latte-dock.git/commit/?id=f22d5c85b29bfab667c11b10dc9b34ca83d980c4

Will compile and test it again.

**Comment by michaldybczak** [comment]
OK, now it works! :)
Meaning, I can set semi-transparent light panel (for darker wallpapers) and yet still have solid background in maximized state.

Now, wallpapers finally don't limit my settings and I can set anything I want! Sweet! Thanks! :D

**Comment by psifidotos** [comment]
nice to hear! ;) I will enjoy your screenshots or videos... :)
