### ISSUE TITLE
Manage the background height for the maximized windows

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#762]
You might think adding an option to maximize the background height for the maximized windows
Maybe somebody might be interested
![screenshot_20171112_223934](https://user-images.githubusercontent.com/24593950/32703732-6ed89522-c7fa-11e7-9b95-f5552dff6f48.png)

![screenshot_20171112_224140](https://user-images.githubusercontent.com/24593950/32703750-b1532aa2-c7fa-11e7-9c4f-0cc9b74535d7.png)

**Comment by psifidotos** [comment]
sorry, I dont get it... what is the benefit of this?

**Comment by JenaPlinsky** [comment]
it's just a matter of personal taste, since the options available are already satisfying enough to give more emphasis to the dock's icons than anything else in the background.
 
my thoughts that I had until some time ago was to have, for maximized windows, a transparent and blurred maximized background and otherwise, when no maximized window is present, keep the background reduced to its minimum height

now as I am, I'm fine with the ever-blurred and minimized background and for maximized windows I use the "force solid background ...." option

So again, it's just a matter of personal tastes

**Comment by psifidotos** [comment]
sorry, no interest in adding it
