### ISSUE TITLE
how to change expanded active windows indicator to dot ?

### ISSUE THREAD

**Issue by unc926** [psifidotos/Latte-Dock#763]
hi,
I want to change the expanded active window indicator.
look everywhere, including in advanced settings. not found an option for this.
how can i change it? or will there be an update about it?
![new project](https://user-images.githubusercontent.com/30185386/32704387-3925bc28-c815-11e7-8282-98efba74d0b6.png)

**Comment by psifidotos** [comment]
you mean you dont want the line for the active window ?

how would you distinguish windows then? 1.active, 2.shown but not active, 3.minimized?

**Comment by unc926** [comment]
I want the dot to appear instead of the line.
3 different colors can be used to distinguish 
sample: active (blue) , inactive (white) , minimize (darkgrey)

**Comment by psifidotos** [comment]
The colors are based only on the plasma theme palette

**Comment by psifidotos** [comment]
I will think it over if it is feasible... an attempt for this in the past didnt find three colors from plasma theme palette that can play nice these three roles... it was too much coloring...

**Comment by unc926** [comment]
thick line: it looks very bad on small screens! 
try
![new project](https://user-images.githubusercontent.com/30185386/32725183-2c4352c0-c885-11e7-9646-6035321abe11.png)

**Comment by psifidotos** [comment]
looks interesting...

you have added a border to your circles in order to look nice with the glow...

hm...

**Comment by psifidotos** [comment]
> thick line: it looks very bad on small screens!

can you show me a screenshot for this ?

**Comment by unc926** [comment]
sort by: minimize, inactive, active

![screenshot_20171113_164500](https://user-images.githubusercontent.com/30185386/32729228-1d3ead4c-c894-11e7-967f-306069837b16.png)

**Comment by psifidotos** [comment]
![screenshot_20171113_164500](https://user-images.githubusercontent.com/30185386/32729228-1d3ead4c-c894-11e7-967f-306069837b16.png)

@unc926 I dont like it... can you show me how the active line looks at small resolution screens?

**Comment by unc926** [comment]
here
![screenshot_20171113_210217](https://user-images.githubusercontent.com/30185386/32741314-e5290a2e-c8b6-11e7-82ab-4293e0a0b21e.png)

fine look only dot 

![screenshot_20171113_205947](https://user-images.githubusercontent.com/30185386/32741391-281c9382-c8b7-11e7-84be-215cb87e6380.png)

**Comment by psifidotos** [comment]
playing with it... in a fast design approach... the following are real screenshots...

![image](https://user-images.githubusercontent.com/2216474/32917702-bad68b42-cb28-11e7-8fab-14c878c914a1.png)

![image](https://user-images.githubusercontent.com/2216474/32917725-cae0aaf4-cb28-11e7-995a-271f55d13486.png)

![image](https://user-images.githubusercontent.com/2216474/32917776-ea1f553c-cb28-11e7-8286-1019e085f8c2.png)

**Comment by unc926** [comment]
@psifidotos it looks much better now .

**Comment by psifidotos** [comment]
> it looks much better now .

a matter of user choice... I personally prefer  the active line...

either way in order to add thisc some new adjustments need to be made in the code and I need also to find a way to support this beautiful glow for the line also... 

one step at a time...

**Comment by unc926** [comment]
@psifidotos 
I understand. you're right. I mentioned earlier that the thick lines are very bad on small screens.
this is just a suggestion, if you think it is possible you should definitely add it to the latte dock.

you can also remove the stroke on the edge of the dot. if there is a problem.

**Comment by psifidotos** [comment]
ok... we have a new glow I think but I will need to play with it a bit more... ;) is animated correctly etc...

![image](https://user-images.githubusercontent.com/2216474/32959951-e5858a66-cbcb-11e7-8057-5de6446ecb42.png)

**Comment by psifidotos** [comment]
yep.... this one I like...

![image](https://user-images.githubusercontent.com/2216474/32960926-5f3f8354-cbcf-11e7-955b-d3f9ac94c2d6.png)

![image](https://user-images.githubusercontent.com/2216474/32960965-7b42f144-cbcf-11e7-9a42-cc90710842df.png)

**Comment by unc926** [comment]
it could be in the following way. you can make it look nicer by narrowing the line
active,inactive,minimize

![screenshot_20171117_234628](https://user-images.githubusercontent.com/30185386/32968312-dc53f83a-cbf1-11e7-970a-876d4a0db995.png)

**Comment by psifidotos** [comment]
> it could be in the following way. you can make it look nicer by narrowing the line

I dont like it... 

what will be supported is this case:

![image](https://user-images.githubusercontent.com/2216474/32960965-7b42f144-cbcf-11e7-9a42-cc90710842df.png)

and that case, but with the above improved glow which is also your feature request:

![image](https://user-images.githubusercontent.com/2216474/32917725-cae0aaf4-cb28-11e7-995a-271f55d13486.png)

**Comment by unc926** [comment]
@psifidotos  do not want the lights or the stroke effect. just use dot instead of line or shorten line.
I will definitely choose the "dot" style if a choice is made.
If you do not want to change the line, you have to narrow it short. the last picture I sent can help you.
it is actually very simple, hard to tell with my bad english really.

**Comment by psifidotos** [comment]
> @psifidotos do not want the lights or the stroke effect. just use dot instead of line or shorten line.
I will definitely choose the "dot" style if a choice is made. If you do not want to change the line, you have to narrow it short. the last picture I sent can help you. it is actually very simple, hard to tell with my bad english really.sorry wont happen

sorry wont happen

**Comment by psifidotos** [comment]
ok... works really nice... the Glow options moved to Appearance page (advanced). The user can choose the following:
- Enable/Disable Glow
- Enable Glow to All Indicators
- Enable Glow only for the active task and at the same time disable the active line
- Alter the Glow opacity
- Enable/Disable the 3D Glow style by not painting on the dot anything

![image](https://user-images.githubusercontent.com/2216474/32978855-f832f39c-cc52-11e7-8ba2-85d1085661b3.png)

@unc926 I cant improve it more... it is goog enough for me...

**Comment by psifidotos** [comment]
glow only on active, glow opacity:35%, no 3d

https://gfycat.com/gifs/detail/SoulfulRectangularFowl

**Comment by unc926** [comment]
@psifidotos looks good, it was i tell you exactly this .

**Comment by psifidotos** [comment]
all these new features have been added in master...

the user can use a line or a dot for its active tasks/applets from the Tweak page
the settings for the glow can be found at Appearance page...

**Comment by unc926** [comment]
I install it to try.  great. Good job

**Comment by aislanmaia** [comment]
Is there a way to change completely the indicator? I want to change the indicator to background style of [Unity bar](http://1.bp.blogspot.com/-qX6dkQNK7ZY/UjMMAD4OmyI/AAAAAAAAIa0/XHR3-1M8K_c/s1600/a_better_ubuntu_unity_launcher___part_ii__updated__by_rylexr-d5u51np.png)

**Comment by psifidotos** [comment]
no this isnt possible...

only by providing your own plasma theme and using the icon-only taskmanager. And I dont know all the parts of the referenced designs can be achieved.

**Comment by aislanmaia** [comment]
So does icon-only taskmanager can be used in latte-dock, or they're mutually exclusive?

**Comment by psifidotos** [comment]
Yes it can but without the parabolic effect...

1. Disable from Tweaks page the Automatic applet shrinking when it is needed
2. Remove the Latte Tasks plasmoid from Tweaks page 
3. Enable the Justify alignment
4. Set zoom to 0% from Appearance page
5. Drag n' drop any plasma taskmanager you want onto Latte dock

**Comment by psifidotos** [comment]
plasma icon-only taskmanager (both are Latte docks)
![default](https://user-images.githubusercontent.com/2216474/33183069-0d141aa4-d07f-11e7-80c9-4b7d997af808.png)

(plasma classic taskmanager in Latte Dock)
![default](https://user-images.githubusercontent.com/2216474/33183128-47116716-d07f-11e7-94d3-4e00d1dedff7.png)

**Comment by psifidotos** [comment]
I added the steps to Tips & Tricks also... https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks#q-how-can-i-use-a-plasma-taskmanager-instead-of-the-one-provided-by-latte

**Comment by aislanmaia** [comment]
Many thanks for your kind reply @psifidotos . I've accomplished to add the icon-only taskmanager to latte dock following exactly all steps listed by you, but for somehow, the icons in taskmanager was too small, while my dash icon was in the normal size and increasing the size in configs results in my dash icon way bigger than the icons in taskmanager. 
I'll upload a screenshot later, since I've removed the taskmanager because that.

**Comment by psifidotos** [comment]
yeah I know, that is a plasma design limitation. Under 64px. they provide only the icon sizes provided from your icon theme and nothing else in between in order to avoid any small blur. On the contrary Latte because of the parabolic effect has other priorities. We have special heuristics in our code in order to support single icons plasma applets correctly.
