### ISSUE TITLE
Start in hidden mode

### ISSUE THREAD

**Issue by arthurflor** [psifidotos/Latte-Dock#764]
Hello!
Is it possible to start the dock in hidden mode?
What currently occurs is the dock start open and only after an interaction does it hide (auto hide).

**Comment by psifidotos** [comment]
> What currently occurs is the dock start open and only after an interaction does it hide (auto hide).

in my system (Auto Hide mode) it shows itself and afterwards it hides itself.
Isnt that the case in your system?

**Comment by arthurflor** [comment]
Huum, in my case, I need to interact with it (hover over It), to then hide itself.
But I would like to know if it is possible to start it already hidden. And then, when move the mouse over the border, the dock appears normally. (Is just a detail)

**Comment by psifidotos** [comment]
sorry it isnt possible to start hidden...

**Comment by arthurflor** [comment]
Ok, thanks anyway
