### ISSUE TITLE
v0.7.2 Seg Fault when selecting Latte Settings

### ISSUE THREAD

**Issue by rporter220** [psifidotos/Latte-Dock#766]
System Specs:
Kubuntu 17.10 w/ backports
KDE 5.11.3 / QT 5.9.1 / KDE FW 5.39.0

Latte-Dock was updated via the backports PPA from v0.7.1 and now when I right-click the dock and select "Latte Settings" the dock disappears and re-appears and KDE reports a Seg Fault. I have ran latte-dock with DDD and providing this info below.

This happens every time and is easy to re-produce.

DDD output and backtrace:

GNU DDD 3.3.12 (x86_64-pc-linux-gnu), by Dorothea LReading symbols from latte-dock...(no debugging symbols found)...done.
(gdb) set args
(gdb) run
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe0bd2700 (LWP 11718)]
[New Thread 0x7fffd5d80700 (LWP 11719)]
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[New Thread 0x7fffcfdc7700 (LWP 11720)]
[New Thread 0x7fffbee2f700 (LWP 11721)]
[New Thread 0x7fffbce8b700 (LWP 11733)]
[New Thread 0x7fffabfff700 (LWP 11735)]

Thread 7 "QQmlThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffabfff700 (LWP 11735)]
0x00007ffff53944d0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
(gdb) frame 2
#2  0x00007ffff539691e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
(gdb) frame 0
#0  0x00007ffff53944d0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
(gdb) Quit
(gdb) Quit
(gdb) 

![screenshot_20171113_190244](https://user-images.githubusercontent.com/30326590/32757683-5436cf02-c8a6-11e7-9cc8-d794c1d62c53.png)

**Comment by nemonein** [comment]
Same here.
Kubuntu 17.10 with backports enabled.
Latte-dock 0.7.2-0ubuntu1~ubuntu17.10~ppa3.

**Comment by rikmills** [comment]
Works OK here on 2 machines and a VM.

![8ce4a570b8](https://user-images.githubusercontent.com/25360459/32769376-95c26c8e-c913-11e7-85b0-156d532c9092.png)

Maybe close the dock and clear contents of:

~/.cache/lattedock/qmlcache/

**Comment by psifidotos** [comment]
things to try in order to start understanding the issue:

1. can you change layouts or it crashes ? From right click menu -> Layouts
2. If you change layouts does it still crash when opening the settings window?

for better backtrace install debug symbols for latte and qt5 declarative e.g. qt5-declarative-debug
and afterwards run latte with:

`env QV4_FORCE_INTERPRETER=1 latte-dock -d`

I would like to see the command line output of the above command

and for  a better backtrace you can try:
`env QV4_FORCE_INTERPRETER=1 ddd --debugger /bin/gdb latte-dock`

is the backtrace more descriptive?

**Comment by psifidotos** [comment]
clearing qmlcache usually fixes qml crashes temporarily.... 

 so this is a settings window issue... we need a more informative backtrace

**Comment by rikmills** [comment]
For installing debug symbols:

See: https://wiki.ubuntu.com/Debug%20Symbol%20Packages

qtdeclarative has a silly number of dbsym packages in ubuntu, so perhaps you can say which.

https://launchpad.net/ubuntu/+source/qtdeclarative-opensource-src/5.9.2-3ubuntu2

latte-dock's ownf dbgsym is: https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports/+files/latte-dock-dbgsym_0.7.2-0ubuntu1~ubuntu17.10~ppa3_amd64.ddeb

**Comment by nemonein** [comment]
There's something weird.
I don't know about debug system at all, so I installed these packages thanks to @rikmills.
```
qtdeclarative5-dev-tools
qtdeclarative5-dev-tools-dbgsym_5.9.1-4ubuntu1_amd64.ddeb 
latte-dock-dbgsym_0.7.2-0ubuntu1~ubuntu17.10~ppa3_amd64.ddeb
```
Then I ran latte.

```env QV4_FORCE_INTERPRETER=1 latte-dock -d```

Hm..
**Latte does not crash.**

Here's the messages.

```
$ env QV4_FORCE_INTERPRETER=1 latte-dock -d
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
[warning 21:26:04.127127] - JIT is disabled for QML. Property bindings and animations will be very slow. Visit https://wiki.qt.io/V4 to learn about possible solutions for your platform.
[warning 21:26:04.219219] - Unable to find service type for service "Plasma/PopupApplet"
[warning 21:26:04.642642] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 21:26:04.690690] - trying to show an empty dialog
[warning 21:26:05.286286] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 21:26:06.443443] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
[warning 21:26:06.984984] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
[warning 21:26:06.984984] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 21:26:06.984984] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 21:26:06.984984] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 21:26:06.984984] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
[warning 21:26:07.594594] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 21:26:07.595595] - Icon theme "Mint-X" not found.
[warning 21:26:07.595595] - Icon theme "elementary" not found.
[warning 21:26:07.595595] - Icon theme "gnome" not found.
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
[warning 21:26:07.599599] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 21:26:07.600600] - Icon theme "Mint-X" not found.
[warning 21:26:07.600600] - Icon theme "elementary" not found.
[warning 21:26:07.600600] - Icon theme "gnome" not found.
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
[warning 21:26:07.613613] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 21:26:07.614614] - Icon theme "Mint-X" not found.
[warning 21:26:07.614614] - Icon theme "elementary" not found.
[warning 21:26:07.614614] - Icon theme "gnome" not found.
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
[warning 21:26:07.618618] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 21:26:07.619619] - Icon theme "Mint-X" not found.
[warning 21:26:07.619619] - Icon theme "elementary" not found.
[warning 21:26:07.619619] - Icon theme "gnome" not found.
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
[warning 21:26:07.631631] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 21:26:07.632632] - Icon theme "Mint-X" not found.
[warning 21:26:07.633633] - Icon theme "elementary" not found.
[warning 21:26:07.633633] - Icon theme "gnome" not found.
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
[warning 21:26:07.637637] - Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 21:26:07.638638] - Icon theme "Mint-X" not found.
[warning 21:26:07.638638] - Icon theme "elementary" not found.
[warning 21:26:07.638638] - Icon theme "gnome" not found.
[warning 21:26:07.672672] - No object for name "alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor"

---- Latte Launched ----
---- After Opening the Settings in Latte ----

[warning 21:27:13.6262] - JIT is disabled for QML. Property bindings and animations will be very slow. Visit https://wiki.qt.io/V4 to learn about possible solutions for your platform.
[warning 21:27:13.9898] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
[warning 21:27:13.9898] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
[warning 21:27:13.9898] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
[warning 21:27:13.107107] - QQmlComponent: Component is not ready
```

I also tried this, but Latte is not launched.
```env QV4_FORCE_INTERPRETER=1 ddd --debugger /usr/bin/gdb latte-dock```

Is this helpful to you?

**Comment by rporter220** [comment]
I have similar results as nemonein with the Layouts option. I can open the Configure with no problems, but I don't have a different layout to change to. I did not try to create a new layout.

I'm leaving for work right now. If I have some time to remote in I'll try the above to see if I can get a better backtrace for you, otherwise I'll do this when I get home.

Thank you for your response and assistance with getting accurate debug info. :-)

**Comment by psifidotos** [comment]
> I also tried this, but Latte is not launched.
> env QV4_FORCE_INTERPRETER=1 ddd --debugger /usr/bin/gdb latte-dock

did the ddd window opened? if it did you must afterwards write `run` in its output area and hit `Enter`

> Hm..
> Latte does not crash.

it looks like as a #730 behavior... it gives me some insights but I really need a good backtrace...

1. after you installed the debug packages, isnt the backtrace more informative?
2. is this your first Latte install ? were you using 0.7.1 before and it was working ok?

**Comment by nemonein** [comment]
@psifidotos 
I followed your instruction, on the ddd window, and type 'run'.
Latte does not crash, this time too. (Normal launch crashes Latte.)

I have been using Latte since 0.7.1. (or older. from rikmills's PPA.) I upgraded Latte through Backports PPA. It was working fine.

Here's ddd backtrace.
```
GNU DDD 3.3.12 (x86_64-pc-linux-gnu), by Dorothea LReading symbols from latte-dock...Reading symbols from /usr/lib/debug/.build-id/19/7f2344c2c4dc38a30b459f033566005d8ea719.debug...done.
done.
(gdb) run
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe0a8f700 (LWP 30712)]
[New Thread 0x7fffd4495700 (LWP 30713)]
[New Thread 0x7fffd3c94700 (LWP 30714)]
[New Thread 0x7fffd2ffd700 (LWP 30715)]
[New Thread 0x7fffd27fc700 (LWP 30716)]
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
[New Thread 0x7fffd0942700 (LWP 30717)]
[New Thread 0x7fffab2de700 (LWP 30718)]
[New Thread 0x7fffa9694700 (LWP 30719)]
[New Thread 0x7fffa15c6700 (LWP 30730)]
[New Thread 0x7fff8bfff700 (LWP 30745)]
[New Thread 0x7fff8a5ad700 (LWP 30746)]
[Thread 0x7fff8bfff700 (LWP 30745) exited]
[Thread 0x7fff8a5ad700 (LWP 30746) exited]
```

I reserved ```qmlcache``` directory which caused Latte to be crashed. Could it be helpful if I send it to you?

**Comment by psifidotos** [comment]
> I reserved qmlcache directory which caused Latte to be crashed. Could it be helpful if I send it to you?

unfortunately not....

> Here's ddd backtrace.

this isnt a backtrace...
use the following #147 in order to have a screenshot with the backtrace window

@rporter220 
> but I don't have a different layout to change to. 

you can press the defaults button in order to restore the default layouts that their names arent present in the Layouts

**Comment by rporter220** [comment]
Ok, I had some time to look into this and this is what I found.

First, I installed
`qtdeclarative5-dev-tools
qtdeclarative5-dev-tools-dbgsym_5.9.1-4ubuntu1_amd64.ddeb 
latte-dock-dbgsym_0.7.2-0ubuntu1~ubuntu17.10~ppa3_amd64.ddeb`

I then ran the
`env QV4_FORCE_INTERPRETER=1 latte-dock -d`
After running this, the dock opened and I was able to access the settings menu without it crashing. Several attempts after using this and it would no longer crash even if I used the above command or not. So something about the above command seemed to "fix" the issue. Here is the output of the command:

Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 9:35:27.706706] - JIT is disabled for QML. Property bindings and animations will be very slow. Visit https://wiki.qt.io/V4 to learn about possible solutions for your platform.
[warning 9:35:28.240240] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 9:35:29.461461] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/LayoutsContainer.qml:67:8: Unable to assign [undefined] to double
[warning 9:35:36.185185] - JIT is disabled for QML. Property bindings and animations will be very slow. Visit https://wiki.qt.io/V4 to learn about possible solutions for your platform.
[warning 9:35:36.256256] - QQmlComponent: Component is not ready
[warning 9:35:43.579579] - No object for name "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1"
[warning 9:35:43.580580] - No object for name "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1"
[warning 9:35:43.580580] - No object for name "alsa_input.pci-0000_00_1f.3.analog-stereo"
Xlib:  extension "NV-GLX" missing on display ":0".


Since it was no longer crashing, I removed the latte-dock cache directory and restored it to yesterday's copy and verified that the crashing problem returned with the restored cache. I then got the following backtrace with just the 'ddd latte-dock' command

![image](https://user-images.githubusercontent.com/30326590/32791169-f9349d0c-c925-11e7-88e1-fd22bdf63f28.png)

I hope this helps.

**Comment by psifidotos** [comment]
@nemonein 

from 0.7.1 -> 0.7.2 for the configuration window only one file changed.
you can try to substitute it with the old version, I send you the old version, the file is located at:

`/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/AppearanceConfig.qml`

0.7.1 version:
[AppearanceConfig.qml.txt](https://github.com/psifidotos/Latte-Dock/files/1471603/AppearanceConfig.qml.txt)

1. remove the .txt extension from the file I send
2. substitute the AppearanceConfig.qml with the file I send
3. restart Latte

does it crash ?

**Comment by psifidotos** [comment]
@nemonein I just read your comment that it didnt crash after you removed your cache...
Let's give it some time to see if it will crash again... there is no point to use the old qmlcache directory, it might be that between the upgrade 0.7.1 -> 0.7.2 qt didnt update its cache properly... we will see...

**Comment by nemonein** [comment]
@psifidotos 
Ok, I see. I'll let you know it crashes or malfunctions again.

By the way, I tested with AppearanceConfig.qml, but no crashes at all.

**Comment by psifidotos** [comment]
not having any news with this, so...
