### ISSUE TITLE
Firefox Quantum icon fighting

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#768]
![video](https://user-images.githubusercontent.com/19151258/32979371-afe76c6c-cc5c-11e7-9aea-237116729fd8.gif)

OS: Archlinux (fully updated)

So far tried restarting dock and `rm -rf ~/.cache/lattedock*` but that did not help.

**Comment by psifidotos** [comment]
Try to change icon theme and clear your icon cache

**Comment by rokups** [comment]
That solved it, thank you
