### ISSUE TITLE
Regression with the separator applet 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#770]
I noticed a regression with the separator applet ... which is the best choice between the internal separator and the plasmoid separator?

**Comment by psifidotos** [comment]
what is the regression?

**Comment by JenaPlinsky** [comment]
non-fluid animation in the transition between area applets and area tasks

**Comment by psifidotos** [comment]
Show me a screenshot of your edit mode and tell me which separators are applets

**Comment by JenaPlinsky** [comment]
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1485410/video.zip)

**Comment by psifidotos** [comment]
when you restart Latte is it fixed ?

**Comment by JenaPlinsky** [comment]
It is always present also by restarting Latte

**Comment by JenaPlinsky** [comment]
@psifidotos I removed the separator applet and the problem remains so I do not think it depends on this plasmoid

Here it is, the problem depends on the internal separator !!!! :
- if it is present, everything goes smoothly
- if it is absent, the animation is not fluid

**Comment by psifidotos** [comment]
@JenaPlinsky yeah, you were right... I think now it should be ok...

**Comment by JenaPlinsky** [comment]
Ohhhhhh Yeah !!!
