### ISSUE TITLE
Solid top panel breaks shadow calculations for Unity layout when maximized window present

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#772]
I was playing with various setups for the video you wanted me to make and I discovered some unresolved panel behavior that breaks consistency and proper look of panels.

In Unity type of setup a horizontal and vertical panel touch each other in one corner. In maximized mode space for shadow is reserved, even if shadow is disabled, creating empty space which doesn't look good.

Here is video showing the problem:

https://youtu.be/GXdE8eX0bJw

Some themes have shadow, however the best look is obtained by disabling it, but in maximized mode latte somehow "detects" space for shadow and moves out of its way.

I suspect that this may be, because latte doesn't enforce space but adjust itself to the given settings and even is shadow becomes invisible, it's still there.

Is there a way to resolve it gracefully?

**Comment by psifidotos** [comment]
please send me your layout because I cant reproduce it... possiblly a matter of settings

**Comment by psifidotos** [comment]
ok found it... you have enabled solid background for your top panel...

**Comment by michaldybczak** [comment]
Top and side panel too, but yeah, top panel none-shadow is making the problem.

From one side, when shadow is enabled, it is sound that panel moves aside so the shadow wouldn't overlap on the first icon on panel/dock. However, when shadow is off, it should not influence panel.

By the way, it's amazing how latte has grown. When I switched to predefined Unity setting, basic setting was bad so I started tweaking and Unity setting remembers it so I can easily switch between settings that are all perfectly set. That is so awesome and works so well!

**Comment by psifidotos** [comment]
> That is so awesome and works so well!

thanks

>  When I switched to predefined Unity setting, basic setting was bad so I started tweaking and Unity setting remembers it so I can easily switch between settings that are all perfectly set.

yes, it was designed that way. Latte provides you with some predefined layouts and you can alter them any way you want. If you want the default layout again you can just rename you layout in anything you want and click afterwards the Defaults button in Layout Editor. The Defaults button checks the names of the layouts and if a predefined layout name doesnt exist only in that case it readds that predefined layout.

> However, when shadow is off, it should not influence panel.

why this is happening. The solidness  of the panel is get from the plasma theme but that solidness is provided by the theme for !compositing cases, so the themes do not provide at all a shadow for real solid panels. Why Latte is doing is that it uses the shadow from transparent panel below the solid panel (so this is a workaround). In most cases it works but you hit a corner with your setup.

What I can add in my code is to take into account if the user has enabled shadows or not. If the user has solidpanel but has disabled the shadows then there shouldnt be an issue... 
I can fix that...

**Comment by psifidotos** [comment]
@michaldybczak things you can do in order to fix this temporally if you can not build from master or v0.7 branch are:

1. Disable Solid panel for your top panel, and move the transparency to 100% in order to not have transparency at all
2. Enable blur from Latte Tweaks settings for the top panel
3. Enable the blur and background contrast kwin effects from plasma systemsettings

**Comment by michaldybczak** [comment]
I'm still on latte-dock-git version so there's no problem. I updated it and now the shadow problem is gone :D. No awkward space between panels!
Awesome!
