### ISSUE TITLE
Sound icon not switching completely in dark mode

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#774]
Today another small thing to shape latte into perfection :).

I've been playing with dark theming, switched to dark breeze, breezmite dark and so on. I noticed that the sound icon doesn't look right in dark mode. Its background goes black but the grayish sound symbol stays that way which creates a very unreadable effect. Here is the screenshot:

![screenshot_20171120_184210](https://user-images.githubusercontent.com/10132958/33033038-5de1573e-ce23-11e7-9adf-032e43ae9772.jpg)

**Comment by michaldybczak** [comment]
I don't see any change :(

**Comment by psifidotos** [comment]
are you using the latest ?

yes I checked it...

![image](https://user-images.githubusercontent.com/2216474/33039300-34cd081c-ce40-11e7-938e-2bf444c47773.png)

**Comment by michaldybczak** [comment]
Yeah, I updated 4 times in last 2 hours and see no change. As you know, usually when you post a commit I can see results almost immediately.
On: https://cgit.kde.org/latte-dock.git/
where AUR git version is pulled, you can see your latest commits so all should be there.

Will check again tomorrow and let you know if something has changed.

**Comment by psifidotos** [comment]
if this is a matter of your theme I dont think we can do something... try to change themes to check if the behavior persists

**Comment by michaldybczak** [comment]
I am using Breeze dark. I check other dark themes and they all produce the same effect so it's not a matter of specific theme for me.

**Comment by michaldybczak** [comment]
OK, I switched to test, clean user and I figured out what's the issue. On Breeze icons, it works correctly, but you get the mentioned dark on dark effect when you use La Captain icons.

Should I bring it to La Capitaine developer or is something that you can do to make it work with it properly? La Capitaine is nowadays one of the most popular and complete icons sets.

**Comment by psifidotos** [comment]
How does it look the volume icon in the systray with a solid panel background?

**Comment by michaldybczak** [comment]
White. Completely different from the dock. On systray icons are from theme, on dock, icons are from icons.

![screenshot_20171120_223415](https://user-images.githubusercontent.com/10132958/33042719-1e059362-ce43-11e7-8c9e-44cf9987e286.jpg)

**Comment by psifidotos** [comment]
ok I researched it...
this is an issue for the maintainer of La Capitaine...
Latte cant do anything about it...

**Comment by michaldybczak** [comment]
OK, will do.
I checked various icon themes and there are some which sound icon looks ok, probably because of the latest tweak, however for many of them I must switch to dark version to get sound icon correctly. So the issue with La Capitain is, it doesn't have dark version.
Thanks for help :).

**Comment by keeferrourke** [comment]
As far as I can the issue is not with La Capitaine, so long as the user first runs the included configure script to use the correct theme subset for dark or light themes.

**Comment by psifidotos** [comment]
yep, that would work
