### ISSUE TITLE
Memory leak over the time

### ISSUE THREAD

**Issue by Aetf** [psifidotos/Latte-Dock#776]
I notice that Latte Dock has been leaking memory slowly over the time sometime ago.

After a fresh restart of the system, the memory usage of latte is ~100M, which is good.

Then after a day of use, its memory usage grows to somewhere around 1G.

The following screenshot is taken after 3 days since startup, and most of the time the system was just idling.

![screenshot_20171120_145510](https://user-images.githubusercontent.com/1519759/33039829-5a263b9e-ce07-11e7-97d5-b23953c32da1.png)

Versions:
* Archlinux with latest update
* Qt: 5.9.2
* Plasma: 5.11.3
* KDE Frameworks: 17.08
* Latte: 0.7.2

**Comment by psifidotos** [comment]
Show me your Latte

**Comment by Aetf** [comment]
More info about my configuration:

A screenshot of my desktop
![screenshot_20171120_154731](https://user-images.githubusercontent.com/1519759/33040815-3b709674-ce0a-11e7-803d-89246bac93b0.png)

Both the top right panel and bottom dock is provided by latte. And there is no multiple monitors.

**Comment by Aetf** [comment]
The Layout https://gist.github.com/Aetf/047d8f3a3fbd8bb37a80040efc62f0a5

**Comment by psifidotos** [comment]
It is probably an applet issue... you must try to remove all applets except the bottom dock that contains only Latte plasmoid   and see it still happens... 

Known applets leaks and no related to Latte is the frame plasmoid that shows pictures
Electron apps showing their menu in the panel

**Comment by psifidotos** [comment]
The audio playing in your systray is also one of the suspicious and koversation app if it is shown in the systray

**Comment by Aetf** [comment]
Hmm, for electron apps do you mean showing their icon in systray is known to leak?

Though I've been having this configuration for quite a while and I only observed the leak recently.

Anyway, let me try remove the playbar (the audio icon in systray) and close slack and see what happens.

**Comment by psifidotos** [comment]
any news one this?

**Comment by Aetf** [comment]
I've been trying to isolate the issue to a specific applet by adding back applets one by one.
For now the results are
- Only the bottom dock with latte plasmoid and clock (the default layout): no leak
- Default bottom dock plus system tray on top right, with one electron app icon (slack): no leak. But I haven't run this layout for too long.
- Same as above, plus event calendar: leak. But it seems much slower. After about 3 days, the memory usage was ~900MB

**Comment by psifidotos** [comment]
so this is starting to point to event calendar...
nice to know that this is upstream...

> But it seems much slower. After about 3 days, the memory usage was ~900MB

maybe the action that creates the leak wasnt triggered so often... an update maybe or something relevant... which event calendar? the plasma one or the store.kde.org one?

**Comment by Aetf** [comment]
This one: https://store.kde.org/p/998901/

Yeah now I can confirm that the leak is triggered by updating calendar data from Google.
Simply clicking on the update button makes the memory usage grow up constantly. I'll report to upstream.

Thank you for helping me debug this!
