### ISSUE TITLE
Show audio playing apps: Chrome issue

### ISSUE THREAD

**Issue by unc926** [psifidotos/Latte-Dock#777]
hi, All windows with chrome open have a displayed sound play icon problem.

![screenshot_20171122_150149](https://user-images.githubusercontent.com/30185386/33127170-70d4c17a-cf98-11e7-8102-aad645a78b81.png)

**Comment by psifidotos** [comment]
they do because these are webapps, dont they?
so they are identified as chrome...
so this is plasma libtaskmanager issue and you should be able to reproduce it with plasma icon-only taskmanager...

you can report any upstream issues at: bugs.kde.org
