### ISSUE TITLE
Please add pinned and frequent option to the latte dock like in windows 7/10.

### ISSUE THREAD

**Issue by nazar2sfive** [psifidotos/Latte-Dock#779]
I want latte dock to show my frequently open files and also to pin my favorite document/folder like in windows. 
![image](https://user-images.githubusercontent.com/12841320/33227705-8c44bcfe-d1d1-11e7-91ee-78598eea9aba.png)

currently latte dock only gives me new document option in libreoffice. I want to see my frequently opened documents and also option to pin my most used documents like in windows.
![image](https://user-images.githubusercontent.com/12841320/33227755-5cfbf4d4-d1d2-11e7-929e-c1ee5f81656c.png)

**Comment by psifidotos** [comment]
Frequent: is not supported by plasma libtaskmanager so this is upstream you can request at bugs.kde.org

Pinned Folders: right click on dolphin launcher when no window is shown

Latte and Plasma show last used 5 records for an app, e.g. kwrite, etc i think that libreoffice works ok in my system.


A good alternative for this, one that i am using is to use Activities. 

1. Pin any folder or file you want in an Activity through its context menu in dolphin. 
2. Add in Latte a Folder widget through the widgets explorer
3. From the settings of the Folder widget enable to show only pinned files of the current activity

**Comment by psifidotos** [comment]
there is also this: https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks#q-how-to-add-an-history-applet-to-latte-dock-
