### ISSUE TITLE
Focus during preview windows on hovering

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#78]
Latte-dock works great. There is however the issue that it steals focus during "preview windows on hovering", which frequently breaks my workflow. I don't know how icon-only task manager is avoiding it, but it doesn't happen there.

It would be just great if the focus would remain in the active window instead.

**Comment by kupiqu** [comment]
Thanks for fixing this so fast!

**Comment by kupiqu** [comment]
There is another issue that frequently breaks my workflow, which is related to the focus of "preview windows on hovering", this time within the Latte dock itself. Not sure it is technically solvable though.

An example of the issue is the following: imagine you want to open an application/ or to gain focus on a window (e.g. konsole), but by mistake the mouse gets off the icon by a tiny bit so it now falls within the area of let's say a kate window that is open, then a preview for kate emerges which was unintended and impedes to click on the konsole icon. One needs then to move the mouse off of kate icon, wait patiently until the preview disappears and click again on the konsole icon.

Do you think it would be possible to keep the window preview but still respond to the latte icons behind if a mouse click is done on those icons?

On the other hand, if the mouse click is on the previewed window area (which really appears outside the latte dock itself), it should behave as it currently does, so focus whould be directed to that window.

I tried to be clear, but this is difficult to explain... Let me know if you would need further explanations...

**Comment by kupiqu** [comment]
I could not reopen the issue, should I open another one?

**Comment by psifidotos** [comment]
>  then a preview for kate emerges which was unintended and impedes to click on the konsole icon.

can you provide a screenshot? The preview in your system hides the icons in Latte?

**Comment by kupiqu** [comment]
Oh, that would be much simpler to do, to set te whole preview out of the latte dock. This is not happening in my case, vertical dock

<img width="100" alt="screenshot_20170126_180920" src="https://cloud.githubusercontent.com/assets/3875196/22354344/e61cda9a-e3f2-11e6-83c7-3f4295b4ed90.png">

Note that in the screenshot konsole is the one that hides kate, no the other way around.

**Comment by kupiqu** [comment]
Oh, that would be much simpler to do, to set te whole preview out of the latte dock. This is not happening in my case, vertical dock

<img width="100" alt="screenshot_20170126_180920" src="https://cloud.githubusercontent.com/assets/3875196/22354410/3843b528-e3f3-11e6-8612-cfc078191674.png">


Note that in the screenshot konsole is the one that hides kate, no the other way around.

**Comment by psifidotos** [comment]
Can you also try with a bottom dock, problem still remains?

What kde frameworks version are u using?

**Comment by kupiqu** [comment]
Mmm, I realized that this issue only happens when latte dock is on the left side.

Using kf5 5.30 (plasma 5.8.5; up-to-date kde neon user)

**Comment by psifidotos** [comment]
@kupiqu  latest master should fix this for you... please, check it...

**Comment by kupiqu** [comment]
Excellent, as always. Thanks!
