### ISSUE TITLE
Question: Different latte dock for activities

### ISSUE THREAD

**Issue by Kolesar** [psifidotos/Latte-Dock#780]
It is possible to create different late dock for each activities?

I try set in Appearance->Layout->Configure, but without effect. I have same Latte dock on all my activities.

Latte-dock version: 0.7.2
KDE Frameworks 5.40.0
Qt 5.9.2 (built against 5.9.2)
The xcb windowing system
OpenSUSE Tumbleweed

**Comment by psifidotos** [comment]
Yes you can... create different layouts and assign them to each activity you want from the Layouts editor
