### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by ttv20** [psifidotos/Latte-Dock#781]
_sorry about my bad english..._

For now there isn't rtl support.
I try to add 
```
LayoutMirroring.enabled: Qt.application.layoutDirection === Qt.RightToLeft
LayoutMirroring.childrenInherit: true
```
to the plasmoid and the containment and it's work, but it need more workaround.

Can you take care of it?
Thanks

**Comment by ttv20** [comment]
basicly, in qml main just add this
```
LayoutMirroring.enabled: Qt.application.layoutDirection === Qt.RightToLeft
LayoutMirroring.childrenInherit: true
```
for more info: [http://doc.qt.io/qt-5/qtquick-positioning-righttoleft.html](url)

you can try to start with `--reverse` to test it easily

I found 2 problem when the panel is in edit mode:
1. when the panel is in edit mode the transparent selection above the widgets is not on the widgets 
![screenshot_20171128_150121](https://user-images.githubusercontent.com/8342914/33321940-225ad0ea-d450-11e7-8ff7-74f3af8174ba.png)

2. the panel take minimum width (normaly is 100% width)
normaly:
![screenshot_20171128_145954](https://user-images.githubusercontent.com/8342914/33322081-a45255f0-d450-11e7-8088-88b23ae52b1a.png)
on editing:
![screenshot_20171128_150121](https://user-images.githubusercontent.com/8342914/33322224-3be18e4a-d451-11e7-88b2-cba766bd52bd.png)


And, I don't how to reverse the settings panel:
now:
![ltr](https://user-images.githubusercontent.com/8342914/33322138-e84dbb32-d450-11e7-94f6-0122d12a0f2c.png)
need to be:
![rtl](https://user-images.githubusercontent.com/8342914/33322157-fe6332a8-d450-11e7-803b-bb9eecd2f260.png)

**Comment by psifidotos** [comment]
> And, I don't how to reverse the settings panel

its main file is: shell/package/contents/configuration/LatteDockConfiguration.qml

things that I have found broken for RTL:

```
- parabolic effect
- applet shadows
- applets tooltips order
- plasmoid badges (audio and progress)
- configuration window -> show/hide timers
- configuration window, comboxes show their lists out of place (I dont think Latte can do something about that as this is Qt  behavior)
- edit mode->applets hovering indicators out of place
```

@ttv20 are you able to test a branch when I improve the situation in order to find any remaining issues?
The thing is that I want RTL support to 0.7 version also except our master branch so this is going to take a bit, I will try to improve RTL situation for upcoming 0.7.3 version and I would like to help me indicate any issues if this is possible...

**Comment by ttv20** [comment]
yes, I can test and build if needed.

**Comment by psifidotos** [comment]
first question, I understand that RTL reverses all things when in horizontal... but in vertical what is happening? e.g. an RTL bottom dock goes to right edge, then in that case the items are shown like in non RTL ?

**Comment by psifidotos** [comment]
@ttv20 please check rtl branch which is based on master version...
I think most of the issues are fixed..
The Configuration Window Comboboxes issues I will need to report them upstream please confirm me that they are produced also in your system:
1. The comboboxes in settings window they show the selected item to the left even though they should show it at the right
2. Expanding the comboboxes options, shows the list of options far from the correct placement, in some cases also far from the settings window

**Comment by psifidotos** [comment]
bug reports:
https://bugs.kde.org/show_bug.cgi?id=387415
https://bugs.kde.org/show_bug.cgi?id=387416

**Comment by ttv20** [comment]
Can you add screenshots in the bugs?
And, I think this bug [https://bugs.kde.org/show_bug.cgi?id=368605](url) is also related to PlasmaComponents
Can you check it? 
thank you

**Comment by psifidotos** [comment]
bug1: MyProfile text should be on the right and not on the left.

![default](https://user-images.githubusercontent.com/2216474/33342791-f8cb0fec-d48b-11e7-9eef-50e8299fba21.png)

bug2: showing the items of the combobox the list is shown far from the correct placement

![default](https://user-images.githubusercontent.com/2216474/33342945-64f3da78-d48c-11e7-8e32-98b7b146c867.png)

**Comment by ttv20** [comment]
The text is auto alignment & direction by the text language
just change the text to "הפרופיל שלי" and see
After you change the text you will see that the V is on the caret arrow, this is another bug.

**Comment by psifidotos** [comment]
> After you change the text you will see that the V is on the caret arrow, this is another bug.

Are you using the RTL branch?

> The text is auto alignment & direction by the text language

Doesnt make sense... if in the same list there are english options are aligned on the left and the RTL one on the right?

**Comment by psifidotos** [comment]
> The text is auto alignment & direction by the text language

you are right and the implementation is wrong in my opinion... If the user has a list containing both english and RTL options then the current selection is some times to the left and sometimes to the right... This is broken behavior in my opinion...

**Comment by psifidotos** [comment]
@ttv20 

1. have you tested rtl branch for any issues concerning RTL ? did you find any?
2. In RTL all things are reversed when in horizontal... but in vertical what is happening? e.g. an RTL bottom dock goes to right edge, then in that case the items are shown like in non RTL ?

**Comment by psifidotos** [comment]
> when I open a widget and there is a maximize window the window jump down for a sec and the panel glow showed up (I disable the panel glow when window is maximize). when I disable panel shadow it not happand. In the Master build it didn't happend

I dont understand... do you have a screenshot?

> on appearance, layout, if the selected item is RTL the V is after the text (left to the text) 

ok... I can fix that

> in select box if the text is LTR the caret is on the text

exactly... this is upstream bug: https://bugs.kde.org/show_bug.cgi?id=387415

> on edit mode all the panel gathering to the center

this is default behavior... in edit mode all applets are gathered to the center

> I don't understand exactly what you mean, but the way it works now is good

ok... then we are ok...

**Comment by ttv20** [comment]
"on appearance, layout, if the selected item is RTL the V is after the text (left to the text)"
I look at the code
in AppearanceConfig.qml:96
instead:
```
var selText = "    ";

if (layouts[i] === layoutManager.currentLayoutName) {
    selText = Qt.application.layoutDirection === Qt.RightToLeft ? " ✔" : "✔ ";
    activeLayout = i;
}

if (Qt.application.layoutDirection === Qt.RightToLeft) {
    layoutTexts.push("    " + layouts[i] + selText);
} else {
    layoutTexts.push(selText+layouts[i]);
}
```

I did:
```
var selText = "    ";

if (layouts[i] === layoutManager.currentLayoutName) {
    selText = "✔ "
    activeLayout = i;
}

layoutTexts.push(selText+layouts[i]);
```

now it's look fine

**Comment by psifidotos** [comment]
the RTL support in the ComboBox is a bit of a mess... :) I uploaded a new commit to fix this in order to be a lit bit reasonable also the mixed list (combined texts of RTLs and non-RTLs)

**Comment by ttv20** [comment]
I notice another bug
on edit mode when I try change widget place it has problem... try and see

**Comment by psifidotos** [comment]
not in my system... it works ok...

**Comment by psifidotos** [comment]
ok... all this initial work has landed both in master and v0.7 so every different issue for RTL should now be reported separately...

**Comment by psifidotos** [comment]
Just checked... 
bug1: is not appearing with QML standard ComboBox so this is plasma issue
bug2: is appearing also with QML standard ComboBox

**Comment by psifidotos** [comment]
@ttv20 in case you still have any issues in RTL with Latte master branch please report each one of them separately, and open for each one a different thread...
