### ISSUE TITLE
Active windows indicator: Does not show multiwindows

### ISSUE THREAD

**Issue by unc926** [psifidotos/Latte-Dock#782]
hi
using layouts unitymode 

![screenshot_20171202_000928](https://user-images.githubusercontent.com/30185386/33504047-ffde7f40-d6f6-11e7-8000-dac3e187ccd8.png)
![screenshot_20171202_001054](https://user-images.githubusercontent.com/30185386/33504048-000a8932-d6f7-11e7-90e6-fd7d0949ebdc.png)

Also, the indicators should be on the bottom of icons, not side.?

**Comment by psifidotos** [comment]
firefox has two dots so that indicates multiple windows...

dolphin has one dot... if you open one more dolphin or activate between them isnt a second dot appearing?

> Also, the indicators should be on the bottom of icons, not side.?

the indicators should be at the left side as this is a left dock

**Comment by psifidotos** [comment]
give me steps to reproduce this...

**Comment by unc926** [comment]
here

![peek 2017-12-02 01-04](https://user-images.githubusercontent.com/30185386/33505608-1f079fae-d6fd-11e7-94a0-24b4aecaf941.gif)

**Comment by psifidotos** [comment]
is that happening only with chrome? can you make a video also with dolphin?

**Comment by psifidotos** [comment]
chrome is known to create such issues with plasma libtaskmanager...

**Comment by unc926** [comment]
have same problem all apps chrome, firefox, dolphin ...

here dolphin
![peek 2017-12-02 01-14](https://user-images.githubusercontent.com/30185386/33505929-8e5657f0-d6fe-11e7-8675-a504c2f44408.gif)

**Comment by psifidotos** [comment]
Can you send me your layout file to test it in my system?

**Comment by unc926** [comment]
my layout
[Unity.layout.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1523721/Unity.layout.latte.zip)

**Comment by psifidotos** [comment]
activate at` Tasks -> Indicator for active window group`.

This option was supposed to enable the second dot for the active task when there are multiple windows. Because in the beginning the active line was the main design decision...

I will update this... temporarily activate at `Tasks -> Indicator for active window group`.

**Comment by unc926** [comment]
Perfect thanks

**Comment by JenaPlinsky** [comment]
Hi @unc926 
How did you manage to make those videos? is that an animated gif?

**Comment by unc926** [comment]
@JenaPlinsky created with peek
https://github.com/phw/peek

**Comment by psifidotos** [comment]
> now displayed only 2 indicators do not show more.

it never did. Two dots mean = 2 or more windows... you cant have 3 dots, 4 dots etc...

**Comment by unc926** [comment]
@psifidotos     Shouldn't he be showing a dot for every window?

**Comment by psifidotos** [comment]
> @psifidotos Shouldn't he be showing a dot for every window?

no, by design stops to 2 dots

**Comment by unc926** [comment]
@psifidotos  Okay, I got it thanks
