### ISSUE TITLE
Overlayed numbers make icons hard to distinguish

### ISSUE THREAD

**Issue by lingtjien** [psifidotos/Latte-Dock#783]
This is not really a bug but more an improvement request. As you can see in the attachment, in some icon themes the icons become completely obscured by the number indicators.

A few quick suggestions I can think of:

- allow the overlayed numbers to be transparent
- allow the overlayed number to be displayed in a corner of the icon (and smaller)
- allows the adjustment of the number overlay size (I couldn't find that option, but maybe I haven't looked at the right places)
![latte-dock](https://user-images.githubusercontent.com/27009907/33551631-440cdb74-d8f2-11e7-8739-442f9b1c12a9.png)
![overlay](https://user-images.githubusercontent.com/27009907/33551634-45db3144-d8f2-11e7-93ea-8a2f3fe437c9.png)

**Comment by psifidotos** [comment]
I can discuss an improvement but I will need a mockup that is going to be more appealing than the current solution

**Comment by psifidotos** [comment]
I reduced their size 20% more...
