### ISSUE TITLE
alignment issue on the "Unity" layout

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#784]
alignment issue on the "Unity" layout when **both top and left** docks are in **autohide** mode...

![screenshot_20171205_025525](https://user-images.githubusercontent.com/24593950/33586076-bf8a93b6-d967-11e7-873a-e97ecb29bb97.png)
![screenshot_20171205_024623](https://user-images.githubusercontent.com/24593950/33585910-0115bdde-d967-11e7-921e-692ae0f697ba.png)

**Comment by psifidotos** [comment]
What do you mean? That the left dock should use all the space? In Dodge visibility modes isnt that happening?

**Comment by JenaPlinsky** [comment]
Yes when both top and left are in auto hide mode
