### ISSUE TITLE
Global menu

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#785]
is possible to automatically set the type of menu option depending on whether the "Global Menu" plasmoid is present?

![screenshot_20171205_031151](https://user-images.githubusercontent.com/24593950/33586757-3f4e1494-d96b-11e7-8e87-cd5d336086e2.png)

**Comment by psifidotos** [comment]
Sorry, i dont touch plasma systemsettings from Latte but i could also review a patch for this

**Comment by psifidotos** [comment]
upstream plasma reivew that will also enable this automatically in case it is accepted...

https://phabricator.kde.org/D9215
