### ISSUE TITLE
No extra indicators for firefox?

### ISSUE THREAD

**Issue by ninjafuchs** [psifidotos/Latte-Dock#787]
Hi,
I just tried out your dock, since it came to kde neon user and i really like it.
I figured out some strange behaviour: when chromium is playing sounds, then i get the audio indicator at the chromium icon and i can mute it if I want to.
Unfortunately there are no indicators for my firefox (quantum), which i use as default.

I know its just a small flaw, but its the only one I found and I would really appreciate it if it could be fixed.

thank you in advanced
ninja

**Comment by psifidotos** [comment]
has been fixed through: https://github.com/psifidotos/Latte-Dock/commit/454cd949d50b28bd71c70960f82064468ae23312
