### ISSUE TITLE
halo for colored indicator is missing

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#789]
the halo of the indicator for the active window, does not appear for the colored dot when the "need attention" is active

**Comment by psifidotos** [comment]
Didnt understand anything, can you make a screenshot?

**Comment by JenaPlinsky** [comment]
I'll try to better explain myself :)
when an icon bounces, its active window indicator has a background light of the same color as the indicator itself, this alternates with a red indicator which does not have the same light effect as the standard active window indicator

**Comment by psifidotos** [comment]
screenshot please...

**Comment by JenaPlinsky** [comment]
Ehmmmmm I do not know how to do it, the duration of the "need attention" does not allow me to capture the screenshot

**Comment by psifidotos** [comment]
- you can use kazam or recordmydesktop to make a video
- and you can use https://gfycat.com/ in order to make it as gif if you want to...

**Comment by JenaPlinsky** [comment]
[video..zip](https://github.com/psifidotos/Latte-Dock/files/1540685/video.zip)
Maybe I saw badly

**Comment by psifidotos** [comment]
I watched the video but I didnt see any issue...

**Comment by JenaPlinsky** [comment]
Ohh yes I too

**Comment by psifidotos** [comment]
ok... if we find something new we reopen it...
