### ISSUE TITLE
Very strange behavior

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#790]
![screenshot_20171208_180058](https://user-images.githubusercontent.com/24593950/33776466-c067c948-dc41-11e7-88cc-fb6dc88b92e0.png)

- long time ago because of a strange flicker on the dock latte I changed the default behavior of the Intel 2D graphics driver

          Q: Are there known compatibility issues, with some specific graphics driver ?
          A: If you have Intel Graphics and experiment problems with the rendering e.g. pixelated graphics, corrupt text, etc, you can try changing the rendering method 2D from SNA to UXA.

   /etc/X11/xorg.conf.d/20-intel.conf

   ```
   section "Device"
      Identifier  "Intel Graphics"
      Driver      "intel"
      Option      "AccelMethod"  "uxa"
   EndSection
   ```

- today, to see if things have improved, I tried to restore things as default so I deleted the file /etc/X11/xorg.conf.d/20-intel.conf and then restarted plasma

unfortunately, I noticed that the behavior of the graphics driver has remained that of the past .... but this is not the topic of this discussion

the real problem, however, is that I have observed, a couple of times in a day, to see latte work without any graphic animations
unfortunately I'm not able to replicate the problem
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1543323/video.zip)

**Comment by psifidotos** [comment]
> the real problem, however, is that I have observed, a couple of times in a day, to see latte work without any graphic animations
unfortunately I'm not able to replicate the problem

never happened in my system... I am using NVidia proprietary drivers...

> If you have Intel Graphics and experiment problems with the rendering e.g. pixelated graphics, corrupt text, etc, you can try changing the rendering method 2D from SNA to UXA

this is very old topic... What I have read in plasma devs forums, concercing intel they only acceptable driver is modesetting. You should try first to see how to enable modesetting intel driver in case this helps...

either way this report looks more a specific system setup problem and not something Latte could do something about...

**Comment by JenaPlinsky** [comment]
Ohhh Yesss I also think that this depends on my system

**Comment by JenaPlinsky** [comment]
Just to inform you that after other problems of this type, I restored the graphics driver with **UXA** rendering

```
section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "uxa"
EndSection
```

 and now everything runs smooth and **no longer seems to be the problem documented in the video**
it therefore seems to be bound exclusively to the rendering mode of the Intel **standard 2D driver SNA**
