### ISSUE TITLE
Ability to specify custom icon for an application

### ISSUE THREAD

**Issue by UralZima** [psifidotos/Latte-Dock#791]
Hi. I am using multiple firefox profiles simultaneously, and have 4-5 firefox icons on bottom.
I start them all with a separate window class, so they are not grouping.
Is there any way to specify an icon for task manager, doing it like specifying window class? So every firefox profile will have own icon (and may be pinned as launcher).

Sometime ago I tried to do it through desktop file, but firefox is changing icon back anyway.

Thanks

**Comment by psifidotos** [comment]
This is an upstream plasma libtaskmanager request... Latte cant do something...
