### ISSUE TITLE
Wayland session > Top dock don't rise with "dodge all windows" mode

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#795]
Wayland session > 
Top dock don't rise with "dodge all windows" mode
this kind of problem is not specific to a particular type of window as it happened long tome ago, for firefox55 but it occurs for all types of windows
...the dock hides only at the outer pixel

**Comment by psifidotos** [comment]
unfortunately I dont have a wayland session any more... I hope in the future that I will have hardware to support the wayland case...

**Comment by psifidotos** [comment]
the issue looks that in Wayland the window decoration isnt taken into account...

**Comment by JenaPlinsky** [comment]
Ohhh Ok 
in any case, is nice to see how with wayland there is no more flicker and 2d rendering is always perfect

**Comment by JenaPlinsky** [comment]
exactly it looks like that

**Comment by psifidotos** [comment]
> in any case, is nice to see how with wayland there is no more flicker and 2d rendering is always perfect

nice!

**Comment by psifidotos** [comment]
@JenaPlinsky  are you using the Breeze decoration in wayland?

**Comment by psifidotos** [comment]
reported upstream: https://bugs.kde.org/show_bug.cgi?id=387913 I dont know if this is going to be improved in plasma or not...

**Comment by psifidotos** [comment]
@JenaPlinsky there is problem to reproduce this...
show screenshots of your system please... 

1. Does this occur only on Dodge All Windows?
2. Do you observe this always for all cases? maximixed windows, normal, etc...

I have a VirtualBox and wayland in there even a bit sluggish it runs...

**Comment by JenaPlinsky** [comment]
> are you using the Breeze decoration in wayland?

No I'm using Oxygen

> Does this occur only on Dodge All Windows?

it was just like that

> Do you observe this always for all cases? maximixed windows, normal, etc...

I can not replicate the problem so I can not give you precise answers
 I'm happy to inform you that after the umpteenth **zypper up**....

openSUSE tumbleweed
Plasma 5.11.90
Framework 5.42
QT 5.10

now everything works as expected

**Comment by psifidotos** [comment]
ok... so we are clean then....

**Comment by JenaPlinsky** [comment]
> ok... so we are clean then....

Yes
