### ISSUE TITLE
Cant switch between instances in wayland

### ISSUE THREAD

**Issue by wandi34** [psifidotos/Latte-Dock#796]
Hi, I am using latte dock 0.7.2 in opensuse Tumbleweed with KDE Plasma in a Wayland session and newest updates installed.

Unfortunately when I have multiple sessions of one application open, I cannot switch from one to the other with latte-dock. Sometimes when clicking on the icon in the dock, the dock just shows the current instance as thumbnail. Sometimes, it shows two thumbnails for my two open instances. But when I click on the other instance, nothing happens.

Are you able to reproduce this?

Nevertheless, I already donated for this dock because it is super helpfull and would do it again! Thanks for your work, keep it up!

**Comment by psifidotos** [comment]
yeah... I know... last time I had checked the kwin effect needed to solve this wasnt working correctly yet...

how does plasma taskmanager solves this? does it show a list to choose?

**Comment by wandi34** [comment]
The plasma taskmanager shows a list which session to choose and it works.

**Comment by psifidotos** [comment]
in plasma taskmanager the window previews do they work correctly?

**Comment by wandi34** [comment]
The taskmanager in wayland just shows me a list of app instances next to the taskmanager icon.

In x session, the taskmanager shows me big thumbnails in the center of the screen of the instances

**Comment by psifidotos** [comment]
@wandi34 isnt this fixed in plasma 5.12?

**Comment by wandi34** [comment]
@psifidotos no it is not. I have tried it with plasma 5.12.1 and openSUSE Tumbleweed.

Steps to reproduce the problem:
1. Open Wayland session
2. Open an application (for example Dolphin)
3. Open another instance of this application (For example open paste bin with dolpin)
4. Click on the Dolphin icon in Latte Dock. It shows two thumbnails for the two instances. But when clicking on one of them, nothing happens.

I'am just able to switch between the instances with KDEs built in taskmanager widget.

**Comment by psifidotos** [comment]
Present Windows isnt supported yet on wayland?

**Comment by wandi34** [comment]
Sry I dont understand what you mean with this. I can just say that switching between several instances of one application is supported by wayland. It just does not look the same as in X.

**Comment by Kolesar** [comment]
On my suse tumbleweed sometimes work double click (I get two thumbnail) and I can click on it, but it is sometimes

**Comment by wandi34** [comment]
@Kolesar unfortunately this is also not working here. Just nothing happens when I click or double click on the thumbnails.

**Comment by psifidotos** [comment]
> Sry I dont understand what you mean with this.

Present windows is the kwin effect that shows all windows  or the selected grouped windows, such as: https://i.ytimg.com/vi/ysGu5fU6oFg/maxresdefault.jpg

**Comment by psifidotos** [comment]
I managed to load wayland in my laptop finally, with nouveau drivers!!! :)

ok... Present Windows isnt implemented yet in wayland...

Have you tried to switch window with the mouse scroll wheel? You can activate it from the Tasks config page

**Comment by wandi34** [comment]
Congratulation :) I believe it must be a hard job after all the horrible things I have read about nvidia and linux. 

Switching instances with the mouse wheel is working. It is a nice workaround till present window will be supported in wayland!

**Comment by psifidotos** [comment]
> Switching instances with the mouse wheel is working. It is a nice workaround till present window will be supported in wayland!

I fixed this in master version... now you can switch through previews in different windows...

**Comment by psifidotos** [comment]
commit: 916629334843cc002b67bc3240eb909ad3818ee9

**Comment by wandi34** [comment]
I'm sorry but I have the same problem with latte dock 0.7.4

**Comment by psifidotos** [comment]
The fix is only in master... i can backport it to v0.7.x

**Comment by psifidotos** [comment]
Sorry , i cant backport it *

**Comment by wandi34** [comment]
Thanks for your fast reply and the great development of latte dock!!!

Sorry, I did not look on the differences between master and 0.7. Its totally up to you, when you want to merge the branches. I trust your skills. Do it when you think it is stable enough.
