### ISSUE TITLE
Black screen problem when switching between desktop

### ISSUE THREAD

**Issue by unc926** [psifidotos/Latte-Dock#797]
Hi @psifidotos 
In unity mode, when switching between the desktop, there is a black divide in the right corner.
**Note**: Transition effect: Desktop cube, (This issue occurs while it is selected)
I compiled the latte from the most recent files about two hours ago.

Preview:
![screenshot_20171215_201214](https://user-images.githubusercontent.com/30185386/34052935-89276b48-e1d5-11e7-8779-9078f7be3475.png)

**Comment by psifidotos** [comment]
I cant reproduce this...
but why do you think that this is Latte issue and not a driver issue or a kwin effect one?

**Comment by unc926** [comment]
@psifidotos Problem-causing, not kwin or drivers
The problem is related to the panel. 
Go to the Configure Desktop section. When you disable the panel animation, there's no problem.

![screenshot_20171215_233430](https://user-images.githubusercontent.com/30185386/34059940-785f1442-e1f2-11e7-9c0a-ef62da70e43b.png)

Here without panel animation

![screenshot_20171215_233326](https://user-images.githubusercontent.com/30185386/34059971-aa565fbe-e1f2-11e7-805b-f6a4728f52db.png)

**Comment by psifidotos** [comment]
> @psifidotos Problem-causing, not kwin or drivers. The problem is related to the panel.

This is definitely a plasma or kwin or driver issue!!! you can report it at: bugs.kde.org

in order to see with plasma panels you can do the following:

1. close Latte
2. Add to Default Plasma Panels, one at the left and one at the top of the screen
3. change desktop and you will notice again the same issue...
