### ISSUE TITLE
crashing with SegFault after undetermined time (libQt5Gui.so)

### ISSUE THREAD

**Issue by acegallagher** [psifidotos/Latte-Dock#799]
plasmashell 5.11.4
kded5 5.41.0
QMake version 3.1
Qt version 5.10.0 

this is running current git sources, with version reported as:

lattedock 0.7.75

I'm having extremely erratic behaviour with latte dock since trying it. It crashes between 30 seconds and 5 minutes for me. I absolutely love the features and I'm using it in a unique way that greatly improves my workflow/screen use. 

Anyway. Here's the ddd/gdb backtrace. Hopefully it's helpful. Let me know if I can provide anything else. The built in debug flag (-d) wasn't providing any information. I should note, if you manage to help me fix this so that I'm using latte-dock regularly I'll probably become a regular bug submitter ;)

![lattedock_debug](https://user-images.githubusercontent.com/25115064/34066280-c4a6dc1e-e1c9-11e7-8266-88545a3383d6.png)

**Comment by psifidotos** [comment]
I updated #147 info, please follow them each one of them in order to test your system...

**Comment by psifidotos** [comment]
@acegallagher there is also the chance to be a plasmoid crash... are you using event calendar plasmoid? because there is a talk for it at: #800

**Comment by acegallagher** [comment]
@psifidotos I am using event calendar. Interesting. It's not in the dock however. That's unfortunate. I use the calendar a lot. I removed the calendar and haven't had a crash since.

@Zren I'm happy to help debugging if I can. I haven't found a way to get the debug info that seems relevant though. The most recent crash I had seems to be stuck in an infinite loop somewhere (backtrace is 1500 lines long). Here's the first 35 lines or so:

![eventcal](https://user-images.githubusercontent.com/25115064/34075517-4999523c-e286-11e7-869f-db51ee7bb029.png)

**Comment by acegallagher** [comment]
Correction. It still crashes for me. Even without event calendar and even with a basic toolbar.

**Comment by Zren** [comment]
Did you start Latte, remove event calendar, then it crashed later on? Or did you start Latte without Event Calendar, then left it and it crashed on it's own?

**Comment by acegallagher** [comment]
Removed event calendar (which was a widget separate from latte-dock on the desktop), deleted the QML cache for latte-dock, then restarted latte-dock. It later crashed on its own.

**Comment by psifidotos** [comment]
Do you use the default layout?

**Comment by psifidotos** [comment]
The suspect plasmoids are those in Latte so event calendar cant be the one.... The crash points to a qml text element... 

Only crash Latte is known to have with external plasmoids is when Latte has a systray and a plasma panel also! So the systray must be either in Latte docks or plasma panels, not both

**Comment by acegallagher** [comment]
I did some more digging. I narrowed it more fully. I have redshift in the systray and any time I turn redshift on or off latte crashes. Let me know if there's a way to dig further.

**Comment by psifidotos** [comment]
I use also redshift in the systray but it doesnt crash.  But we may have different plasmoid versions... isnt that crash occurs also with a lasma panel?

**Comment by psifidotos** [comment]
Question 2: your systray is in a plasma panel or Latte ?

**Comment by psifidotos** [comment]
I tested the redshift-conrol widget in the systray of a plasma panel... it created instability for me by crashing plasma some times while tweaking its settings window...

I dont use plasma panels at all, my systray is in a Latte panel and in there I have enabled the redshift control widget.... I dont know if that would help your system... In case you can reproduce this in your system regularly it would be a good idea to report it upstream because the bug in the redshift plasmoid code either running in a plasma or Latte panel.
https://github.com/kotelnik/plasma-applet-redshift-control

**Comment by psifidotos** [comment]
any update?
