### ISSUE TITLE
Dock does not hide when Spotify is maximized

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#80]
This is strange because dock works ideally. Except when spotify gets maximized dock does not detect that and remains visible. Happens every time. This happens on archlinux with latest packages and revision 8b28fb72fa70d159c48215471eb125f1da80aae4.

**Comment by sebbuku** [comment]
Can confirm, on Kubuntu 16.10.

**Comment by audoban** [comment]
Okay, thanks for the report. I'll fix it right now

**Comment by audoban** [comment]
what mode of visibility do you using?

**Comment by sebbuku** [comment]
The default: dodge active

 
 
  Am So., 22. Jan. 2017 um 21:21 U9r schrieb Smith AR<notifications@github.com>:   
what mode of visibility do you using?

**Comment by audoban** [comment]
Do you can confirm if this also happen with Dodge Maximized?

**Comment by sebbuku** [comment]
Yes. Just tried. Restarted latte dock to be sure.

**Comment by audoban** [comment]
ok, thanks.

**Comment by audoban** [comment]
Sorry for the delay, but it cost me a lot to install spotify.
Well, I can't reproduce this. 
I'm using Spotify `0.9.17.8.gd06432d7` and  `Qt: 5.6.1, KDE Frameworks: 5.26.0, kf5-config: 1.0`

I need more details.

**Comment by rokups** [comment]
I am having issue with `spotify 1.0.47.13-1` (archlinux). Here is output of `xprops`:
```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 1215, 1004, 71, 76
_NET_WM_ICON(CARDINAL) =
WM_CLASS(STRING) = "spotify", "Spotify"
WM_NAME(STRING) = "Spotify"
_NET_WM_NAME(UTF8_STRING) = "Spotify"
XdndProxy(WINDOW): window id # 0x7a00002
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE
_KDE_NET_WM_FRAME_STRUT(CARDINAL) = 0, 0, 29, 0
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 29, 0
_NET_WM_DESKTOP(CARDINAL) = 0
_KDE_NET_WM_ACTIVITIES(STRING) = "59f5cdfb-064c-4220-b9ce-aa9092c6a62a"
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                window gravity: Static
_KDE_NET_WM_USER_CREATION_TIME(CARDINAL) = 3925645
_NET_WM_PID(CARDINAL) = 3850
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "rk-pc"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

Window was maximized:
![maximized](https://cloud.githubusercontent.com/assets/19151258/22240227/09be9890-e212-11e6-85d6-4cc9e067d6e3.png)

Set dock to dodge all windows in the test, also tried other options - neither of them work with spotify but they work normally with other windows. I think i also experienced same issue with `xfreerdp` window btw.

**Comment by sebbuku** [comment]
My software versions:
Spotify version 1.0.44.100
Qt: 5.6.1
KDE Frameworks: 5.28.0
kf5-config: 1.0

Bug persists with the last build from the master branch of Latte-Dock

![image](https://cloud.githubusercontent.com/assets/7261864/22249342/ef1b8526-e242-11e6-86e4-9d0577b718a0.png)

**Comment by sebbuku** [comment]
Debian and Ubuntu .deb installers can be downloaded from http://repository.spotify.com/pool/non-free/s/spotify-client/

**Comment by audoban** [comment]
Ok, I will install the latest version and I test again.

**Comment by audoban** [comment]
ok, now I can reproduce the bug. I'll fix it soon

**Comment by audoban** [comment]
Apparently it is a spotify bug or the KWindowSystem API, because it is impossible to get information of the window type and for this reason Latte ignores the window.

However add exception for spotify by now.

**Comment by sebbuku** [comment]
Fix confirmed. Thank you!
