### ISSUE TITLE
Crash al login

### ISSUE THREAD

**Issue by namkhaib** [psifidotos/Latte-Dock#800]
Hi, I have a crash in the login with latte-dock.
When I login, the dock shows for... 5-7 sec., and after it crashes. If I don't start it in autostart, and I open it after the  login, this don't happen. Also, if I open <code>ddd latte-dock</code>, (in autostart), this also don't happen. I attach my system specs. I have a very bad english, sorry 🙂 

![system specs](https://user-images.githubusercontent.com/33267474/34066467-ffe96c8e-e1dc-11e7-8724-3a5c7e5fd7d3.png)

**Comment by psifidotos** [comment]
I updated #147 info, please follow them each one of them in order to test your system...

If the above dont help, you could try to check if it helps: http://www.mulley.co.uk/2017/05/delay-startup-of-latte-dock-in-kde.html

**Comment by namkhaib** [comment]
@psifidotos with 

> if nothing from the above in order to check if the crash is from a specific plasmoid:
>
>    1. **Use Latte only with default Layout (does it crash?)**
>    2. **If it doesnt crash start adding one by one your plasmoids to check their behavior if the crash Latte...**

the crash solves removing plasmoid <code><a href=https://github.com/Zren/plasma-applets/tree/master/org.kde.plasma.eventcalendar>Event Calendar</a></code>

**Comment by psifidotos** [comment]
ok... you can try to report this to Zren (https://github.com/Zren/plasma-applets/tree/master/org.kde.plasma.eventcalendar) who is an active plasma developer to take care of it...

**Comment by Zren** [comment]
How would I go about debugging this @psifidotos?

`Exec=latte-dock %u &>/home/chris/lattedock.log` in `~/.config/autostart/latte-dock.desktop`? I noticed that there's 0 stdout logging, is there a log file somewhere?

**Comment by psifidotos** [comment]
@Zren latte can provide debug output with -d parameter.
`latte-dock -d` . For Latte crashes I usually point to the users #147...

I have forwarded also one more user for a memory leak from event calendar plasmoid... I dont know if he reached you, to relevant thread can be found here: #776
