### ISSUE TITLE
Latte does not display active shortcuts properly

### ISSUE THREAD

**Issue by daljit97** [psifidotos/Latte-Dock#802]
I have compile and installed Latte on KDE Neon, however I have a strange problem. So I have got some applications shortcuts I dragged onto the dock, but when I click them instead opening a window and make that shortcut active, Latte creates a new entry for the application on the Dock, which is not what I want.

So for example in the screenshot below, when I click on settings it opens a new instance and displays a new shortcut, instead of making the current one active.
![latte screenshot](https://user-images.githubusercontent.com/3147428/34103286-2c534796-e3e4-11e7-9f3b-f8ab5ba6766f.jpeg)

**Comment by psifidotos** [comment]
Latte Settings -> (Advanced options) Tweaks page -> option "Add Launchers only in the specified area" ... is it enabled?

**Comment by daljit97** [comment]
No it's disabled

**Comment by psifidotos** [comment]
1. this option by default is enabled, so you must enable it
2. because the previous option was disabled you added that launchers as applets.
3. If you enabled the option readd the launcher you want
4. If you want to remove the old launchers that behave as applets you can remove them in editing mode (that is when the settings window is shown) from their tooltip

**Comment by daljit97** [comment]
ok so when I enable the option, I cannot drag the shortcuts from the application menu on the dock. And I cannot pin the launchers.

**Comment by psifidotos** [comment]
You can... just drop a launcher there even if you dont see a visual indicator... I hope you didnt remove the Latte Tasks plasmoid.

An alternative way to pin is to just open the application, right click on the task in the dock, and from the context menu shown to pin it.

**Comment by daljit97** [comment]
Ok so I uninstalled Latte using the script. I then deleted the configuration files in ./config. I then proceeded to clone and install the latest version from Github. And no, I cannot drag my launchers to Latte (with "Add Launchers only in the specified area" on). I have tried several times. When I am in settings mode, I cannot see the Latte Tasks plasmoid. Not sure what I am doing wrong.

**Comment by psifidotos** [comment]
Close latte and execute, latte-dock --default-layout   

This will load the default layout with tasks in it and try again...

**Comment by daljit97** [comment]
Ok I have done and the default layout loads, but still unable to drage apps. I have just noticed that Latte creates a blank space when my Terminal is open, I can use that to minimize or switch to the Terminal.

**Comment by psifidotos** [comment]
I am starting to believe your installation is broken... why dont you install Latte from Discovery? Neon provides a prebuilt package...

**Comment by daljit97** [comment]
I have tried looking for Latte on Discover, but it doesn't show up.
![screenshot_20171218_205810](https://user-images.githubusercontent.com/3147428/34127784-457fcfa8-e436-11e7-9e1d-3dd68a6cef92.png)

**Comment by psifidotos** [comment]
Are you using plasma 5.8 and Neon LTS version???

**Comment by daljit97** [comment]
Yes

**Comment by psifidotos** [comment]
You can use only Latte v0.6     ,v0.7 requires plasma 5.9 and above
