### ISSUE TITLE
Adding existing widgets to Latte dock.

### ISSUE THREAD

**Issue by ChrisP4** [psifidotos/Latte-Dock#803]
So, in plasma a great thing when changing stuff a lot is it's easy to keep the same widgets that you've already configured - adding them to new panels or moving them on the desktop is a single drag 'n' drop.

However in Latte dock adding existing plasmoids can't happen like that. Could we add this function?

Also, where are latte's stuff stored? With plank it's ~/home/.config/plank/launchers. Maybe I could copy-paste my existing widgets in the folder where the dock has its configuration files?

Thanks!

**Comment by psifidotos** [comment]
I think it isnt possible but I will check it out again....

The Latte layout configuration can be found in folder, .config/latte

**Comment by psifidotos** [comment]
Ok I checked it... This isnt possible...
