### ISSUE TITLE
Vivaldi snapshot - Latte CPU 99% 

### ISSUE THREAD

**Issue by postadelmaga** [psifidotos/Latte-Dock#804]
Whenever I start Vivaldi snapshot ( installer using aur on arch linux), latte dock start to misbehave and eat my cpu.

Looks the same issue do not happen with normal version on Vivaldi.
I tried to change Vivaldi-snapshot icon and its .desktop file but so far no differences.

**Comment by psifidotos** [comment]
I suppose you must report it to vivaldi also...

**Comment by RibShark** [comment]
I've been getting the same problem without using Vivaldi or any Chromium based browsers, just Firefox. After a while Latte eats up so much CPU the system is practically unusable unless I kill it.

**Comment by psifidotos** [comment]
Are you using firefox nightly? https://bugzilla.mozilla.org/show_bug.cgi?id=1389953

**Comment by psifidotos** [comment]
@postadelmaga when the stable version is out, if the same problem persists i will take a look with the stable version...but probably is just the issue with Firefox nightly... too much X calls from the browser, thus might be for debugging purposes of the browser.

**Comment by RibShark** [comment]
> Are you using firefox nightly?
Nope, Firefox stable. It's Latte that is using the CPU though, not the browsers.

**Comment by psifidotos** [comment]
I use the most recent Firefox daily and I dont have that issue... i cant think what might is happening

**Comment by psifidotos** [comment]
@RibShark @postadelmaga  feel free to test again with latest master and report back...
I uploaded a fix concerning Firefox that is sending X11 events without any reason and now Latte ignores them..
