### ISSUE TITLE
[feature] - Layouts Live Session

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#808]
**Enable Latte to load multiple layouts at the same time...**

Currently Latte is using from plasma libraries the `loadLayout` function to load a file layout. This way everything is in sync with plasma libraries and clean between different layouts.

A Live Layouts Session is a session that all the layouts needed based on the running Activities are loaded at the same time. And when we switch to other layout combination the layouts are updated.

_Current implementation example:_
```
Layouts: A, B, C
Running: B
```

in the above example there are three layouts A,B,C and the running one is B. Changing something to A, C is not possible. Going to C as running would need to unload the B layout and load afterwards the C.

_Live Session equivalent:_
```
Layouts: A, B, C
Running: A, B
```

we will need to load two and more layouts at the same time. For this to be done we need a new intermediate layer so that would look like this:
```
1. Layouts: A, B, C
2. Live Layer: A+B
3. Running: Live Layer
```

1. The Live Layer take the two layouts and combines them into a temporary single one. So the ids in them should be updated in order to not conflict between them... This is already supported a bit when we copy a dock... The ids of the new dock are altered in order to not conflict with the original one.
2. When the Live Layer ends its purpose the updated data of A and B must be restored to layout files A and B
3. (2) and (1) steps are also used when activating new Activities and the combination of the Live Layer must be changed.... e.g. from A+B we need a live session of B+C... in such case we first do (2) and then (1) again... there is no other way to keep the B data active and load only the C ones...

~~(3) has the disadvantage that switching from a Live Session combination to another Live Session combination will take more time... on the other hand switching Activities(thus Layouts) would be instantly as they are already loaded...~~ **(3) can work just perfect based on the implemented multiple-layouts architecture... Any layout can be loaded/unloaded runtime without breaking the rest active layouts.**

**_The proposal of course is that the Live Layer is optional and not default by any means... The user has to enable it in order to activate it...._**

**Comment by psifidotos** [comment]
**Technology Limitations that Latte should work-around:**

- struts from AlwaysVisible panels arent Activity-aware.
- The Latte smart mechanisms in order to automatic place the docks and panels arent activity and struts aware but rather screen only

**Comment by psifidotos** [comment]
![default](https://user-images.githubusercontent.com/2216474/35059620-80692952-fbc4-11e7-811e-57d13d627c89.png)

**Comment by JenaPlinsky** [comment]
@psifidotos 

I state that there is a high possibility that I could say crap :-)

Currently with "Multiple layouts" all layouts are loaded into memory in unison, right? this involves. on my system a considerable slowdown

- I think it is correct to keep only the layouts associated with activities in memory ... is this the case now?

- What do you think of starting to memorize the layout only after the first access to each activity? can it make sense?

- Could it make sense to apply a timeout to dump each layout from memory, after a certain time ?

- I have an activity called "PowerSaving" in this specific case it may be convenient to think about an exception and then, dump all layouts from memory to ensure as many resources as possible for this scope ?



Another thing, currently, with this option enabled, I observe several overlapping docks ... is it a defect of my graphics driver and / or X server?

**Comment by psifidotos** [comment]
> Currently with "Multiple layouts" all layouts are loaded into memory in unison, right?

no

> I think it is correct to keep only the layouts associated with activities in memory ... is this the case now?

no.... only layouts of the Running Activities are pre-loaded... any layouts from the stopped Activities arent loaded until that Activities are started.

> Could it make sense to apply a timeout to dump each layout from memory, after a certain time ?

no... you can just close that Activity in order to unload it...

> I have an activity called "PowerSaving" in this specific case it may be convenient to think about an exception and then, dump all layouts from memory to ensure as many resources as possible for this scope ?

you can just close all the rest Activities and keep only "PowerSaving" as active...

> Another thing, currently, with this option enabled, I observe several overlapping docks ... 


it could be a Latte issue... you could open a different thread to check if any of your layouts became broken... In Single mode when you open the Layouts Editor are any layouts appearing broken?
