### ISSUE TITLE
Sometimes happens to observe a strong flickering above the external separator

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#809]
when the mouse is positioned on the outer separator while the first icon of the launchers area is bouncing .... sometimes happens to observe a strong flickering and it breaks the parabolic effect in the passage between different areas, applets and launchers looking like two bodies unbound

**Comment by psifidotos** [comment]
yeah makes sense based on the codepage... but to solve this... uph....

**Comment by psifidotos** [comment]
@JenaPlinsky bouncing in what sense ? in attention mode or because a new window is added?

I tried with in attention case but I couldnt reproduce...

**Comment by JenaPlinsky** [comment]
I have not well yet understood ... this, it often happened to me when days ago, was repeatedly crashing kactivitymanagerd 

in that case, latte disappeared and reappeared every 2 seconds or so, in an endless cycle. In any case I kept the corrupt sqlite database, maybe I could try again

... to highlight the problem we might think, to a branch with the critical times specially prolonged .... but mainly I had the 'impression that this problem coincides when an application is launched but also when on attention mode I think

**Comment by JenaPlinsky** [comment]
Here is an interesting video made with the corrupt kactivitymanagerd
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1585734/video.zip)
Do you understand something? ... not me :(

**Comment by psifidotos** [comment]
> Do you understand something? ... unfortunately, I do not :(

me neither... When kactivitymanagerd is broken no issue is considered valid because **kactivitymanagerd should never broke!!!**, that applies to plasmashell also... the issue is this:  **kactivitymanagerd should never broke!!!** ... if you manage to reproduce this issue in a working system feel free to reopen.

**Comment by JenaPlinsky** [comment]
... I'm asking you just to be sure ... Have you understood the right purpose of the video ?

this was to highlight the flicker of the dock **or, rightly, you claim that this abnormal behavior may depend on something unrelated to the proper functioning of the plasma**? 

In any case, if I'm not mistaken, I also encountered this problem in another couple of circumstances that I could not document

**Comment by psifidotos** [comment]
> rightly, you claim that this abnormal behavior may depend on something unrelated to the proper functioning of the plasma?

yes

> if I'm not mistaken, I also encountered this problem in another couple of circumstances that I could not document

feel free to reopen if you fall again in such case and we can reproduce

**Comment by JenaPlinsky** [comment]
Do you believe that the latest commits introduced may have improved the issue? 
do I have to test them with the corrupt file mentioned above **or does it make no sense**?

**Comment by psifidotos** [comment]
> Do you believe that the latest commits introduced may have improved the issue?

I dont know

> do I have to test them with the corrupt file mentioned above or does it make no sense?

makes no sense

**Comment by JenaPlinsky** [comment]
even if it did not make sense, I wanted to make a comparison after the last commits

and I must say that the situation has improved a lot

look  
[corrupted_before_last_commits.zip](https://github.com/psifidotos/Latte-Dock/files/1586008/corrupted_before_last_commits.zip)
and
[corrupted_after_last_commits.zip](https://github.com/psifidotos/Latte-Dock/files/1586007/corrupted_after_last_commits.zip)

**Comment by psifidotos** [comment]
good to see! ;)
there are also more improvements scheduled for separators in the future...

**Comment by JenaPlinsky** [comment]
on the bug report of kactivitiesmanagerd I glued the corrupt file maybe it could be useful to understand the cause
