### ISSUE TITLE
rename Latte's configuration files

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#81]
currently Latte configuration files are named"

- Latte Dockrc
- Latte Dock-appletsrc

I propose to rename that at:

- lattedockrc
- lattedock-appletsrc

if we agree... the sooner the better in my opinion, before the user base starts to increase a lot !!!

**Comment by audoban** [comment]
ok, I'm agree, no problem.

**Comment by psifidotos** [comment]
**IMPORTANT FOR USERS**

_**If you dont want to lose your configuration after updating to this commit you should do the following!!!!**_

**_Go to **.config** directory after you close Latte Dock and rename file:_**

**Latte Dock-appletsrc**  _into_ **_lattedock-appletsrc_**

**Comment by audoban** [comment]
> IMPORTANT FOR USERS
If you dont want to lose your configuration after updating to this commit you should do the following!!!!
Go to .config directory after you close Latte Dock and rename file:
Latte Dock-appletsrc into lattedock-appletsrc

This note we will put it in CHANGELOG of the following version.
