### ISSUE TITLE
Thumbnails windows and contextual menu sometimes overlapping

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#811]
The thumbnails windows, should never exist in the presence of a contextual menu.
There is a way to force the tooltip to close, perhaps with a delay if the problem is due to almost simultaneous events

**Comment by psifidotos** [comment]
can you show me  a video how you produce this issue?

**Comment by JenaPlinsky** [comment]
I'm sorry ..... a bug with the context menu prevents me from testing

**Comment by JenaPlinsky** [comment]
in any case it is a rather random coincidence and I do not know how to recreate it

this very little defect exist for a long time now

**Comment by psifidotos** [comment]
I can add a timer in case a preview first shown to check if there is also a context menu shown... but I want to be sure that solves the issue...

**Comment by JenaPlinsky** [comment]
as soon as possible I test it
...it happened quite often so, we will immediately notice if it has improved

**Comment by JenaPlinsky** [comment]
it seems to me that dock work fine !!!!

the context menu as it behaved before now, did it have a time out?

the parabolic effect, was it active even in the presence of the contextual menu ?

now the dock remains freezed until the contextual menu disappears ?

was it so even before? I do not remember

**Comment by psifidotos** [comment]
> the context menu as it behaved before now, did it have a time out?

I think not

> the parabolic effect, was it active even in the presence of the contextual menu ?

no

> now the dock remains freezed until the contextual menu disappears ?

yes

> was it so even before? I do not remember

yes
