### ISSUE TITLE
Export an even more complete Latte configuration

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#814]
Here I write some of my considerations that could also be a bit confused

When I export a complete latte configuration ...
in that file are saved all the layouts and the relative ID of the activities to which they are associated, right?

As often, in these days, it happened to me, to be forced to delete the corrupted SQLite3 database of  kactivitymanagerd or for those that for some reason have to delete the contents of the .local or .config folders

happens **to lose all the settings related to the latte's pinned apps** and even **those related to the default plasma panel**
does it works this way, right ?

 it is quite frustrating, every time, to find myself with the need to re-set, all the pinned apps and the plasmoids of the desktop
especially when using a lot of activities, that I find incredibly comfortable because they mainly keep me focused on the work I am doing without unnecessary distractions.

I wonder, if you have in mind some solution to save in the configuration file **also the content of the database related to the pinned apps**, or maybe, for each exports,  do the back up of that database to then retrieve its content at each import of the latte's full configuration

just to clarify my ideas:

- the activity configuration file contains the ids for each activity, if you delete kactivitymanagerd, as soon as necessary, a new database is created, the ids of the activities that are contained in it match with those I had previously or I risk of finding myself an inconsistency with those ID ?

- where are the data related to latte's pinned apps stored ?

- where are the data related to the plasma's pinned apps stored ?

**Comment by psifidotos** [comment]
Latte doesnt have to lose anything... it can export each layout and its full configuration also...

For plasma i dont know...
