### ISSUE TITLE
Copy dock for activity

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#815]
To better replicate the primary display on the external display, Why not insert a new item, such as "copy for activities", to allow you to copy the respective dock of each activity eg. "Bottom" by iterating on all activities?
![screenshot_20171226_130837](https://user-images.githubusercontent.com/24593950/34356499-8730108a-ea3e-11e7-9de0-ae2a288cbbe7.png)

**Comment by psifidotos** [comment]
I think that i have discussed this again in the past... my opinion is that this isnt important in order to add it...
