### ISSUE TITLE
Dock consuming 50% of cpu

### ISSUE THREAD

**Issue by anshulgoyal15** [psifidotos/Latte-Dock#818]
The dock is consuming 2 core of cpu making system lag

**Comment by trmdi** [comment]
You should provide more info such as:

- What distro ? What version ?
- How to reproduce the lag ?

**Comment by anshulgoyal15** [comment]
Just hover over the dock multiple time in a row ,
On kubuntu 17.10,plasma 5.11.4

**Comment by trmdi** [comment]
What is the version of Latte-dock ? Did you try the latest version ?

**Comment by anshulgoyal15** [comment]
Yes I cloned the master branch

**Comment by psifidotos** [comment]
1. any chance to be plasmoid? Are you using default layout?

2. Is firefox or vivaldi window open?

**Comment by anshulgoyal15** [comment]
no
