### ISSUE TITLE
[Crash] - with the check box in wether plasmoids

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#82]
![screenshot_20170118_042655](https://cloud.githubusercontent.com/assets/24593950/22049925/0b35723c-dd37-11e6-95ea-4ecec56949c2.png)
![screenshot_20170118_042622](https://cloud.githubusercontent.com/assets/24593950/22049937/18e612c4-dd37-11e6-973f-bfd5910e8384.png)

I get a crash by setting "render meteogram"
![screenshot_20170118_042417](https://cloud.githubusercontent.com/assets/24593950/22049942/1bae5214-dd37-11e6-875a-3393117703ad.png)

**Comment by psifidotos** [comment]
I can not reproduce it

**Comment by JenaPlinsky** [comment]
always keep in mind, that I use factory packages (unstable)

distro openSUSE thumbleweed
Plasma 5.8.85
Framework 5.31.0
QT 5.7.1
kernel 4.8.3.1 Vanilla
64 bit
latte-dock Version 0.5.91 Alpha installed from RPM

**Comment by JenaPlinsky** [comment]
This bug does not exist anymore
