### ISSUE TITLE
[feature] - Allow ungrouped tasks

### ISSUE THREAD

**Issue by TieSKey** [psifidotos/Latte-Dock#821]
Consider adding an option to avoid grouping task/app icons globally or by app as the regular icon-only task manager from kde. (The reason I'm not using the kde task manager is its inability to center icons)

That's all. Keep up the good work ;)

**Comment by psifidotos** [comment]
I think the by app option is supported... Tasks -> Actions. Set for an action to group/ungroup tasks.

**Comment by TieSKey** [comment]
Found it and works well. 
I'd certainly expect that to be on the context menu rather than having to map it to one of the only 2 extra actions available though.

**Comment by nanokatz** [comment]
Can you explain where you found this? I am running the latest git version and do not have an "Action" section in the tasks option page.

**Comment by psifidotos** [comment]
> Can you explain where you found this? I am running the latest git version and do not have an "Action" section in the tasks option page.

activate the "advanced" option at the top right corner... Latte has plenty "advanced" options hidden... There is also in the v0.7 version not only the git one...

**Comment by nanokatz** [comment]
Hmm I do have that enabled. I've attached somescreen shots to show you what I do have in case I am just in the completely wrong area 
![screenshot from 2018-01-06 13-05-33](https://user-images.githubusercontent.com/22838757/34639577-6ee55204-f2e2-11e7-86cc-bbb8888b17ca.png)
![screenshot from 2018-01-06 13-05-56](https://user-images.githubusercontent.com/22838757/34639578-6f3df788-f2e2-11e7-990b-8e3844225714.png)
![screenshot_20180106_125955](https://user-images.githubusercontent.com/22838757/34639579-6f97a882-f2e2-11e7-8930-be63854509f6.png)

**Comment by psifidotos** [comment]
yeah you are right... that is the place... 
the option in the comboboxes is called: Toggle Task Grouping

**Comment by nanokatz** [comment]
Oh god i'm blind. I did't actually ever check the options in that combo box. I guess in trying to take the screenshots i changed it witout noticing.
Sorry to be a bother!
