### ISSUE TITLE
How can I to disable the task indicators ?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#822]
Am I trying to re-create a panel like the opensuse's standard  one, is it possible to have an option to disable the task indicators

![screenshot_20180101_180607](https://user-images.githubusercontent.com/24593950/34469590-f1888ac8-ef22-11e7-9bf2-70df3e26d538.png)

**Comment by psifidotos** [comment]
Remove Latte plasmoid and add them as applets
