### ISSUE TITLE
Impossibile to pin the wine's (un-grouped) programs

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#823]
Impossibile to pin the wine's (un-grouped) programs  and its icons appear pixelated

[video1.zip](https://github.com/psifidotos/Latte-Dock/files/1596333/video1.zip)
[video2.zip](https://github.com/psifidotos/Latte-Dock/files/1596334/video2.zip)

**Comment by psifidotos** [comment]
report upstream to kde

**Comment by psifidotos** [comment]
I dont know you might can handle this with PlayOnLinux. At least this is how I am doing it:

1. I install the app with PlayOnLinux
2. I create a desktop file from PlayOnLinux for that app
3. The desktop file is located in Desktop folder so I move it to ~/.local/share/applications

that's it afterwards that app is opened correctly and set up to activities... at least this is happening for those wine desktop files that are correct set e.g. for PokerStars in my system that looks like:

```
[Desktop Entry]
Encoding=UTF-8
Name=PokerStars
Comment=PlayOnLinux
Type=Application
Exec=/usr/share/playonlinux/playonlinux --run "PokerStars" %F
Icon=~/.PlayOnLinux//icones/full_size/PokerStars
Name[fr_FR]=PokerStars
StartupWMClass=PokerStars.exe
Categories=
```

**Comment by MattMcHackit** [comment]
Hi

I'm having the same problem. I have copied the .desktop file for a Wine app (Word 2010) to ~/.local/share/applications and launch it from that location. I'm still unable to pin it. File content is as follows:
`[Desktop Entry]
Encoding=UTF-8
Name=Microsoft Word 2010
Comment=PlayOnLinux
Type=Application
Exec=/usr/share/playonlinux/playonlinux --run "Microsoft Word 2010" %F
Icon=/home/matthew/.PlayOnLinux//icones/full_size/Microsoft Word 2010
Name[fr_FR]=Microsoft Word 2010
StartupWMClass=WINWORD.EXE
Categories=
`
I have it set to ungrouped, so not sure where I am going wrong?

**Comment by psifidotos** [comment]
me neither ... this is plasma libtaskmanager responsibility... you will have same issue with plasma taskmanagers....

You can report at bugs.kde.org

**Comment by MattMcHackit** [comment]
Just tried removing all spaces from the .desktop file's name... and it pins! However, it acts only as a launcher and a separate icon appears for the task on launch.

**Comment by MattMcHackit** [comment]
Problem was completely resolved by changing to the developer stable branch of Neon -- plasma 15.12.90 and up do not have this problem :-)
