### ISSUE TITLE
Small redraw defects

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#826]
![screenshot_20180103_093725](https://user-images.githubusercontent.com/24593950/34513848-9a2fa628-f06a-11e7-925c-48afc8b58c0c.png)
![screenshot_20180103_093625](https://user-images.githubusercontent.com/24593950/34513847-9a09d114-f06a-11e7-8672-6cfedda7a695.png)

---------------------------------------------------------------------------------------------------------------------------------

![screenshot_20180103_094537](https://user-images.githubusercontent.com/24593950/34514036-99d03e26-f06b-11e7-87d4-d842c02be653.png)
![screenshot_20180103_095352](https://user-images.githubusercontent.com/24593950/34514251-cd75b02a-f06c-11e7-89cb-2c72e4625f8d.png)

---------------------------------------------------------------------------------------------------------------------------------

![screenshot_20180103_095025](https://user-images.githubusercontent.com/24593950/34514039-9a26d222-f06b-11e7-9b9e-ce637d43300d.png)
![screenshot_20180103_095231](https://user-images.githubusercontent.com/24593950/34514276-f29aa374-f06c-11e7-891f-22dfe7b00d37.png)

---------------------------------------------------------------------------------------------------------------------------------

![screenshot_20180103_094743](https://user-images.githubusercontent.com/24593950/34514038-9a04044a-f06b-11e7-9844-61c38d2e0b6b.png)
![screenshot_20180103_095701](https://user-images.githubusercontent.com/24593950/34514313-2b9e7fec-f06d-11e7-8871-8b981d8aa6bd.png)

---------------------------------------------------------------------------------------------------------------------------------

**Comment by psifidotos** [comment]
change plasma theme... it seems broken...

**Comment by JenaPlinsky** [comment]
Ohhhh yeah it totaly depend on the plasma theme
