### ISSUE TITLE
How to show the tasks combined with activities 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#827]
![screenshot_20180103_133333](https://user-images.githubusercontent.com/24593950/34520848-f9a92cc6-f08a-11e7-8339-1091320a045f.png)

About the checkbox "shows only the tasks of the current activity", I think I'm observing a different behavior between the Latte's tsak manager and that of the icononly's taskmanager

- when disabled, the icononly's task manager shows all the **opened tasks** of all the activities

- when disabled, the icononly's taskmanager shows all the **pinned tasks** of the all activities ... which does not seem to make any practical sense and makes it so the super populated dock

![screenshot_20180103_133128](https://user-images.githubusercontent.com/24593950/34520766-8a3404f6-f08a-11e7-8506-aec1bf480c93.png)

my personal opinion is that of the icononly's taskmanager and why not, with a hot key to quickly toggle between "all activities" and "current activity" and thus having, if necessary, a live view of the tasks spread between the various activities

**Comment by psifidotos** [comment]
I cant understand, what is the difference between Latte taskmanager and icon-only taskmanager?

**Comment by JenaPlinsky** [comment]
In Latte are shown all open tasks and pinned launchers for all activities instead, in IconOnly, are shown only the opened tasks ...the pinned launchers are not shown

**Comment by psifidotos** [comment]
> the pinned launchers are not shown

yes they do

**Comment by JenaPlinsky** [comment]
Normally icononly, it is used, when it is docked on the default plasma panel and behaves **exactly like Latte**.

I have confused the things a bit, because the thing I described above,  happen only **when icononly is docked on Latte**, so they are special cases !!!!!!.

      In this activity [A] Blender is pinned 
   ![screenshot_20180103_165059](https://user-images.githubusercontent.com/24593950/34527583-47a50c0e-f0a6-11e7-89bf-e28718da1175.png)

      here Blender is not shown even if it is pinned on [A] 
   ![screenshot_20180103_164437](https://user-images.githubusercontent.com/24593950/34527515-10996c8c-f0a6-11e7-9de3-3afd87c70914.png)

I state, that this is my personal consideration
In any case it would not be better if the task manager shows only the pinned tasks of the current activity and in addition the open tasks of all the activities? basically now as now I would get the same result if each launcher was anchored con "on all activities"
non è quindi piu conveniente avere in questo caso una visione generale dei tasks piuttosto che dei launchers ? se poi uno volesse pinnare come globale un lanucher può sempre utilizzare "pin on all activities"

**Comment by psifidotos** [comment]
> only when icononly is docked on Latte, so they are special cases !!!!!!.

not in my system

> in any case it would not be better if the task manager shows only the pinned tasks of the current activity and in addition the open tasks of all the activities? 

no idea, i dont find important and I dont see any difference between Latte taskmanager and plasma taskmanager in my system... both of them behave the same at all circumstances.
