### ISSUE TITLE
Is possible make the the tool-tip's navigation a bit more comfortable?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#829]
I know it's a minor thing ....

Currently, when trying to activate a grouped windows preview tool-tip, since the underlying parabolic effect remains (rightly) active, it is easy to slip slightly to the side and drop down the previews. I wondered if it was possible to make everything a little less sensitive to the path of the mouse

![screenshot_20180105_191106](https://user-images.githubusercontent.com/24593950/34624145-7aebf4e2-f254-11e7-9ed5-77f8ce4fe9f7.png)

**Comment by psifidotos** [comment]
Sorry  not possible, only thing you can done is to increase the applet margins from Appearance settings

**Comment by JenaPlinsky** [comment]
No problem it's great anyway ;)

**Comment by JenaPlinsky** [comment]
@psifidotos 
Do you think could possible, even in this case, to use a timer as a filter to filter the out-focus?

with something like this ...
drop the grouped windows preview tool-tip only if the task has lost its focus for T time AND if out of the tool-tip

**Comment by psifidotos** [comment]
sorry, I dont like the idea...
