### ISSUE TITLE
Configuration window cuts off the translation string

### ISSUE THREAD

**Issue by omni6** [psifidotos/Latte-Dock#831]
Hi,

i noticed this behavior 

![latte_config](https://user-images.githubusercontent.com/24492439/34688043-0bff0c18-f4b1-11e7-9320-6ad292a3dc73.png)

Do i have to shorten the string or has the window resize to proper fit?

Some of other languages should have the same issue:

+"Einfarbigen Hintergrund für eingerastete oder maximierte Fenster erzwingen"
 "Força un fons sòlid per a les finestres maximitzades o ajustades"
 "Força un fons sòlid per a les finestres maximitzades o ajustades"
 "Εξαναγκασμός συμπαγούς φόντου για μεγιστοποιημένα παράθυρα"
 "Force solid background for maximised windows"
 "Mostrar fondo solo para las ventanas maximizadas"
 "Forza sfondo solido per le finestre massimizzate o agganciate"
+"Wymuś jednolite tło dla zmaksymalizowanych lub przszczypniętych okien"
 "Forçar um fundo sólido para as janelas maximizadas ou ajustadas"
 "Показывать фон только для распахнутых окон"
 "Tvinga ifylld bakgrund för maximerade eller bundna fönster"
+"Примусово суцільне тло для максимізованих або прилиплих вікон"
 "xxForce solid background for maximized or snapped windowsxx"

  

btw: I opened a request to add latte to kde bugtracking system. I think it is better you provide the requested informations.  https://phabricator.kde.org/T7715

**Comment by psifidotos** [comment]
> Do i have to shorten the string or has the window resize to proper fit?

the window doesnt have such resize... you should probably shorten the string

> I opened a request to add latte to kde bugtracking system. I think it is better you provide the requested informations. https://phabricator.kde.org/T7715

yeah, no prob... but it will take some days

**Comment by omni6** [comment]
my reviewer doesn't accept the shortened string, he wrote that it will cause problems, also for other languages, if this will not fixed in general. 
> "Fixed layout is evil"

Other concerns were about changing the font of fontsize, but i have tested it and in this case latte is flexible. Maybe there is a maximum character count? 
This could be a solution:
https://techbase.kde.org/Development/Tutorials/Localization/i18n#Adding_Context_with_i18nc.28.29

**Comment by psifidotos** [comment]
> Maybe there is a maximum character count?

the algorithm  counts the font metrics and sets the width of the settings window at around 28-29 characters, To auto-adjust the size of the window based on the contents is not a solution because afterwards many animations probably would break. What it would work well and I could accept is to break the checkbox's text to two lines whenever that is needed... But I fear that QML checkbox elide's the text "..." instead of breaking it to two lines...
I suppose I could workaround it by creating my own checkbox but there are many things that could break e.g. tooltips.

**Comment by psifidotos** [comment]
@omni6 if you try to add a character '\n' in the translated text in order to break the text in two lines isnt the reviewer accepting it?

**Comment by omni6** [comment]
i believe we have used \n only for tooltips yet. you think it is possible?

**Comment by omni6** [comment]
btw: is there a way to compile my translation locally into latte? Then i could check cases like this without the danger to break something...

**Comment by psifidotos** [comment]
> btw: is there a way to compile my translation locally into latte? Then i could check cases like this without the danger to break something...

I dont know any...

it would look like this if you used '\n' :

![default](https://user-images.githubusercontent.com/2216474/34737070-a8826a7c-f57d-11e7-85de-f3a2adeb704c.png)

**Comment by omni6** [comment]
Ok, we've done this. 
But to avoid confusion for later reviewers or translators it would be nice if you could add a contect to your code with 18nc(). 
Something like: 
If your string is too long use \n otherwise it will not be completely shown..!?

**Comment by psifidotos** [comment]
@omni6 I found a different solution.., I provided a Latte specific checkbox style for that checkbox... I dont want to use it at all checkboxes only to those with big strings... So you can translate it without '\n', it should look like this now, that provides better alignment:

![default](https://user-images.githubusercontent.com/2216474/34740095-f71b17de-f586-11e7-8b05-935a830ab139.png)

**Comment by omni6** [comment]
wow nice, thank you!
