### ISSUE TITLE
Sometimes the icon jumps up but it doesn't fall down

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#833]
Like this:
![image](https://user-images.githubusercontent.com/11857205/34730619-83f9c9e2-f592-11e7-85bf-ec1266336d93.png)

It just falls down after a long time.
I'm using the latest git version 0.76 on openSUSE Tumbleweed.

**Comment by psifidotos** [comment]
it happens when that window requests Attention
