### ISSUE TITLE
Missing "Alternatives" in Widget right-click menu ?

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#834]
This is the Plasma panel:
![image](https://user-images.githubusercontent.com/11857205/34877470-c3fc05bc-f7d8-11e7-89a8-ec66efcc1354.png)

This is the Latte's one - **can it have the Alternatives line ?**
![image](https://user-images.githubusercontent.com/11857205/34877493-e06fc5d0-f7d8-11e7-92d7-44f8dfb1d135.png)

**Comment by psifidotos** [comment]
try in "Edit Mode" for Latte, this is when showing the config window

**Comment by trmdi** [comment]
Thank you, I see it.
