### ISSUE TITLE
unable to make latte dock

### ISSUE THREAD

**Issue by anshulgoyal15** [psifidotos/Latte-Dock#836]
-- Could NOT find KF5NewStuff (missing: KF5NewStuff_DIR)
-- Could NOT find KF5NewStuff: found neither KF5NewStuffConfig.cmake nor kf5newstuff-config.cmake 
CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: NewStuff) (found suitable version "5.41.0",
  minimum required is "5.29.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:21 (find_package)

**Comment by trmdi** [comment]
> Could NOT find KF5NewStuff 

What distro are you using ?

**Comment by anshulgoyal15** [comment]
KUbuntu 17.10

**Comment by trmdi** [comment]
https://github.com/psifidotos/Latte-Dock/pull/835

**Comment by anshulgoyal15** [comment]
Thanks
