### ISSUE TITLE
Dock showing a red label with white cross

### ISSUE THREAD

**Issue by Pafzedog** [psifidotos/Latte-Dock#837]
My system:

Ubuntu 17.10
Plasma Version: 5.10.5
KDE Frameworks Version: 5.38.0
Qt Version: 5.9.1
Kernel Version: 4.13.0-25-generic
OS Type: 64-bit

lattedock 0.7.76 from ppa:rikmills/latte-dock

here is the log when launching with: latte-dock -d

```
~$latte-dock -d
[warning 13:20:19.456456] - WARNING: Cannot find style "org.kde.desktop" - fallback: "/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Desktop"
[warning 13:20:19.632632] - trying to show an empty dialog
[warning 13:20:19.646646] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 13:20:19.646646] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:46: TypeError: Cannot read property 'DateTime' of undefined
[warning 13:20:19.646646] - file:///usr/share/plasma/plasmoids/org.kde.plasma.analogclock/contents/ui/analogclock.qml:47: TypeError: Cannot read property 'DateTime' of undefined
[warning 13:20:19.650650] - trying to show an empty dialog
[warning 13:20:19.668668] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/TextArea.qml:941: TypeError: Cannot read property '__cursorHandle' of null
[warning 13:20:19.668668] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/TextArea.qml:905: TypeError: Cannot read property '__selectionHandle' of null
[warning 13:20:19.668668] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 13:20:19.668668] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 13:20:19.668668] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 13:20:19.668668] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
```

There is an error message a top of the dock:

> Erreur du chargement du fichier QML : file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1367:26: WindowsModel is not a type

![screenshot_20180114_132541](https://user-images.githubusercontent.com/8932092/34915890-961031f8-f92e-11e7-8042-fe11424102ee.png)

**Comment by psifidotos** [comment]
this file is outdated from our master version:

` file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1367:26: WindowsModel is not a type
`

either you dint install correctly or the package is broken

**Comment by Pafzedog** [comment]
So package must be broken because I installed it from a ppa, and I'm using it since several months but suddenly this error show up.
What can I do ?

**Comment by psifidotos** [comment]
1. uninstall / reinstall , the same thing happens?
2. if it continues you should contact the packager

**Comment by Pafzedog** [comment]
1. this is the first thing I did, same issue.
2. so I will contact the packager.

thx
