### ISSUE TITLE
Global Menu not working properly when Applet Shadows is on

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#838]
I noticed that global menu isn't showing every menu when applet shadows is on.
![screenshot_20180120_234654](https://user-images.githubusercontent.com/18561627/35188459-30b22e8c-fe3e-11e7-9f6e-afa1281303dc.png)
![screenshot_20180120_234532](https://user-images.githubusercontent.com/18561627/35188460-30dd72fe-fe3e-11e7-88e0-ee4f7b840112.png)

What should be displayed is this but with shadow around it
![screenshot_20180120_234754](https://user-images.githubusercontent.com/18561627/35188466-5464cb6e-fe3e-11e7-8964-4bccdd0ce875.png)

Is this a known issue?

**Comment by psifidotos** [comment]
Are you using plasma version or Active Window Control?

**Comment by Petross404** [comment]
The second.

**Comment by psifidotos** [comment]
are you using Active Window Control with FillWidth or specific pixels size?

**Comment by psifidotos** [comment]
and now the funny part... :)

you believe that the **non-shadows** is the correct one but the correct one is the **shadows-one**. I reproduced by setting specific size to AWC. But if the AWC has specific size then it shouldnt show contents that are out of its limits (that is the non-shadow case).

If you enable to your AWC to Fill Width from its options then the issue is gone...

**Comment by psifidotos** [comment]
Look what can happen because of this, I think this should be reported to AWC developer:

![default](https://user-images.githubusercontent.com/2216474/35192984-8bf29294-fea4-11e7-80af-776f0df48329.png)

**Comment by Petross404** [comment]
Let me test this, I will report back. Thanks.

**Comment by psifidotos** [comment]
@Petross404 btw what is your plasma theme?

**Comment by Petross404** [comment]
Under "Look and Feel" I am using the Breeze theme. 

You are right, it's not latte's fault. I will report this. Strange though...

**Comment by Petross404** [comment]
With Short Date : 
![screenshot_20180121_123207](https://user-images.githubusercontent.com/18561627/35193164-9632dc0c-fea7-11e7-85be-3d00acbee71b.png)

With Long Date : 
![screenshot_20180121_123454](https://user-images.githubusercontent.com/18561627/35193165-965bf07e-fea7-11e7-8e4e-e666bb1612d5.png)

No other application needs all this space like KDevelop does. So I am lucky here. But anyway what should be reported isn't that some screens are smaller (ie in a laptop) and thus the applets override, but the "Width in horizontal panel" malfuction.

**Comment by Petross404** [comment]
> are you using Active Window Control with FillWidth or specific pixels size?

I was using pixel size. About 1/5 or 1/4 of the slider's full length on my 22" monitor.
