### ISSUE TITLE
Main config window overlaps secondary config window

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#839]
![screenshot_20180121_235229](https://user-images.githubusercontent.com/24593950/35200080-febdbaac-ff07-11e7-8244-f22988e80222.png)

**Comment by psifidotos** [comment]
Nothing to do with MultipleLayouts, what is your screen resolution?

**Comment by Petross404** [comment]
Yes, what is your wallpaper too? :p

**Comment by psifidotos** [comment]
the resolution is 1366x768 based on the screenshot...

**Comment by JenaPlinsky** [comment]
Yep it is 1366x768

**Comment by psifidotos** [comment]
I think that for resolutions <=1366x768 the secondary config window will be disabled...

**Comment by JenaPlinsky** [comment]
I suppose you mean only for the docks placed on the sides and <= 768

**Comment by psifidotos** [comment]
I can make it to 1024 for width and 768 for height  in order to not show it at all... but there is still the question what is going to happen in such case...

- are the Dock/Panel options wont provided at all or the secondary config window should be shown elsewhere... I must think it over...

**Comment by JenaPlinsky** [comment]
I wonder ... but it would not be enough to move everything a little higher ... it seems to me that there is enough space, at least for that resolution

**Comment by psifidotos** [comment]
> it seems to me that there is enough space, at least for that resolution

I wont add any calculations for overlapping config windows and free space to reposition... neither I like to have it in the first window if that doesnt look nice... so it will probably be ugly...
