### ISSUE TITLE
Strange flickering with an inexplicably duplicated launcher 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#840]
Please use dragonplayer, vlc can not play the video
- with the launcher "kcalc" inexplicably duplicated, I observe a strange flicker at the second 3
- if I close and re-open Latte the doubled launcher disappears and everything returns to normal

[2.zip](https://github.com/psifidotos/Latte-Dock/files/1653190/2.zip)

**Comment by psifidotos** [comment]
@JenaPlinsky without a way to reproduce such issues cant be fixed...

**Comment by psifidotos** [comment]
@JenaPlinsky are you using global launchers or unique ones?

**Comment by JenaPlinsky** [comment]
@psifidotos I'm using the global

**Comment by psifidotos** [comment]
Can you provide your lattedockrc?

**Comment by JenaPlinsky** [comment]
[lattedockrc.txt](https://github.com/psifidotos/Latte-Dock/files/1653669/lattedockrc.txt)

**Comment by psifidotos** [comment]
@JenaPlinsky nothing special for kcalc in it...

**Comment by JenaPlinsky** [comment]
I have to be more careful if it happens to me again, maybe I'll provide the rc file, of that precise moment
