### ISSUE TITLE
Garbled graphics on wake with nvidia proprietary + compositor

### ISSUE THREAD

**Issue by GorrillaRibs** [psifidotos/Latte-Dock#841]
On my laptop (GTX 1070 mobile, so a fairly new card) I am running KDE plasma 5.11.5 on Manjaro (started as Manjaro Gnome and later switched to KDE, if that matters). Latte works wonderfully when I start it up, and is generally better looking and snappier than the plasma panel for me, however whenever I wake my computer from suspend most of the icons on my dock (seemingly a random number) have garbled, multicolored pixels appearing on them, as well as a white box when I mouse over them instead of the proper animation (a slight brighter fade). I am currently using i3wm within KDE, but the issue persists whether using i3 or kwin, and it only seems to be an issue when I have compositing enabled (whether with kwin itself or compton with i3). The widgets on my dock (system tray, pager and an application launcher) seem unaffected, and the KDE panel's task manager widgets are also unaffected. Is this a known issue with nvidia graphics cards, and can in be solved within latte dock or is it a compositor issue? I am unsure if latte has any sort of logs I can attach, but I have attached my current latte config and a screenshot of the issue. I can reproduce the issue by suspending and resuming, but given how little I can find about it I'm unsure if it's easily reproducable outside of nvidia graphics. Thanks in advance!
![github](https://user-images.githubusercontent.com/16048044/35254380-ec293f28-ffb7-11e7-91bd-1f37d0153fa9.png)

**Comment by psifidotos** [comment]
It happens to me also, kwin devs flag it as an upstream NVidia proprietary driver issue....
