### ISSUE TITLE
Dodge Window not properly working on wayland (multiple desktops)

### ISSUE THREAD

**Issue by portaloffreedom** [psifidotos/Latte-Dock#842]
Hi! I'm using latte-dock 0.7.3 on Archlinux with Plasma on a Wayland session.

I really like the dodge active feature on the dock, but somehow is not working properly. I have a 2x2 workspace configuration and I've noticed that the dodge active feature works only in the first workspace, while in all the other workspace it just stays always shown.

Can you check if you are able reproduce this?

**Comment by portaloffreedom** [comment]
update, if I fix the window to be present in all workspaces, normal behaviour is restored for that window. 
A quick deduction would tell me that latte is checking the collision of the window only in the first workspace area, but I could be wrong.

Attached screenshots are in workspace 4, in the second image I fixed the window in all screens. 
![screenshot_20180125_181456](https://user-images.githubusercontent.com/1150666/35402111-d1bde9f4-01fb-11e8-9090-f816debd3203.png)
![screenshot_20180125_181519](https://user-images.githubusercontent.com/1150666/35402112-d1df9f2c-01fb-11e8-95b1-0bb77344ece3.png)

**Comment by psifidotos** [comment]
this is because Plasma is not supporting yet fully virtual desktops in wayland... the plasma pager case...

**Comment by psifidotos** [comment]
@portaloffreedom in wayland the filtering of tasks in your taskmanager does it work properly if you enable to filter windows by desktop?

**Comment by portaloffreedom** [comment]
@psifidotos You intuition is right, it's completely ignoring the setting. If filtering by desktop is enabled, all windows are showed like before.

It's not showing only the windows in the first workspace, but all of them.

**Comment by portaloffreedom** [comment]
@psifidotos You intuition is right, it's completely ignoring the setting. If filtering by desktop is enabled, all windows are showed like before.

It's showing **all** of the windows, not only the ones in the first workspace.
