### ISSUE TITLE
Flickering when the last task is bouncing with no other tasks after it

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#843]
When konversation icon is in attention mode, I can observe a "always reproducible" strange flickering, when the mouse hover the border area between these two icons
![screenshot_20180127_150210](https://user-images.githubusercontent.com/24593950/35472678-e8ce99c6-0373-11e8-8af3-b6eea85e2f17.png)

**Comment by psifidotos** [comment]
It may be internal separators faulty behavior... show me please in edit mode your Lattd

**Comment by JenaPlinsky** [comment]
[lattedockrc.txt](https://github.com/psifidotos/Latte-Dock/files/1670217/lattedockrc.txt)

![pagq1](https://user-images.githubusercontent.com/24593950/35473649-af40ff4a-0383-11e8-93d9-90cd835c4831.png)

![pagq2-1](https://user-images.githubusercontent.com/24593950/35473663-c643bcc8-0383-11e8-9e6f-fbddd9d29e86.png)
![pagq2-2](https://user-images.githubusercontent.com/24593950/35473664-c82e7e74-0383-11e8-9ce9-e922e4e3314d.png)

![pagq3-1](https://user-images.githubusercontent.com/24593950/35473668-d1d924e2-0383-11e8-9f13-6ad5e9ae432b.png)
![pagq3-2](https://user-images.githubusercontent.com/24593950/35473669-d3d4cecc-0383-11e8-9b59-832b6ca1a84c.png)

![pagq4-1](https://user-images.githubusercontent.com/24593950/35473671-d8c4a7cc-0383-11e8-962e-9e5dc9bcdb99.png)
![pagq4-2](https://user-images.githubusercontent.com/24593950/35473673-db095aa0-0383-11e8-87af-f67f19e68c2d.png)

**Comment by JenaPlinsky** [comment]
![screenshot_20180127_171120](https://user-images.githubusercontent.com/24593950/35473764-1cea0720-0385-11e8-9e02-479692d21d2f.png)

**Comment by psifidotos** [comment]
no idea... I dont know how to reproduce in my system...

**Comment by psifidotos** [comment]
Ok... I managed to reproduce...
only way to occur is that there isnt anything next to konversation (that is the attention bouncing) .. If you have an applet or task next to konversation then you shouldnt be able to reproduce...

**Comment by psifidotos** [comment]
last commit was for this and not #840

**Comment by JenaPlinsky** [comment]
Great @psifidotos !!! the problem seems solved !!!!
