### ISSUE TITLE
Missing and cloned icons when using special application launcher in different activities

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#845]
Sorry if I don't use the correct english words since my system language is german.

I'm currently running master and recently have started using latte in conjunction with activities. So I switched the application starter from "global" to "special" in order to have some applications only attached to particular activities. The first three applications (dolphin, krusader and firefox) are set to be visible on all activities. the fourth is special to two activities (digikam and IntelliJ).

When switching activities I often stumble over the following issues: 
1. Instead of an icon there is only an empty space
2. Starters are drawn with the image of its neighbor
3. Sometimes applications have no indicator (the dot showing that an app is running)

I thought that maybe something could be wrong with my configs. So I started with a fresh Latte config but the problems persists.

This video shows issue 1. One have just work a few minutes and the other issues are going to appear, too.
[activities.flv.zip](https://github.com/psifidotos/Latte-Dock/files/1675104/activities.flv.zip)
remove zip ending

EDIT:
``` 
Arch Linux
Qt: 5.10.0
Plasma: 5.11.5
Frameworks: 5.42.0
```

**Comment by psifidotos** [comment]
I cant open the file you sent... it seems broken..

**Comment by psifidotos** [comment]
Ok I saw the video... but the only issue I saw is [1] the blank icon for krusader at some case, which I will try to reproduce in my system...

Now, some infos:

Unique and Global launchers arent used for having different launchers in your activities. This can be done from both. They are used in case you are using multiple docks/panels (e.g. on a multiscreen environment) and you want your launchers synced between them. The Unique group provides independent launchers that arent synced at all, Global group provides a launchers group that is synced even between different Layouts.

> Starters are drawn with the image of its neighbor

I dont understand.

> Sometimes applications have no indicator (the dot showing that an app is running)

check your tasks filtering in Tasks  config page... if the window is in different desktop or activity and you have enabled such filtering then active indicator isnt shown...

**Comment by psifidotos** [comment]
one more thing.. are you using X11 or wayland?

**Comment by psifidotos** [comment]
> but the only issue I saw is [1] the blank icon for krusader at some case

my mistake, it is the icon from the video recording app... which app is this ?

**Comment by marhkb** [comment]
>I dont understand.

![double_icon](https://user-images.githubusercontent.com/3630213/35537404-6dc8988e-054a-11e8-8e90-190529390bc7.png)

krusader is drawn with firefox icon

>one more thing.. are you using X11 or wayland?

X11 for the next 5 years ;-)

>check your tasks filtering in Tasks config page

I have enabled the last, "only show for activity". The first and second are disabled.
the indicator was not shown for firefox. But firefox was definitely opened in the current activity. I could switch to it with alt+tab. When I clicked on the firefox starter, nothing happend (no second app start or minimize). This happens not very often in comparison to the other issues.

The only thing to get correct launchers again is to restart latte. But after a fee minutes the issues reappear.
Do you need some configs from me?

Thanks for explaining how unique and global launchers work. As far as I understand they should work the same in my setting as I have only one dock with application launchers.

**Comment by marhkb** [comment]
>my mistake, it is the icon from the video recording app... which app is this ?

There should be IntelliJ. But when hovering no tooltip appears.
O fuck, as I watched the video I noticed the the video recording app recorded the sound.
Sorry for that, I should have watched before uploading. XD

**Comment by psifidotos** [comment]
problem is all this experience doesnt exist in my system...

> Thanks for explaining how unique and global launchers work. As far as I understand they should work the same in my setting as I have only one dock with application launcher.

yes... dont they?

> Do you need some configs from me?

you could send me your layout file but I dont think there will be something strange in it...

> krusader is drawn with firefox icon, EDIT: and has no indicator but is definitely opened in that activity

probably plasma libtaskmanager is doing a swap on startup between them but the strange thing is why the icon isnt updated. can you provide the krusader desktop file? there should be a `StartupWMClass` in it, it might be broken...

> There should be IntelliJ. But when hovering no tooltip appears.

very weird... can you provide its desktop file... there should be a `StartupWMClass` in it, it might be broken...

> the indicator was not shown for firefox. But firefox was definitely opened in the current activity.

seems like a plasma libtaskmanager issue.. are you able to reproduce this with plasma taskmanager? you can add a plasma panel at the left edge with icon-only plasma taskmanager in it, in order to compare behaviors.

**Comment by marhkb** [comment]
>are you able to reproduce this with plasma taskmanager?

Just did a little testing. libtaskmanager seems correct as far I can see now. I put it in top panel because latte app launcher was barely visible when putting it in bottom dock.

![libtaskmanager_cmp](https://user-images.githubusercontent.com/3630213/35539498-268d4016-0552-11e8-8f7c-af869aca7441.png)

A window rule sets cantata to be visible on all activities and to be placed on second virtual desktop.
After starting cantata and switching activity latte totally gets messed while libtaskmanager looks sane.

Will do a bit more testing the next days and try to find ways to reproduce.

**Comment by psifidotos** [comment]
> I put it in top panel because latte app launcher was barely visible when putting it in bottom dock.

good idea... in order for plasma taskmanager to work correctly in Latte the dock must be set to panel or manually from Tweaks page in advanced mode the automatic shrinking of applets must be disabled...

**Comment by psifidotos** [comment]
@marhkb I am closing this in order to follow each issue separately... I created : #846 #847 #848 add any information please at the specific and corresponding issue...

**Comment by marhkb** [comment]
Thanks. Currently I've to work a lot but I'll try to provide information within this week.
