### ISSUE TITLE
Crash on "complete configuration file" importing

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#850]
no backtrace available
it may be that the activities in the configuration file are different from those currently in use since I had to recreate them...
![screenshot_20180131_223343](https://user-images.githubusercontent.com/24593950/35648676-cca4dfe2-06d6-11e8-91c5-02a09f487742.png)

![screenshot_20180131_224349](https://user-images.githubusercontent.com/24593950/35649084-360a7a18-06d8-11e8-88f2-e8372d32c22e.png)

![screenshot_20180131_224432](https://user-images.githubusercontent.com/24593950/35649105-4f8c8698-06d8-11e8-8844-ef1a66a3242e.png)

[MyDock5.latterc.zip](https://github.com/psifidotos/Latte-Dock/files/1683432/MyDock5.latterc.zip)

**Comment by psifidotos** [comment]
What is the backtrace?

**Comment by psifidotos** [comment]
@JenaPlinsky please re-test with latest commit...

1. I fixed also a small bug for exporting full configuration. It might be a good idea to re-export your configuration
2. The importing full configuration from the configuration window didnt work at all, so there is a chance that Latte just closed for you without reloading properly
3. I imported your MyDock5 full afterwards successfully in my system...

P.S. In your current exported full configuration file the memory usage is set to MultipleLayouts and not Single like in your screenshot...

**Comment by psifidotos** [comment]
It should be fixed
