### ISSUE TITLE
Can't raise dock when is hidden on the left side

### ISSUE THREAD

**Issue by Tichy** [psifidotos/Latte-Dock#851]
When I place the dock on the left side and a window makes it hide, I expect it to return visible by moving the cursor to the left screen border, but it doesn't happen.

My version is 0.7.3 on plasma 5.11.5, kde frameworks 5.42.0, qt 5.9.3. distro: KDE neon

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-behaves-strangely-from-plasma-510-and-beyond-can-i-fix-this

**Comment by Tichy** [comment]
Thanks. It was that. Sorry, I didn't thought it could be my case.
