### ISSUE TITLE
Feature Request: Full-screen mode

### ISSUE THREAD

**Issue by ishovkun** [psifidotos/Latte-Dock#853]
It would be cool if Latte Dock could do the following:
Let's say a window is maximized and a Latte Dock panel is hidden. When I hover the mouse at the edge of the screen, the pannel appears but not on top of the window (not as an overlay) but the panel rather shrinks the window and occupies the space on the screen taken from the maximized window. This situation is somewhat similar to how OSX window manager handles the panel and maximized windows.
Although, it would be even better if this feature isn't restricted to maximized windows only.

I'd like to express a concern that this feature might be incompatible with wayland because one app cannot have control over other apps. Therefore, even if it is to be implemented, it should be a low-priority feature.

**Comment by psifidotos** [comment]
can you present with a screenshot or something what you mean?

**Comment by ishovkun** [comment]
Yeah, that's probably gonna be easier.
The first screenshot: 
the top panel is hidden
![screenshot_20180202_023833](https://user-images.githubusercontent.com/11154303/35724150-5b15fd10-07c2-11e8-84fd-487ff7e705a1.png)
The second screenshot:
the top panel is visible on hover, but instead of covering a part of the window, it shifts the window down
![screenshot_20180202_023804](https://user-images.githubusercontent.com/11154303/35724204-8a1d58ec-07c2-11e8-9c80-1d65c81a8d8b.png)

Screenshot 3:
The top panel actually covers the top part of the window: I want to prevent this from happening.

![screenshot_20180202_024236](https://user-images.githubusercontent.com/11154303/35724281-c41e1f40-07c2-11e8-97a9-e0b7dc43bf8a.png)

I hope it does make sense to you.

**Comment by psifidotos** [comment]
it is a nice a idea and wayland is not an issue for this... you propose a combination of Dodge Active + Always Visible...
I dont know how easy this would be and it wouldnt animated nice...
Latte is not going to alter external windows geometry in any case. Exception is the AlwaysVisible that provides a strut to succeed that effect. BUT the only solution would be to enable that strut when needed(e.g. when mouse is touching and edge) and disable it at all other cases. That part of changing struts settings looks awful when it is done frequently...

**Comment by ishovkun** [comment]
I agree,  animating this is probably troublesome....
At the same time, this feature per se would definitely help to save vertical space. Besides, the screenshot 3 demonstrates that my browser tab bar is unusable when the panel overlays it on hover.

**Comment by psifidotos** [comment]
>  the screenshot 3 demonstrates that my browser tab bar is unusable when the panel overlays it on hover.

yep... this is the proper behavior when using Auto-Hide or Dodge modes....
