### ISSUE TITLE
The bouncing launcher "infects" other icons

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#854]
When I pin a bouncing launcher, sometimes happens, that it come re-positioned inside the task manager ...
well, in these cases its animation moves to the icon that was next to it, or to those that takes the place of the launcher

**Comment by psifidotos** [comment]
I would never think to pin a bouncing launcher!!! :) probably plasma libtaskmanager moves it to another place without deleting it... I will check it out...

**Comment by JenaPlinsky** [comment]
:)

**Comment by psifidotos** [comment]
@JenaPlinsky can you show me a video ? in my system works ok...

**Comment by JenaPlinsky** [comment]
do you know a way to make bounce the launcher ?

**Comment by psifidotos** [comment]
> do you know a way to make bounce the launcher ?

you mean the non-launcher... right ?

**Comment by JenaPlinsky** [comment]
I'm looking for a practical way to simulate a bouncy task (since the launcher is already running)

**Comment by psifidotos** [comment]
@JenaPlinsky can you show me a video ? in my system works ok...
