### ISSUE TITLE
[Kubuntu] - PlasmaComponents3.ComboBox crashes Latte?

### ISSUE THREAD

**Issue by anshulgoyal15** [psifidotos/Latte-Dock#855]
Kubuntu isnt able to support **PlasmaComponents3.ComboBox**

**Comment by psifidotos** [comment]
it shouldnt... is it Kubuntu? try to clear the Latte cache when Latte is closed...

https://github.com/psifidotos/Latte-Dock/issues/766

**Comment by anshulgoyal15** [comment]
yes it is kubuntu

**Comment by Jeffset** [comment]
Had the same issue. Tried to use gdb to locate an error, but got this:
```
(gdb) exec-file /usr/bin/latte-dock 
(gdb) run
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe1326700 (LWP 8227)]
[New Thread 0x7fffd6186700 (LWP 8228)]
Icon theme "elementary" not found.
Icon theme "gnome" not found.
[New Thread 0x7fffcffff700 (LWP 8229)]
[New Thread 0x7fffb94f8700 (LWP 8230)]
[New Thread 0x7fffafa20700 (LWP 8232)]
[New Thread 0x7fffaef1f700 (LWP 8233)]
[New Thread 0x7fffad71e700 (LWP 8234)]
[New Thread 0x7fff9ffff700 (LWP 8235)]

Thread 1 "latte-dock" received signal SIGSEGV, Segmentation fault.
0x00007fff9e7da921 in Kirigami::PlatformTheme::palette() const () from /usr/lib/x86_64-linux-gnu/libKF5Kirigami2.so.5
(gdb) q
```
I'm not familiar with all kde/qt stuff, so I'll just leave it here :)

**Comment by psifidotos** [comment]
1. have you tried to clear the Latte cache?
- close Latte
- remove everything in: `~/.cache/lattedock/qmlcache`
- start Latte

2. are you using Latte master version?

3. what is your plasma version?

**Comment by Jeffset** [comment]
KDE Plasma version: 5.11.5
KDE Frameworks Version 5.41.0
Qt Version 5.9.1
Yes, I used master branch.

**Comment by Jeffset** [comment]
Is there any more info you require or some other stuff? I'll gladly do what I can, 'cause it's my favourite plasma dock :)

**Comment by psifidotos** [comment]
> Is there any more info you require or some other stuff? I'll gladly do what I can, 'cause it's my favourite plasma dock :)

you can try again... I reverted the PlasmaComponents3.ComboBox from the settings window which is probably the component referencing the Kirigami2.

just tell me if it is fixed...

**Comment by Jeffset** [comment]
Yeah, you did it! Settings're working again 👍

**Comment by psifidotos** [comment]
ok... let me report it to kubuntu packagers and see what are they saying about this...

**Comment by psifidotos** [comment]
@Jeffset which kubuntu version are you using?

**Comment by Jeffset** [comment]
> which kubuntu version are you using?
**Ubuntu 17.10 artful**, all kde/plasma/qt versions are mentioned ⬆️

**Comment by rikmills** [comment]
@Jeffset How do you trigger the crash? What revision was it?

With frameworks 5.42, Plasma 5.12 and latte-dock package built on 1st March (0.7.77+git20180201.1823) I can't see a crash so far.

**Comment by anshulgoyal15** [comment]
thanx it is working fine now

**Comment by psifidotos** [comment]
> With frameworks 5.42, Plasma 5.12 and latte-dock package built on 1st March (0.7.77+git20180201.1823) I can't see a crash so far.

@ rikmills  the user was using the master version that was containing for a week now PlasmaComponents3.ComboBox , I reverted the commit in order to fix the issue first in kubuntu and then re-introduce it... I can create a branch that produces for you that crash...

**Comment by psifidotos** [comment]
@rikmills

**Comment by Jeffset** [comment]
As we seemingly figured out bug was in kde not in latte-dock.

Look, I sad, that bug was in:
> KDE Plasma version: 5.11.5
KDE Frameworks Version 5.41.0
Qt Version 5.9.1
Yes, I used master branch.

And these are updated versions:
> With frameworks 5.42, Plasma 5.12 and latte-dock package built on 1st March (0.7.77+git20180201.1823) I can't see a crash so far.

Maybe bug is already fixed.

**Comment by psifidotos** [comment]
> @psifidotos, as we seemingly figured out bug was in kde not in latte-dock.

I can create a different branch in order to test it in Kubuntu if it crashes? I have reverted the specific commit that introduced PlasmaComponents3.Combobox(es) in settings window

**Comment by Jeffset** [comment]
> I can create a different branch in order to test it in Kubuntu if it crashes? I have reverted the specific commit that introduced PlasmaComponents3.Combobox(es) in settings window

You mean that you kinda "re-revert" back PlasmaComponents3.Combobox in separate branch in order to me to test if this bug still persists? Ok, just ping me when I can test.

**Comment by psifidotos** [comment]
> Ok, just ping me when I can test.

@Jeffset I created a branch called **kubuntu** and contains the commit that was creating the crash when showing the configuration window...

**Comment by Jeffset** [comment]
I did built and installed **kubuntu** branch - no crash, when I open settings. Before that today I upgraded system to all latest kde/plasma versions (5.42/5.21) as they became available from repos. So it really was internal kubuntu bug and it's fixed now.

**Comment by psifidotos** [comment]
ok... so I merged again in master... let's see how it goes...
