### ISSUE TITLE
The dock has a brusque behaviour 

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#856]
When the mouse makes a L movement ,the dock has a brusque behaviour 

[test.zip](https://github.com/psifidotos/Latte-Dock/files/1696785/test.zip)

**Comment by psifidotos** [comment]
I dont see anything special in the video

>  the dock has a brusque behaviour

what is that? at which second of your video do you notice it?

**Comment by JenaPlinsky** [comment]
at the 36sec  and at the 39sec

**Comment by psifidotos** [comment]
> at the 36sec and at the 39sec

you mean the sudden appearing?

**Comment by JenaPlinsky** [comment]
even on the far sides of the dock it sometimes narrows a little too abruptly ... personal opinion
[test2.zip](https://github.com/psifidotos/Latte-Dock/files/1696843/test2.zip)

**Comment by psifidotos** [comment]
> even on the far sides of the dock it sometimes narrows a little too abruptly ... personal opinion

which secs?

**Comment by JenaPlinsky** [comment]
yes if I make a downward movement and then to the side when the dock is already rising the animation is smooth while if I move quickly to the side when the dock is still hidden, this rise brusquely

**Comment by psifidotos** [comment]
> even on the far sides of the dock it sometimes narrows a little too abruptly ... personal opinion test2.zip

for this video I dont see anything special... for test1 the issue was introduced with #852 but I dont know a good way to improve this yet...

**Comment by JenaPlinsky** [comment]
>   which secs?

46 sec
for only a few millimeters

**Comment by psifidotos** [comment]
> brusque behavior

you could try to check again..

> 46 sec, for only a few millimeters

I see it but I cant track it down

**Comment by JenaPlinsky** [comment]
[test3.zip](https://github.com/psifidotos/Latte-Dock/files/1696981/test3.zip)
a little shot here again at the 25th second

**Comment by psifidotos** [comment]
> a little shot here again at the 25th second

yeah, i see it... unfortunately I cant fix it...

**Comment by psifidotos** [comment]
@JenaPlinsky open a different issue for the last videos... you first video and the last videos are different issues... the first was for zoom-in and the last are for zoom-out... totally different...

**Comment by JenaPlinsky** [comment]
pumping at the 57th sec
[screencast_2018-02-05_232724_slowmotion.zip](https://github.com/psifidotos/Latte-Dock/files/1697029/screencast_2018-02-05_232724_slowmotion.zip)

**Comment by JenaPlinsky** [comment]
> open a different issue for the last videos... you first video and the last videos are different issues... the first was for zoom-in and the last are for zoom-out... totally different...

Ohhh yes, now I put the questions in order

**Comment by psifidotos** [comment]
> pumping at the 57th sec

you mean the tooltip? different issue different thread...

**Comment by JenaPlinsky** [comment]
the problem described above seems to be less evident but still present and the current implementation gives the impression that it is difficult to manage
