### ISSUE TITLE
Tooltips positioning breaks a bit the parabolic effect

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#857]
Icon pumping at the 57th sec
[screencast_2018-02-05_232724_slowmotion.zip](https://github.com/psifidotos/Latte-Dock/files/1697041/screencast_2018-02-05_232724_slowmotion.zip)

**Comment by psifidotos** [comment]
The "Photo" tooltip  isnt positioned properly at first showing... but this hasnt appeared in my system .... "Photo" is a task or an applet?

can you present the issue with enabled flag `latte-dock --graphics` ?

**Comment by JenaPlinsky** [comment]
> "Photo" is a task or an applet?

it's an applet
5.08th sec and at the 5.50th sec
[screencast_2018-02-06_185700_SlowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1700270/screencast_2018-02-06_185700_SlowMotion.zip)

**Comment by psifidotos** [comment]
it shows the tooltip even though it is hidden... it should show the tooltip after the slide-in has ended...

**Comment by JenaPlinsky** [comment]
and hear instead with the Dolphin task
[screencast_2018-02-06_193122_SlowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1700374/screencast_2018-02-06_193122_SlowMotion.zip)

**Comment by psifidotos** [comment]
> and hear instead with the Dolphin task

what sec?

**Comment by JenaPlinsky** [comment]
1,29.and 1.45
...maybe it could be another kind of flaw

**Comment by JenaPlinsky** [comment]
this is the same video, but without slowmotion
[screencast_2018-02-06_193122.zip](https://github.com/psifidotos/Latte-Dock/files/1700572/screencast_2018-02-06_193122.zip)

**Comment by JenaPlinsky** [comment]
in the slowmotion video...
3.58th sec peek icon seems to rise up abruptly or it is my impression ?
4.22th sec peek icon seems to come down abruptly or it is my impression ?
5.42 task preview tooltip as you mentioned earlier, it appears and disappears several times

**Comment by psifidotos** [comment]
> 3.58th sec peek icon seems to rise up abruptly or it is my impression ?

x11 issue, nothing to do with latte

> 4.22th sec peek icon seems to come down abruptly or it is my impression ?

it's ok

> 5.42 task preview tooltip as you mentioned earlier, it appears and disappears several times

this is in the same category...

stange issue that is... I dont know if I will be able to fix it...

**Comment by JenaPlinsky** [comment]
- Applets
it is always reproducible in autohide mode, every time the dock rise up
the tooltip is positioned on the wrong place and the animation breaks for a moment
[screencast_2018-02-08_004127.zip](https://github.com/psifidotos/Latte-Dock/files/1705177/screencast_2018-02-08_004127.zip)


- Launchers
the tooltip is correctly positioned but is visible only for a few frames when the mouse reaches the maximum point and in this case the animation does not break
[screencast_2018-02-08_004259.zip](https://github.com/psifidotos/Latte-Dock/files/1705180/screencast_2018-02-08_004259.zip)
