### ISSUE TITLE
The icon moves to the side abruptly at the 25th second

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#858]
[test3.zip](https://github.com/psifidotos/Latte-Dock/files/1697047/test3.zip)

**Comment by psifidotos** [comment]
can you present the issue with enabled flag `latte-dock --graphics` ?

**Comment by JenaPlinsky** [comment]
1.07th sec
[screencast_2018-02-06_195228_SlowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1700616/screencast_2018-02-06_195228_SlowMotion.zip)
