### ISSUE TITLE
latest master and 0.7 branches fail to build from source

### ISSUE THREAD

**Issue by rikmills** [psifidotos/Latte-Dock#859]
https://launchpadlibrarian.net/355961136/buildlog_ubuntu-bionic-amd64.latte-dock_0.7.77+git20180206.1034-0~ubuntu18.04~ppa1_BUILDING.txt.gz

[ 45%] Building CXX object app/CMakeFiles/latte-dock.dir/windowinfowrap.cpp.o
cd /<<BUILDDIR>>/latte-dock-0.7.77+git20180206.1034/obj-x86_64-linux-gnu/app && /usr/bin/c++  -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -I/<<BUILDDIR>>/latte-dock-0.7.77+git20180206.1034/obj-x86_64-linux-gnu/app -I/<<BUILDDIR>>/latte-dock-0.7.77+git20180206.1034/app -I/<<BUILDDIR>>/latte-dock-0.7.77+git20180206.1034/obj-x86_64-linux-gnu/app/latte-dock_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5 -isystem /usr/include/KF5/KDBusAddons -isystem /usr/include/KF5/KDeclarative -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KPackage -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5/KGlobalAccel -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/KF5/KArchive -isystem /usr/include/KF5/KCrash -isystem /usr/include/KF5/KXmlGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/KF5/KConfigWidgets -isystem /usr/include/KF5/KCodecs -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/KF5/KConfigGui -isystem /usr/include/KF5/KAuth -isystem /usr/include/KF5/Plasma -isystem /usr/include/KF5/KService -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5/KActivities -isystem /usr/include/KF5/KNotifications -isystem /usr/include/KF5/KNewStuff3 -isystem /usr/include/KF5/KNewStuff3/KNS3 -isystem /usr/include/KF5/KNewStuff3/knscore -isystem /usr/include/KF5/KNewStuff3/kns3 -isystem /usr/include/KF5/KNewStuff3/KNSCore -isystem /usr/include/KF5/Attica -isystem /usr/include/KF5/KWayland/Client -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras  -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/latte-dock-0.7.77+git20180206.1034=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -O3 -DNDEBUG   -fPIC -std=gnu++14 -o CMakeFiles/latte-dock.dir/windowinfowrap.cpp.o -c /<<BUILDDIR>>/latte-dock-0.7.77+git20180206.1034/app/windowinfowrap.cpp
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `operator()':
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:186: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:190: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:190: undefined reference to `Latte::LayoutManager::switchToLayout(QString, int)'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `Latte::DockCorona* qobject_cast<Latte::DockCorona*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:514: undefined reference to `Latte::DockCorona::staticMetaObject'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `Menu::switchToLayout(QAction*)':
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:181: undefined reference to `Latte::DockCorona::layoutManager() const'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `Latte::DockCorona* qobject_cast<Latte::DockCorona*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:514: undefined reference to `Latte::DockCorona::staticMetaObject'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `Menu::populateLayouts()':
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:138: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:138: undefined reference to `Latte::LayoutManager::menuLayouts() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:139: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:139: undefined reference to `Latte::LayoutManager::activeLayoutsNames()'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:140: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:140: undefined reference to `Latte::LayoutManager::memoryUsage() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:141: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:141: undefined reference to `Latte::LayoutManager::currentLayoutName() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:143: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:143: undefined reference to `Latte::LayoutManager::menuLayouts() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:160: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:160: undefined reference to `Latte::LayoutManager::activeLayout(QString) const'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `Latte::DockCorona* qobject_cast<Latte::DockCorona*>(QObject*)':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:514: undefined reference to `Latte::DockCorona::staticMetaObject'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `Menu::contextualActions()':
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:110: undefined reference to `Latte::DockCorona::layoutManager() const'
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:110: undefined reference to `Latte::LayoutManager::menuLayouts() const'
CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/menu.cpp.o: In function `operator()':
./obj-x86_64-linux-gnu/containmentactions/contextmenu/./containmentactions/contextmenu/menu.cpp:186: undefined reference to `Latte::LayoutManager::showLatteSettingsDialog(int)'
collect2: error: ld returned 1 exit status
containmentactions/contextmenu/CMakeFiles/plasma_containmentactions_lattecontextmenu.dir/build.make:123: recipe for target 'containmentactions/contextmenu/plasma_containmentactions_lattecontextmenu.so' failed

**Comment by psifidotos** [comment]
the thing is that in my system it builds, in your system locally same things happens? (I havent tried in my system to start clean, without a build directory, maybe it cant reference something)

the code that doesnt build is from the new containmentactions that provide the Latte contextmenu choices everywhere, even with plasma official taskmanagers....

**Comment by rikmills** [comment]
It does seem to build locally.

Neon build from master branch also fails:

https://build.neon.kde.org/job/xenial_unstable_kde-extras_latte-dock_bin_amd64/94/console

**Comment by rikmills** [comment]
For what it's worth, the last commit on the 0.7 branch also broke the builds of that:

https://build.neon.kde.org/job/xenial_stable_kde-extras_latte-dock_bin_amd64/29/console

https://launchpadlibrarian.net/355510002/buildlog_ubuntu-bionic-amd64.latte-dock_0.7.3+p18.04+git20180202.0838-0_BUILDING.txt.gz

**Comment by psifidotos** [comment]
> For what it's worth, the last commit on the 0.7 branch also broke the builds of 

they were irrelevant...
for v0.7 the branch should be ok now...

for master, I cant understand yet how it builds locally but not online...

**Comment by rikmills** [comment]
0.7 branch

https://build.neon.kde.org/job/xenial_stable_kde-extras_latte-dock_bin_amd64/30/console

15:02:26 [ 42%] Built target lattedockplugin
15:02:26 [ 44%] Building CXX object app/CMakeFiles/latte-dock.dir/windowinfowrap.cpp.o
15:02:27 [ 46%] Building CXX object app/CMakeFiles/latte-dock.dir/abstractwindowinterface.cpp.o
15:02:28 [ 48%] Building CXX object app/CMakeFiles/latte-dock.dir/xwindowinterface.cpp.o
15:02:30 [ 51%] Building CXX object app/CMakeFiles/latte-dock.dir/waylandinterface.cpp.o
15:02:32 [ 53%] Building CXX object app/CMakeFiles/latte-dock.dir/visibilitymanager.cpp.o
15:02:34 [ 55%] Building CXX object app/CMakeFiles/latte-dock.dir/dockcorona.cpp.o
15:02:39 [ 57%] Building CXX object app/CMakeFiles/latte-dock.dir/dockview.cpp.o
15:02:42 /workspace/build/app/dockview.cpp: In member function ‘void Latte::DockView::syncGeometry()’:
15:02:42 /workspace/build/app/dockview.cpp:751:69: error: invalid use of incomplete type ‘class ScreenPool’
15:02:42              int fixedScreen = onPrimary() ? dockCorona->screenPool()->primaryScreenId() : this->containment()->screen();
15:02:42                                                                      ^
15:02:42 In file included from /workspace/build/app/dockview.cpp:23:0:
15:02:42 /workspace/build/app/dockcorona.h:36:7: note: forward declaration of ‘class ScreenPool’
15:02:42  class ScreenPool;
15:02:42        ^
15:02:42 make[4]: *** [app/CMakeFiles/latte-dock.dir/dockview.cpp.o] Error 1

**Comment by psifidotos** [comment]
> 0.7 branch

ok, fixed...

**Comment by psifidotos** [comment]
> master branch

ok... I made an attempt to fix it in master, can you please check?

**Comment by rikmills** [comment]
stable 0.7 branch appears fixed: https://build.neon.kde.org/job/xenial_stable_kde-extras_latte-dock/31/

master, sadly not: https://build.neon.kde.org/job/xenial_unstable_kde-extras_latte-dock_bin_amd64/96/console

**Comment by psifidotos** [comment]
> master, sadly not

ok... I suppose I will try a different approach the next days...

**Comment by psifidotos** [comment]
> master

@rikmills , I changed the configuration in order to use dbus functionality... can you please check again with latest master?

**Comment by rikmills** [comment]
@psifidotos So far so good compiling on a Neon build.

**Comment by psifidotos** [comment]
nice
