### ISSUE TITLE
Fedora/Debian: Cannot load "org.kde.latte"

### ISSUE THREAD

**Issue by fapasv** [psifidotos/Latte-Dock#86]
QML: file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:34:1: module "org.kde.latte" is not installed

Debian 9 / 64 bits
Plasma 5.8.2
Kde framework 5.27
qt 5.7.1
kernel 4.8.0-2

**Comment by psifidotos** [comment]
can you send the installation messages?

**Comment by fapasv** [comment]
this is my output:

$ ./install.sh 
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.27.0") 
-- Found KF5PlasmaQuick: /usr/lib/x86_64-linux-gnu/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.27.0") 
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.27.0") 
-- Found KF5Declarative: /usr/lib/x86_64-linux-gnu/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.27.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.27.0") 
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.27.0") 
-- Found KF5XmlGui: /usr/lib/x86_64-linux-gnu/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.27.0") 
-- Found KF5DBusAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5DBusAddons/KF5DBusAddonsConfig.cmake (found version "5.27.0") 
-- Found KF5IconThemes: /usr/lib/x86_64-linux-gnu/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.27.0") 
-- Found KF5: success (found suitable version "5.27.0", minimum required is "5.26.0") found components:  Plasma PlasmaQuick WindowSystem Declarative I18n CoreAddons XmlGui DBusAddons IconThemes 
-- Disabling debug info
-- Found KF5: success (found version "5.27.0") found components:  WindowSystem CoreAddons Plasma PlasmaQuick IconThemes 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fapa/Descargas/Latte-Dock-master/build
Scanning dependencies of target translations-containment
[  0%] Built target translations-containment
Scanning dependencies of target translations-plasmoid
[  0%] Built target translations-plasmoid
Scanning dependencies of target translations-app
[  0%] Built target translations-app
Scanning dependencies of target latte-dock_automoc
[  4%] Automatic moc for target latte-dock
Generating moc source latte-dock_automoc.dir/moc_abstractwindow_VVSVCQSKGXIZ2N.cpp
Generating moc source latte-dock_automoc.dir/moc_dockconfigview_TC7C5YNWO3DY7P.cpp
Generating moc source latte-dock_automoc.dir/moc_dockcorona_FQ3UHH3LYQ7NPF.cpp
Generating moc source latte-dock_automoc.dir/moc_dockview_MHYA7OBTBFTZG2.cpp
Generating moc source latte-dock_automoc.dir/moc_dockpackage_BON6MFJPNXI7Q5.cpp
Generating moc source latte-dock_automoc.dir/moc_visibilitymana_YQBWQFIYUX3NAC.cpp
Generating moc source latte-dock_automoc.dir/moc_visibilitymana_S32UF7RILJU54W.cpp
Generating moc source latte-dock_automoc.dir/moc_xwindowinterfa_2OWXFJPNWWGWU5.cpp
Generating moc source latte-dock_automoc.dir/moc_dock_ZXGG7LNOKSXHEH.cpp
Generating moc source latte-dock_automoc.dir/moc_windowsystem_JHV6SGHINIIJFT.cpp
Generating moc compilation latte-dock_automoc.cpp
[  4%] Built target latte-dock_automoc
Scanning dependencies of target latte-dock
[  9%] Building CXX object app/CMakeFiles/latte-dock.dir/__/liblattedock/dock.cpp.o
[ 14%] Building CXX object app/CMakeFiles/latte-dock.dir/__/liblattedock/windowsystem.cpp.o
[ 19%] Building CXX object app/CMakeFiles/latte-dock.dir/windowinfowrap.cpp.o
[ 23%] Building CXX object app/CMakeFiles/latte-dock.dir/abstractwindowinterface.cpp.o
[ 28%] Building CXX object app/CMakeFiles/latte-dock.dir/xwindowinterface.cpp.o
[ 33%] Building CXX object app/CMakeFiles/latte-dock.dir/visibilitymanager.cpp.o
[ 38%] Building CXX object app/CMakeFiles/latte-dock.dir/dockcorona.cpp.o
[ 42%] Building CXX object app/CMakeFiles/latte-dock.dir/dockview.cpp.o
[ 47%] Building CXX object app/CMakeFiles/latte-dock.dir/dockconfigview.cpp.o
[ 52%] Building CXX object app/CMakeFiles/latte-dock.dir/packageplugins/shell/dockpackage.cpp.o
[ 57%] Building CXX object app/CMakeFiles/latte-dock.dir/main.cpp.o
[ 61%] Building CXX object app/CMakeFiles/latte-dock.dir/latte-dock_automoc.cpp.o
[ 66%] Linking CXX executable latte-dock
[ 66%] Built target latte-dock
Scanning dependencies of target lattedockplugin_automoc
[ 71%] Automatic moc for target lattedockplugin
Generating moc source lattedockplugin_automoc.dir/moc_dock_JDKA5CZNV5UGY5.cpp
Generating moc source lattedockplugin_automoc.dir/moc_iconitem_YSSWX4L6MCTNZP.cpp
Generating moc source lattedockplugin_automoc.dir/moc_lattedockplugi_YHHZPOKREU7AJO.cpp
Generating moc source lattedockplugin_automoc.dir/moc_windowsystem_AWL2BMGD6H75BX.cpp
Generating moc compilation lattedockplugin_automoc.cpp
[ 71%] Built target lattedockplugin_automoc
Scanning dependencies of target lattedockplugin
[ 76%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/lattedockplugin.cpp.o
[ 80%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/windowsystem.cpp.o
[ 85%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/dock.cpp.o
[ 90%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/iconitem.cpp.o
[ 95%] Building CXX object liblattedock/CMakeFiles/lattedockplugin.dir/lattedockplugin_automoc.cpp.o
[100%] Linking CXX shared library liblattedockplugin.so
[100%] Built target lattedockplugin
[  0%] Built target translations-containment
[  0%] Built target translations-plasmoid
[  0%] Built target translations-app
[  4%] Automatic moc for target latte-dock
[  4%] Built target latte-dock_automoc
[ 66%] Built target latte-dock
[ 71%] Automatic moc for target lattedockplugin
[ 71%] Built target lattedockplugin_automoc
[100%] Built target lattedockplugin
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/share/locale/kf5/el/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/es/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/pl/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/zh_TW/LC_MESSAGES/plasma_applet_org.kde.latte.plasmoid.mo
-- Installing: /usr/share/locale/kf5/el/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/es/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/pl/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/ro/LC_MESSAGES/latte-dock.mo
-- Installing: /usr/share/locale/kf5/zh_TW/LC_MESSAGES/latte-dock.mo
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/images/panel-west.png
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config/main.xml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AddWidgetVisual.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/AppletItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/ConfigOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/EditModeVisual.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/blueprint.jpg
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/splitter.png
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/LayoutManager.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.desktop
-- Installing: /usr/share/appdata/org.kde.latte.containment.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.containment.desktop
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images/panel-west.png
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/config.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/main.xml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/CircleText.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigPanel.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconBuffers.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipWindowMouseArea.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/GlowPoint.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/VisualAddItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipDelegate.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskIconItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskActiveItem.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskProgressOverlay.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/MouseHandler.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigAppearance.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ConfigInteraction.qml
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskGroupItem.qml
-- Up-to-date: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/layout.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/tools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js
-- Installing: /usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.desktop
-- Installing: /usr/share/appdata/org.kde.latte.plasmoid.appdata.xml
-- Installing: /usr/share/kservices5/plasma-applet-org.kde.latte.plasmoid.desktop
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/defaults
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/controls/SpinBox.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/SIL Open Font License.txt
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/fonts/tangerine.ttf
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/views
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml
-- Up-to-date: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/config.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/Header.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockConfiguration.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/BehaviorConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/AppearanceConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteTextField.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/TasksConfig.qml
-- Installing: /usr/share/plasma/shells/org.kde.latte.shell/metadata.desktop
-- Installing: /usr/share/appdata/org.kde.latte.shell.appdata.xml
-- Installing: /usr/share/kservices5/plasma-shell-org.kde.latte.shell.desktop
-- Installing: /usr/bin/latte-dock
-- Installing: /usr/share/applications/latte-dock.desktop
-- Installing: /usr/lib/x86_64-linux-gnu/qml/org/kde/latte/liblattedockplugin.so
-- Installing: /usr/lib/x86_64-linux-gnu/qml/org/kde/latte/qmldir
-- Installing: /usr/share/icons/hicolor/16x16/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/22x22/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/24x24/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/32x32/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/48x48/apps/latte-dock.svg
-- Installing: /usr/share/icons/hicolor/scalable/apps/latte-dock.svg
-- Installing: /usr/share/icons/breeze/applets/256/org.kde.latte.plasmoid.svg

**Comment by psifidotos** [comment]
ok, I found it... Your distro I think has a bug, in my system the following are not there:
-- Installing: /usr/lib/x86_64-linux-gnu/qml/org/kde/latte/liblattedockplugin.so
-- Installing: /usr/lib/x86_64-linux-gnu/qml/org/kde/latte/qmldir

they both are at:
-- Installing: /usr/lib64/qt5/qml/org/kde/latte/liblattedockplugin.so
-- Up-to-date: /usr/lib64/qt5/qml/org/kde/latte/qmldir

as you can see the "qt5" directory is missing from your installation paths...

this is set during installation with: ${KDE_INSTALL_QMLDIR}

I believe that in Fedora and Debian this is not set correctly, so you must report it I think and you can also send them this link in order to see what is happening...

until then you can move these two files in the correct location but in every installation you must also update these files manually...

I hope this works for you...

**Comment by fapasv** [comment]
I see. sure I will send this bug... thanks for your answer, And your suggestion works!!.

**Comment by fapasv** [comment]
thanks a lot!!

**Comment by psifidotos** [comment]
no worries !!! ;)

**Comment by rdieter** [comment]
I suggest to be on the safe side that install.sh also pass to cmake:
-DKDE_INSTALL_USE_QT_SYS_PATHS:BOOL=ON
to help ensure proper paths are used

**Comment by psifidotos** [comment]
Can you please show me a plasma code that uses that flag? I havent seent it somewhere

**Comment by psifidotos** [comment]
Yes I know but I cant understand why this is needed... I havent seen it used from any other kde/plasma project

**Comment by rdieter** [comment]
If that is not sett, then instead of using the proper system paths, it hardcodes the value to:
    _define_relative(QMLDIR LIBDIR "qml"
        "QtQuick2 imports"
        QML_INSTALL_DIR)

which as you saw here, is wrong in some circumstances.

**Comment by psifidotos** [comment]
No prob adding it, are we sure it wont break other distros?

2. Can you give me an example where to add it?

**Comment by rdieter** [comment]
If it breaks anyone, it means their systems' Qt5 is misconfigured/broken.  It should be reasonably safe.

Add the cmake define in install next to where you set other stuff, like -DCMAKE_PREFIX=/usr, heck, I can make a pull request if you want

**Comment by rdieter** [comment]
I think I came up with a solution for fedora downstream,
https://bugzilla.redhat.com/show_bug.cgi?id=1435525#c8

Turns out KDE_INSTALL_USE_QT_SYS_PATHS is supposed to get used if CMAKE_INSTALL_PREFIX matches qt's install prefix.  Unfortunately, that check is not true on fedora (and probably also debian).  I'll fix that in fedora now.

**Comment by psifidotos** [comment]
nice!
