### ISSUE TITLE
Improve CPU usage for the parabolic effect

### ISSUE THREAD

**Issue by TobiichiAmane** [psifidotos/Latte-Dock#861]
Latte-dock is the most elegant dock-like app I've ever seen, but when zooming the icons, Latte-dock consumes 10% of the CPU( laptop, i7-5500U, Archlinux, Plasma 5.12). On my celeron laptop, the number is 25%. Meanwhile, Plank only consumes 1% on my i7 laptop, or 2~3% on my celeron laptop. Though it only happens when I hover my mouse over the dock, it's still very annoying, especially when doing some resources-consuming jobs( compiling, watching 4K videos, etc.).

**Comment by psifidotos** [comment]
> On my celeron laptop, the number is 25%. Meanwhile, Plank only consumes 1% on my i7 laptop, or 2~3% on my celeron laptop. Though it only happens when I hover my mouse over the dock, it's still very annoying, 

yeah I confirm this... but unfortunately I dont have any idea how this can be improved with qml... feel free to contribute if you have such expertise... one thing I have also noticed is that if you disable the applets shadows then the cpu usage drops a bit... The main reason for this is the painting... I think that for every frame Latte provides crisp icons based on the svg files that the icon theme provides...

Any buffering or other way to handle this in the past ended to create much more issues than the one solved...

**Comment by TobiichiAmane** [comment]
I've managed to get it running with hardware acceleration, which makes it consumes less CPU, but it freezes the whole plasma 😂. Switching compositor to compton solved the problem, so I think it maybe a issue of the compatibility between my patched code and the default KDE compositor.
The Lunar New Year is coming and I'm pregnant, which means I'm disappearing from Github for a while. After that I'll fork this repository and try to solve the issue. Meanwhile, if you and other developers managed to solve the CPU usage problem, please update this issue. I'll be grateful.

**Comment by psifidotos** [comment]
@TobiichiAmane are you using proprietary nvidia drivers? I tried the nouveau one and cpu usage dropped 50%

**Comment by RaitaroH** [comment]
I will contribute to the discussion a bit:
[My laptop detailed here](https://github.com/RaitaroH/DELL-Inspiron-Gaming-7567). This is the compositor settings:
![screenshot_20180227_151611](https://user-images.githubusercontent.com/19552720/36730744-2f936ce0-1bd1-11e8-9d14-31a635cbc9e1.png)

Latte dock consumes at most 200.000k memory (at least I noticed this a couple of times). This is the results while hovering the dock:
![screenshot_20180227_151236](https://user-images.githubusercontent.com/19552720/36730702-0b667fd8-1bd1-11e8-8996-7efbadd9fde9.png)
![screenshot_20180227_151319](https://user-images.githubusercontent.com/19552720/36730703-0b8e4932-1bd1-11e8-84e9-2121a12c5969.png)

**Comment by psifidotos** [comment]
@RaitaroH we have the same laptop!!!!! :) hehe I get of course the same metrics... yesterday I managed to use wayland and the Latte animations are smooth as butter in it!!! :)

**Comment by RaitaroH** [comment]
@psifidotos XD Not sure why I would bother with Wayland myself considering that I mainly hear about bugs when it comes to it. Should I try it? Is it worth it?

**Comment by psifidotos** [comment]
from today all new or unclosed issues should be reported to: https://bugs.kde.org/
