### ISSUE TITLE
The desktop icons are covered by dock and bar

### ISSUE THREAD

**Issue by Tichy** [psifidotos/Latte-Dock#863]
I don't know if this is a latte dock or plasma issue.
I set the desktop as folder view, copy or create some icons in there, then arrange them to the left or right.
What happens is that the icons are placed behind the dock. What I expect is that latte dock is  treated like plasma panels and the icons placed in an uncovered space.

![screenshot_20180208_204742](https://user-images.githubusercontent.com/2348771/35994934-2a6d0938-0d12-11e8-8e38-143c81a65c00.png)![screenshot_20180208_204807](https://user-images.githubusercontent.com/2348771/35994935-2a8cfc02-0d12-11e8-9ae2-eac362806968.png)

**Comment by psifidotos** [comment]
Duplicate #737
