### ISSUE TITLE
[Wayland] - Top Panel cover other apps

### ISSUE THREAD

**Issue by postadelmaga** [psifidotos/Latte-Dock#864]
Kde: 5.12
Latte: lattedock 0.7.77

As you can see from the below screenshot yakuake first 2 lines are covered by the latte top panel
![screenshot_20180209_080249](https://user-images.githubusercontent.com/2010800/36015693-e5afd95c-0d6f-11e8-838a-72924affd40e.png)

This happens with yakuake but also with the Plasma Search box ( I wasn't able to get a screenshot for this)

**Comment by psifidotos** [comment]
1. have you enabled always visible for the top panel ? 

2. show me a normal maximized window, yakuake and krunner is special cases....

**Comment by psifidotos** [comment]
ok ... I suppose this isnt valid for other types of windows

**Comment by postadelmaga** [comment]
Sorry I miss you questions but I can confirm now it is working fine on **lattedock 0.7.79**
