### ISSUE TITLE
Menu Icon cannot be invoked from lowest left corner with mouse in plasma layout mode?

### ISSUE THREAD

**Issue by star-buck** [psifidotos/Latte-Dock#867]
Hi, I use Latte Dock with Plasma Layout set to 100% width , Location bottom and 48px height.
If i click with mouse in the lowest left corner to invoke application menu, the logo seems visibly get clicked but the menu doesnt appear.
For the menu to appear I need to click 1-2 pixels up on the menu icon.
I tried this with Breeze theme but also any other theme and it doesnt change, any idea?

**Comment by psifidotos** [comment]
in master version this has been fixed... for v0.7 you can try to enable from Tweaks page,
"Shrink thickness margins to minimum"

**Comment by star-buck** [comment]
Not sure if the version below is any good for testing git, but it doesnt seem to work there:
https://launchpad.net/~rikmills/+archive/ubuntu/latte-dock

**Comment by psifidotos** [comment]
1. Have you enabled any kwin edge corner for bottom left one?

2. Have you added any applets or spacers in the plasma layout?

**Comment by psifidotos** [comment]
3. Which application launcher are you trying to trigger ?

**Comment by star-buck** [comment]
1. i have kwin edge for lower RIGHT corner enabled
3. dash, but its the same for all launchers
2. yes, notification in left corner, see images:
![screenshot_20180430_112606](https://user-images.githubusercontent.com/840070/39421536-cdf6debc-4c69-11e8-8c8a-e1deb953a7a1.png)
![Uploading Screenshot_20180430_112754.png…]()

**Comment by star-buck** [comment]
Btw. is latte integration such that the plasma desktop containments (desktop, folderview) are aware of any docks and should adjust the icon grid accordingly (like when detecting a plasma panel in the same space)?
see screenshot above where the top icons extend into the latte dock at top...

**Comment by star-buck** [comment]
Update: I tried same layout with Latte 0.7.5 and it seems to work fine, i guess the package is then just faulty... still the question regarding integration remains, will open a new question and only reply if this happens again when updating from 0.7.5 to latest release.

**Comment by psifidotos** [comment]
this is confirmed for master version!!! I will give it a check...

**Comment by psifidotos** [comment]
ok, found it...
