### ISSUE TITLE
I get a flickering when i enter on the applet separator

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#871]
I get a flickering when I enter on the separator
[vokoscreen-2018-02-17_22-17-15.zip](https://github.com/psifidotos/Latte-Dock/files/1734166/vokoscreen-2018-02-17_22-17-15.zip)
Other times, flickering is persistent when hovering the first icon of the tasks/launchers area
[vokoscreen-2018-02-17_21-57-34.zip](https://github.com/psifidotos/Latte-Dock/files/1734132/vokoscreen-2018-02-17_21-57-34.zip)

**Comment by psifidotos** [comment]
1. is that separator an applet or a tasks internal one? 

2. please remake your videos with latest master and  running the following command:

`latte-dock -d --graphics --spacers`

**Comment by psifidotos** [comment]
I can reproduce...

**Comment by JenaPlinsky** [comment]
Sorry I could not make a video, in these days I'm been busy ...

Now, there's something I just do not understand ....
Yesterday I downloaded from master, after that you have fixed the bug in question ...
and the problem seemed to be perfectly solved, then I turned the laptop off and on and now everything is back as before
how is this thing possible?
it almost seems that Latte has come back, of different commits

To be honest, even before of opening this discussion, things like this happened

Now I try to download again from master and I expect everything will go smoothly until I'll restart the laptop

is it possible to show the number of the last commit somewhere?

**Comment by JenaPlinsky** [comment]
I confirm that after the new download everything runs smoothly [despite the fact that I had downloaded yesterday, it is identical to the current]
so if I go out and come back in plasma there are many possibilities to visualize again, those flickering that I mentioned above
```
### 3 - Download from GIT repository: ###
remote repository: https://github.com/psifidotos/Latte-Dock [branches: audoban2 audoban2-signal dock-pressure master v0.5 v0.6 v0.7]
local repository:  /home/Shared/Settings/Script
From https://github.com/psifidotos/Latte-Dock
 * branch            master     -> FETCH_HEAD
Already up to date.
```

**Comment by JenaPlinsky** [comment]
@psifidotos  
OK I confirm !!!
After restarting the laptop the problem of **flickering is again present** and clearly visible

**Comment by psifidotos** [comment]
show me because in my system such flickerings dont exist anymore

**Comment by JenaPlinsky** [comment]
Ciao @psifidotos 
> show me because in my system such flickerings dont exist anymore

I confirm that with the default layout, exiting and returning to plasma session, flickering is not observed
So I think the problem is circumscribed to my layout in use and I can also confirm that the problem is not due to the external separator as I removed it from my layout

since the problem described in this discussion **is always reproducible** on my system, I tried to make a comparison of the respective configuration files
- file just completed
[MyDock.layout.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1754522/MyDock.layout.latte.zip)
- file after login
[MyDock.layout_with_flickering.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1754523/MyDock.layout_with_flickering.latte.zip)

do these differences suggest something to you?
```
mio@linux-18t9:~> diff /home/mio/Desktop/MyDock.layout_flick.latte /home/mio/Desktop/MyDock.layout.latte
83c83
< PreloadWeight=28
---
> PreloadWeight=20
793c793
< PreloadWeight=72
---
> PreloadWeight=64
860c860
< PreloadWeight=8
---
> PreloadWeight=0
918c918
< PreloadWeight=73
---
> PreloadWeight=62
1080c1080
< PreloadWeight=81
---
> PreloadWeight=73
1337c1337
< PreloadWeight=81
---
> PreloadWeight=73
1355a1356,1358
> 
> [Containments][271][Applets][307][Configuration]
> PreloadWeight=42
```

**Comment by JenaPlinsky** [comment]
I also observe that although no separator is visible, in the configuration file there are still "separator" keys

I then made a test by copying the file of the layout that presented the problem on the correct layout ... I would have expected to recreate that problem instead nothing to do, latte remains smooth, so maybe the problem is not even related to my layout

.

**Comment by psifidotos** [comment]
Can you show me the flickering in order to understand what we are talking about?

**Comment by JenaPlinsky** [comment]
Ciao @psifidotos 
Here is the video and **I'm sorry for the delay**

P.S. I changed the account on my laptop and then, I've imported the configuration of "Latte" from that old account, because of this thing, the configuration files that I currently use have some references to the old account
- can this thing be the cause of this problem?
- is it possible, in cases like this, to clean the configuration files of milk in which case I open a new thread?

[screencast_2018-03-03_193125.zip](https://github.com/psifidotos/Latte-Dock/files/1777765/screencast_2018-03-03_193125.zip)
[screencast_2018-03-03_193125_slowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1777766/screencast_2018-03-03_193125_slowMotion.zip)

**Comment by psifidotos** [comment]
@JenaPlinsky you need to find a way to reproduce... I tried to load your layout but  first of all there werent any separators as applets, there were only internal separators in Tasks and they were set only at Launchers in Layout mode.

So the best way is to start a layout from scratch and find the steps to reproduce.

**Comment by JenaPlinsky** [comment]
I have a doubt, what can happen if I associate an applet, an image of 127x128 while all the other applets of the dock are 128x128 ?
in any case, for security I'm writing a script to make uniform all my extra icons

**Comment by psifidotos** [comment]
> I have a doubt, what can happen if I associate an applet, an image of 127x128 while  all the other applets of the dock are 128x128 ?

that is the applet responsibility... Latte informs the applet that can use 128x128 and the applet can override this... afterwards based on what the applet demands Latte decides if the parabolic effect will be ok with it or not... If the applet demands 129 px . instead of 128 px. then Latte blocks the parabolic animation for that applet.

**Comment by JenaPlinsky** [comment]
Interesting ! so it's a good thing to make uniform the aspect ratio for all my extra icons all in all it does not cost me anything to do it

**Comment by JenaPlinsky** [comment]
how do I remove internal separators? from the ui is not possible

```
[Containments][13][Applets][69]
immutability=1
plugin=audoban.applet.separator
```

```
[Containments][13][Applets][73][Configuration][General]
launchers=multi;*;2;file:///usr/share/applications/firefox.desktop;file:///usr/share/applications/org.kde.dolphin.desktop
launchers59=file:///latte-separator.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///usr/share/applications/firefox.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///home/Ivan/.local/share/applications/telegramdesktop.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///usr/share/applications/skypeforlinux.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///home/Ivan/.local/share/applications/org.kde.dolphin.desktop
```

```
[Containments][15][Applets][85][Configuration][General]
isInLatteDock=true
launchers=multi;*;2;file:///usr/share/applications/firefox.desktop;file:///usr/share/applications/org.kde.dolphin.desktop
launchers59=file:///latte-separator.desktop
```

```
[LayoutSettings]
activities=
color=blue
launchers=file:///latte-separator.desktop,[c7b541ec-c223-4660-9237-aaa69c2ddb10\\,32ce0942-edce-41b4-b5a5-fab3a366926b\\,75297778-6994-417b-b5e6-ba0cc0934057\\,077609ba-74dc-4150-8d92-74a46b23a404\\,e95c9977-9b8f-4ee4-95b3-b7038bf5c630\\,afaa6c8d-ff8b-49ab-b357-b2d2b48a4009\\,d03c5234-4009-465a-9da3-87bc853a4c3e\\,adc86a77-072c-4231-99e7-108225d83594\\,583e7863-7562-40ad-aed6-37dc244d3be9\\,5c4c45ce-f353-4f31-8a64-3b4db23d382a\\,d6472788-db57-4a05-96b8-299c4853e819]\nfile:///usr/share/applications/firefox.desktop,[c7b541ec-c223-4660-9237-aaa69c2ddb10\\,32ce0942-edce-41b4-b5a5-fab3a366926b\\,75297778-6994-417b-b5e6-ba0cc0934057\\,077609ba-74dc-4150-8d92-74a46b23a404\\,e95c9977-9b8f-4ee4-95b3-b7038bf5c630\\,afaa6c8d-ff8b-49ab-b357-b2d2b48a4009\\,d03c5234-4009-465a-9da3-87bc853a4c3e\\,adc86a77-072c-4231-99e7-108225d83594\\,583e7863-7562-40ad-aed6-37dc244d3be9\\,5c4c45ce-f353-4f31-8a64-3b4db23d382a\\,d6472788-db57-4a05-96b8-299c4853e819]\nfile:///home/Ivan/.local/share/applications/telegramdesktop.desktop,[c7b541ec-c223-4660-9237-aaa69c2ddb10\\,32ce0942-edce-41b4-b5a5-fab3a366926b\\,75297778-6994-417b-b5e6-ba0cc0934057\\,077609ba-74dc-4150-8d92-74a46b23a404\\,e95c9977-9b8f-4ee4-95b3-b7038bf5c630\\,afaa6c8d-ff8b-49ab-b357-b2d2b48a4009\\,d03c5234-4009-465a-9da3-87bc853a4c3e\\,adc86a77-072c-4231-99e7-108225d83594\\,583e7863-7562-40ad-aed6-37dc244d3be9\\,5c4c45ce-f353-4f31-8a64-3b4db23d382a\\,d6472788-db57-4a05-96b8-299c4853e819]\nfile:///usr/share/applications/skypeforlinux.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///home/Ivan/.local/share/applications/org.kde.dolphin.desktop,[c7b541ec-c223-4660-9237-aaa69c2ddb10\\,32ce0942-edce-41b4-b5a5-fab3a366926b\\,077609ba-74dc-4150-8d92-74a46b23a404\\,e95c9977-9b8f-4ee4-95b3-b7038bf5c630\\,00b40232-c1ed-4467-ae25-53bb8bfc1856\\,afaa6c8d-ff8b-49ab-b357-b2d2b48a4009\\,583e7863-7562-40ad-aed6-37dc244d3be9\\,5c4c45ce-f353-4f31-8a64-3b4db23d382a\\,d6472788-db57-4a05-96b8-299c4853e819]\nfile:///usr/share/applications/org.kde.kcalc.desktop
showInMenu=true
version=2
```

**Comment by JenaPlinsky** [comment]
![screenshot_20180304_211704](https://user-images.githubusercontent.com/24593950/36950103-63dbda54-1ff1-11e8-8387-cb4466addac0.png)
- I'm trying to narrow down the problem :)
   only one dock
   only one applet
   no esternal separayor
   and the problem [still present

**Comment by JenaPlinsky** [comment]
I've deleted the separator applet ... why is there still a trace?
to clean the layout I have to delete both items related to applet 69?

```
[Containments][13][Applets][69]
immutability=1
plugin=audoban.applet.separator

[Containments][13][Applets][69][Configuration]
PreloadWeight=0
```

**Comment by psifidotos** [comment]
> how do I remove internal separators? from the ui is not possible

it is possible, in EditMode(when showing the dock settings), you can right click them, a remove option is offered and to assign them to different activities also

> to clean the layout I have to delete both items related to applet 69?
yes

**Comment by JenaPlinsky** [comment]
![screenshot_20180304_233721](https://user-images.githubusercontent.com/24593950/36951508-fd949d3a-2004-11e8-8812-0ca570f87445.png)


do you mean this one?
I do not see any item to remove the separators

**Comment by psifidotos** [comment]
this is to add it... after you add it, right click on the added separator

**Comment by JenaPlinsky** [comment]
Ok I tried to add a new one and then I managed to remove it ...
The fact is that I can not delete those indicated by the layout ... I can not see and I can not select them ... now I'll try to edit the layout

**Comment by psifidotos** [comment]
> The fact is that I can not delete those indicated by the layout ... I can not see and I can not select them ... now I'll try to edit the layout

you should choose Layout Launchers from Tasks page in advanced mode

**Comment by JenaPlinsky** [comment]
Wowwww I had to play between layout and unique to find them all and now that I have eliminated everything flows smoothly like butter

it remains only a separator mentioned below ... do you think I missed something?

```
[Containments][13][Applets][73][Configuration][General]
launchers=multi;*;2;file:///usr/share/applications/firefox.desktop;file:///usr/share/applications/org.kde.dolphin.desktop
launchers59=file:///latte-separator.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///usr/share/applications/firefox.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///home/Ivan/.local/share/applications/telegramdesktop.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///usr/share/applications/skypeforlinux.desktop,[32ce0942-edce-41b4-b5a5-fab3a366926b]\nfile:///home/Ivan/.local/share/applications/org.kde.dolphin.desktop
```

**Comment by psifidotos** [comment]
no I dont think show...

**Comment by JenaPlinsky** [comment]
therefore internal separators were involved in this type of problem
- It remains now, to understand why only I had it
- do you think the problem is reproducible now, playing with the separators? not is easy I think also because it appears only after login
- Is there a logical way to display and delete them easily?

**Comment by psifidotos** [comment]
> do you think the problem is reproducible now, playing with the separators? not is easy I think also because it appears only after login

if you manage to reproduce it, first thing to try is to make a task drag because after dragging the internal separators update their indexes, so there is a chance that it would fix it.

> Is there a logical way to display and delete them easily?

except the ways mentioned no other way exists...

**Comment by JenaPlinsky** [comment]
it would be enough to find the flickering, the method to delete is correct .... probably the separators not related to the "launchers group" in use, should be irrelevant and maybe is escaped something here ...
we will see

**Comment by JenaPlinsky** [comment]
Please try to add an internal separator as "UNIQUE" launchers group 
I think that the problem is that

**Comment by psifidotos** [comment]
I tried but it wasnt reproduced... :(

**Comment by JenaPlinsky** [comment]
I can no longer replicate the issue so how about if we close it ?
