### ISSUE TITLE
sometimes the --replace option does not work

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#872]
... or better, it does not always work
even with root privileges
...then after having forced its closure from ksysguard I've tried again and it works correctly 
... very strange
```
mio@linux-18t9:~> latte-dock --replace
"An instance is already running!, use --replace to restart Latte"
```

**Comment by psifidotos** [comment]
a way to reproduce... except if latte-dock that you are trying to substitute isnt in a normal mode and something has gone wrong with it...

**Comment by JenaPlinsky** [comment]
![screenshot_20180221_012310](https://user-images.githubusercontent.com/24593950/36456647-20c3eff8-16a6-11e8-815f-df2c082585c8.png)
Konversation's name "Latte-dock" very odd

**Comment by psifidotos** [comment]
> Konversation's name "Latte-dock" very odd

is that relevant to this issue?

**Comment by JenaPlinsky** [comment]
I do not believe

**Comment by psifidotos** [comment]
I have  no idea how you fall into such situation....

**Comment by trmdi** [comment]
Did you type `latte-dock --replace` from Konsole or from Krunner @psifidotos  ?

**Comment by psifidotos** [comment]
> Did you type latte-dock --replace from Konsole or from Krunner @psifidotos ?

konsole

**Comment by psifidotos** [comment]
this happens to my system only in cases that the entire system needs some time to close that application
