### ISSUE TITLE
No config dialog for Latte plasmoid (standalone)

### ISSUE THREAD

**Issue by hetdegon** [psifidotos/Latte-Dock#873]
It seems since commit 8fb12bdbcf90bc10e25b5030710bd0dd357b9b57, Latte Plasmoid cannot be configured when used standalone inside a Plasma dock. 
While this seems intentional, it makes the plasmoid unusable standalone, unless editing the plasmashell config file, which is remarkably human-unfriendly.

**Comment by psifidotos** [comment]
it isnt intentional :-) i will fix it

**Comment by hetdegon** [comment]
That's great to hear, thank you.
