### ISSUE TITLE
Latte dock doesn't animate launching of applications if the parabolic effect is disabled

### ISSUE THREAD

**Issue by zzag** [psifidotos/Latte-Dock#874]
At a given moment, latte-dock animates(by jumping) launching of applications only if Zoom On Hover is greater than 0(i.e. the parabolic effect is enabled). It would be great to have launch application animations even if the parabolic effect is disabled.

Step to reproduce:
* disable parabolic effect
* launch an application

Expected result:
* have some animation, like jumping

Latte dock version: right from the master branch

**Comment by psifidotos** [comment]
I suppose you like the jumping animation but you dont like the parabolic one?

**Comment by zzag** [comment]
I like them both but the parabolic effect feels to me weird. (not the same as in plank)

Also, it is good to separate two different animations.

**Comment by psifidotos** [comment]
> I like them both but the parabolic effect feels to me weird. (not the same as in plank)

I see... unfortunately it would add configurability above the goals of the project so I am sorry but I dont think I can add this...
