### ISSUE TITLE
Add the ability to go down the app and Automatic shrink [suggestion]

### ISSUE THREAD

**Issue by relsi1053** [psifidotos/Latte-Dock#876]
This app is really fantastic
But I think adding the following features will be better
1- If the program can have "windows go abov" in addition to the "windows go blow" feature, it will be very useful.
2. If this is possible when you maximize the window instead of fading dock have a smaller dock,it will be very useful

**Comment by psifidotos** [comment]
> 1- If the program can have "windows go abov" in addition to the "windows go blow" feature, it will be very useful.

unfortunately this is out of the design decisions... 

> 2. If this is possible when you maximize the window instead of fading dock have a smaller dock,it will be very useful

I dont understand what you are describing
