### ISSUE TITLE
Allow keyboard shortcuts for widgets on the dock

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#879]
When you open the menu, you can drag and drop onto the latte-dock. This creates a little widget of the application. I would love if you could have a separate set of keyboard shortcuts to open up these and not just entries within the latte task manager.

I suppose alternatively if you could not show the running applications in the task manager BUT then custom application commands won't work. For example I have many different separate profiles of firefox (with `firefox -p profile`) which will be grouped into one pinned application.

**Comment by psifidotos** [comment]
> I would love if you could have a separate set of keyboard shortcuts to open up these and not just entries within the latte task manager.

I cant understand you ... you mean shortcuts in order to trigger applets showing their popups?

> For example I have many different separate profiles of firefox (with firefox -p profile) which will be grouped into one pinned application.

you can ungroup windows if you want for a specific application, there is a action for this in the Tasks page in config window

**Comment by RaitaroH** [comment]
So here is an example of a application widget that is created when you drag it onto the panel or latte dock:

![screenshot_20180222_185057](https://user-images.githubusercontent.com/19552720/36551930-62b5c646-1801-11e8-8698-7c641ba8713d.png)
![screenshot_20180222_185107](https://user-images.githubusercontent.com/19552720/36551931-62dae0c0-1801-11e8-8268-4945dcd7d7a3.png)

I don't mean to trigger popups. I mean to open these kind of application widget you get on you drag and drop onto the panel.

It is also not a case of ungrouping applications either.
`firefox -p profile1` and `firefox -p profile 2` cannot be pinned in the taskbar (too my knowledge) as separate entries. Also their icons is different too. In the edit applications I can make SEPARATE entries for both of these, with different name, with different icons. The only way to get them onto the panel is to drag and drop them.

**Comment by RaitaroH** [comment]
Well then this could be done in a different way:
1. allow not showing the running applications in the latte task manager, only pins
2. allow customizing the command of pinned applications in the panel with different commands, names and icons.

The second might be quite hard to do I suppose.

**Comment by psifidotos** [comment]
> allow customizing the command of pinned applications in the panel with different commands, names and icons.

this is totally plasma libtaskmanager behavior and not Latte... Latte isnt using its own implementation to handle launchers and tasks... this is provided by plasma through plasma libtaskmanager

**Comment by psifidotos** [comment]
I will try to approach this and see how much mess it creates...

**Comment by RaitaroH** [comment]
Oh you will? Nice. Even if you can't implement it, thank you.

**Comment by psifidotos** [comment]
ok I think, we can have this... ;) it is a matter of days I think... :)

![default](https://user-images.githubusercontent.com/2216474/36644151-ad42ed92-1a5e-11e8-8118-221c38ff7a59.png)

**Comment by psifidotos** [comment]
implemented with commits between : https://github.com/psifidotos/Latte-Dock/commit/db28c6bcafffd831e8c11544a3afced7da4a6cee
and: https://github.com/psifidotos/Latte-Dock/commit/052a8519ceec3c684ab00b9f5083d14cc481d638

**Comment by psifidotos** [comment]
ok you can test it... ;)

**Comment by psifidotos** [comment]
![default](https://user-images.githubusercontent.com/2216474/36645075-25caed66-1a6c-11e8-9c18-62e7c67a4774.png)

**Comment by RaitaroH** [comment]
Does work, thank you very much.

**Comment by RaitaroH** [comment]
Ah, if I may point out a couple minor of issues with this:
1. the justify icons are also recognized but obviously calling them does nothing
2. this only works if you have latte plasmoid on the panel. If you don't it does not respond.
3. also you get z x c after 0 even thou those + meta are not actually mapped to a latte command. I even have those for different things entirely.
Again not big of a deal issues.

Actually you do not need the meta key in the kwinrc file. I use Meta+` to show the numbers and Meta+NR does the job regardless. I have krunner set to meta :P

Nevertheless, thank you for this. I really wanted this behaviour for a very long time.

**Comment by psifidotos** [comment]
(1) - good catch, fixed with: https://github.com/psifidotos/Latte-Dock/commit/db58a240400e4dbf6c87dac0c7ab04acb881e813

(2) - this is intentional to keep things simple... global shortcuts work only with panel/docks that contain a latte or plasma taskmanager

(3) - of course they can be mapped... All Latte shortcuts can be accessed through plasma systemsettings.

![default](https://user-images.githubusercontent.com/2216474/36681422-41996616-1b21-11e8-9497-1cfc4674f496.png)

> Actually you do not need the meta key in the kwinrc file. 

(4) -This is for a different feature... To show the application launcher.... :
![default](https://user-images.githubusercontent.com/2216474/36681512-79b2a95e-1b21-11e8-9c96-39fd78473348.png)

**Comment by RaitaroH** [comment]
Well then, I guess that's about it.

Again, my gratitude for this.
