### ISSUE TITLE
Remove the clock in the dock

### ISSUE THREAD

**Issue by blop135** [psifidotos/Latte-Dock#880]
Hi,

Sorry dumb question but I looked everywhere and I didn't manage to figure it out. Can we remove the clock in the dock? 

Thank you in advance;)

**Comment by blop135** [comment]
Ok really sorry I figured it out finally, you can close this thread.

Thanks for your amazing app:)

**Comment by psifidotos** [comment]
yep... ;) in editing mode you can remove and reposition whatever applet you want..  that is when the settings window is shown...
