### ISSUE TITLE
Plasmoid not remembering pinned items

### ISSUE THREAD

**Issue by hetdegon** [psifidotos/Latte-Dock#881]
Latte version: 1e57260c5fbd810a92772942f0ee33d546be59a6
Plasmashell version:  5.12.2
OS: Ubuntu 17.10 64b

When changing pinned items all changes will be lost upon restart when using Latte as a plasmoid in a regular plasma panel.
The only way I found for it to keep a number of pinned items on restart is to add them manually to the plasma-org.kde.plasma.desktop-appletsrc file, which looks like this (relevant section only): 
```
[Containments][19][Applets][129][Configuration][General]
dotsOnActive=true
durationTime=0
iconSize=32
launchers59=applications:Slade.desktop,applications:godot.desktop,applications:atom-beta.desktop,applications:gimp.desktop,applications:Krita.desktop,applications:Blender.desktop,applications:quiterss.desktop,applications:firefox.desktop,applications:org.kde.krusader.desktop,applications:org.kde.konsole.desktop
middleClickAction=Close
plasmoidPosition=Left
showBarLine=false
showOnlyCurrentActivity=false
showOnlyCurrentDesktop=true
showToolTips=true
showWindowActions=true
threeColorsWindows=true
transparentPanel=true
zoomLevel=0
```

The property name being "launchers59" might have something to do with it? All other config settings seem to be remembered properly.

**Comment by psifidotos** [comment]
@hetdegon  ok fixed... ;)

do you want to show me how do you use Latte in plasma panel? 
You are the first user that is trying something like this...

**Comment by hetdegon** [comment]
Can confirm it fixed, thank you!
And, sure, here's my panel:
![out5](https://user-images.githubusercontent.com/323651/36646962-13bb96e4-1a7f-11e8-9edc-5af162150008.png)
I just tried it randomly one day and found it rendered icons better than the standard icons-only-taskmanager, so have been using it like this since. I also like the glowy indicators more.
