### ISSUE TITLE
Network applet in systray not showing

### ISSUE THREAD

**Issue by nivaca** [psifidotos/Latte-Dock#882]
For some strange reason, the network applet icon is not showing in the systray in Latte-Dock. It is indeed running, as I can display its menu by giving it a shortcut key. (It is not hidden inside the systray, btw.)

(The problem only occurs in Latte-Dock, not in normal panels.)

I'm running Latte-Dock v.0.3.7.1 on Arch Linux (KDE Plasma 5.2.12, KDE Frameworks 5.43.0, Qt Version 5.10.1, Kernel 4.15.5-1-ARCH).

You can see in this screenshot that the applet doesn't show up on the Latte-Dock (bottom) but it does on panel (right).

![screenshot_20180225_221617](https://user-images.githubusercontent.com/2309005/36651927-85845230-1a79-11e8-9ae0-de562178c53a.png)

**Comment by psifidotos** [comment]
Have you tried to use the systray only inside Latte?

**Comment by nivaca** [comment]
Yes, of course. This was only for demonstration purposes.

**Comment by psifidotos** [comment]
this is my network applet in systray... the icon next to telegram...

![default](https://user-images.githubusercontent.com/2216474/36680255-e87e4982-1b1d-11e8-82cc-1d99c893e6c2.png)
