### ISSUE TITLE
Trash widget in vertical dock is not animated on hover

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#883]
Every other widget and the task manager icons are animated. The trash does not animate.

**Comment by psifidotos** [comment]
- Have you lock it to not animate?
- Do you have a screenshot?

This is from my system.... 
![default](https://user-images.githubusercontent.com/2216474/36686926-aaad1bb6-1b30-11e8-855e-964ce804d4b6.png)

**Comment by RaitaroH** [comment]
Also to be very clear the widget is not locked either. I locked it and unlocked it just to check and I get this. I have the latest version of KDE Neon and the Latte commit before the justify fix.

[Here](https://www.youtube.com/watch?v=Q8cOnJk5snk&feature=youtu.be) is a video.

**Comment by psifidotos** [comment]
looks like specific to Breeze icons...

**Comment by RaitaroH** [comment]
Hmm.. I switched to la-capitaine and did a restart plasmashell and it's still there. Now... I didn't quite install the la-capitaine nicely. It is a modified version.

**Comment by RaitaroH** [comment]
Also for some reason the trash icon is the only one what gets a normal popup with the tile and not the more condensed version that latte has.  I did show it in the video.

**Comment by psifidotos** [comment]
doesnt look a Breeze issue...

![default](https://user-images.githubusercontent.com/2216474/36741384-9f3eb5f6-1bed-11e8-925d-8c2b990bc6ce.png)


dont you get that popup?

![default](https://user-images.githubusercontent.com/2216474/36741439-c9e75524-1bed-11e8-95fb-ae0c8505fb1f.png)

**Comment by RaitaroH** [comment]
Normal popup of a widget (same thing with clock, menu etc)
![1](https://user-images.githubusercontent.com/19552720/36770885-b9d4bba0-1c55-11e8-90b1-a2a14ed6d74d.png)
![2](https://user-images.githubusercontent.com/19552720/36770886-b9faddd0-1c55-11e8-8f38-b892b29a6591.png)
![3](https://user-images.githubusercontent.com/19552720/36770887-ba1776e8-1c55-11e8-9c8c-0400744f2e6c.png)
![4](https://user-images.githubusercontent.com/19552720/36770888-ba34a7a4-1c55-11e8-8aa3-8633153cf762.png)

**Comment by RaitaroH** [comment]
Eh, I just copyed the panel and removed the original, with the trash icon on it. Seems that the problem got "fixed", not sure why.

**Comment by RaitaroH** [comment]
XD Noooope. That was worse. Now all my dropped widgets give this error:
![image](https://user-images.githubusercontent.com/19552720/36771461-46efc310-1c59-11e8-8dac-0c9581452ebc.png)

Fuck it I guess. I will just redo the whole thing manually.

**Comment by RaitaroH** [comment]
@psifidotos even more info... as I said above the issue was solved after making a new panel, but after a reboot it is there again.

**Comment by psifidotos** [comment]
@RaitaroH this is happening only when the dock is vertical... and there is big chance that this is because the specific applet returns its Layout settings (maximum, minimum etc.) wrongly... It returns bigger value that the applet size set by the user and that means that it could break the parabolic effect and for that Latte blocks it...

I will look into that and see if an upstream fix can be accepted...

**Comment by psifidotos** [comment]
It is clearly a bug in plasma... it is missing a return statement at:
https://github.com/KDE/plasma-desktop/blob/master/applets/trash/package/contents/ui/main.qml#L48

**Comment by psifidotos** [comment]
patch: https://phabricator.kde.org/D10979

**Comment by psifidotos** [comment]
commited for plasma 5.13

**Comment by RaitaroH** [comment]
@psifidotos It got fixed now.
lattedock 0.7.78
Neon 5.12.2

**Comment by RaitaroH** [comment]
@psifidotos Actually what got it fixed was:
1. move the dock at the top (so horizontal)
2. then move it back to the left (so vertical)

Now it gets fixed till next time is restarted.

o.O

**Comment by psifidotos** [comment]
This is fixed for plasma 5.13 not plasma 5.12
