### ISSUE TITLE
Minimize animation getting confused

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#885]
I have a normal panel at the bottom with a normal taskmanager. I also have latte as a left dock with the latte plasmoid, also a taskmanager (I need it for the meta keys to work with other widgets). Seems the minimize animation is favoring the latte instead of the normal taskmanager even if I click on the bottom tasks to minimize or maximize, they still animate to the left. Minimize application and magic lamp still do this.

Is there a way to choose what taskmanager is doing the animation or is this just a weird KDE behaviour that cannot be fixed?

**Comment by psifidotos** [comment]
> Is there a way to choose what taskmanager is doing the animation

unfortunately not...

> or is this just a weird KDE behaviour that cannot be fixed?

taskmanagers in general are designed to be one per screen. So this issue falls in that category...
