### ISSUE TITLE
Bug when copying a dock

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#887]
Steps to reproduce:
1. edit dock
2. new dock > copy
3. delete new dock created

Now all the widgets that are drag and drop (not widgets like clock, trash etc) on the first panel (the original panel) return this error:
![image](https://user-images.githubusercontent.com/19552720/36773070-77411e54-1c60-11e8-9179-ada8fc3b0be5.png)

~~To fix simply remake a copy of the dock (doesn't matter if it is broken) then delete the broken one (what you just used to copy).~~ It actually has the same issue after some time.

**Comment by psifidotos** [comment]
Can you send me your layout file to take a look?

Στις 28 Φεβ 2018 8:23 π.μ., ο χρήστης "RaitaroHikami" <
notifications@github.com> έγραψε:

**Comment by RaitaroH** [comment]
[Done.layout.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1767420/Done.layout.latte.zip)
I also had issues with trying to change to this layout. It simply didn't recognize it and instead went with a default configuration. Now, I won't risk it because I already remade this panel 3 times by now so....


Should I just try to recompile the github code and delete all the config? I have played before with an older release of latte so maybe this sudden jump might be the cause.

**Comment by psifidotos** [comment]
I tried in one of my layouts to reproduce... I didnt succeed... I used a default desktop file, not a local one without any issues...

maybe this is related to the fact that you use edited desktop files...
If you try a default layout and add an original desktop file, do you have any issue?

P.S. There is a chance that this is related to icon applet and not Latte... in your layout file I see: 

```
[Containments][105][Applets][108][Configuration]
localPath=/home/raitaro/.local/share/plasma_icons/org.kde.dolphin (1).desktop
url=file:///home/raitaro/.local/share/applications/org.kde.dolphin.desktop

[Containments][105][Applets][109]
immutability=1
plugin=org.kde.plasma.icon
```

I suppose the localPath and the url should be the same... 
have you tried to drag n' drop the needed desktop file from Dolphin manager onto Latte to see if this fixes it?

**Comment by RaitaroH** [comment]
In `/home/raitaro/.local/share/plasma_icons/` you also get the icons from the other panels. When I created my latte dock I copied the stuff I had from my original non-latte dock. So that's why it has a (1) in the name. Removing both latte and that original non-latte panel cleared the contents of the folder, and now latte is actually not having this bug anymore.

As you can see there is no `(1)` in the name anymore. Also in the plasma_icons folder I only have the icons on the latte dock thus it does not get confused anymore even after repeated coping of the dock, deleting it (like I mentioned above)
[Done.layout.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1771229/Done.layout.latte.zip)

**Comment by psifidotos** [comment]
When you remove an icon applet the associated desktop file is deleted?????

**Comment by RaitaroH** [comment]
@psifidotos Hmm... actually I tested and it does not o.O The hell happened XD

Well, maybe was a really weird one off thing. Sorry to scare you.
