### ISSUE TITLE
Adding new applications (drag and drop) defaults as pinning to the latte task manager also cannot delete latte task manager

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#888]
So as the title says. There is also the case of not being able to remove the latte plasmoid if there is only one existing. You have to create a new panel, remove the latte plasmoid from what you wanted, then delete the temp panel.

https://www.youtube.com/watch?v=5HSviQ-G8GY&feature=youtu.be

**Comment by RaitaroH** [comment]
To be fair, I know about deleting the dock from another issue but the "problem" is still there.

**Comment by psifidotos** [comment]
> There is also the case of not being able to remove the latte plasmoid if there is only one existing. 

Tweaks - > Remove Tasks (Extra Actions)

> Adding new applications (drag and drop) defaults as pinning to the latte task manager

Tweaks -> (Uncheck) Add launchers only in the corresponding area


These are sane defaults and it also offered an alternative for the adventures, so there isnt anything to be changed for them...

**Comment by RaitaroH** [comment]
A... I mean... I think I am pretty good at options but I had no idea what those were supposed to do. Well, thank you. Now everything is fine.
