### ISSUE TITLE
Show tasks from current activities

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#89]
"Show tasks from current activities"
Is there a way to avoid opening a new instance of an application if it is already open on another activity? maybe you could move it to the current task ? or indicate in some way that there is already an open instance? ... This is supposed to be just a thought ... it might make sense?

**Comment by psifidotos** [comment]
The best way to do this is through kwin manager, set up a window rule in order for each specific application you want to be on all activities and desktops always.

To do this, right click on the window title bar, window rules
Enforce to all activities and to all desktops.

Personally i do this for browser, video player, music player, chat applications
