### ISSUE TITLE
Firefox audio Indicator isnt closing even though the audio has stopped

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#890]
Latte in order to track if an audio has stopped or not uses the pulseaudio stream. The pulseaudio stream should be freed when the audio stops.

Such issue has been tracked down from Firefox and it is an upstream bug that should be reported...

**Comment by psifidotos** [comment]
reported at: https://bugzilla.mozilla.org/show_bug.cgi?id=1442535

**Comment by RaitaroH** [comment]
@psifidotos Vlc does the same btw.  Even if the playback is paused, the icon is persistent. Vlc appears in my sound applet and also in pulseaudio. Same with audacious or waterfox. 

Funny enough if I play a video in waterfox and I stop it, the icon is there, but if the video (on youtube) ends on it's own then the audio icon goes away. Audacious has the same behavior (using Ctrl+M to stop after current ends) the icon for audio goes away. 

So if anything I think it is an upstream bug that shows a application as running when is stopped.

**Comment by psifidotos** [comment]
the important thing is the application to release the pulseaudio stream when no audio exists... I suppose you are using vlc 3.x because at vlx 2.x this doesnt happen...

**Comment by RaitaroH** [comment]
Actually vlc 2.2.2. And it happens as I mentioned above: the audio icon goes away only when the playback ends on it's own and not when is paused.

**Comment by RaitaroH** [comment]
I am recompiling right now.

**Comment by RaitaroH** [comment]
@psifidotos Well it did fix audacious and vlc. Seems that both firefox nightly and waterfox didn't quite like the fix. Well, I suppose that can't be helped.

**Comment by psifidotos** [comment]
@RaitaroH it isnt complete... plasma is using a different approach than mine.. I am trying to understand how it suceeds in this... because waterfox doesnt provide an mpris player and plasma still identifies it...

**Comment by RaitaroH** [comment]
@psifidotos Well nevertheless good fix.

Also regarding the touchpad scroll being registered as always scrolling down. I think is the same bug I am having [here](https://bugs.kde.org/show_bug.cgi?id=388353). 

Also do you sometimes get your touchpad kinda... blocked and you cannot move the cursor but only right click or middle click? Sometimes just pressing on it hard gets rid of the issue but is weird. Once I had to restart just because it really wasn't working.

**Comment by psifidotos** [comment]
I dont use touchpad

**Comment by psifidotos** [comment]
ok, this is fixed... thanks for the patience to point me to correct direction...

for touchpad issue open a different issue and try to be as more descriptive as possible...

**Comment by RaitaroH** [comment]
@psifidotos Yep everything is fixed now.
