### ISSUE TITLE
Default pinned apps are always restored after unpinning

### ISSUE THREAD

**Issue by wxnarwhal** [psifidotos/Latte-Dock#891]
Great work on this project, this is the best dock out there for sure.

lattedock 0.7.3

Distributor ID: neon
Description:    KDE neon User Edition 5.12
Release:        16.04
Codename:       xenial

I have two apps that are pinned by default when installing from the repository: Firefox and Dolphin.  I unpin those apps and they disappear.  When latte-dock is restarted both apps are pinned to latte-dock again.  I have confirmed on two machines that are running the identical versions listed above.

When looking at ~/.config/latte/My Layout.layout.latte I see the following lines:

launchers=multi;*;2;file:///usr/share/applications/firefox.desktop;file:///usr/share/applications/org.kde.dolphin.desktop
launchers59=file:///usr/share/applications/firefox.desktop,file:///usr/share/applications/org.kde.dolphin.desktop

When I unpin Firefox and Dolphin the line for "launchers59" is removed but the line for "launchers" remains.  When I relaunch latte-dock I can see that the line "launchers59" gets readded and Firefox and Dolphin are repinned to latte-dock.

**Comment by psifidotos** [comment]
the launchers are the backup from previous versions  and there is no indicator that the user has set empty launchers by choice... what you could do is to remove launchers record  totally...

**Comment by wxnarwhal** [comment]
Thanks for your reply.  I'm don't follow your comment "there is no indicator that the user has set empty launchers by choice".  Isn't the fact that I unpinned them an indicator that I don't want the launchers?  If there's a way that I can edit the config file to fix the issue I'm happy to do it but I feel like the default expectation for unpinning an app is that is stays unpinned.

**Comment by psifidotos** [comment]
I suppose the solution would be after the first importing from lauchers to launchers59 then launchers should be deleted afterwards...

**Comment by wxnarwhal** [comment]
I did manually delete launchers in the config files so latte-dock works to my satisfaction.  I think there are different ways to look at it but your proposed solution is simple and it would fix the issue.  Thanks.

**Comment by psifidotos** [comment]
fix will be part of v0.7.4 and master
