### ISSUE TITLE
Please add outline for shadowless dock (or add a checkbox for that)

### ISSUE THREAD

**Issue by andreyorst** [psifidotos/Latte-Dock#897]
When dock has no shadow it looks kinda out of this world. Espeshially on light backgrounds. With thin outline it will look more native. 

Possible solutions:
1. Change shadow radius to 1px. It will be thin and not as distracting as it already is.
2. Use solid background, It already has grey outline, but has no transparency, so adding a transparency will be a nice solution.

---

And god please add top rounded corners like breeze windows have. I know that panels have none, but rounded corners with outline would be so mac'ish... oh god how mac'ish it wold be.....

**Comment by psifidotos** [comment]
@andreyorst what latte version are you using?

> Change shadow radius to 1px. It will be thin and not as distracting as it already is.

you can change Applet Shadows settings through Appearance page in advanced mode


> Use solid background, It already has grey outline, but has no transparency, so adding a transparency will be a nice solution.

you can change the background settings, size, transparency, solidness etc... through Appearance page in advanced mode

> And god please add top rounded corners like breeze windows have. I know that panels have none, but rounded corners with outline would be so mac'ish... oh god how mac'ish it wold be.....

this is plasma theme responsibility... there are plenty beautiful plasma themes with rounded corners... Arc, Arc Color, Adapte etc...

![default](https://user-images.githubusercontent.com/2216474/36951506-5a6f7036-200d-11e8-8692-a1cf5f3c169d.png)

**Comment by andreyorst** [comment]
>@andreyorst what latte version are you using?

I am using archlinux AUR package [latte-dock-git](https://aur.archlinux.org/packages/latte-dock-git) which refers that it's version is 0.7.78.

> you can change Applet Shadows settings through Appearance page in advanced mode

Yes I do, but there is no way to set it to 1px, only to 0-5% strength. And I am talking about Latte's shadow, not applet shadow.

> you can change the background settings, size, transparency, solidness etc... through Appearance page in advanced mode

Yes I do, but there is no option to change transparency for solid background (because it's kinda solid, lol). But solid background has that fancy outline I'm talking about.
![image](https://user-images.githubusercontent.com/19470159/36958576-ec36f99a-204d-11e8-8a9d-d6544a64dfa0.png)
beautiful outline, that shines on dark backgrounds:
![image](https://user-images.githubusercontent.com/19470159/36958581-ffe1f45e-204d-11e8-90d1-edc579acfb34.png)
Shadowless dock on light bg:
![image](https://user-images.githubusercontent.com/19470159/36958629-480cabe8-204e-11e8-9aa2-f1b120eb9dab.png)
On dark:
![image](https://user-images.githubusercontent.com/19470159/36958652-62012bf0-204e-11e8-86ed-c9f9593c40ce.png)
(it is transparent but hell lot of new plasma blur makes it look like matte glass)

See? With outline it looks more solid on dark bg, but the lack of transparency makes it less beautiful.

> this is plasma theme responsibility... there are plenty beautiful plasma themes with rounded corners... Arc, Arc Color, Adapte etc...

Well I know that It depends on personal taste, but I think that Arc is awful and too overhyped, Adapta is a gnome theme (and Arc too) and can make gnome look good only because gnome is ugly by default. And Adapta has insane contrast in elements, and it looks bad even in gnome. And they're both Aurorae themes which makes them unusable, because they can't change border size, colors of window header, etc etc. Therefore there is only Breeze that is good for plasma. In my personal taste, ofcourse.

But. Dock mode isn't a panel mode, and if plasma panels doesn't have rounded corners, I believe that dock should have one. Or at least have a setting for that. 

![screenshot_20180305_084752](https://user-images.githubusercontent.com/19470159/36959191-dfd4cad4-2051-11e8-99ef-27b0b034ad1e.png)
I imagine a combo with rounded corners and light thin outline that will make perfect match to such setup.

**Comment by psifidotos** [comment]
Ok, I understand but unfortunately wont be implemented...

Latte has a design decision to use the plasma theme used as much as possible. Thus respects the original designer design vision and adds something only when that option has a big demand **and** at the same time doesnt break the experience from the chosen plasma theme...

All of the options you are mentioning can be provided from a tailored plasma theme... For example you could take the plasma theme you like, alter it at your own preference and share that with the rest of the plasma community.

**Panel shadow:** this is plasma theme responsibility, exception is when you enable panel shadow with solid background and that shadow there are themes and combinations that can break. Main reason for this exception is a solid top panel when used at 100% maximum length

> (it is transparent but hell lot of new plasma blur makes it look like matte glass)

you can change the level of blur through plasma systemsettings

> rounded corners

plasma theme responsibility

> But. Dock mode isn't a panel mode, and if plasma panels doesn't have rounded corners, I believe that dock should have one. Or at least have a setting for that.

the panel background used is the same for Dock and Panels and is found at plasma theme and can have as big rounded corners as its designer wants to...

In my opinion I think you want a very specific plasma theme, unfortunately the only way I can think of is to create it and share it...

**Comment by psifidotos** [comment]
I forgot to answer the topic.... "add outline for shadowless dock", in that I agree, that would be a good addition but undortunately the plasma theme doesnt expose its roundness... So I can not implement an outline when I dont know the metrics of the plasma theme...

**Comment by andreyorst** [comment]
> Latte has a design decision to use the plasma theme used as much as possible. Thus respects the original designer design vision and adds something only when that option has a big demand and at the same time doesnt break the experience from the chosen plasma theme...

This is fair enough and no other explanations are needed. Thanks.

> For example you could take the plasma theme you like, alter it at your own preference and share that with the rest of the plasma community.
In my opinion I think you want a very specific plasma theme, unfortunately the only way I can think of is to create it and share it...

I've already [did](https://store.kde.org/p/1170816/)!)
I'll look more closely for shadows and corners in my theme, thanks for the advice.

> I forgot to answer the topic.... "add outline for shadowless dock", in that I agree, that would be a good addition but undortunately the plasma theme doesnt expose its roundness... So I can not implement an outline when I dont know the metrics of the plasma theme...

Understood.

**Comment by psifidotos** [comment]
all these settings in the plasma theme are found at:

`
widgets/panel-background.svg
`
