### ISSUE TITLE
High (relatively) memory usage by dock

### ISSUE THREAD

**Issue by mkudro** [psifidotos/Latte-Dock#898]
Latte at startup consumes some 90+MBs of RAM. Gradually, in a few hours, memory usage is growing towards 240MBs of RAM. I don't know if it is expected, but it seemed little bit higher then i would expected from this application.
Just for info - i'm running dock in "Extended" layout, with "Global menu" and "Pager" as only extra widgets on the top panel. On the bottom i have only "Application dashboard" as extra widget.
OS - fedora 27, plasma 5.12.2, kf5 5.44.0, QT 5.9.4

**Comment by psifidotos** [comment]
yep... this is normal...

if you dint use Latte and you were using plasma panels you would have the following:

1. Only plasma: 340Mbyte
2. Plasma+Latte: Plasma(120Mbyte) + Latte (240Mbyte) = 360Mbyte

so in my system Latte adds around 20-30 Mbyte compared to just using plasma panels

**Comment by mkudro** [comment]
OK.. thanks for quick response. I never took an effort looking into plasma panel memory consumption. Always regarded as Plasma total sort of thing...
closing this one.
