### ISSUE TITLE
Right clicking on the panel in edit mode then clicking away makes the panel hide but the option menu stays

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#900]
lattedock 0.7.78
Steps to reproduce:
1. latte settings
2. right click again in the blueprint area
3. move away and click the desktop
4. the dock hides but not the menu.

It happens in vertical and horizontal configurations for me.
![example](https://user-images.githubusercontent.com/19552720/36982510-aac3b67e-2098-11e8-8e6b-c5fd77fc5788.png)

**Comment by psifidotos** [comment]
in wayland that is ?

**Comment by psifidotos** [comment]
nice catch, fixed...
