### ISSUE TITLE
[Feature Request] Custom Panel Sizes

### ISSUE THREAD

**Issue by beojan** [psifidotos/Latte-Dock#902]
The ability to set a free-form panel size, that doesn't correspond to an icon size.

**Comment by psifidotos** [comment]
If you dont care about the small blur that would introduce then:

1. Tweaks -> (uncheck) Shrink applets size when ever it is needed
2, Without disabling the advance mode in Latte settings change the applets size

**Comment by beojan** [comment]
The Shrink applets size option is disabled.

**Comment by psifidotos** [comment]
In such case just change the applet size in advanced mode, it should change at steps of 1

**Comment by beojan** [comment]
That doesn't seem to be the case. I'm using version 0.7.4 from Arch.

**Comment by psifidotos** [comment]
I checked and it is in the code of v0.7.4 ...
can you make a screenshot of the settings window for Appearance page and Tweaks page for these options?
