### ISSUE TITLE
Strange icon behavior when using custom .destkop files

### ISSUE THREAD

**Issue by smensak** [psifidotos/Latte-Dock#903]
Hi, 
I experienced strange behavior while using latte-dock with .destkop files I wrote for scripts or basicaly any executable. When Iaunched from KDE app menu, all works, correct icons shows up in latte-dock. But when pined and closed,  original icon is replaced by "unknown" icon (see screenshot bellow). When launched again, icon goes back to normal.
![screenshot_2018 03 05_18 00 21](https://user-images.githubusercontent.com/27579955/36988500-5340cd18-209f-11e8-98e3-1a3f6c64b36b.png)
![screenshot_2018 03 05_18 00 30](https://user-images.githubusercontent.com/27579955/36988502-548cdc8e-209f-11e8-9038-2753d1fd8c41.png)

So I tried to go around this issue only to euncounter another strange behavior. When .desktop file is droped to latte-dock it seem good, even icon is there. However that only lasts until you open the app.  Then it will open with new "instance" of the app (see screenshot again) leaving the original icon as some kind of weird launcher.
![screenshot_2018 03 05_17 38 04](https://user-images.githubusercontent.com/27579955/36988959-9010f83e-20a0-11e8-9e85-11f179c704cb.png)
![screenshot_2018 03 05_17 38 15](https://user-images.githubusercontent.com/27579955/36988962-914f7a72-20a0-11e8-878d-7ab0d030eecf.png)

There is some info about my system configuration in case it can help:

latte-dock version: 0.7.4
KDE version: 5.12.2
KDE framework: 5.43.0
OS: Arch linux x64
Kernel: 4.14.23-1-lts

And an example of .desktop file I'm using:

```
[Desktop Entry]
Name=Messenger
Comment=FB Messenger
Exec=/home/samuel/scripts/some_script_or_exec %u
Terminal=false
Type=Application
Icon=fbmessenger
Categories=Network;Chat;
StartupNotify=true
```

**Comment by psifidotos** [comment]
This is plasma libtaskmanager responsibility and you should be able to reproduce with plasma taskmanagers. So please report it upstream at bugs.kde.org

**Comment by smensak** [comment]
Didn't think about that, but you are right. It can be reproduced in default plasma taskmanagers (I hardly use them, so sorry for blaming this project). Gonna report that upstream as sugested.

**Comment by psifidotos** [comment]
yeah... I am trying to use as much plasma and kde code as possible...
