### ISSUE TITLE
polish() not called on QMenu widgets (Global Menu)

### ISSUE THREAD

**Issue by beojan** [psifidotos/Latte-Dock#904]
It looks like `QStyle::polish()` isn't being called on the `QMenu` widgets created by the global menu plasmoid (or by Latte dock itself in the case of the context menu) when it is used from Latte dock, while it is called if the plasmoid is in a Plasma panel.

I noticed this because I use a patched QtCurve that sets the menu palette to a dark one if it is running in Plasma or Latte dock because I have a light KDE color scheme and a dark Plasma theme.

**Comment by psifidotos** [comment]
Can you show me a screenshot to understand which menus you are describing?

**Comment by psifidotos** [comment]
Ok, that menu is created from the menu plasmoid, isnt that its responsibility?

**Comment by psifidotos** [comment]
For the Latte context menu I can fix it

For the plasma case I dont know why it works, but it should be also applied to that plasmoid internally

**Comment by beojan** [comment]
Let's see if the fix for the context menu also fixes the plasmoid in Latte dock.

**Comment by psifidotos** [comment]
just a sec... I used the kvantum engine with dark themes and I get the following....

![default](https://user-images.githubusercontent.com/2216474/37091356-8176cc88-2210-11e8-9ab7-3594fbf54c22.png)

![default](https://user-images.githubusercontent.com/2216474/37091371-8bf97070-2210-11e8-8cf7-3a5001a1a624.png)

**Comment by psifidotos** [comment]
and in plasma code I cant find any polish() function, where is it triggered?

**Comment by beojan** [comment]
It's supposed to be called by Qt, which is why I'm confused as to why
that's not happening in latte.

**Comment by psifidotos** [comment]
no feedback... closing for the time being...
