### ISSUE TITLE
Pinned icon changes after application closes

### ISSUE THREAD

**Issue by eversins** [psifidotos/Latte-Dock#906]
Hello, I have a *.desktop file which opens Firefox with a new instance and a different WM_CLASS, this is useful if you want to use specific sites as an "app".

The problem is when I close said app (firefox instance), the icon changes back to the default FF one.
As you can see here: https://giant.gfycat.com/PinkGivingHuia.webm

This only happens, if you set a manual icon path, if you use a system icon it works as expected.

*.desktop file:
  Icon changes to FF after closing windows:
```
Icon=/home/ever/Fixes/Hangouts-icon.png
layout.latte enty: applications:hangouts.desktop?iconData=XXX (XXX = long randome characters, maybe base64 icon? decoding did not work..)
```

  Icon works and stays as expected:
```
Icon=wechat (system icon)
layout.latte enty: applications:hangouts.desktop
```

So it seems to be connected to the "?iconData=" entry, what is it and where does it come from?

It also works if I drag the first *.desktop file directly into the dock, but that is not the point. Why is this happening and how can we avoid this?

Thank you.

**Comment by psifidotos** [comment]
This is plasma libtaskmanager issue and you should report it to plasma because you probably can reroduce this with plasma taskmanagers also

**Comment by eversins** [comment]
Yes I can reproduce it, will do. Thank you.
