### ISSUE TITLE
Only dodge windows on same monitor as dock

### ISSUE THREAD

**Issue by DrDoctor13** [psifidotos/Latte-Dock#907]
If I maximize a window on my secondary monitor, it causes the dock to disappear from the primary monitor, even if there are no windows on it. Can there be a way to toggle this behavior?

**Comment by psifidotos** [comment]
Maybe a bug...

Which Latte version?
What Dodge are you using?

**Comment by DrDoctor13** [comment]
0.7.4. I'm using "Dodge Maximized" on a dock that is on the top of my primary monitor.

**Comment by psifidotos** [comment]
@DrDoctor13 nice catch! fixed for both master and v0.7.x branch

**Comment by DrDoctor13** [comment]
I'll test this when I get the chance!

**Comment by DrDoctor13** [comment]
Can confirm, it's fixed. Thank you!

**Comment by psifidotos** [comment]
thank you! ;)
