### ISSUE TITLE
Where to improve translations?

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#909]
There are some mistakes and missing pieces in polish translation. For example I have such sentence (translated literally from Polish one):

_"Watercourse of hidden panel for maximized windows"_

I suspect that there is a misspelling and "watercourse' was meant to be "a shadow" and the whole sentence should be something like that:

_"Hide panel's shadow for maximized windows"._

Can someone confirm if that's the correct understanding? And where do I find po files or any localization files? I would like to fixed some most visible translation issues and send a pull request.

**Comment by psifidotos** [comment]
Latte is translated from kde community... join the kde polish translation team

**Comment by michaldybczak** [comment]
Unfortunately, KDE documentation is less then spotty. I tried once to fix some serious mistranslation and NO ONE could ever tell me where to go to do that and I was asking in many places. Some suggested some KDE translation lists. I joined but they are dead and nothing happens there. Eventually someone fixed that translation. I don't know if it was their own discovery or stumbled upon my many threads on various sites about it?
Anyway, I googled "kde polish translation" and I find out my ask threads instead anything helpful.

The easier way would be to have some organization that coordinates translators that would work on github or just simply allow for easy finding of translation projects on github so I could help whenever I want without additional fuzz.

**Comment by psifidotos** [comment]
this is a request for kde community...
the polish translation team has a webpage here:
https://l10n.kde.org/team-infos.php?teamcode=pl

**Comment by omni6** [comment]
so, here we go.

first this are the locations of latte tranlation files:
https://l10n.kde.org/stats/gui/trunk-kf5/team/pl/extragear-base/
svn://anonsvn.kde.org/home/kde/trunk/l10n-kf5/pl               

you need to clone them locally on your hdd

make yourself a workdir like ~/home/translations/l10n-pl/trunk/l10n-kf5/
(this hierarchy is recommended, it is easier to locate the path for the diff that you generate later)
`mkdir -p ~/translations/l10n-pl/trunk/l10n-kf5/`

go to the end of you workdir .../l10n-kf5/
`cd ~/home/translations/l10n-pl/trunk/l10n-kf5/`

now clone svn here
`svn co svn://anonsvn.kde.org/home/kde/trunk/l10n-kf5/pl`

now you can find the related files for latte-dock here:
`cd ~/translations/l10n-pl/trunk/l10n-kf5/pl/messages/extragear-base/`

recommended tool to edit *.po files is **lokalize**, get it!
after you have edited related *.po files you have to generate a diff, optimal create the diff from .../l10-pl/... directory with:
`svn diff -x -U100 trunk/l10n-kf5/pl/messages/extragear-base/latte-dock.po > ~/latte-dock.diff` 

now you have the file **latte-dock.diff** in you home directory

Create an account at https://phabricator.kde.org/

create review request (star button on top)
Raw Diff From File --> choose your latte-dock.diff
repository --> Subversion

next page --> check your changes
Continue

Fill out the form:

Title: latte-dock update (trunk)
discription: some improvements n changes, blah ...
Reviewers: kde-i18n-doc@kde.org
Repository: Subversion


hope my little howto can help you!

**Comment by michaldybczak** [comment]
Thanks @omni6, will do that. Sounds however complicated so I need more time to do it, but I will eventually get it ;P.
