### ISSUE TITLE
Widgets from desktop no longer can be dropped on a dock

### ISSUE THREAD

**Issue by DoubleIntegral** [psifidotos/Latte-Dock#911]
I'm pretty sure you could drag widgets from desktop to Latte dock in previous versions. This seems to no longer be the case as of 11cccbf . If removal is intentional I propose to add this functionality (it was very useful to quickly transition widgets from plasma panels to latte with all configs intact). 

Can't spot when exactly regression happened except that I had previous version installed I think from several months to half a year ago.

**Comment by DoubleIntegral** [comment]
I am seriously not trying to find bugs. They just come to me on their own.

**Comment by DoubleIntegral** [comment]
Checked if maybe "Hide background for not maximized windows" was the culprit. Still no go.

**Comment by psifidotos** [comment]
This was never possible... plasmashell is a different process from latte and so they cant share objects...
