### ISSUE TITLE
Impossible to make the tasbar transparent

### ISSUE THREAD

**Issue by blop135** [psifidotos/Latte-Dock#914]
Hi,

Here's the following from Reddit. So even when I go to Dock/Pannel settings -> Appearance -> Uncheck background. The only thing that became transparent is the dock but not the taskbar on the top of the screen.

https://i.imgur.com/S6XYz5e.png

Thank you ;)

**Comment by psifidotos** [comment]
Can you send me your layout file to check it  in my system?

Go to Layouts Editor from Appearance page and use the export button to extract it.

**Comment by blop135** [comment]
Yeah sure here it is


[Layout.layout.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1794214/Layout.layout.latte.zip)

**Comment by psifidotos** [comment]
:)

your top panel is not a Latte Panel but a plasma panel... :)

you need to replace your plasma panel with a Latte one

**Comment by blop135** [comment]
Ohhhh okay ^^

But when I go to add a new panel, I don't have the latte's panel option :/

**Comment by psifidotos** [comment]
You dont add it that way... :) what Latte version are you using?

**Comment by blop135** [comment]
It's the 0.7.3

**Comment by psifidotos** [comment]
1. Remove your top plasma panel
2. open the Latte Settings from your bottom dock
3. At the bottom-left there is an Add button
4. Add a second dock
5. Move it at the top
6. A panel is just a dock with different settings:
a. Tweaks->Disable automatic shrinking of applets
b. Tweaks->Remove the Tasks plasmoid
c. Behavior->select Justify mode
d. Behavior->Always Visible
e. Appearance-> Background Size:100%
f. Appearance-> Backgound Opacity: 0%

**Comment by blop135** [comment]
OK this is going way better :) .

I saw on your screenshots that you managed to make the applications you're using into you latte taskbar but it doesn't on mine when a windows is active. And when I press the kde button to have the menus it kind of act weird not like the regular one:

https://i.imgur.com/mbcAp5L.png

https://i.imgur.com/11a2LMn.png

Thanks a lot :D

**Comment by blop135** [comment]
Nevermind I found it it's perfect !!!!!

**Comment by psifidotos** [comment]
;)
