### ISSUE TITLE
Unable to set launcher in latte to meta key

### ISSUE THREAD

**Issue by DoubleIntegral** [psifidotos/Latte-Dock#915]
This has been finicky in default Plasma but now it feels even more finicky. 

I set my launcher shortcut to "Alt + F1" (combination tied to meta key). In normal panels it _tends_ to work if not right away then after relogging into plasma. Setting launcher in latte to Alt + F1 half of the time doesn't write it in config (after clicking "OK" and opening application launcher settings you see shortcut field empty) or flat out doesn't work (shortcut is there but it just doesn't react to meta key).

I'm not sure how much fault there is on latte since plasma itself doesn't really work too well with it.
Launcher in matte dock also doesn't register as "openable" when setting corner of your screen as a hot spot to open app launcher (In desktop behavior tab of system settings).

**Comment by psifidotos** [comment]
Are you refering to this? You dont need to set Alt+F1 at all... Latte has fixed that in its codepage... but you need the following in order to inform kwin that Latte is using the Meta key...

https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-can-i-use-my-super-key-to-open-the-app-launcher

both A1 and A2 work.... whatever suits you best...

**Comment by DoubleIntegral** [comment]
Yes, got it. Launcher reacting to Alt + F1 but not meta key itself threw me off

**Comment by DoubleIntegral** [comment]
Hotspot still doesn't react to launcher though

**Comment by psifidotos** [comment]
> Hotspot still doesn't react to launcher though

why it should? is this a plasma feature I dont know of?

**Comment by DoubleIntegral** [comment]
@psifidotos System settings > Desktop behavior (under Workspace section) > Screen Edges
Select one of the edges and choose "Application Launcher" from a dropdown menu. Now whenever mouse "pushes" against that edge it will activate launcher. Pretty handy for lazy people like me

**Comment by psifidotos** [comment]
That should open the Application Launcher like the Meta key or the FullScreen one?

**Comment by DoubleIntegral** [comment]
Like meta key.

**Comment by DoubleIntegral** [comment]
@psifidotos it also doesn't work at all unless you remove the lines setting meta key to launcher in latte.

**Comment by psifidotos** [comment]
> @psifidotos it also doesn't work at all unless you remove the lines setting meta key to launcher in latte.

you mean in order to work at least for plasma the Latte lines must be removed?

**Comment by DoubleIntegral** [comment]
> you mean in order to work at least for plasma the Latte lines must be removed?
Yep.

**Comment by DoubleIntegral** [comment]
also doesn't work if no launcher is present on desktop (launcher in latte doesn't count).

**Comment by psifidotos** [comment]
#916

**Comment by DoubleIntegral** [comment]
I guess I kind of worked out how to keep hotspot and launcher with latte. I just have keep fullscreen app launcher somewhere on desktop in addition to one in latte. Not the best thing in the world but oh well.
