### ISSUE TITLE
Application Launcher isnt activated from KWin Screen Edge

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#916]

**Comment by psifidotos** [comment]
reported to take some feedback from kwin developers:

https://bugs.kde.org/show_bug.cgi?id=391575

**Comment by psifidotos** [comment]
I sent a patch for kwin but it wasnt accepted but on the other hand they proposed that a kwin script can support this... 

I searched it and yep it can be even though the screen edge is hard-coded in the code and the user should alter this by its own. By default the TopLeft screen edge will be used.

**Comment by DoubleIntegral** [comment]
Huh, I didn't think about that. Yes, I'm pretty sure kwin script will work out for it.
