### ISSUE TITLE
How to install correctly Latte-Dock in Debian Buster (Testing)?

### ISSUE THREAD

**Issue by ericvipo** [psifidotos/Latte-Dock#917]
OS: Debian testing (buster) x86_64
KDE Plasma: 5.12.2
KDE Frameworks: 5.42.0
Qt: 5.9.2
Kernel: 4.14.0-3-amd64

**Comment by psifidotos** [comment]
no idea...

**Comment by psifidotos** [comment]
you should ask at: #203 in cases someone can help on that...

**Comment by ericvipo** [comment]
I just now installed with the method .deb, and works fine but I have the version 0.6.0 ...
how to update the latte-dock version?
thanks

**Comment by psifidotos** [comment]
I suppose you will need to find another deb file...

take note that v0.6.x works only for Plasma 5.8 and v0.7.x needs at least Plasma 5.9

**Comment by ericvipo** [comment]
well I clone the repo then put permissions to the folder with chmod -R 755 "Latte-Dock"
`sudo apt install cmake extra-cmake-modules qtdeclarative5-dev libqt5x11extras5-dev libkf5iconthemes-dev libkf5plasma-dev libkf5windowsystem-dev libkf5declarative-dev libkf5xmlgui-dev libkf5activities-dev build-essential libkf5wayland-dev git gettext libkf5archive-dev libkf5notifications-dev libxcb-util0-dev libsm-dev libkf5crash-dev libkf5newstuff-dev`
`sudo ./install.sh`
thats works, thanks for yours answers, greetings :)

**Comment by Leol33t3** [comment]
@ericvipo Thank, It really work !!
