### ISSUE TITLE
Is it possible to display the media controls when hovering the Latte plasmoid ?

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#919]
Like this picture with the Plasma Task Manager:

![image](https://user-images.githubusercontent.com/11857205/37206619-f4595588-23cb-11e8-8dd6-c983eb86f148.png)

**Comment by psifidotos** [comment]
Tasks-> Enable previews

**Comment by trmdi** [comment]
I checked `Task/Interaction/Preview window on hovering` but it just shows this:

![image](https://user-images.githubusercontent.com/11857205/37209810-1c1205fe-23d9-11e8-8f88-3cfcbe9b1313.png)

No media control buttons ?

**Comment by psifidotos** [comment]
Try vlc or other media player.... Does it work?

**Comment by trmdi** [comment]
Same result.
