### ISSUE TITLE
Support Fill with three different locations for applets... 

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#92]
It would be interesting supporting a Fill mode with three different locations to place the applets,
(Start | Center | End). Current implementation supports only two (Start | End)

**Comment by psifidotos** [comment]
this is my current workspace, Latte with two Docks, one at Bottom(below active) and one at Top(Always visible). I would like a lot the date which is at the top-right to show at the top-center and put some other small applet at the top-right position

![0591](https://cloud.githubusercontent.com/assets/2216474/22341788/cf6aa2de-e3fa-11e6-93ba-30db96a6db19.jpeg)

**Comment by audoban** [comment]
I don't know, I think that this feature can be implemented with flexible spacers, maybe we can add a button for create spacers easily.

**Comment by psifidotos** [comment]
Unfortunately the situation is the following... layouts wasnt an option for containment because there were glitches in the zoom animation. So two separate grids are used for Fill mode, one for start and one for the end of the dock.

The default spacer is already supported but it just takes up the empty space of an icon in size, it can be hovered as all the other applets

**Comment by psifidotos** [comment]
@audoban also to add in the discussion...

We could of course enable the user instead of adding a Latte Dock from configuration window to be able to add a Plasma one, hehe, I dont think it will be unified with Latte experience but from architecture point of view is feasible!!! :)

so Latte is going to act as a universal panel manager, in its own process out of Plasma!!! :)

today plasmashell crashed and because of Latte I still had access to my windows!!!! :)
great possibilities open up with Latte !!!

**Comment by kupiqu** [comment]
In addition to the alignment, would it be possible to set an absolute size for the length of the latte dock panel as an option, so the size is autofitted or manually set according to user preference?

Let me explain why I'm asking:

Please see my configuration in the screenshot

<img width="1280" alt="screenshot_20170127_115235" src="https://cloud.githubusercontent.com/assets/3875196/22379402/39a47b3e-e487-11e6-9311-3b5d21fbc4c6.png">

- vertical latte dock: app menu, tasks and some applets
- horizontal latte dock: active window control applet (global menu once plasma 5.9 is released),.., systray, etc.

the problem I'm facing is that the "active window control" applet does not behave properly on latte dock (and didn't try but this could be the same for the global menu once released). the length of this applet can be set to autofill or to a specific length. Autofill fails because latte dock does autofit as well, so no room is left. If instead an absolute size is chosen, then the length of the latte dock panel increases or decreases, e.g., according to the size of the systray, which is sort of annoying.

By the way, I very much agree with:

"so Latte is going to act as a universal panel manager, in its own process out of Plasma!!! :)

today plasmashell crashed and because of Latte I still had access to my windows!!!! :)
great possibilities open up with Latte !!!"

Great work, I owe you a Latte! ;)

**Comment by kupiqu** [comment]
Not sure this fits here, perhaps I should have opened a different issue for this :/

**Comment by psifidotos** [comment]
@kupiqu , yes

and one more thing when you open the ticket I can not understand how these two are relevant:

1. In addition to the alignment, would it be possible to set an absolute size for the length of the latte dock panel as an option, so the size is autofitted or manually set according to user preference?
**(are you referring to maximumLength set by the user?)**
2. the problem I'm facing is that the "active window control" applet does not behave properly on latte dock (and didn't try but this could be the same for the global menu once released). the length of this applet can be set to autofill or to a specific length.

> e.g., according to the size of the systray, which is sort of annoying.

you can lock the systray in order to not be zoomed at all at any case through the editing mode of Latte (that is when the blueprint appears)

**Comment by kupiqu** [comment]
Did it

https://github.com/psifidotos/Latte-Dock/issues/99

Note that I was not referring to the zoom of the systray before (actually I don't use the zoom in the panel), instead I was referring to the dynamic number of icons that appear in the systray, becuase some of them appear depending on context (e.g. kde connect, redshift applet, multimedia player, printer applet, etc)

**Comment by audoban** [comment]
> We could of course enable the user instead of adding a Latte Dock from configuration window to be able to add a Plasma one, hehe, I dont think it will be unified with Latte experience but from architecture point of view is feasible!!! :)

it's ok :)

> Unfortunately the situation is the following... layouts wasnt an option for containment because there were glitches in the zoom animation. So two separate grids are used for Fill mode, one for start and one for the end of the dock.

If we block the zoom effect for spacer.

**Comment by psifidotos** [comment]
> If we block the zoom effect for spacer.

no, what I mean is that the zoom animation wasnt smooth enough for the applets because of the gridlayout instead of grid, too many computations

**Comment by psifidotos** [comment]
by just supporting plasma panels of course this is fixed... some adjustments are needed, for example the iconsize should go to the dockview in order to set dockview size correctly and zoom factor should be disabled in such case...

**Comment by audoban** [comment]
> no, what I mean is that the zoom animation wasnt smooth enough for the applets because of the gridlayout instead of grid, too many computations

Well, I understand

**Comment by audoban** [comment]
The Maximum length doesn't work properly.

I have the following issues:

1.  latte-plasmoid it leaves the background when Alignment is set to Fill and the spacer is on end of dock.
2. The background of edit doesn't align with the dock if the Alignment is set to Left or Right or even Center.

**Comment by psifidotos** [comment]
these are easily fixed...

**Comment by psifidotos** [comment]
> latte-plasmoid it leaves the background when Alignment is set to Fill and the spacer is on end of dock.

you mean in case there arent any applets in the end so this acts like a left alignment ?

> The background of edit doesn't align with the dock if the Alignment is set to Left or Right or even Center.

left, right makes sense!! For center it was working for me...

**Comment by psifidotos** [comment]
ok... these are fixed in master

**Comment by audoban** [comment]
> The background of edit doesn't align with the dock if the Alignment is set to Left or Right or even Center.

Sometimes works fine, but when you change the location, the background doesn't align.

1. set location to Right
2. close ui config
3. open ui config again

![screenshot_20170129_033604](https://cloud.githubusercontent.com/assets/7884292/22402872/2a31159c-e5d4-11e6-9016-f6f75a2b096a.png)


> you mean in case there arent any applets in the end so this acts like a left alignment ?

nop, move the spacer to end.

![screenshot_20170129_033315](https://cloud.githubusercontent.com/assets/7884292/22402862/b35bce58-e5d3-11e6-89bb-abe65525e392.png)

![screenshot_20170129_033135](https://cloud.githubusercontent.com/assets/7884292/22402858/7700bcf2-e5d3-11e6-87d0-a04242230cc3.png)

**Comment by audoban** [comment]
ok, fixed on latest commit.

But the background must never be greater than iconSize + units.smallSpacing when the plasmoid is shrinks.

**Comment by psifidotos** [comment]
sorry, when do you mean?
thickness behavior hasnt been touched, is that an old issue? 

do you have a screenshot to understand?

**Comment by psifidotos** [comment]
@audoban I think this is fixed now...

**Comment by audoban** [comment]
> thickness behavior hasnt been touched, is that an old issue?

when the dock is shirnks, the background does not change its thickness.
I suggest use percent instead of pixels for background.

![screenshot_20170129_130730](https://cloud.githubusercontent.com/assets/7884292/22406614/ecd786d6-e623-11e6-9e0f-9f03b6036136.png)

the background has large thickness.

**Comment by psifidotos** [comment]
ok... various fixes for metrics in master including this...
