### ISSUE TITLE
Closing vim window opened from the dock leaves the konsole process opened

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#920]
Ok, so this bugged me for DAYS.

Here is the gist of it. I get this weird konsole processes that eat 12-13% of the CPU.

After some digging I can say this:
- I have no actual konsole opened myself
- krunner has it's run commands option stopped
- this konsole processes are made by kinit5: https://i.imgur.com/TtuiSRI.png
- I noticed that using alt+F4 to close a vim window causes this. It is not a problem if I open vim from krunner or the application launcher. But it happens if I open it from the dock.
- here is also the systemctl status:
This is an older one I have no idea why is here. I was working in my documents. I can't even confirm it was related to latte.
```
│   │ ├─ 1717 kdeinit5: Running...                                  
   │   │ ├─ 1721 kded5 [kdeinit5]                                      
   │   │ ├─ 5338 konsole [kdeinit5] --workdir /home/raitaro/Documents  
   │   │ ├─21119 file.so [kdeinit5] file local:/run/user/1000/klaunchermAuohD.1.slave-socket local:/run/user/1000/kdeconnectdChDogd.2.slave-socke
   │   │ ├─21516 trash.so [kdeinit5] trash local:/run/user/1000/klaunchermAuohD.1.slave-socket local:/run/user/1000/dolphinBDgHRK.2.slave-socke
   │   │ ├─21518 file.so [kdeinit5] file local:/run/user/1000/klaunchermAuohD.1.slave-socket local:/run/user/1000/dolphinajETez.3.slave-socke
   │   │ ├─22294 file.so [kdeinit5] file local:/run/user/1000/klaunchermAuohD.1.slave-socket local:/run/user/1000/plasmashellsHyuII.6.slave-socke
   │   │ ├─22504 grep --color=auto kdeinit5
   │   │ └─25692 konsole [kdeinit5] --workdir /home/raitaro/Documents  
```
This one I just pulled from opening and closing vim a bunch of times from latte with meta+nr.
```
systemctl status | grep kdeinit5
           │   │ ├─16374 kdeinit5: Running...                                  
           │   │ ├─16378 kded5 [kdeinit5]                                      
           │   │ ├─23162 konsole [kdeinit5] -qwindowtitle Vim --icon gvim -e /usr/bin/vi
           │   │ └─23297 grep --color=auto kdeinit5
```
- this is the konsole info from ksysguard
```
Process 22006 - konsole

Summary

The process konsole (with pid 22006) is using approximately 15.4 MB of memory.
It is using 9.6 MB privately, and a further 50.8 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 5.7 MB. Adding that to the private usage, we get the above mentioned total memory footprint of 15.4 MB.
Library Usage

The memory usage of a process is found by adding up the memory usage of each of its libraries, plus the process's own heap, stack and any other mappings, plus the stack of its one other thread. 
Private
more
6628 KB	[heap]
292 KB	/usr/lib/x86_64-linux-gnu/libkdeinit5_konsole.so
216 KB	/usr/lib/nvidia-390/libGL.so.390.30
168 KB	/usr/lib/x86_64-linux-gnu/libQt5Quick.so.5.10.0
132 KB	/usr/lib/x86_64-linux-gnu/libQt5QuickTemplates2.so.5.10.0
Shared
more
4100 KB	/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.10.0
3920 KB	/usr/lib/nvidia-390/libnvidia-glcore.so.390.30
3464 KB	/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.10.0
3404 KB	/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.10.0
1524 KB	/usr/lib/x86_64-linux-gnu/libQt5Quick.so.5.10.0
Totals

Private	9864 KB	(= 1084 KB clean + 8780 KB dirty)
Shared	52032 KB	(= 47088 KB clean + 4944 KB dirty)
Rss	61896 KB	(= Private + Shared)
Pss	15729 KB	(= Private + Shared/Number of Processes)
Swap	0 KB
Full Details

Information about the complete virtual space for the process is available, with sortable columns. An empty filename means that it is an anonymous mapping.
Both the MMU page size and the kernel page size are 4 KB.

Show Full Details 
```

**Comment by RaitaroH** [comment]
Might be a konsole issue though, but I only managed to make it appear when I open konsole from the latte dock...

**Comment by psifidotos** [comment]
when you open it from a plasma taskmanager dont you have that issue?

**Comment by RaitaroH** [comment]
`when you open it from a plasma taskmanager` I thought the taskmanager is just listing opened applications.

I open vim then I close the window with alt+F4. I noticed that krunner and the application menu do not have this issue.

**Comment by RaitaroH** [comment]
Also... experimenting with this has vim creating a ton of swap files in my home dir, is actually really annoying.

I would also like to mention it does not happen every time. Usually I am just working in a terminal, vim or not and then I'm done but a few minutes later I notice my fans getting noisy and I know a konsole wasn't properly closed.

**Comment by psifidotos** [comment]
> I thought the taskmanager is just listing opened applications

No, it can have launchers. Plasma and Latte use the same codebase . So it happens also  with plasma taskmanager?

**Comment by RaitaroH** [comment]
I tried for quite a bit. It seems that even in latte it happens if I open the vim application and not konsole first... or maybe I just have to try a lot more.

I think this bug information might help.
[kdeinit5-20180311-081158.kcrash.txt](https://github.com/psifidotos/Latte-Dock/files/1800099/kdeinit5-20180311-081158.kcrash.txt)

**Comment by RaitaroH** [comment]
This is the bug report for this issue:
https://bugs.kde.org/show_bug.cgi?id=391616

**Comment by psifidotos** [comment]
>  kdeinit5-20180311-081158.kcrash.txt

this is a crash in nvidia proprietary graphics driver

concerning the Latte responsibility I dont find any for two reasons... The execution of the apps is done through plasma libtaskmanager, so the same issue should happen also with all plasma taskmanagers. And the second thing is that the closing of applications isnt done from Latte....

So this is upstream, I would start by reproducing the issue with plasma taskmanagers and report there and afterwards at konsole...

**Comment by RaitaroH** [comment]
An nvidia proprietary graphics crash huh, thank you for the help. It was REALLY bugging me. I think I will try to move to nouveau drivers.

**Comment by RaitaroH** [comment]
@psifidotos I even get this if I open a file in vim using open with, so yeah, totally upstream.
