### ISSUE TITLE
UI issue with "Remove tasks" and latte task manager plasmoid

### ISSUE THREAD

**Issue by DoubleIntegral** [psifidotos/Latte-Dock#921]
I've hit this issue while trying to make a panel and it's a bit of a pain. Currently, to have no task manager in panel you have to select "Extended" layout and work from there, since there is apparently no way to remove default "Latte plasmoid". 
How it should behave: 
Popup in edit mode should have "Lock" and "Remove" buttons just like any other plasmoid. Adding latte plasmoid can be possible by making a button in edit mode (just like adding spacer)

**Comment by DoubleIntegral** [comment]
Ok, button "Remove tasks" does remove task manager, but I think it's a bit of a UI blunder. It is not clear what exactly "Remove tasks" mean since initial assumption is that some processes related to Latte Dock will be terminated.

**Comment by DoubleIntegral** [comment]
I also have a bit of an issue with "Quit" button in edit mode. Initial assumption is that "Quit" will exit edit mode, not close program entirely. Renaming it to "Close Latte Dock" should probably do the trick.

**Comment by psifidotos** [comment]
Too much text... Quit is the best single word and a tooltip exists also...

Except if you have a better single word for that...

**Comment by DoubleIntegral** [comment]
@psifidotos If you're concerned about symmetry then "Close Latte" would fit nicely with "New Dock" on the other side.

**Comment by psifidotos** [comment]
@DoubleIntegral why not "Quit Latte" ?

**Comment by DoubleIntegral** [comment]
@psifidotos Hmmm... I think it's mostly personal but for me "Close" always felt more like termination of a program (You "Close" the window and it terminates process) when "Quit" felt like change of state in a program (You "Quit" edit mode in Latte to return it to default state). 
Of course you don't have to agree with me on this one, plenty of programs use "quit" in their menus for termination.

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/commit/6ef11d6bf8cf9b9c3b57d945acb730812950a1db

ok.. I improved the Remove Tasks text but for Quit I tried and I didnt like the result.. I will keep the current implementation
