### ISSUE TITLE
Icon changes when hovering next to it

### ISSUE THREAD

**Issue by RaitaroH** [psifidotos/Latte-Dock#924]
![example](https://user-images.githubusercontent.com/19552720/37473102-3fe6066e-2876-11e8-98b4-7ca2e3eb46c2.png)

This happened after the recent kde neon updates. I also tried to recompile latte just to be safe. Still a problem.

The audacious icon has been changed from the menu editor. Also here is the file in `.local/share/applications`:

```
[Desktop Entry]
Categories=AudioVideo;Audio;Player;Qt;
Comment=Listen to music
Exec=audacious --qt %U
GenericName=Music Player
Icon=audacious
Keywords=audio;player;audacious;music;qt;
MimeType=application/ogg;application/x-cue;application/x-ogg;application/xspf+xml;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpegurl;audio/ogg;audio/prs.sid;audio/x-flac;audio/x-it;audio/x-mod;audio/x-mp3;audio/x-mpeg;audio/x-mpegurl;audio/x-ms-asx;audio/x-ms-wma;audio/x-musepack;audio/x-s3m;audio/x-scpls;audio/x-stm;audio/x-vorbis+ogg;audio/x-wav;audio/x-xm;inode/directory;x-content/audio-cdda;
Name=Audacious Qt Interface
NoDisplay=false
Path[$e]=
StartupNotify=true
Terminal=0
TerminalOptions=
TryExec=audacious
Type=Application
Version=1.0
X-KDE-SubstituteUID=false
X-KDE-Username=

```

**Comment by RaitaroH** [comment]
I don't know... it may just be a weird .desktop file issue or a menu editor issue.

**Comment by RaitaroH** [comment]
And just to be clear. I tried:
* updating latte
* restarting plasma and latte
* changing the icon in the menu editor
* changing the icon in .local/share/applications
* droping audacious on the dock again

**Comment by psifidotos** [comment]
this is probably an audacious issue...
you updated audacious and the icon looks a lot different in different icon sizes... 

If you increase the applet icon size from Latte Appearance page probably this issue will be fixed...

**Comment by psifidotos** [comment]
false alarm...

your desktop file is missing a record: `StartupWMClass`
