### ISSUE TITLE
General flickering

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#925]
I deleted my layouts and started from scratch.
Starting from the Latte's **default layout** I created a new layout
with these settings I get a slight general flickering a bit everywhere
![screenshot_20180315_235710](https://user-images.githubusercontent.com/24593950/37506945-98760c18-28ec-11e8-8701-ef6db281b16c.png)
![screenshot_20180315_235742](https://user-images.githubusercontent.com/24593950/37506946-989a7076-28ec-11e8-96cc-b297c45ad374.png)
![screenshot_20180315_235837](https://user-images.githubusercontent.com/24593950/37506947-98be6d32-28ec-11e8-8d84-e9bdd1d86c80.png)
![screenshot_20180315_235930](https://user-images.githubusercontent.com/24593950/37506948-98e33004-28ec-11e8-9094-b9438fc5714d.png)
![screenshot_20180315_235955](https://user-images.githubusercontent.com/24593950/37506949-990c2aa4-28ec-11e8-9778-bad263d82ad3.png)
![screenshot_20180316_000020](https://user-images.githubusercontent.com/24593950/37506951-99704796-28ec-11e8-885b-08e8761d6492.png)
![screenshot_20180316_000047](https://user-images.githubusercontent.com/24593950/37506953-99aba46c-28ec-11e8-9cdd-6a32f8dcad50.png)
I would like to retrace all the steps to understand what is the setting that has created the problem, but I deleted the **default layout** by mistake could you please enter it in the repository download?

**Comment by psifidotos** [comment]
> with these settings I get a slight general flickering a bit everywhere

probably the 56px applet size... but the flickering should be only happening for the plasma applets at startup and only once...

> but I deleted the default layout by mistake could you please enter it in the repository download

Latte offers plenty command line options in master version, you can use
`latte-dock -h`
to track them and:

`latte-dock --default-layout`
is what you need.

**Comment by JenaPlinsky** [comment]
I can no longer replicate the issue so how about if we close it ?
