### ISSUE TITLE
Heuristic animation a little snappy

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#927]
![image](https://user-images.githubusercontent.com/24593950/37568373-9462e17a-2ad4-11e8-80f0-54f94a7b2bcf.png)
With this option, enabled, and when I fast hovering on applets, the heuristic animation is not as smooth as without
maybe it's just my impression

**Comment by psifidotos** [comment]
you should show me in a video what you are trying to describe...
