### ISSUE TITLE
Click on the opening Application Menu not hide it

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#928]
I have an Application Menu on the Latte panel, if I click the icon to open the menu then click it again to close it, it's still there.

Expected behavior: the menu should disappear, like it does on the Plasma default panel.

I'm using the latest version from git: https://github.com/psifidotos/Latte-Dock/commit/04bae04d56f90cd85198270dd38c19b6a208917a

**Comment by psifidotos** [comment]
1. screenshot to understand
2. does this occur with all application launchers in your system?
3. does this occur independent from where you click, or at specific areas it works and for some it doesnt?

**Comment by trmdi** [comment]
Here is the screenshot: https://i.imgur.com/W4ub3gx.mp4
It just happens with the Application Menu widget.
