### ISSUE TITLE
Context menu not shown on right click

### ISSUE THREAD

**Issue by slothds** [psifidotos/Latte-Dock#929]
```
Kubuntu 17.10
KDE Plasma: 5.12.3
KDE Framework: 5.43.0
QT: 5.9.1
Kernel: 4.13.0
Latte: 0.7.78 (0.7.78+git20180318.1832-0~ubuntu17.10~ppa1 from rikmills ppa)
```
bug is present on both my pc and laptop.

Context menu does not shown on right click on dock panel, applets or application icons. debug mode not show any errors.
Right click on thumbinal of runned application showed context menu (screenshots) and debug errors (below).
![spectacle j15446](https://user-images.githubusercontent.com/33009348/37702961-3c785b06-2d05-11e8-90d7-1be7dd90a8f5.png) ![spectacle y15446](https://user-images.githubusercontent.com/33009348/37702971-41bf44f8-2d05-11e8-8e15-ebd165f5f7d0.png)

```
$ latte-dock -d                                       
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
[warning 12:23:49.620620] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 12:23:49.669669] - Failed to register unity service
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:195:30: Unable to assign [undefined] to int
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:50: ReferenceError: Activities is not defined
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:49: ReferenceError: VirtualDesktop is not defined
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:48: ReferenceError: index is not defined
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:47: ReferenceError: AppPid is not defined
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:45: ReferenceError: IsMinimized is not defined
[warning 12:23:49.729729] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:44: ReferenceError: IsActive is not defined
[warning 12:24:05.857857] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml:854:17: Unable to assign [undefined] to QAction*
[warning 12:24:05.858858] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml:846:17: Unable to assign [undefined] to QAction*
[warning 12:24:05.858858] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml:829:17: Unable to assign [undefined] to QAction*
QObject::startTimer: Timers cannot have negative intervals
[warning 12:30:40.723723] - QXcbConnection: XCB error: 2 (BadValue), sequence: 7856, resource id: 29360144, major code: 142 (Unknown), minor code: 3
[warning 12:30:42.1414] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml:854:17: Unable to assign [undefined] to QAction*
[warning 12:30:42.1414] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml:846:17: Unable to assign [undefined] to QAction*
[warning 12:30:42.1414] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml:829:17: Unable to assign [undefined] to QAction*
```

**Comment by psifidotos** [comment]
something is probably wrong with your installation...

@rikmills do you have any idea?

**Comment by Iumih** [comment]
Context menus don't appear to me too. I have version 0.7.78
Debug:
`latte-dock -d --replace
[warning 3:35:01.798798] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:195:30: Unable to assign [undefined] to int
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:50: ReferenceError: Activities is not defined
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:49: ReferenceError: VirtualDesktop is not defined
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:48: ReferenceError: index is not defined
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:47: ReferenceError: AppPid is not defined
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:45: ReferenceError: IsMinimized is not defined
[warning 3:35:02.7171] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ToolTipInstance.qml:44: ReferenceError: IsActive is not defined
[warning 3:35:02.487487] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 3:35:02.623623] - Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
[warning 3:35:02.680680] - Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property 'width' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.786786] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:02.827827] - Both point size and pixel size set. Using pixel size.
[warning 3:35:02.833833] - trying to show an empty dialog
[warning 3:35:02.838838] - Both point size and pixel size set. Using pixel size.
[warning 3:35:02.838838] - Both point size and pixel size set. Using pixel size.
[warning 3:35:02.839839] - Both point size and pixel size set. Using pixel size.
[warning 3:35:02.839839] - Both point size and pixel size set. Using pixel size.
[warning 3:35:02.839839] - Both point size and pixel size set. Using pixel size.
[warning 3:35:02.963963] - trying to show an empty dialog
[warning 3:35:03.560560] - Warning: all files used by qml by the plasmoid should be in ui/. The file in the path "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/code/uiproperties.js" was expected at QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/uiproperties.js")
[warning 3:35:03.691691] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property 'width' of null
[warning 3:35:03.691691] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:365: TypeError: Cannot read property 'padding' of null
[warning 3:35:03.691691] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:364: TypeError: Cannot read property 'padding' of null
[warning 3:35:03.691691] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:363: TypeError: Cannot read property 'padding' of null
[warning 3:35:03.691691] - file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ScrollView.qml:362: TypeError: Cannot read property 'padding' of null
[warning 3:35:03.876876] - file:///home/iumih/.local/share/plasma/plasmoids/XrendrMixer/contents/ui/main.qml:58:4: QML GridLayout: Cannot anchor to an item that isn't a parent or sibling.
[warning 3:35:04.388388] - void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "AllDevices"
[warning 3:35:04.388388] - void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "Capabilities"
[warning 3:35:04.388388] - void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "ConnectivityCheckAvailable"
[warning 3:35:04.388388] - void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "ConnectivityCheckEnabled"
[warning 3:35:04.388388] - void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "Devices"
[warning 3:35:04.388388] - void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "GlobalDnsConfiguration"
[warning 3:35:04.395395] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
[warning 3:35:04.396396] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
[warning 3:35:04.397397] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
[warning 3:35:04.397397] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
[warning 3:35:04.400400] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
[warning 3:35:04.400400] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
[warning 3:35:04.402402] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
[warning 3:35:04.402402] - virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
`

**Comment by slothds** [comment]
@psifidotos if i fully remove 0.7.78 and install latte 0.7.3 from backports bug not presist.

**Comment by psifidotos** [comment]
if you run at your command line:

`qdbus org.kde.lattedock /Latte contextMenuData`

what is its output?

**Comment by slothds** [comment]
```
 slothds(bash ✓): ~ $ qdbus org.kde.lattedock /Latte contextMenuData
0
Sloth
1,Sloth
```

**Comment by psifidotos** [comment]
@slothds go to folder `~/.config/latte` in there you will find the `Sloth` layout file. please send it to me...

**Comment by psifidotos** [comment]
@slothds one more thing, this happens only with Latte plasmoid or also when you right click applets in Latte dock ?

**Comment by slothds** [comment]
@psifidotos i'm say about this in 1st message: this happens on both plasmoid and applets.
my layout config file below, but i'v tryed with fresh install (fully removed package, cache and configs) without any success...
```
[ slothds ~ ] $ cat .config/latte/Sloth.layout.latte 
[Containments][12]
activityId=
dockWindowBehavior=true
formfactor=3
immutability=1
lastScreen=-1
layoutId=
location=6
onPrimary=true
plugin=org.kde.latte.containment
raiseOnActivityChange=false
raiseOnDesktopChange=false
timerHide=700
timerShow=200
visibility=0
wallpaperplugin=org.kde.image

[Containments][12][Applets][40]
immutability=1
plugin=org.kde.latte.spacer

[Containments][12][Applets][40][Configuration][ConfigDialog]
DialogHeight=480
DialogWidth=640

[Containments][12][Applets][40][Configuration][General]
lengthPixels=5
usePercentage=false
usePixels=true

[Containments][12][Applets][41]
immutability=1
plugin=org.kde.latte.spacer

[Containments][12][Applets][41][Configuration][ConfigDialog]
DialogHeight=480                                                                                                                                                                                               
DialogWidth=640                                                                                                                                                                                                
                                                                                                                                                                                                               
[Containments][12][Applets][41][Configuration][General]                                                                                                                                                        
lengthPixels=5                                                                                                                                                                                                 
usePercentage=false                                                                                                                                                                                            
usePixels=true                                                                                                                                                                                                 
                                                                                                                                                                                                               
[Containments][12][Applets][42]                                                                                                                                                                                
immutability=1                                                                                                                                                                                                 
plugin=org.kde.latte.plasmoid                                                                                                                                                                                  

[Containments][12][Applets][42][Configuration][General]
isInLatteDock=true
launchers59=applications:Telegram.desktop,applications:whatsappdesktop.desktop,applications:skypeforlinux.desktop,applications:firefox.desktop,applications:google-chrome.desktop,applications:org.kde.dolphin.desktop

[Containments][12][Applets][45]
immutability=1
plugin=org.kde.plasma.volume

[Containments][12][Applets][45][Configuration][ConfigDialog]
DialogHeight=480
DialogWidth=640

[Containments][12][ConfigDialog]
DialogHeight=533
DialogWidth=450

[Containments][12][General]
advanced=true
appletOrder=41;45;42;40
dotsOnActive=true
iconMargin=5
iconSize=40
lockedZoomApplets=41;40
maxLength=96
middleClickAction=None
modifierClick=MiddleClick
modifierClickAction=NewInstance
offset=2
panelPosition=Bottom
panelTransparency=80
shadowOpacity=60
shadowSize=45
showGlow=false
showOnlyCurrentDesktop=true
showOnlyCurrentScreen=true
showToolTips=true
showWindowActions=true
shrinkThickMargins=false
threeColorsWindows=true
titleTooltips=true
zoomLevel=4

[LayoutSettings]
activities=8b9a8e23-ad56-4613-b1e8-83e8d76a8728
background=
color=blue
lastUsedActivity=8b9a8e23-ad56-4613-b1e8-83e8d76a8728
launchers=applications:Telegram.desktop,applications:whatsappdesktop.desktop,applications:skypeforlinux.desktop,applications:firefox.desktop,applications:google-chrome.desktop,applications:org.kde.dolphin.desktop
showInMenu=true
textColor=fcfcfc
version=2
```

**Comment by psifidotos** [comment]
in such case the package seems broken or the package doesnt install correctly the containmentactions...

You have to contact @rikmills for this....

**Comment by psifidotos** [comment]
As a temp solution you can use shortcut Meta+A  in order to show dock settings

**Comment by rikmills** [comment]
Works for me, but I am using frameworks 5.44 from ppa:kubuntu-ppa/backports-landing which my PPA packages **would have built against**.

**Comment by slothds** [comment]
@psifidotos @rikmills yes, update to 5.44 fixes this error
