### ISSUE TITLE
[enhancement] add spacing between application in latte plasmoid

### ISSUE THREAD

**Issue by pupyc** [psifidotos/Latte-Dock#930]
Hi psifidotos

I'm using latte-plasmoid with plasma-panel (not standalone latte dock), the icons are too close to each other (I'm using 22px), here is a screenshot of what it looks like:

![nospace](https://user-images.githubusercontent.com/31791780/37775214-481608fc-2dda-11e8-89ba-91a086041e21.png)

But when using latte-dock (standalone) I can specify spacing between applications with the `Applet Distance` setting and here is a screen shot of how it looks like with some spacing:

![space](https://user-images.githubusercontent.com/31791780/37775385-ba74c104-2dda-11e8-8f8a-ce6755ec27d4.png)

It is way better I think, what do you think is it possible

**Comment by psifidotos** [comment]
It is possible but it isnt feasible to import all Latte Appearance settings from dock to the plasmoid....

Why dont you try to use Latte Dock as Panel?

**Comment by pupyc** [comment]
Never thought about that, good idea! I will try

**Comment by psifidotos** [comment]
in master version switching between dock mode and panel mode in just one click from settings... 

for v0.7 the easiest way is to use predefined layouts: https://store.kde.org/browse/cat/417/ord/latest/

**Comment by pupyc** [comment]
I have tried it, it is awesome but the problem is still when you make the `Applet Distance` 100% for example all applets will have a huge space between them.

Is there any better solutions ?? or maybe add plasmoid specific settings

**Comment by psifidotos** [comment]
the distance is applied to all elements for uniformity... it isnt separate for applets and separate for tasks

**Comment by pupyc** [comment]
I think the solution is to add latte-plasmoid specific settings

**Comment by psifidotos** [comment]
sorry... I dont like the idea

**Comment by psifidotos** [comment]
the latte-plasmoid specific settings are called Tasks in Latte Dock Settings window

**Comment by pupyc** [comment]
I'm having problem with maping super key to `Application Dashboard` Is there a solution ?? I used `Alt+F1` in plasma panel and it worked but in latte-dock the launcher does not work!

**Comment by psifidotos** [comment]
Alt+F1 isnt needed with Latte...


You can read at FAQs page how to activate the Super key for the app launcher

**Comment by pupyc** [comment]
if you have `Add Spacer` option why would you want `Applet Distance` anyway, I think it makes complete sense to add a space between tasks.
also when I tried to use latte-dock as a panel, there was nothing wrong about it, but it used ~250MB and that alot for my hardware.
although your decision does not make sense at least for me, but I respect your hard and thank you!
