### ISSUE TITLE
Blocking apparition of active window

### ISSUE THREAD

**Issue by BlueKaktus** [psifidotos/Latte-Dock#932]
Hey!
First thanks for this really nice dock app :). 

I would like to set up the following double-panel configuration:

- Panel A : with active window + commun app 
- Panel B: system Tray only

I've successfully created my two panels and added the proper widgets in Panel B. However, active window keeps appearing in Panel B. My question is: Is there a way to prevent it (I would like active windows only on Panel A)?

Thanks 
BK

**Comment by psifidotos** [comment]
I cant understand please provide screenshots

**Comment by BlueKaktus** [comment]
![latte_dock](https://user-images.githubusercontent.com/37671932/37793901-4010e132-2e10-11e8-8bcd-6514b0f6d600.png)
Here is a snap. 

Panel A is at the bottom and Panel B on the right part. 
I had two active windows at that time: Firefox & the screenshot tool. We can see both of them in both panels. I would like to prevent them from appearing in Panel B (right). Is that possible?

**Comment by psifidotos** [comment]
> I would like to prevent them from appearing in Panel B (right).

of course you can. The windows is the Latte plasmoid and you can remove it if you want. 

1. Go to editMode for that panel (that is when the panel settings window is shown)
2. when you hover with you mouse that windows a tooltip is shown, just press the X button which is the one that deletes an applet.

**Comment by BlueKaktus** [comment]
Clear and Simple. 
You're a chief! 

Thanks
