### ISSUE TITLE
"improve content visibility" changes too much

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#933]
At first I thought that's a fault of Active window control but there is more to that. Instead of describing it with words. Please look at the menus and the megasync icon.  Here are the screenshots:

Normal state, no "improve content visibility":

![latte-no-improve-visibility-dark-wallpaper](https://user-images.githubusercontent.com/10132958/37795767-b868df68-2e15-11e8-88a5-c0de96f2f4fb.jpg)

Dark wallpaper with "improve content visibility":

![latte-improve-visibility-dark-wallpaper](https://user-images.githubusercontent.com/10132958/37795813-d3838532-2e15-11e8-8d0c-c347d9847eef.jpg)

Light wallpaper with "improve content visibility":

![latte-improve-visibility-light-wallpaper](https://user-images.githubusercontent.com/10132958/37795827-dff56592-2e15-11e8-8b52-a344df0beef8.jpg)

It clearly shows, that colors are unified and melted together. In short, color change is too aggressive because it doesn't respect native icon colors. Also in global menus background is turned into designed color instead respecting desktop theme color.

Is there a way to make it more sophisticated? I realize, it might be too much to ask, because filtering which elements should switch color and which not may not be easy. Or maybe it's not that hard to define more in details which parts of the panel should response to change of color?

The issue happens when there are some tray icons and global menus so not in all configurations, but it's quite frequent to have some try icons so someone will report it sooner or later.

**Comment by psifidotos** [comment]
From Latte  nothing more can be done... 

For every such issue must be workaround from user side...

In my system I did the following:

1. For AWC I dont show the window icon
2. For AWC I use the master version that solidifies the Latte panel when showing menus
3. For telegram in the systray I changed its icon to monochrome one with nice borders...

so this is a plasma frameworks limitation...

**Comment by michaldybczak** [comment]
A pity. So at this time you need to consider how to put disclaimer to that option. Otherwise people will keep reporting this issue over and over.
The feature is handy but has limitation and a user must be aware of it.

My suggestion would be to put it at the end of "dynamic background" section with some info, like:

- Improve content visibility when panel is transparent*
*May cause readability issues with global menus and some tray icons

Or something like that.

**Comment by psifidotos** [comment]
This isnt the way to handle this...

The disclaimer will be in v0.8 release article and at FAQs page that is all... All  requests will be forwarded to them.

**Comment by michaldybczak** [comment]
OK. I'm not a software developer so I'm not familiar with how things should be handled in case like that. I'm fine with that solution too.
