### ISSUE TITLE
Left side dock sometimes doesn't shows up

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#935]
Moving the cursor over the left border of the screen doesn't make the dock to show up everytime.

Gif of the issue:

![dock](https://user-images.githubusercontent.com/34775187/37897648-0920daa6-30bd-11e8-9e9d-e323cf423855.gif)

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-my-left-dock-behaves-strangely-from-plasma-510-and-beyond-can-i-fix-this

**Comment by psifidotos** [comment]
this bug doesnt influence all systems and I cant reproduce in my system in order to find anything better... on the other hand adding text for an issue that doesnt influence all systems I dont like it as idea... 

either way this in an open source project so some involvement from the users I consider it important... I think that users should first contact the issue either with the developers or the kde community before trying something else...

I could accept of course any pull request fixing this...

**Comment by ssspacez** [comment]
One idea: send a message to Michael https://www.youtube.com/channel/UCmyGZ0689ODyReHw3rsKLtQ/featured, I've heard he saying on YouTube that he uses Latte Dock and doesn't even use KDE panels, just the Latte Dock, or post something on KDE reddit(https://www.reddit.com/r/kde/), I don't know, this might bring attention to this and solve the issue. I don't do this myself because I'm no one :) , but you will probably be heard and get an answer really fast.

**Comment by psifidotos** [comment]
Very bad practice in open source projects to try to solve issues through negative marketing...

ssspacez  can you reprosuce this in your system?

**Comment by ssspacez** [comment]
More eyes, less bugs! :) Yes, the dock on the bottom works fine and doesn't need the touchscreen fix, it's just when the dock in on the left side of the screen that this issue happens.

**Comment by psifidotos** [comment]
if you add a plasma panel on the left edge in Auto Hide mode it works correctly?

**Comment by psifidotos** [comment]
Ok.. I tried to solve this based on plasma experience but new problems are created and for that reason I think we will stick with the current implementation...

The discussion can be found here: https://bugs.kde.org/show_bug.cgi?id=382219

**Comment by ssspacez** [comment]
No, it doesn't work correctly, the panel pops-up twice:

![panel](https://user-images.githubusercontent.com/34775187/38051110-b2a62a26-32a3-11e8-8665-a4e84e31bb21.gif)

(P is the icon of Peek, the gif recorder)

**Comment by psifidotos** [comment]
Same findings in my system... if you keep pressing the left edge you will see that sliding in to continue endlessly...

I reported the findings at the above kde report
