### ISSUE TITLE
Two black bars show around the dock 

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#937]
Two black bars show around the dock:

![docks](https://user-images.githubusercontent.com/34775187/37899481-02fe2098-30c2-11e8-9fcf-4cab12c07b7b.png)

**When it happens**: after closing the configuration window clicking on the desktop.

**Frequency**: not always, just sometimes, less than half of the times I close the window.

**Comment by psifidotos** [comment]
if you change your theme to light one then these two probably will be light then... These are remainings from the config window painting...

Has never happened in my system but I am almost certain thas this is Qt+X11 limitation... all painting issues are fixed in wayland...
