### ISSUE TITLE
Signal: Segmentation fault (11) 

### ISSUE THREAD

**Issue by JackWhite20** [psifidotos/Latte-Dock#938]
Hey,

I am using latte-dock on Kubuntu 17.10 and it does not start any more.

Version is:
0.7.78+git20180327.1956-0~ubuntu17.10~ppa1

Kubuntu Info:
![latte-dock-1](https://user-images.githubusercontent.com/7138037/38023636-2c0e7da8-3283-11e8-872b-b392b370ddc4.png)

I have tried to start it from the command line without luck:

![latte-dock-2](https://user-images.githubusercontent.com/7138037/38023721-55fd5e7c-3283-11e8-95a5-8a3807ccf5de.png)

**Comment by psifidotos** [comment]
try to clear your cache first at:  `~/.cache/lattedock`

**Comment by JackWhite20** [comment]
That actually worked, thanks!

I wonder how that is related to the segmentation fault.

**Comment by psifidotos** [comment]
no idea...

what I know is that this has occured only at kubuntu and at some point kubuntu devs had reported that it was something wrong and they had fixed it... In a case cache shouldnt create crashes... 

https://github.com/psifidotos/Latte-Dock/issues/788
https://bugs.launchpad.net/kubuntu-ppa/+bug/1736765

**Comment by JackWhite20** [comment]
Ah okay, interesting.

Thanks for the quick help and awesome work!
