### ISSUE TITLE
Warning spam in the log: Wrong IconThemePath

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#94]
This is spammed **a lot** in `journalctl -f`:

    Jan 27 17:05:59 rk-pc latte-dock[12346]: [warning 17:05:59.613613] - Wrong IconThemePath "/home/rk/.thunderbird/ksjuvcgt.rk/extensions/{9533f794-00b4-4354-aa15-c2bbda6989f8}/chrome/skin/icons/linux" : too short or does not end with 'icons'

Any chance we could get rid of this? Disabling [FireTray](https://addons.mozilla.org/en-US/thunderbird/addon/firetray/) addon makes spam go away.

**Comment by psifidotos** [comment]
I think this is a general question how to hide all warnings...

@audoban any idea how we can hide all warnings? e.g. when we are ready for release...

**Comment by audoban** [comment]
Hello @rokups, this also happen with plasmashell?

@psifidotos I think, but I need experiment a bit.

**Comment by rokups** [comment]
@audoban i do not quite understand the question i think. That command streams logs from all kinds of services, including plasmashell. However nothing spams logs that much. Latte dock emits several logs / second making log viewing complicated.

**Comment by psifidotos** [comment]
from latest master, any messages appear only if the user sets **--debug** when executing latte
