### ISSUE TITLE
Klipper keyboard shortcuts don’t work in Latte Dock

### ISSUE THREAD

**Issue by silverhook** [psifidotos/Latte-Dock#940]
I use Klipper a lot and its short-cuts are very helpful.

Oddly enough, if I have it in Latte Dock instead of the standard Plasma panel, the same shortcuts don’t work any more (e.g. `Ctrl+Alt+V`).

A work-around is to set the shortcut to Klipper under the Latte Dock shortcuts. But that means that the standard Plasma shortcut to Klipper would be now be overridden to be empty.

So Plasma and Latte Dock seem to be competing for shortcuts to/of (some) Plasmoids.

I suspect this is true not only for Klipper, but any similar short-cuts to/of Plasmoid that are added to Latte Dock.

**Comment by psifidotos** [comment]
> A work-around is to set the shortcut to Klipper under the Latte Dock shortcuts. But that means that the standard Plasma shortcut to Klipper would be now be overridden to be empty.

this is plasma default behavior around shortcuts. The same shortcut can not be applied in more that one action. so I can not understand what you are trying to achieve.

**Comment by silverhook** [comment]
@psifidotos, thanks for the quick reply.

I did notice this seems to be common. But it is confusing. From the end user PoV, a Klipper action is the same Klipper action whether it’s in Latte Dock or in Plasma.

**Comment by psifidotos** [comment]
unfortunately that is the way it is...

**Comment by silverhook** [comment]
@psifidotos So, it’s a Plasma bug/feature? Happy to open an issue there.

**Comment by psifidotos** [comment]
yes this is plasma related, but I wouldnt be too optimistic that something would change around the current way of doing things...
