### ISSUE TITLE
Sometime I get a segment fault by dragging tasks in the tasks manager plasmoid

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#944]
Sometime I get a segment fault, with not useful backtrace information, by dragging tasks in the tasks manager plasmoid amd if is present the internal separator

**Comment by psifidotos** [comment]
I cant reproduce

**Comment by psifidotos** [comment]
at least we must see the backtrace in order to be sure that we can not track this down.

**Comment by psifidotos** [comment]
I will wait for a backtrace...
