### ISSUE TITLE
The Top dock auto hide mode doesn't work properly

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#946]
[screencast.zip](https://github.com/psifidotos/Latte-Dock/files/1865913/screencast.zip)

**Comment by psifidotos** [comment]
this is the same video with the previous issue

**Comment by JenaPlinsky** [comment]
here it is :)
[test.zip](https://github.com/psifidotos/Latte-Dock/files/1865933/test.zip)
