### ISSUE TITLE
Global menu font alignement

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#947]
is there a way to center the font of the global menu when the icon size is less than 24 pixels without even changing the setting of the "General" font?
![screenshot_20180331_233820](https://user-images.githubusercontent.com/24593950/38167801-9a12ca8c-353c-11e8-8c1b-630ec4a988f5.png)

**Comment by psifidotos** [comment]
no idea... you should contact with its developer...
