### ISSUE TITLE
dodge reveal  not working correctly

### ISSUE THREAD

**Issue by tjlynchny** [psifidotos/Latte-Dock#948]
Hi, just installed Neon a few days ago along with Latte-dock (0.7.4) from the KDE software center. If I fire up latte-dock from command line, it will appear, but once it disappears, I cannot make it reappear. Have to kill it and restart to see it again.  Tried different hide / reveal settings, but nothing seems to work.
KDE Plasma 5.12.4
KDE Frameworks 5.44.0
QT 5.10.0
Kernel 4.13.0-37-generic
64-bit
on a Dell M4700

**Comment by psifidotos** [comment]
does this occur at the left edge?

**Comment by tjlynchny** [comment]
both the left edge and bottom, haven't tried the right side or above

**Comment by psifidotos** [comment]
@tjlynchny try to disable all touch gestures from plasma systemsettings and re-login to plasma

**Comment by psifidotos** [comment]
![touch_gesture](https://user-images.githubusercontent.com/2216474/38198527-df372126-3695-11e8-8f67-f014a131bc43.png)

**Comment by tjlynchny** [comment]
That seems to fix it!  Great!
