### ISSUE TITLE
Feature request: alternative task highlight indicators for big square icons

### ISSUE THREAD

**Issue by Tichy** [psifidotos/Latte-Dock#949]
When using big square icons like Evolvere, it's more difficult to spot which applications are open, in foreground or minimized, because the standard indicator tends to blend with the icon. See screenshot.
I think it would be nice to have an alternative style for the indicator, or maybe to be able to modify the distance between the indicators and the icons. Maybe, placing them further, will make them more easily spottable.
![screenshot_20180402_160232](https://user-images.githubusercontent.com/2348771/38199186-1d76041c-3690-11e8-98b7-a783d148e74f.png)

**Comment by psifidotos** [comment]
You can achieve this differently:

1. Enable Applet Shadow from Appearance page
2. Make the Applet Shadow fully transparent
3. Increase the Applet Shadow as much as you like

![hidden_shadows](https://user-images.githubusercontent.com/2216474/38199951-3149568c-369b-11e8-83e1-3c33929766c5.png)

**Comment by Tichy** [comment]
Hi! I tried what you suggested, but I didn't achieved the same result. My indicators are still attached to the icons.
![screenshot_20180402_165900](https://user-images.githubusercontent.com/2348771/38201142-71ff0cca-3697-11e8-8a52-e563fd1d3db5.png)
![screenshot_20180402_165918](https://user-images.githubusercontent.com/2348771/38201146-7662ae8e-3697-11e8-810b-88ab8f3f7c9f.png)

**Comment by psifidotos** [comment]
> I'm still with latte dock 0.7.4

Oh.... that 's probably the reason. I am using master version so this feature will land with 0.8.0

**Comment by Tichy** [comment]
No problem. I'll wait patiently ;-)
