### ISSUE TITLE
an easy way to add applets to the latte dock seems to be missing

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#95]
I don't see how to add applets to latte dock other than editing config files. am I missing sth here?

**Comment by psifidotos** [comment]
:) just drag n' drop them from the widget explorer of plasma

**Comment by kupiqu** [comment]
Oops, missed it! :)

**Comment by AndydeCleyre** [comment]
Hmm, is this available in the `0.5.91` release? I'm not seeing it (latte on the left, nowdock on the right):

http://streamable.com/uimtl

Testing on Arch

**Comment by AndydeCleyre** [comment]
Oh yeah, it's working with git checkout, nevermind. Thanks!
