### ISSUE TITLE
Widgets: CPU/network/disk monitors

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#951]
I was testing adding some widgets to the dock, and almost all work fine, all but CPU/network/disk monitors, they break everything.

I don't know why anyone would want to use them on the dock, I'm just testing/reporting that they mess with the dock really bad when added.

0.7.79+git
Kubuntu 18.04 Beta 1
DE: KDE 5.44.0 / Plasma 5.12.4
Display Server: x11 (X.Org 1.19.6 )
1366 x 768 14" screen

**Comment by psifidotos** [comment]
can you show me a screenshot how they look in a plasma panel?

**Comment by psifidotos** [comment]
> I don't know why anyone would want to use them on the dock, I'm just testing/reporting that they mess with the dock really bad when added.

this is these applets issue and not Latte. If they show too much records they become too big and they mess things up even at plasma panel... If the user chooses from its settings to show only one or two records then they show much nicer...

![monitors](https://user-images.githubusercontent.com/2216474/38205415-33c5c698-36af-11e8-88f8-bab0d5da3e10.png)

**Comment by ssspacez** [comment]
Apparently they are working fine on panels:

![cpu](https://user-images.githubusercontent.com/34775187/38208133-6f99a6ea-3686-11e8-8066-6d94533af3b9.png)
![network_disk](https://user-images.githubusercontent.com/34775187/38208134-6fbd01d0-3686-11e8-8dbb-ac31e8e2f41e.png)

**Comment by ssspacez** [comment]
And this is how the CPU looks like with 4 cpus+system showing:

![screenshot_20180402_150325](https://user-images.githubusercontent.com/34775187/38208333-1d2570d2-3687-11e8-837a-2075764b36b2.png)

It resizes itself with very small icons and goes to bottom right corner.

**Comment by psifidotos** [comment]
yes, and this is happening because of the configuration of that applet. Same thing would happen if you added a plasma taskmanger... I order to change that behavior you must **disable:** Tweaks->Decrease applets size when is needed
