### ISSUE TITLE
Support transparency without composition

### ISSUE THREAD

**Issue by brauliobo** [psifidotos/Latte-Dock#953]
It is a basic feature and it is very confusing to be able to configure when it doesn't work without composition.

I can't enable composition as I'm using the unstable AMD Raven Ridge

**Comment by psifidotos** [comment]
so what you mean is to disable transparency panel setting for !compositing?

**Comment by brauliobo** [comment]
I mean to have transparency even without composition, or at least indicate that it wont work without composition

**Comment by brauliobo** [comment]
thanks :)

**Comment by psifidotos** [comment]
> I mean to have transparency even without composition

unfortunately this isnt possible...

> or at least indicate that it wont work without composition

that made sense... ;)
