### ISSUE TITLE
Strange flickering and duplicated tasks

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#954]
Ciao @psifidotos 
My master branch is updated to commit "update to version 0.7.79" and since then, you've added several changes
in any case, I noticed a strange flickering on the task manager again and I think it is due to some internal or external separator combined with the "global" launchers group mode
[BottomDock_2018-04-02_193358.zip](https://github.com/psifidotos/Latte-Dock/files/1868846/BottomDock_2018-04-02_193358.zip)
[BottomDock_2018-04-02_193358_slowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1868845/BottomDock_2018-04-02_193358_slowMotion.zip)
I've removed the plasmoid separator and nothing improved
then playing on the launchers group I get this
![screenshot_20180402_195101](https://user-images.githubusercontent.com/24593950/38207814-5bc1b8b4-36af-11e8-84a9-dde92a15ee82.png)
some time ago, a situation like this was happened and it was due to the presence of an internal separator in the "unique" group
but now I do not observe any internal separator

**Comment by JenaPlinsky** [comment]
I'm not 100% sure, but this situation occurred just after a layout change

**Comment by JenaPlinsky** [comment]
![screenshot_20180402_222904](https://user-images.githubusercontent.com/24593950/38214673-aa46d22e-36c5-11e8-9ff0-b23926c62121.png)
the dupplicated icon I do not know what it represents, it is not a launcher, it is not a task, and it can not be moved

**Comment by psifidotos** [comment]
sounds like in your system is happening an internal separators mess including a plasma libtaskmanager one.  

Internal separators can be found in three places, my advice is to remove all of them I cant release reproduce what is happening in your system.

Internal separators

1. Global Launchers are found at: **~/.config/lattedockrc**
2. Layout Launchers are found in the layout file at section is called: **LayoutSettings**
3. Unique Launchers are found in the layout file in the latte containment record called: **launchers59**
