### ISSUE TITLE
Move window tabs to a left panel

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#955]
Newer versions of Plasma have by default the configuration tabs on the left, to stay consistent and look more like the Desktop Environment, why not put the **top tabs on a left panel** of the dock window? I mean: attaching a "box" on the left side of the dock window and put the tabs there like KDE system settings.

This also **creates more room for future new configurations/features**(it's a vertical list on the left, you just add more tabs/items to it) and you can get rid of the **< and > buttons** of the top. You also gain some pixels of **vertical space**.

![screenshot_20180402_151511](https://user-images.githubusercontent.com/34775187/38209044-66ec5878-3689-11e8-9c7c-882dc6a95de5.png)

**Comment by ssspacez** [comment]
Configurations on a left window/column appear everywhere, GNOME Settings, LibreOffice settings, etc, users are used to navigate configurations this way.

The possibility to create more tabs is a good advantage, in the future you can add as much features as you wish, or organize the customizations better, just keep stacking tabs vertically.

**Comment by psifidotos** [comment]
sorry this is a totally new design decision and one of which I dont like

>The possibility to create more tabs is a good advantage, in the future you can add as much features as you wish, or organize the customizations better, just keep stacking tabs vertically.

Latte doesnt have a goal to extend its settings to include all minor corner cases... It tries to have a middle ground between basic functionality and advanced settings...
