### ISSUE TITLE
Launching Latte only if the DE is Plasma

### ISSUE THREAD

**Issue by Tromzy** [psifidotos/Latte-Dock#959]
Hi, I use Archlinux with Plasma as my main DE, but I also use other DEs sometimes like Gnome, Budgie, Cinnamon, etc. The thing is, I have set Latte Dock to launch automatically at the session startup, since I use it to put my plasma panel elements and stuff on it.

But the thing is, whenever I launch another session, a Gnome one for example, Latte Dock launches and overlaps my Gnome / budgie / whatever desktop elements.

Is there a way to tell Latte Dock to launch only for a Plasma session, and not a Gnome or any other DE one ?

**Comment by trmdi** [comment]
Launch latte from a bash script.

**Comment by psifidotos** [comment]
@Tromzy  yes you can: https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-is-there-a-way-to-tell-latte-dock-to-launch-only-for-a-plasma-session-

**Comment by Tromzy** [comment]
Wow, thanks !
