### ISSUE TITLE
Right click on systray icons do not work as expected

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#96]
Some icons in the systray have right click options which do not emerge on latte dock panel. the only two available options are systray settings and latte settings, but no specific options about the selected icon.

**Comment by omni6** [comment]
damn good!

**Comment by kupiqu** [comment]
trully impressive, indeed

**Comment by psifidotos** [comment]
?

**Comment by omni6** [comment]
you fix issues in minutes, i dont know anything you do but this makes fun! Watching a project grow and evolve....

**Comment by psifidotos** [comment]
;-) thank u! There are these moments sometimes ! :-)
