### ISSUE TITLE
Dock sometimes is just grey or shows distorted background 

### ISSUE THREAD

**Issue by knut-hildebrandt** [psifidotos/Latte-Dock#960]
Sometimes the bottom dock does not show the widgets and the control panel I had added to it, but is either just gray or looks like a distorted portion of the window behind. This does not always happen and if it happens changing the desktop a couple of times gets it back to normal. Interestingly, if I hover over it, the tool tips of the programs pop up correctly.

I suppose this might be caused by the fact that the dock holds the plasma control panel, since all other docks always work fine. Apart from that it looks as if two docks/panels would appear when I get close to the edge of the screen, one after the other. BTW, all my docks are hidden.

Add two screenshots but can't reproduce the blur in the moment. Will add this as soon as it happens again. But while trying to reproduce it I noticed that parts of other docks sometimes are not rendered correctly too. Thus the Latte-Plasmoid did not show anything in some occasions, whereas the preview windows always showed up when I hovered over the respective areas. All this looks very random.

![latte-grey](https://user-images.githubusercontent.com/27674986/38340419-a3e6911c-3873-11e8-8aba-51e811ad21f6.jpg)
![latte-okay](https://user-images.githubusercontent.com/27674986/38340420-a4162030-3873-11e8-97f0-0bbc24caccba.jpg)

**Comment by psifidotos** [comment]
The distorted case might be a driver issue.

1. Show me full screenshots for the entire screen
2. What latte version are you using
3. X11 or Wayland

**Comment by knut-hildebrandt** [comment]
>The distorted case might be a driver issue.

It's an on-board Intel graphics card. 

> What latte version are you using

0.7.4

>X11 or Wayland

X11

![latte-distorted](https://user-images.githubusercontent.com/27674986/38372640-997da2fc-38ef-11e8-97ac-4837138c958b.jpg)

**Comment by psifidotos** [comment]
this is probably a graphics driver issue...

something is going on with the intel driver.
another user reported this:  https://github.com/psifidotos/Latte-Dock/issues/939

**Comment by knut-hildebrandt** [comment]
You referenced this issue to #939 but I do not think it is the same issue. Read the whole thread and  tried all the settings you recommended, but it did not help. What helped was disabling shadow for the background and selecting "solid color" or however it is called in the settings. Language is set to German on my system. Maybe this hint will help the find the cause for the issue. Anyhow, I'm happy with how it is now and consider this SOLVED.

Thanks

Knut

**Comment by psifidotos** [comment]
Yep the above settings may helped because they disable transparency which is the graphic drivers responsibility...
