### ISSUE TITLE
"Improve contents visibility" option without solid background

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#961]
It would be very useful if we could enable "Improve contents visibility" option when panel is always transparent.

At the moment panel with all 4 dynamic background options enabled. When window is not maximized it looks perfect:

![latte2](https://user-images.githubusercontent.com/19151258/38379126-6fe8f694-3908-11e8-90f7-f5d070e8009f.png)

When window is maximized it looks like this:
![latte](https://user-images.githubusercontent.com/19151258/38378988-ff9ac21e-3907-11e8-9c0a-3bce7b20e5e3.png)

Latte is rendered on top of window titlebar when window is maximized. It is configured to go above windows. Notice darker background dock has. It would be great if we have a transparent background even when window is maximized and have it nicely blend with window titlebar.

**Comment by psifidotos** [comment]
I suppose this has already implemented through: https://github.com/psifidotos/Latte-Dock/issues/957

**Comment by rokups** [comment]
It is not possible to select "Improve contents visibility" if "Force solid background for maximized" is not selected.
![bg](https://user-images.githubusercontent.com/19151258/38380615-e411a67a-390c-11e8-9636-abc22bd598b7.png)

**Comment by psifidotos** [comment]
makes sense... let me update first the Design at #957

**Comment by rokups** [comment]
Something is still off.
![latte](https://user-images.githubusercontent.com/19151258/38407161-0e926f0a-3981-11e8-94da-feefb3a92377.png)
Results in
![tray](https://user-images.githubusercontent.com/19151258/38407176-1e50c8c4-3981-11e8-9c4f-bbedf95e25eb.png)

**Comment by psifidotos** [comment]
Show me also the Appearance-> Background Settings

**Comment by rokups** [comment]
![bg](https://user-images.githubusercontent.com/19151258/38407704-35431c4c-3983-11e8-8f14-5967eaeb3e89.png)

**Comment by psifidotos** [comment]
Have you enabled Tweaks-> Blur ? 

Have you nabled also Background Contrast Kwin Effect?

**Comment by psifidotos** [comment]
send me your layout file

**Comment by psifidotos** [comment]
any chance you are hit from upstream intel bug: https://github.com/psifidotos/Latte-Dock/issues/939 ?

**Comment by rokups** [comment]
[layout.layout.latte.txt](https://github.com/psifidotos/Latte-Dock/files/1883085/layout.layout.latte.txt)
Using RX580 with amdgpu here.

**Comment by psifidotos** [comment]
:)... you are using "Windows Go Below" when a window is maximized its titltebar is underneath the Latte panel.
 
"Improve Contents" takes into account only the desktop background not the window titlebars, this isnt possible...

**Comment by rokups** [comment]
Oh that is unfortunate :) I guess the only way to work this around is to match titlebar color to background of panel.

**Comment by psifidotos** [comment]
> Oh that is unfortunate :) I guess the only way to work this around is to match titlebar color to background of panel.

it is a mess...

**Comment by psifidotos** [comment]
> Oh that is unfortunate :) I guess the only way to work this around is to match titlebar color to background of panel.

on the other hand  the "Windows Go Below" case is a little special...
If we can assume that the plasma theme background will follow the window titlebar background then  we could achieve the following:

-> Windows Go Bellow + Top Panel + Panel Transparency<40% + "Improve Visibility" + "Not Forced Solid Background for maximized windows)

which is your case, then we could assume that the "Improve Visibility" (Colorizer) isnt needed because the window title bar will be under the panel to provide the solidness and because we assumed that the plasma theme follows the window titles it should be ok...

**Comment by rokups** [comment]
But what if window titlebar color is light instead of dark and wallpaper is dark instead of light?

**Comment by rokups** [comment]
That works nicely with light wallpaper. Out of curiosity i tested dark wallpaper:
![forest](https://user-images.githubusercontent.com/19151258/38424038-72310300-39b8-11e8-817b-d13e4204cd18.png)
Maybe a tweak could exist to allow user to configure colorization options for mazimized/snapped and non-maximized cases? I am all happy with how it works now, just thinking others with different combination of colors could find this useful.

**Comment by psifidotos** [comment]
> That works nicely with light wallpaper. Out of curiosity i tested dark wallpaper:

wallpaper should be irrelevant... No idea why it broke for you ... as long as there isnt a maximized window then colorizer should work properly for you... at the above screenshot the textColor should be light not dark... Play with it and tell me settings and when it breaks with full desktop screenshots please.
