### ISSUE TITLE
Dynamic background should not react to windows on other monitors

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#962]
Now if panel is on one monitor but window is maximized on another monitor then panel gets solid background. It should remain transparent unless maximized window is in same monitor.

**Comment by psifidotos** [comment]
what is your latte version?

**Comment by psifidotos** [comment]
fixed with: https://github.com/psifidotos/Latte-Dock/commit/5e4134b1eed3c09152bef1d174eba7c53f20288f

**Comment by psifidotos** [comment]
thaks a lot, very good catch
