### ISSUE TITLE
Lock window while scrolling

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#963]
When I scroll down(mouse) the window sometimes the cursor gets over a bar and change the values there. I don't know if this is possible but it would be nice to "lock" the window when the cursor is scrolling so it doesn't change anything while the user is exploring/scrolling the content of tabs to avoid changing configs by mistake.

**Comment by psifidotos** [comment]
Screenshot please, which bar?

**Comment by psifidotos** [comment]
1. Latte can not lock scrolling to external apps

2. Which internal Latte scrolling is the one creating an issue for you?

**Comment by ssspacez** [comment]
Sorry for my English, by "bar" I meant one of these:

![img](https://user-images.githubusercontent.com/34775187/38404977-f9a7bd4e-3943-11e8-9cdd-5f2aa674ab6e.png)

**Comment by ssspacez** [comment]
People need to pay extra attention on this tab if they have the Advanced mode ON, if you don't pay attention you change one or more of them just scrolling down the page and don't even notice until later... a few times this was my reaction: "Wait.. the dock changed? I didn't changed anything. Maybe it's a bug?!".

**Comment by psifidotos** [comment]
Yeah makes  sense, I will check it out but I dont think it is possible. It is probably a default behavior for sliders that cant be changed

**Comment by psifidotos** [comment]
ok... done...

**Comment by JenaPlinsky** [comment]
Very nice !!!
