### ISSUE TITLE
More icon size options

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#965]
I was resizing the icons and... there's a big jump from one size to another, **8 pixels each**. I think these incremental changes would be better if they were 4 px or even 2 px, this would give the users more options.

**Comment by psifidotos** [comment]
It about blur... if you want other choices, disable from Tweaks-> Reduce icon size when it is needed. Whenever you are at advanced mode you will be able to changw icon size 1px.
