### ISSUE TITLE
Always Visible dock cuts a part of the run command window

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#966]
![screenshot_20180407_170209](https://user-images.githubusercontent.com/24593950/38456486-694c661c-3a85-11e8-80e9-7170e62a28ee.png)

**Comment by psifidotos** [comment]
no it doesnt... krunner window because it is a pop up doesnt add a shadow at its top border. You can reproduce the same thing with a plasma panel that has the same size as the Latte top panel
