### ISSUE TITLE
I always get a crash while I try to import a full Latte configuration

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#968]
I always get a crash while I try to import a full Latte configuration

**Comment by psifidotos** [comment]
all of them... what ever package you read at README file you must also install its debug counter part...

**Comment by psifidotos** [comment]
I tried in my system, it doesnt crash...

1. I exported a full configuration
2i. I imported it from the Latte Settings window
2ii. I imported it from command line through: `latte-dock --import-full <filename>` works just fine.

The latte full configuration is a zip file so you could access your layout files in it easily in case something is broken...
