### ISSUE TITLE
Latte and missing process

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#969]
Can you figure out where the running Latte process is?
[screencast_2018-04-07_203856.zip](https://github.com/psifidotos/Latte-Dock/files/1886638/screencast_2018-04-07_203856.zip)

**Comment by psifidotos** [comment]
I suppose qt issue or the file indicating that latte is running wasnt removed properly because Latte wasnt closed properly...
I suppose you can run --replace and start Latte properly....

**Comment by psifidotos** [comment]
Latte is using QLockFile to provide this http://doc.qt.io/qt-5/qlockfile.html so this isnt Latte responsibility...

**Comment by JenaPlinsky** [comment]
![screenshot_20180407_210655](https://user-images.githubusercontent.com/24593950/38459235-9b09c7f4-3aa7-11e8-9539-cfef03ca550f.png)

**Comment by JenaPlinsky** [comment]
incredibly despite the laptop **restart** I get the same output as described above
before highlighting this problem I think I have done something like this but with the **ROOT** privileges

ddd latte-dock --replace
![screenshot_20180407_213218](https://user-images.githubusercontent.com/24593950/38459545-29517f54-3aab-11e8-9306-e372021341fb.png)


Now I will try to reinstall Latte

**Comment by JenaPlinsky** [comment]
Rebuilding and install from master did not solve the problem
for a deep un-installation, have I to remove the folder in /usr/share?

wait a minute ... but I can not find latte there ... where are its folders?

**Comment by psifidotos** [comment]
Latte folders have nothing to do with it. Let me explain you how this works.

1. When Latte starts create a file at tmp folder. The file is : `/tmp/latte-dock.<username>.lock`
2. When Latte closes automatically deletes the previous file
3. The file contains the Latte process infos
4. When a second Latte tries to start from the same user then if checks if that file exists and Qt also checks if that pid also exists. If both the file and the pid in it exist then the message you see appears. If it doesnt e.g. after a crash then Qt automatically deletes the deprecated lock file and creates a new one

What you could try to do is to delete that file manually and see what happens afterwards. The reason that Qt cant do in your system I think can be only two:
1. there is such pid with same name
2. the file somehow changed ownership and not as a simple user cant be deleted

so if you cant delete as simple user, delete it as root.

**Comment by JenaPlinsky** [comment]
> the file somehow changed ownership and not as a simple user cant be deleted

Even I, I thought that this problem was related to a question of ownwership or permissions ... but I had not really thought about that specific file

- Here is the cause of the problem exactly as you guessed it
   
   /tmp/latte-dock.<username>.lock 
   Owner user: root
   Owner group: root

**Comment by JenaPlinsky** [comment]
So,
I think you should forbid the opening of instances with a different owner from the account in use

**Comment by psifidotos** [comment]
> So, I think you should forbid the opening of instances with a different owner from the account in use

this is Linux responsibility except if you believe that Latte should change operating system

**Comment by JenaPlinsky** [comment]
> this is Linux responsibility except if you believe that Latte should change operating system

Aahahaa Ohh Nooo I do not believe that. Linux Plasma and Latte are a wonderful composition
