### ISSUE TITLE
KWin Edge ghost hidden window interferes with parabolic effect

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#970]
Sometimes, the dock's rise up stops, and the tooltip covers the icons
[BottomDock_2018-04-08_095847.zip](https://github.com/psifidotos/Latte-Dock/files/1887178/BottomDock_2018-04-08_095847.zip)

**Comment by JenaPlinsky** [comment]
On my system everything is still as before

**Comment by psifidotos** [comment]
so sorry... as good as it gets for now...

**Comment by psifidotos** [comment]
this issue occurs when the dock is during sliding and the user hovers a tasks and at the same time has enabled previews... so too much complexity to add for just a small issue

**Comment by JenaPlinsky** [comment]
> this issue occurs when the dock is during sliding and the user hovers a tasks and at the same time has enabled previews

Just a note, it does not depend on the preview flag enabled
min 1:33 [BottomDock_2018-04-08_183452_SlowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1887679/BottomDock_2018-04-08_183452_SlowMotion.zip)

**Comment by psifidotos** [comment]
> Just a note, it does not depend on the preview flag enabled

in 1:33 there is no preview

**Comment by JenaPlinsky** [comment]
in fact, the problem seems to be related to the rise of the dock that for some reason is interrupted if the preview was enabled at that point would be shown

**Comment by psifidotos** [comment]
> if the preview was enabled at that point would be shown

this is hypothetical...

> min 1:33 BottomDock_2018-04-08_183452_SlowMotion.zip

you sent a video, what do you expect from me to see in that video as an issue? at 1:33 no issue appears

**Comment by psifidotos** [comment]
> but normally at that point the task icon should be zoomed because the mouse is exactly below it

so you are referring to a different issue than the original topic...

1. are you at X11 or wayland?
2. have you enabled any touch gestures for that edge or a kwin edge action?

**Comment by JenaPlinsky** [comment]
> so you are referring to a different issue than the original topic...
Ohhh yes the topic

Ohhh yes the original topic was different I should change the title

> are you at X11 or wayland?

X11 but now I'll try under wayland session

have you enabled any touch gestures for that edge or a kwin edge action?
no touch gestures for that edge
Cube on left-bottom, Presentation on right-bottom  for kwin

**Comment by JenaPlinsky** [comment]
This problem is also observable on Wayland

...and while I tried to replicate it **sometimes** the dock rise-up and close-down, pumping in an endless cyclically

**Comment by psifidotos** [comment]
sorry.... works fantastic in my system...

**Comment by JenaPlinsky** [comment]
even with ,,, ?
 delay to show=400ms
 delay to hide=400ms

**Comment by psifidotos** [comment]
flawlessly

**Comment by JenaPlinsky** [comment]
Activate KWin edge after hiding ...

    - disabled
         here the problem discussed in this thread seems to have been resolved

    - enabled
         the issue seems not fixed

Can you confirm ?

**Comment by psifidotos** [comment]
yep, only difference is that in my system happens very rare
