### ISSUE TITLE
Cant open Settings Window. 

### ISSUE THREAD

**Issue by relink2013** [psifidotos/Latte-Dock#973]
I installed latte dock on Kubuntu 17.10, and it looks nice but I cannot open the settings window. When I right click and go to Dock/Panel Settings, I get a Blue grid behind the dock, and a translucent blurry square at the top left of my screen and thats it. 

I installed from ppa:rikmills/latte-dock, I also added the backports repo, and did apt-get dist upgrade before installing latte dock.

**Comment by psifidotos** [comment]
yeah I know it was fixed yesterday.

@rikmills is it possible to update that package with latest commits from master? I had used by fault a library that needed Qt 5.10 in the settings window. Now it should be ok as it needs Qt 5.9

**Comment by rikmills** [comment]
@psifidotos New builds done. Just waiting on the launchpad publisher to make the binaries available. Some days can be a few mins, others a fair bit longer.

**Comment by psifidotos** [comment]
no prob
