### ISSUE TITLE
Very small dock pumping

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#974]
Very very small indecision when it reaches its 100%
It is almost imperceptible and I don't know if it is worth trying to solve it but maybe it could be useful for other things
[BottomDock_2018-04-10_204420.zip](https://github.com/psifidotos/Latte-Dock/files/1896039/BottomDock_2018-04-10_204420.zip)

**Comment by psifidotos** [comment]
Previews and title tooltips use the same spacing currently. For previews that behavior is needed because the mouse must enter the preview immediately after leaving the task element.  For tooltips probably we need to increase that spacing.

**Comment by psifidotos** [comment]
@JenaPlinsky can you play that video again with --graphics enabled? I cant reproduce this...

1. what is you plasma theme?
2. what is your applet size and zoom factor?

**Comment by JenaPlinsky** [comment]
> what is you plasma theme?

![screenshot_20180414_193219](https://user-images.githubusercontent.com/24593950/38770935-8d039018-401a-11e8-8ec3-b92afc9f89bb.png)

![screenshot_20180414_193104](https://user-images.githubusercontent.com/24593950/38770920-6032fc90-401a-11e8-9755-ab3fec63712f.png)

> what is your applet size and zoom factor?

![screenshot_20180414_192754](https://user-images.githubusercontent.com/24593950/38770888-f5e88044-4019-11e8-8c09-2ce4233b25ae.png)




> can you play that video again with --graphics enabled? I cant reproduce this...

[BottomDock_2018-04-14_193750.zip](https://github.com/psifidotos/Latte-Dock/files/1910686/BottomDock_2018-04-14_193750.zip)
[BottomDock_2018-04-14_193750_SlowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1910687/BottomDock_2018-04-14_193750_SlowMotion.zip)

**Comment by psifidotos** [comment]
cant reproduce... Do you have previews enabled also ?

**Comment by JenaPlinsky** [comment]
> cant reproduce... Do you have previews enabled also ?

Yes, but it does not depend on this

while the "Shrink thickness margin" disabled makes the issue even more visible

**Comment by JenaPlinsky** [comment]
"Shrink thickness margin" disabled 
[BottomDock_2018-04-14_210437.zip](https://github.com/psifidotos/Latte-Dock/files/1910783/BottomDock_2018-04-14_210437.zip)

**Comment by JenaPlinsky** [comment]
Oops I forgot !! I'm using customized icons 128x128

**Comment by psifidotos** [comment]
Does that issue occur only with folderviews in your system?

**Comment by JenaPlinsky** [comment]
> Does that issue  occur only with folderviews in your system?

Ohh no !!, by disabling the previews also occurs with tasks, launchers and plasmoids
...so it does not depend on the icon I've associated with the folderviews

**Comment by psifidotos** [comment]
this issue cant be reproduced in my system, so I am going to wait for more reporters...

**Comment by JenaPlinsky** [comment]
![screenshot_20180501_110014](https://user-images.githubusercontent.com/24593950/39467535-d4aaa5e8-4d2e-11e8-8d5e-2ed5925bcbb4.png)
![screenshot_20180501_110133](https://user-images.githubusercontent.com/24593950/39467578-0697e4ee-4d2f-11e8-89f1-e6c41d42e6f9.png)
I realize that it is complicated to think about things that you can not later reproduce
In any case, I have noticed this thing, maybe it can suggest something

This pumping involves the entire dock and therefore both the applets and the launchers but does **not involve the tasks**, at least when the task's thumbnail is present, despite that its preview window, compared to the tip tool is positioned even closer to the edge
The tasks are instead involved, if the windows previews are disabled

**Comment by psifidotos** [comment]
feel free to add any info

**Comment by JenaPlinsky** [comment]
I do not know if this information can be useful, however I observe the same behavior even under the Gnome session
same behavior even if I change theme or decoration

**Comment by psifidotos** [comment]
nope... the problem is that I cant reproduce... without reproducing this issue cant be fixed... I am waiting for more users to identify such issue in their systems...

**Comment by psifidotos** [comment]
from today all new or unclosed issues should be reported to: https://bugs.kde.org/
