### ISSUE TITLE
Delay to show is ignored with "Activate KWin edge after hiding"

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#975]
Delay to show is ignored with "Activate KWin edge after hiding"

**Comment by psifidotos** [comment]
Yep, that is correct and can not be done anything about it. Kwin has its own interval that you can change from plasma systemsettings. I would disable it but its value is used in some internal settings.

**Comment by JenaPlinsky** [comment]
In that case you could make that timer gray "un-accessible"

**Comment by psifidotos** [comment]
I dont like it as default visual effect
