### ISSUE TITLE
Icon disappears after clicking

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#976]
After clicking, the icon disappears for a split second:

Gif:

![dock](https://user-images.githubusercontent.com/34775187/38584826-f5ab06b2-3ced-11e8-87ac-9533057db227.gif)

**Comment by epintric** [comment]
Disabling the taskbar launch effect fixed that for me.

You can find it in System Settings > Applications > Launch Feedback > Enable taskbar notification

**Comment by ssspacez** [comment]
This workaround works, thank you.

**Comment by psifidotos** [comment]
This is also a good catch

**Comment by psifidotos** [comment]
I will try to make a fix for without needing from the user any change

**Comment by Petross404** [comment]
I think this was an upstream problem, long time ago solved by you psifidotos. How is that it showed up again?

> Disabling the taskbar launch effect fixed that for me.    

I confirm the workaround.

**Comment by psifidotos** [comment]
nope... this isnt upstream because it doesnt occur to plasma taskmanagers. Latte has plenty workaround for plasma libtaskmanager nasty behaviors. There is a chance I can add some more workarounds to catch this case.

**Comment by psifidotos** [comment]
ok I think, it is fixed...
