### ISSUE TITLE
Apps opened from dock minimize to center of screen

### ISSUE THREAD

**Issue by epintric** [psifidotos/Latte-Dock#977]
When I open an app from Latte Dock, it minimizes to the center point of my displays, but when I open them from anywhere else, they behave as expected. The Task Manager and Icons Only Task Manager alternative plasmoids have no issues.

[Example](https://youtu.be/hTQgRfjZweU)

**Comment by psifidotos** [comment]
Send me your layout file, this can be relevant to many things

**Comment by epintric** [comment]
It wouldn't let me upload the raw file so I put it in a .zip
[layout.zip](https://github.com/psifidotos/Latte-Dock/files/1903938/layout.zip)

**Comment by epintric** [comment]
I was messing around with the settings, and it seems that this only happens when "Zoom on hover" is at 0%.

**Comment by psifidotos** [comment]
Are you at X11 or wayland?

**Comment by epintric** [comment]
X11

**Comment by epintric** [comment]
Recompiled it from source with your recent commit. Everything's working perfectly again. Thank you for making this amazing dock, it really helps me achieve the mac-like look I was going for.
