### ISSUE TITLE
Latte Dock silently fails to save any configuration changes on some systems

### ISSUE THREAD

**Issue by therealpxc** [psifidotos/Latte-Dock#980]
When Latte copies over the `.latte.layout` files from the default ones, it doesn't modify their permissions at all. On systems where Latte is installed on a read-only filesystem, or wherever they are otherwise marked non-writable for the owner, this results in read-only `.layout.latte` files in the `~/.config/latte` directory.

Worse, when a layout file is marked read-only, Latte silently fails to save any changes to it. It does not reset the permissions, even when it is run by the user who owns the files. It does not warn the user, either. This problem also prevents configuration changes to widgets within the layouts from being persisted, as well.

This is confusing and painful. :-(

Latte should

 * warn users when filesystem permissions prevent saving layout configurations
 * offer fix the permissions on its config files when the user has sufficient rights to do so
 * lock all docks/panels in layouts which are read-only, so users aren't confused about what they can do

**Comment by psifidotos** [comment]
This is reported first time. Makes sense when copying default files to adjust their permissions. If the permission afterwards are altered then this would be user responsibility. Either way a check that a layout is readonly and a warning isnt a bad idea. Locking the settings I dont agree, it could be a feature in order for the user to test things.

**Comment by therealpxc** [comment]
Thanks for the quick reply!

You may have already changed my mind about locking the settings. Maybe our form of ‘locking them’ can be prompting the user to make a read-write copy of the read-only layout, if possible?

PS: Sorry if my initial report was a bit rude. I was still wearing the frustration of discovering the bug, a bit. Now that I've had a chance to play more with Latte and actually save my settings (just using good ol' `chmod` as a workaround), there's a lot about it I enjoy. :-)

**Comment by psifidotos** [comment]
The dialog i dont think is necessary. There is copy option in Layouts editor. Copy function should also make sure that the new file has correct rights

**Comment by psifidotos** [comment]
this is the first batch and now I am thinking if there will be a Lock/Unlock button in settings window. In the screenshot you can see the lock icons indicating read-only layouts.

![issue980](https://user-images.githubusercontent.com/2216474/38778261-b7051c74-40bf-11e8-9eec-0c59b5c1e5b9.png)

**Comment by psifidotos** [comment]
commited as a feature... the user can lock/unlock layouts...

![default](https://user-images.githubusercontent.com/2216474/38956491-6ce092f6-4360-11e8-8a51-1240ae35c4cc.png)
