### ISSUE TITLE
Window title in tooltips

### ISSUE THREAD

**Issue by defue** [psifidotos/Latte-Dock#981]
Hello there!

I have a question or a feature request :-) Currently if "show applets/task title tooltips on hovering" option enabled then Latte-Dock shows a tooltip with application name on app icon hover. If application is closed that absolutely is fine. But if it is open is not informative. Is it possible to show application title bar text instead? For example if one opens Firefox and navigates to google.com page then the title bar text will be "Google - Mozilla Firefox". It is very important for quick navigatation between app windows when windows grouping is disabled. 

I've attached a screenshot of how it looks like in Cairo dock that I am using now. I am planning to replace it with Latte-Dock but it is the last thing that stops me.
![dock](https://user-images.githubusercontent.com/7314657/38616422-a82506e0-3d9c-11e8-983c-e81368d51a27.png)

**Comment by psifidotos** [comment]
It might make sense for single windows to use the window title

**Comment by psifidotos** [comment]
Or I think is better for windows than cant be grouped

**Comment by defue** [comment]
Yes, it would be great to show window title for windows that are not grouped.

BTW I don't understand that grouping thing enabled by default. For example if I open 2 calculators then in order to switch between them I have to make 2 clicks instead of 1 click if not grouped. Is there a way to make app windows not grouped by default in Latte-Dock?

**Comment by psifidotos** [comment]
It is the default case for all icon-only taskmanagers

**Comment by defue** [comment]
Is there a way to make app windows not grouped by default in Latte-Dock? If not can it be implemented?

**Comment by psifidotos** [comment]
It can be implemented but you will have to open a new request and in order to enable it you will have to edit the layout file, I am not going to add that option in settings window

**Comment by defue** [comment]
Thanks a lot! I've opened another request for that feature. Do you accept donations to make these features done?

**Comment by psifidotos** [comment]
Not for specific features, only for the project in general, at mvourlakos@gmail.com at paypal
