### ISSUE TITLE
Is TRANSLATORS file, removed?

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#982]
Lately latte's ebuild from git master can't be installed due to a missing file
```
FileNotFoundError: [Errno 2] No such file or directory: b'TRANSLATORS'
 * ERROR: kde-misc/latte-dock-9999::testing failed (install phase):
 *   dodoc failed
```
I have to remove it from the ebuild?

**Comment by psifidotos** [comment]
Yes, it is removed... Translations are offered from kde community, no reason to have a specisl file for contributions

**Comment by Petross404** [comment]
Thanks
