### ISSUE TITLE
Some applets are using Latte heuristics even though they shouldnt

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#983]
Latte heuristics is a way for Latte to solve a plasma limitation. Plasma applets most of the time are using PlasmaCore.IconItem in order to be shown in the panel. But for PlasmaCore.IconItem when the icon size is lower of 64px. the parabolic animation breaks.

So Latte heuristics are searching in the applet code in order to find that icon and when they do so overlay over that applet a Latte IconItem and hide the applet below it.

That can succeed for the applets that specific heuristics are used but for the general case it might be better to disable it.

**Comment by psifidotos** [comment]
A solution should also acknowledge that Latte is automatic shrinking applets if the dock size reaches maximum length so an applet can have applet size greater and lower than 64px. at all its life cycle.

For applets that are always lower from 64px
size the plasma solution isnt optimal for Latte because that can break visual consistency with surrounding applets.

**Comment by Zren** [comment]
And more specifically in the last update of Present Windows Button, it will [use this logic](https://github.com/Zren/plasma-applet-presentwindows/blob/master/package/contents/ui/Main.qml#L51)
 to use pager like code for the Unity7 skin. So it's not using AppletIcon in that case.

**Comment by psifidotos** [comment]
I cant test the plasmoid yet, I will the next days.

My guess is that identifies the IconItem it AppletIcon from the generic heuristic code.

The thread is if the applet developers would prefer a specific way to inform Latte if they are parabolic effect capable or Latte should workaround for each applet.

Now that Latte has momentum I think I will disable Latte heuristics for all applet

**Comment by psifidotos** [comment]
except those that Latte has specific identical code for them. So for each applet its developer should support or not the parabolic effect properly.

**Comment by Zren** [comment]
Ah, kinda like a `property bool disableLatteParabolicIcon: true` in the `main.qml` that you can look for?

```
Item {
     id: main
     property bool disableLatteParabolicIcon: true // Don't hide compactRepresentation in Latte
}
```

**Comment by psifidotos** [comment]
Sounds good idea! In that way the generic Latte heuristic code could still be used for all applets except those that this variable is set. I will test it in the weekend to confirm.

**Comment by psifidotos** [comment]
@Zren how about adding also in the same way a containment identifier for applets that want to be Latte perfect when they are added in Latte
e.g.

```qml
Item {
     id: main
     property bool isInLatte: false // the applet is found in a Latte containment
}
```
**OR**
```qml
Item {
     id: main
     property string containmentType: "" // when in Latte this is adjusted to "org.kde.latte.containment"
}
```

**Comment by Zren** [comment]
A property that Latte sets if it sees it? Nice idea. `appletinterface.h` doesn't have anything like that so it might be useful. Probably don't need to worry about conflicts with plasma since everything is prefixed with `Plasmoid.blah:`. `containmentType` is an attempt of creating a standard? Probably better if `plasmoid.containment.id` was exposed by plasma, so:

I lean towards `isInLatte` since the developer will just need to create another property doing a string comparison on `containmentType`.

**Comment by psifidotos** [comment]
@kupiqu I played around with present windows applet even before the above commits. But I couldnt find any broken behavior with Latte.

What is the experience in your system?

**Comment by psifidotos** [comment]
> The only issue is the invisible icon. According to the video it should be a dynamic icon showing the number of virtual desktops in the system... This is what I don't see. I see no icon at all

strange... I didnt fall under such issue... I suppose the last commits will fix this for your system also when you update to newer Latte version and @Zren updates its applet code. If it doesnt open a different issue to track it down.

**Comment by kupiqu** [comment]
Sounds good

**Comment by Zren** [comment]
I can't reproduce in 1.7.4 either (https://streamable.com/geqgd), but I've added the new property to disable things in present windows button v6.

**Comment by psifidotos** [comment]
nice!
