### ISSUE TITLE
Parabolic animation broken after systen update

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#984]
Heuristic animation broken **despite the absence of separators**
Yesterday I did not have this series of defects, then after a **zypper up** here is what I get by rebooting the system...
[BottomDock_2018-04-13_000529.zip](https://github.com/psifidotos/Latte-Dock/files/1905202/BottomDock_2018-04-13_000529.zip)
[BottomDock_2018-04-13_000529_SlowMotion.zip](https://github.com/psifidotos/Latte-Dock/files/1905185/BottomDock_2018-04-13_000529_SlowMotion.zip)
[lattedockrc.txt](https://github.com/psifidotos/Latte-Dock/files/1905198/lattedockrc.txt)
[Video.layout.latte.txt](https://github.com/psifidotos/Latte-Dock/files/1905197/Video.layout.latte.txt)
![screenshot_20180413_003855](https://user-images.githubusercontent.com/24593950/38707768-0caebc7a-3eb3-11e8-8e0a-020678ac06f6.png)

**Comment by psifidotos** [comment]
You mean parabolic animation?

**Comment by psifidotos** [comment]
Arent you installing Latte by yourself? The zypper up you mean that by updating your system it happened this?

I suppose this happens only with folderviews?

**Comment by JenaPlinsky** [comment]
> You mean parabolic animation?

Yep

> Arent you installing Latte by yourself? The zypper up you mean that by updating your system it happened this?

The command that I have given, to update my system, I do not think it has altered the master branch downloaded and installed manually by **github,** right ?

```
mio@linux-18t9:~> latte-dock -v
lattedock 0.7.79
```



> The slow motion video didnt open in my system

Strange, I've just downloaded it and launched it with DragonPlayer and it works fine

**Comment by psifidotos** [comment]
I watched it...

I dont have any idea why this occurs...

Is this your current system  behavior at all times?

**Comment by JenaPlinsky** [comment]
> Is this your current system behavior at all times?

Now after a new update ... I do not observe the problem mentioned above ..... 
it would seem therefore, not a Latte problem

**Comment by JenaPlinsky** [comment]
The problem mentioned in this thread is still present and does not seem to depend on the latest commits and perhaps not even from the latest plasma updates.
This, quite often happens, after a prolonged use of Latte, as if, something degenerates, as you use plasma, I notice this, since basically, **I have the habit of never turning off the laptop** and the times that the problem is highlighted **if I turn off and restart the laptop, the problem disappears** and the animation flows smooth as if nothing were the feeling is as if the cache or any other calculation, with the passage of time remained dirty.

I think it is very complicated both to reproduce and to fix
- the flag relating to the automatic restriction of the dock is not involved in the issue
- I tried to change the Intel friver 2D rendering method from SNA to UXA but nothing changed.

**Comment by psifidotos** [comment]
No prob... I will leave it open for the future... Personally my Latte involvement has been reduced a lot, I will just focus in maintainability and things to just.work... New blood must appear...

**Comment by psifidotos** [comment]
from today all new or unclosed issues should be reported to: https://bugs.kde.org/
