### ISSUE TITLE
The #1 hotkey label is smaller than the others

### ISSUE THREAD

**Issue by trmdi** [psifidotos/Latte-Dock#985]
Look at the picture:
![image](https://user-images.githubusercontent.com/11857205/38715942-642e776a-3f08-11e8-9366-5a326621d58f.png)

I'm using the https://github.com/psifidotos/Latte-Dock/commit/745b9ea07554cda9d71d10e6b937d15a90da4dde version.

**Comment by psifidotos** [comment]
What is your applets size?
