### ISSUE TITLE
background size slider going bonkers

### ISSUE THREAD

**Issue by tofuhead** [psifidotos/Latte-Dock#987]
The slider for background size is jumping all over the place when dragging, and showing veeery precise decimals.. 
![latte2](https://user-images.githubusercontent.com/8156935/38731464-f863315e-3f22-11e8-9bb8-f268a392c0a4.png)

This is self built Latte (master), on a Kubuntu 17.10

**Comment by psifidotos** [comment]
Because ubuntu is stuck with qt 5.9 the Sliders in settings window was updated to a  Latte specific fork from PlasmaComponents3.Slider I will check it out where that broke for Background size

**Comment by psifidotos** [comment]
I cant reproduce that... 
The slider values are set as:
```

                            from: 0
                            to: 100
                            stepSize: 5
```

does this occur at all cases? even at new default layouts?

**Comment by psifidotos** [comment]
what is your plasma theme?
