### ISSUE TITLE
unnecessary tooltip for spacer

### ISSUE THREAD

**Issue by tofuhead** [psifidotos/Latte-Dock#988]
you wanted reports of inconveniences... so here's a little that caught my eye. 
there are tooltips for spacers! :) 

![latte1](https://user-images.githubusercontent.com/8156935/38731531-52e55116-3f23-11e8-9fad-4d705e036741.png)

**Comment by psifidotos** [comment]
Oh... good catch

**Comment by psifidotos** [comment]
what panel spacer is that one? is that the plasma one?

**Comment by tofuhead** [comment]
it's called "panel spacer"..  so yes might be something older.. I've been using Latte Dock quite somewhile now and it's possible there are some legacy stuff.., I tried adding new on straight from latte dock config window, and that doesn't show tooltip.

**Comment by psifidotos** [comment]
> it's called "panel spacer".. so yes might be something older.. 

ok no prob
