### ISSUE TITLE
Is there a way to reload the layout assigned to the to the underlying  activity ?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#989]
![screenshot_20180414_190053](https://user-images.githubusercontent.com/24593950/38770646-5c117a5a-4016-11e8-8b2e-ec40549a6a9d.png) 

After loading a specific layout, it would be comfortable to have the possibility to reload the layout assigned to the to the underlying  activity ... but it is not present among the proposed items

maybe avoiding to show all layouts but showing only the current one

ex. "Gaming" layout is missing
![screenshot_20180414_185856](https://user-images.githubusercontent.com/24593950/38770649-66dc063a-4016-11e8-9d7f-924c91bf2774.png)

**Comment by psifidotos** [comment]
> ex. "Gaming" layout is missing

You must enable "show In menu" for that layout in layouts editor
