### ISSUE TITLE
Option for adjusting (if wanted) the total length of the latte dock panel

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#99]
In addition to the alignment, I would like to adjust the total length of the latte dock panel.

See the picture below: In this case I would like to adjust the length of the top panel so it does not overlay the left panel.

<img width="1280" alt="screenshot_20170127_115235" src="https://cloud.githubusercontent.com/assets/3875196/22379402/39a47b3e-e487-11e6-9311-3b5d21fbc4c6.png">

Please note that this is not about setting the maximumLength, instead I would like the size to be fixed, so I can use the autofit option of the "active window control" applet (it may be useful as well for the global menu in plasma 5.9).

What I'm requesting is to either set the length dynamically, as it is now (default option), or fixed, for the reasons given above.

**Comment by psifidotos** [comment]
> Please note that this is not about setting the maximumLength, instead I would like the size to be fixed, so I can use the autofit option of the "active window control" applet (it may be useful as well for the global menu in plasma 5.9).

these are two separate things...
1. in order for the dock to have a fixed size other than the screens maximum a maximumLength set by the user is needed
2. "so I can use the autofit option of the "active window control" applet", this could be a bug for this applet. It could be easily solved if the applet had set a minimumWidth or Height...

**Comment by psifidotos** [comment]
> "so I can use the autofit option of the "active window control" applet", this could be a bug for this applet. It could be easily solved if the applet had set a minimumWidth or Height...

Ok, I tested the applet...
I think that you must describe me what you want from the "active window control" applet to do and it doesnt with the current implementation of Latte.
Except the Fill Width choice all other size choices are working ok in my system and this is normal based on how Latte treats its applets...
What do you need the FillWidth choice, what do you want to achieve?

**Comment by psifidotos** [comment]
@audoban what do you think about the maximumLength mentioned?

**Comment by psifidotos** [comment]
@kupiqu, I thought also that concerning maximumLength we could just add an option to not overlap with neighbour docks. So a dock from the configuration window would be able to take into account the neighbour docks for its maximumLength

**Comment by kupiqu** [comment]
yes, I think that last option would probably be the most general solution (I mean that it would help in other situations as well) :)

**Comment by psifidotos** [comment]
@kupiqu I went for maxLength setting through percentage... you can try it at master branch through the configuration window...

**Comment by psifidotos** [comment]
![maxlength1](https://cloud.githubusercontent.com/assets/2216474/22397709/76de3482-e580-11e6-933a-8aa14a7be191.png)
![spectacle t11776](https://cloud.githubusercontent.com/assets/2216474/22397718/a89e236a-e580-11e6-9920-ab459de848db.png)

**Comment by kupiqu** [comment]
Unfortunately I don't see a way to solve my issue with current implementation.

If I don't set fill width in active window control, then the length of the latte panel will increase/decrease according to the number of icons in systray, date, weather city name, etc.

If I set the width to fill the latte panel, it disappears.

I see two potential ways to solve the issue:

1. latte panel allows to specify a length (I think you are against this option, which I think I understand)

2. get a proper minimum length for the active window control, so fill width will use that length in latte dock

do you agree or see more options?

**Comment by kupiqu** [comment]
On the other hand, what you implemented is great, so multiple latte dock panels do not interfere with each other :)

**Comment by psifidotos** [comment]
@kupiqu I can not understand the problem you are describing

> If I don't set fill width in active window control, then the length of the latte panel will increase/decrease according to the number of icons in systray, date, weather city name, etc.

1. why? have you locked all these applets to not animate on zoom hovering?

> latte panel allows to specify a length (I think you are against this option, which I think I understand)

2. to specify a length for what thing?

**Comment by kupiqu** [comment]
Let me try to clarify it with a bit of a different perspective... (I think it is difficult to show with screenshots as it is sth dynamic)

This is not about zoom on hovering, I don't have any. This is about the applets increasing/decreasing in horizontal length (more or less icons based on context in systray), day of the week, different cities in the weather applet have different length, etc. This makes the latte panel to increase or decrease its length, which I want to avoid.

There are two ways to avoid it:

1. the latte panel sets a fixed size and I use fit width in current window control, so it this applet compensates for the change of length of all others.

2. a second option (to set a minimum size for current window control that is long enough) would perhaps solve the issue as well

**Comment by kupiqu** [comment]
Actually, I don't think the second option would compensate for a growing length of the latte panel. This leaves me just with option 1, I guess :/

**Comment by kupiqu** [comment]
Ok, I found the way! :) 

By using justified alignment. Forgot that it works now (i.e. this latte panel does not interfere my second latte panel because of your implementation!)

**Comment by psifidotos** [comment]
> By using justified alignment

Ok!!! I thought you had set that from start!!!

**Comment by kupiqu** [comment]
I did and then I changed it, to test with different options. It doesn't work yet as I would like though, but I'm playing a bit with the source code of current window control to see if I can "fix" it

**Comment by psifidotos** [comment]
In my system was working just fine with the following,

Fill mode for Latte, the active window was the last in the left side and i had set a fixed size for active window applet from its configuration window

**Comment by kupiqu** [comment]
Do you mean fill mode = justify, right?

I have that exact configuration, but if I set fixed size for active window, then I have either of these two situations:

1. small fixed size: active window does not take benefit from all available space

<img width="1280" alt="screenshot_20170128_162035" src="https://cloud.githubusercontent.com/assets/3875196/22399932/f4899f08-e575-11e6-93d1-2b786b152398.png">

2. adjust fixed size to available one: any change in other applets makes the active window take more space than available, so all font and icon sizes become scaled down. Also, unfortunately, this does not reverse by manually decreasing the size of active window, so latte needs to be restarted

<img width="1280" alt="screenshot_20170128_162158" src="https://cloud.githubusercontent.com/assets/3875196/22399945/362a5ea2-e576-11e6-9a35-1d80bdd591b9.png">

**Comment by psifidotos** [comment]
> Do you mean fill mode = justify, right?

yes...

> adjust fixed size to available one: any change in other applets makes the active window take more space than available, so all font and icon sizes become scaled down. Also, unfortunately, this does not reverse by manually decreasing the size of active window, so latte needs to be restarted

So if i got it right you want the active window applet to use all the available space but without auto shrinking the icon size. This unfortunately is not the applets fault...  Latte wasnt designed for such case... I ll have to think it over how can this be supported, it needs a Gridlayout implementation instead of a Grid one, and that must not break at all the current implementation...

**Comment by kupiqu** [comment]
Yes, I understand.

I hope this can be implemented at some point anyhow. I'd love to see the latte panel fitting together optimally with the active window and global menu applets :)

**Comment by kupiqu** [comment]
Just for the case somebody could be interested... The best way it works for me for now is to use center alignment in latte dock, and then use a fixed size for active window control that is small enough so the total size of the latte dock never exceeds what you would like or expect.

**Comment by psifidotos** [comment]
Can you send also a screenshot as a reference?

**Comment by kupiqu** [comment]
Sure:

![image](https://cloud.githubusercontent.com/assets/3875196/22407469/e458d814-e634-11e6-95d4-e13f17072326.png)

**Comment by kupiqu** [comment]
latte dock panel increases and decreases, so the trick is to give a size to active current control that is constrained by how much latte is expected to grow and the minimum size that makes the applet useful

also using this option there is no empty space as it appears with the justify option

**Comment by psifidotos** [comment]
nice !!!
