### ISSUE TITLE
Seg fault opening conf window

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#990]
Docks close and restart, error:

**Application: Latte Dock (latte-dock), signal: Segmentation fault**

Steps to reproduce:
* Right-click on the dock
* Open configuration window

Version `0.7.79+git20180414.0958-0~ubuntu18.04~ppa1`
Kubuntu 18.04 Beta 2
Wayland and Xorg

**Comment by psifidotos** [comment]
Try to clear the cache

**Comment by ssspacez** [comment]
That worked, thank you.
