### ISSUE TITLE
Pinned menu is not launched using keyboard shortcut

### ISSUE THREAD

**Issue by ssspacez** [psifidotos/Latte-Dock#991]
When I press 'Super key' after pinning the **menu** to the dock(or panel), nothing happens, the pinned menu icon is not activated. I checked and there's no shortcut inside the menu's config window, it's a new menu with empty shortcut.

Possible solution:
Match the **same hotkey** the user configured for the menu, **or use the system default**(Super key).

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-can-i-use-my-super-key-to-open-the-app-launcher

**Comment by ssspacez** [comment]
This FAQ is interesting, consider in the future creating a **( ? ) button** that links to it and put the button inside the config window, or when you right-click the dock... or make it offline like a manual window. 

This can save some time, people will ask less questions/bugs.
