### ISSUE TITLE
Latte cannot be closed anymore

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#992]
Using git version here.
Since some time now I cannot close latte-dock over preferences menu anymore. When I hit the close button the preferences menu disappears but latte keeps running.
This issue affects all my machines (Arch Linux).

**Comment by psifidotos** [comment]
can you show me the preferences menu you are describing?

**Comment by marhkb** [comment]
the close button bottom right
![latte-close](https://user-images.githubusercontent.com/3630213/38778139-bb0f1c44-40b4-11e8-80f6-19d7f05beb35.png)

**Comment by Sporif** [comment]
Yeah, that button used to exit latte-dock, but it was changed to close (#934). 

You now need to use CTRL+Q to exit while in the general Latte settings menu or the quit button in the menu bar of said menu (File > Quit Latte), which can be accessed via right-click latte dock > Latte Options > Layouts > Configure...
Or click the Latte icon at the top left of the dock/panel settings menu.

**Comment by psifidotos** [comment]
yep that was intentional...

In my system I use:

`Meta+W   ->   Ctrl+Q`
