### ISSUE TITLE
Apps pinned by dnd from a launcher(kicker), when launched, have an additional launcher/with running indicator

### ISSUE THREAD

**Issue by worldofpeace** [psifidotos/Latte-Dock#993]
I noticed this in NixOS (dolphin is affected in this image)
![38772194-ff851a38-3ffe-11e8-93f1-4af4f11597a7](https://user-images.githubusercontent.com/28888242/38785275-e36e3bde-40eb-11e8-8c3c-b23dbabb5e98.gif)

#### Steps to reproduce

1. Pin an app by dragging it's icon from a launcher
2. :rocket:  it
3. See an additional indicator appear for the running app(another icon with running indicator)

#### Upon investigation into the .config/latte/*.layout.latte files I found this interesting behaviour.

If I drag an app from a launcher like kicker and pin it we get this:
```
[Containments][1][Applets][2][Configuration][General]
launchers59=file:///run/current-system/sw/share/applications/firefox.desktop
```
In nix this desktop file is just a symlink to somewhere in the nix store.
Typical permissions of these files would be .r-xr-xr-x. Elsewhere they're usually .rw-r--r--.

But If I open the app and pin it we get:
```
launchers59=applications:firefox.desktop
```
When this is in the config this behaviour disappears.

I understand on other platforms this works as expected either way.

I'm also seeing warnings in debug output like:
```
latte-dock-0.7.3/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/TaskDelegate.qml:959: Unable to assign [undefined] to int

Empty filename passed to function
```

###### System Info
- system: `"x86_64-linux"`
- host os: `Linux 4.14.34, NixOS, 18.03.132006.6ba9b9c9fa2 (Impala)`
- latte-dock version: `0.7.4`

**Comment by psifidotos** [comment]
This is plasma libtaskmanager responsibility. Do you have the same issue with plasma taskmanagers?

**Comment by worldofpeace** [comment]
> This is plasma libtaskmanager responsibility. Do you have the same issue with plasma taskmanagers?

Just looked. 100% sure that's it.
Lol I was hoping this was going to be easy. I guess Nix needs to patch plasma-workspace.
Thanks for pointing me in the right direction :+1:

**Comment by psifidotos** [comment]
no prob. If you manage to create a patch, it might be a good idea to commi it also upstream through plasma review process.
