### ISSUE TITLE
Latte doesn't keep entries/Programs

### ISSUE THREAD

**Issue by jonabw** [psifidotos/Latte-Dock#994]
Hello,
When I reboot Mint KDE 18.3, Latte-Dock always just starts with the clock. All other programs disappeared somehow. I tried to reinstall it and switched the kernel, nothing helped.

Latte-Dock version 0.6.2-0

Please help me!

**Comment by psifidotos** [comment]
1. close Latte
2. remove all latte settings files:` ~/config/*latte*`
3. start Latte

**Comment by jonabw** [comment]
Man thank you so much. I know that this might be a little problem for you, but it was driving me nuts!
Thank you so much!

**Comment by psifidotos** [comment]
I suppose your removed Latte plasmoid by accident... :) it is the plasmoid that shows the tasks...
