### ISSUE TITLE
Wayland and move window to edge of screen to move to another virtual desktops

### ISSUE THREAD

**Issue by alexjp** [psifidotos/Latte-Dock#995]
Hi,

I am testing latte-dock with wayland ( kubuntu 18.04 with stable kubuntu ci packages ).

I have the setting to "move window to next virtual desktop my dragging it to edge of screen". When I do this, latte-dock always dies.

If not clear info, I can do a video.

Thanks !

**Comment by psifidotos** [comment]
> If not clear info, I can do a video.

I dont think you can do a video in wayland :)

> I have the setting to "move window to next virtual desktop my dragging it to edge of screen"

where is that setting?

**Comment by psifidotos** [comment]
one more thing... 

1. does that also occur for the Default layout?
2. if you use a plasma panel with the same plasmoids it doesnt crash plasma?

**Comment by alexjp** [comment]
> where is that setting?

https://imgur.com/a/ok3ib
The option: "Switch desktop on edge"

**Comment by alexjp** [comment]
Going to test the other situations, but it doesn't happen on Xorg, only on Wayland.

**Comment by psifidotos** [comment]
the thing is to test if that is a plasma issue or an applet issue...

e.g. I know that pager plasmoid creates crashes under wayland

**Comment by alexjp** [comment]
I think i found the problem: 

![screenshot_20180416_223613](https://user-images.githubusercontent.com/85806/38836606-b5e98804-41c6-11e8-9997-8b61aeedca96.png)


I was having trouble making it crash again on wayland, when i remembered i was using chrome apps when it happened ( i almost always have chrome apps running ).

It doesn't seem to detect chrome apps like in xorg, and switching desktops makes it crash

**Comment by alexjp** [comment]
forgot to mention, I use chromium apps and I have chromium apps launchers in the tasks applet of latte-dock.

**Comment by psifidotos** [comment]
Ok... are you using Active Window Control?

**Comment by alexjp** [comment]
No. Nothing fancy, Just latte-dock and some chromium app launchers.

My applets are just "menu launcher", "tasks", "systray"

**Comment by psifidotos** [comment]
Do you have a backtrace?

**Comment by alexjp** [comment]
> Do you have a backtrace?

No i don't, sorry. I am using latte-dock package from kubuntu stable-ci.

I can send you the full log, running latte-dock with -d --mask

[latte.log](https://github.com/psifidotos/Latte-Dock/files/1917507/latte.log)

does it help ?

**Comment by psifidotos** [comment]
nope... are you using v0.7.4 or master version?

**Comment by alexjp** [comment]
think its master:
`
Package: latte-dock
Version: 0.7.4+p18.04+git20180415.2328-0
`

I am kinda new to kubuntu.

**Comment by psifidotos** [comment]
Lets try differently, if you close Latte and you add the default plasma panel and add the chromium launchers etc. Does that crash occurs?

**Comment by psifidotos** [comment]
For the Latte version run in command prompt, latte-dock -v

**Comment by alexjp** [comment]
Version: 

```
alex@alex-kubuntu-desktop ~  $ latte-dock -v
lattedock 0.7.4

```

Gonna try with default plasma panel next

**Comment by psifidotos** [comment]
You are using Latte stable and probably in wayland it isnt stable enough. Wayland in 0.7.x series is considered a technology preview. In master version that is going to be v0.8.x in  a few months contains many fixes for Wayland.

**Comment by alexjp** [comment]
strangely, with default kde panel it doesn't crash.

I also added "taskbar icons only" to the mix and nothing, doesn't crash.
I then loaded latte-dock, moved things around, latte-dock crashed but plasma panel didn't.

Also, seems "sending window to previous/next desktop" doesn't crash it. What makes it crash is moving window to the edge of the screen, making latte-dock go into autohide, and change window virtual desktop ( through that setting i showed in first image ).

**Comment by alexjp** [comment]
> You are using Latte stable and probably in wayland it isnt stable enough. Wayland in 0.7.x series is considered a technology preview. In master version that is going to be v0.8.x in a few months contains many fixes for Wayland.

Sorry, just tested with: https://launchpad.net/~rikmills/+archive/ubuntu/latte-dock/+build/14764110

which uses version: 

` latte-dock -v
lattedock 0.7.79
`

and still happens

**Comment by alexjp** [comment]
doing more tests, and chromium is not at fault. happened also with konsole.

this is not actually important to me right now, since wayland is not yet fully usable for me.

can be marked "for later", especially when wayland allows to record video, so i can do a bug video.

**Comment by psifidotos** [comment]
no prob. Either way without a backtrace and without a way to reproduce such issues cant be identified and fixed
