### ISSUE TITLE
Unable to launch gnome-terminal from latte-dock 

### ISSUE THREAD

**Issue by bigbrett** [psifidotos/Latte-Dock#996]
My default terminal emulator is gnome-terminal, and everything works fine with it on my current DE, however I'm unable to launch it from the latte-dock once I've pinned the application. The icon just bounces and then never opens. Launching from the Plasma panel or any other launcher works, as always.

Running in debug mode gives me the following message: 
`Failed to register: Unable to acquire bus name 'org.gnome.Terminal'`

I am using **lattedock 0.7.4**, installed via pacman. **Display server is X11**

**System details:**

![screenshot_20180417_202356](https://user-images.githubusercontent.com/7547222/38908403-4b78176c-427d-11e8-822c-d6c7a899cd55.png)

I'm a n00b when it comes to debugging dbus issues, so let me know if I should provide some other info.

**Comment by bigbrett** [comment]
Yes, yes, and once it was running I right clicked the active terminal widget and selected "Pin to dock"

On Apr 18, 2018 06:21, Michail Vourlakos <notifications@github.com> wrote:

Can you launch it from your app launcher?

Can you launch it from a plasma taskmanager?

How did you add it as launcher in Latte?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsifidotos%2FLatte-Dock%2Fissues%2F996%23issuecomment-382367425&data=02%7C01%7CBrett.R.Nicholas.TH%40dartmouth.edu%7C71341d754fe94795c1ad08d5a526e8c4%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C636596508889223460&sdata=sHFVTytbkIPH6QVG6LbAab3pGvNREBHfqX6zjxhbXTM%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHMpVi8N-KetpDAQBZkezsxa8T5hsAEtks5tpy_GgaJpZM4TZUom&data=02%7C01%7CBrett.R.Nicholas.TH%40dartmouth.edu%7C71341d754fe94795c1ad08d5a526e8c4%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C636596508889223460&sdata=3CepQCShBkVXNVgiYsBM0cWvRMRhzvJrrjNsILaMLn8%3D&reserved=0>.


Can you launch it from your app launcher?

Can you launch it from a plasma taskmanager?

How did you add it as launcher in Latte?

**Comment by psifidotos** [comment]
totally weird... Latte and plasma taskmanagers use the same codepage.... if plasma taskmanager can launch something then Latte should also....

**Comment by psifidotos** [comment]
Can you please show me a screenshot how that launcher looks in a plasma taskmanager and how that launcher after you activate it?

**Comment by bigbrett** [comment]
Oooooh forget the screenshot, heres a gif of the problem in action: 
![desktop-animation](https://user-images.githubusercontent.com/7547222/39224822-581b595a-4806-11e8-8a2c-0de7549cc92c.gif)

**Comment by bigbrett** [comment]
>"now in your video when you are demonstrating the correct launching from plasma panel isnt accurate...."

sorry, I don't understand what you mean here, how can launching from a plasma panel not be accurate? 

> "Latte and Plasma use the same code for this, so you are going to have the same issue with plasma also..."

but I don't have the same issue launching from the plasma panel....


see this next GIF of how I add the program to latte-dock. Is this not how I'm supposed to do it? 
![desktop-animation](https://user-images.githubusercontent.com/7547222/39342296-9bfadc38-4994-11e8-9033-92598203f0c9.gif)

**Comment by trmdi** [comment]
I can confirm this issue. I see this happens:

▶ grep -i gnome Unity.layout.latte  

When I pin it:
```
launchers59=file:///usr/lib/gnome-terminal-server?iconData=iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAFrklEQVRoge2ZvW8cRRjGn7kPny_n89qRYuqIOuFvALrEHwgHiIKCSGEokoZ_IaJC6SggWEK2-FZsHMctKUmPSxS5QNztmcJS4jvfnW9vXoqdmZ2dj921o0iR4ik89n6883vf531m987A2Tgbr_dg5oG79-7tlkvlSwCBCAAIJE8SqVmeUz_lD0rdEV8n75NnVBhKzfL-ZClKViAgisa7X3159y2dt2Im8PfTp5e6vZ4dXIM2ZwWtzSAJa88WvH5fKr62NoDm1NRlk9dKQMG7oPLgXUn7kiiSmJYgQHj-_NDEtRMoDJ-5cHaChdTxrJ2bgAs-3Rb5quh976yoDz5rbRU_TwEY8mb0uRW8YFuc2E_SD0USeBXM6mJQ9-YqUAT-JZs1iyE3AVcv-xd-eWZ1FtBhArcCr4RZ3QU0R8k64oAnV1AtuIR9Y-4CvrhzG81mM4llXp8LL9pOtR_JqjoVsBLI3EI9ppUVv768jDcvXsTtlRU0Gg2HYjGIDqYD-55BegELKGD0sph9vawUIMLq-jr-abUwN3cBdz7_DM3pKc0rSaIpVQx1LXhpbnV9ngIatPpbACTPiHT1ZCLdwy6-_vY-_m21cX52Fiu3bmG62UzHLGpWg8HnA1sBTerUTkP5wQlA7_AQ36yuotWOk_j0k5toTjX9fjJ85Spcqu3yFbCDmmb1PlnF3O128d33a2iFIc7PzuLmxzfQbEyd0KxGayn18hQoYFY1S384zNrrdbG2to5WGGJ2JsCN6x9iqtEoZlbH7pUqWKYCBrTLrNlVSxbr9o7ww48_Iex0EMzM4KMPrqHROJdvVt_ajuE0sWuL083qC-4ya693hJ9_-RWdzj6mgwDXlt9Ho3GukJ9S6hM5k3C2kL0LeYK7zO0wa--oj98ePMD-_n-Ynp7G0tIi6vW6Fr_AM0KyGcPxOp1c-KKvwQlU_DvnY0RRhH6_j6OjHjgnMGZvHN61LXzP67QVQIMyzZoK7kgQBEzWJ_He0iKCIEAYhtjY2MSwPwBjDBO1Wm7h9HVyE0j1nAHnDe5RhQio1yextLig4Dc3fsdwOACIwEEYDgeoVmuxEuY6zsIVUSDLTJnBDfjJGhYX5hEEATphiM3NLQyHAxCn-Asd0Vqj4yEqExPxdzw5a5vDswsZAQqaNQVfq2FhYR7BzAw6nY6A76fgZYtxzjEaDsE5z9_GcxXQoU9jVhDqtUnMLwr4MMTW1kMBD0CYlhEBYCBIIxOi0QiVSgXS2aavXC72fq1yGrNK-KsLV1XPb289xHAwEGuTgAdIZQIQB4gBRByjKEKlXIaUyVonV4FTmhUC_sr8lRi-HeLR9jYGg0EqeRMeFMPHR-Pj42iMcqX8gruQBp1nVqnA2---gyAI0G63sbO9E-82XviYnFi8lrQFE1WOogjlctnBkB7ZT-ICZpXtRER48ucT7O3tYWf7kYCXOxqLeeVm4IRnAp6BiMAI4OOxVcB8BU5gVjP4wcEBHv_xGMfHx0ksisGEZyF7xgcPEn8xiKMnVUBVTcykzb7ENDUAhmq1BiIm4OGGl0JwFu9IJHeeBF55RLC4POB-DmitYbZMkddgVmKo1aoAAzhIsBGIi4pyWSoGxiSU8InglpknBZRX5ClQwKxFXoPBSpjQnq4AoIwg_q3CNKBYJPn_FuYsYKEWKmJWCR2fk61ltx0AVGUSKjFmLpjAy9bxMBT8PCDbyPCA7EMN2gpuJRgXW73nSHhSHZLqd2laV-Fc_e9WoKBZXcF9H4IYgHKlCvnKyRjAxQkTHp7CkSpcemR-uWtvoUj1udX3Et6RPGNAuVQCx1h8kGHKrEwrXNY27jKBpcDoeJQEKGBWBe-pmt52jDEwVkqZVW2zOfBEhCiK8hU4fPZsl3N-WWabwOsVkEGVZtAuSjYMmaBeQfFrnBBS0GoFsxVVuvjLyuBsnI3XfPwPw-dX-dA4uVQAAAAASUVORK5CYII%3D
```

When I drag and drop it from the Application Menu:
```
launchers59=applications:org.gnome.Terminal.desktop
```

**Comment by psifidotos** [comment]
@trmdi please replicate with plasma, it will be the same. Libtaskmanager is responsible for this, not Latte

**Comment by psifidotos** [comment]
He is using single click if he used right click new instance from context menu then same issue would appear

**Comment by psifidotos** [comment]
and one more thing, the user in the video didnt click a launcher but an applet. He has added the terminal shortcut as an applet. If he was doing the same in Latte there wouldnt be any issue.

**Comment by trmdi** [comment]
So this is a plasma bug and someone should report to the KDE devs ?
